### ISSUE TITLE
Config for other version of Chromium

### ISSUE THREAD

**Issue by HariharanSampathkumar** [microsoft/vscode-chrome-debug#1000]
- VS Code Version:
- Log file (set `"trace": true` in launch config):

Steps to reproduce:
=====================
 {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Brave against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}"
    }
=====================
1. i am using brave browser which is a chromium based
2. When i try to run in debug i am getting following erro
Error processing "launch": Error: Can't find Chrome - install it or set the "runtimeExecutable" field in the launch config.

Let me know what should i do to include brave browser for debugging

**Comment by roblourens** [comment]
You can set 'runtimeExecutable' to the path to Brave. I don't know whether it will work or not, no guarantees.
