### ISSUE TITLE
Calling getUserMedia stops chrome instance

### ISSUE THREAD

**Issue by dreamerchandra** [microsoft/vscode-chrome-debug#1001]
I was trying to use `getUserMeida` and whenever I do chrome stops. Neither I can't able to figure out what was the issue nor I couldn't find out any on StackOverflow or Github. 

I remember that providing [use-fake-device-for-media-stream](https://webrtc.org/getting-started/testing) for getting fake streams but I don't know how to provide a runtime args in here.

I had to run through the codebase to check how to provide one. Luckily it took me less than 5 minutes to reach [this point](https://github.com/microsoft/vscode-chrome-debug/blob/aec50a5b4c67870715c6a899c6dc3618d5400d55/src/chromeDebugAdapter.ts#L105). where I understood about `runtimeArgs`.

Before going to codebase I checked [this doc](https://github.com/microsoft/vscode-chrome-debug#other-optional-launch-config-fields). It wasn't clear as it doesn't say anything about what it does and what it takes(vs code IntelliSense helped in what it takes).

[Similar issue but on file input](https://github.com/microsoft/vscode-chrome-debug/issues/938)

So there are two problem
 - Crash on `getUserMeida`. (I'm on mac version `10.15.4` and chrome `80.0.3987.163` VS Code Version:  `1.44.2`)
 - Doc could be a bit clear on what it does (less of a problem more of a suggestion)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-js-debug/issues/400
