### ISSUE TITLE
how to set breakpoint in the chrome browser only

### ISSUE THREAD

**Issue by daron4ever** [microsoft/vscode-chrome-debug#1002]
- VS Code Version: 1.44.2
I want to check the code in the chrome only but when I clicked the 'step' while 'Paused on breakpoint' in the Chrome, the VS code browser displayed everytime I clicked the 'step' button.

Is there anyway to skip the process?

**Comment by roblourens** [comment]
Are you using chrome devtools at the same time? If not I don't understand, please explain more

**Comment by daron4ever** [comment]
@roblourens When I cliked "start debugging" in the VScode, the chrome browser opened and I debugged from the chrome devtools.

**Comment by roblourens** [comment]
Then why are you using the vscode debugger at all? We can't tell if chrome devtools is in use, so we can't change behavior based on that.
