### ISSUE TITLE
Sourcemap could not be downloaded with error "HTTP GET failed with: 302 Found"

### ISSUE THREAD

**Issue by gnguyen83** [microsoft/vscode-chrome-debug#1003]
We updated our project and several framework/packages in it (Angular, PrimeNg, Typescript, etc.). After that, during debugging all breakpoints are disable and show the message "Breakpoint set but not yet bound". In the log file "vscode-chrome-debug.txt" I recornized that the source map main.js.map could not be downloaded with error "HTTP GET failed with: 302 Found". But I could open the download link direct in Chrome. Debug with Chrome DevTool works. If I create a new Angular project, this also works. Any ideas which problem could cause this issue?

- vscode-chrome-debug Version: 4.12.6
- VS Code Version: 1.44.2
- Angular Version: 9.1.2
- @angular-devkit/build-angular Version: 0.901.1
- OS Version: Windows 10
- launch.json:
{
	"version": "0.3.0",
	"configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "debug in chrome",
			"url": "http://localhost:3100",
			"sourceMaps": true,
			"trace": true,
			"webRoot": "${workspaceFolder}",
			"sourceMapPathOverrides": {
				"webpack:///./*": "${workspaceFolder}/*"
			},
			"skipFiles": [
				"${workspaceFolder}/node_modules/**/*.js",
				"${workspaceFolder}/lib/**/*.js"
			],
			"internalConsoleOptions": "openOnSessionStart",
		}
	]
}

- Log file (set `"trace": true` in launch config)
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/4535236/vscode-chrome-debug.txt)
:

**Comment by roblourens** [comment]
Could you try this with our new debugger implementation? https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by gnguyen83** [comment]
Thank you for your response. Sorry that I didn't provide enough infos to this issue. In this project we use ASP.NET (not Node.js) for backend and Angular for frontend. We have problem by debugging the typescript files of Angular components. We don't use JavaScript Debugger, only Debugger for Chrome.

**Comment by roblourens** [comment]
The new javascript debugger can debug Chrome, and it will replace Debugger for Chrome soon. I think it fixes this issue already, if not, I will fix it over there.

**Comment by gnguyen83** [comment]
I installed the extension but couldn't configure it like in the guideline. The config `debug.chrome.useV3` is unknown.

![Code_2020-04-30_11-41-24](https://user-images.githubusercontent.com/24679666/80696550-d555e780-8ad7-11ea-8c0a-6571cec7f62f.png)

**Comment by roblourens** [comment]
Are you using the latest version of the Debugger for Chrome extension? Also, you can ignore that and just change the launch config type to `pwa-chrome` if you want.

**Comment by gnguyen83** [comment]
Thank you. Now I can debug my project again. But website starting take much longer than before. With Chrome DevTool I saw, that many js files were opened and closed (see attachment). Maybe this is already known or the new debugger just need more time to process?

![2020-05-01_21-52-15](https://user-images.githubusercontent.com/24679666/80837001-3542b000-8bf6-11ea-8ee2-64e7b3bed7c8.gif)

**Comment by jaskiratr** [comment]
Thank you @roblourens 
> The new javascript debugger can debug Chrome, and it will replace Debugger for Chrome soon. I think it fixes this issue already, if not, I will fix it over there.

![image](https://user-images.githubusercontent.com/8619877/80845100-44196a80-8bd6-11ea-9b77-ce08a4358588.png)

This also solved breakpoints jumping around. It was occurring for a Nuxt.js app, and I was trying to attach the debugger to an already open webpage on chrome. 

There are some intermittent issue with breakpoints not updating or vscode debug won't stop or de-attach. Assuming, it is due to preview build.

**Comment by roblourens** [comment]
@jaskiratr I'm glad it helps, I would appreciate you filing a new issue for the new issues you are seeing in https://github.com/microsoft/vscode-js-debug/issues

@connor4312 fyi, see @gnguyen83's issue above

**Comment by connor4312** [comment]
The issue Giang is seeing is the same as https://github.com/microsoft/vscode-js-debug/issues/431. I will be looking to fix it this month.

**Comment by connor4312** [comment]
Closing since the new debugger fixed this since June
