### ISSUE TITLE
Co-Debugging with Live Share Extension not working from within Remote Container

### ISSUE THREAD

**Issue by nibtime** [microsoft/vscode-chrome-debug#1008]
I was trying to get co-debugging to work with the excellent [Live Share Extension](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) inside a remote container

However, this does not work yet, since the Chrome Debug Extension runs in `ui` mode per default and the Live Share extension runs in `workspace` mode inside the Remote Container, so it is currently no possible to co-debug in this specific scenario. It would be nice if that would work out of the box somehow in the future (I have no idea how feasible that is though).  However, I found a workaround, so you can get co-debugging anyway. I'd like to document it here since I didn't find any other documentation that covers this particular problem.

The basic idea is tunneling debug traffic via SSH from a Chrome instance on the host OS into the Remote Container and force the Chrome Debug Extension to run inside the Remote Container to make it work with Live Share. It doesn't involve any networking changes that could potentially break things between Docker and host OS. Just an SSH server running inside the Remote Container, that's it.

The following instructions assume Docker Desktop for Windows and Win10 as the host OS, however, this should be doable with other host OS in a similar fashion. 

1. In your VS Code user settings, add `"msjsdiag.debugger-for-chrome": ["workspace"]`. This will force the Chrome Debug Extension to run inside the Remote Container

2. Create a debug task  `"type": "chrome"` and `"request": "attach"`. Choose an arbitrary available `<remote-debug-port>`

3. Start an SSH server inside your Remote Container and forward the `<container-ssh-port>` (usually 22) to an arbitrary available `<localhost-ssh-port>` on the host OS. Later you want to connect from your host machine to the Remote Container with SSH. Append the public key you want to use for that to `~/.ssh/authorized_keys` in the Remote Container file system

4. Select a Chrome Profile you want to use for Remote Debugging. Create a Shortcut for Chrome and add `--profile-directory="your profile" --remote-debugging-port=<remote-debug-port>` as flags to the Chrome executable

5. Get [PuTTY](https://www.putty.org/). Create a session profile to connect into the Remote Container with SSH. Since the SSH server has been forwarded from the container to the host earlier, you can connect via `localhost:<localhost-ssh-port>`, so you do not have to deal with any IP addresses and networking issues between Docker and host. Open a tunnel for the `<remote-debug-port>`. Select the corresponding private key for authorization.
<details>
<summary>PuTTY auth</summary>
<img src="https://user-images.githubusercontent.com/52962482/81307800-56d1ea80-9081-11ea-98c3-3b7c376934d7.png" />
</details>
<details>
<summary>PuTTY tunnel config</summary>
<img src="https://user-images.githubusercontent.com/52962482/81307078-816f7380-9080-11ea-9680-30bec4a56548.png" />)
</details>

6. Connect with PuTTY to the SSH server. Now there is a tunnel open for `<remote-debug-port>` (Chrome remote debugging traffic) at localhost to `<remote-debug-port>` inside the Remote Container.

7. Start Chrome and navigate to the URL you want to debug, e.g. `localhost:3000` for React apps.

8. Start the `"request": "attach"` task defined in step 2 to start your debug session. With this session, co-debugging works.

**Comment by roblourens** [comment]
Thanks for the detailed issue, you're right that it doesn't really work with Debugger for Chrome. However, we have a new implementation of the chrome debugger which is in preview now, and should work out of the box in this scenario.
