### ISSUE TITLE
Need help setting up debugger

### ISSUE THREAD

**Issue by wpaul-magicleap** [microsoft/vscode-chrome-debug#1009]
- VS Code Version: 1.44.2
- Log file (set `"trace": true` in launch config): none created?
- MacOS Catalina

I'm trying to debug Perfetto (https://www.perfetto.dev/#/).  The local HTTP server is running at http://localhost:10000.  I am able to use the Chrome dev tools debugger.  I'm not a web developer and not used to Chrome dev tools, so I find the debug experience in vscode more like what I'm accustomed to.  I went through the readme and thought I had created my launch.json correctly, but when I try to launch it just sits there.  There's an indeterminate progress indicator under the run toolbar but it never completes.  The status bar remains blue (I think it turns orange once the launch completes?).   I get nothing in the debug console, even if I enable trace in my launch.  In fact, the debug console still says "Please start a debug session to evaluate expressions.".  So it seems the launch simply isn't completing.  I've tried both with Chrome running and the page open, and with Chrome closed.  My guess is it's trying to launch Chrome and is waiting but is never getting whatever event it's waiting for.  Without the log though I'm not sure how to debug this.

Any help would be greatly appreciated.

Here's my launch.json:
`{
	"version": "0.2.0",
    "configurations": [
        
        {
            "name": "Debug Perfetto",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:10000",
            "webRoot": "${workspaceFolder}/../out/debug/ui",
            "preLaunchTask" : "Run Perfetto (Debug)",
            "trace": true
        }
    ]
}
`

**Comment by roblourens** [comment]
It's likely that your preLaunchTask is not set up correctly and the task system doesn't think that it has completed. Can you try starting that manually then running the launch config?

**Comment by wpaul-magicleap** [comment]
I'm a little embarrassed I didn't figure that out myself.  That was indeed the issue.  The pre launch task ensures it was built and starts the server, but does not exit.  So it was just waiting for that to end which it never did.  Thanks for the help and sorry for the noise...
