### ISSUE TITLE
Feature Request: Global launch.json if local launch.json doesn't exists

### ISSUE THREAD

**Issue by ryuta69** [microsoft/vscode-chrome-debug#1011]
I repeatedly use same launch.json when I develop node.js application, so it will be helpful if we have global launch.json feature. I think it good to place the global file to `~/.config` maybe?

Then, if global launch.json doesn't exists neither, it will create local launch.json.

If this request is good for others, I will create PR.

**Comment by roblourens** [comment]
This actually exists, you can add a `"launch"` object with configurations to your settings.json

**Comment by ryuta69** [comment]
Wow, thank you.

**Comment by ryuta69** [comment]
@roblourens 
Ah, sorry to ask you again, but there is no document nor information about it.
Would you tell me some example?

**Comment by roblourens** [comment]
@isidorn is there documentation for this?

**Comment by isidorn** [comment]
Yes, here's the link
https://code.visualstudio.com/docs/editor/debugging#_global-launch-configuration

**Comment by ryuta69** [comment]
@isidorn 
Thank you very much!
I love this plugin for long time and get loving more and more. I appreciate it!
