### ISSUE TITLE
Unable to start debugging

### ISSUE THREAD

**Issue by mich2k** [microsoft/vscode-chrome-debug#1012]
hello, I am having some issues actually starting the debugging, for sure I am doing something wrong, since I never managed to start this

config:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:9222",
            "trace": "true",
            "webRoot": "${workspaceFolder}",
            "runtimeExecutable": "/snap/bin/chromium",
            "runtimeArgs":[
                "--new-window",
                "-user-data-dir=\"/${workspaceFolder}/DevProfile\"",
                "--remote-debugging-port=9222",
                "--disable-background-networking"
             ]
        }
    ]
}
```

- VS Code Version: code-exploration 1.46.0
- Log file (set `"trace": true` in launch config):
```
Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:9222/favicon.ico]
```
when starting I am having this error
[image](https://i.imgur.com/pGarGR6.png)
Same for standard chrome

**Comment by roblourens** [comment]
Does it work without all those runtimeArgs? Also, could you try this with our new debugger implementation? https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger
