### ISSUE TITLE
Feature request - add Folder to Chrome Workspace

### ISSUE THREAD

**Issue by penx** [microsoft/vscode-chrome-debug#1016]
Please add an option to launch.json, e.g.

```json
{
  "type": "chrome",
  "addToChromeWorkspace": true
},
```

That, when enabled, adds the `workspaceFolder` to the Chrome Workspace folders:

https://developers.google.com/web/tools/chrome-devtools/workspaces?hl=en

This will allow developers to edit code in the Chrome debugger and have it show up in VSCode.

I've [not been able to find a way](https://peter.sh/experiments/chromium-command-line-switches/) to do this by [passing an argument to Chrome](https://www.chromium.org/developers/how-tos/run-chromium-with-flags), so this feature perhaps may rely on a [feature request from Chrome Dev Tools](https://bugs.chromium.org/p/chromium/issues/detail?id=1087367).

**Comment by roblourens** [comment]
I think that integrating with chrome devtools like this is out of scope for this extension. I think your feature request on chrome devtools is the right place to discuss this, thanks for filing that. I think ideally, you would just be able to add an argument to chrome and your launch config would not need a special attribute.
