### ISSUE TITLE
Workaround for webRoot support for files option

### ISSUE THREAD

**Issue by AlexYash** [microsoft/vscode-chrome-debug#1019]
- VS Code Version: 1.45.1

Looks like VS Code doesn't support _**webRoot**_ option with **_files_** key in _launch.json_ debug configuration.
So I've used this workaround to support relative path in HTML:
```
{         
            "name": "Launch Chrome",  
            "type": "chrome",  
            "request": "launch",  
            "url": "http://localhost/${relativeFile}",  
            "webRoot": "${workspaceFolder}/"          
}
```

**Comment by connor4312** [comment]
Thanks for the issue, apologies for the late response!

We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/) if you continue to run into issues.
