### ISSUE TITLE
Recent extension improvement breaks workaround for undesired behavior

### ISSUE THREAD

**Issue by vegerot** [microsoft/vscode-chrome-debug#1020]
I'm starting to feel like [LongtimeUser4](https://xkcd.com/1172/), but in previous versions of this plugin I disliked that closing VSCode or quitting the debugger would force-quit my browser.  I actually really disliked this behavior, because I need Chrome to stay open and ALSO need it to auto-open and have custom profiles.  This caused me to switch to [Firefox](https://github.com/firefox-devtools/vscode-firefox-debug) (which I really did not want to do, love Chrome) which has an option to not quit Firefox after quitting VSCode.  

However, I discovered a workaround that let Chrome stay open after quitting VSCode, so I quickly switched back to Chrome (again, Chrome rocks).  The workaround was to start a debugging session (which opened Chrome), then if I were going to quit VSCode I would simply open a new tab, kill the first (debugged) tab, then quit Chrome.  This workaround worked great and I used it for a while.

However, a few days ago this plugin was updated that added much better tracking of tabs through the Call Stack, and giving more control.  I think these changes are great, and I love using them.  However, this breaks the workaround.  Now if I ever close the tab Chrome was opened with, the whole browser quits instantly.

So my request: Would you please add an option to not quit Chrome when quitting VSCode or the debugging session?  If not, would you add an option to disable these improved Call Stack features so I can go back to using my workaround?

Again, I know this sounds very unreasonable.  [Look, my setup works for me.  Just add an option to reenable worse stack tracing.](https://xkcd.com/1172/)
- VS Code Version: 
```
1.46.0-insider
a5d1cc28bb5da32ec67e86cc50f84c67cc690321
x64```


Steps to reproduce:

1. Start a new debugging session (which opens Chrome)
2. Open new tab
3. Close first tab
4. close VSCode

**Comment by roblourens** [comment]
If you add this setting, does it put the old behavior back? `"debug.javascript.usePreview": false`

cc @connor4312

**Comment by connor4312** [comment]
@vegerot great timing, we've actually _just_ added this behavior today :) https://github.com/microsoft/vscode-js-debug/pull/517 By default we'll now only close the tabs we launched when the debug session ends, and keep the browser around.

To get this you'll want to disable the builtin js-debug extension (you can find it by searching `@builtin js-debug`) and installing the nightly channel, `js-debug-nightly`

**Comment by vegerot** [comment]
Thank you!  Works perfectly.  WIsh there was something I could do to give back to your guys, but looks like this is Microsoft owned 🙂.  Would love to buy you a coffee.

Is there a debug version of the [companion](https://github.com/microsoft/vscode-js-debug-companion)?

**Comment by connor4312** [comment]
There's no debug version for the companion.

If you're ever in Redmond, feel free to buy me a tea 😉
