### ISSUE TITLE
SkipFile not working for flutter

### ISSUE THREAD

**Issue by tomasbaran** [microsoft/vscode-chrome-debug#1021]
This is my launch.json

```dart
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"skipFiles": [
				"<node_internals>/**",
				"**/app/out/vs/**"
			]
		}
	],
}

```

and it still is skipping outside my file e.g. framework.dart

**Comment by roblourens** [comment]
Could you try this with our new debugger implementation? https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by connor4312** [comment]
Closing after no response
