### ISSUE TITLE
v4.12.9 not launching Chrome with WSL

### ISSUE THREAD

**Issue by MichaelFlucher** [microsoft/vscode-chrome-debug#1026]
- VS Code Version: 1.47.0

Debugging on Windows works very well, but if I reopen the folder in WSL (Ubuntu), the debugger gives me the following error:
![image](https://user-images.githubusercontent.com/56301583/87513278-c31c2c00-c678-11ea-840e-a32b49c05559.png)

With Version 4.12.8 everything works fine. This is the config I'm using:
```
 {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:5090/index.html",
            "webRoot": "${workspaceFolder}/public",
            "runtimeArgs": ["--load-extension=${env:userprofile}/AppData/Local/Google/Chrome/User Data/Default/Extensions/bebecogbafbighhaildooiibipcnbngo/0.9.6_0"]
}
```

**Comment by roblourens** [comment]
cc @connor4312

**Comment by connor4312** [comment]
Let me know if this fixes it for you: https://github.com/microsoft/vscode-js-debug/issues/582#issuecomment-657083660

**Comment by MichaelFlucher** [comment]
With `pwa-chrome` I can at least launch chrome from WSL again, but now it cannot load the Extension anymore. It gives me Manifest file is missing or unreadable. Adding the Extension later in the opened Chrome works.
![image](https://user-images.githubusercontent.com/56301583/87665625-7fecb680-c767-11ea-8e72-28b4b6901f49.png)

**Comment by connor4312** [comment]
I'm not sure this is a problem in js-debug, though I don't know very much about Chrome extensions. It seems the common problem with this is the manifest being named incorrectly.

**Comment by MichaelFlucher** [comment]
But the Chrome extension works when starting debug on Windows. Only with WSL activated, which launches the same executable of Chrome (?), I get this error.

**Comment by connor4312** [comment]
Ah, okay. I think the `${env:userprofile}` is the issue for you -- the new Chrome debugger runs as a workspace extension so VS Code is taking variables from the _remote_ (i.e. WSL) rather than the local machine. This is the same root cause as https://github.com/microsoft/vscode-js-debug/issues/591. @roblourens we can probably close this as a duplicate, I'll make a note of this scenario in the other issue.

**Comment by MichaelFlucher** [comment]
Using absolute path fixed it for now. Thanks
