### ISSUE TITLE
Reopening #1020

### ISSUE THREAD

**Issue by vegerot** [microsoft/vscode-chrome-debug#1028]
A while ago, @connor4312 helped me out by telling me about some preview features in the `js-debug-nightly` extension to help a breaking improvement recently.

He was great help, but now it seems that even in `js-debug-nightly`, stopping the debug session will close ALL tabs and quit the browser, instead of just closing the tab the debugger was attached to.

Was this beta feature removed?  If so, then #1020 is still a problem for me, and would like to reopen that for strategies on how to NOT kill Chrome when stopping debugging

**Comment by connor4312** [comment]
Hi @vegerot -- we changed the default back due to https://github.com/microsoft/vscode-js-debug/issues/555, which I'd like to look into and change back somehow... However you can add `"cleanUp": "onlyTab"` to your launch.json to preserve the tab-closing behavior.

**Comment by vegerot** [comment]
Looks like that's two teas I owe you 🍵!  It works perfectly, thank you.

One thing: the `cleanUp` option is not recognized by VSCode's configuration syntax, but it works fine

**Comment by vegerot** [comment]
Awesome.  Can't buy you tea, but I'll donate a few bucks to the FSF on your behalf.  Thanks for keeping VSCode open source!

**Comment by vegerot** [comment]
(or any other charity you want) 🙂

**Comment by connor4312** [comment]
hah FSF or EFF works 😛 

Thanks for filing issues, happy coding ⌨️

**Comment by vegerot** [comment]
Cheers 🍻
