### ISSUE TITLE
Running the `.scripts` command fails with `Uncaught SyntaxError: Unexpected token '.'`

### ISSUE THREAD

**Issue by bartocc** [microsoft/vscode-chrome-debug#1029]
The `.scripts` command oddly fails with the `Uncaught SyntaxError: Unexpected token '.'` error

- VS Code Version:

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

- Log file (set `"trace": true` in launch config):

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4959601/vscode-debugadapter-0.json.gz)

Steps to reproduce:

1. Lauch chrome in debug mode on port 9222
2. Attach a debugger from vscode
3. Type `.scripts` in the debug console

**Comment by roblourens** [comment]
@connor4312

**Comment by connor4312** [comment]
This duplicates https://github.com/microsoft/vscode-js-debug/issues/260

**Comment by bartocc** [comment]
Ok, thx @connor4312.

For others finding this issue through search engines, here is the workaround https://github.com/microsoft/vscode-js-debug/issues/602#issuecomment-658273752
