### ISSUE TITLE
The debugger can't connect to a server with windows authentication to download the map files

### ISSUE THREAD

**Issue by jtarquino** [Microsoft/vscode-chrome-debug#103]
When it launch chrome connecting to a server that uses windows authentication, the extension fails to download the map files with a 401  unauthorized request
The problem seems to be located in the sourceMapTransformer.ts method  public scriptParsed(event: DebugProtocol.Event).

also the utilities.ts doesn't log the http error in the logger so its hard to figure out why the extension wasn't able to load the map files

**Comment by roblourens** [comment]
I guess I would have to inject code into the page to download the sourcemap file.

**Comment by roblourens** [comment]
A workaround - you could inline your sourcemaps so they don't need to be downloaded? Or maybe you can configure your build process to output an absolute local path for the sourceMapURL.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#5
