### ISSUE TITLE
Debugging older (second) version of Chrome seems te hang without error-indication

### ISSUE THREAD

**Issue by N247S** [microsoft/vscode-chrome-debug#1030]
I installed an older version of Chrome (for cross-browser compatibility testing), and it seems that the extension can't handle the old version? As it works fine with the recent version of Chrome.

I can run the debugger, it will properly start the older version of Chrome, but after that nothing happens. The requested 'url' (or 'file') is not loaded, and nothing in the debugger-view indicates that it is able to connect with the Chrome instance.

- If I close the ChromeWindow, it will instantly throw an error in VSCode "Unable to attach to browser".
- If I close the Debugger in VSCode, the debugger stops but Chrome stays open
- If I reload the Debugger, it will give an error "There is already a debug configuration "Launch Chrome 53.0" running." And the debugger will close (Chrome stays open)

- VS Code Version:
  Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- Chrome debugger version: 4.12.9
- Launch configuration:
  ```
  	{
			"type": "chrome",
			"request": "launch",
			"name": "Launch Chrome 53.0",
			"url": "http://localhost:9229",
			"webRoot": "${workspaceFolder}/test",
			"runtimeExecutable": "[[path to Chrome directory]]/Chrome/53.0/install/chrome64_53.0.2785.116/53.0.2785.116/chrome.exe",
			"runtimeArgs": ["--auto-open-devtools-for-tabs", "--chrome-version=53.0.2785.116"],
			"sourceMaps": true,
			"userDataDir": "${workspaceFolder}/.vscode/chrome_53",
			"sourceMapPathOverrides":
			{
				"webpack:///./*": "${workspaceFolder}/*",
				"webpack:///src/*": "${workspaceFolder}/*",
				"webpack:///*": "*",
				"webpack:///./~/*": "${workspaceFolder}/node_modules/*",
				"meteor://ðŸ’»app/*": "${workspaceFolder}/*"
			},
        }
  ```

If you need more information, feel free to ask.
Thanks for your time!

**Comment by roblourens** [comment]
Most likely it just won't be supported. Chrome has added new APIs that we use for debug support, and we can't support legacy versions when Google doesn't even support them. It is not considered safe to use old versions of Chrome.

**Comment by N247S** [comment]
That would be a great disappointment. I agree for web-development it is crucial to stay updated.

But in practise there are still older Chromium versions running on both desktop applications, and currently on almost all chromium powered smartscreens. (especially the later won't get an update if they are already running, and unfortunately that is exactly the environment I am currently developing for).

Especially because this extension has supported this specific older version, I hope the support will be made available (may it be through special settings).

So in all, I would verry much appreciate it, if this request is taken into serious consideration, rather than it being closed pre-emptively.

**Comment by N247S** [comment]
@roblourens  I hate to bump and tag, but I really would appreciate if this gets a change to be considered. As stated above, unfortunately I don't decide the production standards (for both web and non-web elements). Otherwise email-programming would have had a huge overhaul for example. Matter of fact is that we are still stuck using tables for layout at a fixed 600px width viewport. So also with this I am still searching for a way to test things properly.

Because the chrome version I am developing for has already been supported by this extension in the past, I hope this will get re-added/re-enabled (may it be through special settings). I am wel aware that supporting legacy builds/versions means that the bugs connected to those versions will persist. Nonetheless I think it would be a great feature if the support for legacy builds/versions would at least be available, may it be in the state support was dropped for those versions.

Again, sorry for bumping and tagging, but I would verry much appreciate it, if this request is taken into serious consideration, rather than it being closed pre-emptively.

**Comment by roblourens** [comment]
It might work if you set `"debug.javascript.usePreview": false`. Or you are free to install an old version of the extension, if it ever worked. But no, we are not going to support a version of Chrome which is not safe to use and isn't supported by Google.

**Comment by N247S** [comment]
Disappointing that backwards compatibility is not supported. Anyways FYI, setting `debug.javascript.usePreview` to `false` doesn't work.
