### ISSUE TITLE
CHANGELOG and Releases are out of date

### ISSUE THREAD

**Issue by chucknelson** [microsoft/vscode-chrome-debug#1031]
The CHANGELOG is out of date and doesn't include the latest versions / tag. The same goes for Releases in the repository.

I think if we get these back in sync with the code it could prevent some confusion - when looking at the repo, it looks like this hasn't been updated in a while, but it has.

**Comment by roblourens** [comment]
I added a note pointing to the vscode-js-debug repo, thanks.

**Comment by chucknelson** [comment]
Just adding commit for reference -https://github.com/microsoft/vscode-chrome-debug/commit/453a5c10ae5ab5dd05208291fe40eed3470af3ed#diff-4ac32a78649ca5bdd8e0ba38b7006a1e
