### ISSUE TITLE
`trace: "verbose"` does not print logs in Debug Console

### ISSUE THREAD

**Issue by doomleika** [microsoft/vscode-chrome-debug#1040]
- VS Code Version: `version 1.48`
- Log file:  [vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/5084571/vscode-debugadapter-1.json.gz)

Steps to reproduce:

1. Set the `"trace": true`

```json
// launch.json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:1234",
      "breakOnLoad": true,
      "webRoot": "${workspaceFolder}",
      "sourceMapPathOverrides": {
        "../*": "${webRoot}/*",
      },
      "showAsyncStacks": true,
      "disableNetworkCache": true,
      "trace": true,
    }
  ]
}

```

2. Launch the debugger

```
Verbose logs are written to:
C:\Users\corvo\AppData\Local\Temp\vscode-debugadapter-1.json.gz
```

3. Change the value of `"trace"` from `true` to `"verbose"`

4. repeat step **2**

5. Observe there's no difference with `"trace": true`

## Additional notes

It seems the log data are now gzipped by default. Is there options to disable this behavior? I used to open another editor and monitor the log in real time, but I can't do this anymore with gzipped logs.

**Comment by roblourens** [comment]
cc @connor4312

**Comment by connor4312** [comment]
Js debug only takes "true" or an options object. Not sure this is worth changing, it's a diagnostic thing and I don't think anything needs anything more than true/false.

**Comment by doomleika** [comment]
I am not sure what have changed over the development. However, this behavior was the case about a year a ago and `README.md` also [stated](https://github.com/microsoft/vscode-chrome-debug/blame/master/README.md#L138) this expected behavior.

Any clarification would be nice. Thank you.

**Comment by roblourens** [comment]
We have switched to a new debugger implementation which doesn't support this. This repo's Readme is for the older version.

**Comment by doomleika** [comment]
So, um... those documents are for older debuggers only?

**Comment by roblourens** [comment]
Some details: https://code.visualstudio.com/updates/v1_47#_new-javascript-debugger

**Comment by doomleika** [comment]
I believe it will be beneficial to restate those options are for older debugger only in the documents and remove "verbose" options while using the new debugger to avoid confusion, which I did fall into.
