### ISSUE TITLE
support for runtime sourcemaps

### ISSUE THREAD

**Issue by Gabriel0402** [Microsoft/vscode-chrome-debug#105]
I'm wondering whether there's support for runtime sourcemaps. I build the sourcemap manually but the extension seems not tracking it. I put my built js file and map file under dist folder and attach the webRoot to this folder and it's hitting the breakpoint at first. After I change the code and rebuild and lines of breakpoints are not correct. I have to restart the debugger to reattach and then it works. Is there any workaround for this case?

**Comment by roblourens** [comment]
Not totally clear on the scenario - are you using something for live-reloading of the script when it rebuilds? And it doesn't work after a rebuild, but works if you restart the debugger? It won't reload the sourcemaps for a script unless the page actually refreshes or the script is added/removed from the page. Does that make sense?

**Comment by Gabriel0402** [comment]
I'm using live-reloading of the script when it rebuilds, After rebuild and reload the page, I can see that the debugger is still using the old sourcemap, but after I restart the debugger, the debugger is using the new sourcemap. The page did refresh but the debugger didn't reload the sourcemap unless it get restarted. Is there any workaround for this case?

**Comment by roblourens** [comment]
Is there any chance that the script or sourcemap is being cached by the page or webserver? The debugger will always redownload the sourcemap when the page refreshes.

**Comment by Gabriel0402** [comment]
Thanks for this information! Yes I tested the debugger will always redownload the sourcemap when the page refreshes. I'll go to check whether my process will cache the sourcemap for some reason. I think I can close this issue.

**Comment by Gabriel0402** [comment]
one more question is that if the debugger redownload the sourcemap will the debugger auto reattach to the new sourcemap?

**Comment by Gabriel0402** [comment]
I checked that the debugger did redownload the sourcemap and reattach to it. And step over and step into both works.But some breakpoints will not recognize the new sourcemap. After I restart the debugger the breakpoints are set correctly. Is this a bug?

**Comment by roblourens** [comment]
There isn't really a 'reattaching' process - the old script is unloaded, and the new script is loaded, and it starts over completely fresh. It doesn't try to relate the new 'app.js' to the old 'app.js'. So refreshing the page should be more or less the same as when you start for the first time.

**Comment by roblourens** [comment]
What do you mean by "some breakpoints will not recognize the new sourcemap"? Can you not set a breakpoint in some locations? Does the breakpoint set but not get hit?

**Comment by Gabriel0402** [comment]
it seems that the debugger didn't recognize the soucemap. And refresh or reload the page didn't help. It only works when I restart the debugger. And I checked that breakpoints are set with the new sourcemap only I restart the debugger. refresh and reload didn't help.

**Comment by roblourens** [comment]
What exactly do you see when the debugger "didn't recognize the sourcemap"?

**Comment by Gabriel0402** [comment]
I saw that I cannot set the breakpoints correctly until I restart the debugger.

**Comment by roblourens** [comment]
Are they gray? Or are they red, but they don't get hit?

**Comment by Gabriel0402** [comment]
They're red, but in incorrect lines. Some are gray which says invalid because they're map to different lines, they get hit, but in wrong lines. I think it's because it's using the old sourcemap. And it works after restart the debugger.

**Comment by roblourens** [comment]
Can you share the log with me? Including rebuilding, and setting a breakpoint? I'm not sure what would be happening.

**Comment by Gabriel0402** [comment]
[log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/137245/log.txt)
Here's the log and I added the explanation inside. Thanks a lot for your help!

**Comment by roblourens** [comment]
I can't see any problem from the log. First you set a breakpoint at line 157 (0-indexed) which is mapped to line 42467
`›SourceMaps.setBP: Mapped c:\Users\czhu\Desktop\Nova\src\app\components\home\home.component.ts:157:0 to c:\Users\czhu\Desktop\Nova\dist\main.bundle.js:42467:31`
and Chrome comes back and says sure, the breakpoint is set at 42468:9. (Which is ok, maybe the 42467 is on a brace or something).
`›From target: {"id":12,"result":{"breakpointId":"http://localhost:3000/main.bundle.js:42467:31","locations":[{"scriptId":"981","lineNumber":42468,"columnNumber":9}]}}`

Then after where you say it's messed up, I see exactly the same thing
`›SourceMaps.setBP: Mapped c:\Users\czhu\Desktop\Nova\src\app\components\home\home.component.ts:157:0 to c:\Users\czhu\Desktop\Nova\dist\main.bundle.js:42467:31`
...
`›From target: {"id":91,"result":{"breakpointId":"http://localhost:3000/main.bundle.js:42467:31","locations":[{"scriptId":"1924","lineNumber":42468,"columnNumber":9}]}}`

Then where you say it's working again:
`›SourceMaps.setBP: Mapped c:\Users\czhu\Desktop\Nova\src\app\components\home\home.component.ts:157:0 to c:\Users\czhu\Desktop\Nova\dist\main.bundle.js:42467:31`
...
`›From target: {"id":38,"result":{"breakpointId":"http://localhost:3000/main.bundle.js:42467:31","locations":[{"scriptId":"1924","lineNumber":42468,"columnNumber":9}]}}`

**Comment by roblourens** [comment]
It sounds like you can at least continue to work by restarting the debugger. I've used browser-sync without issue so you might try that. And maybe this issue will be fixed as I fix other sourcemap-related issues.

**Comment by Gabriel0402** [comment]
Yes, that's true. I set two breakpoints at first, and I add three console.log between this two breakpoints. After the rebuild the first breakpoint is set correctly. But the second one is wrong. I think this is the problem of the sourcemap. Thanks.
