### ISSUE TITLE
Problem inside Angular Observables

### ISSUE THREAD

**Issue by kvinay3** [microsoft/vscode-chrome-debug#1053]
version: 1.50.1
chrome: 83.0.4103
OS:Windows 10
my launch.json
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceFolder}"
        }

Steps:
1. add a break point inside an Observable of angular project
2. when u hover over this inside an Observable it should show the current class variables and functions but instead it shows the observable scope
![subscribe](https://user-images.githubusercontent.com/23552349/96218978-7a3f8080-0fa3-11eb-8070-35ca7cb50f2e.PNG)
3. when i try to check any variable it show undefined.
![undefined](https://user-images.githubusercontent.com/23552349/96218983-7c094400-0fa3-11eb-8f3d-7ace08a6b6a4.PNG)
4. but the local variable declared inside the Observable are working fine.
5. if i check the same variable inside chrome debug console
![chrome](https://user-images.githubusercontent.com/23552349/96219494-942d9300-0fa4-11eb-84ec-fe81c4f6cbf4.PNG)

**Comment by connor4312** [comment]
What's your `target` in your tsconfig? You may be hitting https://github.com/microsoft/vscode/issues/12066 where the compiler downlevels arrow functions.
