### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MrJack404** [microsoft/vscode-chrome-debug#1055]
- Issue Type: `Performance`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.12.11`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.47.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\USER\msjsdiag.debugger-for-chrome-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by connor4312** [comment]
This extension is no longer actively developed. We have a [new debugger](https://github.com/microsoft/vscode-js-debug), which is the default unless you set `debug.javascript.usePreview: false`. We recommend updating your VS Code version and switching over to that; please file an issue if there's something that doesn't work right or othewise prevent you from switching.
