### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by codeNameM1** [microsoft/vscode-chrome-debug#1057]
- Issue Type: `Bug`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.12.11`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 12604,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "msjsdiag.debugger-for-chrome",
				"_lower": "msjsdiag.debugger-for-chrome"
			},
			"activationEvent": "onDebugResolve:chrome"
		}
	},
	"runtimeErrors": []
}
```

**Comment by connor4312** [comment]
This extension is no longer maintained (see readme). Let us know if you have issues with the new debugger.
