### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Viper-76** [microsoft/vscode-chrome-debug#1058]
- Issue Type: `Performance`
- Extension Name: `debugger-for-chrome-nightly`
- Extension Version: `2020.2.15300`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\usuario\AppData\Local\Temp\msjsdiag.debugger-for-chrome-nightly-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by connor4312** [comment]
We have a new debugger and this extension is no longer maintained (see readme)
