### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by FikahMazid** [microsoft/vscode-chrome-debug#1059]
- Issue Type: `Performance`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.12.11`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Owner\AppData\Local\Temp\msjsdiag.debugger-for-chrome-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by connor4312** [comment]
We have a new debugger and this extension is no longer maintained (see readme)
