### ISSUE TITLE
Need to beable to inspect dom without chrome just crashing

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#106]
Need to be able to inspect dom without chrome just crashing.
Is there a way to express the good bits of devtools. or even connect the vscode devtools to the debug session?

**Comment by auchenberg** [comment]
Sadly it's not possible to have two debugging tools connected to Chrome at the same time. This means that if you open Chrome DevTools while debugging from VS Code, the connection is closed, and the other way around. 

This is a limitation of Chrome. See this issue https://github.com/Microsoft/vscode-chrome-debug/issues/83

**Comment by justin-romano** [comment]
Yep agreed

On Fri, Feb 19, 2016 at 11:13 AM, Kenneth Auchenberg <
notifications@github.com> wrote:

> Closed #106 <https://github.com/Microsoft/vscode-chrome-debug/issues/106>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode-chrome-debug/issues/106#event-555781841>
> .
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166
