### ISSUE TITLE
Getting the error: Configured debug type chrome is not supported

### ISSUE THREAD

**Issue by sunpietro** [Microsoft/vscode-chrome-debug#112]
I wanted to start using your newest feature whish debugging in Chrome. I followed instructions from here: http://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code and when I run the Chrome in debugger mode (`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`) and click on _Play_ button in VS Code, then I'm getting the error: *Configured debug type chrome is not supported*

My config in `.vscode/launch.json` looks like this:
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch local.dev",
            "type": "chrome",
            "request": "launch",
            "url": "http://local.dev",
            "webRoot": "./Resources/js"
        },
        {
            "name": "Attach local.dev",
            "type": "chrome",
            "request": "attach",
            "port": 9222
        }
    ]
}
```

What did I do wrong?

**Comment by roblourens** [comment]
That sounds like you don't have the extension installed, or didn't restart after installing it.

**Comment by sunpietro** [comment]
@roblourens what extension do you mean?

**Comment by sunpietro** [comment]
I had to reinstall the extension for some reason

**Comment by johnfn** [comment]
For future googlers, I ran into this issue when I installed the extension on Visual Studio Code, then switched to Visual Studio Code Insiders. I needed to install it on there, too. :)

**Comment by deevus** [comment]
This issue persists in 1.4.0

I've tried reinstalling but get the same error

**Comment by roblourens** [comment]
So you installed the extension, restarted VS Code, and got this message when you tried to debug? Can you verify that the extension does show up in the extensions pane and `~/.vscode/extensions/msjsdiag.debugger-for-chrome-0.5.2`?

**Comment by jonaskello** [comment]
I'm having the same issue. Installed and restarted. Confirmed the plugin shows up in the pane and the folder exists. Still getting error configured debug type 'chrome' is not supported when hitting the play button. 

I also noticed that before I added a launch.json, the configure icon next to the dropdown with configs had an option to generate a launch.json, but it only listed "Node.js", "VSCode Extension Development" as environment options. Not sure if chrome should be listed there too? Anyway I generated one for node.js and replaced it with the contents from the example [here](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome).

**Comment by jonaskello** [comment]
Uninstalled all my extensions (only chrome debug and flow support). Then reinstalled just chrome extension. Now it works :-).

**Comment by roblourens** [comment]
Oh, I think these past couple reports are the same as this issue - https://github.com/Microsoft/vscode/issues/10148

Which is, a bug in vscode triggered by something in the flow extension. Glad it works for you!

**Comment by misbell** [comment]
This thread was really helpful and I'm now debugging from VSCode attached to Chrome. Thank you folks!
