### ISSUE TITLE
Problem with set breakpoints with latest VS Code version 0.10.10

### ISSUE THREAD

**Issue by saskomateski** [Microsoft/vscode-chrome-debug#115]
After installing latest VS Code version 0.10.10 we are having problems when setting breakpoints - the debugger is not stopping on breakpoints.

**Comment by 4zriel** [comment]
Same story...yesterday everything on same launch.json settings worked fine but today after update to 0.10.10 debugger is usless :(

**Comment by marko-baric-travcorp** [comment]
Same problem here. Looks like there is a problem related to setting "webRoot" value which might be related to this. There is a separate issue for this.

**Comment by saskomateski** [comment]
Workaround for the problem ca be found in Issue #117

**Comment by andersrydman** [comment]
We're experiencing the same thing as well.

**Comment by auchenberg** [comment]
Thanks for reporting this! Stay tuned.

**Comment by auchenberg** [comment]
Duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/117

README has been updated with new defaults for `webRoot`
