### ISSUE TITLE
Can't set breakpoints in script tags in html files

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#122]
Old issue, no existing bug

**Comment by roblourens** [comment]
If we enable breakpoints for ".html" files, users will be able to set a breakpoint on html as well as embedded scripts. But now that there is UI for unbound breakpoints, we can probably give a decent experience here.

**Comment by felixfbecker** [comment]
I think the ideal solution would be that VS Code detects that a `<script>` tag inside HTML has the language ID `javascript` and not `html`. I have the same problem with my PHP debugger.

**Comment by auchenberg** [comment]
@roblourens Has the UI behavior changed? Will `index.html` with `<script>` be treated as `scriptParsed` event, to enable sourcemaps, etc?

**Comment by roblourens** [comment]
Nothing has changed

**Comment by deandob** [comment]
Hi, would be nice to have this feature - using inline <script> is quite common and not being able to set breakpoints for inline script is a showstopper for me using VS code.
Is this feature planned at some point?

**Comment by csakaszamok** [comment]
+1

**Comment by roblourens** [comment]
Nothing has changed unfortunately but in Insiders now and in 1.7 soon there will be the option `"debug.allowBreakpointsEverywhere": true` which will let you set breakpoints in any file, valid or not. I haven't tested it yet with html files but that might be a good workaround.

**Comment by csakaszamok** [comment]
excelent

**Comment by sasivarnan** [comment]
@roblourens It works. Thanks. 👍

**Comment by abdonrd** [comment]
Any news with VSCode 1.8? :)

**Comment by roblourens** [comment]
This works with `debug.allowBreakpointsEverywhere": true`
