### ISSUE TITLE
[cordova-debug-adapter] TypeError: Cannot read property 'nodeValue' of undefined

### ISSUE THREAD

**Issue by Ritzlgrmft** [Microsoft/vscode-chrome-debug#123]
In between, I am able to debug my app in the simulator (#54). But now I wanted to debug on an attached iPhone. When I select `Run iOS on device`, I see in the debug console:

    Launching for ios (This may take a while)...
    Launching app (This may take a while)...
    Installing app on device
    Launching app

And the I get the error

    [cordova-debug-adapter] TypeError: Cannot read property 'nodeValue' of undefined

When I select `Attach to running iOS on device`, I see in the debug console:

    Attaching to ios
    Configuring debugging proxy

And then I get the same error as above.

**Comment by roblourens** [comment]
Sounds like you're using the Cordova extension, right? You can file an issue with them here - https://github.com/microsoft/vscode-cordova/issues

**Comment by Ritzlgrmft** [comment]
Sorry, my mistake, now I created the issue in the right repository.
