### ISSUE TITLE
not stopping on soft debug breakpoints or hard breakppoints with sourcemap view

### ISSUE THREAD

**Issue by myusrn** [Microsoft/vscode-chrome-debug#125]
I'm trying to use vscode chrome debug/launch settings on an implementation of the simple angular 2 [ng2] quickstart web application detailed here https://angular.io/docs/ts/latest/quickstart.html.

I defined a .vscode/launch.json "Launch localhost with sourcemaps" entry meant to enable debugging of web app pages using chrome extension but what i'm finding is that it doesn't stop of soft break points.  

Using hard break points, e.g. uncommenting onTestClick() debugger statement, i can get vscode chrome extension to break into code at which point its showing transpiled javascript and not the sourcemap enabled view of original typescript.   I tried to ensure i had the relevant tsconfig.json sourceRoot entry and vscode launch.json sourceMaps + webRoot setting necessary to make that all work.

This can be repro’d by cloning https://github.com/myusrn/vscng2qs | executing "npm install" to restore modules | opening in vscode | building typescript using ctrl+shift+b [ or "npm run tsc" | setting a few break points in app.component.ts, e.g. in onTestClick() | entering "npm run lite" to get web server going and killing browser instance it launches | then selecting vscode debug "Launch localhost with sourcemaps" option | clicking on test button.  Then do again with hard breakpoint statement uncommented.

**Comment by roblourens** [comment]
Is this different from the issue we resolved over email?

**Comment by myusrn** [comment]
Yes it is different.  This has to do with use of vsc chrome extension for debugging of simple web app using ng2 and typescript.  The one we addressed previously was use of vscode chrome extension for debugging of apache cordova execution environment [ acx] using ng2 and typescript.

**Comment by roblourens** [comment]
That app works for me - I can hit breakpoints in `app.component.ts` as-is.

**Comment by roblourens** [comment]
By the way, that other bug, #88, is fixed.

**Comment by roblourens** [comment]
I've fixed a couple bugs lately so maybe that's why it works now.

**Comment by myusrn** [comment]
thanks fro followup on this.  

i'm thinking something must differ between our setups as i'm running vscode 0.10.11 and can still repro the above and now i can't stop on hard break point either.

wrt bug #88 being resolved does this mean tsconfig.json "sourceRoot": "file:///d:/src/repos/vscng2qs" could now be defined using backslashes as well as forward slashes or even better using relative path?

**Comment by roblourens** [comment]
Can you ensure the extension is up to date, then send me the log?

And right, relative path should work.

**Comment by myusrn** [comment]
ctrl+p | ext [ or f1 | extensions: show installed extensions ] had me running debugger for chrome 0.2.2

ctrl+p | ext update  [ or f1 | extensions: show outdated extensions ] offered me debugger for chrome 0.2.4 update that i installed

i found that if i commented out the tsconfig.json | "sourceRoot": "file:///d:/src/repos/vscng2qs" entry i had previously, to work around issue #88, this breaking on soft debug break points properly mapped to typescript source file view worked.   I tried using tsconfig.json | "sourceRoot": "file:\\\\d:\\src\\repos\\vscng2qs" and that didn't work so only not having any sourceRoot entry worked for me.

Also i'm finding that using ctrl+shift+b appears to be executing typescript compile but isn't updating the associated .js output.   I verified this by adding/removing lines and after ctrl+shift+b succeeds looking for that change in the associated .js file and its not there.  Conversly if i drop to command line and execute "npm run tsc" or "npm run tscw" it is successfully updating associated .js file.   Not sure what is causing this but it is definitely messing up my efforts to test for repros of vscode typescript based project work as i have been assuming ctrl+shift+b leaves me launching test using updated *.js output when its not.

**Comment by roblourens** [comment]
Good, but `"file:\\d:\src\repos\vscng2qs"` isn't a valid sourceRoot, because you need 3 forward slashes after file:. Then backslashes probably work after that but might not - URLs typically require forward slashes. The extension should be ok with it but Chrome may or may not.

**Comment by roblourens** [comment]
And you may need to escape them too... less headache if you stick with forward slashes. I think the original issue was gulp-sourcemaps outputting backslashes.

**Comment by myusrn** [comment]
thanks for clarification
tried tsconfig.json | "sourceRoot": "file:///d:\\src\\repos\\vscng2qs",  and that didn't work

retried tsconfig.json |  "sourceRoot": "file:///d:/src/repos/vscng2qs",  which worked before resolution to issue 88 and that didn't work which is fine i think given it appears with that issue resolved i don't need this entry in place at all.  so unless there is a scenario where i do need to explicitly define sourceRoot in order for *.js.map to contain relevant mappings back to typescript source file i think this is good.

any pointers to the GitHub repo/issues list i should surface the fact that vscode ctrl+shift+b typescript build process is not updating *.js and *.js.map files even though "npm run tsc" is working as expected?  i think could be really misleading for folks, if its happening elsewhere, as you think it is producing updated output when ctrl+shift+b succeeds and it is not.

**Comment by roblourens** [comment]
Is "npm run tsc" actually running when you press ctrl+shift+b? That's determined by which task has `"isBuildCommand: true"` in tasks.json. I see a couple tasks with that set for some reason so I'm not sure what's actually running. What output is there? I'm guessing you're not running the right task.

**Comment by myusrn** [comment]
my understanding is that ctrl+shift+b causes vscode to execute any .vscode/tasks.json entries that have "isBuildCommand": true defined.   the repo for repro'ng this matter has only one uncommented task definition in tasks.json named "tsc" that when vscode executes it should be carrying out the same thing that cli "npm run tsc" carries out.   

i just checked in update that adds "isBuildCommand": true to that task definition so that as you called out ctrl+shift+b finds and executes it vs you having to use ctrl+p | tsc [ or f1 | tasks: run task | tsc ] to run it.

**Comment by roblourens** [comment]
See the "args" prop in the build task - your task runs "tsc -p . --noemit". The noemit flag prevents tsc from emitting js. I guess that's useful for typechecking without actually transpiling. Probably not what you want though. If you want to guarantee that the build task is in sync with the npm script, I would make the build task do "npm run tsc".

**Comment by myusrn** [comment]
that was the issue, I updated task to remove that argument and then it produced updated .js & *.js.map output every time I used ctrl+shift+b or ctrl+p | task tsc.   Surprised that vscode sets up .vscode/tasks.json entries with that argument present by default.
