### ISSUE TITLE
Hope vscode can auto launch chrome 

### ISSUE THREAD

**Issue by wangan** [Microsoft/vscode-chrome-debug#126]
Hope vscode can auto launch chrome

**Comment by jalissia** [comment]
The extension does support auto launching chrome if you use a launch configuration. By default it will try to look up the chrome install location automatically, but you can override the path it uses by specifying a "runtimeExecutable" in your launch configuration json.

For example:
`"configurations": [{
			"name": "Launch index.html",
			"type": "chrome",
			"request": "launch",
			"file": "${workspaceRoot}/index.html",
                        "runtimeExecutable": "C:\\MyApps\\chrome.exe"
}]`
