### ISSUE TITLE
Breakpoints issues with nwjs

### ISSUE THREAD

**Issue by johanolofsson** [Microsoft/vscode-chrome-debug#129]
Breakpoints move around and wont get hit when debugging typescript in NWJS.

**Comment by auchenberg** [comment]
Hi @johanolofsson 

Can you provide steps to reproduce and potentially a sample app? That would make this faster to dig into. For now, we don't have official NW.JS support, as our focus is sole on the browser, Chrome.

**Comment by Spown** [comment]
I don't think vscode suppoorts nwjs. first of all it doesn't start mw.exe (on Windows and whatever on Linux/OSX), but rather sends ``package,json``'s ``main`` to node, which will run in most cases and quickly&silently exit. Secondly you need to attach the debugger, and for that you need to configure [the remote debugger](https://github.com/nwjs/nw.js/wiki/Debugging-with-devtools#remote-debugging).

We need a nwjs debugger extension for vscode. Maybe someone makes one in the future...

**Comment by roblourens** [comment]
If you launch nwjs in debug mode, then attach with the Chrome extension, that should work. I can't officially support it, but it should be using the same debug protocol.

**Comment by karikera** [comment]
I made it! :D
https://marketplace.visualstudio.com/items?itemName=ruakr.vsc-nwjs
