### ISSUE TITLE
Support source mapping of stack traces

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#132]
When an error is thrown with a stack trace, we should support source mapping of the source:

Actual:
![app js - timey in 2016-03-22 15-09-38](https://cloud.githubusercontent.com/assets/173559/13969430/1bf126c8-f040-11e5-88cf-8bd3f7cf5b48.png)

Click on `Scope.$scope.onAddNewClick (http://localhost:8080/app_bundled.js:234:5)` triggers:
![app js - timey in 2016-03-22 15-10-13](https://cloud.githubusercontent.com/assets/173559/13969441/2fe6e8ca-f040-11e5-841e-46b91258e494.png)

Expected: 
Path to files within stack traces are source mapped to the original source.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#6
