### ISSUE TITLE
I can't do anything with this extension... Launch or attach

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/vscode-chrome-debug#133]
This is the code snippet I am trying to use. 

    ```          
{
 "name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000/",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true
        },
        {
            "name": "Launch index.html (without sourcemaps)",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/app.js"
        }

```
when I launch it keeps giving me this error:
**[debugger-for-chrome] Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222**

It launches in its browser (port 3000) but I get the error and nothing actually debugs.  I am on a mac using chrome browser.  

I am probably doing something wrong.

As well, I am not familiar with the attach and launch difference.

**Comment by roblourens** [comment]
Sometimes when Chrome launches, it doesn't start up in remote debugging mode correctly. This has been sort of a common problem. Some things to try -
* Make sure all other instances of Chrome are closed.
* On Windows, Chrome puts an icon in the taskbar when it's running in the background. There might be a similar clue in OS X? Not sure. If needed, kill Chrome from Activity Monitor
* Launch Chrome manually manually with the --remote-debugging-port flag and use the attach config.

Difference between launch/attach is that launch will launch Chrome for you, and attach will look for running instances of Chrome (with remote-debugging enabled) to use.

**Comment by xtianus79** [comment]
But what about the port. My normal app runs on 3000. What should this debugger run on to debug yet still run the app?  The standard node debugger that vs  codecomrs with works well.

**Comment by roblourens** [comment]
That's fine, you just need `:3000` in the URL. The debugger will use port 9222 to talk to the browser, but that's independent of the browser talking to your server.
