### ISSUE TITLE
Get rid of "webkit" naming

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#136]
Since this debugger is targeting the Chrome Debugger Protocol, and not the Webkit Remote Debugging Protocol, we should get rid of all of the webkit naming for consistency and clarity.

**Comment by auchenberg** [comment]
Now when this debugger is being repackaged as a dependency I think this is more important, as we want to avoid spreading the misleading webkit references into other debuggers.

**Comment by roblourens** [comment]
Finally, 'webkit' is 100% expunged.

**Comment by auchenberg** [comment]
![](https://media.giphy.com/media/3oEduV4SOS9mmmIOkw/giphy.gif)
