### ISSUE TITLE
Question: is it possible to debug both Chrome and Node.js?

### ISSUE THREAD

**Issue by buzinas** [Microsoft/vscode-chrome-debug#140]
I'm able to debug client-side code in VSCode using Chrome with this extension, and I'm also able to debug Node.js through the other configuration inside my `launch.json` file.

Although, I would like to debug both simultaneously, e.g:

I put a breakpoint on a button's click event listener, and after I click the button, I can debug to see what's happening. Inside this listener, I make a request to my Node.js api, and I want to debug it too. And, then, when my API answers, I want to debug the response again.

When working with VS, I can debug both IE's Javascript code and C# web api one simultaneously, but I can't figure out how to do that with VSCode and Chrome/Node.js. Is there any way to do that?

It seems that I can only have one debugging at the same time.

I appreciate any help/feedback. Thanks in advance.

**Comment by auchenberg** [comment]
Hi,

For now we don't support that we call "cross tier" debugging where you can step through the different layers in VSCode. We love the concept, but it's currently not on our roadmap, as we still are perfecting the normal debugging experience.

So for now you have to continue to use regular VS for get this experience. 

/k

**Comment by weinand** [comment]
VS Code supports running multiple debuggers simultaneously in multiple windows but it is a bit tricky to run two debuggers from the same project folder.
Please see Microsoft/vscode#1616 for how this can be done.

**Comment by Ulili** [comment]
Yes it is possible!!!
You need first create booth launcher and then add compounds you lunch.json gonna be like bellow:
```json
{
    "version": "0.2.0",
    "compounds": [
        {
            "name": "Launch & Debug",
            "configurations": ["Launch Program","Launch Chrome"]
        }
    ],
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\app.js"
        }
    ]
}
