### ISSUE TITLE
When add breakpoint ... error : can't be resolved to a loaded script

### ISSUE THREAD

**Issue by faustomura** [Microsoft/vscode-chrome-debug#145]
- VSCode Version:0.10.11
- OS Version:Windows 8.1
-Extension version : 0.2.5

I can't debug browser side typescript code of Angular 2 "Tour Of Heroes" sample code ( http://plnkr.co/edit/?p=preview )

If i try to add a breakpoint with Debugger for chrome extensions i se in the log console this error "can't be resolved to a loaded script.".

I already start chrome whit --remote-debugging-port=9222
My launch copnfiguration is :+1: 
		{
			"name": "Chrome Attach",
			"type": "chrome",
			"request": "attach",
			"port": 9222,
			"url": "http://localhost:9085/_template/dev/www/dashboard",
			"webRoot": "${workspaceRoot}",
			"diagnosticLogging": true,
			"outDir": "${workspaceRoot)",
			"cwd":"${workspaceRoot}",
			"sourceMaps": true
		},

**Comment by roblourens** [comment]
Sorry for the slow response - that seems like a popular tutorial app, and I've been meaning to add some examples with working configs, so I added this under the 'examples' folder with a working launch configuration. Try it out and let me know if that helps!
