### ISSUE TITLE
List in npm

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#146]
This codebase is reused by the cordova extension (and more soon?) using slightly awkward methods. Need to clean up a few things, fixup the interface that they use, and list in npm.

**Comment by auchenberg** [comment]
:+1:

**Comment by roblourens** [comment]
We will probably need to split extension code from npm package code. The package name is of course determined by the 'name' field in package.json - I set this as the extension name, "debugger-for-chrome". We can't change that on the extension side, but I don't think that makes sense for an npm package name. We probably need to split the module code from the extension code, and that's not too hard, but we need to decide whether to keep it in one repo, or create a new repo where the extension code will live. I think it would make development easier to use one.

**Comment by auchenberg** [comment]
I do see a need for 3rd parties to be able to use the core chrome debugger with the VSCode extension specific code. 

I imagine scenarios like Node, iOS, Edge, Firefox, etc, that each needs their own extension wrapping to start browsers/runtimes, but need to spin up an instance of the Chrome debugger by pointing it to an endpoint.

I suggest we use something like `vscode-chrome-debugger-core` for the NPM package name, if the debugger is gonna be separated.

**Comment by roblourens** [comment]
https://www.npmjs.com/package/vscode-chrome-debug-core :)
