### ISSUE TITLE
Automatically reattach to a new target when the debuggee closes

### ISSUE THREAD

**Issue by Vj3k0** [Microsoft/vscode-chrome-debug#147]
I'm developing Electron application with multiple windows. I've made configuration which works well and I can actually debug my code. But when this window is closed, debugging stops and is not switched to another window.

So my question is basically, how can I debug more than one window in Electron?

When I navigate to localhost:9222, I can see my window there, but VS debugging has stopped.

**Comment by roblourens** [comment]
I'm not super familiar with Electron, but I assume that the different windows are sort of like multiple tabs in a browser. You'll have to reattach to a different window each time, I don't have any way to automatically reattach to a new one at the moment.

**Comment by auchenberg** [comment]
@roblourens How does the Node debugger do this? Thinking this is done to work correctly with Nodemon

**Comment by roblourens** [comment]
It's definitely technically possible for chrome-debug to do it. I just mean that there isn't a way implemented yet.
