### ISSUE TITLE
Not all breakpoints work

### ISSUE THREAD

**Issue by zhouhao27** [Microsoft/vscode-chrome-debug#148]
In my app, some breakpoints work, some don't.

![screen shot 2016-04-07 at 10 46 34 am](https://cloud.githubusercontent.com/assets/8099731/14339109/a694e100-fcae-11e5-9221-ed939bbc7ed9.png)

In my case, only the breakpoint in create() function works. Why? Any idea? Thanks.

**Comment by auchenberg** [comment]
Hi @zhouhao27 

Can you tell a bit more about your setup, as it looks like you are using ES2015, that's getting transpiled with Babel or something?

Please share your setup details and `launch.json`

/k

**Comment by zhouhao27** [comment]
Hi @auchenberg , I'm using typescript. My launch.json:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch index.html",
			"type": "chrome",
			"request": "launch",
			"file": "index.html"
		},
		{
			"name": "Launch localhost with source maps"
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:8080/index.html",
			"sourceMaps": true,
			"webRoot": "."
		},
		{
			"name": "Attach",
			"type": "chrome",
			"request": "attach",
			"port": 9222
		}
	]
}
```

**Comment by auchenberg** [comment]
Aha. Since you are using TypeScript you need to use the Source map launch target, and you also need to update `webRoot` to match the root of your TypeScript source files. 

If they are in your root, set `webRoot` to `${workspaceRoot}"

You can see the examples in our README, https://github.com/Microsoft/vscode-chrome-debug/blob/master/README.md

**Comment by zhouhao27** [comment]
@auchenberg I'm using Source map which you can see in my `launch.json`. My directory structure is like this:

<img width="242" alt="2016-04-08 2 22 48" src="https://cloud.githubusercontent.com/assets/8099731/14375560/c2b82eaa-fd94-11e5-82ad-3b788856c20e.png">

My launched file `index.html` is in my root, so that I set the webRoot to '.'. Because my .ts files are compiled into .js with source map, so that the system will know my source code through source map. Am I right?

One thing puzzled me is the app did stop at one of the breakpoint in my app.ts file.

<img width="692" alt="2016-04-08 2 22 17" src="https://cloud.githubusercontent.com/assets/8099731/14375632/43f2ac2a-fd95-11e5-9b08-1f89ded280fc.png">

But it never stops at other breakpoints.

**Comment by roblourens** [comment]
The breakpoints in onload and the constructor won't be hit unless you refresh the page. The breakpoint on preload is on the function definition, not in the body. That may be because of #48.
