### ISSUE TITLE
debugging current ionic 2 project templates using typescript

### ISSUE THREAD

**Issue by myusrn** [Microsoft/vscode-chrome-debug#150]
I'm trying to debug current angular 2 based ionic project templates where by default the typescript based output, generated using gulpfile.js buildBrowserify task, is configured to bundle with source maps.  I'm finding when I use vscode to launch or attach to chrome instance, using current 0.2.5 version of extension, its not stopping on breakpoints.

I can repro this using https://github.com/myusrn/acxwithng2io sources that were generated using:

1. npm install [ | update ] -g cordova ionic@beta gulp [ 6.1.1, 2.0.0-beta.25, 3.9.1 respectively ]
2. ionic start acxwithng2io sidemenu --v2 --ts
3. adding the relevant acxwithng2io/.vscode/settings.json + tasks.json + launch.json settings
4. placing some break points in app/pages/list/list.ts | constructor and itemTapped event handler
5. building and launching project from command line using "ionic serve"
6. in vscode I then attach debugger using "Attach to chrome with sourcemaps" entry

At this point I was expecting it to break on list.ts constructor and/or itemTapped event handler when I used the hamburger menu to navigate to that list and select any entry, as it does if I attach f12 browser tools, but it does not.

**Comment by roblourens** [comment]
When I build your project, the sourcemap has `"sourceRoot":"/source/"` which doesn't exist, and `"sources"` from the project root, like `"app/app.ts"` which is ok, but needs to work with sourceRoot. I don't know how to configure the sourceRoot with your build setup, but if you can get these values to come out right, I'm sure it will work with the extension

**Comment by myusrn** [comment]
Thanks for the review of this matter and calling out source of issue.   

I've posted [https://forum.ionicframework.com/t/controlling-ionic-gulp-browserify-typescript-sourcemap/50372](https://forum.ionicframework.com/t/controlling-ionic-gulp-browserify-typescript-sourcemap/50372) to get some insight into how to get browserify process that transpiles and bundles typescript sources to use the relevant "sourceRoot":"/" setting when generating .js.map file.
