### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by jeffa87** [Microsoft/vscode-chrome-debug#151]
I'm new to visual studio code and can't figure out how to get debug working. I have been able to debug in chrome but I can't seem to get the vscode-chrome-debug to connect correct. Any help would be greatly appreciated.

launch.json
```json
{
	"version": "0.2.5",
	"configurations": [
		{
			"name": "Launch localhost with sourcemaps",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:3000/abc/#/login?_k=20m5po",
			"sourceMaps": true,
			"webRoot": "C:/source/abc/ABC-GUI/build/js/",
			"diagnosticLogging": true
		}
	]
}
```
diagnostic logging
  ›From client: setExceptionBreakpoints({"filters":[]})
  ›To target: {"id":3,"method":"Debugger.setPauseOnExceptions","params":{"state":"none"}}
  ›From target: {"id":3,"result":{}}
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"setExceptionBreakpoints","success":true}
  ›From target: {"method":"Console.messagesCleared"}
  ›From target: {"method":"Debugger.globalObjectCleared"}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"97","url":"","startLine":0,"startColumn":0,"endLine":172,"endColumn":0,"executionContextId":2,"sourceMapURL":""}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"120","url":"http://localhost:3000/abc/js/app.js","startLine":0,"startColumn":0,"endLine":125998,"endColumn":0,"executionContextId":2,"sourceMapURL":"dist/react-breadcrumbs.min.js.map"}}
  ›Paths.scriptParsed: resolved http://localhost:3000/abc/js/app.js to c:\source\abc\ABC-GUI\build\js\app.js. webRoot: C:/source/abc/ABC-GUI/build/js/
  ›SourceMaps.createSourceMap: Reading local sourcemap file from c:\source\abc\ABC-GUI\build\js\dist\react-breadcrumbs.min.js.map
  ›SourceMaps.createSourceMap: Could not read map from c:\source\abc\ABC-GUI\build\js\dist\react-breadcrumbs.min.js.map
  ›SourceMaps.createSourceMap: Reading local sourcemap file from c:\source\abc\ABC-GUI\build\js\app.js.map
  ›SourceMap: creating SM for c:\source\abc\ABC-GUI\build\js\app.js
  ›SourceMap: no sourceRoot specified, using script dirname: c:\source\abc\ABC-GUI\build\js
  ›SourceMaps.scriptParsed: c:\source\abc\ABC-GUI\build\js\app.js was just loaded and has mapped sources: ["c:\\source\\abc\\ABC-GUI\\build\\js\\app.js"]
  ›From client: setBreakpoints({"source":{"path":"c:\\Source\\abc\\ABC-GUI\\build\\js\\app.js"},"lines":[113471],"breakpoints":[{"line":113471}]})
  ›SourceMaps.setBP: c:\Source\abc\ABC-GUI\build\js\app.js can't be resolved to a loaded script.

**Comment by roblourens** [comment]
```
›SourceMaps.scriptParsed: c:\source\abc\ABC-GUI\build\js\app.js was just loaded and has mapped sources: ["c:\source\abc\ABC-GUI\build\js\app.js"]
 ›SourceMaps.setBP: c:\Source\abc\ABC-GUI\build\js\app.js can't be resolved to a loaded script.
```

Looks like the casing is different between your webRoot and the drive (Source vs source). You may want to use `${workspaceRoot}` in your launch config so you don't have to match it manually.

The only reason I don't do a case-insensitive compare is that I don't know whether that could cause problems on some servers. But it's much more likely to bite people this way... I'll file a bug to address that.

**Comment by jeffa87** [comment]
Thanks for the help. That was my problem.
