### ISSUE TITLE
runtimeExecutable does not work with Chrome.exe

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#154]
runtimeExecutable does not work with Chrome.exe when executed from the programs folder where as local user works fine.

```json
"runtimeExecutable": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
			"runtimeArgs": [
				"--nolazy",
				"--remote-debugging-port=9222"
				
			],
```
Canary works fine.
```json
"runtimeExecutable": "C:\\Users\\justin.romaine\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe",
			// Optional arguments passed to the runtime executable.
			"runtimeArgs": [
				"--nolazy",
				"--remote-debugging-port=9222"
			],
```

**Comment by roblourens** [comment]
Meaning that it doesn't launch Chrome? Are there any errors if you run with diagnosticLogging? In the first case that is exactly [the path that I use by default](https://github.com/Microsoft/vscode-chrome-debug/blob/master/src/utils.ts#L16) so it should work.

**Comment by roblourens** [comment]
Does it not work without specifying runtimeExecutable?
