### ISSUE TITLE
Target URL search should be case-insensitive

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode-chrome-debug#156]
Code Version: 1.0.1-alpha
OS: Windows 10

I'm getting an error when launching an html file but it runs and opens in chrome correctly.

![chromedebugwarning](https://cloud.githubusercontent.com/assets/12900364/14750187/56948130-0878-11e6-8853-9e5b24a4a862.PNG)

My launch.json looks like this:
```json
{
            "name": "Launch index.html with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
```

**Comment by roblourens** [comment]
That's ok - it's just that `${workspaceRoot}` lowercases the path. I'll change this to a case-insensitive search.

**Comment by DavidRigglemanININ** [comment]
I'm seeing a similar warning, but in my case it's not an issue with the workspaceRoot being lowercased, but rather that the entire "file" is being lowercased.

Here's the relevant part of my launch.json file:
```
"name": "Launch SpecRunner.html",
"type": "chrome",
"request": "launch",
"sourceMaps": true,
"file": "${workspaceRoot}/SpecRunner.html",
"webRoot": "${workspaceRoot}",
```

And here's the warning I get:

>Warning: Can't find a page with url: /users/david/workspace/workforce-management-service/domain/specrunner.html. Available pages: ["file:///Users/david/workspace/workforce-management-service/domain/SpecRunner.html"]

The case insensitive file search solution should resolve the issue for me as well. I just thought I'd point out a slightly different variation on this issue.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#26
