### ISSUE TITLE
Better webpack sourcemap support

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-chrome-debug#158]
With the current version of this extension and webpack 1.13 I can only get devtool:"source-map" to work. In webpack 2 the default devtool setting is "#cheap-module-eval-source-map" regarding to the documentation. 
Webpack provides multiple types of inline and file based source maps: https://webpack.github.io/docs/configuration.html#devtool

It would be nice to have support for:
* cheap-module-eval-source-map
* cheap-module-source-map
* eval-source-map
* source-map _(already working)_

A sample project can be found here: https://github.com/skolmer/react-hot-boilerplate-vscode

**Comment by auchenberg** [comment]
Cool, thanks @skolmer. We are working on improving our sourcemaps support, so this is great!

**Comment by MarkPieszak** [comment]
Have you been able to get it to work with debugging TypeScript (after it's been webpack bundled) @skolmer ?

**Comment by skolmer** [comment]
@MarkPieszak I haven't checked TypeScript but debugging with webpack 1.x and `devtool: "#source-map"` should work with TypeScript too. You can take a look at the boilerplate project linked above and check launch.json, tasks.json and webpack.config.dev.js for more details.

**Comment by MarkPieszak** [comment]
Excellent I'll take a look, thanks :)

**Comment by roblourens** [comment]
I fixed the 'eval' sourcemap modes in 0.4.0. cheap-module-source-map was already working for me. Try it out and let me know!

**Comment by skolmer** [comment]
I have successful tested the following devtool settings (vscode 1.3.0-insider + chrome debugger 0.4.1):

-     cheap-module-eval-source-map
-     cheap-module-source-map
-     eval-source-map
-     source-map

Thanks! :+1:

**Comment by faceyspacey** [comment]
I just wanted to say how perfectly VSCode worked with webpack! ...for the record I was using `new webpack.SourceMapDevToolPlugin` . Not all the configuration options like `module`, `columns`, `lineToLine` work perfectly (webpack unfortunately doesnt seem to generate files that match the lines perfectly with these performance optimizations). But that's not VSCode's fault--chrome has the same problem. 


**Either way, for the first time ever I have a world class editor + debugger in one! Great work!**

**Comment by roblourens** [comment]
Awesome! How is `SourceMapDevToolPlugin` different than the `devtool` option in the config? I guess it basically just gives you more config options? And yeah it sounds like those optimizations are expected to come at the cost of debugging accuracy.

**Comment by faceyspacey** [comment]
exactly. here are the options:

https://webpack.github.io/docs/list-of-plugins.html#debugging
