### ISSUE TITLE
Chrome debug functionality to be added to Visual Studio itself?

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode-chrome-debug#159]
> (I've been looking for a better place to ask this, but doesn't seem Visual Studio itself is on Github, let me know if there's a better place to ask this)

Is there any plan (or is it already possible) to set TypeScript debugging breakpoints **inside Visual Studio**, not just VSCode? Just hoping this amazing feature gets migrated there as well one of these days. Such an incredible tool!

**Comment by roblourens** [comment]
Thanks! I think this is already possible technically, but not really advertised. I don't know a lot about it but there is a blog post here - http://lostindetails.com/blog/post/JavaScript-debugging-in-VisualStudio-with-Chrome

**Comment by MarkPieszak** [comment]
Thanks for the article Rob I'll have to look into that! 👍 
I'd hope this would migrate from Code to Studio soon fully functional! :)
