### ISSUE TITLE
Chrome is not being not shut down properly on stop debugging

### ISSUE THREAD

**Issue by aaronhoffman** [Microsoft/vscode-chrome-debug#163]
If you "stop debugging" in VSCode, and the instance of Chrome is also shut down. When you start Chrome back up, you may receive the message: "Restore Pages? Chrome didn't shut down correctly."

![image](https://cloud.githubusercontent.com/assets/109249/15635606/80947524-25a8-11e6-9393-f735da86273d.png)

I can get this to happen consistently if multiple tabs are open when "stop debugging" is executed.

This may be resolved by #92

**Comment by roblourens** [comment]
#92 will fix this, I've tried other approaches in the past with no success. Using 'attach' instead of 'launch' is another workaround.

**Comment by DrewJordan** [comment]
you can also fix this by supplying `runtimeArgs` like below in `launch.json`: 

`"runtimeArgs": [
                "--disable-infobars --disable-session-crashed-bubble"
            ]`

**Comment by ChristopherMCollins** [comment]
Only "runtimeArgs" is needed. Works fine for me without specifying "runtimeExecutable". Thanks for the workaround.

**Comment by aj-r** [comment]
In more recent versions of chrome you may need to use `--disable-session-restore` instead of `--disable-session-crashed-bubble`.
