### ISSUE TITLE
Ignore query params when trying to open source file from debug console

### ISSUE THREAD

**Issue by pjsvis** [Microsoft/vscode-chrome-debug#164]
It would make sense to ignore query params when trying to open files from the debug console EG

```
Unable to open 'Tester.controller.js?v=20165115215742': File not found (\\localhost:55693\OTS.UTP\scripts\app\partials\Tester\Tester.controller.js?v=20165115215742).
```

**Comment by roblourens** [comment]
Is this from clicking a link in the console? That's handled by vscode, which won't download a file from a url. But with this task - Microsoft/vscode-chrome-debug-core#6 - we will map the url to the source file path so vscode can open it. That would solve this, right?
