### ISSUE TITLE
Enable break on exception buttons

### ISSUE THREAD

**Issue by isRyven** [Microsoft/vscode-chrome-debug#165]
How to make VS Code to pause execution once it encounters exceptions and show the problematic line?
Seems i can't make the Code to break on error anyhow: i don't see options like: "All exceptions" and "Uncaught exceptions" in the Breakpoints section, and didn't find anything useful in the debugger docs. This seems pretty weird.

**Comment by roblourens** [comment]
You don't see these options in the Debug panel?
![image](https://cloud.githubusercontent.com/assets/323878/15724622/b4d94908-27fc-11e6-981e-2bf39907493e.png)
Try restarting or updating vscode?

**Comment by isRyven** [comment]
Yes i don't see those
![bponts](https://photos-6.dropbox.com/t/2/AAAiEPiUgjDaX-jgLCPPMMTVy_JJx7TTeb_gk088awdIUg/12/6300089/png/32x32/3/1464868800/0/2/bpoints.png/EIq_2QQYz7QdIAIoAg/7kktLBxRkHmOfA9SlDZ9I7eo0JX7FBEvMlTwOGOiWzM?size_mode=5&size=32x32 "")
Tried to restart Code several times and it's updated to the last version. Don't have any problem if using debugger for node btw, just chrome's doesn't work correctly. 
Also i don't see these break points in the chrome dev tools, they have got pause button now, which triggers pause on all exceptions.

**Comment by justin-romano** [comment]
Me neither.
![image](https://cloud.githubusercontent.com/assets/1707226/15808257/41b58076-2bc7-11e6-9f0b-cf67b65b4ff9.png)

**Comment by justin-romano** [comment]
Actually works on 1.1.1
![image](https://cloud.githubusercontent.com/assets/1707226/15808362/532c2258-2bca-11e6-986b-c5ca7c5c22d5.png)
but not on 1.2
![image](https://cloud.githubusercontent.com/assets/1707226/15808369/6f44097e-2bca-11e6-81d5-dd5349947dad.png)

**Comment by isRyven** [comment]
Hmm i got 1.1.1 doesn't work there...

**Comment by roblourens** [comment]
I see the same thing in the Insider's build. I don't know whether it's a bug, or they moved it, but I don't have control over it. I just asked about it in https://gitter.im/Microsoft/vscode

**Comment by weinand** [comment]
@roblourens please see #3015. Did you adopt that change?

**Comment by roblourens** [comment]
Fixing, thanks @weinand

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#23

**Comment by roblourens** [comment]
Fixed in 0.3.2.
