### ISSUE TITLE
Install with error

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/vscode-chrome-debug#167]
`end of central directory record signature not found`

but wait for a moment, it will be successfully installed on vscode.

**Comment by auchenberg** [comment]
Hi Cao,

Can you provide some more details of the error you get when installing?

/k

**Comment by frogcjn** [comment]
OK. I'll try again.

**Comment by joshgav** [comment]
`end of central directory record signature` sounds likes a problem reading a ZIP file, see https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers

**Comment by roblourens** [comment]
@frogcjn, this would be vscode, not something I have control over. You might want to file a bug on them or ask in https://gitter.im/Microsoft/vscode
