### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by isRyven** [Microsoft/vscode-chrome-debug#169]
Thanks for fixing breakpoints, but i still couldn't check them working :(
After updating Code to 1.2.0 and the extension to 0.3.2, i keep getting "Debug adapter process has terminated unexpectedly" error if i try to attach debugger.

![alt text](https://www.dropbox.com/s/bi59rpdlzb35006/anotherissue.png?dl=1 "")

**Comment by roblourens** [comment]
Can you set `diagnosticLoggingEnabled: true` in your launch config and share the log?

**Comment by roblourens** [comment]
Um, there was a file excluded from the extension package for some reason. Fixing now...

**Comment by roblourens** [comment]
Ok, you can't `vsce publish` the symlink from `npm link`. Still figuring out the best way to work across 2 repos. It should work in v0.3.3. Thanks for the quick report!
