### ISSUE TITLE
connot open js file:connot find js file \\localhost:8080\RSSuperviseApp\xx.js

### ISSUE THREAD

**Issue by westfalenxqq** [Microsoft/vscode-chrome-debug#171]
is there any way to replace localhost with absolute file path?

**Comment by roblourens** [comment]
Can you be more specific about what you're trying to do and where you see this error message?

**Comment by westfalenxqq** [comment]
![image](https://cloud.githubusercontent.com/assets/8254415/15952643/53ed9536-2ef5-11e6-8cb0-253cd5b6e7b0.png)
In this case,I want to click the link of js file,then check my source code in the vscode edtior.

**Comment by roblourens** [comment]
yeah, that's just vs code. It won't open a url or map it to a file on disk. I have this task to support that Microsoft/vscode-chrome-debug-core#6
