### ISSUE TITLE
Breakpoints aren't rebound after refreshing the page

### ISSUE THREAD

**Issue by isRyven** [Microsoft/vscode-chrome-debug#174]
Hey there, today i have encountered some weird problems again, my breakpoints won't pause code execution at all, they are just being ignored. 
Although if i put "throw" inside the code, debugger would then handle that and pause the runtime.
But for the rest of breakpoints it would just skip them. I have tried to reinstall the extension and restart vscode, several times, no results so far.

![alt text](https://www.dropbox.com/s/0fth46mkmn8s1k8/Screenshot%202016-06-13%2022.03.00.png?dl=1 "")

Also i can't get "diagnosticLogging" to work.

![alt text](https://www.dropbox.com/s/wmzg9diwwbtorxc/diag.png?dl=1 "")

For some reason it just ignores the setting in launch.json and doesnt write any logs.

![alt text](https://www.dropbox.com/s/yae1mqrwfi8lhe2/expl.png?dl=1 "")

Also i have found that you are shipping some unwanted files along with package, this includes debugging files and profiles. I guess that wasn't done intentionally, so i decided to mention that.

![alt text](https://www.dropbox.com/s/kuk1zxhwdnogf33/test.png?dl=1 "")

**Comment by roblourens** [comment]
"diagnosticLogging" needs to go in the configuration itself (like next to webRoot). I just cleaned up the logs, so you can be the first to tell me whether they help!

**Comment by roblourens** [comment]
You are right that I can clean up those files from the npm package. Thanks!

**Comment by isRyven** [comment]
Alright, this time i have put the "diagnosticLogging" in the right place, now it logs stuff in the console, but still can't make it to log into the txt file :( What could go wrong? 
Can you also see from the console logging that breakpoints aint being hit?

![alt text](https://www.dropbox.com/s/itn7dxyyqb9i6g8/debugger.png?dl=1 "")

**Comment by roblourens** [comment]
Ignore the file for now, I see an issue with creating the file. Fixing it.

The log would show if there is some problem with resolving sourceMaps, which is what I was expecting to see. It looks like that file isn't sourcemapped, right? You could try removing `sourceMaps: true` from your launch config, although it should work anyway.

You can also see more info by setting `verboseDiagnosticLogging: true` which we can use to be sure that the bp is being handled by chrome.

**Comment by roblourens** [comment]
If you update to 0.4.3, it will write the file. And it always writes the verbose info to the file. You should be able to drag it into a github issue to upload, if needed.

**Comment by isRyven** [comment]
Yeah last time i have removed sourceMaps key from the config, so yeah that's the reason why logging didn't show it.

Alright here is verboseDiagnostics log from the console:
`›From target: {"method":"Console.messagesCleared","params":{}}
›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"64","url":"http://localhost/opentype.js","startLine":0,"startColumn":0,"endLine":6589,"endColumn":3,"executionContextId":4,"hash":"080DFE2353627A7A0C630E26C70484762735C1E1","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
›Paths.scriptParsed: resolved http://localhost/opentype.js to c:\Users\ryv\Dropbox\coding\somefont2\opentype.js. webRoot: c:\Users\ryv\Dropbox\coding\somefont2
›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"65","url":"http://localhost/main.js","startLine":0,"startColumn":0,"endLine":319,"endColumn":1,"executionContextId":4,"hash":"A4B47DA32C917371661DCAE0DC86280BCDADC350","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
›Paths.scriptParsed: resolved http://localhost/main.js to c:\Users\ryv\Dropbox\coding\somefont2\main.js. webRoot: c:\Users\ryv\Dropbox\coding\somefont2
›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"66","url":"","startLine":0,"startColumn":0,"endLine":179,"endColumn":24,"executionContextId":4,"hash":"397ECEE1C9CCDC1A990AD8C067A1C6D7FFC66595","isContentScript":false,"isInternalScript":true,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
›From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"sup?","type":"log","url":"http://localhost/main.js","line":53,"column":17,"parameters":[{"type":"string","value":"sup?"}],"stack":{"callFrames":[{"functionName":"DrawFont","scriptId":"65","url":"http://localhost/main.js","lineNumber":53,"columnNumber":17},{"functionName":"readFont","scriptId":"65","url":"http://localhost/main.js","lineNumber":245,"columnNumber":16}]},"timestamp":1465851169.94109,"executionContextId":4}}}`

**Comment by isRyven** [comment]
Alright testing 0.4.3, debug file is being written now, which is great, also breakpoint was hit once, and after refreshing the page - never again. Here is the log:
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/312699/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
I think it might not be rebinding the breakpoints when the page is refreshed. Can you hit them if you set new breakpoints after refreshing the page? And they always work before refreshing right?

**Comment by isRyven** [comment]
I have tried to rebinding them and setting to a new position and it didn't work either. And no they never work before refreshing the page. It just was one lucky time it did work. But now it never hit the breakpoint, just ignores it completely. Funny but "throwing errors" and "debugger;" are working great and pause the timerun execution.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/312729/vscode-chrome-debug.txt)

**Comment by isRyven** [comment]
Well hmm sometimes it does hit tho, just had it 2nd time.

**Comment by roblourens** [comment]
From the log, that code is running immediately when the page loads, so after you set the breakpoint. When this bug is fixed, the breakpoint should hit immediately after refreshing the page.

**Comment by isRyven** [comment]
Oh yeah it hits if you do next: load the page -> set breakpoint -> run the callback code -> hits the breakpoint. So yeah you were right, after refreshing it doesn't rebind it.

**Comment by roblourens** [comment]
Ok, this is fixed in 0.4.4. Thanks for the report. It won't be fixed for eval scripts - Microsoft/vscode-chrome-debug-core#45
