### ISSUE TITLE
Problem Attaching to Tab

### ISSUE THREAD

**Issue by default0** [Microsoft/vscode-chrome-debug#177]
I'm using the following launch.json config:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch index.html",
            "preLaunchTask": "build",
            "type": "chrome",
            "request": "launch",
            "sourceMaps": true,
            "userDataDir": "C:\\temp\\chromeDummyDir",
            "file": "${workspaceRoot}/index.html"
        }
    ]
}
```

When I hit F5 in Visual Studio Code to launch into my index.html, I get the following error:
```
›Warning: Can't find a target that matches: file:///c:/Users/cs/Desktop/nong/index.html. Available pages: [<list of pages that I have open in my other chrome window>]
```
And immediately after, this:
```
Warning: Found more than one valid target page. Attaching to the first one. Available pages: [<same-list-as-above>]
```

Followed by it apparently attaching to whatever page happens to be the first tab I have open in the other window.

It then starts up a second chrome window with the correct file and ignores its existence entirely, causing me to be unable to debug (it also doesn't close it when I stop debugging).

I can circumvent this behaviour if I close my casual-use chrome window in the background (the one it shouldn't even care about). If I do that, I get the following output:
```
 ›Warning: Can't find a target that matches: file:///c:/Users/cs/Desktop/nong/index.html. Available pages: []
```
Repeated roughly 500 billion times, followed by the extension complaining it cannot attach and closing the chrome window it just (correctly, set to the correct file) opened.

If you're curious, all the prelaunchTask does is recompile my TypeScript sources using a minimalistic batch script, it doesn't even touch the index.html. I also get the exact same behaviour if I do not configure a prelaunchTask.

Any ideas on how to fix this?

**Comment by roblourens** [comment]
Sounds like the existing Chrome window is open with '--remote-debugging-port' set. You can try not opening that instance in remote debugging mode, or use a different port for the new window by setting the 'port' option in your launch config.

**Comment by default0** [comment]
It was! That fixed the problem. Any chance to have the extension behave better in that case (error messages, warnings, different things)?

**Comment by roblourens** [comment]
Great! Yeah, I think it should wait a little longer for the target with that expected URL to show up. I just filed Microsoft/vscode-chrome-debug-core#48 for that. Thanks for the report!
