### ISSUE TITLE
Debugger cannot attach unless you have only one version of chrome open and the url is open in a tab

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#178]
This means i cannot have any other tabs open. So basically i cannot use chrome as my browser on the same user session.
Proposed solution:
vscode chrome debugger should only attach to a process that is listenting to the port specified in the launch setting.

Flow:
1. Enumerate chrome processes/daemons loaded.
2. Determine which one is listening to the debug port
3. Attach to that session

**Comment by auchenberg** [comment]
Before VS Code is to be able to connect to Chrome, the chrome process has to be started with remote-debugging enabled. This is the reason for why all other instances of Chrome has to be killed and Chrome has to be restarted. Right now the solution is to fx use Chrome Canary for debugging.

This is a limitation of Chrome, and we have made the Chrome team aware of this as it's super inconvenient.

**Comment by justin-romano** [comment]
Thanks for responding. This is fine until Canary gets a bug that crashes
the browser when connected. Then you need to find a way to downgrade to the
correct version. I run hangouts and other background processes in my
default profile as I'm guessing a lot of users do.
So come-on team! We can do anything :-p

**Comment by roblourens** [comment]
The problem is that it *isn't* isn't listening on the debug port, since it can't be put in debug mode after it's already open.

Have you tried the `"userDataDir"` option in your launch config? Create some directory, set it to that, and it should open a new instance of Chrome, ignoring the existing one.

**Comment by justin-romano** [comment]
OK cool that's what i have been looking for. Seems like chrome must have a
default process manages the command-line from. This sounds like the
promising workaround. Tried --profile but does not work the same way.

On Thu, Jun 16, 2016 at 8:22 AM, Rob Lourens <notifications@github.com>
wrote:

> The problem is that it *isn't* isn't listening on the debug port, since
> it can't be put in debug mode after it's already open.
>
> Have you tried the "userDataDir" option in your launch config? Create
> some directory, set it to that, and it should open a new instance of
> Chrome, ignoring the existing one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode-chrome-debug/issues/178#issuecomment-226308392>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABoM2p0TJQq4WMpQqVNZSYHePcnpeSuXks5qMF8MgaJpZM4I2AVD>
> .
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by roblourens** [comment]
Glad that worked for you!
