### ISSUE TITLE
Telemetry/analytics for activation seems to be broken

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#185]
Dashboards show a quite low number of activations, which doesn't match number of installs.

We should investigate whether the activation metric/telemetry is broken or not.

**Comment by auchenberg** [comment]
Ping @nojvek

**Comment by roblourens** [comment]
This is as expected - normal extensions register for "activations" when a certain file type is opened, or a command is run, etc. Debug adapters don't use those activiations. Some of the other debug extensions also have a language service or syntax highlighting component, so they have a bunch of activations. But others like the php extension which is only a debug adapter also show 0 activations.
