### ISSUE TITLE
wrong "this" expression value

### ISSUE THREAD

**Issue by emiljas** [Microsoft/vscode-chrome-debug#186]
Steps to reproduce:
1. Start vscode debug.
2. Set breakpoint at src\vs\workbench\parts\emmet\node, line 66.
3. Add "this" expression to watch.

![vscodedebugpart](https://cloud.githubusercontent.com/assets/3979308/16362984/ea2d8e88-3bbc-11e6-84b0-3cf5e37f51ff.png)

**Comment by auchenberg** [comment]
Hi @emiljas 

Thanks for the report. 

Can you provide a few more details on your setup? `launch.json`, how to transpile your code, which runtime you target? Chrome or Node?

**Comment by emiljas** [comment]
I debug vscode in vscode [(https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging)](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging)

**Comment by roblourens** [comment]
If you look at the actual javascript, you'll see that 'this' has actually compiled to '_this', because TS compiled the arrow function to a `function` so it had to capture the 'this' from the outer scope. That's just one thing you have to keep in mind when debugging with sourcemaps.

**Comment by auchenberg** [comment]
Is this a limitation in source maps or is there something we can do here?

**Comment by roblourens** [comment]
There was a proposal to extend the sourcemap spec to add info about things that were renamed. I don't know where it's at. @andysterland might actually know. https://gist.github.com/asterland/edf028ed7947c8c258d1

**Comment by coder925** [comment]
It would be nice if there were any way for the debugger to understand this renaming because then even hovering over would work.
I have stumbled over this issue often when using the arrow function. However, now when I found out the trick to add a watch for *_this* it is not a big problem.
