### ISSUE TITLE
NaN and Infinity appear as strings instead of numbers

### ISSUE THREAD

**Issue by evanw** [Microsoft/vscode-chrome-debug#190]
Numeric values that are either NaN or Infinity show up quoted as if they are strings both in the variables window and in tooltips inside the editor view. This makes debugging unnecessarily confusing since those values are in fact numbers (using the "typeof" operator in the console says "number"). I assume this means there's some JSON-based protocol somewhere since the fact that JSON doesn't support NaN and Infinity makes this tricky to handle, but it seems strange that Chrome Developer Tools handles this and this extension doesn't.

**Comment by roblourens** [comment]
Should be fixable. Thanks!

**Comment by roblourens** [comment]
Fixed in 0.4.6 :)

**Comment by evanw** [comment]
It looks like this was fixed in [vscode-chrome-debug-core/commit/4e0835](https://github.com/Microsoft/vscode-chrome-debug-core/commit/4e0835b13a10c0b6242f02932bdb0d61dd22f569?w=1) but the fix looks suspect to me. I was expecting to see tests for these cases too:

```js
test('string', () => {
    testRemoteObjectToValue({ type: 'string', value: 'NaN' }, '"NaN"');
    testRemoteObjectToValue({ type: 'string', value: 'Infinity' }, '"Infinity"');
    testRemoteObjectToValue({ type: 'string', value: '-Infinity' }, '"-Infinity"');
});

test('number', () => {
    testRemoteObjectToValue({ type: 'number', value: '-Infinity' }, '-Infinity');
});
```

Those test cases aren't present and they fail when I add them. Shouldn't the fix for this issue be to check for `if (object.type === 'number')` instead of `if (object.value === 'NaN' || object.value === 'Infinity')` in [chromeUtils.ts](https://github.com/Microsoft/vscode-chrome-debug-core/blob/4e0835b13a10c0b6242f02932bdb0d61dd22f569/src/chrome/chromeUtils.ts#L88)? That makes all of these test cases pass for me.

**Comment by roblourens** [comment]
Ooof. Yeah, I should be doing something like that. Thanks.
