### ISSUE TITLE
Got response from target app, but no valid target pages found

### ISSUE THREAD

**Issue by fandy** [Microsoft/vscode-chrome-debug#191]
Does this extension support debugging for Meteor apps, or is there something I'm missing? I've ran `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=3000` and added to `launch.json`:

```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 3000,
            "sourceMaps": true
        }
    ]
}
```

VScode is throwing `[debugger-for-chrome] Got response from target app, but no valid target pages found`. How would I specify target pages?

**Comment by auchenberg** [comment]
Hi @fandy ,

Can I get you to add the `url` property to your `launch.json` with a value that's matching the page you wanna debug?

Please be aware that we currently have an open issue with Meteor apps and source maps, https://github.com/Microsoft/vscode-chrome-debug/issues/183

**Comment by roblourens** [comment]
Sourcemap debugging likely won't work because of #183, but you should be able to debug the generated js.

Once Chrome launches and you've loaded your page in a tab, could you post the output of `http://localhost:3000`?

**Comment by auchenberg** [comment]
Ping @fandy
