### ISSUE TITLE
Attempt to attach to page that it finds, but says no valid target pages found

### ISSUE THREAD

**Issue by shawnlauzon** [Microsoft/vscode-chrome-debug#192]
I'm attempting to attach to a page running an Angular2 mobile client. 

My launch.json:
```
        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "url": "http://192.168.1.132:8100/?restart=814919",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
```
and a partial output of http://localhost:9222/json:
```
...
{
   "description": "",
   "id": "8FF313C1-904B-4D91-AF6A-3BCC5AD5A27B",
   "title": "Programs",
   "type": "page",
   "url": "http://192.168.1.132:8100/?restart=814919"
},
...
```
If I specify the URL, there is no output on the console and gives error about no valid target pages found.

If I don't specify URL, the console displays "Found more than one valid target page. Attaching to the first one." If the first one is not the page I want, no more messages. If the first page _is_ the page I want the console fills up with the same message and then after a few seconds tells me that no valid target pages are found.

Apparently it's not having success attaching to my page.

**Comment by auchenberg** [comment]
Hi @shawnlauzon 

The reason for why you are getting the `Found more than one valid target page.` warning, is probably because you have multiple browser tabs open with the same page. Is this correct? The `url` is used as the identifier, and if there's multiple, VS Code simply doesn't know which one to choose.

**Comment by roblourens** [comment]
Could you update to 0.4.8 and try again? I fixed some stuff around attaching. Not sure whether it's your issue or not. If it still doesn't work, it would be helpful to see the logs.

In this release, your 'url' param can have wildcards, if it's more convenient to write `"192.168.1.132*"` or something like that.

**Comment by pubwebmarketing** [comment]
"192.168.1.132*"
