### ISSUE TITLE
Cannot set breakpoints in skew source

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-chrome-debug#195]
_From @alecazam on July 8, 2016 16:44_

- VSCode Version: 1.2.1
- OS Version: OSX 10.11.2

I'm trying to step debug through skew language files in VSCode using the chrome-debugger extension. These have the .sk extension.   I can't set any breakpoints on these files, but I can step through/break into the source with source maps enabled.   VSCode debugger occasionally jumps back to compiled.js file and then I can set breakpoints in the js code.  I could turn off sourceMaps, but I want to work with the original source.

remote-debugging chrome launch at 9222
webRoot www
url           http://localHost:8000/...../www/index.html

on my drive
www
source <- renamed from src due to other VSCode bug
www/source  <- symbolic link up from webRoot, only way sourceMaps are matched up

I tried setting the webroot one level up, but then even though diagnostics reports the correct sourceMap full path, break/step only occurs in the compiled.js.  This is the only method I've found to step through the .sk files.

Why can't I even set breakpoints in source files?  They're not gray, they're not red, I just cannot set them in the source.  That's with debugging enabled/disabled.

_Copied from original issue: Microsoft/vscode#8963_

**Comment by weinand** [comment]
_From @evanw on July 8, 2016 17:6_

I haven't tried this out personally but my guess is that this is because Skew uses the sourcesContent feature of source maps and VSCode has made a decision not to support debugging in this scenario (https://github.com/Microsoft/vscode-chrome-debug/issues/60).

Skew uses sourcesContent both because it keeps everything self-contained (you don't have to resort to brittle solutions like symlinks if the sources are embedded) and because the standard library sources are embedded in the compiler and don't exist on disk.

**Comment by weinand** [comment]
_From @alecazam on July 8, 2016 17:12_

I've verified that the sourceMaps work fine in Chrome debugger and that I can set breakpoints there.  So it's just VSCode that won't set breakpoints.  It appears to break/step and display the variables just fine in the .sk files.

**Comment by weinand** [comment]
@alecazam @evanw source map handling is the responsibility of individual debug extensions and has nothing to do with VS Code. So VS Code is not in the position to make any decisions to **not** support specific debugging scenarios. The node.js debugger extension supports `sourcesContent` (aka inlined content) just fine.

Since you are using the [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) extension I will move this issue to the corresponding repository.

**Comment by roblourens** [comment]
@alecazam Sounds like this isn't a sourcemap issue, this is the fact that debug adapters have to explicitly enable breakpoints in particular file types. Since there are tons of languages that compile to javascript, I just have to enable them on demand. I'll do that for Skew.

**Comment by weinand** [comment]
Since JavaScript debug extensions cannot know all the languages that can be transpiled to JavaScript, a more scalable approach is to let the extensions that introduce a language that is transpiled to JS to enable breakpoints for it.
In this case it might be [skew-vscode(https://marketplace.visualstudio.com/items?itemName=evanw.skew-vscode).
For that reason node-debug does not enable breakpoints for any other language than JavaScript.

**Comment by roblourens** [comment]
Oh, I didn't know extensions can enable breakpoints for a language without implementing a debug adapter. I think that's the right fix then.

**Comment by weinand** [comment]
Yes, that's a fundmental concept of a contribution point in VS Code: you can contribute everywhere and you can leave out every section you are not interested in.

Here is the 'debuggers' contribution for TypeScript:

```ts
		"debuggers": [
			{
				"type": "node",
				"enableBreakpointsFor": {
					"languageIds": [
						"typescript", "typescriptreact"
					]
				}
			}
		]
```

The debug type `node` doesn't matter much here because enabled breakpoints are available for all debug extensions.

**Comment by alecazam** [comment]
Adding the "debuggers" entry to the skew-vscode extension fixed the issue.  Thanks for the help there.  It's hard to know with so many json overrides which ones to set.

**Comment by weinand** [comment]
@alecazam glad, that you could fix the problem.
BTW, there are 'no overrides', there are only 'additions' ;-)
