### ISSUE TITLE
Unable to set breakpoints in .js file using Virtual Code Chrome Extension

### ISSUE THREAD

**Issue by BardoBravo** [Microsoft/vscode-chrome-debug#197]
Hello,

I have read all existing posts regarding issues with breakpoints in the Chome extension, and none of them worked for me :(

Basically, I have installed the latest versions of both NODE.JS and Visual Studio Code (with the Chrome extension), but even so whenever I launch Chrome from Visual Code, the breakpoints are never hit, and if I place any new breakpoint, they stay marked as 'Unverified Breakpoint'.

Besides that, when I create new breakppoints, the following error log is displayed in the console:
"›SourceMaps.setBP: ..\.js can't be resolved to a loaded script. It may just not be loaded yet."

Below you can find a opy of my launch.json file:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "https://localhost:8000",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "runtimeArgs": [
          "--new-window", //Open in new window
          //"--user-data-dir=C:/temp/", 
          "--remote-debugging-port=9222" 
      ],
            "webRoot": "${workspaceRoot}/webui"
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

Thanks

**Comment by roblourens** [comment]
It's probably not able to resolve the source paths in your sourcemaps to paths on disk. If you read the console logs from the `diagnosticLogging` option which you have enabled then you may be able to figure it out. Or post the log file from `~/.vscode/extensions/msjsdiag.debugger-for-chrome/vscode-chrome-debug-txt` and I can help.

**Comment by BardoBravo** [comment]
Hi,
File has been attached.
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/356256/vscode-chrome-debug.txt)

I noticed that the path where that log file was saved is different from the the .vscode generated for launch.json file:
a) C:\Users\i823001\.vscode (path for the log file)
b) C:\Users\i823001\Documents\GitHub\Bridge\bridge\.vscode (path where the launch.json was saved)

Could this be an issue?

Regards,
Cláudio Ramos

**Comment by BardoBravo** [comment]
Hi,

Checking the log I noticed the statements:

From client: setBreakpoints({"source":{"path":"c:\\Users\\i823001\\Documents\\GitHub\\Bridge\\bridge\\server\\server.js","name":"server.js"},"lines":[],"breakpoints":[]})
SourceMaps.setBP: c:\Users\i823001\Documents\GitHub\Bridge\bridge\server\server.js can't be resolved to a loaded script. It may just not be loaded yet.

It seems to be the issue. How can I solve it?

[]s

**Comment by roblourens** [comment]
In your log, I don't see any script loaded named `server.js`, or any source in a sourcemap named `server.js`. It looks like the only script with sourcemaps are some angular scripts. Are you sure that your project is built with sourcemaps, and that `server.js` is running?

**Comment by BardoBravo** [comment]
Hi,
server.js is running, as well as the other .js scripts that the systems states as 'not loaded'. All the application runs flawlessly in Chrome.
Regarding usage of sourcemaps, I am not sure. When I set the sourceMaps flag to 'False', i still get a similar error.
Is there a way to certify if I am using SourceMaps?
[]s

**Comment by roblourens** [comment]
If you debug using chrome devtools, does server.js show up?

**Comment by BardoBravo** [comment]
Nope - the .js files that I use are not displayed in the "Sources" tab file tree.

**Comment by roblourens** [comment]
Ok, well a good rule of thumb for this project is, if Chrome DevTools can't do it, we can't either :). You'll have to look at the setup for your particular project.
