### ISSUE TITLE
How to target the right tab?

### ISSUE THREAD

**Issue by Mr-Binary** [Microsoft/vscode-chrome-debug#198]
Hi. Thanks for the work.
Have an issue or just I don't know the best method to use.

Every time I tried to debug some js file.
It will open the file via the attacked Chrome instance.

But the first time is annoying, always shows some error messages:

> 
>   ›Warning: Can't find a target that matches: file:///c:/Users/camus/ClionProjects/COSC%20242/hello.html. Available pages: ["chrome://newtab/"]
> SW registered
> Mixed Content: The page at 'https://www.google.co.nz/_/chrome/newtab?espv=2&ie=UTF-8' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/rosarivo/v1/OGdIq-p0tOtBN2VMVvO9W_esZW2xOQ-xsNqO47m55DA.woff'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://www.google.co.nz/_/chrome/newtab?espv=2&ie=UTF-8' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/inconsolata/v5/BjAYBlHtW3CJxDcjzrnZCIbN6UDyHWBl620a-IRfuBk.woff'. This request has been blocked; the content must be served over HTTPS.
> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT (https://www.google.co.nz/gen_204?v=3&s=newtab&atyp=csi&ei=obN9V-eICNL0jwOT55ewBQ&adh=&xjs=init.8.3.ntp.7.jsa.1.bbd.0&p=s&npn=1&ima=1&rt=prt.41,xjsls.42,ol.130,xjses.320,xjsee.348,xjs.348,aft.40,wsrt.545,cst.0,dnst.0,rqst.5,rspt.1,rqstt.136,unt.112,cstt.112,dit.588)
> Mixed Content: The page at 'https://www.google.co.nz/_/chrome/newtab?espv=2&ie=UTF-8' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/rosarivo/v1/OGdIq-p0tOtBN2VMVvO9W_esZW2xOQ-xsNqO47m55DA.woff'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://www.google.co.nz/_/chrome/newtab?espv=2&ie=UTF-8' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/inconsolata/v5/BjAYBlHtW3CJxDcjzrnZCIbN6UDyHWBl620a-IRfuBk.woff'. This request has been blocked; the content must be served over HTTPS.
> 

I know the reason, because the first tab is the default tab opened with a google search page.
I have to manual close this page and re-debug from the editor to get the expected result.

and the second time I wanna debug, I need to close the old tab and re-debug from the editor since it will always attach to the 1st tab and the latest opened tab is obviously not the 1st one. 

Very tedious procedure, how to optimize?

**Comment by roblourens** [comment]
There's a bug here that's been around for awhile. I'm trying to fix it now. As a workaround, you could open your page `file:///c:/Users/camus/ClionProjects/COSC%20242/hello.html` in that tab, and make that the only tab open.

**Comment by roblourens** [comment]
Can you update to 0.4.8 and try again? I fixed some stuff around attaching to Chrome.

**Comment by roblourens** [comment]
Let me know if you still have a problem.
