### ISSUE TITLE
array in debugger  didn't display in right order

### ISSUE THREAD

**Issue by yeluoqiuzhi** [Microsoft/vscode-chrome-debug#199]
<img width="254" alt="screen shot 2016-07-11 at 5 10 59 pm" src="https://cloud.githubusercontent.com/assets/9261562/16725596/92e94232-478a-11e6-97cb-ac33033d7c1d.png">
<img width="278" alt="screen shot 2016-07-11 at 5 11 07 pm" src="https://cloud.githubusercontent.com/assets/9261562/16725601/965625e8-478a-11e6-8cc9-80e43e308fd7.png">

As you see above, the array that displayed in debugger is disordered.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#62
