### ISSUE TITLE
Map and debug dynamically loaded javascript file

### ISSUE THREAD

**Issue by middiu** [Microsoft/vscode-chrome-debug#205]
Hi Guys,
I'm facing an issue in debugging one of my js file that is dynamically loaded by jQuery.
Once the script is loaded (file name is **cms.main-utility.js**) it appears in Chrome Dev Tools Sources tab under "**(no domain)**" folder:
<img width="258" alt="screen shot 2016-07-20 at 8 52 09 pm" src="https://cloud.githubusercontent.com/assets/428032/16984367/d957acca-4ebc-11e6-9234-e5bae544ca66.png">

When I start the debugger  in VSC I see this message:

`›Paths.scriptParsed: could not resolve cms.main-utilitiy.js to a file under webRoot: /Users/epetrang/workspace/LMS4/SiteFiles. It may be external or served directly from the server's memory (and that's OK).`

This is my **launch.json** file:

`{
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true,
            "sourceMapPathOverrides": {
                "cms.main-utilitiy.js":"${webRoot}/cimic-files/js/cms.main-utilitiy.js",
                "http://xxxxxxxxxxxxxxx/_layouts/15/STYLES/cimic-files/*": "${webRoot}/cimic-files/*"
            }
        }`

when I add a breakpoint to the file I see this message as well:

`SourceMaps.setBP: /Users/epetrang/workspace/LMS4/SiteFiles/cimic-files/js/cms.main-utilitiy.js can't be resolved to a loaded script. It may just not be loaded yet.`

Any idea?? is there any error in my configuration?

thanks in advance

Emilio

**Comment by roblourens** [comment]
I'm guessing cms.main-utility.js is eval'd with a `@sourceUrl="cms.main-utility.js"`. Does that file have sourcemaps? If not, it won't be mapped to the file on disk, because I hadn't thought of applying the `sourceMapPathOverrides` in that case. I can make it work that way.

Also, your second entry, that starts with http, won't be applied because those only operate on the paths without the protocol/hostname. But using it that way totally makes sense, so I've filed Microsoft/vscode-chrome-debug-core#71

**Comment by roblourens** [comment]
And I filed Microsoft/vscode-chrome-debug-core#72 for the first

**Comment by roblourens** [comment]
And as a workaround, you should be able to break in that file using the debugger statement.

**Comment by middiu** [comment]
Hi roblourens, 
yes you are right **cms.main-utility.js** is eval'd with @sourceUrl="cms.main-utility.js" and no it does not have sourcemaps.

About the protocol in the second entry, VSC is still able to map js files correctly ( apart from the dynamically loaded files of course), I'll run a couple of extra tests and will let you know.

Thanks for your help

**Comment by roblourens** [comment]
Ok, makes sense. And yeah it may certainly still work, but I don't think that entry will have any effect.

**Comment by middiu** [comment]
I can confirm the second line does not have any effect.

I'm going to try using the source map for the first file.

Cheers

**Comment by middiu** [comment]
my file **cms.main-utility.js** is not minified so I'm struggling to generate source map file correctly... I think I will wait that you fix [Microsoft/vscode-chrome-debug-core#72](https://github.com/Microsoft/vscode-chrome-debug-core/issues/72)

Thanks!
