### ISSUE TITLE
Console can be output, but the breakpoint can not hit

### ISSUE THREAD

**Issue by u3u** [Microsoft/vscode-chrome-debug#206]
**Console can be output, but the breakpoint can not hit**

> Visual Studio Code
> Version: 1.3.1
> Submit: e6b4afa53e9c0f54edef1673de9001e9f0f547ae
> Date: 2016-07-12T13:35:06.227Z
> Shell: 0.37.6
> Renderer: 49.0.2623.75
> Node: 5.10.0

**launch.json**
``` JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

**Operation steps:**

1. Set target: "%USERPROFILE%\AppData\Local\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222"
2. Test access "http://localhost:9222" successful
3. _Set breakpoint_
4. Switch to "Attach to Chrome, with sourcemaps"
5. Start debugging
6. _Console display output, but the breakpoint can not hit_

**Breakpoint display gray: Not verified breakpoint**

**Comment by roblourens** [comment]
Sounds like it can't resolve your sourcemaps. If you set 'diagnosticLogging' to true, that may give you some clues. You can also upload the full log file from `~/.vscode/extensions/msjsdiag.debugger-for-chrome/vscode-chrome-debug.txt` here and I can help you figure it out.

**Comment by u3u** [comment]
Thanks you can reply me, I have already solved this problem, is my question, I am sorry.
@roblourens

**Comment by jvanlangen** [comment]
So? It would be nice to explain what the problem was....
