### ISSUE TITLE
attaching debugger after running gulp task to start server issue

### ISSUE THREAD

**Issue by khronic** [Microsoft/vscode-chrome-debug#209]
Hi Guys,

I ran into an issue when running the debugger based on the instructions provided. I am confused why the debugger keeps trying to hit http://127.0.0.1:3000/json by default rather then hitting http://127.0.0.1:3000/ by default? *Details of issue below*

*file attached is the vscode-chrome-debug.txt*
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/416063/vscode-chrome-debug.txt)

Below is the launch/attach command i am using:
`
 {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 3000,
            "sourceMaps": true,
            "diagnosticLogging": true
    },
`

When i run the "Attach with sourcemaps" in vscode debugger window i notice that it is hitting the server located at http://localhost:3000/ but the server logs shows that it is getting a bunch of 404 request for /json (see below):

GET /json 404 2.379 ms - 17
GET /json 404 1.309 ms - 17
GET /json 404 0.503 ms - 17
GET /json 404 3.757 ms - 17
GET /json 404 0.979 ms - 17
GET /json 404 1.409 ms - 17
GET /json 404 0.502 ms - 17
GET /json 404 0.748 ms - 17
 
The  vscode-chrome-debug.txt file attached is the diagnostic logging which also shows a bunch of failed responses for /json (see below).

Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
[Error] HTTP GET failed with: 404 Not Found

Could you help figure out why its keeps trying to hit /json rather then hitting http://127.0.0.1:3000/ by default?

**Comment by roblourens** [comment]
The "port" argument is the remote debugging port of chrome, not the port that your server is running on. This is typically 9222, and that's the default if you don't specify otherwise. Since you're using an "attach" config, you should have launched Chrome in debug mode with the `--remote-debugging-port` flag.

**Comment by khronic** [comment]
Hi @roblourens, 

Thanks for the reply. I changed to the launch.json to point to port 9222 *see below* and also made sure to launch chrome in debug mode with the  `--remote-debugging-port=9222` but still get the repeating /json request issue. *I attached the vscode-chrome-debug.txt diagnostic file*. Do you happen to have any other suggestions?  Thanks again for the help.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/417378/vscode-chrome-debug.txt)

`
 {
            "name": "Attach Chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "diagnosticLogging": true
  },
`

**Comment by roblourens** [comment]
If you navigate to `http://localhost:9222` in a browser when Chrome is launched, is there a response? And can you make sure that there are no other Chrome instances running when you start it? Otherwise Chrome will not actually start with remote debugging enabled. See #112 for another instance of this. If that is the issue, you might try setting the 'userDataDir' option to work around it.
