### ISSUE TITLE
Enable userDataDir by default

### ISSUE THREAD

**Issue by Andrew-MSFT** [Microsoft/vscode-chrome-debug#210]
- Have an existing instance of Chrome open that was not launched with debugging enabled
- Start debugging from VS Code

Actual: A new tab opens in the existing instance of Chrome and the debugger fails to connect.

Expected: It should open a new instance of Chrome with debugging enabled so debugging succeeds

**Comment by auchenberg** [comment]
This is limitation of Chrome, who requires all existing processes to be killed before a new instance with remote debugging enabled can be started.

@roblourens Could we use a special profile/user-dir for Chrome? I think the Mozilla folks does this to keep multiple instances running.

**Comment by roblourens** [comment]
There is an option to use a different user dir, which will work around this - set `"userDataDir"` in your launch config to some temp directory.

**Comment by roblourens** [comment]
I didn't want to enable this by default, because the Chrome instance will have none of your data, extensions, customizations, settings, and so on, which might be unexpected.

**Comment by Andrew-MSFT** [comment]
userDataDir gave me exactly what I wanted.  It may be worth thinking about how to make that more discoverable in the launch.json itself (e.g. some sort of comment)

**Comment by roblourens** [comment]
Maybe adding it but commented out would be useful. It's a common issue. Thanks for the feedback.

**Comment by roblourens** [comment]
I now have a default config with userDataDir, but I'm reusing this issue to enable userDataDir by default.
