### ISSUE TITLE
Does not break on or display common errors like 404s in the debug console.

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#211]
when debugging even with break on all exceptions turned on. it will seldom indicate useful errors.

e.g. devtools
![image](https://cloud.githubusercontent.com/assets/1707226/17826671/4d4cd818-66c7-11e6-9a69-fca7565109ef.png)

e.g. vscode-chrome
![image](https://cloud.githubusercontent.com/assets/1707226/17826640/ecba75c8-66c6-11e6-9351-767788d5203a.png)

**Comment by roblourens** [comment]
I fixed an issue just like this recently. Can you make sure that the extension is updated to the latest? And upload the log if so?

**Comment by roblourens** [comment]
And breaking on all exceptions doesn't include network errors. If it doesn't work that way in Chrome devtools, it won't work that way in the extension.

**Comment by roblourens** [comment]
LMK if it's still an issue.
