### ISSUE TITLE
Changes not reflected while debugging

### ISSUE THREAD

**Issue by snarum** [Microsoft/vscode-chrome-debug#212]
Hi,

I'm developing an angular2/typescript solution using VSCode and I'm having a weird issue. Suddenly changes to a component ts file is not reflected in the browser while debugging using the extension, but debugging in the regular chrome debugger everything works fine.

I have tried refreshing using CTRL->refresh during debugging, and even tried to reboot my machine, without any success.

To build the files I use JSPM, and this has worked very well up until yesterday. 

I'm not quite sure if this is an issue with the chrome debugging extension or something else, but my first guess is that there is some caching somewhere that is not cleaned.

Any thoughts are greatly appreciated.

Snorre

**Comment by snarum** [comment]
Update. I changed the --user-data-dir folder in launch.json to an empty folder, and then things started working again. I guess deleting the content would also do the trick.

**Comment by auchenberg** [comment]
Thanks for the report @snarum. Interesting, the assets shouldn't be cached, but glad you found a solution.
