### ISSUE TITLE
Have to restart Code after installing the extension to make it show up in Debug

### ISSUE THREAD

**Issue by stuartlangridge** [Microsoft/vscode-chrome-debug#213]
After installing this extension via the Extensions pane, it does not show up in the Debug "configs" list; after quitting and restarting Code it does then show up. This is OK if necessary, but the extension ought to tell me that that's needed (and ideally shouldn't need to do it at all).

**Comment by auchenberg** [comment]
Hi @stuartlangridge, 

Did VS Code prompt you to restart after the extension had been installed?

**Comment by stuartlangridge** [comment]
Nope. I suppose it's possible that it did and I didn't notice, but that's equivalent to not prompting :) Latest Code installed from website deb, on Ubuntu.

**Comment by auchenberg** [comment]
Interesting. Hereby noted.

**Comment by roblourens** [comment]
VS Code should prompt you to restart after every extension you install before it can be used. I can't do anything about that from the extension side.
