### ISSUE TITLE
console.log is not Display in debugger 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-chrome-debug#214]
_From @guogaigai on August 24, 2016 3:55_

- VSCode Version:1.3.1
- OS Version: ubuntu 12.04

Steps to Reproduce:

1. I Installed the Debugger for chrome extension 
2. I try to add console.log in chromeDebug.js and the vscode-chrome-debug-core/out/chrome/chromeDebugAdapter.js and other files in the same directory 
3. When i press F5 to debug webapp on chrome debugger , i can not see the console.log info i added  in the Debug Console. 

Does there is any special of the debugger to show console.log ? How can i see the logs in the debugger 

I am looking forward to your reply ,thank you very much ~

_Copied from original issue: Microsoft/vscode#10870_

**Comment by weinand** [comment]
_From @guogaigai on August 24, 2016 7:39_

@weinand  Can you answer my question ? thanks

**Comment by weinand** [comment]
The chrome debugger is a separate extension and not part of VS Code. I'll will move this issue to the correct repository.

**Comment by guogaigai** [comment]
Can i ask you another question? Is there any terminal API provided for extension developers to create a terminal with the specified path as the initially start ,thank you@weinand

**Comment by weinand** [comment]
@guogaigai as I said elsewhere: please ask @Tyriar since he is the owner of the integrated terminal. And please don't hijack issues for random questions.

**Comment by roblourens** [comment]
@guogaigai It sounds like you're trying to debug the extension itself, right? Try setting the `diagnosticLogging` option, and add more of those calls instead of using `console.log`, or check out the contributing.md page for a dev setup.

**Comment by guogaigai** [comment]
thanks for your guide , i have try as your guide ,and see the logs by logger.log  method , but do you know why  console.log not display , because i require my own js file in the chromeDebugAdapter.js , and my js file used the console.log , so how can i see the logs, thank you@roblourens

**Comment by roblourens** [comment]
console.log calls won't show up because the debug adapter is running in its own node process, logging in that process, and the console only shows logs from the target process, running in Chrome. Nothing is attached to the debug adapter process to show those calls.

If you have to, you could work around it by overwriting console.log to redirect to logger.log, something like `console.log = (msg) => logger.log(msg)`. I'm curious, what are you trying to do by modifying chromeDebugAdapter.js?

**Comment by guogaigai** [comment]
ok ,thank you for your reply , I just invoke your vscode-chrome-debug-core ,and do small modification for my own debugger@roblourens

**Comment by roblourens** [comment]
I'm glad it works!

**Comment by guogaigai** [comment]
If possible ,can you share the logic how your logger.log show the msg to the DebugConsole, thank you very much ^^@roblourens
