### ISSUE TITLE
Live editing prototype

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#216]
Build prototype of live editing using `Debugger.setScriptSource` API combined with a local file-watcher.

**Flow**
1. Detect loaded files in the browser/runtime, and keep list
2. Match loaded files with files on the file system
3. Setup file watcher for each matched file
4. When matche file change, push file content using `Debugger.setScriptSource`  to the runtime.

See https://github.com/Microsoft/vscode-chrome-debug/issues/67

**Comment by sivaraman-gmail-com** [comment]
This is a key feature to bring Visual Studio Code debugging experience on par with WebStorm or just debugging within Chrome.

**Comment by roblourens** [comment]
I'm not sure how we can provide a great experience here. It seems like a really common scenario to have files built in memory, not actually on disk, like webpack-dev-server. Also we wouldn't support it for eval scripts, which Chrome can. Then we have the issues with tools like babel-register that compile on the fly, and you have a file that claims to have the path of app.js on disk, but is actually a transpiled version of app.js. Also I'm worried about changes that would affect dependencies between files - I can imagine changes that would fail to apply unless we update the files in the right order.

I've avoided having to understand people's build configs, but with this I'd have to debug all their interesting setups. I'm not sure users will understand all the pitfalls. Is it too much to ask to reload the page? :)

**Comment by auchenberg** [comment]
Good points, but  it's indeed too much to ask people to reload the page ;)

I'm wondering if we can help make the debugger work better together with `webpack-dev-server`, that supports auto-refreshing and HMT? See http://webpack.github.io/docs/webpack-dev-server.html#automatic-refresh.

Will a module re-fetched via HMT trigger a `Debugger.scriptParsed` event, which will make the debugger fetch a new source map?

**Comment by roblourens** [comment]
I'm all for helping other tools do that work. I've used browser-sync with refreshing the page. Hot module reloading, it depends on exactly how they do it. If they swap out one object full of functions for another, then no. If they add a script tag to the page, then yes. Not sure what webpack-dev-server does.

**Comment by auchenberg** [comment]
I'm gonna spend some time diving into how each auto-refresh system works with CDP to see if there's something special we need to handle.

Adding support for live editing scenarios is the feature we need to land for the Chrome family debuggers in Q1 2017.

**Comment by con-ssc** [comment]
For live editing I just used Fiddler in between to make it possible ;) Would be great if the vscode chrome debug would manage on its own though. Would the new dev tools workspace lookup stuff shown by @paulirish help here maybe?

**Comment by auchenberg** [comment]
For now, we support live editing/reloading via Webpack HMR

**Comment by con-ssc** [comment]
@auchenberg okay, what if I don't have an app but remote debugging a single javascript file?

**Comment by auchenberg** [comment]
@con-ssc For now you could use Webpacks HMR mechanism or other live reload tools to trigger a refresh in the browser when you make changes. This should work with single files too.

**Comment by andrew-w-ross** [comment]
@auchenberg I'm attempting to try the live editing with vscode that you outlined in your medium post above but with fuse-box instead of webpack, [here is my attempt](https://github.com/andrew-w-ross/fuse-debug). It works well for debugging but seems to stop breaking at break points when the code changes.

I'm guessing the source-map change isn't being picked up until the debugger is restarted. I'm assuming it's something to do with the file watcher not picking up the change and calling `Debugger.setScriptSource`. Do you mind detailing what files `vscode-chrome-debug` watches and how it determines them?

If you wan't to recreate my issue you can do the following:
- Hit F5 to start fuse-box and the debugger
- Put a breakpoint [here](https://github.com/andrew-w-ross/fuse-debug/blob/master/src/components/Adder.tsx#L19)
- Change the value being added and the break point will no longer break

**Comment by auchenberg** [comment]
@andrew-w-ross I'm not familiar with how the internals of fuse-box work, but we have enabled live editing via WebPack's HMR, that works by pushing a new bundle + sourcemap as a script to Chrome, which our debugger than picks up via the `Debugger.scriptParsed` event, that overrides the existing sourcemap, and then enables breakpoints to re-map after a HMR change has been pushed.

This solution enables us NOT to have yet another file watcher in the debugger, and wire-up `setScriptSource` as we so-to-say have outsourced the responsibility of pushing updates to the bundler, which knows about transpilers, etc.

We should create a seperat issue on getting the debugger to work with FuseBox.
