### ISSUE TITLE
Just My Code / Blackboxing

### ISSUE THREAD

**Issue by markusjohnsson** [Microsoft/vscode-chrome-debug#217]
Is there a feature like Chrome Developer Tools' "Blackboxing" or Visual Studio's "Enable Just My Code" that hides select scripts from debugging? I.e. even though "All Exceptions" is checked, it does not break in those script files.

**Comment by roblourens** [comment]
No, not yet. If All Exceptions is checked, it should break on any exception, as long as it has that behavior in Chrome DevTools.
