### ISSUE TITLE
Response from target seems invalid

### ISSUE THREAD

**Issue by BagelTheKid** [Microsoft/vscode-chrome-debug#218]
I'm trying to debug my AngularJS app, but it seems the debugger is having difficulty attaching the workspace properly. 
I've attached the verbose log. But here is what I'm getting through the console
`Error: Response from the target seems invalid: g:\Nicolas\Practice\rogue-map-gen\/app/index.html`
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/446408/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
The response at this point is supposed to be JSON representing a list of available targets. `port` should be the port that Chrome was launched in debugging mode with, like `--remote-debugging-port=3000`. Is it your webserver port instead?

**Comment by BagelTheKid** [comment]
It is, I'll try setting the remote debugging port to that then

**Comment by BagelTheKid** [comment]
Unless the debugging port needs to be different...

**Comment by roblourens** [comment]
Yeah so the webserver gets one port, and Chrome gets a different port for debugging.
