### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by LincB** [Microsoft/vscode-chrome-debug#219]
I'm unable to start a debugging session, getting a page showing "This page can't be shown: localhost refused to connect" and a debug log ending with "Failed to load resource: net::ERR_CONNECTION_REFUSED (http://localhost/index.html)". The verbose log is copied below. I've looked through the troubleshooting guide and past issues, but nothing has helped.

I'm on a Mac, OS X 10.10.5. I can access localhost:9222/json, so I don't think the issue is with remote debugging not being enabled, as others have experienced in the past. Does anyone have any advice, or next steps to try?

Here is my configuration:
```
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true
        }
```

Here is the verbose log:
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/450432/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
Do you have a web server that's supposed to be serving index.html? If you navigate to that URL manually in a browser, does the page load?

It kind of sounds like it's just not finding anything at that address.

**Comment by LincB** [comment]
Ok, this was my mistake! I assumed that this extension ran its own server to provide HTML/CSS/JS on localhost. I switched my configuration from url to file and it's now working.

Since your example configuration includes a localhost url, you could consider adding a note that a separate web server is required to use that configuration.

Thanks for your help!

**Comment by rajeshrudra007** [comment]
Hi ,

I am getting error while submit the button "localhost:8080/getAllCustomers Failed to load resource: net::ERR_CONNECTION_REFUSED".
Here i am implementing project using technologies Eureka, Ribbon, Zuul gateway.
Can you please help me how can i resolve this issue.
