### ISSUE TITLE
"Run mode" - Support for launch without debugging

### ISSUE THREAD

**Issue by jan-zajic** [Microsoft/vscode-chrome-debug#220]
Please add support for nodebug : true parameter (Run mode - launch with ctrl+f5, see https://code.visualstudio.com/docs/editor/debugging#_run-mode).  It was implemented in https://github.com/Microsoft/vscode/issues/2780. This should simple launch Chrome with specified url, without any debuger attaching, so we can use for examples dom inspector, debug css styles or use integrated debugger, which is sometimes better option.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#89

**Comment by faceyspacey** [comment]
i definitely agree the capability to switch back and forth from the chrome devtools and debugging in VSCode would be very beneficial. Particularly being able to re-attach to your browser window and take control back from chrome devtools.
