### ISSUE TITLE
How to make this work with electron apps

### ISSUE THREAD

**Issue by xwvvvvwx** [Microsoft/vscode-chrome-debug#222]
I'm working on a typescript / electron boilerplate project [here](https://github.com/xwvvvvwx/typescript-react-electron-boilerplate), and I would like to include a `.vscode/launch.json` that can launch and attach to the app for debugging, but I can't get it working properly (app launches, but code execution does not stop on breakpoints).

I was playing around with the vscode repo and I noticed that this was working really nice.([`launch.json`](https://github.com/Microsoft/vscode/blob/master/.vscode/launch.json), [`code.sh`](https://github.com/Microsoft/vscode/blob/master/scripts/code.sh)) 

I attempted to modify their config [in this branch](https://github.com/xwvvvvwx/typescript-react-electron-boilerplate/tree/vscode_debugger_integration) ([`launch.json`](https://github.com/xwvvvvwx/typescript-react-electron-boilerplate/blob/vscode_debugger_integration/.vscode/launch.json), [`launch.sh`](https://github.com/xwvvvvwx/typescript-react-electron-boilerplate/blob/vscode_debugger_integration/scripts/launch.sh)), but I couldn't get it working (again app launched, but breakpoints were skipped).

The approach outlined in [this blogpost](http://electron.rocks/debugging-electron-in-vs-code-revised/) also failed.

Do you have any ideas on what I am doing wrong?

**Comment by roblourens** [comment]
Does the `debugger` keyword work? Do the breakpoints bind (turn solid red)?

Can you set the `diagnosticLogging` option in your launch config and upload the file from `~/.vscode/extensions/msjsdiag.debugger-for-chrome/vscode-chrome-debug.txt` here?

**Comment by roblourens** [comment]
Also I want to mention that debugging electron isn't 'officially supported' by this extension. It should work, but I haven't tested it with different versions of electron, different configurations, and so on.

**Comment by xwvvvvwx** [comment]
Thanks for the reply!

1. The debugger keyword pauses execution in the chrome devtools, but not in vscode. 
2. The breakpoints do turn solid red.

Both behaviours can be seen in this gif:
![recording](https://cloud.githubusercontent.com/assets/6689924/18265062/111232c6-7414-11e6-887d-a9314227abf7.gif)

Logs are attached below:
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/456144/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
Sorry for the slow response - you can't use this at the same time as using chrome devtools because only one debugger can be attached. Looking at the logs, vscode actually attaches to the chrome devtools instance.

**Comment by roblourens** [comment]
Maybe try without the code that launches devtools?
