### ISSUE TITLE
Need to refresh page in Chrome for breakpoints to hit

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#223]
_From @pankleks on September 4, 2016 10:7_

- VSCode Version: 1.4.0
- OS Version: Windows 10
- Chrome debug ext: 0.5.2

When debugging app, Chrome is opened, VS debug console shows JS console outputs, but breakpoints does not fire.
When I go to Chrome and hit refresh - all is fine.

I'm running clean session of Chrome, VS is opening Chrome.

_Copied from original issue: Microsoft/vscode#11513_

**Comment by roblourens** [comment]
Is this code that runs right away when the page loads? We can't bind breakpoints immediately in Chrome, so in that case, they can't be hit until the page is refreshed.

**Comment by mattyork** [comment]
"We can't bind breakpoints immediately in Chrome"

Can you add this to the documentation? This is tripping up our developers trying to use this extension.

**Comment by roblourens** [comment]
It is in the documentation, but I added another sentence to make it stand out a little more.
