### ISSUE TITLE
Debug with webpack and https doesn't work

### ISSUE THREAD

**Issue by Tre665** [Microsoft/vscode-chrome-debug#224]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Hi, I am using the following repo to develop an angular2 app.

[https://github.com/AngularClass/angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter)

With the default http connection it works really great together with VS Code and also the debugger works with no problems.

Unfortunately we need the app to be served from a HTTPS domain because
- we authorize the user via OAuth2 / OpenId connect 
- our backend server only allow (authorized) connections via HTTPS / TLS 
To serve the app via SSL I added the `--https` flag to the startup flags of the WebPack dev server and added the following startup script to the `package.json` file.

`"server:dev:ssl": "npm run server:dev -- --https"`

With that change the login and the API calls work, but unfortunately the debugging from Visual Studio doesn't work anymore.

The output in the console is the following:

`  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.bundle.js.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.bundle.js.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.map
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.bundle.js.map`

My first thought was that i missed a config or something and that the sourcemaps may be still served from http://localhost and not from https://localhost.
So I checked the Urls and it seams that the maps are generated correct. 
In the browser the requested URLs
- https://localhost:3000/polyfills.map
- https://localhost:3000/vendor.map
- https://localhost:3000/main.map
returns the sourcemaps correctly from https.

To further debug the issue i enabled the VSCode Chrome Debuggers diagnostic loging feature via the following addition in the config file for the debugger ( `.vscode/launch.json`). 

`"diagnosticLogging": true,`

Unfortunately with no new hints that could help to solve the issue.
I can post the logs if it somewhat helps.

As a side note: 
When I debug in Chrome the breakpoints are hit correctly (although not in my current project which is not updated to Webpack 2 yet, but it works with the current master) 

* **What is the expected behavior?**
That the breakpoints are also hit within VSCode with https enabled

* **Please tell us about your environment:**
- latest master of webpack starter repo
- node v 6.3
- npm 3.10.3
- Tested on Mac OSX 10.10.5 and Windows 10 (without the anniversary update)
- Angular RC6
- Browser: all
- Webpack 1 (OSX) and Webpack 2(Win)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I am not sure if it is an issue of this webpack 2 repo or webpack dev server or the chrome debugger or that I made something wrong with the configuration (still learning webpack).
Because I think that this is a common requirement (use https) I hope that someone has also run into this issue which can help to solve the issue.

**Comment by roblourens** [comment]
Hm, unfortunately I don't log the actual error message when that download fails. I'll add the error message in the next update. So those URLs are correct? Can you check from incognito mode, or from another browser where you're not logged in? If you have to be logged in to download the files, it won't work.

**Comment by roblourens** [comment]
Actually, is there no 'HTTP GET failed with: ...' message in the log before those other messages?

**Comment by Tre665** [comment]
Hi, thank you for looking into the issue.
I have made your suggested checks. I can view the mapping files from another browser and also from chrome incognito mode. The Url is the first URL that the debugger tries to download.

I am also sorry that I may created some confusion about the statements about the login. I had just mentioned that to explain the reason why I needed the https feature. But the problem also occurs with no login flow involved. 

I have also searched the debugger logs for the 'HTTP GET failed with: ...' message. I get some messages that it tries to access the file, but not with exact same string 'HTTP GET failed with: ...'.
Instead it says `SourceMaps.loadSourceMapContents: Downloading sourcemap file from `

With diagnosticLogging turned off the output is:
`  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.map   (Note: this URL is available by other browsers)

  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.bundle.js.map

  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.map (Note: this URL is available by other browsers)

  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.bundle.js.map

  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.map (Note: this URL is available by other browsers)

  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.bundle.js.map
`

And with diagnosticLogging enabled (here are also the logs where it tries to GET the files and I stripped out some things that I thought that are not needed):
`Verbose logs are written to /Users/$USER/.vscode/extensions/msjsdiag.debugger-for-chrome-0.5.2/vscode-chrome-debug.txt
OS: darwin x64
Node: v5.10.0
vscode-chrome-debug-core: 0.1.19
debugger-for-chrome: 0.5.2
From client: initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}]}}
From client: launch({"name":"Launch HTTPS localhost with sourcemaps","type":"chrome","request":"launch","url":"https://localhost:3000/","sourceMaps":true,"diagnosticLogging":true,"webRoot":"/Users/$USER/DevProjects/Project/webclient","userDataDir":"/Users/$USER/DevProjects/Project/webclient/.vscode/chrome"})
spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--user-data-dir=/Users/$USER/DevProjects/Project/webclient/.vscode/chrome","https://localhost:3000/"])
Discovering targets via http://127.0.0.1:9222/json
Discovering targets via http://127.0.0.1:9222/json
Discovering targets via http://127.0.0.1:9222/json
Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/516a5537-1895-484a-b72e-eb1630e5c248","id":"516a5537-1895-484a-b72e-eb1630e5c248","thumbnailUrl":"/thumb/516a5537-1895-484a-b72e-eb1630e5c248","title":"","type":"page","url":"https://localhost:3000/","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/516a5537-1895-484a-b72e-eb1630e5c248"}
WebSocket Url: ws://127.0.0.1:9222/devtools/page/516a5537-1895-484a-b72e-eb1630e5c248
To target: {"id":1,"method":"Debugger.enable"}
From target: {"id":1,"result":{}}
To target: {"id":2,"method":"Console.enable"}
From target: {"id":2,"result":{}}
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
From client: setBreakpoints({"source":{"path":"/Users/$USER/DevProjects/Project/webclient/src/app/authentication/authentication-guard.service.ts","name":"authentication-guard.service.ts"},"lines":[16,18],"breakpoints":[{"line":16},{"line":18}],"sourceModified":false})
SourceMaps.setBP: /Users/$USER/DevProjects/Project/webclient/src/app/authentication/authentication-guard.service.ts can't be resolved to a loaded script. It may just not be loaded yet.
From target: {"method":"Console.messagesCleared","params":{}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"https://code.jquery.com/jquery-2.2.3.min.js","startLine":0,"startColumn":0,"endLine":5,"endColumn":0,"executionContextId":1,"hash":"0C5A5D012C587821E8760DD7A52080F0778C1DC2","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve https://code.jquery.com/jquery-2.2.3.min.js to a file under webRoot: /Users/$USER/DevProjects/Project/webclient. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"https://cdnjs.cloudflare.com/ajax/libs/three.js/r73/three.min.js","startLine":0,"startColumn":0,"endLine":871,"endColumn":0,"executionContextId":1,"hash":"64CF63B162F751A7AC52AD86B05628D1679D3224","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve https://cdnjs.cloudflare.com/ajax/libs/three.js/r73/three.min.js to a file under webRoot: /Users/$USER/DevProjects/Project/webclient. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"https://localhost:3000/webpack-dev-server.js","startLine":0,"startColumn":0,"endLine":2,"endColumn":8606,"executionContextId":1,"hash":"729FFC3002628528C3C336A4F6373053DD1C5562","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve https://localhost:3000/webpack-dev-server.js to a file under webRoot: /Users/$USER/DevProjects/Project/webclient. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"50","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":3,"executionContextId":0,"hash":"DED4D86051B774094CB5762843D429DC872EBA18","isContentScript":false,"isInternalScript":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"51","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":2,"executionContextId":0,"hash":"1110BA42E4E4F1BA4CB5762843D429DC872EBA18","isContentScript":false,"isInternalScript":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"52","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":2,"executionContextId":0,"hash":"8193CF03E4E4F1BA4CB5762843D429DC872EBA18","isContentScript":false,"isInternalScript":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"https://localhost:3000/polyfills.bundle.js","startLine":0,"startColumn":0,"endLine":16269,"endColumn":34,"executionContextId":1,"hash":"4A9FFF72AE009F596300BA60764BD9B016AB05D7","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"polyfills.map","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve https://localhost:3000/polyfills.bundle.js to a file under webRoot: /Users/$USER/DevProjects/Project/webclient. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for https://localhost:3000/polyfills.bundle.js by URI: polyfills.map and webRoot: /Users/$USER/DevProjects/Project/webclient
**SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://localhost:3000/polyfills.map**
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://localhost:3000/polyfills.bundle.js.map
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/polyfills.bundle.js.map
From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"54","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":3,"executionContextId":0,"hash":"DED4D86051B774094CB5762843D429DC872EBA18","isContentScript":false,"isInternalScript":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"55","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":2,"executionContextId":0,"hash":"1110BA42E4E4F1BA4CB5762843D429DC872EBA18","isContentScript":false,"isInternalScript":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"56","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":2,"executionContextId":0,"hash":"8193CF03E4E4F1BA4CB5762843D429DC872EBA18","isContentScript":false,"isInternalScript":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"AB1DDDC0E5FB8300ECC80ED4F7FF84D50BB47543","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}

// stripped out some From target files.....

Paths.scriptParsed: could not resolve https://localhost:3000/vendor.bundle.js to a file under webRoot: /Users/$USER/DevProjects/Project/webclient. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for https://localhost:3000/vendor.bundle.js by URI: vendor.map and webRoot: /Users/$USER/DevProjects/Project/webclient
**SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://localhost:3000/vendor.map**
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://localhost:3000/vendor.bundle.js.map
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/vendor.bundle.js.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"73","url":"https://localhost:3000/main.bundle.js","startLine":0,"startColumn":0,"endLine":25706,"endColumn":29,"executionContextId":1,"hash":"2DF457D26CC43DA984987AB414A7B967E3746A10","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"main.map","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve https://localhost:3000/main.bundle.js to a file under webRoot: /Users/$USER/DevProjects/Project/webclient. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for https://localhost:3000/main.bundle.js by URI: main.map and webRoot: /Users/$USER/DevProjects/Project/webclient
**SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://localhost:3000/main.map**
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from https://localhost:3000/main.bundle.js.map
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from https://localhost:3000/main.bundle.js.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"74","url":"script:///Users/$USER/DevProjects/Project/webclient/node_modules/source-map-loader/index.js!/Users/$USER/DevProjects/Project/webclient/src/assets/js/awv.min.js","startLine":0,"startColumn":0,"endLine":6,"endColumn":195,"executionContextId":1,"hash":"46E247630B24C9505957EF6676588CE246AA0900","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":true,"deprecatedCommentWasUsed":false}}

// stripped out the the rest of the comments.....
`

**Comment by roblourens** [comment]
Ok, I just realized that there is a different method for making https requests in Node. I'll have to fix that. Thanks for the report!

**Comment by roblourens** [comment]
And apparently I knew that already, tracked in https://github.com/Microsoft/vscode-chrome-debug-core/issues/65
