### ISSUE TITLE
When resolving sourceMapPathOverrides, permit use of ${webRoot} or ${workspaceRoot} 

### ISSUE THREAD

**Issue by samconn** [Microsoft/vscode-chrome-debug#226]
I'm using the _preview release_ of angular-cli which has shifted to using webpack (2.1.0-beta.22) for supporting RC6.

I ran into the dreaded "unverified breakpoint" issue and tried a bunch of combinations before stumbling on the following `launch.json` configuration which works:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "sourceMaps": true, 
            "webRoot": "${workspaceRoot}",

            "sourceMapPathOverrides": {
                "webpack:///C:/Depot/Impakt/DNA/DNACore/*": "${webRoot}/*" // SUCCEEDS
                //"webpack:///${workspaceRoot}/*": "${webRoot}/*" // FAILS
                //"webpack:///${webRoot}/*": "${webRoot}/*"  // FAILS
            },         

            // Uncomment this to run easily alongside another running instance of Chrome
            "userDataDir": "${workspaceRoot}/.vscode/chrome"

            // Uncomment this to get diagnostic logs in the console
            //,"diagnosticLogging": true
        }
}
```

Since my ${workspaceRoot} is already `C:\Depot\Impakt\DNA\DNACore`, i.e., the same hard-coded value I need to set on the left-side of the override, I'm curious if, when detected, the value of either the ${webRoot} or ${workspaceRoot} variables can be resolved prior to attempting the source map matching.

I've attached diagnostic logs from each of my attempts.

[vscode-chrome-debug_WithoutSourceMapPathOverrides_FAILS.txt](https://github.com/Microsoft/vscode-chrome-debug/files/466608/vscode-chrome-debug_WithoutSourceMapPathOverrides_FAILS.txt)
[vscode-chrome-debug_WithSourceMapPathOverrides_SUCCEEDS.txt](https://github.com/Microsoft/vscode-chrome-debug/files/466609/vscode-chrome-debug_WithSourceMapPathOverrides_SUCCEEDS.txt)
[vscode-chrome-debug_WithWebRootSourceMapPathOverrides_FAILS.txt](https://github.com/Microsoft/vscode-chrome-debug/files/466610/vscode-chrome-debug_WithWebRootSourceMapPathOverrides_FAILS.txt)
[vscode-chrome-debug_WithWorkspaceRootSourceMapPathOverrides_FAILS.txt](https://github.com/Microsoft/vscode-chrome-debug/files/466607/vscode-chrome-debug_WithWorkspaceRootSourceMapPathOverrides_FAILS.txt)

**Comment by roblourens** [comment]
Thanks for the report! I can definitely resolve those patterns on the left side too. I try a few sourceMapPathOverrides by default so that some configs will work out of the box, and could probably add one for this case too.

**Comment by samconn** [comment]
Thanks!

**Comment by mpriem** [comment]
Sorry for hijacking this thread. I have tried everything to get VSCode to hit breakpoints in my ng-cli generated project, and could really use some help.

I'm running Windows 10, node 6.10.0, npm 3.10.10, ng-cli 1.0.0-rc.1, VSCode 1.10.2 with chrome debugger 2.6.0.

I simply create a new project using ng-cli --> ng new TestProject

I add some code to app.component.ts to be able to set a breakpoint.

`import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  constructor (){
    var newtitle:string = 'App does not work!'
    this.title = newtitle
  }
}
`
After starting the project with ng serve I can set breakpoints using Chrome dev tools.

When I use VSCode however the breakpoint is never hit. The breakpoint will grey out with the message the code is not found. I have enabled tracing, and it seems the source maps are correctly loaded (see attached filed), but the problem persists.

Any ideas?

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/835721/vscode-chrome-debug.txt)

my launch.json:

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200/",
            "sourceMaps": true,
            "trace": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:///*": "/*"
            }
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            /*"diagnosticLogging": true,*/
            "webRoot": "${workspaceRoot}",
            "url": "http://localhost:4200/*",
            "sourceMapPathOverrides": {
                "webpack:///*": "/*"
            }
        }
    ]
}
`

**Comment by roblourens** [comment]
How did you come up with that sourceMapPathOverrides entry? I see you have sourcemap entries like `"webpack:///./src/main.ts"`, so you need something that maps that to your workspaceRoot. This might be covered by one of the defaults, so you might try removing the sourceMapPathOverrides first. Then I recommend using `.scripts` to debug it, see the readme for details.

**Comment by mpriem** [comment]
Hi Rob, sometimes it can be so easy. Removing the sourceMapPathOverrides solved the issue.

**Comment by bborad** [comment]
Same, removing sourceMapPathOverrides solved the problem.  @roblourens Thanks

**Comment by roblourens** [comment]
The webRoot part of this is fixed. An issue is open in the vscode repo for workspaceRoot. I think that's all this covers.
