### ISSUE TITLE
No targets listed at localhost:9222

### ISSUE THREAD

**Issue by jshanman** [Microsoft/vscode-chrome-debug#227]
Hi,

I'm trying to debug safari on an iphone SE using windows + visual studio code with the Debugger for iOS Web (0.1.2) installed.

My environment:
Windows 10
Google Chrome  52.0.2743.116
Visual Studio Code (1.5.2) installed today
Debugger for iOS Web (0.1.2) installed today
iTunes 12.5.1.21 (installed today & rebooted machine)

iPhone SE mllx2ll/a
iOS 10.0.1 14a403
Safari 602.1.5

Launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Navigate to current project on an iOS device",
            "type": "ios",
            "request": "launch",
            "port": 9222,
            "url": "index.html",
            "webRoot": "${workspaceRoot}",
            "deviceName": "*",
            "tunnelPort": 8080
        },
        {
            "name": "Navigate to url on an iOS device",
            "type": "ios",
            "request": "launch",
            "port": 9222,
            "url": "http://mysite.com/index.html",
            "webRoot": "${workspaceRoot}",
            "deviceName": "*"
        },
        {
            "name": "Attach to an iOS device",
            "type": "ios",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}",
            "deviceName": "*",
            "diagnosticLogging": true
        }
    ]
}`

Going to localhost:9222/json while it is attempting to connect returns
`[]`

in iTunes, I can see that 'iphone' is connected. I clicked "allow access" on the firewall prompt that came up, and clicked "trust" on the iphone when the usb was connected to the PC.

debug output:

  ›OS: win32 ia32
  ›Node: v5.10.0
  ›vscode-chrome-debug-core: 0.1.16
  ›debugger-for-ios-web: 0.1.2
  ›spawn('C:\Users\user\.vscode\extensions\msjsdiag.debugger-for-ios-web-0.1.2\node_modules\vs-libimobile\lib\ios_webkit_debug_proxy.exe', ["--no-frontend","--config=null:9222,:9223-9323"])
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Error: Got a response from the target app, but no target pages found
    at Object.errP (C:\Users\user\.vscode\extensions\msjsdiag.debugger-for-ios-web-0.1.2\node_modules\vscode-chrome-debug-core\out\src\utils.js:225:13)
    at C:\Users\user\.vscode\extensions\msjsdiag.debugger-for-ios-web-0.1.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeTargetDiscoveryStrategy.js:13:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by auchenberg** [comment]
Hi @jshanman 

Have you enabled "Web Inspector" on your iOS device? See https://github.com/Microsoft/vscode-ios-web-debug#ios-device

**Comment by jshanman** [comment]
Yes, web inspection is enable under the Safari settings.

**Comment by auchenberg** [comment]
Okay.

Which debug type are you trying to use `attach` or `launch`? Make sure Safari is open on the device, and the phone is unlocked.

When using the `Navigate to current project on an iOS device` you should see Safari navigate to a url from the HTTP tunnel.

**Comment by jshanman** [comment]
Thanks for troubleshooting this with me, I appreciate it.

I am using "attach". Safari is open to google.com and the device is unlocked.

I do have fiddler installed but I've tried it with fiddler both enabled and disabled.

**Comment by auchenberg** [comment]
Ah @jshanman, if you are using the `attach` config, then the `url` must match one of the open tabs in Safari, as the property is used to identify correct tab. When using the `attach` config you are usually targeting a locally available dev-environment, where you have the source code open in VS Code.

**Comment by jshanman** [comment]
Hm. Ok, the default launch.json file didn't have a "url" entry so I didn't expect that it was needed.

I added a "url" property to the "attach" profile but I still have the same issue.  I would expect that adding a url there would only serve to select which option from the http://127.0.0.1:9222/json to use, but that request returns an empty json array.  I just updated the device to the latest iOS 10. 

I just found this: https://github.com/artygus/ios-webkit-debug-proxy-win32/issues/22 perhaps this is related?

**Comment by auchenberg** [comment]
That's a good point. I'll get the `attach` examples updated. We need to be able to identity which tab to "connect" VS Code too. Just like you select DevTools for a given browser tab in your desktop browser.

Yes, I'm afraid that's another problem. We don't support iOS10 at the moment.

**Comment by ethan-deng** [comment]
This build works for me for iOS 10.

https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-win64.zip/download
