### ISSUE TITLE
Can't Load the file added breakpoint

### ISSUE THREAD

**Issue by xuecat** [Microsoft/vscode-chrome-debug#229]
My `launch.json` file:

    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "runtimeArgs": [ "--remote-debugging-port=9222" ],
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/public",
            "diagnosticLogging": true,
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "port": 9222,
            "sourceMaps": true
        }
    ]

Error:
 
    ›SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in debugadapter://86
    ›SourceMap: creating for debugadapter://86
    ›SourceMap: sourceRoot: undefined
    ›SourceMap: sources: ["example.js"]
    ›Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.
    ›SourceMap: webRoot: c:\Users\wq\Desktop\react-tutorial/public
    ›SourceMap: no sourceRoot specified, using webRoot + script path dirname: c:\Users\wq\Desktop\react-tutorial\public
    ›SourceMaps.scriptParsed: debugadapter://86 was just loaded and has mapped sources: ["c:\\Users\\wq\\Desktop\\react-tutorial\\public\\example.js"]
    Download the React DevTools for a better development experience: https://fb.me/react-devtools
    You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/
    ›SourceMaps.setBP: c:\Users\wq\Desktop\react-tutorial\public\scripts\example.js can't be resolved to a loaded script. It may just not be loaded yet

What's problem?    Thanks.

**Comment by montrealist** [comment]
I'm guessing, but one of the reasons could be the inlined sourcemaps:

```
›Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.
```

Try to generate JS files without sourcemaps being in the same file and see if anything changes.

**Comment by auchenberg** [comment]
Caused by inline source maps. Duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/230

**Comment by roblourens** [comment]
`›SourceMaps.scriptParsed: debugadapter://86 was just loaded and has mapped sources: ["c:\\Users\\wq\\Desktop\\react-tutorial\\public\\example.js"]`
`›SourceMaps.setBP: c:\Users\wq\Desktop\react-tutorial\public\*scripts*\example.js`
The 'scripts' segment is missing - I don't have enough info to tell you for sure but you either need to add '/scripts' to your webroot, or fix your build to add it to the sourceRoot or sources.

**Comment by auchenberg** [comment]
Ping @xuecat

**Comment by xuecat** [comment]
Thanks for so much, I have resolved.
