### ISSUE TITLE
Add support of inlined sources

### ISSUE THREAD

**Issue by kkovalevskiy** [Microsoft/vscode-chrome-debug#230]
At the moment when I try to debug code uses some 3d party libs with source maps having inlined sources, I get the following message in the log
`Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.`
and as consequence, when I navigate through call stack, I have to read and investigate already compiled source.

There're several libs/frameworks that ship their bundles with inlined sources into sourcemaps, without any source *.ts files (for example, angular2). It would be great if this extension can handle such source maps.

**Comment by roblourens** [comment]
Yes - I've been working on this and it should be supported next time I update it - not exactly sure when that will be

**Comment by roblourens** [comment]
This has shipped
