### ISSUE TITLE
Question: breakpoints not attaching (TypeScript / Grunt)

### ISSUE THREAD

**Issue by montrealist** [Microsoft/vscode-chrome-debug#231]
Hi! In need of config help; I got Chrome launching fine but it's not stopping at breakpoints inside VSCode.

JS files are being produced by Grunt(`ts` and `uglify` tasks). Sourcemaps for individual JS files in `src/` are populated after running `tsc --sourcemap` in terminal manually.

### Debug console error
```
> SourceMap: creating for http://localhost:9500/dist/js/editor.min.js
> SourceMap: sourceRoot: /
> SourceMap: sources: ["editor.js"]
> SourceMap: webRoot: /project/examples
> SourceMap: resolved sourceRoot / -> /project/examples/
> SourceMaps.scriptParsed: http://localhost:9500/dist/js/editor.min.js was just loaded and has mapped sources: ["/project/examples/editor.js"]
> SourceMaps.setBP: /project/src/View.ts can't be resolved to a loaded script. It may just not be loaded yet.
```

### File structure
```
|-- .vscode
    |----- launch.json
    |----- tasks.json
|-- dist
    |-- js
        |----- editor.js
        |----- editor.min.js
        |----- editor.min.js.map
|-- examples
    |----- index.html
|-- src
    |----- App.ts
    |----- Controller.ts
    |----- Model.ts
    |----- View.ts
|-- node_modules
    |-- [..]
|-- package.json
|-- Gruntfile
|-- tsconfig.json
```

### Relevant launch.json config
```
{
    "name": "Launch with sourcemaps",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:9500/",
    "webRoot": "${workspaceRoot}/examples",
    "sourceMaps": true,
    "preLaunchTask": "grunt",
    "userDataDir": "${workspaceRoot}/.vscode/chrome",
    "port": 9222,
    "runtimeArgs": [
        "--remote-debugging-port=9222" 
    ],
    "diagnosticLogging": true
},
```

Relevant tsconfig.json
```
"compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "outDir": "dist",
    "sourceRoot": "/",
    "sourceMap": true
},
"exclude": [...]
```

Side question regarding documentation: "_Check the sourceRoot and sources properties in your sourcemap and make sure that they can be combined with the webRoot property in your launch config to build the correct path to the original source files._" - how should sourceRoot/sources and webRoot combine? I feel the issue is here but I can't make the connection.

**Comment by roblourens** [comment]
Two questions - is the webRoot correct? Since `http://localhost:9500/dist/js/editor.min.js` is actually at `${workspaceRoot}/dist/js/editor.min.js`, maybe it should be `${workspaceRoot}`.

And when editor.min.js loads, it has a sourcemap that maps to editor.js, but it doesn't mention the .ts files, so it looks like you don' thave a sourcemap from editor.js to the ts files? Can you debug them in chrome devtools?

And basically in the sourcemap it combines `sourceRoot` + `sources` entries, then if that resolves to `/something`, it would use a webRoot of `C:/project' to resolve that to `C:/project/something`.

**Comment by montrealist** [comment]
Thank you for taking a look!

> is the webRoot correct?

I assume the `webRoot` setting is where the index.html is served from. If this is the case then yes, it's correct. Thought I don't get your reasoning of why it wouldn't be (perhaps I'm too stuck to get a different perspective).

> but it doesn't mention the .ts files, so it looks like you don' thave a sourcemap from editor.js to the ts files? Can you debug them in chrome devtools?

Nope, can't get to any `.ts` files from inside Chrome, only `.js` files. That's my problem - I can't seem to make this connection between TS and JS and I don't know how. Grunt takes care of generating one big `.js` from all the `.ts` files, so that's where this connection is being lost. How do the sourcemaps usually get generated?

By the way my `/src` directory now looks like this:
```
|-- src
    |----- App.js
    |----- App.ts
    |----- App.js.map
    |----- Controller.js
    |----- Controller.ts
    |----- Controller.ts.map
```

And here's the inside of one of those `.map` files:
```
{"version":3,"file":"App.js","sourceRoot":"../src/","sources":["App.ts"],"names":[],"mappings":"..."}
```

Does it mean the mapping between the JS and TS does exist, and it's being lost when concatenation into a larger JS file happens?

**Comment by roblourens** [comment]
webRoot is where your webserver is serving files from, in your case, might be the same as where index.html is.

If you can't do this scenario in Chrome DevTools, you won't be able to do it here, the extension doesn't have any extra information. I think you're right, that you have two sets of sourcemaps covering two steps, but you need to change your build config to generate one sourcemap covering everything from TS to the end product. I can't really help you with Grunt though, sorry :/
