### ISSUE TITLE
Cannot debug dynamically loaded JavaScript

### ISSUE THREAD

**Issue by grantcv1** [Microsoft/vscode-chrome-debug#232]
I believe this issue is related to #205 

In my app, the modules are loaded dynamically using script elements and setting .src property. This is essentially the same approach as requirejs.

In CDT, the debugger works fine and the files are shown in my domain's folder in the Chrome Dev Tools sources tab. (This is different from #205 where they are shown in (no domain))

In VSCode, I've enabled diagnostic logging and see messages:
> Paths.scriptParsed: resolved http://dev.xxxxx.com/edit/scripts/MenuComponent.js to    
> c:\Users\xxxxx\Documents\Projects\xxxxx\edit\scripts\MenuComponent.js. 
> webRoot: C:\Users\xxxxx\Documents\Projects\xxxxx

However, when I try to set a breakpoint, I get the "Unverified Breakpoint" flyover and a message in the console that reads:

> Paths.setBP: No target url cached for client path: 
> c:\Users\grantcv1\Documents\Projects\LegisPro3\XmlEditor\scripts\String.js, 
> waiting for target script to be loaded.

I have tried using the //# sourceURL= directive and all I've been able to achieve with the is to move the domain folder in the CDT sources tab from my domain to (no domain) and the file://.

I have tried to use the debugger statement and I can stop the debugger in my files loaded the normal way, but not in the files I load dynamically.

I am not using source maps at all.

**Comment by auchenberg** [comment]
Thanks for the report. Looking at the paths, then it seems you are trying to set a breakpoint in a file that isn't loaded on the page? Is that correct?

Loaded script path:```c:\Users\grantcv1\Documents\Projects\LegisPro3\edit\scripts\MenuComponent.js```

Target file ```c:\Users\grantcv1\Documents\Projects\LegisPro3\XmlEditor\scripts\String.js, 
waiting for target script to be loaded.```

The difference in those paths seems to be **`edit`** and **`XmlEditor`**. Are both paths being served to the browser?

Do you see a `Paths.scriptParsed` event in the logs for the file you are trying to set a breakpoint in?

**Comment by grantcv1** [comment]
Yes, sorry I was a bit sloppy. Here is the corresponding list for String.js:

> Paths.scriptParsed: resolved http://dev.xxxxx.com/xmlEditor/scripts/String.js to
> c:\Users\grantcv1\Documents\Projects\LegisPro3\xmlEditor\scripts\String.js. 
> webRoot: c:\Users\grantcv1\Documents\Projects\LegisPro3

**Comment by roblourens** [comment]
It looks like `XmlEditor` is cased differently, it has a lowercase x on the filesystem. Matching paths/urls is case-sensitive right now, but it really shouldn't be, see https://github.com/Microsoft/vscode-chrome-debug-core/issues/27. Can you try changing it to load with the same case?
