### ISSUE TITLE
Sourcemap not fetched when served over http 

### ISSUE THREAD

**Issue by thorseye** [Microsoft/vscode-chrome-debug#233]
I'm serving my sourcemaps over http when developing a quite big application with a lot of different modules. In my js files, I've got a reference to a sourcemap like so: 

``` js
//# sourceMappingURL=http://localhost:9000/src/path/to/file/filename.js.map
```

When launching a chrome debugger, I see the following in the console log:

```
›HTTP GET failed with: 404 Not Found
  ›SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:9000/path/to/file/http:/localhost:9000/src/path/to/file/filename.js.map
```

It seems that the debugger plugin tries to normalze the path to the sourcemap, but since it's served over http it should really be looking for the url on `http://localhost:9000/src/path/to/file/filename.js.map` instead of `http://localhost:9000/path/to/file/http:/localhost:9000/src/path/to/file/filename.js.map`

The js file is served and accessible on `http://localhost:9000/path/to/file/filename.js`.

This setup works for debugging in Chrome directly, but not when trying to use VS Code to set breakpoints. 

My `launch.json`:

``` json
        {
            "name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:9000",
            "webRoot": "${workspaceRoot}/src",
            "sourceMaps": true
        }
```

Maybe this is not something that could be achieved with VS Code? Is there some other way to solve this if this is not considered a bug?

**Comment by colonelchlorine** [comment]
I had this problem as well and it turned out I didn't have a MIME type returning for .map files on my web server. Set up "application/json" for .map files and then it picked up the map files.

**Comment by roblourens** [comment]
This was addressed in https://github.com/Microsoft/vscode-chrome-debug-core/issues/65 (although the extension isn't updated with that fix yet, coming soon)

**Comment by jhicken** [comment]
@roblourens So not to be a pain in the butt.... Whats the time frame on this being released. 

![Alt Text](http://big.assets.huffingtonpost.com/Smiling.gif)

I'm really excited about it.
