### ISSUE TITLE
Cross-tier debugging of Chrome and Node

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#236]
Prototype of Cross-tier debugging of Chrome and Node, that allows a developer to debug code from Node and Chrome within the same debugging session

**Suggested architecture**

```
Node v8 inspector   +----->   VS Code Chrome Core   +
                                                    |
                                                    <-->     New "magic" cross-tier VS Code bugger
                                                    |
           Chrome   +----->   VS Code Chrome Core   v
```

**Comment by roblourens** [comment]
I implemented this last year, it was pretty ugly. Doing this right needs first-class support for debugging multiple things simultaneously, one way or another, from vscode.

**Comment by auchenberg** [comment]
We still need this feature, so let's keep it around in the back log. I'd like to understand what' specifically need from VS Code to enable scenarios like this, and why the above approach didn't work.

**Comment by faceyspacey** [comment]
isn't this the same as opening a 2 VSCode windows, and using one to debug chrome and the other to debug Node? Are there any additional capability you get from having them both run in the same window? I guess, for javascript used on both the client and the server, you only need one of them open.

**Comment by roblourens** [comment]
The only thing blocking that right now is that you can't open two vscode windows on the same folder. That could change in the future too, I think it's an open question.

**Comment by faceyspacey** [comment]
you could have, say, your client code in a subfolder and then open that and adjust the `webRoot` config option

**Comment by auchenberg** [comment]
Landed (for now) via [multi target debugging =in VS Code 1.7](http://code.visualstudio.com/updates#_node-debugging)
