### ISSUE TITLE
v1.0.0: Cannot connect to runtime process

### ISSUE THREAD

**Issue by desturm** [Microsoft/vscode-chrome-debug#237]
After installing v1.0.0, the following error message appears after 10 seconds when running the debugger:
**Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: 504 - HTTP status code 504).**
Chrome is then closed automatically.
The previous version had no problems. There were no changes in the launch.json file.

**Comment by roblourens** [comment]
During that 10 seconds, can you try opening `http://localhost:9222/json` (maybe a different port, it should get printed to the console) in a browser? And is another instance of Chrome open, or something else on that port?

Also could you please set `"verboseDiagnosticLogging": true` in your launch config, and share the logs? You can drag this file into the github comment box: `/Users/roblou/.vscode/extensions/msjsdiag.debugger-for-chrome-1.0.0/vscode-chrome-debug.txt`.

**Comment by gdlm91** [comment]
I'm also having a similar issue after installing 1.0.0 when trying to "Attach to Chrome":

**Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: 401 - Unauthorized. The server is refusing to respond.).**

No changes to the launch.json since yesterday, and it was working fine until the Update.

Opening http://localhost:9222 works fine too.

**Comment by roblourens** [comment]
And you get this error every time, and always the same error? Could you post your logs too?

I'm using `request-light` to make the request instead of the http module, and I could try reverting that, but this is a strange issue.

**Comment by gdlm91** [comment]
Sure, here are my logs.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/511529/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
So this is for an 'attach' config? Do you see this for 'launch' as well?

**Comment by gdlm91** [comment]
Yes, I see the same error for "launch" too.

**Comment by gdlm91** [comment]
**BTW**
I switched back to _0.5.2_ just to be sure is not a local issue, and it's working again. 

So it is definitely an issue with the new version.

**Comment by roblourens** [comment]
Thanks for trying that. That is really strange... There are a couple things I can experiment with. I'm also curious whether it would make a difference to use vscode insiders, or the new release that will be out tomorrow/Friday. Probably not, but it will be running in a newer version of Node, and that's where I did most of the testing.

**Comment by bijeebuss** [comment]
Im hitting this issue too.

**Comment by roblourens** [comment]
Can someone try opening `http://127.0.0.1:9222/json` while Chrome is open and post the response? I should have asked for that instead of localhost.

Also, could you try setting 'port' to some other random number?

**Comment by roblourens** [comment]
And anyone else who runs into this, would appreciate you chiming in. And if it randomly starts working for any of you above, would appreciate to know that too :)

**Comment by desturm** [comment]
Hi Gerardo, how to switch to the older version 0.5.2?

2016-10-05 20:22 GMT+02:00 Gerardo Leal <notifications@github.com>:

**Comment by desturm** [comment]
Hi Rob, here is the response from http://127.0.0.1:9222/json :


2016-10-06 0:42 GMT+02:00 Rob Lourens <notifications@github.com>:

**Comment by wkamir** [comment]
Unfortunately I have a very similar issue ... 

Visual Studio Code DEBUG CONSOLE:
```
Discovering targets via http://127.0.0.1:9222/json
HTTP - GET failed with: 403 - Forbidden. The server is refusing to respond.
```

When I request the json myself using another browser window I seem to get a valid response though:

```
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/1fd1a1ee-83a9-4e9b-927d-5757aeb9b0c1",
   "id": "1fd1a1ee-83a9-4e9b-927d-5757aeb9b0c1",
   "thumbnailUrl": "/thumb/1fd1a1ee-83a9-4e9b-927d-5757aeb9b0c1",
   "title": "Angular QuickStart",
   "type": "page",
   "url": "http://localhost:3000/",
   "webSocketDebuggerUrl": "ws://127.0.0.1:9222/devtools/page/1fd1a1ee-83a9-4e9b-927d-5757aeb9b0c1"
}, ... ]
```

Hope this helps

**Comment by gdlm91** [comment]
@desturm In my PC, I went to 'C:\Users\lealg\.vscode\extensions' and had 2 debugger-for-chrome folders: the 1.0.0 and 0.5.2. I deleted 1.0.0 and VSCode loads the 0.5.2. 

The other option I think is to clone and build the plugin, and copy the result in a folder like 'msjsdiag.debugger-for-chrome-0.5.2'.

**Comment by gdlm91** [comment]
@roblourens I tested 1.0.0 with VSCode Insider and it fails too.

Also tested changing the port to 9223 and retry with VSCode and VSCode Insider, and still get connection Unauthorized.

Here is my localhost;9223/json file
[localhost_9223.txt](https://github.com/Microsoft/vscode-chrome-debug/files/513733/localhost_9223.txt)

**Comment by roblourens** [comment]
It looks like everyone is on windows? Does using the userDataDir option make a difference? Set it to some folder where Chrome can store its profile data.

**Comment by roblourens** [comment]
I just released 1.1.0 which reverts the code that makes the http request for Chrome to exactly the same as it was before. Hope that helps... If that doesn't fix it, I just uploaded a vsix package for 0.5.2 here - https://github.com/Microsoft/vscode-chrome-debug/releases/tag/v0.5.2 which you can install by dragging it on to the vscode window.

**Comment by desturm** [comment]
The error no longer occurs with 1.1.0, but the debugger does not seem to work, because breakpoints are no longer served. After switching to 0.5.2 everything works again correctly. I work under Windows.

**Comment by roblourens** [comment]
Great, so it seems like that fixed this problem. I'll close unless anyone is still seeing it.

If breakpoints are not working, it is probably a separate issue. I would really appreciate you uploading the log file from a debug session with 1.1.0 so I can take a look.

**Comment by gdlm91** [comment]
**1.1.0 is working!** And also my breakpoints are working fine too, so @desturm issue must be other thing.

Thanks for the quick support! @roblourens

**Comment by roblourens** [comment]
Great, and thanks everyone for the reports and debugging help.
