### ISSUE TITLE
Add setting to allow other compile-to-JS languages to be debugged

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-chrome-debug#240]
@aolney is using [fable](http://fable.io/) to compile F# code to JS (with sourcemap) and wants to use Chrome Debugger to debug it.

Now breakpoints can't be set against F# `fsx` file, so I edited `~/.vscode-insiders/extensions/msjsdiag.debugger-for-chrome-1.0.0/package.json`:

![image](https://cloud.githubusercontent.com/assets/4033249/19131550/b722a57c-8b04-11e6-8f9b-370fab0dc52f.png)

And it works:

![image](https://cloud.githubusercontent.com/assets/4033249/19131753/87fc3fe6-8b05-11e6-8553-5ac4add42e32.png)

Is it possible to add a config for Chrome Debugger, so users can provide a list of languages that they can debug?

**Comment by octref** [comment]
Original issue at: https://github.com/octref/vscode-electron-debug/issues/2

**Comment by roblourens** [comment]
I'll add fsharp to the package.json to unblock Fable, but you can open an issue on vscode if you want to start the discussion about this again. It seems doesn't make sense to list every language in the world in this extension, but this is the one place where you could actually be debugging anything compiled to JS. Also doesn't make sense to allow breakpoints in every file type out of the box, or to whitelist a bunch out of the box.

**Comment by octref** [comment]
I agree. Think we need a user config for enabling debugger file types, which is loosely coupled with debuggers in the context of transpilation.

**Comment by octref** [comment]
@roblourens Seems already discussed: https://github.com/Microsoft/vscode/issues/9037

Though user still needs an extension to enable debugging for a specific language...
