### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by faceyspacey** [Microsoft/vscode-chrome-debug#242]
I'm wondering what the path to achieving React Native support might be. I've found VSCode's debugger to be the best debugger in an IDE I've ever experienced for browser applications. For me, I've been debugging in Chrome, and bouncing back to my editor for years. You can do stuff to match your files and make Chrome your default editor, but the editor in Chrome isn't good enough. There's WebStorm, but the experience was always shoddy compared to this. So Kudos to you guys for building this.

That all said, React Native is also debuggable in Chrome as standard fare. So it's only a natural progression that *vscode-chrome-debug* works for React Native as well. It would be big for the React Native world and big for making VSCode the #1 choice for React Native developers. My hunch is this particular feature is a very natural evolution to implement. Perhaps I already can do it by attaching to the chrome window React Native pops up. Here are some things to consider:

1) The first thing to note is that React Native code executes in a different frame than the main one. So VSCode would have to allow you to choose a frame to attach to, but perhaps that doesn't matter. 

2) The next thing--and this is basically a minor general issue--I can't get the debugger to attach to an already running chrome window/tab. It always launches a new one. That is somewhat annoying. It feels like it should since there is a dropdown to choose what to attach to, but there are never any other options other than launching a new window. *And, on a side note, if Redux devtools wasn't able to automatically attach to any new window running your app, that would be a problem since you would then have to open up chrome devtools to launch redux devtools, which obviously kills your current VSCode debug session.* So as for React Native, the idea is that the application on your phone launches a chrome window. So I'm assuming the best path forward for the VSCode debugger would be to be able to attach to already running browser tabs--that way we don't have to  worry about making the window VSCode launches attach to the application on your phone or in the simulator. And being able to attach to already running windows would obviously be a nice general enhancement.

**Comment by roblourens** [comment]
Thanks for the thoughts, @faceyspacey - Have you seen the React Native extension with debugging support? :) https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native

From what I understand, React Native runs the code in a Node process on the host machine when in debug mode, and that extension wraps the existing Node debug adapter in vscode.

**Comment by faceyspacey** [comment]
wow! I don't know how I missed that. I'm still pretty new to VSCode (atom refugee). I'll check it out.

Ima close this, but any thoughts on attaching to an already running browser window? Sometimes you need Chrome devtools for things like the Elements tab, and then boom, your debugging session is over and next time you want to debug it opens a new window.

**Comment by roblourens** [comment]
Yes, you can actually start Chrome in debug mode, then in your launch config you can have `"request": "attach"` instead of launch, and attach to the open tab. There are a couple notes in the readme about that.

**Comment by faceyspacey** [comment]
yea, i saw that in the video, but couldn't find it when skimming the text readme. gracias
