### ISSUE TITLE
Canary - truncated console logs

### ISSUE THREAD

**Issue by bitbay** [Microsoft/vscode-chrome-debug#245]
Debugger for Chrome 1.0.0
VSCode 1.5.3
Chrome 55.0.2882.1 canary SyzyASan

Once the debug session starts i see truncated output in the debug console.
For example, code
```
var num = 123;
console.log("[ debug ] num:", num);
```
outputs in chrome console `[ debug ] num 123`, while in VSCode debug console it only reads `[ debug ] num`.

Logging whole objects is possible in chrome dev-tools.
Is this a feasible feature for a future release?
I think even a ".toString()" of the not-fully-supported output would be better than leaving off data.

Thanks for reading.

**Comment by roblourens** [comment]
Yes there are two problems here - one is that the console message API used here was deprecated, but that should be fixed in the next non-bugfix update.

Second is that we can't log objects, which is a vscode limitation. https://github.com/microsoft/vscode-node-debug/issues/4

**Comment by roblourens** [comment]
Fixed in 2.0.0
