### ISSUE TITLE
VS Code jumps into wrong file

### ISSUE THREAD

**Issue by TimBo93** [Microsoft/vscode-chrome-debug#247]
Hey Hackers,

i love your tool. It worked already correctly but now Visual Code jumps in the wrong file when hitting a breakpoint.

Chrome (Version 53.0.2785.143 m) handles the breakpoints correctly.

![debugger](https://cloud.githubusercontent.com/assets/8701341/19185862/cd9337d8-8c83-11e6-975d-3ec9ac7fe9d4.PNG)

So i think webpack is not the issue. 

Instead of jumping into file
\app\ViewModels\AxisViewModel.ts
Line 46

Visual Studio Code jumps into 
\app\Views\views\directives\Common\ErrorImage.ts
Line 1

Debugger for Chrome has the version 1.1.0
And Visual Studio Code the version 1.5.3

My launch.json looks like this:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch index.html with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:12345/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

with kind regards,
Tim

**Comment by roblourens** [comment]
If you step a couple times, does it go from ErrorImage line 1 to somewhere in AxisViewModel? Is this a project you can share with me?

**Comment by TimBo93** [comment]
Dear @roblourens 
i asked my superiors to publish the project on GitHub or Visual Studio Team Projekt but they are undecided. So i think it could be take a while till they make a decision.

The stack view and the code view displays the same line and file. One more problem is that when i make a breakpoint then it is placed in some underlying lines in vs code with the hint that there could be a problem with the source files.
![movingbp](https://cloud.githubusercontent.com/assets/8701341/19268865/4a3d32c6-8fb7-11e6-91f5-919e396a00ce.PNG)

 In chrome the breakpoints in the corresponding typescript file work accurately.
![chrome](https://cloud.githubusercontent.com/assets/8701341/19268866/4a463f10-8fb7-11e6-940b-03ca86382ea1.PNG)

if you need any informations feel free to ask.

**Comment by roblourens** [comment]
One thing to try is removing files or code from this file to see if you can create a simpler repro. Which webpack setting are you using for sourcemaps? Some of them will be less reliable.

**Comment by TimBo93** [comment]
Packages.json

```
{
  "version": "1.0.0",
  "name": "projekt----",
  "private": true,
  "author": {
    "name": "",
    "email": "",
    "url": ""
  },
  "readme": "Dependencies for developing and building Projekt ---. One should not check nor ship node_modules folder.",
  "devDependencies": {
    "awesome-typescript-loader": "^1.1.1",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-angular-templatecache": "^2.0.0",
    "gulp-bower": "0.0.13",
    "gulp-inject": "^4.1.0",
    "gulp-sass": "^2.3.2",
    "gulp-task-loader": "^1.4.4",
    "gulp-tslint": "^6.1.2",
    "gulp-typings": "^2.0.4",
    "gulp-util": "^3.0.7",
    "main-bower-files": "^2.13.1",
    "run-sequence": "^1.2.2",
    "tslint": "^3.15.1",
    "typescript": "^2.0.3",
    "typings": "^1.4.0",
    "vinyl-paths": "^2.1.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.2",
    "webpack-stream": "^3.2.0"
  }
}

```


webpack.config.js
```
module.exports = {
    entry: 'app/Applications/App',
    output: {
        path: './wwwroot/build',
        filename: 'bundle.js',
    },

    // Currently we need to add '.ts' to the resolve.extensions array.
    resolve: {
        root: __dirname,
        extensions: ['.ts']
    },

      // Source maps support ('inline-source-map' also works)
    devtool: 'source-map',
    devServer: {
        contentBase: "wwwroot/build/"
    },

    // Add the loader for .ts files.
    module: {
        loaders: [
        {
            test: /\.ts$/,
            loader: 'awesome-typescript-loader'
        }]
    }
};
```

i think it is actually a chrome debugger protocol problem. Currently i'm working on a lightweight repo to understand the cause of the bug.

**Comment by TimBo93** [comment]
Hopefully it can help you to reproduce the bug.
https://github.com/TimBo93/MinimalTsAngularSPA

**Comment by TimBo93** [comment]
After changing the devtool property in _webpack.config.js_ the visual studio debugger works like charme
`devtool: 'inline-source-map'`.

But
`devtool: 'source-map',`
jumps wildly through the code lines.

The Chrome-Debugger (F12 and localhost:9222) instead works with both configurations perfectly. In my configuration webpack packs all transcompiled TS-Files into one bundled JS-file which contains approximately 4.000 lines of code (without sourcemaps). 

After switching the configuration of devtool from source-map to inline-source-map several times, i am pretty sure, that this is the cause. I guess there is caching issue somewhere.

**Comment by roblourens** [comment]
This was maybe related to #250 - try out 1.2.0 and let me know

**Comment by TimBo93** [comment]
i tried version 1.2.0 but it is the same behaviour as before  :confused: Inline-source-map is working brilliantly but source-map is as buggy as before.

**Comment by roblourens** [comment]
Ok, can you tell me exactly what you're trying in the repro project? It worked alright for me.

**Comment by TimBo93** [comment]
The repository has basically the same structure as my business application. 

I added a branch [WithModel](https://github.com/TimBo93/MinimalTsAngularSPA/tree/WithModel). The impact to the breakpoints is greater here. The app doesn't calculate anything magic, its just to understand the debugger behaviour.

**Setting a breakpoint with "source-map"**
![jumping breakpoints](https://cloud.githubusercontent.com/assets/8701341/19410392/ab137664-92eb-11e6-90c7-ca4f0d63863a.gif)
as you can see the breakpoints are jumping around.

**Setting a breakpoint with "inline-source-map"**
![inline sourcemap](https://cloud.githubusercontent.com/assets/8701341/19410421/640c7c24-92ec-11e6-8419-aa043f07d850.gif)
Everything is working nice.

**Comment by roblourens** [comment]
Ok I can finally repro this! Going into it I thought that this only made sense if it was just using the wrong sourcemap file. And, that's exactly what it's doing. I added some code to cache downloaded sourcemaps by URL, but I never clear out the cache. So let me push out a change that just disables the cache...

**Comment by roblourens** [comment]
Ok, pretty sure I got this in 1.2.1. Try it out and let me know

**Comment by TimBo93** [comment]
the first run works.  
But when I 
1) add some lines 
2) let webpack rebuild everything 
3) restarting the debugging session
the breakpoints and debugger-statements are as wrong as before. 

Can you see this too?

**Comment by roblourens** [comment]
I'm not seeing this, except once, when webpack stopped actually rebuilding. I don't know why that happened, but I killed and restarted it, and it all worked again as expected.

**Comment by roblourens** [comment]
When you say the first run, like the first run after starting webpack, or the first run after installing the update, or something else?

When it's wrong, can you check that the correct sources show up in Chrome? Maybe it's either the issue I saw (webpack not actually rebuilding) or Chrome caching scripts?

**Comment by TimBo93** [comment]
you are absolutely right. I can reproduce it and its actually exactly what you are saying. Webpack is doing some strange things, if edit your code which doesn't change the compilation result, i.e. adding some empty lines or spaces.

Thank you for your fix!
