### ISSUE TITLE
Just Debug this js files. How should i config?

### ISSUE THREAD

**Issue by Midqiu** [Microsoft/vscode-chrome-debug#248]
![image](https://cloud.githubusercontent.com/assets/5728399/19258306/5dd838fc-8fa9-11e6-972e-2b1ed3bafb85.png)

**Comment by roblourens** [comment]
Do you have a webserver? webRoot is the directory where the server is serving files from.

**Comment by Midqiu** [comment]
It's OK when I use the absolute path for the webRoot.

**Comment by roblourens** [comment]
Ok, I don't quite understand what you're asking

**Comment by TimBo93** [comment]
@Midqiu "webRoot": "C:\\Users\\name\\Source\\Repos\\WebFrontEnd\\FrontEnd" works for me...
