### ISSUE TITLE
Can't set breakpoint in typescript in angular-cli generated bundle

### ISSUE THREAD

**Issue by Tmr** [Microsoft/vscode-chrome-debug#251]
OS: Windows 7.
Debugger for Chrome 1.1.0 installed. 
VS Code 1.6.0
Node 6.5.0

Steps to reproduce:
```
npm -g angular-cli
ng new exampe-proj
cd example-proj
ng serve
```
Run Chrome:
`chrome.exe --remote-debugging-port=9222 --user-data-dir=remote-profile`
Open example-proj directory in VS Code.
Run debugger with "Attach to Chrome, with sourcemaps". 
Relevant launch.json section:
```
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                 "webpack:///C:/*":"C:/*"
            },
            "diagnosticLogging": true
        }
```
Open "app.component.ts" and set breakpoint on "title = 'app works!!!';" string.
Gray breakpoint appers with a message:
> Breakpoint ignored because generated code not found (source map problem?).

**Comment by ujibang** [comment]
I'm experiencing that same issue on OSX

**Comment by Tmr** [comment]
**vscode-chrome-debug.txt content:**

OS: win32 ia32
Node: v6.5.0
vscode-chrome-debug-core: 2.0.2
debugger-for-chrome: 1.1.0
From client: initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true}}
From client: attach({"name":"Attach to Chrome, with sourcemaps","type":"chrome","request":"attach","port":9222,"sourceMaps":true,"webRoot":"c:\\dev\\angular\\project-ang-cli","sourceMapPathOverrides":{"webpack:///C:/*":"C:/*"},"diagnosticLogging":true})
Discovering targets via http://127.0.0.1:9222/json
Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/c2f963bb-f88b-4b46-819c-63c5536f470b","faviconUrl":"http://localhost:4200/favicon.ico","id":"c2f963bb-f88b-4b46-819c-63c5536f470b","thumbnailUrl":"/thumb/c2f963bb-f88b-4b46-819c-63c5536f470b","title":"ProjectAngCli","type":"page","url":"http://localhost:4200/","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/c2f963bb-f88b-4b46-819c-63c5536f470b"}
WebSocket Url: ws://127.0.0.1:9222/devtools/page/c2f963bb-f88b-4b46-819c-63c5536f470b
To target: {"id":1,"method":"Runtime.enable"}
To target: {"id":2,"method":"Debugger.enable"}
To target: {"id":3,"method":"Console.enable"}
To target: {"id":4,"method":"Runtime.runIfWaitingForDebugger"}
To target: {"id":5,"method":"Runtime.run"}
From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"isDefault":true,"origin":"http://localhost:4200","name":"","frameId":"7004.1"}}}
From target: {"id":1,"result":{}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"32","url":"http://localhost:4200/inline.js","startLine":0,"startColumn":0,"endLine":138,"endColumn":31,"executionContextId":2,"hash":"8E5CA56065F232C10EC5BBC2C5717153EA1D7067","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"inline.map","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve http://localhost:4200/inline.js to a file under webRoot: c:\dev\angular\project-ang-cli. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/inline.js by URI: inline.map and webRoot: c:\dev\angular\project-ang-cli
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/inline.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"33","url":"http://localhost:4200/styles.bundle.js","startLine":0,"startColumn":0,"endLine":363,"endColumn":31,"executionContextId":2,"hash":"C2D0CAC0B4E735E822C14BC29C598BBC054482C7","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"styles.map","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve http://localhost:4200/styles.bundle.js to a file under webRoot: c:\dev\angular\project-ang-cli. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/styles.bundle.js by URI: styles.map and webRoot: c:\dev\angular\project-ang-cli
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/styles.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"34","url":"http://localhost:4200/main.bundle.js","startLine":0,"startColumn":0,"endLine":65956,"endColumn":29,"executionContextId":1,"hash":"0A726D63C2CF212028603575D690D8DA5FC054D1","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"main.map","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve http://localhost:4200/main.bundle.js to a file under webRoot: c:\dev\angular\project-ang-cli. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/main.bundle.js by URI: main.map and webRoot: c:\dev\angular\project-ang-cli
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/main.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"39","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"AB1DDDC0E5FB8300ECC80ED4F7FF84D50BB47543","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"40","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"52B6A052DE156707D2E00FF51017D482543400D6","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"41","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"FA2DA8027B99D731274F00318686F393CBE44264","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"42","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"646722F315EF70E4953AF603BDBF2D70221E2F90","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"43","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"3002EE91D344E7E9803CABE168F7AA4260FD6310","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"44","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"14DE9DE18080A46602E947332D1A7A214EE24815","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"45","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"FEF6B7F329BC00A2EA79B2E4A2C9ACCA3DC12262","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"519E36427F9D96F997685AB431C5BD0926CA3B54","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"C555EA63B900C078A4F08F62C3151EA0050E7973","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"A4CAEE539429A803D5C15DB4EF30D11AF37B9C96","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"6D2F76C0E70696D650DCA0D0083A5CB2B19488D5","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/inline.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/inline.js.map
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/styles.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/styles.bundle.js.map
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/main.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/main.bundle.js.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"10CACB814A4A9773F66ACF66192BA1E54C240642","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"51","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"1374B8700487D2064DC4DE058FF0E7D9E23DFA31","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"52","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"40C41AB17B027C9246EF5AE7821869881E6B45D4","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"40C41AB17B027C9246EF5AE7821869881E6B45D4","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"C555EA63B900C078A4F08F62C3151EA0050E7973","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"55","url":"AppModule.ngfactory.js","startLine":0,"startColumn":0,"endLine":211,"endColumn":2,"executionContextId":1,"hash":"837C2F7119523029D98DE433DFFDBFFBFE830D56","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":true,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve AppModule.ngfactory.js to a file under webRoot: c:\dev\angular\project-ang-cli. It may be external or served directly from the server's memory (and that's OK).
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/inline.js.map
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/styles.bundle.js.map
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/main.bundle.js.map
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"56","url":"AppComponent.ngfactory.js","startLine":0,"startColumn":0,"endLine":55,"endColumn":2,"executionContextId":1,"hash":"8596D18163E4966AA13D5A962738C023250B71D4","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":true,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve AppComponent.ngfactory.js to a file under webRoot: c:\dev\angular\project-ang-cli. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"AppComponent_Host.ngfactory.js","startLine":0,"startColumn":0,"endLine":32,"endColumn":2,"executionContextId":1,"hash":"CB83C6906416208A6B47CA06A17FEB5C3E5E12A7","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":true,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve AppComponent_Host.ngfactory.js to a file under webRoot: c:\dev\angular\project-ang-cli. It may be external or served directly from the server's memory (and that's OK).
From target: {"id":2,"result":{}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"67","url":"","startLine":0,"startColumn":0,"endLine":185,"endColumn":24,"executionContextId":1,"hash":"A0247552321E228369039AE6BD77DC177D990211","isContentScript":false,"isInternalScript":true,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.","type":"log","url":"http://localhost:4200/main.bundle.js","line":853,"column":13,"parameters":[{"type":"string","value":"Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode."}],"stack":{"callFrames":[{"functionName":"print","scriptId":"34","url":"http://localhost:4200/main.bundle.js","lineNumber":853,"columnNumber":13}]},"timestamp":1476355699.9075,"executionContextId":1}}}
From target: {"id":3,"result":{}}
From target: {"error":{"code":-32601,"message":"'Runtime.runIfWaitingForDebugger' wasn't found"},"id":4}
From target: {"id":5,"result":{}}
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":true}
From client: setBreakpoints({"source":{"path":"c:\\dev\\angular\\project-ang-cli\\src\\app\\app.component.ts","name":"app.component.ts"},"lines":[11],"breakpoints":[{"line":11}],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":11,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000}]}}
From client: setExceptionBreakpoints({"filters":["uncaught"]})
To target: {"id":6,"method":"Debugger.setPauseOnExceptions","params":{"state":"uncaught"}}
From target: {"id":6,"result":{}}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
From client: setBreakpoints({"source":{"path":"c:\\dev\\angular\\project-ang-cli\\src\\app\\app.component.ts","name":"app.component.ts"},"lines":[],"breakpoints":[],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":6,"command":"setBreakpoints","success":true,"body":{"breakpoints":[]}}

**Comment by roblourens** [comment]
```SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/main.map
...
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
[Error] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:4200/main.map```

This works for me. When the app is being served, can you download the map at this URL?

**Comment by Tmr** [comment]
Yes, http://localhost:4200/main.map is downloadable in browser.

**Comment by roblourens** [comment]
Dang, I wonder if this is the same as #237? I will try the same fix as I did there.

**Comment by roblourens** [comment]
Try it out in 1.2.0 and please let me know

**Comment by ujibang** [comment]
updated to 1.2.0, it still does not work.

chrome actually loads the maps; also setting breakpoints from the chrome dev console is possible.

however when trying to set a brekpoint from vscode, it still complains with **Breakpoint ignored because generated code not found (source map problem?)**

**Comment by Tmr** [comment]
Breakpoints work as expected in 1.2.0! Thank you!!!

**Comment by roblourens** [comment]
@ujibang Yours is probably some issue with your setup. Did you go through the README, set the webroot, look at diagnosticLogging, etc? I can't help without knowing more about your config, so open a new issue if needed.

**Comment by ujibang** [comment]
I found the solution here https://github.com/angular/angular-cli/issues/2453:

using angular-cli we need to remap `webpack:///* in launch.json.`

**Comment by roblourens** [comment]
Glad it works, but the extension includes this by default - `'webpack:///*': '*'`. That didn't do it?

**Comment by ujibang** [comment]
Hi @roblourens 

In my case, the extension hasn't included `webpack:///*` by default. I had to add it manually.

**Comment by roblourens** [comment]
Ok, if you update the extension, then you should have it.
