### ISSUE TITLE
Only one TS file is not showing in Chrome debugging

### ISSUE THREAD

**Issue by ssashok10** [Microsoft/vscode-chrome-debug#252]
Hello,
   I am using Angular 2 with Type Script and I am using Visual studio 2015 for my project.  I have added the below configuration entries on the web.config to make TS files on Chrome debugging. I have many TS  files on the project and all are showing properly on Chrome debugging except one TS file which shows blank data. What might be the reason that Chrome is showing blank for only one TS file? I even cleaned up the ASP .NET temporary folder. 

```
  <system.webServer>
    <staticContent>
            <remove fileExtension=".ts" />
            <mimeMap fileExtension=".ts" mimeType="application/x-typescript" />
     </staticContent>
  </system.webServer>
```

**Comment by roblourens** [comment]
It sounds like you're using Visual Studio. This is an extension for [Visual Studio Code](code.visualstudio.com) which is a different product. You might want to look around here - https://www.visualstudio.com/vs/support/
