### ISSUE TITLE
chrome crashes when opening dev tools and vscode-chrome-debug is attached

### ISSUE THREAD

**Issue by ujibang** [Microsoft/vscode-chrome-debug#253]
on OSX 10.12, vscode 1.6.0, chrome 53.0.2785.143 (64-bit) (currently all are updated to latest version)

1. I have an angularjs app running with angular-cli on `localhost:4200`
1. lauch chrome with `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`
1. attach vscode, working I see the debug console showing logs from my app
1. open the dev tools window

just right after last step, chrome crashes. 

as a side note, vscode is not able to submit breakpoints as reported on https://github.com/Microsoft/vscode-chrome-debug/issues/251

**Comment by roblourens** [comment]
So you're starting Chrome yourself and using an 'attach' config in vscode? It's expected that you would see this if you were using a 'launch', because when the debug adapter process shuts down, it kills Chrome too. But if you're using 'attach', that shouldn't happen. It would be a Chrome issue.
