### ISSUE TITLE
cannot debug  angular2 hello world in vscode

### ISSUE THREAD

**Issue by turkalpjr** [Microsoft/vscode-chrome-debug#254]
## cannot debug  angular2 hello world in vscode

Hello 
My application is under /dev app.component.ts , a simple hello world app.
I have put breakpoints in 

addAlert() {
    window.alert('bastınız');
in  component1.component.ts. 
When I try to debug application I get the following errors and chrome is not attached.

`SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:3000/browser-sync/socket.io.min.1.5.0.js.map
SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: SyntaxError: Unexpected token w in JSON at position 0
at Object.parse (native)
at new SourceMap (C:\Users\VALLEYKING\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
at sourceMapContentsP.then.e (C:\Users\VALLEYKING\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:39:24)
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Failed to load resource: the server responded with a status of 404 (Not Found) (http://localhost:3000/favicon.ico)`
 

 

I need help, I want a debuggable angular2  vscode project to go on, I am stuck. Any help will be appreciated, thanks.

Note: my angular2 hello world program can be downloaded from :http://www.hiztrans.com/couldnotdebugangular2vscodehelloworld.rar

**Comment by roblourens** [comment]
None of those errors should cause a real problem. It seems like your problem is just with your sourcemap config. If you set the `diagnosticLogging` option, you can see this log

```

Paths.scriptParsed: resolved http://localhost:3002/app/app.component.js to /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app/app.component.js. webRoot: /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld
SourceMaps.getMapForGeneratedPath: Finding SourceMap for /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app/app.component.js by URI: data:application/json;charset=utf8;base64,[...] and webRoot: /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app/app.component.js
SourceMap: creating for /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app/app.component.js
SourceMap: sourceRoot: undefined
SourceMap: sources: ["app.component.ts"]
SourceMap: webRoot: /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld
SourceMap: no sourceRoot specified, using script dirname: /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app
SourceMaps.scriptParsed: /Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app/app.component.js was just loaded and has mapped sources: ["/Users/roblou/Downloads/couldnotdebugangular2vscodehelloworld/app/app.component.ts"]
```

notice that it's resolved to `.../app/app.component.ts` because your sourcemap doesn't have a sourceroot. If you change your gulpfile to produce one, you should be able to resolve the ts file to the right place. Or the `sourceMapPathOverrides` option might be useful.

**Comment by turkalpjr** [comment]
Dear Rob
could you modify the code then show ? I tried ,googled but no luck!.. I could not be successful.

**Comment by turkalpjr** [comment]
Dear Rob,
now I get the following error


`SourceMaps.loadSourceMapContents: Could not download sourcemap from http://localhost:3000/browser-sync/socket.io.min.1.5.0.js.map
SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: SyntaxError: Unexpected token w in JSON at position 0
    at Object.parse (native)
    at new SourceMap (C:\Users\VALLEYKING\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
    at sourceMapContentsP.then.e (C:\Users\VALLEYKING\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:39:24)`
