### ISSUE TITLE
Cant debug on OSX 

### ISSUE THREAD

**Issue by levalencia** [Microsoft/vscode-chrome-debug#255]
I am trying to debug on chrome but I havent been able to:

I am using this task.json 
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/app.js",
      "stopOnEntry": false,
      "args": [],
      "cwd": "${workspaceRoot}",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "runtimeArgs": [
        "--nolazy"
      ],
      "env": {
        "NODE_ENV": "development"
      },
      "console": "internalConsole",
      "sourceMaps": false,
      "outFiles": []
    },
    {
      "name": "Attach",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "address": "localhost",
      "restart": false,
      "sourceMaps": false,
      "outFiles": [],
      "localRoot": "${workspaceRoot}",
      "remoteRoot": null
    },
    {
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "processId": "${command.PickProcess}",
      "port": 5858,
      "sourceMaps": false,
      "outFiles": []
    },
     {
        "name": "Launch localhost with sourcemaps",
        "type": "chrome",
        "runtimeExecutable" : "/Applications/Google Chrome 2.app/Contents/MacOS/Google Chrome",
        "request": "launch",
        "url": "http://localhost:4321/temp/workbench.html",
        "webRoot": "${workspaceRoot}/src",
        "sourceMaps": true
    }
  ]
}
```

I am using a Sharepoint Framework project

**Comment by roblourens** [comment]
Can you be more specific? Much, much, more specific? :)

**Comment by levalencia** [comment]
look at this please:
http://sharepoint.stackexchange.com/questions/196754/debugging-sharepoint-framework-webparts-with-vs-code-on-mac

**Comment by roblourens** [comment]
Most of those configs are for debugging Node, not Chrome, note "type": "node", so that won't work.

The one for Chrome, from the error, sounds like Chrome is not launching. I see you have a custom location for Chrome put in, which looks correct, assuming it actually exists. Does Chrome show up when you run that config?

**Comment by levalencia** [comment]
when I run that config I get this error: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).

**Comment by roblourens** [comment]
Right, because it can't connect to Chrome. Is Chrome actually open?

**Comment by levalencia** [comment]
Yes, when I type gulp serve chrome is opened.
If I execute this line: chrome is also opened
Softwares-MacBook-Pro:LibrarySample luis.valencia$ ./"Google Chrome" --remote-debugging-port=9222


if from Chrome I try I get this:


Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).

**Comment by roblourens** [comment]
No I mean that launch config for Chrome is supposed to launch Chrome. If it doesn't launch when you run that config, then something is wrong with it, like your runtime executable path is wrong.

If you want to launch Chrome manually, you can switch to an 'attach' config.

**Comment by pedrocatre** [comment]
I have the same problem. My config is:

`{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/demo/index.html",
            "webRoot": "${workspaceRoot}/app/files",
            "sourceMaps": true
        },
        {
            "name": "Launch index.html (without sourcemaps)",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/demo/index.html"
        },
    ]
}`

if I do attach instead of launch on port 9222 it also fails.

I get: Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1

The config does launch chrome.

**Comment by roblourens** [comment]
Also did you guys read the portion of the readme for troubleshooting this error?

**Comment by pedrocatre** [comment]
Hi, no I did not read that part. Probably it helps, thanks!

**Comment by levalencia** [comment]
It worked with an attach config.
