### ISSUE TITLE
Colors in Debug Console

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode-chrome-debug#259]
_First of all my compliments for this wonderful extension._

One question: is it possible to allow style-colored strings 
appear in VSC debug console just like they are shown in chrome console?

I.E.: This is Chrome:
![log_out_console](https://cloud.githubusercontent.com/assets/11835025/19438099/84b271c6-9478-11e6-82c5-7f4b0afe76c0.jpg)

This is VSC Debug Console:
![log_out_console1](https://cloud.githubusercontent.com/assets/11835025/19438106/8fa904e6-9478-11e6-8908-2b3aeb5dfd6b.jpg)

Is there any option that I'm missing to enable them?

--R

**Comment by roblourens** [comment]
Thanks :)

No, unfortunately the debug console doesn't support fancy colored output like Chrome devtools

**Comment by RobertoMalatesta** [comment]
OK. A Pity but the tool is so good that I can live without colors.
:beers: 
-R
