### ISSUE TITLE
No command autocompletion in VSC Debug Console

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode-chrome-debug#260]
VSC Debug Console shows no auto-completion hints.

See the "no suggestions" popup while typing "conso" and hitting ^SPC:
![log_out_console2](https://cloud.githubusercontent.com/assets/11835025/19438721/9d53a562-947b-11e6-8d62-de6b28aab1f3.jpg)

--R

**Comment by roblourens** [comment]
Soon! I don't have an issue tracking it here so I'll use this one. Thanks.

**Comment by roblourens** [comment]
Implemented some time ago.

**Comment by RobertoMalatesta** [comment]
@roblourens still not working
Linux Kubuntu 14.04
Chromium Version 55.0.2860.0 (64-bit)

--R
