### ISSUE TITLE
Unable to use Chrome debug to debug front-end JS on an express JS app

### ISSUE THREAD

**Issue by samunplugged** [Microsoft/vscode-chrome-debug#261]
I am getting this error:

Paths.scriptParsed: could not resolve http://localhost:3000/javascripts/test.js to a file under webRoot: /Users/sgu128/src/debug-test/. It may be external or served directly from the server's memory (and that's OK).

When I changed webRoot to _${workspaceRoot}/public/_ - it resolved the file, however, skipped the breakpoint.

Paths.scriptParsed: resolved http://localhost:3000/javascripts/test.js to /Users/sgu128/src/debug-test/public/javascripts/test.js. webRoot: /Users/sgu128/src/debug-test/public/

Breakpoint was skipped with following message: 

Breakpoint ignored because generated code not found (source map problem?).

This sure seems like a bug, since due to lack of documentation I am assuming developers intended to support front-end debugging when serving files using NodeJS.

Can you please confirm if chrome-debug tool can work with JavaScript? It seems to me like it works only with TypeScript. This is not clear from documentation. The documentation is also not clear on how to use it while serving files from a set-up like ExpressJS. Is there a working example

Thanks!

**Comment by roblourens** [comment]
It doesn't matter what your server is, or whether you're using TS. In the log, do you see a setBreakpoints request that matches that resolved local path exactly? There are some links to examples in the wiki but not for every particular setup.

**Comment by samunplugged** [comment]
Thanks for your response. I would appreciate if you take a look into my project set-up which is basically create by following steps available here: http://expressjs.com/en/starter/generator.html 

Its a very simple and basic project at this stage. I have uploaded my project here:

https://github.com/samunplugged/vs-code-express-debug-sample

I run by app by running:

`set DEBUG=debug-test:* && npm start`

The entire log I see in VS Code debug console is:

Verbose logs are written to /Users/sgu128/.vscode/extensions/msjsdiag.debugger-for-chrome-1.2.2/vscode-chrome-debug.txt
OS: darwin x64
Node: v6.5.0
vscode-chrome-debug-core: 2.0.6
debugger-for-chrome: 1.2.2
spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost:3000/"])
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
Warning: Found more than one valid target page. Attaching to the first one. Available pages: ["http://localhost:3000/","http://localhost:3000/"]
Paths.scriptParsed: resolved http://localhost:3000/javascripts/test.js to /Users/sgu128/src/debug-test/public/javascripts/test.js. webRoot: /Users/sgu128/src/debug-test/public/
testing...
1
2
3
Failed to load resource: the server responded with a status of 404 (Not Found) (http://localhost:3000/favicon.ico)

**Comment by roblourens** [comment]
I don't see anything in the log about setting a breakpoint. And the error message before implies that sourcemaps are enabled, but it looks like you shouldn't be using them. Can you check the verbose log for more clues? It's in the file written at the top of the log.

**Comment by sant123** [comment]
Hi @roblourens, following the structure of @samunplugged 's code, VS Code generates this launch.json

``` json
{
    "name": "Launch",
    "type": "node",
    "request": "launch",
    "program": "${workspaceRoot}\\bin\\www",
    "stopOnEntry": false,
    "args": [],
    "cwd": "${workspaceRoot}",
    "preLaunchTask": null,
    "runtimeExecutable": null,
    "runtimeArgs": [
        "--nolazy"
    ],
    "env": {
        "NODE_ENV": "development"
    },
    "console": "internalConsole",
    "sourceMaps": false,
    "outFiles": []
}
```

¿What should I do in order to use the Chrome Debugger and Node.js debugger at the same time? Something I was thinking is using the "preLaunchTask" attribute to call the Chrome Debugger before Node.js debugger; but I'm not sure if that would work.

Thank you!

**Comment by roblourens** [comment]
We don't allow debugging two things at the same time right now, but watch for a way to do that in 1.7.

**Comment by sant123** [comment]
Excuse me @roblourens, what do you mean about "1.7"? The lastest release is "2.0" and the previous one was "1.2.1".

Thanks.

**Comment by roblourens** [comment]
I mean vscode 1.7, next week.

**Comment by roblourens** [comment]
@samunplugged - Please upgrade to 2.1.1 which should solve your problem. Thanks!
