### ISSUE TITLE
how to debug inside docker?

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode-chrome-debug#263]
Is there any way to attach to a node process inside docker? Or is it completely reliant on command line and process messages? couldn't find any information about this (in a microservice architecture emulation using docker-compose is hard(er) to debug)

**Comment by roblourens** [comment]
This extension is for debugging Chrome not Node, I assume you want https://github.com/microsoft/vscode-node-debug or https://github.com/microsoft/vscode-node-debug2

**Comment by pocesar** [comment]
oops sorry!

**Comment by augustovictor** [comment]
https://gist.github.com/augustovictor/67c69cb91fb91a4321a289c4132a9432

**Comment by auchenberg** [comment]
We have a recipe for this https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript
