### ISSUE TITLE
Breakpoints in 'file:///' URLs not working on Windows

### ISSUE THREAD

**Issue by yizhoucao** [Microsoft/vscode-chrome-debug#264]
all breakpoint stopped working and  showing 'unverified breakpoint' after ungrade to v2.0.0.

everything works fine after i reverted back to v1.2.1.

simple launch.json

{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch Chrome against localhost, with sourcemaps",
			"type": "chrome",
			"request": "launch",
			"file" : "${workspaceRoot}/index.html",
			"sourceMaps": true,
			"webRoot": "${workspaceRoot}"
		}
	]
}

**Comment by roblourens** [comment]
Can you set the diagnosticLogging option to look for clues about why the breakpoints aren't resolving? I can help you if you post the full log from the file path that it will print first.

**Comment by klaasb01** [comment]
I'm having the same issue this is what the debug console is showing when I set a break point.
Verbose logs are written to C:\Users\brian.KLAASSENS\.vscode\extensions\msjsdiag.debugger-for-chrome-2.0.0\vscode-chrome-debug.txt
11:08:02 AM, 10/24/2016
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.2.0
debugger-for-chrome: 2.0.0
spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","file:///c:/Temp/knockout-cart-chapter1/index.html"])
Discovering targets via http://127.0.0.1:9222/json
Discovering targets via http://127.0.0.1:9222/json
Target userAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\vendors\jquery.min.js to c:\Temp\knockout-cart-chapter1\js\vendors\jquery.min.js. webRoot: c:\Temp\knockout-cart-chapter1
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\vendors\bootstrap.min.js to c:\Temp\knockout-cart-chapter1\js\vendors\bootstrap.min.js. webRoot: c:\Temp\knockout-cart-chapter1
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\vendors\knockout.debug.js to c:\Temp\knockout-cart-chapter1\js\vendors\knockout.debug.js. webRoot: c:\Temp\knockout-cart-chapter1
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\models\Product.js to c:\Temp\knockout-cart-chapter1\js\models\Product.js. webRoot: c:\Temp\knockout-cart-chapter1
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js to c:\Temp\knockout-cart-chapter1\js\viewmodel.js. webRoot: c:\Temp\knockout-cart-chapter1
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js

**Comment by roblourens** [comment]
@klaasb01 It looks like it should have set that breakpoint successfully. Can you post the verbose logs from `C:\Users\brian.KLAASSENS.vscode\extensions\msjsdiag.debugger-for-chrome-2.0.0\vscode-chrome-debug.txt`?

**Comment by klaasb01** [comment]
Verbose logs are written to C:\Users\brian.KLAASSENS\.vscode\extensions\msjsdiag.debugger-for-chrome-2.0.0\vscode-chrome-debug.txt
11:08:02 AM, 10/24/2016
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.2.0
debugger-for-chrome: 2.0.0
From client: initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true}}
From client: launch({"name":"Launch index.html","type":"chrome","request":"launch","file":"c:\\Temp\\knockout-cart-chapter1/index.html","sourceMaps":true,"diagnosticLogging":true,"webRoot":"c:\\Temp\\knockout-cart-chapter1"})
spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","file:///c:/Temp/knockout-cart-chapter1/index.html"])
Discovering targets via http://127.0.0.1:9222/json
Discovering targets via http://127.0.0.1:9222/json
Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/ed7118ee-0985-47e1-bfa8-0fad28c9fa8a","id":"ed7118ee-0985-47e1-bfa8-0fad28c9fa8a","title":"","type":"page","url":"file:///C:/Temp/knockout-cart-chapter1/index.html","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/ed7118ee-0985-47e1-bfa8-0fad28c9fa8a"}
WebSocket Url: ws://127.0.0.1:9222/devtools/page/ed7118ee-0985-47e1-bfa8-0fad28c9fa8a
To target: "{\"id\":1,\"method\":\"Debugger.enable\"}"
To target: "{\"id\":2,\"method\":\"Runtime.enable\"}"
To target: "{\"id\":3,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
To target: "{\"id\":4,\"method\":\"Runtime.run\"}"
From target: {"id":1,"result":{}}
From target: {"id":2,"result":{}}
From target: {"error":{"code":-32601,"message":"'Runtime.runIfWaitingForDebugger' wasn't found"},"id":3}
To client: {"seq":0,"type":"event","event":"initialized"}
To target: "{\"id\":5,\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"navigator.userAgent\",\"silent\":true}}"
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
From target: {"id":4,"result":{}}
From client: setExceptionBreakpoints({"filters":["uncaught"]})
To target: "{\"id\":6,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"uncaught\"}}"
From target: {"method":"Runtime.executionContextsCleared","params":{}}
From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"isDefault":true,"origin":"file://","name":"","frameId":"10296.1"}}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"45","url":"","startLine":0,"startColumn":0,"endLine":185,"endColumn":24,"executionContextId":1,"hash":"A0247552321E228369039AE6BD77DC177D990211","isContentScript":false,"isInternalScript":true,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":19,"executionContextId":1,"hash":"261450710E53FAF08507A2B5A8FCEC05872EBA18","isContentScript":false,"isInternalScript":true,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"id":5,"result":{"result":{"type":"string","value":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"},"wasThrown":false}}
Target userAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
From target: {"id":6,"result":{}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":4,"command":"configurationDone","success":true}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"file:///C:/Temp/knockout-cart-chapter1/js/vendors/jquery.min.js","startLine":0,"startColumn":0,"endLine":2067,"endColumn":0,"executionContextId":1,"hash":"238C19037FBCB1C90D7EA1479C75B7CCE696E521","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\vendors\jquery.min.js to c:\Temp\knockout-cart-chapter1\js\vendors\jquery.min.js. webRoot: c:\Temp\knockout-cart-chapter1
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"48","url":"file:///C:/Temp/knockout-cart-chapter1/js/vendors/bootstrap.min.js","startLine":0,"startColumn":0,"endLine":654,"endColumn":10,"executionContextId":1,"hash":"E3E3F5528FA010348F93D9F1C084883743351A37","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\vendors\bootstrap.min.js to c:\Temp\knockout-cart-chapter1\js\vendors\bootstrap.min.js. webRoot: c:\Temp\knockout-cart-chapter1
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"file:///C:/Temp/knockout-cart-chapter1/js/vendors/knockout.debug.js","startLine":0,"startColumn":0,"endLine":5375,"endColumn":0,"executionContextId":1,"hash":"CEF4FA72ECF13DE6F6145A917F2330B107600B61","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\vendors\knockout.debug.js to c:\Temp\knockout-cart-chapter1\js\vendors\knockout.debug.js. webRoot: c:\Temp\knockout-cart-chapter1
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"file:///C:/Temp/knockout-cart-chapter1/js/models/Product.js","startLine":0,"startColumn":0,"endLine":17,"endColumn":0,"executionContextId":1,"hash":"02BD35A2F00001C62CDDE570BB0EB0F7EBF4B2F4","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\models\Product.js to c:\Temp\knockout-cart-chapter1\js\models\Product.js. webRoot: c:\Temp\knockout-cart-chapter1
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"51","url":"file:///C:/Temp/knockout-cart-chapter1/js/viewmodel.js","startLine":0,"startColumn":0,"endLine":67,"endColumn":21,"executionContextId":1,"hash":"BA2B1A51E10EA088685B9214C39ECA59B7CA9430","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: resolved file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js to c:\Temp\knockout-cart-chapter1\js\viewmodel.js. webRoot: c:\Temp\knockout-cart-chapter1
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"52","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"161C81C13B6CBF60409A7482F6820D55C2B88C56","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"8DAFBB528862B1A8A8696AE674C6A8F827564534","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"EC83C50333362241ABC76242FD7AC03A1A745DB4","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"55","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"EC83C50333362241ABC762427D76320B1A745DB4","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"56","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"DFE9810078C23576C858922122406B8CBF005115","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"D1AA0E82D9358B55E4EDB2564D1E9BD83364E355","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"58","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"BAD628E357E9D0C2409A74826B817119BD66A6A7","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"59","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"379F35526054D57AB28A0580FCC5FE18C2B88C56","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"60","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"FB3A63603B6CBF60409A748253B9A4F61D46E714","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"61","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"FB3A63603B6CBF60409A7482D703AC441B7E4051","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"62","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2,"executionContextId":1,"hash":"FB3A63603B6CBF60409A7482D703AC441B7E4051","isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From client: setBreakpoints({"source":{"path":"c:\\Temp\\knockout-cart-chapter1\\js\\viewmodel.js","name":"viewmodel.js"},"lines":[20],"breakpoints":[{"line":20}],"sourceModified":false})
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
To target: "{\"id\":7,\"method\":\"Debugger.setBreakpointByUrl\",\"params\":{\"urlRegex\":\"file:\\\\/\\\\/\\\\/c:\\\\\\\\Temp\\\\\\\\knockout-cart-chapter1\\\\\\\\js\\\\\\\\viewmodel\\\\.js\",\"lineNumber\":19,\"columnNumber\":0}}"
From target: {"id":7,"result":{"breakpointId":"/file:\\/\\/\\/c:\\\\Temp\\\\knockout-cart-chapter1\\\\js\\\\viewmodel\\.js/:19:0","locations":[]}}
To client: {"seq":0,"type":"response","request_seq":5,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1000,"verified":false,"line":null}]}}
From client: setBreakpoints({"source":{"path":"c:\\Temp\\knockout-cart-chapter1\\js\\viewmodel.js","name":"viewmodel.js"},"lines":[],"breakpoints":[],"sourceModified":false})
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
To target: "{\"id\":8,\"method\":\"Debugger.removeBreakpoint\",\"params\":{\"breakpointId\":\"/file:\\\\/\\\\/\\\\/c:\\\\\\\\Temp\\\\\\\\knockout-cart-chapter1\\\\\\\\js\\\\\\\\viewmodel\\\\.js/:19:0\"}}"
From target: {"id":8,"result":{}}
To client: {"seq":0,"type":"response","request_seq":6,"command":"setBreakpoints","success":true,"body":{"breakpoints":[]}}
From client: setBreakpoints({"source":{"path":"c:\\Temp\\knockout-cart-chapter1\\js\\viewmodel.js","name":"viewmodel.js"},"lines":[20],"breakpoints":[{"line":20}],"sourceModified":false})
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
To target: "{\"id\":9,\"method\":\"Debugger.setBreakpointByUrl\",\"params\":{\"urlRegex\":\"file:\\\\/\\\\/\\\\/c:\\\\\\\\Temp\\\\\\\\knockout-cart-chapter1\\\\\\\\js\\\\\\\\viewmodel\\\\.js\",\"lineNumber\":19,\"columnNumber\":0}}"
From target: {"id":9,"result":{"breakpointId":"/file:\\/\\/\\/c:\\\\Temp\\\\knockout-cart-chapter1\\\\js\\\\viewmodel\\.js/:19:0","locations":[]}}
To client: {"seq":0,"type":"response","request_seq":7,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1001,"verified":false,"line":null}]}}
From client: setBreakpoints({"source":{"path":"c:\\Temp\\knockout-cart-chapter1\\js\\viewmodel.js","name":"viewmodel.js"},"lines":[],"breakpoints":[],"sourceModified":false})
SourceMaps.setBP: SourceMaps are enabled but c:\Temp\knockout-cart-chapter1\js\viewmodel.js is a runtime script
Paths.setBP: Resolved c:\Temp\knockout-cart-chapter1\js\viewmodel.js to file:///c:\Temp\knockout-cart-chapter1\js\viewmodel.js
To target: "{\"id\":10,\"method\":\"Debugger.removeBreakpoint\",\"params\":{\"breakpointId\":\"/file:\\\\/\\\\/\\\\/c:\\\\\\\\Temp\\\\\\\\knockout-cart-chapter1\\\\\\\\js\\\\\\\\viewmodel\\\\.js/:19:0\"}}"
From target: {"id":10,"result":{}}
To client: {"seq":0,"type":"response","request_seq":8,"command":"setBreakpoints","success":true,"body":{"breakpoints":[]}}

**Comment by roblourens** [comment]
I see, I'm not handling this right for `file:///` paths anymore. Until I fix it, you could work around it by serving files from a webserver, which is a better-tested scenario.

An easy way to set one up is `npm i -g http-server` then `http-server -p 8080` in the directory to serve files from.

**Comment by klaasb01** [comment]
Thanks for the answer. Though I was going crazy.

**Comment by auchenberg** [comment]
Let's make sure we'll add some test cases for `file://` too. New back log item?

**Comment by roblourens** [comment]
Fixed in 2.1.0 (with tests!)

https://github.com/Microsoft/vscode-chrome-debug-core/commit/e100031ef67c33485a6c83fb1110e40b11fa4dc7
