### ISSUE TITLE
Console logs missing in pre-Chrome 54

### ISSUE THREAD

**Issue by mpricope** [Microsoft/vscode-chrome-debug#265]
Hey there,

I am trying to use the chrome-debug extension to debug my files but one thing I can't seems to get it working is to see the console.log output into the "Debug Console".

The problem is that once I open the Chrome Console cause it will the attach session will automatically end ... so I can't use that to see the output of the console.log statements.

Maybe I am doing something wrong but I can't figure it out what. 

In the "Debug Console" I can type for example:
console
and I will get the full console object. 

however console.log doesn't display anything.

**Comment by roblourens** [comment]
Can you tell me which version of Chrome you're using?

**Comment by mpricope** [comment]
I use Version 53.0.2785.116 (64-bit) (on Linux)

**Comment by roblourens** [comment]
Is there any reason you can't upgrade to 54, the latest stable? I had expected that most people would have done that by now, because their console API changed for 54. But if not, I can add back-compatibility for that.

**Comment by mpricope** [comment]
oh with 54 it works, thanks!. Didn't knew it's out there :)

**Comment by roblourens** [comment]
Cool, sounds like lots of people are still pre-54 though.

**Comment by mpricope** [comment]
thanks a lot for your support!

**Comment by lostfictions** [comment]
Thanks for keeping this issue open! I'm also on Linux (Ubuntu 14.04) and my package manager simply hasn't caught up with upstream yet, so I'm still on Chromium 53. I imagine I'm far from the only one in this sort of situation, so back-compat would be much appreciated!

**Comment by avandecreme** [comment]
I have this issue with Chromium 54 as well.

**Comment by roblourens** [comment]
Fixed in 2.2.0

f1682b2b0d3aa34fdcee2c26611d63ec063a67bd
