### ISSUE TITLE
Unverified breakpoint

### ISSUE THREAD

**Issue by Krimik** [Microsoft/vscode-chrome-debug#267]
Hi. I have been using vscode successfully to debug javascript for a while, but since about 1 day all my breakpoints stopped working and started getting Unverified breakpoint status like [this](https://i.imgur.com/pVStx6l.png).

Debugger stops fine when using `debugger;` statement

My launch.json is:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch index.html",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true
        },
        {
            "name": "attach to chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true            
        }
    ]
}
```

and diagnistics log returns this: http://pastebin.com/kxKDe1uy

**Comment by roblourens** [comment]
Breakpoints in file:/// URLs aren't working right now, tracked in this bug #264. I'll fix ASAP
