### ISSUE TITLE
2.0 hides console.log output for remote debugging

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-chrome-debug#271]
Same setup, 1.2.1:

![image](https://cloud.githubusercontent.com/assets/4033249/19736384/e162e850-9b63-11e6-9b11-6cad5b68dcf0.png)

2.0.0:

![image](https://cloud.githubusercontent.com/assets/4033249/19736444/16c0b18a-9b64-11e6-8718-6c7d95824510.png)

Originally reported at: https://github.com/octref/vscode-electron-debug/issues/4

Can you try running this project, for renderer process:

https://github.com/octref/vscode-electron-debug/tree/master/electron-quick-start-es6

**Comment by roblourens** [comment]
This is #265 - i'll do something about that.
