### ISSUE TITLE
In Watch window I can view Preview of Object (first 3 properties), but cannot expand object to view all the properties of object

### ISSUE THREAD

**Issue by achawla5000** [Microsoft/vscode-chrome-debug#273]
I believe this issue started with the latest version of vscode-chrome-debug.

**Comment by roblourens** [comment]
Can you show me a screenshot?

**Comment by ChristopherMack** [comment]
I'm also having this issue 
![chromedebugger](https://cloud.githubusercontent.com/assets/22960906/19851354/62ec6e06-9f55-11e6-85a1-53a5a732f440.PNG)

As you can see the modalInstance has not expanded

**Comment by dsm0880** [comment]
I'm getting the exact same behavior. Seems to have happened when I updated to the latest version 2.1.1.

**Comment by roblourens** [comment]
Actually I have seen this a couple times. This will be fixed in 1.7 but I'll get a fix out.

**Comment by roblourens** [comment]
Ok, fixed in 2.1.2. I made a change that shouldn't have been run against 1.6. Sorry and thanks for all the reports!

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/commit/173e43ffc245fda1e9aaa1b98bf9ab94178090b5
