### ISSUE TITLE
Breakpoint Render issue. 

### ISSUE THREAD

**Issue by MeirionHughes** [Microsoft/vscode-chrome-debug#275]
I have project that looks like this: 

```
./source/app.ts
./source/widgets/widget-plot3d.ts
./index.html
./output/app-bundle.js
```
The source maps generated are pretty sound; Chrome has no issues with any source file, and breakpoints in chrome will hit perfectly. 

Since updating to 2.1.2, the debugger does a good job of hitting the breakpoints. 

One minor issue is that when if I add a breakpoint while debugging, when the page is refreshed the rendered breakpoints move to the end of the file. Yet, the application will still break on the original breakpoints. It stays this way until I reload the application entirely, at which point the breakpoint at the end of the file is removed and the original breakpoints show up again. 

![breakpoints moving 1](https://cloud.githubusercontent.com/assets/3584509/19886755/8b40b52a-a01c-11e6-974d-84743ceb0d92.gif)

**Comment by roblourens** [comment]
Are you using any framework to bundle like webpack or meteor? Is this a project on github that I can try? Can you set 'diagnosticLogging' in your launch config and upload the full log file (from the path that it writes out on the first line)?

**Comment by MeirionHughes** [comment]
its bundled into require style module bundle (I think) by aurelia's cli. 

I have a small test app that should hopefully be easy to setup. 

steps:
clone
`npm install`
`npm run build` _if this doesn't work you might need to do `npm install aurelia-cli -g`
in vscode go to source/window.ts
add breakpoint to line 10 (window.ts)
press f5
press f5 (continue)
add breakpoint to line 15 (window.ts)
app: press the question mark top right. 
app: click focus on chrome debug section and press f5 (refresh electron page)

at this point the breakpoint on line 11 will hit, but the breakpoints themselves will be shown on line 47. 


... and if you want it; this is the log of a) setting a breakpoint and b) refreshing the electron app. 

>Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\common\api\callbacks-registry.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\browser\api\exports\electron.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\content-scripts-injector.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\web-view\web-view.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\api\web-frame.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\web-view\guest-view-internal.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\web-view\web-view-constants.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\web-view\web-view-attributes.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: resolved file:///d:/Code/aurelia-cli-electron-app/index.html to d:\Code\aurelia-cli-electron-app\index.html. webRoot: undefined
Paths.scriptParsed: resolved file:///d:/Code/aurelia-cli-electron-app/output/vendor-bundle.js to d:\Code\aurelia-cli-electron-app\output\vendor-bundle.js. webRoot: undefined
Paths.scriptParsed: resolved file:///d:/Code/aurelia-cli-electron-app/output/app-bundle.js to d:\Code\aurelia-cli-electron-app\output\app-bundle.js. webRoot: undefined
SourceMaps.scriptParsed: d:\Code\aurelia-cli-electron-app\output\app-bundle.js was just loaded and has mapped sources: ["d:\\Code\\aurelia-cli-electron-app\\source\\app.ts","d:\\Code\\aurelia-cli-electron-app\\source\\environment.ts","d:\\Code\\aurelia-cli-electron-app\\source\\main.ts","d:\\Code\\aurelia-cli-electron-app\\source\\elements\\dock-panel.ts","d:\\Code\\aurelia-cli-electron-app\\source\\elements\\index.ts","d:\\Code\\aurelia-cli-electron-app\\source\\elements\\menu-control.ts","d:\\Code\\aurelia-cli-electron-app\\source\\elements\\tab-control.ts","d:\\Code\\aurelia-cli-electron-app\\source\\elements\\window.ts","d:\\Code\\aurelia-cli-electron-app\\source\\models\\page.ts","d:\\Code\\aurelia-cli-electron-app\\source\\pages\\example-page.ts","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\compose.js","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\if.js","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\with.js","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\repeat.js","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\repeat-strategy-locator.js","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\null-repeat-strategy.js","d:\\Code\\aurelia-cli-electron-app\\node_modules\\aurelia-templating-resources\\dist\\amd\\a[...]Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\common\api\clipboard.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\common\api\crash-reporter.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve os.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\common\api\native-image.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\common\api\shell.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\api\desktop-capturer.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve d:\Code\aurelia-cli-electron-app\node_modules\electron\dist\resources\electron.asar\renderer\api\screen.js to a file under webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).

**Comment by roblourens** [comment]
Thanks - I'm trying your project, but there is no npm script 'build'

**Comment by MeirionHughes** [comment]
oh dam, sorry, forgot to push it. should be up now. it was just a helper to call `au build` with the local node bin.

**Comment by roblourens** [comment]
Thanks. This works just fine for me actually. But note that you usually won't be able to use the builtin chrome devtools at the same time as the chrome extension in vscode. In this case, it looks like the chrome devtools just fail to attach when the extension is attached for some reason, which isn't usually how it works.

Can you try upgrading to 2.1.3 just in case I fixed it with a tweak in the last release? If you still see a problem, can you upload the full log file here? Thanks.

**Comment by MeirionHughes** [comment]
yeah the only reason I mention to go to the chrome tools was so that you can press f5 and refresh chromium/electron; or you can unhide the frame (index.js:20 ) and use the electron menu to refresh. 

That is what causes the breakpoints to go funny. I'm on 2.1.3 at home and it occurs here too. I am on Windows 10 in both instances... by any chance are you on OSX / Ubuntu?

**Comment by roblourens** [comment]
I tried on both OSX and Windows 10 with the same result. Can you upload the full log, from the file at the path printed at the top of the debug console? What you posted isn't the whole thing.

**Comment by auchenberg** [comment]
Ping @MeirionHughes

**Comment by MeirionHughes** [comment]
Tested this on vscode 1.8.1 and chrome-debugger 2.4.1 and the problem appears to have been resolved (at least on my home machine).
