### ISSUE TITLE
debugger doesn't work (adapter terminates immediately) for VSCode 1.7.1 on Linux

### ISSUE THREAD

**Issue by StephenMcConnel** [Microsoft/vscode-chrome-debug#276]
When I try to launch the debugger on Linux, I always get "Debug adapter process has terminated unexpectedly" immediately.  The browser does come up with the expected page showing and interacting with the server, but none of the debugging operations work.  My launch profile looks like this:
        {
            // Note the changed executable path.
            "name": "Launch Linux Chromium",
            "type": "chrome",
            "request": "launch",
            "externalConsole": true, // so console.log shows up in vscode "Debug Console"
            "runtimeExecutable": "/usr/bin/chromium-browser",
            "url": "http://localhost:8089/bloom/CURRENTPAGE.htm",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "userDataDir": "${workspaceRoot}/output/chrome"
        },
It was working okay with this launch profile for an earlier version of VSCode and the debugging extension.  I think we're using TypeScript 2.0.6 in our project if that makes any difference.

**Comment by roblourens** [comment]
Do you have the latest version of the extension? It was updated recently. Are there any errors in the dev tools? (Help > Toggle developer tools). Can you set `"verboseDiagnosticLogging": true` and look for errors?

**Comment by StephenMcConnel** [comment]
I  updated the extension today after updating VSCode to version 1.7.1.  I'm
attaching a file showing the output of the Debug Console and a stack trace
from the internal debugger Console tab.  I hope this may be helpful --
nothing said much to me (even if there's something glaringly obvious to
you).  Nothing has changed on my machine's setup since earlier versions of
VSCode and the chrome debugger worked okay.  Thanks for looking into this.
--
Steve McConnel

**Comment by roblourens** [comment]
Thanks. I don't see a file though - if you attached it to an email, it may not have made it to github.

**Comment by DizWARE** [comment]
I also am getting the same issue with the newest VSCode and the newest version of the extension. It started happening after I updated.

Here's my verbose log. It's interesting because sometimes I get the "Debug adapter process has terminated unexpectedly" error and sometimes it is the "Socket closed" error, but they seem to be related.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/572783/vscode-chrome-debug.txt)

**Comment by StephenMcConnel** [comment]
Yes, my earlier comment was via email.  Either github didn't like the filename extension or it didn't like attachments in general.  I'm attaching it here again.  For what it's worth, the same versions of VSCode, chrome debugger, and my local code work fine on Windows.  I've only ever seen the "Debugger adapter process has terminated unexpectedly message", but it happens every time on Linux for me.

[vscode-linux-debugger-stopped.txt](https://github.com/Microsoft/vscode-chrome-debug/files/572802/vscode-linux-debugger-stopped.txt)

**Comment by roblourens** [comment]
Hm, there is nothing wrong in either log file. Does this happen every time, and does it only happen in that project, or can you use it successfully in another project?

I think "socket closed" also just means the debug adapter crashed.

**Comment by roblourens** [comment]
I can push a change that logs unhandled exceptions before crashing (which I should have done already...)

**Comment by roblourens** [comment]
2.2.1 should at least log the error before crashing. Would be very helpful if you let me know what the error is

**Comment by StephenMcConnel** [comment]
Here's a new crash log file, containing both the DEBUG CONSOLE and the Developer Tools Console tab content.
[VSCode-chrome-debugger-Linux-crash1.txt](https://github.com/Microsoft/vscode-chrome-debug/files/576166/VSCode-chrome-debugger-Linux-crash1.txt)

**Comment by roblourens** [comment]
Ah, thanks! I started supporting the older version of the console log event for backwards compatibility (and apparently for chromium compatibility), and you and @DizWARE are getting that event in a different format than what I've seen. Fixing it to handle that style too. In the meantime, if you can use the latest version of Chrome, that should fix it too.

**Comment by StephenMcConnel** [comment]
I have verified that the current debugger works on linux with thegoogle-chrome-stable_current_amd64.deb package downloaded from https://www.google.com/chrome/browser/desktop/index.html.  This is running on a derivative of Ubuntu 14.04 ("trusty").

**Comment by FDiskas** [comment]
Works for me
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "runtimeExecutable": "/usr/bin/chromium-browser",
            "runtimeArgs": [
                "--remote-debugging-port=9222"
            ],
            "request": "launch",
            "name": "Chromium against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "smartStep": true,
            "verboseDiagnosticLogging": true
        }
    ]
}
```
:cinema:
