### ISSUE TITLE
Pending breakpoints resolved after refreshing the page sometimes don't bind correctly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#279]
- Have breakpoints set in a script that can't be resolved
- Refresh the page, causing them to be bound

Depending on how quickly things happen, the breakpoints will then sometimes show up as gray, because the debug adapter might incorrectly assign new breakpoint IDs instead of reusing the existing ones.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/commit/b462b96bb5674e5a6c4de2bc2b14348feb6f9234

**Comment by apozgaj** [comment]
Hello,

So, I have 2.2.2 version and it seems that I have the exact problem.
I'm having angular2+webpack2 app which I want to debug with vscode and when I start the debugger it:
1) doesn't place the breakpoints at the right places
2) doesn't hit them until I refresh the page
3) hits them in wrong order (e.g. functionA calls functionB - but the debugger will hit breakpoint in function B first

I'd gladly send you the debug log just let me know how you want it.

Thanks,
Andrija

**Comment by roblourens** [comment]
Not the same as this bug, this was for a specific case.

1. Not sure what you mean by 'not at the right places'. The log says the breakpoints were requested and set at lines 11 and 21
2. That's sometimes expected if your code runs immediately when the page loads. The readme says a little more about this but the code may run before the debugger attaches.
3. The breakpoints will be hit at the time that code is running - I would look more carefully or check if it's different in chrome devtools.

**Comment by apozgaj** [comment]
Ok, apologies for making noise on this bug, however, by "not at the right places" means that the log is correct but when I start the vscode debugger these breakpoints are not shown and there's only 1 breakpoint at the end of the file (in vscode).

I'm generally ok with the number 2.

3. in chrome, breakpoints are hit in the correct order but in vscode it's the opposite order.

Here's the screenshot of the code related with the logs I've sent:
![image](https://cloud.githubusercontent.com/assets/3367509/20354670/3563953c-ac1f-11e6-8dbc-0924135e0b95.png)

**Comment by roblourens** [comment]
Ok it's interesting because the log doesn't show the breakpoint going to line 27 like it usually would in this case. So I'm kind of baffled.

**Comment by apozgaj** [comment]
Yeah, I have problems with removing that breakpoint later. Beside that, in this screenshot, you can see that bp on ln 21 was the first one that was hit. If I hit "continue" for couple of times, I'll get to the breakpoint on ln 11.

Do you want me to open a new bug maybe?

**Comment by roblourens** [comment]
Sure. Would appreciate if you take another shot at the logs in case it missed something, but the one you posted just doesn't fit the screenshot.

If it's the typical sort of problem here, since you're using webpack, I would check which sourcemap option you're using, and try to use one of the simpler ones like `devtool: 'source-map'` if you aren't.
