### ISSUE TITLE
Enhancement: Select open tab on start debug

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode-chrome-debug#280]
Hey guys

First of all: Thank you for your work! It's a very nice feature to have vscode debug the whole chrome stuff! 👍 

I'd like to suggest a feature at this point: It would be cool if one can configure the `launch.json` as such, that on hitting <insert start debug button here>, a small `showQuickPick` would open and show all possible open tabs. One can then choose the actual tab to attach to.

This feature would be particularly awesome when debugging with query parameters and stuff.

Example: 

Actual url pointing to localhost:3001/foobar
Hit F5, select this tab, debug, be happy.

Now you change the url (without the attached debugger) to localhost:3001/foobar?whatever
To attach to this tab, you need to edit the launch.json to match the url exactly.

In this case it would be cool to set the url to undefined and have a flag like "select tab on debug" or whatever so one can choose the url to attach to.

Cheers
Chris

**Comment by buehler** [comment]
Hey guys, I did not see the option to use `*` in the url-field. So for now, I'm good to go ;-)

**Comment by roblourens** [comment]
When using an 'attach' config, and multiple matching targets are encountered, a quickpick will offer the choice of tabs:

![image](https://cloud.githubusercontent.com/assets/323878/25213050/f9f5ed72-2542-11e7-879a-5387165ba55b.png)

Otherwise, same experience as usual.

**Comment by auchenberg** [comment]
Booya! 👍 🔥 🎊
