### ISSUE TITLE
Support or strip colour format codes in console log

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode-chrome-debug#282]
There are modules (such as [debug](https://github.com/visionmedia/debug) and [redux-logger](https://github.com/evgenyrodionov/redux-logger)) that that advantage of the `%c` formatting code (supported by Chrome and Firefox) in their console output. But in VSCode, I get stuff like this:

```
color: lightseagreenAnalyticsStore color: inheritPublishing eventcolor: lightseagreen +2s exposedListingResult Array[6]
color: forestgreenHydrantAnalyticsAdapter color: inheritPublishing eventscolor: forestgreen +0ms exposedListingResult Array[6]
```

While it might be possible to configure these turn colours off, it's not really desirable just to make the debugger plugin print nicely. Support for stripping unknown format codes in general would be nice.

**Comment by roblourens** [comment]
Technically, since the debug console supports color codes, I could support the colors. It would take some effort to map CSS colors to terminal colors though. 

I'll strip them for now, so it's more readable.

**Comment by roblourens** [comment]
Change to strip them, but will keep this open to show colors - https://github.com/Microsoft/vscode-chrome-debug-core/commit/bce3d601d63538601efde8afb0b559111bd25395

**Comment by atombender** [comment]
Awesome, thanks.

**Comment by aulisius** [comment]
Hey, I would like to work on this. Where do I start looking?

**Comment by roblourens** [comment]
Somewhere around here: https://github.com/Microsoft/vscode-chrome-debug-core/blob/a7e6923367153aa5bbefa29c41b4b220174db434/src/chrome/consoleHelper.ts#L145

That function takes a format specifier like `%d` and a value, and returns the formatted value. So here it will take `%c` and the color parameter and you will have to return the color escape code.

This can be used like `console.log('%c test1 %c test2', 'background-color: #222; color: #00ff00', 'color: red');` I think basically any CSS is valid. So you will have to parse that and match it to terminal color codes.

**Comment by rdegelo** [comment]
I have managed to support color and bold format. "Debug Console" is very limited though, only ~14 colors supported.

I had to import Color library to parse rbg to ansi16. Not sure if I can contribute with I have.

**Comment by roblourens** [comment]
I'd like to see what you have if you want to submit a PR!

**Comment by connor4312** [comment]
This was implemented in the linked PR, and also works in the [new debugger](https://github.com/microsoft/vscode-js-debug/) (default since 1.47).
