### ISSUE TITLE
console.log doesn't work in vscode console when connected to chrome

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug#284]
VSCode: Version 1.7.1 (1.7.1)
Chrome:Version 54.0.2840.71 (64-bit)

```
console.log("asdf")
undefined
Unimplemented console API: undefined
```

**Comment by roblourens** [comment]
Are you using the latest version of the extension?

**Comment by nojvek** [comment]
I see, this seems to be fixed after updating the extension. Thanks.

![image](https://cloud.githubusercontent.com/assets/1018196/20320044/50365b9c-ab25-11e6-9580-55b72084d574.png)

I see the weird undefined as well. Could be that this is actually sent from chrome so not really a bug.

**Comment by roblourens** [comment]
That's what console.log returns, same in F12 ;)
