### ISSUE TITLE
Enhancement: support "env" and "cwd"

### ISSUE THREAD

**Issue by arolson101** [Microsoft/vscode-chrome-debug#286]
I'm using the chrome debugger with electron; it works great but I can't figure out how to set the NODE_ENV environment variable to "development".  It would be great if it supported the "env" key to set environment variables.

Similarly, the "cwd" when running through the chrome debugger is "C:\Program Files (x86)\Microsoft VS Code" which causes problems when using relative paths expecting the project directory

**Comment by roblourens** [comment]
Where do environment variables come into play for Chrome? A webpage can't read env variables.

**Comment by arolson101** [comment]
It would be for the process itself; ie when using runtimeExecutable

**Comment by roblourens** [comment]
Are you using it to debug something that isn't chrome?

**Comment by arolson101** [comment]
correct- I'm using [electron](http://electron.atom.io)

**Comment by roblourens** [comment]
Got it, that's fair

**Comment by joechiu-msft** [comment]
For Electron app, it's quite common to pass additional parameter into the app using environment variables. Please consider upping the priority on this one.

**Comment by thiagoabreu** [comment]
The [Electron-forge](https://github.com/electron-userland/electron-forge) tool checks the current directory to validade if it's running a Electron app, so it's impossible to launch it with the chrome-debug.

I think the `cwd` should be supported at least when the `runtimeExecutable` is set.
