### ISSUE TITLE
Need 250ms startup delay to trigger breakpoints

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode-chrome-debug#288]
React app, launching in Chrome (Version 54.0.2840.98 (64-bit)) . Pre-existing breakpoints do not get triggered unless I put a 250ms delay before starting up ReactDom.render. 100ms delay is insufficient. Attaching logs for both cases:
[vscode-chrome-debug-100ms.txt](https://github.com/Microsoft/vscode-chrome-debug/files/596262/vscode-chrome-debug-100ms.txt)
[vscode-chrome-debug-250ms.txt](https://github.com/Microsoft/vscode-chrome-debug/files/596263/vscode-chrome-debug-250ms.txt)

**Comment by roblourens** [comment]
Right, this is expected. We can't hit breakpoints in code that runs before the debugger is able to attach. They should be hit if you refresh the page though.
