### ISSUE TITLE
Refreshing page undoes breakpoint source mapping

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode-chrome-debug#289]
I set a breakpoint and launch in chrome. The breakpoint doesn't trigger because of race with execution. I refresh the page. The breakpoint triggers correctly, but the red dot is displayed at the wrong place, using the line number in the compiled .js, not the source .ts. The breakpoints panel also indicates this by saying "18->97" for the line number. Log attached:
[vscode-chrome-debug-refresh.txt](https://github.com/Microsoft/vscode-chrome-debug/files/596310/vscode-chrome-debug-refresh.txt)

**Comment by roblourens** [comment]
I think this is fixed in 2.3.0, can you try it out? Thanks!

**Comment by JonathanMEdwards** [comment]
Fixed! Thanks.
