### ISSUE TITLE
what port number I should use in the url configure line

### ISSUE THREAD

**Issue by yuren1978** [Microsoft/vscode-chrome-debug#290]
In the launch.json, on url line, I would like to know what port number I should use ?

Here is what I use,

 "url": "http://localhost:9222/demo01/index.html"

However, I got the error "cannot connect to the runtime process, timeout after 10000 ms", I am not sure what port number to configure here.

**Comment by auchenberg** [comment]
The `url` should point to the your of your local webserver or the url of the page you want to debug.

The `port` property is the debugging port for Chrome, which is default `9222`
