### ISSUE TITLE
Breapoints are not hit in correct order and location is not accurate in VSCode

### ISSUE THREAD

**Issue by apozgaj** [Microsoft/vscode-chrome-debug#291]
Related to the conversation on bug #279, I'm opening a new ticket.
There are two problems I see:
1) when I have 2 functions and I set breakpoint in each of them, they are not affected in correct order; let's say functionA calls functionB, the breakpoint in functionB will be the first one I'll hit

2) As you can see in the screenshot in the related issue, breakpoints are dislocated during the debugging session and additional breakpoints appear at the end of the file while debug log says there's no breakpoint at the end of the file.

I've uploaded the example here: [https://github.com/apozgaj/angular2-webpack2-setup](url)

**Comment by roblourens** [comment]
This example works for me with v2.3.0. There was an issue fixed with breakpoints moving when the page refreshes - hopefully that was it. Let me know if it still reproes.
