### ISSUE TITLE
Sourcemaps are not mapping to the proper place in TS files

### ISSUE THREAD

**Issue by Cammisuli** [Microsoft/vscode-chrome-debug#294]
Using webpack, with source maps enabled, breakpoints do not go to their proper place in the .ts file. 
Shown here:
![breakpoints-moving](https://cloud.githubusercontent.com/assets/4332460/20574545/f6f521c6-b182-11e6-8efd-950ee6753fd1.gif)

In the logs I get the following:
```SourceMaps.setBP: Mapped C:\Development\git\ngui\WWW\portals\console\_dist\portal.bundle.js:65860:9 to c:\Development\git\ngui\WWW\portals\console\app\views\login\login.view.ts:38```

Clicking the link for the portal.bundle.js file goes here:
![image](https://cloud.githubusercontent.com/assets/4332460/20574616/64e31c88-b183-11e6-8003-b628cf8b6b5d.png)

Placing the same breakpoint in chrome leaves it in the same spot where it was clicked:
![image](https://cloud.githubusercontent.com/assets/4332460/20574666/ab15c110-b183-11e6-8630-713f9c1e632d.png)

My launch configuration is this:
```
{
    "name": "Launch Chrome with sourcemaps",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:8080/console",
    "sourceMaps": true,
    "webRoot": "${workspaceRoot}/WWW",
    "diagnosticLogging": true,
    "userDataDir": "${workspaceRoot}/.vscode/chrome",
    "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceRoot}/*"
    },
    "runtimeArgs": [
        "--disable-session-crashed-bubble",
        "--disable-infobars"
    ]
}
```

Extension version is `2.2.2`

If more information is needed, I'll try my best to provide it. Thanks!

**Comment by roblourens** [comment]
Can I see your webpack config? Some of the crazier 'devtool' settings won't work correctly.

**Comment by Cammisuli** [comment]
Just using source-map:
```
module.exports = function (env) {
    return webpackMerge(portalConfig(env), {
        devtool: 'source-map',
        watch: true,
        module: {
            rules: [
                {
                    test: /\.scss$|\.sass$/,
                    exclude: /node_modules/,
                    loaders: [
                        'style-loader',
                        {
                            loader: 'css-loader',
                            options: {
                                sourceMap: true
                            }
                        },
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: true
                            }
                        }
                    ]
                }
            ]
        },
        node: {
            global: true,
            crypto: 'empty',
            process: true,
            module: false,
            clearImmediate: false,
            setImmediate: false
        }
    });
}
```

**Comment by roblourens** [comment]
Can you see if it still reproes in 2.3.0? If so, does this happen everywhere or just that one case? Can you upload the whole verbose log?

**Comment by Cammisuli** [comment]
Yup, still appears to be happening. Break points jump to a different location.

Here's the verbose log I got:
https://gist.github.com/Cammisuli/4ec947aa357f1b710d17ede09e88deb6

**Comment by roblourens** [comment]
Thanks, but I can't tell what the problem is from the log in this case. Is this a project on github that I can try?

**Comment by gbaldeck** [comment]
I'm experiencing the same issue.

**Comment by roblourens** [comment]
Same questions for you then @gbaldeck

**Comment by Cammisuli** [comment]
@roblourens, the project isn't on github, but i'll try and see if i can make a simpler project where this is reproducible.

**Comment by Cammisuli** [comment]
@roblourens I'm pleased to say that the latest release (2.4.2) fixed the source map issue for me. It now keeps the breakpoint in the proper spot and pauses at the right code. Thanks!

**Comment by brianppoole** [comment]
I'm having this same issue, even on 2.4.2, unfortunately.
 
I'm using JSPM to pack everything, which I'm still learning about, so I hope that's not the issue, but Chrome's native debugger seems to work OK.
`jspm build myproject dist/scripts/main.js --global-name myproject --minify --watch`

Diagnostics output for clicking a breakpoint:
`SourceMaps.setBP: Mapped /home/brian/workspaces/myproject/app/scripts/stage.js to /home/brian/workspaces/myproject/dist/scripts/myproject.js
SourceMaps.setBP: Mapped /home/brian/workspaces/myproject/app/scripts/stage.js:39:1 to /home/brian/workspaces/myproject/dist/scripts/myproject.js:5:1272
Paths.setBP: Resolved /home/brian/workspaces/myproject/dist/scripts/myproject.js to http://localhost:8080/scripts/myproject.js
SourceMaps.setBP: Mapped /home/brian/workspaces/myproject/dist/scripts/myproject.js:5:1307 to /home/brian/workspaces/myproject/app/scripts/stage.js:41'`

Is there anything else I can do to diagnose? (And let me know if I should file a new issue.)

**Comment by roblourens** [comment]
Is this a project that I can try? I haven't used jspm

**Comment by brianppoole** [comment]
I'll put together a more basic example the next time I get a moment. In the meantime I'll PM you a link in case you'd like to try anyway.

**Comment by brianppoole** [comment]
JSPM's toolchain seems to be culprit here, as roblourens discovered that even Chrome is showing those lines as invalid breakpoints.
