### ISSUE TITLE
Issue while debugging angular2 rc project using VS code and chrome debugger extention

### ISSUE THREAD

**Issue by anisharknair** [Microsoft/vscode-chrome-debug#295]
@willbar  am facing issues while debugging using VS code editor.But I am bale to debug using chrome developer tools.

Break points are not hitting and its showing in grey circle.

Also in console I am getting this error .

<img width="726" alt="issue" src="https://cloud.githubusercontent.com/assets/5848157/20616023/25232a60-b305-11e6-94f4-8e0e74817814.PNG">

Here is my launch.json.

"version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000/",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",

			// Uncomment this to get diagnostic logs in the console
			 "diagnosticLogging": true
 /*"sourceMapPathOverrides": {
              "webpack:///c:/Users/anisha.rn/angular-2-hello-world/*": "${workspaceRoot}/*"
          }*/
	
        },

THis is my app folder structure.
![image](https://cloud.githubusercontent.com/assets/5848157/20616251/ec36776e-b306-11e6-89ad-930d18a6b516.png)

This is my index.html.

![image](https://cloud.githubusercontent.com/assets/5848157/20616280/206e4688-b307-11e6-83b2-9fc60ee1bedb.png)

**Comment by roblourens** [comment]
That error would be coming from your app. You don't see it in Chrome devtools?

**Comment by anisharknair** [comment]
Thanks for your reply,
But I am not getting any error in chrome developer tools and I am able to debug,only with VS code editor i am not able to debug and its not hitting breakpoints at all.Application is running without any errors,only problem when it comes to debugging with VS code editor.Is there any problem related to debugging in VS code editor for angular rc version applications,because beta version I am able to debug using VS code.

**Comment by roblourens** [comment]
You're saying that you don't get an error debugging with the  angular beta, but you do with the angular rc? I don't know what the problem is but it must be a problem with angular or your app, sorry.
