### ISSUE TITLE
Typescript Breakpoints

### ISSUE THREAD

**Issue by Bforsyth1234** [Microsoft/vscode-chrome-debug#298]
Hi I am having an issue where the break points on my TS files are greyed out. I can make the breakpoints work in my js files but not my ts files. My app directory is setup like so at the root of the project the dist folder has the .js files and the src folder that is at the root has the corresponding typescript files.

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3002",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/dist",
            "diagnosticLogging": true
        }
    ]
}

**Comment by roblourens** [comment]
What's the output if you type `.scripts` in the console?

**Comment by Bforsyth1234** [comment]
Its pretty big. Im not sure why but the debug console in vs code wont let me copy and paste the whole thing..... 





› http://localhost:3002/app/common/services/logout/logout.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/logout/logout.service.js)
    - common/services/logout/logout.service.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/logout/common/services/logout/logout.service.ts)
› http://localhost:3002/app/common/services/messaging/messaging.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/messaging/messaging.service.js)
    - common/services/messaging/messaging.service.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/messaging/common/services/messaging/messaging.service.ts)
› http://localhost:3002/app/common/services/modal/modal.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/modal/modal.service.js)
    - common/services/modal/modal.service.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/modal/common/services/modal/modal.service.ts)
› http://localhost:3002/app/common/services/moduleLoader/module.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/moduleLoader/module.js)
    - common/services/moduleLoader/module.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/moduleLoader/common/services/moduleLoader/module.ts)
› http://localhost:3002/app/common/services/moduleLoader/moduleLoader.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/moduleLoader/moduleLoader.service.js)
    - common/services/moduleLoader/moduleLoader.service.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/moduleLoader/common/services/moduleLoader/moduleLoader.service.ts)
› http://localhost:3002/app/common/services/sessionManagement/navigate.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/sessionManagement/navigate.js)
    - common/services/sessionManagement/navigate.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/sessionManagement/common/services/sessionManagement/navigate.ts)
› http://localhost:3002/app/common/services/sessionManagement/session.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/sessionManagement/session.service.js)
    - common/services/sessionManagement/session.service.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/sessionManagement/common/services/sessionManagement/session.service.ts)
› http://localhost:3002/app/common/services/shortcuts/shortcuts.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/shortcuts/shortcuts.service.js)
    - common/services/shortcuts/shortcuts.service.ts (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/shortcuts/common/services/shortcuts/shortcuts.service.ts)
› http://localhost:3002/app/common/services/specialbrowser/ie-saf-lifecycle-hook.service.js (/Users/brooksforsyth/dev/htmlclient/dist/app/common/services/specialbrowser/ie-saf-lifecycle-hook.service.js)
 




Further down ... 

› http://localhost:3002/lib/rxjs/add/operator/retry.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/retry.js)
› http://localhost:3002/lib/rxjs/add/operator/retryWhen.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/retryWhen.js)
› http://localhost:3002/lib/rxjs/add/operator/sample.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/sample.js)
› http://localhost:3002/lib/rxjs/add/operator/sampleTime.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/sampleTime.js)
› http://localhost:3002/lib/rxjs/add/operator/scan.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/scan.js)
› http://localhost:3002/lib/rxjs/add/operator/sequenceEqual.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/sequenceEqual.js)
› http://localhost:3002/lib/rxjs/add/operator/share.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/share.js)
› http://localhost:3002/lib/rxjs/add/operator/single.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/single.js)
› http://localhost:3002/lib/rxjs/add/operator/skip.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/skip.js)
› http://localhost:3002/lib/rxjs/add/operator/skipUntil.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/skipUntil.js)
› http://localhost:3002/lib/rxjs/add/operator/skipWhile.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/skipWhile.js)
› http://localhost:3002/lib/rxjs/add/operator/startWith.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/startWith.js)
› http://localhost:3002/lib/rxjs/add/operator/subscribeOn.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/subscribeOn.js)
› http://localhost:3002/lib/rxjs/add/operator/switch.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/switch.js)
› http://localhost:3002/lib/rxjs/add/operator/switchMap.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/switchMap.js)
› http://localhost:3002/lib/rxjs/add/operator/switchMapTo.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/switchMapTo.js)
› http://localhost:3002/lib/rxjs/add/operator/take.js (/Users/brooksforsyth/dev/htmlclient/dist/lib/rxjs/add/operator/take.js)
› http://localhost:3002/lib/rxjs/add/operator/takeLast.js (/Users/brooksfor

**Comment by roblourens** [comment]
Right, looking at the first entry for example, this is all the information that the sourcemap has about the location of the source - "common/services/logout/logout.service.ts". I'm guessing your sources are inlined in the sourcemap so chrome devtools for example doesn't need the real path.

You can change your build to get the right paths out or you can override this with 'sourceMapPathOverrides' in your launch config. Maybe like

```
"sourceMapPathOverrides": {
  "common/*": "${workspaceRoot}/src/common/*"
}
```

Play with it to get the right paths.

**Comment by Bforsyth1234** [comment]
@roblourens  Thanks for the help.

If the i put 

            "sourceMapPathOverrides": {
                "dist/*": "src/*"
            }

Will this change the url from dist/ to src/ ?

**Comment by roblourens** [comment]
No, it operates on what's in the sourcemap, so in this case, it only operates on `"common/services/logout/logout.service.ts"`

**Comment by Bforsyth1234** [comment]
Ok so everything in the common folders source maps  would now be pointed to the ts files?

**Comment by roblourens** [comment]
In theory - just try it out.

**Comment by Bforsyth1234** [comment]
AWESOME!!!! Thank you. I got it working.
