### ISSUE TITLE
Unexpected error in debug adapter... Debugger.setBlackboxPatterns' wasn't found

### ISSUE THREAD

**Issue by aGrahamAtFuji** [Microsoft/vscode-chrome-debug#302]
******** Unhandled error in debug adapter - Unhandled promise rejection: {"code":-32601,"message":"'Debugger.setBlackboxPatterns' wasn't found"}

Since this is showing we have also lost the capability of debugging Marionette based application initialization calls.

**Comment by roblourens** [comment]
What version of Chrome are you using?

**Comment by roblourens** [comment]
Errors from this call are ignored, so if you're having trouble debugging, it must be something else.

Also I imagine that any runtime that doesn't have this method must be either a really old version of Chrome, or something that isn't Chrome.
