### ISSUE TITLE
Enhancement: Network debugging

### ISSUE THREAD

**Issue by G2Jose** [Microsoft/vscode-chrome-debug#305]
Currently, opening the built-in chrome DevTools causes the debug connection to vscode-chrome-debug to close. This is a known problem, as Chrome / Chromium only supports one debug connection at a time (https://bugs.chromium.org/p/chromium/issues/detail?id=129539). Not having visibility into network requests is a serious limitation when debugging web applications.

A workaround to this problem could be to support a `Network` debugging view right within Visual Studio Code, similar to 'Variables', 'Watch', 'Call Stack'. 

Related issues: 
- https://github.com/Microsoft/vscode-chrome-debug/issues/54
- https://github.com/Microsoft/vscode-chrome-debug/issues/95

**Comment by mzygmunt** [comment]
Alternatively, you can try https://github.com/hbenl/vscode-firefox-debug and firefox. It works good, but currently there is a small problem with the integration of webpack dev server. After some improvements vscode-firefox-debug may be a good alternative for vscode-chrome-debug.

**Comment by auchenberg** [comment]
Thanks for the suggestion @G2Jose. At this point we time we don't have any plans on expanding the functionality from script debugging to network inspection, as it opens a "can of worms" that could slowly transition VS Code from a simple editor to a full blooded IDE.

We think VS Code should work better with any DevTool, not aim to replace the in-browser DevTool.
