### ISSUE TITLE
Ignore URL params when debugging and following Click to follow links in Debug Console

### ISSUE THREAD

**Issue by pjsvis** [Microsoft/vscode-chrome-debug#307]
1. I use a version param to help with cache busting
2. EG http://localhost:55693/OTS.UTP/scripts/app/SomeFile.js?v=20161114132417363:107:48 
3. When I click in the Debug Console to follow the link it reports Unable to open 'SomeFile.js?v=20161114132417363': File not found (\\localhost:55693\OTS.UTP\scripts\app\SomeFile.js?v=20161114132417363).
4. I guess this is because of the param
5. It would be a nice enhancement if you could ignore the param
6 Otherwise chrome debugger is tons of fun

**Comment by roblourens** [comment]
It's also because of the URL. The console is looking for absolute paths, it won't download files.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode#17183
