### ISSUE TITLE
"showSavedCopyButton is not defined" bug

### ISSUE THREAD

**Issue by Skywalker-gamefu** [Microsoft/vscode-chrome-debug#308]
chrome debug tool not working with me 
configurations

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

i already did 
 --remote-debugging-port=8000

**Comment by roblourens** [comment]
Where do you see this error? This is probably an error on your page, because there's nothing in the extension with that name.

**Comment by Skywalker-gamefu** [comment]
ok it was an error in my script but still This site can’t be reached again my configurations


 {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
        
    ]
}

what is wrong ?
 i tried empty script with console.log()
main.js
still the same

**Comment by roblourens** [comment]
What is the probably exactly, when you say "the site can't be reached"

**Comment by Skywalker-gamefu** [comment]
look at this screen shots
![1](https://cloud.githubusercontent.com/assets/6768659/21206017/1c4a88da-c268-11e6-8d63-79934f98b1b8.jpg)
![1](https://cloud.githubusercontent.com/assets/6768659/21206018/1c7b12d4-c268-11e6-9344-ae071f2ccb24.png)
![2](https://cloud.githubusercontent.com/assets/6768659/21206019/1de1bc72-c268-11e6-913e-b4fa487f459b.jpg)

i dont understand what is happening !

**Comment by Skywalker-gamefu** [comment]
i tried many ports 
8000 , 9222 , 8080

**Comment by roblourens** [comment]
Ok, that port number needs to be the port of the webserver that your site is running on. vscode won't start a web server for you.

**Comment by Skywalker-gamefu** [comment]
oh i thought it will run node web server 
ok how i prevent opening new chrome tap every time i hit run , just refresh the current

**Comment by roblourens** [comment]
The circular green refresh button will refresh the page
