### ISSUE TITLE
Error when changing value in debug console

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/vscode-chrome-debug#310]
VsCode 1.8.0
Os Windows 10
Chrome  55.0.2883.87

While using the `webpack-dev-server@beta` having the following config

`webpack.config.js`
```javascript
const fs = require("fs");
const path = require("path");

module.exports = {
	entry: "./src/index",
	output:{
		path:path.resolve(__dirname, "dist"),
		filename:"bundle.js",
		publicPath:"/assets/"
	},
	devtool:"source-map"
};
```

`src/index.js`
```javascript
const element = document.createElement("h1");
element.innerText = "Hello World";
document.body.appendChild(element);
element.addEventListener("click", () => {
	const newElem = document.createElement("h2");
	newElem.textContent = "Again";
	document.body.appendChild(newElem);
});
```

If I add a breakpoint to line 7 and change the `newElem.textContent` value in the debug console I'll receive the following error : 
`Error processing "scopes": TypeError: Cannot read property 'scriptId' of undefined`

It's correctly appending a new element with the value I entered in the debug console and continues to work but the error is annoying.

**Comment by roblourens** [comment]
So you stop at a breakpoint, then eval something in the console, then get that error? That's strange. I can add a null check maybe.

Can you set `diagnosticLogging` and upload the log from the path printed at the top of the console? Thanks.

**Comment by scottlu** [comment]
I get this reliably but would rather send you my log directly than post it here.

**Comment by roblourens** [comment]
Sure, my email is in my profile

**Comment by roblourens** [comment]
Thanks for the log. It looks like you're breaking in an extension script or something, which isn't supposed to happen, so it's causing issues. I need a better fix for that stuff, but I'll add a null check or something to work around it.
