### ISSUE TITLE
Path's in stack traces aren't mapped to local file system, and causes VS Code to fail open files when clicked

### ISSUE THREAD

**Issue by ntilwalli** [Microsoft/vscode-chrome-debug#311]
VSCode: Version 1.8.0 (1.8.0)
Debugger for Chrome: v2.4.1

I'm unable to open the file linked in a stack trace:

```
TypeError: Cannot read property 'rrule' of undefined
    at Object.recurrenceToRRuleSet (http://localhost:4000/js/main.js:56970:23)
    at renderRecurring (http://localhost:4000/js/main.js:56744:28)
    at renderCuando (http://localhost:4000/js/main.js:56778:16)
    at Object.renderListingResult (http://localhost:4000/js/main.js:56791:21)
    at http://localhost:4000/js/main.js:58153:99
    at Array.map (native)
    at MapSubscriber.project (http://localhost:4000/js/main.js:58153:14)
    at MapSubscriber._next (http://localhost:4000/js/main.js:34358:35)
    at MapSubscriber.Subscriber.next (http://localhost:4000/js/main.js:25766:18)
    at RefCountSubscriber.Subscriber._next (http://localhost:4000/js/main.js:25802:26)
```

Clicking on any of the above links causes this error to show at the top of the window: `Unable to open 'main.js': File not found (/localhost:4000/js/main.js).`

This is my `launch.json`:
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch localhost with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4000",
            "webRoot": "${workspaceRoot}/priv/static",
        }
    ]
}
```
I confirmed that the file`${workspaceRoot}/priv/static/js/main.js` does exist.

Seems like the clicked links are not having their `localhost...` prefix substituted with `${webRoot}`
Am I doing something wrong?

**Comment by ntilwalli** [comment]
Output when using `diagnostiLogging` attached:

[vscode_debug_log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/659109/vscode_debug_log.txt)

**Comment by auchenberg** [comment]
What you are seeing is the original stack trace coming from Google Chrome. This seems to be VS Code trying to open http://localhost:4000/js/main.js as fil, which fails, as the file isn't local.

I'm wondering if we can re-map the sources in stack traces using source map info @roblourens?

**Comment by ntilwalli** [comment]
Got it.  I assumed linking between stacktraces and code was already a feature.  Would def be useful enhancement.

**Comment by auchenberg** [comment]
We support linking to local files from stack traces during debugging, as we are getting each "stack frame" as meta-data. 

I think this is a string message from Chrome's console API that needs to be re-mapped, so slightly different.

**Comment by roblourens** [comment]
Yeah we have https://github.com/Microsoft/vscode-chrome-debug-core/issues/6 for this - I agree that it would be useful!
