### ISSUE TITLE
Values not shown with hover over variable

### ISSUE THREAD

**Issue by Z3roCoder** [Microsoft/vscode-chrome-debug#314]
So, this debugger for Chrome would be really nice to use, but I am missing a very important feature.

Hovering over a variable does either only show "undefined", or nothng at all.
This problem mainly occurs on pureComputed-Functions (KnockoutJS) and ES5/6 async functions (public async myFunction() {...})

Visual Studio Code 1.8.0
Debugger for Chrome 2.4.1
We are using files compiled by typescript, along with .ts-sourcemaps

**Comment by roblourens** [comment]
Is there a project where this reproes that you can share?
