### ISSUE TITLE
Handle create-react-app config out of box

### ISSUE THREAD

**Issue by MykolaGolubyev** [Microsoft/vscode-chrome-debug#315]
Hello, I recently switched from using webpack directly to [create-react-app](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html) from Facebook.

My breakpoints are not getting recognized and tooltip suggests that it is possibly due to source maps. I tried changing launch.json file, but I didn't have much success.  I am able to debug through Chrome. 

Source files are within `src` dir. Chrome sees them as `webpack://src/App.js`

**Comment by auchenberg** [comment]
Hi @MykolaGolubyev 

Can you post your `launch.json` config? Seems like the webRoot property might not be pointing to `src`

**Comment by MykolaGolubyev** [comment]
```javascript
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/src"
        },
```

**Comment by auchenberg** [comment]
Validated. Seems to be caused by `create-react-app` building a source map that contains a virtual path named `.` where files might appear. Needs more debugging.

**Comment by MykolaGolubyev** [comment]
Thank you very much for looking at it.

**Comment by roblourens** [comment]
You can probably fix it by adding a mapping with the `sourceMapPathOverrides` option, and debug it by using the `.scripts` command in a terminal. I can try later.

**Comment by auchenberg** [comment]
Looks like the webpack:/ path aren't being stripped out correctly by default:

webpack:///src/App.js (/Users/auchenberg/Development/react-test/src/static/js/**webpack:**/src/App.js

```
    - webpack:///src/App.js (/Users/auchenberg/Development/react-test/src/static/js/webpack:/src/App.js)
    - webpack:///./src/logo.svg (/Users/auchenberg/Development/react-test/src/src/logo.svg)
    - webpack:///./src/App.css?1810 (/Users/auchenberg/Development/react-test/src/src/App.css)
    - webpack:///./src/App.css (/Users/auchenberg/Development/react-test/src/src/App.css)
    - webpack:///./~/css-loader/lib/css-base.js (/Users/auchenberg/Development/react-test/src/~/css-loader/lib/css-base.js)
    - webpack:///./~/style-loader/addStyles.js (/Users/auchenberg/Development/react-test/src/~/style-loader/addStyles.js)
    - webpack:///./src/index.css?25dd (/Users/auchenberg/Development/react-test/src/src/index.css)
    - webpack:///./src/index.css (/Users/auchenberg/Development/react-test/src/src/index.css)
```

**Comment by roblourens** [comment]
So these rules are provided by default, because it matches what I've seen in some popular setups, and I think angular CLI

```
'webpack:///./*': '${webRoot}/*',
'webpack:///*': '*'
```

But here, there's a relative path after `webpack:///`. It will try to apply the second rule, then fail because it doesn't result in an absolute path.

I think to fix this, I should allow something like this -

`'webpack:///*': ['*', '${webRoot}/*']`

where it will try to apply the first, fail, then try the second.

**Comment by roblourens** [comment]
And I would expect that adding ``'webpack:///*': '${webRoot}/*'` would fix it... I'll try it out later

**Comment by MykolaGolubyev** [comment]
Didn't help

**Comment by MykolaGolubyev** [comment]
Adding explicit sub-dirs helped
```
 "webpack:///src/sub-dir/*": "${webRoot}/sub-dir/*"
```
Is there a way to avoid enumerating all of them? I tried ** with no luck.

**Comment by roblourens** [comment]
In that case `"webpack:///src/*": "${webRoot}/*"` should work, my example was just missing `/src`.

**Comment by MykolaGolubyev** [comment]
It does work indeed. Not sure what I missed yesterday when I thought I tried exactly that :( 
Thanks! 
Do you think it should become part of the default mapping?

**Comment by auchenberg** [comment]
Before updating our default mapping we will have to look at the default use
for webpack and if the 'src' sub path will have unwanted consequences for
others.

That's said I'd like to get this working out of the box with as many
tools/generators as possible.

**Comment by MykolaGolubyev** [comment]
That sounds like a good plan. As a fallback plan a pull request for React CLI's readme.md file should help.

**Comment by zdne** [comment]
Thanks, everyone! Your suggestion works like a charm. Just for the completeness, the following setup works for me:

```json
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}/src",
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }
```

**Comment by foobar8675** [comment]
@zdne are you also able to debug? I just added your snippet to my Launch Chrome configuration and I always get 

> Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).

**Comment by roblourens** [comment]
Check out the section of the readme that has tips for that error message.

**Comment by foobar8675** [comment]
thanks @roblourens

**Comment by auchenberg** [comment]
https://github.com/react-boilerplate/react-boilerplate/issues/1575

**Comment by auchenberg** [comment]
🔥
