### ISSUE TITLE
true and false literals show as strings

### ISSUE THREAD

**Issue by Compulsed** [Microsoft/vscode-chrome-debug#319]
When you type or check for true/false in the debugger you get "true" & "false" rather than the literal true & false.

![image](https://cloud.githubusercontent.com/assets/1109278/21585517/263edeb0-d116-11e6-9af8-1b75e14ac753.png)

**Comment by roblourens** [comment]
I'm about to update it with the fix for this, #312

**Comment by roblourens** [comment]
It's in v2.4.2
