### ISSUE TITLE
Not working with webpack://, breakpoint never hits

### ISSUE THREAD

**Issue by kukjevov** [Microsoft/vscode-chrome-debug#320]
Hi,

i discovered that this plugin is not working correctly if you use it webpack. Interesting thing is that it is working directly in chrome, but when you connect remotely it just never hits breakpoints. It looks like there is some problem with webpack:// protocol or something like that.

https://github.com/kukjevov/ngls-standalone-html-problem

Here is a sample sample project where you can debug it. Please can you take a look at this? I can provide more info if needed.

To test it just run:
 - `npm install`
 - `npm start`
   - open chrome with http://localhost:8888 (working debug)
   - in vscode press F5 it will open chrome with http://localhost:8888 (not working debug)

Thank you very much for your help

**Comment by roblourens** [comment]
If you run the `.scripts` command you can see how it's resolving your webpack:/// sourcemaps. I try that and see that the scripts are being resolved under wwwroot because it tries that by default, but you can fix that with `overrideSourceMapPaths` like so:

```
"sourceMapPathOverrides": {
    "webpack:///./*": "${workspaceRoot}/*"
}
```

**Comment by kukjevov** [comment]
Thank you very much :).
