### ISSUE TITLE
Enhancement: Just my code / Black box scripts

### ISSUE THREAD

**Issue by agjs** [Microsoft/vscode-chrome-debug#321]
Hi there guys. I deeply apologize for reopening this thread since similar was opened in March but this feature is not implemented yet and after doing some research, I've realized that many people are still debugging in browser because we can't black box libraries when debugging which leads to way increased time when doing so. 

Any time estimate when or if this will ever be implemented because it's a must have feature in the context of debugging.

Thanks a bunch

**Comment by auchenberg** [comment]
We recently added blackboxing via the new `skipFiles` property in your config. See https://github.com/Microsoft/vscode-chrome-debug#skip-files--blackboxing--ignore-files

**Comment by robertmain** [comment]
Can someone tell me how I use this to ignore node internals? I tried putting `<node_internals>/events.js` in the `skipFiles` array, but that caused code to throw an error saying it couldn't find that file...
