### ISSUE TITLE
Support Standard JavaScript Files With No SourceMaps

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/vscode-chrome-debug#323]
I have an `index.html` file with basic `script` tags to JavaScript files which have not been minified and don't have source maps. When I try to set a breakpoint, it gets greyed out and it's tooltip says:

> Breakpoint ignored because generated code not found (source map problem?)

Is this basic scenario supported? If not can it be? My launch.json file looks like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceRoot}/index.html"
        },
        {
            "name": "Attach to Chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}/index.html"
        }
    ]
}
```

**Comment by roblourens** [comment]
Yes, that should be supported. The problem is probably with your `webRoot` property. It should be the folder that your webserver is running from, not a file.
