### ISSUE TITLE
Uglified names in debug

### ISSUE THREAD

**Issue by xinix00** [Microsoft/vscode-chrome-debug#326]
When using Uglify, and the Chrome debug plugin (using ASP.NET MVC Core + Chrome Debug), I see the obfuscated names, not the translated names by the mapping in the "VARIABLES" section: ( http://imgur.com/a/9JJnd ).

When not using Uglify it's working as expected. Though Chrome is able to look past this and does translate the names back to the original one using the built in Developer tool. Breakpoint is hit correctly.

Uglify has some major issues in hitting breakpoints by the way, and also the translation of breakpoints is a bit weird, it searches for the next line possible to add the breakpoint, which sometimes is the next function.

My gulp config:
.pipe(sourcemaps.init())
.pipe(uglify())
.pipe(sourcemaps.write(...))
.pipe(...destination)

**Comment by roblourens** [comment]
The variable name issue would be covered by #12066. Breakpoints going to the next line is probably due to https://github.com/Microsoft/vscode-chrome-debug-core/issues/144, which I just found recently. 

Skipping uglify makes it easier to debug but I hope to fix these to give a better experience.
