### ISSUE TITLE
localhost:9222/Index.html renders blank page while /json seems OK 

### ISSUE THREAD

**Issue by rachidbch** [Microsoft/vscode-chrome-debug#327]
Well i strongly suspect this is my bad but I'm really unable to make the simplest demo work.

setup:
-------- 
  - Ubuntu 14.04/64
  - Chrome 55
  - vscode 1.8.1
  - debugger for chrome extension v.2.4.2

launch.json
----------------
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/index.html",
            "webRoot": "${workspaceRoot}/",
            "port": 9222,
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        },
        {
            "name": "Attach to Chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```
Working dir
----------------
 * index.html
 * index.js
 * launch.json
 * .vscode

web server
---------------
No backend as I assume vscode (more precisely the debugger for chrome extension) will:
  - serve my static site on localhost:9222 
  - launch a chrome in debugg mode on localhost:9222
  - attach to the the launched chrome process using inspector API

Are these assumptions wrong?

Debug: Launch
---------------------
  - chrome opens on 'localhost:9222' 
  - displays a blank screen
  - trying to open devtools focuses back on vscode
  - manually changing url to 'localhost:9222/json' spits

      ```json
      [ {
          "description": "",
          "id": "502e3004-c70c-4f0c-9f4d-2c9bd830e81e",
          "title": "localhost:9222/index.html",
          "type": "page",
          "url": "http://localhost:9222/json"
       } ]
      ```
Question
-------------
What I'm missing guy's? I'm running short of options ...

**Comment by roblourens** [comment]
No, the extension doesn't start a webserver for you. You need to run your own.

**Comment by roblourens** [comment]
"port" is the port used to connect to Chrome for debugging.

**Comment by rachidbch** [comment]
Thanks for this amazingly fast answer @roblourens !
Maybe I'm not alone in not picking that in the doc: Should we add a line in the doc to make that point clear?

btw, how would you use (or is it even possible ?) launch.json to automate:
  1. the launching of a simple web server (something like 'live-server' or instant or whatever)
  2. launch chrome, attach, etc...

Keep up the (fantastically) good work!

**Comment by roblourens** [comment]
You're not the only one - it's in the description of the property but maybe it would be more clear if the name was "debugPort" or something.

You can use the option "preLaunchTask" to run a task (https://code.visualstudio.com/docs/editor/tasks) to serve your project.

Thanks! :)

**Comment by rachidbch** [comment]
Thanks to you @roblourens! You've been incredibely helpful :)
