### ISSUE TITLE
Feature request: Set breakpoint in vscode - extension should add/remove them in chrome dev-tools.

### ISSUE THREAD

**Issue by kmolerov** [Microsoft/vscode-chrome-debug#329]
Use-case: I want to debug in chrome dev-tools but it is hard to find code lines to put break-points. It will be much easier if I am able to add breakpoints from the editor in vscode, as I have required code file opened in editor.

**Comment by roblourens** [comment]
This is a scenario that I wish I could support, unfortunately there's no way for us to add bps to devtools currently.

**Comment by auchenberg** [comment]
Technically we are telling the debug server within Chrome to set a breakpoint at a specific line, when Chrome DevTools connect it should in theory be able to update it's UI to reflect the current breakpoints. However, at this point in time Chrome only supports one connection to the server, which means VS Code will get kicked out when Chrome DevTools is opened.

**Comment by kmolerov** [comment]
Thank you for the good explanation. Now we know why this feature can't be implemented.
