### ISSUE TITLE
Breakpoints get greyed out and don't get hit

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-chrome-debug#330]
While launching vs code from source, none of the breakpoints get hit.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/702907/vscode-chrome-debug.txt)
!

**Comment by auchenberg** [comment]
@ramya-rao-a Can we get you to provide your `launch.json` file, and tell us about your setup? Using WebPack or any other bundlers?

**Comment by roblourens** [comment]
Heh this was me filing a bug from Ramya's laptop, now tracked in https://github.com/Microsoft/vscode/issues/18475 :)

**Comment by auchenberg** [comment]
🙈😂
