### ISSUE TITLE
Bug in Launching Chrome Debugger

### ISSUE THREAD

**Issue by seantrott** [Microsoft/vscode-chrome-debug#331]
I've seen some previous issues similar to this problem, but unfortunately the replies didn't help. Sorry if this is merely repeating a previous question!

I'm using a very simple .html file as a test, which just has a line of text, and is stored in the folder currently opened by VS Code (presumably this is ${workspaceRoot}). I've tried both attaching and launching the debugger, to no avail. Here's the json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/webpage.html",
            "webRoot": "${workspaceRoot}"
        },
        {
            "name": "Attach to Chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}/webpage.html"
        }
    ]
}
```

**Launch**: When I launch against the localhost, I get an error on Chrome ("localhost refused to connect"), and then an error in VS Code:

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).`

**Attach**: When I attach to a Chrome instance (after executing the "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222" command in Terminal), I get the same error in VS Code:

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).`

Am I missing something really fundamental? Let me know if you need more information.

**Comment by roblourens** [comment]
Most likely you already have Chrome open - take a look at the suggestions here - https://github.com/Microsoft/vscode-chrome-debug#cannot-connect-to-the-target-connect-econnrefused-1270019222
