### ISSUE TITLE
varriable.js trimProperty has error

### ISSUE THREAD

**Issue by ocdogan** [Microsoft/vscode-chrome-debug#332]
When expanding the tree if the value is undefined, debugger is firing _"Error processing "variables": TypeError: Cannot read property 'length' of undefined"_ error. Add "value && " expression to condition, it will fix.

`function trimProperty(value) {
    return (value && value.length > PREVIEW_PROP_LENGTH) ?
        value.substr(0, PREVIEW_PROP_LENGTH) + ELLIPSIS :
        value;
}`

**Comment by roblourens** [comment]
Can you explain what you mean by "expanding the tree if the value is undefined"? I can't repro this.

**Comment by yukiarai** [comment]
It seems the method has some inappropriate coding. When I start a Cordova debug process, the following are shown in console.

Attaching to ios
Configuring debugging proxy
Attaching to app.
Error handling message from target: Response with id:14 has no pending request
(snip)
Error handling message from target: Response with id:41 has no pending request
Error processing "variables": TypeError: Cannot read property 'length' of undefined
    at trimProperty (/Users/xxxxx/.vscode/extensions/vsmobile.cordova-tools-1.2.6/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:137:18)
    at propertyPreviewToString (/Users/xxxxx/.vscode/extensions/vsmobile.cordova-tools-1.2.6/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:131:19)
    at props.map.prop (/Users/xxxxx/.vscode/extensions/vsmobile.cordova-tools-1.2.6/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:120:43)
    at Array.map (native)
    at Object.getObjectPreview (/Users/xxxxx/.vscode/extensions/vsmobile.cordova-tools-1.2.6/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:120:14)
    ....

**Comment by roblourens** [comment]
In your launch config, could you set `"diagnosticLogging": true`, then upload the log from the path it prints at the top of the console? Thanks

**Comment by yukiarai** [comment]
Sorry for late, but I guess I couldn't get what you needed. No log file created in my environment, though vscode says logpath would be "...platforms/ios/cordova/console.log". Adding '"diagnosticLogging": true' to launch.json makes no change. The only I can upload is that vscode prints to it's debug console.

[log.zip](https://github.com/Microsoft/vscode-chrome-debug/files/734102/log.zip)

**Comment by roblourens** [comment]
Oh ok, maybe Cordova isn't passing on that path correctly. cc @MSLaguana. Can you try setting `verboseDiagnosticLogging` instead, and copying that log out of the console? Might be a bit long but it will have all the details I need.

**Comment by brassh** [comment]
same error for me as reported by ocdogan; error can be avoided by modifying file variables.js line 167 as proposed by ocdogan

verbose error log:
(...)
[Error] Error processing "variables": TypeError: Cannot read property 'length' of undefined
    at trimProperty (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:167:18)
    at propertyPreviewToString (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:161:19)
    at props.map.prop (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:43)
    at Array.map (native)
    at getObjectPreview (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:14)
    at Object.getRemoteObjectPreview (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:194:17)
    at ChromeDebugAdapter.createObjectVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1470:33)
    at ChromeDebugAdapter.remoteObjectToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1413:33)
    at ChromeDebugAdapter.internalPropertyDescriptorToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1163:21)
    at ChromeDebugAdapter.propertyDescriptorToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1106:25)
To client: {"seq":0,"type":"response","request_seq":17,"command":"variables","success":false,"message":"[debugger-for-chrome] Error processing \"variables\": TypeError: Cannot read property 'length' of undefined\n    at trimProperty (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:167:18)\n    at propertyPreviewToString (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:161:19)\n    at props.map.prop (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:43)\n    at Array.map (native)\n    at getObjectPreview (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:14)\n    at Object.getRemoteObjectPreview (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:194:17)\n    at ChromeDebugAdapter.createObjectVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1470:33)\n    at ChromeDebugAdapter.remoteObjectToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1413:33)\n    at ChromeDebugAdapter.internalPropertyDescriptorToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1163:21)\n    at ChromeDebugAdapter.propertyDescriptorToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1106:25)","body":{"error":{"id":1104,"format":"[{_extensionName}] Error processing \"{_requestType}\": {_stack}","variables":{"_extensionName":"debugger-for-chrome","_requestType":"variables","_stack":"TypeError: Cannot read property 'length' of undefined\n    at trimProperty (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:167:18)\n    at propertyPreviewToString (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:161:19)\n    at props.map.prop (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:43)\n    at Array.map (native)\n    at getObjectPreview (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:151:14)\n    at Object.getRemoteObjectPreview (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/variables.js:194:17)\n    at ChromeDebugAdapter.createObjectVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1470:33)\n    at ChromeDebugAdapter.remoteObjectToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1413:33)\n    at ChromeDebugAdapter.internalPropertyDescriptorToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1163:21)\n    at ChromeDebugAdapter.propertyDescriptorToVariable (/home/brassh/.vscode/extensions/msjsdiag.debugger-for-chrome-2.7.0/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:1106:25)"},"sendTelemetry":true}}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"297","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":62,"executionContextId":1,"hash":"10F0A1B2B299A37081820E77218D64225C212585","executionContextAuxData":{"isDefault":true,"frameId":"29811.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
From target: {"id":25,"result":{"result":{"type":"boolean","value":false}}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"299","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":62,"executionContextId":1,"hash":"10F0A1B2B299A37081820E77218D64225C212585","executionContextAuxData":{"isDefault":true,"frameId":"29811.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
From target: {"id":26,"result":{"result":{"type":"string","value":"nicht abgefragt"}}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"301","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":62,"executionContextId":1,"hash":"10F0A1B2B299A37081820E77218D64225C212585","executionContextAuxData":{"isDefault":true,"frameId":"29811.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
From target: {"id":27,"result":{"result":{"type":"number","value":-1,"description":"-1"}}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"303","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":62,"executionContextId":1,"hash":"10F0A1B2B299A37081820E77218D64225C212585","executionContextAuxData":{"isDefault":true,"frameId":"29811.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
From target: {"id":28,"result":{"result":{"type":"string","value":"breit"}}}

**Comment by roblourens** [comment]
I think this was fixed with https://github.com/Microsoft/vscode-chrome-debug/issues/394 (maybe not in Cordova extension yet)
