### ISSUE TITLE
Launch VSCode never successfully attaches

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-chrome-debug#333]
Refs: https://github.com/Microsoft/vscode/issues/19110
os x

1. Get the latest chrome debug vsix 
2. Open vscode repo
3. Choose launch VSCode launch config -> it never succesfully ataches

If you take the latest chrome extension from the marketplace everything works fine for me.

**Comment by roblourens** [comment]
Ugh, good catch. Code from a PR gets stuck in an infinite loop.

**Comment by isidorn** [comment]
Probably related to https://github.com/Microsoft/vscode/issues/19209 please check that one once this is fixed
