### ISSUE TITLE
Setup could be improved

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-chrome-debug#337]
Refs: https://github.com/Microsoft/vscode/issues/19110

I am having a hard time setting up the chrome debugger, which means we should probably invest in imporving this.

1. clone my example repository https://github.com/bpasero/standup  
2. npm install
3. Change line 17 in app.js to `app.set('port', 8080);`
4. Generate a launch.json with the default chrome configuration, choose launch hrome against localhost
5. Error: `Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches: http://localhost:8080. Available pages: ["file:`

I am probably doing something stupid here but this should give us a hint that the configuration step should be simplified

**Comment by roblourens** [comment]
Does your launch config have `"port": 8080`? That's a common issue, that's the debug port for chrome, not your webserver's port.

**Comment by isidorn** [comment]
@roblourens no here my launch.json
How could we improve this port issue - since it is common, might we somewho make this more obvious? What is the minimalstic launch.json that I need in order to start?

```
 {
            "name": "Launch Chrome against localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8008",
            "pathMapping": {
                "/": "${workspaceRoot}"
            }
```

**Comment by roblourens** [comment]
Sorry I misread the error. 

You may be debugging vscode on the same port? The rest of 'available pages...' would give a clue. It works for me, using

```
"pathMapping": {
  "/": "${workspaceRoot}/client"
},
```

**Comment by isidorn** [comment]
Thanks for help - I will try it out.
My point still stays the same that it is not easy to setup :)

**Comment by roblourens** [comment]
Agreed

**Comment by auchenberg** [comment]
@roblourens Could we remove the `port` property for launch scenarios? We have another issue on setting it automatically.

**Comment by roblourens** [comment]
I feel like there's always going to be some case where someone wants to override it. We could rename it though.

**Comment by auchenberg** [comment]
Yeah, more thinking that we could make it an optional property to set, and remove it from the default config. That would reduce the confusion.

**Comment by roblourens** [comment]
It's not in the default config. Some people just throw it in for fun.

**Comment by auchenberg** [comment]
Got it. 
@isidorn Can you help me understand the problem? You started your local node server, and used the default launch config, and the experience was that the debugger didn't work?

**Comment by isidorn** [comment]
@auchenberg my problem was that I did not properly configure the `pathMapping`. Coming as a user who successfuly used node debug the issue is that I do not know which are the configuraitons that I must modify in order to make this work. I believe this is a common challange that all adapters are facing.
Could we somehow improve this that it is more obvious to the user that they must configure the pathMapping

**Comment by roblourens** [comment]
It's hard because from the debug adapter's perspective, all it knows is that the user set a breakpoint in a file that it doesn't know anything about, and there can be many reasons for that:

- Attaching to the wrong tab
- 1000 issues related to sourcemaps
- Incorrect pathMapping/webRoot
- Script is not loaded yet but will be later

In the current model, the user or app has to provide all the information to match up paths perfectly. I've thought about how the adapter could be smarter and make more inferences based on fuzzy matching or something. But I think it will always break down in some case, and in an even more confusing manner than this.

**Comment by auchenberg** [comment]
@isidorn Aha, got it. Yeah, source mapping and path configuration are really a pain to solve. I don't have a great way to prevent this issue.

@roblourens Could we do some clever automatic root path detection? The first top-level folder with most JS HTML, and CSS files within? However this estimation would need to happen when the config is being suggested.

**Comment by roblourens** [comment]
It would probably always pick the root, since the root will have more of those files than any of its subfolders. In this case especially, it wouldn't know the difference between the client, server, (and node_modules) folders, and the js files at the root.

**Comment by roblourens** [comment]
I'm not sure there's an action item here, and I'm trying to clean up issues, so closing.
