### ISSUE TITLE
Breakpoints not working with webpack sourcemaps of type eval-source-map

### ISSUE THREAD

**Issue by joseds** [Microsoft/vscode-chrome-debug#339]
Hi,
I noticed that breakpoints do not work as expected when debugging using Chrome and sourcemaps of type `eval-source-map` generated by webpack. The breakpoints are shown in VS Code as if they were working, but execution is not halted there.

With the same launch configuration and just changing to `source-map` sourcemap type, it works fine.

I have set up a little project reproducing this behaviour: [chrome-vscode-debug](https://github.com/joseds/chrome-vscode-debug). 

One observation one can make looking at the debug log is that there are mappings of the form `webpack:///./app/component.js?60be =>
 c:\Users\jose\Documents\GitHub\chrome-vscode-debug\app\component.js?60be`, where the latter file obviously does not exist. This could be the reason for the problem. For details please see the readme file in the project.

**Comment by roblourens** [comment]
Thanks for the sample project. I've had issues with different webpack settings in the past but I can't remember whether `eval-source-map` has ever worked.

**Comment by roblourens** [comment]
There are problems with some webpack settings, one issue tracking it is https://github.com/webpack/webpack/issues/2145
