### ISSUE TITLE
Unable to get attach to chrome working with React app (possibly related to #315?)

### ISSUE THREAD

**Issue by ewittle** [Microsoft/vscode-chrome-debug#340]
I have a React app built with Webpack that I'd like to debug with Visual Studio Code and Chrome. I've been tweaking the the launch.json file trying to get this to work based on various links I've found via Google, with limited success. My current state is that I can set breakpoints in Visual Studio Code if I don't start the debugging session, but as soon as I try to run the debugger, the breakpoints grey out and the tooltip says "Breakpoint ignored because generated code not found (source map problem?)"

I probably have non-standard source code organization, which may be contributing to the problem. Here's the organization of the project directory:

```
/server
/client
  /react
  /js
  /redux
/docroot
  /html
  /react
```

So the source code lives in the client directory, and the generated code is in the docroot/react directory. Here is the configuration entry from launch.json:

```
  {
            "name": "Attach to Chrome, with source maps",
            "type": "chrome",
            "request": "attach",
            "url": "http://eric.netapp.local/tmeinfo/ui/home",
            "port": 9222,
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///./~/": "/Users/ericw/tmeinfo/node_modules",
                "webpack:///../": "/Users/ericw/tmeinfo/node_modules",
                "webpack:///./": "/Users/ericw/tmeinfo",
                "webpack:///*": "/*"
            }
    }
```
As you can see, I've put in the full path in the sourceMapPathOverrides because I'm still unclear the context (for example what ${workspaceRoot} refers to). I know which directory I opened in VSC, that is "/Users/ericw/tmeinfo/client" in this case.

Here's a couple of entries from the source map with comments I'm making:

```
# Example library files
"webpack:///./~/babel-polyfill/~/core-js/shim.js",
"webpack:///./~/react/lib/React.js",
# Example of how my source is referenced
"webpack:///./client/react/HitsList.jsx"

```

I have no idea if I'm applying the parameters in the launch.json file directly, any help you can provide would be greatly appreciated.

**Comment by roblourens** [comment]
Easiest way to debug this, since it's hard without knowing your webpack config, is to use the `.scripts` command in the debug console. There are some notes in the README about how to interpret its output, but it should help you figure out why it's not resolving your sources to the correct location.

`${workspaceRoot}` is the folder you have open in vscode.

**Comment by ewittle** [comment]
Thanks for the comment. I'm not sure you want all of my webpack config, but here's what I hope are the useful bits (leaving out the non-JS loaders):

```
var BUILD_DIR = path.resolve(__dirname, 'docroot/react');
var APP_DIR = path.resolve(__dirname, 'client');

var config = {
  entry: ['babel-polyfill', APP_DIR + '/react/index.jsx'],
  output: {
    path: BUILD_DIR,
		filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
			  test: /\.jsx?/,
			  include: [APP_DIR + '/react', APP_DIR + '/js'],
			  loader: 'babel'
	    },
		  {
			  test: /\.js$/,
			  include: APP_DIR + '/redux',
			  loader: 'babel-loader',
			  query: {
				presets: ["es2015"]
			}
		  }
};
```

I ran the .scripts command in the debugger console, the complete output is probably too long to include here, but here is the top:

```
eval://77
› eval://78
› http://eric.netapp.local/tmeinfo/ui/react/bundle.js
    - webpack:///webpack/bootstrap fafcaeb023c09d05602c (/webpack/bootstrap fafcaeb023c09d05602c)
    - webpack:///./~/babel-polyfill/lib/index.js (/~/babel-polyfill/lib/index.js)
    - webpack:///./~/babel-polyfill/~/core-js/shim.js (/~/babel-polyfill/~/core-js/shim.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/es6.symbol.js (/~/babel-polyfill/~/core-js/modules/es6.symbol.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_global.js (/~/babel-polyfill/~/core-js/modules/_global.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_has.js (/~/babel-polyfill/~/core-js/modules/_has.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_descriptors.js (/~/babel-polyfill/~/core-js/modules/_descriptors.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_fails.js (/~/babel-polyfill/~/core-js/modules/_fails.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_export.js (/~/babel-polyfill/~/core-js/modules/_export.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_core.js (/~/babel-polyfill/~/core-js/modules/_core.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_hide.js (/~/babel-polyfill/~/core-js/modules/_hide.js)
    - webpack:///./~/babel-polyfill/~/core-js/modules/_object-dp.js (/~/babel-polyfill/~/core-js/modules/_object-dp.js)
```

and here are some of the lines that refer to my actual source code (as opposed to 3rd party libraries I'm including):

```
    - webpack:///./client/react/InlineLogin.jsx (/client/react/InlineLogin.jsx)
    - webpack:///./client/react/TechDocInterest.jsx (/client/react/TechDocInterest.jsx)
    - webpack:///./client/react/KeywordSelect.jsx (/client/react/KeywordSelect.jsx)

```

The general advice for how to construct sourceMapPathOverrides entries seems to suggest that one or two prefixes with wildcards should work, but given the variety of prefixes I see across all of the sources in the list produced by the .scripts command, that seems unlikely to work in my case. I'll keep experimenting for now to see if I can figure it out.

**Comment by ewittle** [comment]
OK, not paying enough attention to the examples I was looking at and what I typed. It's always the obvious thing. The launch entry that works:

```
        {
            "name": "Attach to Chrome, with source maps",
            "type": "chrome",
            "request": "attach",
            "url": "http://eric.netapp.local/tmeinfo/ui/home",
            "port": 9222,
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "webpack:///./~/*": "${workspaceRoot}/../node_modules/*",
                "webpack:///../*": "${workspaceRoot}/../node_modules/*",
                "webpack:///./*": "${workspaceRoot}/../*",
                "webpack:///*": "/*"
            }
        }
```
Note that the changes I made were really basic, was missing the asterisk in a number of cases, and put in the ${workspaceRoot} this time. Seems to be working just fine now, am able to set a breakpoint and step through code while running. Sorry for the spam.

**Comment by roblourens** [comment]
No worries. I think that what you had for overrides originally should be equivalent to having `*` at the end. I think it makes sense to read it that way. I'll open another issue for it.
