### ISSUE TITLE
Keep debug adapter process running when devtools launch

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#345]
People have long complained about Chrome dying when opening the chrome devtools, which happens because that kills the debug connection, so the debug adapter process stops, and Chrome dies because it belongs to that process. Also it's useful so you don't end up with extra Chrome processes hanging around.

One way around this which I hadn't thought of is just to keep the vscode debug session running when Chrome disconnects due to the devtools opening. We know why we were disconnected, so we can treat that case differently. And it would unblock people who want to switch from vscode to the devtools.

People will probably be confused that they aren't hitting BPs in vscode anymore. Can print a console message or something - not sure what else.

**Comment by auchenberg** [comment]
I like this idea. I thought we simply could start Chrome as a new independent process of the debug adapter, so if the adapter exits or crashes, then the Chrome process will still run? 

We should sure output a special message in the console with the reason. Does the VS Code console support colors these days?

As a user I expect my editor to be able to launch the browser, but not have a strict relationship between them.

**Comment by roblourens** [comment]
Yeah, I was never able to make that work successfully, and couldn't figure out why.

You only get white, red, and yellow. I use yellow for messages from the adapter right now.

**Comment by auchenberg** [comment]
Alrighty, we should just output it as a yellow warning then.

**Comment by auchenberg** [comment]
@roblourens Didn't you land this?

**Comment by roblourens** [comment]
Yes!
