### ISSUE TITLE
Make configurable attach timeout

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode-chrome-debug#346]
- VSCode Version: 1.8.1
- OS Version: Windows 8.1 x64

Would like to have an option to change attach timeout because there are times when the app being debugged need more time to initialize before getting ready to accept attach request than hardcoded 10 seconds. Especially when using hybrid debugging and when prelaunch task take up time.

**Comment by roblourens** [comment]
Sure, that's easy enough. It might actually work already if you set it in your launch config. For an 'attach' config, not a 'launch' config. I'll add it officially though.

**Comment by Deilan** [comment]
I've tried setting it for `attach` config and it's still ignored by VS Code as of VS Code v1.9.0 and Debugger for Chrome v2.5.1.

![untitled](https://cloud.githubusercontent.com/assets/4777512/22585081/0991c886-ea07-11e6-8caa-1c06db82f843.png)

**Comment by peternann** [comment]
Just for completeness: This seems to have been fixed+closed.

"timeout" property on Launch task works for me.

Google led me here - And it wasn't sure, so I thought I'd mention it.

**Comment by taylorstutts** [comment]
Doesn't work for background tasks
