### ISSUE TITLE
Debugging Chrome with Static on another server from index.html

### ISSUE THREAD

**Issue by steckdev** [Microsoft/vscode-chrome-debug#349]
I am attempting to debug my Javascript code that is served up for our static IIS server. However our index.html is located on another server. Which means that our javascript code is being executed from another location than index relative path. Is there a set of instructions for getting this setup. Because I'm sure i'm not the only person who has a split architecture. Hopefully someone knows how to change the relative path to the maps to another server. I am able to access global variables, however I am unable to get the sourcemaps to step into my code. It randomly connected once for a moment but I haven't been able to get it to work again.

![serverfilelayout](https://cloud.githubusercontent.com/assets/1010935/22574626/3c3b19ee-e96d-11e6-86ac-179784f07040.png)

- VS Code Version: 1.9.0
- vscode-chrome-debug 2.5.1

Steps to reproduce:

1. Navigate to website (mine was http://engage.allegiance.local/#r/ed2005d9-ae3d-45b8-a3ce-823e942767f0/0)
2. Attempt to launch/attach on a website with Index.html on another IIS server than the static javascript content

Relevant workspace information

-workspace-

Static
   A.Reporting.js
   B. Reporting
      I. Scripts
        a. Controllers
           i. *.Controller.js
         b. Models
            ii. *.Models.js

launch.json
	{
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "url": "http://engage.allegiance.local/*",
            "webRoot": "${workspaceRoot}",
            "sourceMaps":true
        }

**Comment by roblourens** [comment]
I don't totally understand your scenario but there's no reason it's not workable. What's the output of the `.scripts` command?
