### ISSUE TITLE
Config help needed

### ISSUE THREAD

**Issue by dimwell-git** [Microsoft/vscode-chrome-debug#350]
Hi, 
It is possible that I miss understand the functionality.
Please, correct me if I wrong, but I believe that my need is pretty straight forward and should work...
Unfortunately, it does not work.

1) Let say I have an HTML file in root directory that is called: index.html
2) It has very simple content: 

DOCTYPE
html
  head
  body
     ... some content 
    
  script
        'use strict';

        let a = 5;
        let b = 6;         // -> here I want to put breakpoint
        console.log(a);
  /script

3) I have OS X El Capitan version: 10.11.6 and VS Code: 1.9

4) I trie the following config ?    
 {
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "url": "http://localhost:9222",
            "webRoot": "${workspaceRoot}",
            "pathMapping": {
                 "/": "${workspaceRoot}/index.html" 
            }
 }

5) I run chrome using command in terminal: 
"sudo /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --no-first-run --no-default-browser-check"

6) Finally, on my tab index.html I press: start Debugging button and screen changes to orange.

7) I try to put breakpoint next to the variable "b" (see step 2), but nothing happens ! 

What do I do wrong ?

If to summarise, I simply want to be able to run HTML file in VS Code, debug content of <script> ... </script> and see result in Chrome. How can I achieve this ?

**Comment by roblourens** [comment]
You need to provide your own webserver running on a different port from chrome. Then use that url (like `http://localhost:8080` or something) in your launch config

**Comment by dimwell-git** [comment]
Hi roblourens,

Thank you for your help.
Changed settings to the following:
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach Chrome",
            "port": 9222,
            "url": "http://localhost:8080",
            "webRoot": "${workspaceRoot}",
            "pathMapping": {
            "/index.html": "${workspaceRoot}/index.html"
            }
}

Now it works, but it works partially... I can debug files with extension .js

This means that I have to attach .js files using src like:  <script src="...... .js"></script>
In most cases this is a standard way of working...

However, for example with Custom Elements its often convenient to work straight in .html file and write everything in a single file.

I tried to add breakpoint inside <script> tag in html file and this way it did not work...
Is it currently not possible way of debugging ? or do I do something wrong ?

**Comment by dimwell-git** [comment]
Played around with debugger and during debugging it opened a new tab that contains inner content of <script> tag... So everything works. Thanks for help.
