### ISSUE TITLE
Why do I get "Paused in Visual Studio Code" upon every launch in the browser?

### ISSUE THREAD

**Issue by AlGantori** [Microsoft/vscode-chrome-debug#351]
- VS Code Version:
1.2.6
- Debugger for Chrome
2.5.2

Steps to reproduce:
new Ionic 2 project
ionic start --v2 myApp tabs

ionic serve
in VSCode press F5, 

I get the snapshot below (tooltip like popup saying "Paused in Visual Studio Code", polyfills.js, containing garbage if you ask me :), is automatically loaded in VSCode.
Here is snapshot of browser...
![index 7](https://cloud.githubusercontent.com/assets/11699920/22616979/4ebba4d8-ea6e-11e6-8015-a92b9d7ad81b.jpg)

launch config in launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8100",
            "webRoot": "${workspaceRoot}"
        },
```

**Comment by roblourens** [comment]
Because the debugger is pausing :)

If you didn't set a breakpoint, then you're probably breaking on a thrown exception. Uncheck the "exceptions" checkboxes at the bottom of the debug viewlet.

**Comment by AlGantori** [comment]
Hard to spot the "debug viewlet" BREAKPOINTS when it is collapsed ;-), thanks.  So different than Visual Studio kinda like getting used to an Adobe workspace :).
Unchecked "Uncaught Exceptions"
This means that somehow, this polyfills.js has some "Uncaught Exceptions" right?
Is it possible to catch these exceptions only my code? and not the ionic framework.
Thank you.

**Comment by roblourens** [comment]
Check out 'smartStep' which will auto-step through un-sourcemapped code, or 'skipFiles' which lets you pick files to not break in.

**Comment by AlGantori** [comment]
It's interesting that when I experimented adding this to the config in launch.json, now F12 closes chrome instead of showing the developer tools / console?  Is this expected or a bug?

```
            "skipFiles": [
                "${webRoot}/www/build/polyfills.js"
            ],
```
Also not sure if above path is resolving correctly, because when I re-enable "Uncaught Exceptions" polyfills.js opened in vscode and I get a breakpoint.
