### ISSUE TITLE
Debugger fails on native async/await 

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode-chrome-debug#352]
I have async function which throws an error and reject promise.
When I compile my app using ES6 - all is fine - debugger stops at exception.
When I change to ES2017 (with native async/await) - I see in debug console of VS code (and debugger is not stopping on anything):

```
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
    at _allSourcePathDetails._sources.map.sort (C:\Users\root\.vscode\extensions\msjsdiag.debugger-for-chrome-2.5.2\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:84:36)
    at Array.sort (native)
...
```

- VS Code Version:
1.9.0
Chrome ext: 2.5.2

**Comment by CoryTriplett1971** [comment]
Why /.?

**Comment by pankleks** [comment]
not sure I understand ...

**Comment by roblourens** [comment]
This is probably the same as #353. I'll investigate there.
