### ISSUE TITLE
2.5.2 regression

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/vscode-chrome-debug#353]
Hi,

I just updated to 2.5.2 with latest VSC and breakpoints do not work anymore.

Console errors are produced:

```
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
    at _allSourcePathDetails._sources.map.sort (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:84:36)
    at Array.sort (native)
    at SourceMap.get allSourcePathDetails [as allSourcePathDetails] (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:83:16)
    at SourceMaps.allSourcePathDetails (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMaps.js:47:64)
    at _preLoad.then (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:255:37)
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Cannot read property 'line' of null
    at _allSourcePathDetails._sources.map.sort (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:84:36)
    at Array.sort (native)
    at SourceMap.get allSourcePathDetails [as allSourcePathDetails] (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:83:16)
    at SourceMaps.allSourcePathDetails (/home/robi/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMaps.js:47:64)
```

Watch variables tab untruly reports not being connected to server.

The SPA application uses an url with a GET parameter, like the following, and it is in 
"Attach with sourcemap" mode.

`"url": "http://127.0.0.1:8080/TheApp.html?localToken=1486381018502"`

_**The same project configuration works and debugs perfectly 
if opened with an instance of VSC Nightly and debug 2.4.2.**_

```
"configurations": [

        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "address": "127.0.0.1",
            "port": 9222,
            "url": "http://127.0.0.1:8080/TheApp.html?localToken=1486381018502",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        },
....

```

The application tsconfig.json (below) uses the "outfile" option to create a single js output file:

```
  "compilerOptions": {
        "module": "system",
        "target": "es5",
        "noImplicitAny": false,
        "noImplicitReturns": true,
        "outDir": "built",
        "rootDir": ".",
        "sourceMap": true,
        "outFile": "built/ts/TheAppSingleJSFile.js",
        "removeComments": true,
        "allowUnreachableCode": false,
        "watch": false,
        "allowJs": false,
        "lib": [
                "dom",
                "es2015.promise",
                "es5"
            ]
            // "strictNullChecks": false
    },
    "files": [
```

Thank for your time and this invaluable tool.

--R

**Comment by roblourens** [comment]
Can you try running with `"diagnosticLogging": true`, then uploading the log from the path that it prints at the top of the debug console?

Or, is this a project on github that I can try out? Thanks.

**Comment by RobertoMalatesta** [comment]
Hi @roblourens ,
the project is a private one, not on github.
I've run the diagnosticLogging and I would like to share it with you privately, since the log shows sensible information as well.
Sending it to your profile address.

--R

**Comment by roblourens** [comment]
Thanks for the log. I'm still not sure what's going on - probably there is one file where I can't find a mapping for line 0 column 0 of the source file, although I don't think that should happen. But the code that's breaking isn't really important, so I'm working around it. It will be fixed in the next version of Insiders.

I did add a log statement, "Could not map start position for ..." so I would be curious whether it prints that for just one script, or all of them, and if there's something different about those scripts, like if they start with comments at the top. And I'm curious which version of Typescript you are using.

**Comment by RobertoMalatesta** [comment]
I will try it as soon as I get the extension plugin update notification in Visual Studio Code.
As of now I  still see the 2.5.2 version. does it contain the fix without version change bump ?

> probably there is one file where I can't find a mapping for line 0 column 0 of the source file

zero sized files are generally produced by a *ts file containing interfaces only, but I suspect it's
something triggered by the "outfile" single file output option.

Versions: the problem is present on TS 2.1 stable and 2.2 RC as well.

--R

**Comment by roblourens** [comment]
That could be it, an interface file plus "outFile". If it's listed as a source but doesn't have any mappings.

Sorry I don't mean "fixed in the next version of insiders" (was thinking of our node debugger), I mean it will be fixed in the next chrome update which I'll get out shortly.

**Comment by roblourens** [comment]
The fix it in 2.5.3, let me know how it goes

**Comment by RobertoMalatesta** [comment]
Now it works as a charm again. :beers: 


-R

**Comment by pankleks** [comment]
Works for me too, thanks!
