### ISSUE TITLE
Consider to create a launch config snippet for debugging the Electron renderer

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-chrome-debug#354]
see https://github.com/octref/vscode-electron-debug/blob/master/electron-quick-start/.vscode/launch.json#L17

I've created one for Electron main process:
https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L221

**Comment by auchenberg** [comment]
Handled by the Electron recipe for now, https://github.com/Microsoft/vscode-recipes/tree/master/Electron
