### ISSUE TITLE
Reload HTML on save

### ISSUE THREAD

**Issue by tschuegge** [Microsoft/vscode-chrome-debug#355]
Reload attached Chrome while a debugging session. Now you write something in VSCode, then you have to switch to chrome, reload an switch back to VSCode. Automatic reloading would be a nice feature.

**Comment by roblourens** [comment]
The 'restart' button will reload the page, you can use a keybinding for `workbench.action.debug.restart` if you want. Otherwise I recommend using a third-party tool like browsersync that will do this for you.
