### ISSUE TITLE
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by justaddcl** [Microsoft/vscode-chrome-debug#356]
I'm trying to debug my project which is simply made up of an ```index.html``` and an ```app.js``` in the root folder, but whenever I try to launch chrome (using the launch request) to debug, it will load Chrome but won't show the index page, but rather one that lists Inspectable pages
![screen shot 2017-02-10 at 0 25 40](https://cloud.githubusercontent.com/assets/20213406/22819547/7ef3ac78-ef27-11e6-944c-cac1ef3cdb99.png)

Here are my launch settings:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:9222",
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "diagnosticLogging": true
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "url": "http://localhost:9222",
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true
        }
    ]
}
```

I've tried following suggestions from [other threads with similar issues](111) as well as the troubleshooting tips in the [readme](https://github.com/Microsoft/vscode-chrome-debug), but nothing's working for me.

I can navigate to ``` http://localhost:9222/json ``` and I have verified that the ```port``` in the launch config matches the port in the url. This is the json I see:
![screen shot 2017-02-10 at 0 00 14](https://cloud.githubusercontent.com/assets/20213406/22819493/2df36700-ef27-11e6-9a93-9e5ac38ca5e3.png)

Also, I'll get an HTTP ERROR 404 when trying to manually navigate to ```http://localhost:9222/index.html``` or ```http://localhost:9222/app.js```
 
![screen shot 2017-02-10 at 0 03 21](https://cloud.githubusercontent.com/assets/20213406/22819638/df750df8-ef27-11e6-8363-76150fab0fb7.png)

Here is the output I get in my debug console:
```
Verbose logs are written to /Users/JustAddCl/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.3/vscode-chrome-debug.txt
12:02:36 AM, 2/10/2017
OS: darwin x64
Adapter node: v6.5.0 x64
vscode-chrome-debug-core: 3.12.6
debugger-for-chrome: 2.5.3
spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--user-data-dir=/Users/JustAddCl/Repositories/meanstack-flappernews/.vscode/chrome","http://localhost:9222"])
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
Paths.scriptParsed: could not resolve http://localhost:9222/ to a file under webRoot: /Users/JustAddCl/Repositories/meanstack-flappernews. It may be external or served directly from the server's memory (and that's OK).
Target userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Paths.scriptParsed: could not resolve http://localhost:9222/ to a file under webRoot: /Users/JustAddCl/Repositories/meanstack-flappernews. It may be external or served directly from the server's memory (and that's OK).
```

I have also attached the verbose log below

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/766013/vscode-chrome-debug.txt)

I am currently running:
- VS Code Version: 1.9.1
- Chrome Versio: 56.0.2924.87 (64-bit) (up to date)

What am I missing?

**Comment by roblourens** [comment]
This extension won't set up a server for you, you need to set up your own and point it to its url.

**Comment by justaddcl** [comment]
Gotcha, thank you for the answer @roblourens!

**Comment by pre1ude** [comment]
Thanks, I supposed to think that it will server the file automatically, em..I were wrong.
