### ISSUE TITLE
Breakpoints greyed out? React + Webpack

### ISSUE THREAD

**Issue by therealAJ** [Microsoft/vscode-chrome-debug#357]
Hey!
Building a React app with Webpack that I'd like to debug with Visual Studio Code and Chrome. I can set breakpoints in Visual Studio Code if I don't start the debugging session, but as soon as I try to run the debugger, the breakpoints grey out and the tooltip says "Breakpoint ignored because generated code not found (source map problem?)"

Project structure in chrome: 
![image](https://cloud.githubusercontent.com/assets/12767206/22867248/7ba5bf3e-f139-11e6-8ca9-45aa63a7e25a.png)

Project structure in VScode
![image](https://cloud.githubusercontent.com/assets/12767206/22867252/8f5daea6-f139-11e6-9281-417343d1fb52.png)

`.scripts` gives me things like : `› eval://4549
    - webpack:///SearchBar.jsx?b143 (c:\Users\Alex\Documents\GitHub\smart-mirror\build\SearchBar.jsx)
› eval://4550
    - webpack:///VideoList.jsx?13b1 (c:\Users\Alex\Documents\GitHub\smart-mirror\build\VideoList.jsx)`

(which I'm assuming is ok???)

`launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "diagnosticLogging": true
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:///*": "${workspaceRoot}/build/*"
            }
        }
    ]
}
```
`webpack config`

```json
var path = require('path');
var webpack = require('webpack');
var BowerWebpackPlugin = require('bower-webpack-plugin');

module.exports = {
  devtool: '#eval-source-map',
  debug: true,
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    './src/index.jsx'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/build/'
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ['babel'],
        include: path.join(__dirname, 'src')
      },
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      },
      {
        test: /\.css$/,
        loader: "style!css"
      },
      {
        test: /\.js$/,
        loaders: ['babel']
      }
    ]
  },
  plugins : [
    new BowerWebpackPlugin(),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    })
  ]
}
```

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/769749/vscode-chrome-debug.txt)

Really not sure what's happening, I feel like my `sourceMapPathsOverrides` isn't too far off, but I'm not sure if its my webpack config thats causing the problems. Any help would be greatly appreciated :)

**Comment by pvpshoot** [comment]
I just use create-react-app and breakpoints don't work,
But if i put `debugger;` code will stops at bunde.js

**Comment by roblourens** [comment]
`c:\Users\Alex\Documents\GitHub\smart-mirror\build\SearchBar.jsx` is this the correct path to the file?

**Comment by therealAJ** [comment]
Solved! Thank you, new launch.json is 

``` json 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:///*": "${workspaceRoot}/src/*"
            },
            "diagnosticLogging": true
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:///*": "${workspaceRoot}/src/*"
            }
        }
    ]
} 
```

**Comment by auchenberg** [comment]
Hi Alex,

Instead of doing source map overrides it looks your webRoot is configured
to ${workspaceRoot} and not ${workspaceRoot}/src where your source files
are located.

You can try changing your webRoot and see if it works too. Our debugger
needs to know where your source files are if they are in a specific sub
folder within your open workspace.

/k

**Comment by pvpshoot** [comment]
something is wrong
`x: not available` http://take.ms/25OS3
http://take.ms/fPonE

**Comment by auchenberg** [comment]
@pvpshoot Interesting. Can you poste a GIST of how the compiled code look like? Are you using Babel?

**Comment by pvpshoot** [comment]
@auchenberg i use https://github.com/facebookincubator/create-react-app ,
just hello world,
this is webpack && babel configs:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js
https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js 

As i know, there is no bundle file saved to disc when env is development,  but i create a gist with in browser file https://gist.github.com/pvpshoot/74f1c03ad2008411765f8570e8ec887b

**Comment by pvpshoot** [comment]
@auchenberg please sorry, i change webpack config devtool to eval, and it is the reason, when i return 'cheap-module-source-map' it works fine.

**Comment by auchenberg** [comment]
@pvpshoot Cool, glad you got it working!

**Comment by liuliangsir** [comment]
I run into the issue just now, after referring to various links I've found via Google, with limited success.
So i will list steps for solving the upper issue, as it follows:
- key code snippet(webpack dev config)
```
config.output.devtoolModuleFilenameTemplate = function (info) {
    return "file:///" + encodeURI(info.absoluteResourcePath);
};
config.output.devtoolFallbackModuleFilenameTemplate = function (info) {
    return "file:///" + encodeURI(info.absoluteResourcePath) + '?' + info.hash;
};
config.devtool = 'cheap-module-source-map';
```
- modify your settings.json. (File -> Preferences -> Settings)
```
{  
    "debug.allowBreakpointsEverywhere": true
}
```
