### ISSUE TITLE
Disable network cache when debugging

### ISSUE THREAD

**Issue by llgcode** [Microsoft/vscode-chrome-debug#358]
Hi,
It would be great if we could disable network cache from visual studio code when debugging. May be by adding an option in the launcher: `"disableNetworkCache": true`.

https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-setCacheDisabled

**Comment by auchenberg** [comment]
What's the use-case @llgcode? This is more a developer wide setting, that can be toggled from Chrome DevTools.

**Comment by llgcode** [comment]
The use case is a debug session. I want to be sure that code loaded in the browser is the latest written in vscode so all is synchronized. In other words I need to be sure that the code I see on vscode is the same that is executed in the browser. Can you provide such a feature in launch configuration?
I don't think it's a global setting, not sure but I was thinking that this function could be activated for a debug session.

**Comment by yann-stepienik-cko** [comment]
+1 for this request
It can be done via Chrome dev tool, but isn't the point of this plugin to not having to use it ?

**Comment by johnfn** [comment]
The best way I've found to permanently disable the cache when using this extension is to add this to the launch.json configuration for this extension:

```
    "runtimeArgs": [
      "--disk-cache-size=1"
    ]
`

**Comment by llgcode** [comment]
Great I can not wait to try it :) thanks @roblourens

**Comment by llgcode** [comment]
works for me
