### ISSUE TITLE
Attach to multiple page configurations

### ISSUE THREAD

**Issue by jschmidt42** [Microsoft/vscode-chrome-debug#360]
When debugging remote chromium processes (i.e. in the context of CEF), it is possible that the application has many pages available at the same time. When using `vscode-chrome-debug` extension to debug these processes, the extension always attach to the first context it finds. It would be great if the extension would either ask the user which context to debug or have a debug field that we can set to select that context (in `launch.json`).

Currently, using CEF we can connect to `localhost:9088/` and we get prompted with:

![image](https://cloud.githubusercontent.com/assets/4054655/22987826/21e853d4-f37e-11e6-9dc0-49bebdc41f7a.png)

Which let's us select with page/context to debug.

Also Webstorm is doing something equivalent when you start the debug session:

![image](https://cloud.githubusercontent.com/assets/4054655/22987897/466bda32-f37e-11e6-90d9-9f1047f682f6.png)

I am using the following launch config at the moment:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Stingray Editor",
            "type": "chrome",
            "request": "attach",
            "port": 9088,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

Maybe there's already a way to do this, but I didn't found out how yet, otherwise it would be awesome if something equivalent could be done with the debugging extension.

Thanks,

- VS Code Version:
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-09T00:26:45.394Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by roblourens** [comment]
You should be able to set a 'url' in your launch config, and it will attach to the page with a matching url. You can use a wildcard in the url too.

**Comment by jschmidt42** [comment]
@roblourens do you have an example? Should it be a devtools url, something like: `http://localhost:9088/devtools/inspector.html?ws=localhost:9088/devtools/page/ff325d6b-6020-4e4c-98cb-434b3fc1f644` or the URL of the page itself, i.e. `http://localhost:9088/devtools/inspector.html?ws=localhost:9088/devtools/page/ff325d6b-6020-4e4c-98cb-434b3fc1f644` ?

**Comment by jschmidt42** [comment]
CEF does not serve the pages, it streams them from disk.

**Comment by roblourens** [comment]
Probably the `file:///` url. If you look at `localhost:9088/json/`, it should return a list of the targets with a 'url' field, which is what it will look at.

**Comment by roblourens** [comment]
Having a quick open to select the target has been requested before too, in https://github.com/Microsoft/vscode-chrome-debug/issues/280. Should do that at some point.

**Comment by jschmidt42** [comment]
Thanks @roblourens, looking forward for #280 to be implemented.

**Comment by roblourens** [comment]
Closing in favor of #280
