### ISSUE TITLE
Can't get variable to show its contents

### ISSUE THREAD

**Issue by FrogTheFrog** [Microsoft/vscode-chrome-debug#362]
Hello,

I have an angular2 project compiled using webpack2. I am able to use breakpoints, however local values contain no valuable information at all. I've been at it for a day now and can't seem to track down the source of this problem. Normally, I host everything on PHP server, but have exported important stuff to webpack dev server so that you won't need to install PHP while keeping the folder structure.

- VS Code Version: 1.9.1
- Node.js Version: 7.5.0

Steps to reproduce:

1. Download my [repository](https://github.com/FrogTheFrog/chrome-debug-test).
2. Run "npm run start".
3. Break at "login/login.component.ts => console.log(a)" and check its value.

**Comment by roblourens** [comment]
It's actually not breaking where you think it is- if you look at the mapped file in chrome devtools, you can see that the sourcemap actually maps to some JS, not TS. Something about your webpack config will need to change to get it to map to the original TS sources but I don't know webpack well enough to tell you what.

**Comment by FrogTheFrog** [comment]
AHHH, thank you! I forgot to set "sourceMap" to true in tsconfig.json. Such a silly mistake.
