### ISSUE TITLE
`Error processing "variables": Cannot find context with specified id` every second

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug#364]
Observed:
![image](https://cloud.githubusercontent.com/assets/1018196/23088315/468abd22-f530-11e6-82e5-1ba25bbf81af.png)

Sometimes I see an error `Error processing "variables": Cannot find context with specified id` every second. It doesn't go away until I refresh page. Seems like the debugger got in a bad state. 

Expected:
No bad state

This is with latest vscode and I downloaded the plugin on monday.

**Comment by roblourens** [comment]
Hm, that error is probably coming from Chrome, not my code. Did you have any watches when you saw this? If you see it again, can you set diagnosticLogging and give me the log?

**Comment by nojvek** [comment]
No watches. I don't see that when I debug with actual devtools. I'll enable
diagnostic logging and get back to you.

**Comment by roblourens** [comment]
I mean, probably coming from Chrome as a result of the adapter doing something wrong. Thanks.

**Comment by roblourens** [comment]
Also seeing this in the wild in telemetry, but I still don't know what's causing it. I'm also curious if there are any logged objects in the console.

**Comment by Klemensas** [comment]
I'm also experiencing this. This happens on either manual page reload or a reload through the debugger. 
My launch file looks like this:
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "url": "localhost/carousel/dist"
        }
    ]
}
```

The cause seems to be the `workspaceRoot` variable, changing it to a static value seems to stop the issue from occurring.

**Comment by Klemensas** [comment]
I am also getting this on the newest version (2.5.4). The cause indeed seems to be logged objects. 
I can reproduce it consistently by logging an object, expanding that object in the debug console and then reloading the window. The error messages will start and not cease until the object is collapsed.

**Comment by roblourens** [comment]
I see the problem with @Klemensas repro steps, thanks.

**Comment by respectTheCode** [comment]
I am getting this same thing except for me I have to restart chrome for it to stop. Reloading the page doesn't do it.

I don't have any watches but I do have break points.

**Comment by roblourens** [comment]
Thanks for the reports. For now, when you refresh the page, logged objects will disappear, because they are requested from chrome again each time the console updates. We need to cache the values so they aren't requested from the debug adapter again, which is tracked in https://github.com/Microsoft/vscode/issues/18001.
