### ISSUE TITLE
Debug javascript angular-cli, breakpoints ignored

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-chrome-debug#365]
_From @doczoidberg on February 20, 2017 11:2_

- VSCode Version: 1.9.1
- OS Version: windows 10

Steps to Reproduce:

1. create angular-cli project with some components (e.g. https://github.com/doczoidberg/ang1)
2. install chrome debug extension and use it 1.9.1
ng serve
attach debugger in vs code

debugging console works in vs code so that I think chrome is attached to vs code right.

but when settings a breakpoint in app.component.ts line 9 vs code says 'Breakpoint ignored because generated code could not be found (source map problem?)

this problem does not occur in webstorm 2017. 
Breakpoints are sometimes also set on the wrong line in VS code

_Copied from original issue: Microsoft/vscode#20918_

**Comment by weinand** [comment]
@doczoidberg how does the launch configuration you are using look like?

**Comment by weinand** [comment]
_From @doczoidberg on February 21, 2017 10:0_

```
      {
            "name": "9222 attach Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "attach",
             "port": 9222,
            "url": "http://localhost:4200/*",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                     "webpack:///./*": "${workspaceRoot}/*"
            }
        },
```

**Comment by weinand** [comment]
Since this is an issue with the Chrome debugger, I'll move the issue to the correct repository.

**Comment by doczoidberg** [comment]
I have to delete the %temp% folder on win64 to get the breakpoints working correct after each code change. I think this is a vscode issue and not the plugin issue?

**Comment by maxime1992** [comment]
@doczoidberg do you know on Linux if there's anything I can do to get this working ? (like the trick to remove %temp% on windows).

**Comment by doczoidberg** [comment]
@maxime1992 sorry I don't know

**Comment by roblourens** [comment]
@doczoidberg Try refreshing the page after attaching. Your scripts are garbage collected by Chrome after they run, when a debugger isn't attached. I see the exact same behavior in chrome devtools.

**Comment by maxime1992** [comment]
@roblourens I don't know why but I did create a project from scratchand it's working well now ... Thanks !
