### ISSUE TITLE
Reverse map JSException error callstacks back to source

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug#366]
Steps to reproduce:

1. Suppose you have a project which compiles to a bundled.js
2. When an unhandled exception occurs or an error object is logged
3. Chrome devtools nicely reverse-maps the exception call stack to source callstack
4. Would love to see this in vscode. 

With webpack-dev-server the compilation is done in memory so the bundled js is not even saved on disk. 

When you see an error like this, in the console, its not very helpful

```
TypeError: Cannot read property 'foobar' of undefined
    at Object.blah (http://localhost:8080/app.bundle.js:66857:64)
    at http://localhost:8080/app.bundle.js:67052:58
    at http://localhost:8080/app.bundle.js:67076:20
    at http://localhost:8080/app.bundle.js:67078:18
    at Array.reduce (native)
    at http://localhost:8080/app.bundle.js:67036:57
    at http://localhost:8080/app.bundle.js:67081:14
    at http://localhost:8080/app.bundle.js:67151:12
    at http://localhost:8080/app.bundle.js:67292:10
```

can't click on app.bundle.js as its not a file url. Even if it is the line numbers won't match as its an in memory compilation. It only writes to the disk first time. Its really fast for subsequent changes.

Since the adapter already maintains source mappings, its going to be faster than a human at translating to the source numbers. The other advantage is I can click on the stack lines to automatically jump to the correct tab and figure out what went wrong.

**Comment by auchenberg** [comment]
We are already tracking this enhancement in https://github.com/Microsoft/vscode-chrome-debug-core/issues/6
