### ISSUE TITLE
Vs code debug angular 2 webpackq

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-chrome-debug#367]
_From @brux88 on February 20, 2017 23:55_

hello, I am trying to debugging an app created with angular cli from vs code, but it does not work that way?

_Copied from original issue: Microsoft/vscode#20964_

**Comment by weinand** [comment]
@brux88 please provide details about your setup (VS Code version, platform, node version, launch.json), the exact steps you've tried and what doesn't work.

**Comment by weinand** [comment]
_From @brux88 on February 22, 2017 7:55_

of corse, 
Vs Code : 1.9.1
node : 6.9.5
ng (angular-cli) : @angular/cli: 1.0.0-beta.32.3 [2.7.0]

my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}/src",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "sourceMapPathOverrides": {
                "webpack:///C:*":"C:/*"
            }
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}/src",
            "sourceMapPathOverrides": {
                "webpack:///C:*":"C:/*"
            }
        }
    ]
}```

i add this string "--remote-debugging-port=9222" in target of chrome.exe ,

The step is:
open vs code, open termina and digit "ng serve" then go on debug and click on "Launch Chrome against localhost, with sourcemaps".

this is my solution:
![2017-02-22_0853](https://cloud.githubusercontent.com/assets/3495339/23202005/63165f0a-f8dc-11e6-9996-d90d259af608.png)


Finally, I wanted to know if it was possible to manage everything from "vs code", ie without have to write ng serve, automatically if you do I debug, the server is started and opens me the solution of chrome

**Comment by roblourens** [comment]
Looks like you're missing a slash in your sourceMapPathOverrides: `"webpack:///C:/*":"C:/*"`

**Comment by brux88** [comment]
i try but not work, if I go in the breakpoint tells me there's something wrong, I have attached a picture
![immagine](https://cloud.githubusercontent.com/assets/3495339/23250596/1c6f22f2-f9aa-11e6-9bb8-5de6ecce1fd2.png)

**Comment by roblourens** [comment]
Try using the `.scripts` command to debug it, there are details in the readme.

**Comment by brux88** [comment]
excuse me, where I have to use .scripts?

**Comment by roblourens** [comment]
There is lots of advice in the readme on how to use `.scripts` and debug this problem, please try it out.

**Comment by maxime1992** [comment]
I do have the same issue. It would be very nice to have a working repo of a fresh angular-cli project with the `launch.json` file in it :)

In case anyone is wondering how to create and start a project with angular-cli : 
**With npm :**
```
npm i -g @angular/cli
cd /tmp
ng new --ng4 debug-test
cd debug-test
ng serve
```

**With yarn :**
```
yarn global add @angular/cli
cd /tmp
ng new --ng4 debug-test
cd debug-test
ng serve
```

I think many people are interested in that configuration because I opened a [stackoverflow](http://stackoverflow.com/questions/40443217/debug-with-visual-studio-code-not-working) topic about that which has more than 1600 views.

**Comment by roblourens** [comment]
This works fine for me out of the box, with no special sourceMapPathOverrides config.

If breakpoints don't bind at first, try refreshing the page, because chrome may garbage collect scripts when they are done running. Chrome devtools will show the same behavior.

**Comment by LwaziPrusent** [comment]
if anyone joins and wants a working example of the launch.json here it is
also as @roblourens  mentioned used the .scripts command it's very useful to see why files are not mapped correctly

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}`

**Comment by smithag77** [comment]
Thank you so much @LwaziPrusent and @roblourens for the assist.  This worked perfectly.

Would either of you be able to tell me how to debug the e2e tests that the angular cli runs?  That has me stumped.

**Comment by roblourens** [comment]
Here's a blog post on karma debugging if that helps: http://blog.mlewandowski.com/Debugging-Karma-tests-with-VSCode.html

Otherwise please open another issue with details

**Comment by smithag77** [comment]
@roblourens thank you.  That definitely helped me set up debugging for my unit tests.  I'm tantalizingly close to getting my e2e tests "debuggable" but still not quite there.  Per your request, I've submitted [an issue](https://github.com/Microsoft/vscode-chrome-debug/issues/413).

**Comment by sebasfiorent** [comment]
@roblourens  you say that "If breakpoints don't bind at first, try refreshing the page, because chrome may garbage collect scripts when they are done running." Cant reproduce with devtools, are you sure that is nothing with the chrome-debug extension?

**Comment by daBishMan** [comment]
I have the same issue where I can not even hit my break points for end to end test using protractor.

**Comment by atlabiz** [comment]
How the , i can debug ANG4 with Vs code

**Comment by atlabiz** [comment]
I have undefined breakpoint

**Comment by auchenberg** [comment]
@atlabiz Have you seen, https://medium.com/@auchenberg/super-charged-live-editing-and-javascript-debugging-for-angular-using-visual-studio-code-c29da251ec71?

Please open an new issue instead re-using this old one, if the problem/angular version is different.

**Comment by haydenhancock** [comment]
@LwaziPrusent Thanks! Using your launch.json configuration resolved my issue.

Visual Studio Code 1.14.2
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Angular Cli 1.2.5
