### ISSUE TITLE
Feature req: Run and debug karma / angular2 (cli) tests

### ISSUE THREAD

**Issue by mmc41** [Microsoft/vscode-chrome-debug#369]
It would be wonderful if one could debug angular 2 cli's karma bases tests inside visual code.

Right now I can debug an angular 2 app with a suitable "chrome" launch configuration but I haven't found a way to run and debug the associated karma/jasmine test suite. If I use angular2 cli's "ng test" option it will start a browser but it will proceed before I have a chance to attach the debugger. It would be much nicer, if I could start and debug the tests from inside visual code.

**Comment by roblourens** [comment]
Can you debug it with chrome devtools? How does that work usually?

**Comment by roblourens** [comment]
This might just be something that angular or karma needs to implement - wait to run the tests until you click a button or something.

**Comment by mmc41** [comment]
I can only debug karma tests in the browser. vscode-chrome-debug can't be used for debugging karma tests. I would prefer if I could start and launch the tests from vscode. You suggestion about changing karma/angular would only allow attach to work.

**Comment by roblourens** [comment]
How do you debug it in the browser?

**Comment by xxxtonixxx** [comment]
I can run karma/jasmine test with this config
```javascript
{
    "name": "Run jasmine",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:9876/debug.html",
    "sourceMaps": true,
    "webRoot": "${workspaceRoot}/src",
    "userDataDir": "./out/chrome",
    "runtimeExecutable": "/usr/bin/google-chrome-stable",
    "skipFiles": [
      "node_modules/**/*"
    ],

    "sourceMapPathOverrides": {
      "webpack:///./*": "${workspaceRoot}/*"
    }
  }
```

I run `ng test` and, then I launch debugger. However, I need reload/refresh web browser/debugger to do to work breakpoints.

**Comment by roblourens** [comment]
Right, I mean, I don't know how people usually debug it in Chrome without having to refresh the page. Since it sounds like the tests will just start running before the debugger has attached, in either case.

**Comment by roblourens** [comment]
Here's a blog post about Karma debugging with vscode: http://blog.mlewandowski.com/Debugging-Karma-tests-with-VSCode.html
