### ISSUE TITLE
Cannot see variables & call stack

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode-chrome-debug#37]
I have successfully connected Code to Chrome using your extension: I can see the console logs into the Debug Console of code, and I can play/pause the execution from Code. However, when in a breakpoint, variables/watch/callstack panel remains empty.

What could be missing ?

**Comment by roblourens** [comment]
Hm, which OS is this? And can you try setting `"diagnosticLogging": true` in your launch config, and copying out the logs that are dumped in the console?

**Comment by warpdesign** [comment]
I'm using Windows (10). After more tests it seems only the console output is working (and I can type code into the Code debug console, and it is correctly executed into Chrome).

- If I set breakpoints into Code, it won't break.
- Same thing for "debugger" statements found into the code: it won't break.
- Pressing the "pause" button in Code doesn't seem to pause the execution

If I open the chrome dev tools, it stops the connection from Code, I guess this is normal.

**Comment by warpdesign** [comment]
Here is the debug log:

 ›[50:16.894] OS: win32 ia32
  ›[50:16.895] Node version: v4.1.1
  ›[50:16.904] Adapter version: 0.1.5
  ›[50:16.906] spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost:9000/editor/#/element/?uuid=ONMAP_PROJET_HOME_ELEMENT"])
  ›[50:16.910] Attempting to attach on port 9222
  ›[50:16.933] To target: {"id":1,"method":"Debugger.enable"}
 ›[50:17.160] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"590","url":"","startLine":0,"startColumn":0,"endLine":5,"endColumn":2}}
  ›[50:17.160] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"507","url":"","startLine":0,"startColumn":0,"endLine":7,"endColumn":2}}
  ›[50:17.161] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"568","url":"","startLine":0,"startColumn":0,"endLine":7,"endColumn":2}}
  ›[50:17.161] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"364","url":"http://localhost:9000/editor/scripts/rappid-module/services/geometryService.js","startLine":0,"startColumn":0,"endLine":115,"endColumn":5,"sourceMapURL":""}}
  ›[50:17.162] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"284","url":"http://localhost:9000/editor/bower_components/gsap/src/uncompressed/TweenMax.js","startLine":0,"startColumn":0,"endLine":7053,"endColumn":127,"sourceMapURL":""}}
  ›[50:17.163] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"294","url":"http://localhost:9000/editor/bower_components/perfect-scrollbar/src/perfect-scrollbar.js","startLine":0,"startColumn":0,"endLine":877,"endColumn":0,"sourceMapURL":""}}
  ›[50:17.165] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"312","url":"http://localhost:9000/editor/bower_components/onmap-shared/scripts/share-module/services/i18n.js","startLine":0,"startColumn":0,"endLine":31,"endColumn":5,"sourceMapURL":""}}
  ›[50:17.167] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"531","url":"","startLine":0,"startColumn":0,"endLine":7,"endColumn":2}}

[...]

  ›[50:17.352] From target: {"id":1,"result":{}}
  ›[50:17.352] To target: {"id":2,"method":"Console.enable"}

[...]

  ›[50:17.364] From target: {"id":2,"result":{}}
  ›[50:17.364] To client: {"seq":0,"type":"event","event":"initialized"}
  ›[50:17.364] To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
  ›[50:17.366] From client: setBreakpoints({"source":{"path":"c:\\docs\\dev\\onmap6_sp77\\yo\\editor\\app\\scripts\\right-panel-module\\directives\\right-panel.js"},"lines":[240]})
  ›[50:17.368] SourceMaps.setBreakpoints: c:\docs\dev\onmap6_sp77\yo\editor\app\scripts\right-panel-module\directives\right-panel.js can't be resolved to a loaded script.
  ›[50:17.369] From client: setExceptionBreakpoints({"filters":["uncaught"]})
  ›[50:17.369] To target: {"id":3,"method":"Debugger.setPauseOnExceptions","params":{"state":"uncaught"}}
  ›[50:17.379] From target: {"id":3,"result":{}}
  ›[50:17.380] To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}

**Comment by roblourens** [comment]
It's weird that nothing happens when you hit a debugger statement - if you're attached to the right tab, *something* should happen then even if it can't match up the source.

You set a breakpoint in `right-panel.js`, was there a scriptParsed event for the file it maps to? This could be the same problem as #32 - you may need to set `"cwd"` to the folder that your files are served from.

**Comment by warpdesign** [comment]
When setting a breakpoint to rightPanel.js I'm getting the following in the debug log:

No target url cached for client url: c:\docs\dev\onmap6_sp77\yo\editor\app\scripts\right-panel-module\directives\right-panel.js, waiting for target script to be loaded.

Note: Code was opened on the onmap6_sp77 directory.

**Comment by warpdesign** [comment]
Setting `cwd` to the fold the files are served from seem to have fixed the problem: now when setting a breakpoint from it correctly stops execution and I can see the call stack,..

Only problem is that sometimes it cannot find the correct tab to attach to.

**Comment by chandra-sekar** [comment]
I am facing the same issue on OSX. I was able to set breakpoints but I cannot see any of the variables and I am unable to step through. I am only able to pause and play execution.

My breakpoints don't hit if I set "diagnosticLogging" to True. I can paste my debug log here if it will help.

**Comment by maximedupre** [comment]
I have the same problem on OSX and setting `cwd` does not fix the problem. As mentioned:
* If I set breakpoints into Code, it won't break.
* Same thing for "debugger" statements found into the code: it won't break.
* Pressing the "pause" button in Code doesn't seem to pause the execution

Here is the diagnostic:
 ›[22:09.019] OS: darwin x64
  ›[22:09.020] Node version: v4.1.1
  ›[22:09.021] Adapter version: 0.1.6
  ›[22:09.021] spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://192.168.2.5:8000"])
  ›[22:09.026] Attempting to attach on port 9222
  ›[22:09.881] To target: {"id":1,"method":"Debugger.enable"}
  ›[22:09.942] From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"45","url":"http://192.168.2.5:8000/main.js","startLine":0,"startColumn":0,"endLine":9,"endColumn":3,"sourceMapURL":""}}
  ›[22:09.944] From target: {"id":1,"result":{}}
  ›[22:09.945] To target: {"id":2,"method":"Console.enable"}
  ›[22:09.949] From target: {"method":"Console.messageAdded","params":{"message":{"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (File not found)","timestamp":1448241729.88494,"type":"log","line":0,"column":0,"url":"http://192.168.2.5:8000/recordings/camaupoint-15-11-21-17-35-40.h264","networkRequestId":"73982.3"}}}
Failed to load resource: the server responded with a status of 404 (File not found) (http://192.168.2.5:8000/recordings/camaupoint-15-11-21-17-35-40.h264)
  ›[22:09.951] From target: {"method":"Console.messageAdded","params":{"message":{"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (File not found)","timestamp":1448241729.93829,"type":"log","line":0,"column":0,"url":"http://192.168.2.5:8000/favicon.ico","networkRequestId":"73982.4"}}}
Failed to load resource: the server responded with a status of 404 (File not found) (http://192.168.2.5:8000/favicon.ico)
  ›[22:09.952] From target: {"id":2,"result":{}}
  ›[22:09.953] To client: {"seq":0,"type":"event","event":"initialized"}
  ›[22:09.953] To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
  ›[22:09.954] From client: setBreakpoints({"source":{"path":"/Users/maximedupre/Desktop/Dropbox/documents/camaupoint/main.js"},"lines":[5]})
  ›[22:09.956] To target: {"id":3,"method":"Debugger.setBreakpointByUrl","params":{"url":"http://192.168.2.5:8000/main.js","lineNumber":4,"columnNumber":0}}
  ›[22:09.956] From client: setExceptionBreakpoints({"filters":["uncaught"]})
  ›[22:09.956] To target: {"id":4,"method":"Debugger.setPauseOnExceptions","params":{"state":"uncaught"}}
  ›[22:09.966] From target: {"id":3,"result":{"breakpointId":"http://192.168.2.5:8000/main.js:4:0","locations":[{"scriptId":"45","lineNumber":4,"columnNumber":1}]}}
  ›[22:09.967] To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"line":5}]}}
  ›[22:09.967] From target: {"id":4,"result":{}}
  ›[22:09.967] To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}

**Comment by roblourens** [comment]
@warpdesign If you have multiple tabs open, it may not find the right one. It tries to pick one by URL but isn't perfect. And note that `cwd`

**Comment by roblourens** [comment]
@warpdesign If you have multiple tabs open, it may not find the right one. It tries to pick one by URL but isn't perfect. Also note that I just pushed an update which renames `cwd` to `webRoot`. 

@chandra-sekar The log would be helpful, thanks.

@maximedupre That's odd that it works in attach mode but not launch mode. Do you see an obvious difference in the logs? The one you posted for launch looks like it has attached correctly and set a breakpoint successfully, so if you don't get a "Debugger.paused" event from Chrome, then maybe the breakpoint isn't being it or it's on the wrong line.

**Comment by maximedupre** [comment]
@roblourens Odd indeed! I tried the attach and launch modes with the same code and breakpoints and only the attach mode works.

**Comment by kowsheek** [comment]
I was able to repro this, adding `sourceRoot` made things go. Though, the schema is pending update since it shows this property is not allowed in the launch task.

@maximedupre Can you try to add `sourceRoot` to the launch task (ignore the warning). And set it to absolute path to the root of your source files, similar to: https://github.com/Microsoft/vscode-chrome-debug/issues/45#issuecomment-158223633

**Comment by maximedupre** [comment]
@kowsheek I am not using `"sourceMaps": true`, but I still tried your suggestion and it didn't work.

I don't know if the plugin has been updated (are plugins auto-updated by VSC?), but now neither the attach or launch modes work. I have tried multiple combinations with webRoot, sourceRoot, etc with not success.

**Comment by roblourens** [comment]
`sourceRoot` isn't a property in the launch config, I was talking about `sourceRoot` in the actual source map. That problem has been fixed in 0.1.9. 

@maximedupre  In this log I see it's trying to resolve `/Users/maximedupre/Desktop/Dropbox/documents/icms/icms-web/web/src/main.js` to `http://web:8080/src/app.js`. It should work if you set `webRoot` to `/Users/maximedupre/Desktop/Dropbox/documents/icms/icms-web/web/` (or a relative path there from the directory that's open in Code). Unfortunately there's a bug in 0.1.6 so the log doesn't have the properties in your launch config.

**Comment by maximedupre** [comment]
@roblourens 

> `sourceRoot` isn't a property in the launch config, I was talking about sourceRoot in the actual source map. That problem has been fixed in 0.1.9.

Ah ok! I am not using `sourceMaps` now, so neither of those keywords are defined in my launch.json.

> In this log I see it's trying to resolve /Users/maximedupre/Desktop/Dropbox/documents/icms/icms-web/web/src/main.js to http://web:8080/src/app.js. It should work if you set webRoot to /Users/maximedupre/Desktop/Dropbox/documents/icms/icms-web/web/ (or a relative path there from the directory that's open in Code). Unfortunately there's a bug in 0.1.6 so the log doesn't have the properties in your launch config.

It's weird that main.js is trying to resolve to app.js...
I have tried setting `webRoot` to `/Users/maximedupre/Desktop/Dropbox/documents/icms/icms-web/web/src/main.js to http://web:8080/src/app.js` or `./web` (the directory opened in Code is icms-web), but none of those configs made the breakpoints work. I have put some `console.log`s at the same place then the breakpoints and those are getting executed, so I know the breakpoints should be triggered.

Also my web server is serving the files from /Users/maximedupre/Desktop/Dropbox/documents/icms/icms-web/web/ if it can be useful information. My server is a simple node module and is launched like this: `web/node_modules/.bin/http-server web -a web

**Comment by roblourens** [comment]
> It's weird that main.js is trying to resolve to app.js...

Oops, copied the wrong line. Sorry, I'm still not sure what the problem could be. The latest version, 0.1.10 has a couple extra log statements around this. And to answer your question above, plugins aren't updated automatically, you have to go through the install dialog again.

**Comment by maximedupre** [comment]
@roblourens 
> Oops, copied the wrong line. Sorry, I'm still not sure what the problem could be. The latest version, 0.1.10 has a couple extra log statements around this. And to answer your question above, plugins aren't updated automatically, you have to go through the install dialog again.

I updated to version 0.1.10 and it works perfectly. Why the hell do we have to uninstall and reinstall a plugin to update it? I think it's a major flaw. Anyway, I'm happy it works now! I'll keep an eye on the versions to update manually. Thanks for the help.

-M

**Comment by roblourens** [comment]
Great! And yeah there are some issues on the vscode repo for the extension updating experience. 

It looks like everyone in this thread has it working now, thanks for helping me track these issues down.

**Comment by kowsheek** [comment]
Thanks a bunch for making this happen @roblourens! Debugging will never be the same for me anymore :dancer:
