### ISSUE TITLE
Problem "localhost refused to connect"

### ISSUE THREAD

**Issue by scattin000** [Microsoft/vscode-chrome-debug#376]
Hey guys, I've been reading a tun of various articles and trying all sorts of commands and what not... but then FINALLY after 6hours yesterday attempting to get this going it came down to my localhost isn't set up? I've tried finding videos on youtube, but none of them seemed to do the trick either :/   Basically, I need help!!!

- VS Code Version:  latest version + Google Chrome Debugger 

Steps to reproduce:

1. JSON file
{
    "version": "0.2.0",
    "configurations": [{
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceRoot}/main.html"
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceRoot}/main.html"
        }
    ]
}
2. I run attempt to debug but Google Chrome pops up and says " localhost refused to connect."
3. How do I connect?/ set up the local host for this?  

I know this is probably silly, I've been trying really hard but nothing has worked!

**Comment by roblourens** [comment]
Are you running a server on 8080? The extension doesn't provide a server for you, you have to set up your own.

**Comment by chetan8470** [comment]
8000
