### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by pankleks** [Microsoft/vscode-chrome-debug#377]
I have this error when trying to start chrome debug session.
All was working fine before - I believe it started when I upgraded chrome debug extension to latest version (2.6.0).

VSCode is 1.10.1 on Windows
Chrome debug ext is 2.6.0

Thanks

**Comment by roblourens** [comment]
Is there an error in the console or devtools (Help > Toggle developer tools)?

If not, can you set `"trace": true` and upload the log file?

**Comment by pankleks** [comment]
Hi,

I can't run dev. tools at error happens before Chrome is open.
I set `trace`, but I don't see any log file?
Where I can find it?

**Comment by roblourens** [comment]
By devtools, I mean the devtools against vscode, under the Help menu.

If you set 'trace', it should log something to the console saying "Verbose logs are written to <path>", they are in that file.

**Comment by laurynasmaciulis** [comment]
I have same issue with 2.6.0.
Developer tools log:
`Service.ts:126 
Debug adapter process has terminated unexpectedlye.doShow @ messageService.ts:126
e.show @ messageService.ts:105
g.onServerExit @ rawDebugSession.ts:510
anonymous function) @ rawDebugSession.ts:424
emitTwo @ events.js:111emit @ events.js:191
ChildProcess._handle.onexit @ internal/child_process.js:215`

I have downgraded to 2.5.5 and it seems to work fine now.

**Comment by roblourens** [comment]
Sorry @pankleks, I don't mean 'trace'. It was renamed from 'diagnosticLogging' but not in time for 1.10.

Can you (and @laurynasmaciulis) set `"diagnosticLogging": true`? Then it will write logs to a file, the file path is at the top of the debug console, please upload the log. Thanks.

**Comment by pankleks** [comment]
Hi,

Debug console does not say anything interesting, same message as @laurynasmaciulis.
I set `"diagnosticLogging": true` but I don't see any file created or any message in debug console about it.

**Comment by pankleks** [comment]
Also one more info. 

When I tested on other environment (all same versions) it works well.

**Comment by pankleks** [comment]
@laurynasmaciulis - how you downgraded to 2.5.5

I can't find such function. Thanks!

**Comment by laurynasmaciulis** [comment]
**Download**
https://msjsdiag.gallery.vsassets.io/_apis/public/gallery/publisher/msjsdiag/extension/debugger-for-chrome/2.5.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Rename** 
Microsoft.VisualStudio.Services.VSIXPackage to Microsoft.VisualStudio.Services.vsix

**Install from VSC terminal**
code --install-extension {location where .vsix file is}\Microsoft.VisualStudio.Services.vsix

**Comment by roblourens** [comment]
I still haven't seen an issue, can someone do me a big favor?

Clone and build this repo by the directions here: https://github.com/Microsoft/vscode-chrome-debug/blob/master/CONTRIBUTING.md

Then follow the directions to start the debug adapter and run your app against it. Hopefully it crashes in the same way, and you see some error message.

**Comment by pankleks** [comment]
Hi, upgrading to version 2.7.0 solved issue for me.
Thank you for your time.
