### ISSUE TITLE
Breakpoint with async / await attaches to javascript, not typescript in webpack project

### ISSUE THREAD

**Issue by masonch** [Microsoft/vscode-chrome-debug#378]
- VS Code Version: 1.10.1

Steps to reproduce:

1. Start webpack-dev-server
2. Set a breakpoint in typescript code after an await call
![image](https://cloud.githubusercontent.com/assets/6392972/23636837/d5e69cac-02a5-11e7-98f1-e6630b77b608.png)
3. When breakpoint hits, it is in the javascript file
![image](https://cloud.githubusercontent.com/assets/6392972/23636862/0b3e0016-02a6-11e7-914b-7f96d6efbe4b.png)

I can provide the .scripts output as well as the vscode-chrome-debug.txt.

Note: this was partially working in with the 2.5.x chrome debug extension. However, in that version, while breakpoints were being hit, hover on variables after an await call did not display anything.

**Comment by roblourens** [comment]
This is expected because those lines are not mapped to Typescript code. I recommend debugging async/await with the 'smartStep' option (which should be added to the readme!) to automatically step over unmapped lines.

**Comment by masonch** [comment]
Sure I can share more code with you. I will send you an email.

For the devtool, I am using inline-source-map.

I just tried with smartStep enabled and it did not jump into javascript, however, it ignored any breakpoints after await and jumped back up to the calling method (and no hover capability)

**Comment by roblourens** [comment]
I see that you are using async/await to ES5 which makes the transpiled code/sourcemap very complicated. I see the problem but I'm not sure what to do about it.

async functions get transpiled into large switch statements when targetting ES5. Any variables are declared before the switch block. The sourcemap maps the `let x = ` part to that code before the switch block, and the stuff after the = sign is mapped to the line you would expect. So when the bp is set at column 0, it goes to the line that executes before the await.

Chrome devtools does the same thing. All I can say is, it will work better when we support column breakpoints, or if you can transpile to es6.

**Comment by masonch** [comment]
I am not sure if going to es6 is an option in this case. I can explore it, but we may be forced to go with es5.

**Comment by roblourens** [comment]
Yeah, it's tough especially if you are supporting IE. I'm going to open an issue on TS

**Comment by roblourens** [comment]
https://github.com/Microsoft/TypeScript/issues/14506

**Comment by auchenberg** [comment]
This has now been fixed in TypeScript, and should land in TS 2.4.1
