### ISSUE TITLE
sourceMapPathOverrides do not take application-relative URLs

### ISSUE THREAD

**Issue by fpsychias** [Microsoft/vscode-chrome-debug#379]
When I set a source map path override, I would expect the left-hand side to be relative to the domain or the url of the debug configuration. Instead, when the served JS file is in a subdirectory and the source map creates a tree within, the expression I specify gets tested against the sourceRoot and sources entries of that source map, with no regard to the path (url) the files are in.

I am testing the extension with EmberJS's new ES6 source mapping feature in v2.12's beta and would love to see this issue resolved.

I currently have to map my application like this: `"my-ember-proj/*": "${workspaceRoot}/app/*"`
when it would make a lot more sense to me if the correct way was: `"assets/my-ember-proj/*": "${workspaceRoot}/app/*"`.

Also, I guess the way it is now is prone to conflicts for big projects that could have many source maps.

VSCode is v1.10.2 on Windows
The extension is v2.6.0

Thanks!

**Comment by roblourens** [comment]
The left hand side is looking at the paths that are written in your sourcemap, they aren't looking at the disk at all, so it all depends on how Ember is writing sourcemaps. 

I'd like to try out this new feature, do you have a pointer to a repo where I can try it? If there's a common default sourcemap config that ember uses, I'd like to include it in the extension so it works out of the box.

**Comment by pjsykes** [comment]
@roblourens, the left hand side does look at the sourcemap itself but if the sourcemap is in an url path (not under the domain directly), while Chrome's debugging tools display the sources tree under that path, it is not factored in the expression tests.

![capture1](https://cloud.githubusercontent.com/assets/26348814/23831423/88ffe758-0729-11e7-8ca6-1d659a973547.png)

As you can see, a tree (orange folders) is created with the `sources`, in the path the sourcemap itself is in.

Any [new (even empty) Ember v2.12 project](https://github.com/ember-cli/ember-cli/releases/tag/v2.12.0-beta.2)* will work, you just need to add the following in the `new EmberApp` initialization in ember-cli-build.js

    babel: {
      sourceMaps: 'inline'
    }

\* Note: steps for update are also steps for project creation
