### ISSUE TITLE
Chrome isn't using the WebKit Remote Debugging Protocol

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#38]
The WebKit and Blink Remote Debugging protocols has diverged when Blink branched off Webkit. Today they are using the same underlaying protocol (JSON RPC over WebSocket), but the API's has changed.

There are efforts like https://github.com/artygus/devtools-compat-proxy and https://github.com/samccone/webkit-remote-debugger-translator to adapt the API differences, but since this projects aims to target Chrome-based browsers/runtimes, I'd suggest that the name of this repo/project should be update.

A more accurate name would be `vs-code-chrome-debug`.

**Comment by paulirish** [comment]
+1. The official name is the Chrome Debugging Protocol

The WebKit protocol is now here: https://trac.webkit.org/browser/trunk/Source/WebInspectorUI/Versions

**Comment by roblourens** [comment]
Waiting on admin access to rename this repo

**Comment by paulirish** [comment]
Cool! No rush from me, but that sounds good. Thx Rob!

**Comment by auchenberg** [comment]
@roblourens Looks like you renamed the repo, so I'm closing.
