### ISSUE TITLE
Cannot watch or evaluate variables using TypeScript.

### ISSUE THREAD

**Issue by joneal** [Microsoft/vscode-chrome-debug#380]
VS Code Version: 1.10.2
Debugger for Chrome: 2.6.0

I created a new default Angular (2,3,4,??) application using the Angular Command Line tool (angular-cli).

Application is hosted by using 'ng serve'.

I can get Chrome to launch from the VS Code debugger, and I can hit breakpoints.  However, I cannot view any TypeScript variables e.g. "title" of the application.  I get 'not available' when adding in the Watch windows, or  ReferenceError: title is not defined if trying to evaluate.

Breakpoint is on last line, trying to view "title":

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Application XYZ';
}     <-------- breakpoint is here
```

I get this information in the trace when I try to add the watch or evaluate:

From client: evaluate({"expression":"title","frameId":1000,"context":"watch"})
To target: "{\"id\":30,\"method\":\"Debugger.evaluateOnCallFrame\",\"params\":{\"callFrameId\":\"{\\\"ordinal\\\":0,\\\"injectedScriptId\\\":5}\",\"expression\":\"title\",\"silent\":true,\"generatePreview\":true}}"
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"193","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":5,"executionContextId":5,"hash":"C8192A116CB49A604CB5762843D429DC872EBA18","executionContextAuxData":{"isDefault":true,"frameId":"8344.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false}}
From target: {"id":30,"result":{"result":{"type":"object","subtype":"error","className":"ReferenceError","description":"ReferenceError: title is not defined\n    at eval (eval at evaluate (:85:21), \u003Canonymous\u003E:1:1)\n    at http://localhost:4200/main.bundle.js:67:1\n    at Object.433 (http://localhost:4200/main.bundle.js:67:2)\n    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)\n    at Object.434 (http://localhost:4200/main.bundle.js:80:73)\n    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)\n    at Object.324 (http://localhost:4200/main.bundle.js:24:74)\n    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)\n    at Object.553 (http://localhost:4200/main.bundle.js:165:18)\n    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)\n    at webpackJsonpCallback (http://localhost:4200/inline.bundle.js:24:23)\n    at http://localhost:4200/main.bundle.js:1:1","objectId":"{\"injectedScriptId\":5,\"id\":44}"},"exceptionDetails":{"exceptionId":8,"text":"Uncaught","lineNumber":0,"columnNumber":0,"scriptId":"193","stackTrace":{"callFrames":[{"functionName":"","scriptId":"193","url":"","lineNumber":0,"columnNumber":0},{"functionName":"","scriptId":"183","url":"http://localhost:4200/main.bundle.js","lineNumber":66,"columnNumber":0},{"functionName":"433","scriptId":"183","url":"http://localhost:4200/main.bundle.js","lineNumber":66,"columnNumber":1},{"functionName":"__webpack_require__","scriptId":"16[...]
 

LAUNCH.JSON
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "smartStep": true,
            "sourceMaps" : true,
            "trace" : "verbose",
            "userDataDir": "${workspaceRoot}/.vscode/chrome", 
            "webRoot": "${workspaceRoot}"
        }      
    ]
}
```
Suggestions?

Thanks!

**Comment by roblourens** [comment]
Is your code minified? If the name 'title' has been clobbered, then it won't exist. Does it show up in the variables pane?

**Comment by joneal** [comment]
Yes, the variable "title" does show up in the pane...just has "not available" as value.  I looked at the resultant transpiled JavaScript and it does not appear to be minified.

**Comment by roblourens** [comment]
Does it work in chrome devtools? Does it look like the line number is correct in the stack, line 67 in main.bundle.js? It looks like it might actually be paused in webpack_require which would be some issue with sourcemaps.

**Comment by joneal** [comment]
Well...webpack is new to me.  However, in Chrome debugger I can select line 67 in main.bundle.js, and Chrome loads app.component.ts, which corresponds to the chunk in main.bundle.js.  In the loaded TS file, I can set the breakpoint at the same location in Chrome as I was did in VS Code.  I can view "title" in Chrome and it has the correct value.  But if I refresh the browser and hit the breakpoint again, then "title" <not available>.

**Comment by roblourens** [comment]
Ok. It sounds like the extension has some issues with angular-cli apps. I'll try it out.

**Comment by joneal** [comment]
Thanks...let me know if there is anything you want me to test.

**Comment by roblourens** [comment]
Looking at the code more closely, `title` is not a local variable here, it's a member of the class. `this.title` might work.

**Comment by joneal** [comment]
Quick test shows that this does work (no pun intended).

Watch window:
title --> "not available"
this.title --> "Application XYZ"

Unfortunate that editor will not prefix with "this.", at least not be default.  Will research.

Thanks for you help, and the great extension.
