### ISSUE TITLE
Help. launch configuration for Rails environment. 

### ISSUE THREAD

**Issue by BernardDoherty** [Microsoft/vscode-chrome-debug#383]
I am seeing this error message on a breakpoint: Breakpoint ignored because generated code not found (source map problem?)

I have tried many different configs. I could not find an example of someone using this in a Rails environment. Does this work with the Rails asset pipeline? Can someone share a config that works with Rails. Here is the basic config I started with:
   {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}"
        }

**Comment by roblourens** [comment]
Check out the `.scripts` command: https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command - to figure out why it can't match your code on disk to code in the webpage.

**Comment by BernardDoherty** [comment]
Thanks. I ran .scripts and I see the following:
› http://localhost:3000/
› http://localhost:3000/assets/application.js

I noticed that the only file that I can set breakpoints on is application.js. Breakpoints do not work on any other javascript files or React .jsx files. I am thinking it is something with my Rails config and how it generates source maps.

**Comment by auchenberg** [comment]
Seems like you need to upgrade to Sprockets 4 to get sourcemaps generated. https://github.com/rails/sprockets/blob/master/UPGRADING.md
