### ISSUE TITLE
Cannot debug electron with angular-cli

### ISSUE THREAD

**Issue by Cazs03** [Microsoft/vscode-chrome-debug#384]
- VS Code Version: 1.10.2

Steps to reproduce:

1. ng serve
2. put break point on app.component.ts
3. Launch debug
3. tooltip: "breakpoint ignored because generated code"
4. My config launch.json for debug with Electron
```
{
            "name": "Debug Renderer Process",
            "type": "chrome",
            "request": "launch",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "runtimeArgs": [
                "${workspaceRoot}/src/electron/electron.js",
                "--enable-logging",
                "--remote-debugging-port=9222"
            ],
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        }
```

I'm wasting electron and angular cli to build app, but, when ill try debug in electron can not read any breakpoint

**Comment by roblourens** [comment]
You may need to use the `.scripts` command or `sourceMapPathOverrides` to debug/fix this - see notes on that in the readme
