### ISSUE TITLE
launch configuration fails when chrome instances are already running

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/vscode-chrome-debug#385]
This problem is known as it is even explained in the readme and the workaround (closing all running instances of chrome) works, but to be honest I find it really hard to use.
I have some chrome instances that are suppose to run all the time for things like mail webclients, intranet, etc, and the requirement to close all those before I can actually use the debugger is basically the only thing stopping me to use it regularly.

I really would like to be able to have an isolated debug instance that I can launch and kill from visual code.

I can imagine that technically it might be a hard problem to solve, but the user experience is really affected by this. It is especially weird to witness a launch configuration resulting into the debugger opening a new tab in one of the running instances.

For the rest, thank you for the plugin and all the work for it, it's really great and is improving incredibly fast. Just a few months ago setting up the plugin with typescript and webpack support was a chore, and now it works almost flawlessly!

**Comment by roblourens** [comment]
Thanks, this is a good point and one of the most common problems.

This is exactly what the `userDataDir` option is for, I like to set it to a temp directory or `"userDataDir": "${workspaceRoot}/.vscode/chrome}"` (and add it to your gitignore). Then you can launch an instance of chrome for debugging alongside your other open instances.
