### ISSUE TITLE
Debugging webpack with webpack-dev-server won't work (Breakpoint ignored because generated code not found(source map problem?))

### ISSUE THREAD

**Issue by BenLampson** [Microsoft/vscode-chrome-debug#387]
I run it with "diagnosticLogging": true. and I get this.

- VS Code Version: 1.10.1

OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.14.7
debugger-for-chrome: 2.7.0
Discovering targets via http://127.0.0.1:9222/json
Warning: Found more than one valid target page. Attaching to the first one. Available pages: ["https://github.com/Microsoft/vscode-chrome-debug/issues/40","http://cn.bing.com/search?q=webpack-dev-server+debugger+for+chrome&qs=n&form=QBRE&sp=-1&pq=webpack-dev-server+debugger+for+chrome&sc=0-35&sk=&cvid=E89BEEF2023A4D5AB9179C6412CC47A2","https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=Wednesday&oq=ignored&rsv_pq=e9260e5a000e4173&rsv_t=ae9e8yTTEJ86E4oZCbYoIGrVDwzuRzBAmWUNNE8ZdYSX2yQc4RbKrvAOIhY&rqlang=cn&rsv_enter=0&rsv_sug3=2&rsv_sug1=2&rsv_sug7=100&rsv_n=2&inputT=786&rsv_sug4=881","https://github.com/Microsoft/vscode-chrome-debug/issues/251","https://github.com/angular/angular-cli/issues/2453","https://github.com/Microsoft/vscode-chrome-debug/issues/237","https://manage.windowsazure.cn/neteasehz.partner.onmschina.cn#Workspaces/VirtualMachineExtension/vms"]
Paths.scriptParsed: could not resolve https://assets-cdn.github.com/assets/frameworks-98ac987e4213944e72be21a9a412be5fd96d2b952083b850e8fd248f05d9796a.js to a file under webRoot: g:\sssssssss\TestCodeFolder\ReactDemo/dist. It may be external or served directly from the server's memory (and that's OK).
Paths.scriptParsed: could not resolve https://assets-cdn.github.com/assets/github-f6463e083942e277a8527c46fc606104e83113ec2037e9bc45037dae089b3020.js to a file under webRoot: g:\sssssssss\TestCodeFolder\ReactDemo/dist. It may be external or served directly from the server's memory (and that's OK).
Target userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by roblourens** [comment]
It looks like you attached to the github tab, not your app.
