### ISSUE TITLE
Call stack shows only top 20 entries

### ISSUE THREAD

**Issue by pmneo** [Microsoft/vscode-chrome-debug#389]
VS Code Version: 1.10.2
Deubber for Chrome: 2.7.1

The Call Stack just shows the top 20 entries where native debugger shows 45 entries.

**Comment by roblourens** [comment]
This is by design for now - someday vscode will support paging of the callstack.

**Comment by chhschou** [comment]
I find this difficult to comprehend. In any application complex enough that we need to grab the debugger for will find the call stack invaluable. How difficult is it to enhance the extension to get more frames displayed?

**Comment by roblourens** [comment]
Paging is now supported. Is it not working for you? If so please open a new issue.

You should see this in the callstack:

![image](https://user-images.githubusercontent.com/323878/37608099-49b66d28-2b5f-11e8-9439-7899cf063633.png)

**Comment by chhschou** [comment]
I don't get the 'load more stack frames', I'm on ubuntu 16.04, chrome Version 65.0.3325.162 (Official Build) (64-bit). My colleagues who use Mac seems to have much bigger stacks.

**Comment by roblourens** [comment]
Are you sure you're missing frames? Or just debugging somewhere with fewer than 20 frames?

**Comment by chhschou** [comment]
I checked a few places over the last 2 days and it seems to agree with chrome so it might've just been a red herring.

**Comment by roblourens** [comment]
Thanks for following up, let me know whether you see a reproducible issue.
