### ISSUE TITLE
Cannot use vscode-chrome-debug without each developer modifying their Chrome shortcut

### ISSUE THREAD

**Issue by JoyalToTheWorld** [Microsoft/vscode-chrome-debug#390]
> Right click the Chrome shortcut, and select properties
> In the "target" field, append --remote-debugging-port=9222
> Or in a command prompt, execute <path to chrome>/chrome.exe --remote-debugging-port=9222

This is not acceptable. I will not have ALL my developers modify their Chrome shortcut, that largely defeats the purpose of configuring launch tasks.

The only workaround I can think of is to create a VSCode task to start chrome with the necessary parameters for remote debugging - which is what you should have done from the start. 

Or am I missing something..

**Comment by roblourens** [comment]
Notice that there are two types of launch config, 'launch' and 'attach'. I recommend 'launch' except for special cases. That direction is for 'attach', in which case you either need to do that, or launch chrome from the command line.

**Comment by JoyalToTheWorld** [comment]
> Notice that there are two types of launch config, 'launch' and 'attach'.

Thanks, already noticed that. I don't see how it helps.

>I recommend 'launch' except for special cases.

Why? It doesn't work by default. It simply opens a new tab using the existing instance of Chrome and fails to attach to the debugger (unless users have jumped through the hoops mentioned above - this is the entire reason why I opened this issue). 

>That direction is for 'attach', in which case you either need to do that, or launch chrome from the command line.

What? No, 
**I want to launch a new instance of Chrome without an active profile and with remote debugging enabled and VSCode attaching to this automatically. Isn't this obvious, I thought that was the whole point of this extension.** 

To compound the issue, I can only configure a single 'preLaunchTask' (talk about a head scratcher), so while I could start Chrome with my desired parameters via 'preLaunchTask', I wouldn't be able to also start my server. 

What am I misunderstanding?

**Comment by auchenberg** [comment]
@JoyalToTheWorld You can use the `userDataDir` option to launch Chrome with a different profile. This is a workaround for the fundamental problem of Chrome not being able to active remote debugging to an already running instance. All of this is explained in the README.

You can use a `launch.json` config like the above:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src",
            "userDataDir": "${workspaceRoot}/.chrome"
        }
    ]
}
```

**Comment by JoyalToTheWorld** [comment]
Thank you, I hadn't caught the 'userDataDir' setting, my apologies, that is what I was missing.
