### ISSUE TITLE
Attach to chrome not working when upgrade VS code to v1.10.2 

### ISSUE THREAD

**Issue by vkvarma** [Microsoft/vscode-chrome-debug#391]
- VS Code Version: 1.10.2

Steps to reproduce:

1. Upgrade the VS code to version 1.10.2 and chrome debugger extension to 2.7.1
2. As providing the breakpoint after running app to chrome remote debug mode 
   showing "Breakpoint ignored because generated code not found (source map problem?)."

**Comment by roblourens** [comment]
Nothing changed in 1.10.2. You can use the `.scripts` command to figure out what the problem is: https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command

**Comment by vkvarma** [comment]
when i run .scripts command into VS code debug console i get the below details :- 
› VM562
› http://localhost:3000/browser-sync/browser-sync-client.js?v=2.18.8

**Comment by roblourens** [comment]
If your code is eval()'d, then it's the first entry there (and has no sourcemaps). If not, it isn't loaded on the page, or you're attached to the wrong page.
