### ISSUE TITLE
pathMapping key must end in /

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode-chrome-debug#393]
I'm trying to attach debugger to chrome to a webserver that serves files with some prepended part to the URL, so that file:

`<workspaceRoot>/test/bar.js` (filesystem) becomes `http://host/base/bar.js?randomtoken` (webhost addr) so you can see that I'm trying to replace `/base` with `/test`.

According to docs I should do this with `pathMapping` config property.

I tried numerous configruations:

	"pathMapping": {
		"/": "${workspaceRoot}",
		"/base": "${workspaceRoot}/test"
	},

At some point I thought that asterix might be inlined somewhere? As it was reoccuring somewhere.

	"pathMapping": {
		"/": "${workspaceRoot}",
		"/base*": "${workspaceRoot}/test*"
	},

However it does not match `/base` prefix at all.

Full config available at [karma-and-vscode-debugging's launch.json file](https://github.com/mlewand/karma-and-vscode-debugging/blob/master/.vscode/launch.json).

Full steps to reproduce:

1. Clone repo.
1. Install deps.
1. Run `npm test` (runs a server).
1. Open project with VSCode `code .`.
1. Attach the debugger with `f5`.
1. Hit refresh to make karma re-run tests with `ctrl/cmd+r`.
1. Evaluate `.scripts` in your debugger console to see paths.

## Expected

Among dumped files, example.js being correctly mapped to `test` directory, like so:

```
› http://localhost:8080/base/example.js?51a5f49ea9a60b2b374e551ba2e49c94c476d5b7 (c:\foo\bar\karma-and-vscode-debugging\test\example.js)
```

## Actual

"base" not being replaced with "test".

```
› http://localhost:8080/base/example.js?51a5f49ea9a60b2b374e551ba2e49c94c476d5b7 (c:\foo\bar\karma-and-vscode-debugging\base\example.js)
```

I'm also inlcuding a log here: https://gist.github.com/mlewand/ba26a3eb6e23dfd811538588040c723d

**Comment by roblourens** [comment]
Thanks for the test repo and log. You're gonna hate me for this one! It only works if the pathMapping key ends in a slash. I can debug example.js with

```json
"pathMapping": {
	"/": "${workspaceRoot}",
	"/base/": "${workspaceRoot}/test/"
},
```

No good reason for that. I'll fix it.

**Comment by mlewand** [comment]
@roblourens I can confirm that it works when given tailing slash.

Not a good enough reason to hate you after providing such an useful plugin, so still lot of ❤! Thanks for quick turnaround.

BTW I tried to troubleshot it on my own and make a PR with fix, but I figured out I'm not proficient with TS.
