### ISSUE TITLE
Debug stop if open Developer tools in Chrome

### ISSUE THREAD

**Issue by nischi** [Microsoft/vscode-chrome-debug#396]
- VS Code Version: 1.10.2
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0
- Debugger for Chrome 2.7.2

Steps to reproduce:

1. Close Chrome
2. Click F5 in VSC to start Chrome with the Page
3. Debugging works
4. Click F12 in Chrome to open Dev-Tools

After that the Debugging in VSC stopps, so its not possible to debug in VSC and have open the Dev-Tools in Chrome. I need that for example inspect the elements.

**Comment by roblourens** [comment]
Yeah, it's not possible to use both at the same time, unfortunately. This is a limitation of Chrome.

**Comment by nischi** [comment]
Really? Whats the limitation and why is that?

**Comment by packetstracer** [comment]
Would be great to have both, because sometimes you need Network or other extensions such as React or Redux Dev Tools.

**Comment by nvmkpk** [comment]
I understand this is a limitation imposed by Chrome itself. Can this extension provide a quick way to reconnect?

**Comment by lerit** [comment]
yes,when debug,developer still want to see elements,networks and so on.i think the perfect solution is:when open chrome devtool,this extension exit debug,and sync all breakpoint to chrome debug(and break at extension break before).

**Comment by auchenberg** [comment]
This is now possible with Chrome Canary, and in the next Chrome 63 stable release, that should arrive in Nov. https://bugs.chromium.org/p/chromium/issues/detail?id=129539

**Comment by lerit** [comment]
@auchenberg ,thanks!
I'm going to pay attention to this release

**Comment by nischi** [comment]
oh that sounds fantastic.
