### ISSUE TITLE
Copy evaluated var to the clipboard

### ISSUE THREAD

**Issue by mlewand** [microsoft/vscode-chrome-debug#397]
This is an enhancement request.

I'd love to see a feature where I quickly copy variable's value into the (system/host) clipboard. I'd see it done exactly same way as it's in Chrome devtools, you could simply do `copy( myVar )` in console, and **if there's no collision** within current scope, it will put it into the clipboard.

For me as an end user it's extremely useful many times, just now I'm just copying some directory path, to paste it in file manager to see what's going on. Other cases often include copying json dumps of some state, and quickly putting it into a file etc.

I'm just curious to know whether you guys are interested in feature like that, if so I can try to put it together as a PR.

**Comment by roblourens** [comment]
Hm, typically copy/paste is handled by the vscode frontend using `document.execCommand` from the browser, but in this case, the debug adapter (just a node process) would have to write to the clipboard, which I'm not sure how to do. If you can figure out a good way to do it, I would take a PR.

**Comment by auchenberg** [comment]
@roblourens Since it's running in an electron context, could electron be required? 

```
const {clipboard} = require('electron')
clipboard.writeText('Example String')
```

**Comment by roblourens** [comment]
It isn't an electron context though, it's just a node process.

**Comment by mlewand** [comment]
https://github.com/sindresorhus/clipboardy looks to be an OK option, list of OSes looks good enough to consider it cross platform. I'll see how it fits the job, somewhat later this or next week. Thanks for clarifications!

**Comment by connor4312** [comment]
The [new debugger](https://github.com/microsoft/vscode-js-debug) (default since 1.47) supports `copy(expr)` in the console, as well as right click -> copy value in the Variables view.
