### ISSUE TITLE
Launch web server and debugger in one step

### ISSUE THREAD

**Issue by fafcrumb** [Microsoft/vscode-chrome-debug#398]
Hi!

I was wondering if there was an easy way to configure launch.json to start your webserver before
beginning the debug session (and skip that first step if the server is already running).

I tried to accomplish this with "preLaunchTask", but naturally this fails because it waits for your never-ending serve task to finish before starting the debug session.

Of course, I can always start my server, and then start debugging as 2 separate steps. But I crave to be more lazy!

Thank you!

**Comment by roblourens** [comment]
I think it should be possible with `preLaunchTask` but haven't looked at that in awhile. Is the serve task marked as `isBackground: true`?

**Comment by fafcrumb** [comment]
Yeah it is. I tried both with and without `isBackground: true`. Although without was kind of redundant.

**Comment by fafcrumb** [comment]
@roblourens do you have any other thoughts on what I can try?

**Comment by roblourens** [comment]
I'm not sure but you may need to fill out the problemWatcher in your task and include the beginsPattern and endsPattern under "watching". I think it will start debugging when it encounters the endsPattern. See the example at the end of this section - https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks

**Comment by fafcrumb** [comment]
That did the trick. Thank you! I was looking in the wrong repo though. There was a similar issue in the vscode repo. Closing this, since it's being addressed there.

**Comment by roblourens** [comment]
To cross-reference as much as possible, which issue is it in the vscode repo?

**Comment by fafcrumb** [comment]
Ah, sorry about that. Should've referenced. It's Microsoft/vscode#6209
