### ISSUE TITLE
${workspaceRoot} doesn't resolve properly

### ISSUE THREAD

**Issue by joshhidley** [Microsoft/vscode-chrome-debug#400]
vscode-chrome-debug version: 2.7.3
VS Code Version: Version 1.11.1 (1.11.1)
OS: OS X Sierra 10.12.4 (16E195)

Steps to reproduce:
1. Run the aspnetcore-spa yeoman script for Angular or the `dotnet new angular` template generator: (https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/)
2. Add a coreclr launch configuration using VS Code's Add Configuration button. Looks something like this (after modifying the `program` parameter properly):
```json
{
    "name": ".NET Core Launch (console)",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceRoot}/bin/Debug/netcoreapp1.1/AspnetcoreAngularSpike.dll",
    "args": [],
    "cwd": "${workspaceRoot}",
    "stopAtEntry": false,
    "console": "internalConsole",
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
},
```
4. Note: the `program` property assumes the proper project root.
5. Run coreclr launch configuration.

**What happens:** It works and if you mess with the "program" property, it doesn't work.

6. Add a chrome launch target using VS Code's Add Configuration button. It looks something like this:
```json
{
    "type": "chrome",
    "request": "launch",
    "name": "Launch Chrome",
    "url": "http://localhost:5000",
    "webRoot": "${workspaceRoot}"
},
```
7. Note the `webRoot` property.
8. Run the chrome launch configuration and try to break in a .ts file (e.g. counter.component.ts)

**What happens:** It doesn't hit the break point.

9. Run the `.scripts` command and note that the mapping for counter.component.ts is missing the project root. For example, it might look like this:
```
../.././ClientApp/app/components/counter/counter.component.ts (/Users/josh/ClientApp/app/components/counter/counter.component.ts)
```
10. Add the project root to the end of the chrome launch configuration's `webRoot` property:
```json
{
    "type": "chrome",
    "request": "launch",
    "name": "Launch Chrome",
    "url": "http://localhost:5000",
     "webRoot": "${workspaceRoot}/aspnetcore_angular_spike"
},
```
11. Run the chrome launch configuration again try to hit a break point.

**What happens:** It works.

12. Run the `.scripts` command it note the correct mappings. For example, this:
```
../.././ClientApp/app/components/counter/counter.component.ts (/Users/josh/aspnetcore_angular_spike/ClientApp/app/components/counter/counter.component.ts)
```

**What should happen:** It shouldn't require the project root folder to be appended to `${workspaceRoot}`.

What's strange is that it seems like `${workspaceRoot}` is expanding properly for the coreclr launch configurations, but not for the chrome one.

**Comment by roblourens** [comment]
`${workspaceRoot}` is expanded by VS Code in both cases and that probably isn't the issue. I haven't used that asp.net generator but it might be hosting the webserver from that `aspnetcore_angular_spike` folder which would explain this. Or, it's returning misleading urls/sourcemap paths for some reason.

**Comment by roblourens** [comment]
Most likely, the sourcemap paths aren't correct or don't match where the scripts are served from (like if they're moved after being built). `sourceMapPathOverrides` is another way to fix this on chrome-debug's end.
