### ISSUE TITLE
Invalid resolution of default rule `webpack:///./~/*`

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode-chrome-debug#401]
- VS Code Version: 1.11.1
- OS Version: Windows 10 x64

An example from `vscode-chrome-debug.txt`:

**Actual result:**
`SourceMap: mapping webpack:///./~/@angular/core/index.js => c:\Users\User\Documents\Dev\ng2-admin\~\@angular\core\index.js, via sourceMapPathOverrides entry - "webpack:///./*": "c:\Users\User\Documents\Dev\ng2-admin/*"`

**Expected result:**
`SourceMap: mapping webpack:///./~/@angular/core/index.js => c:\Users\User\Documents\Dev\ng2-admin\node_modules\@angular\core\index.js, via sourceMapPathOverrides entry - "webpack:///./~/*": "c:\Users\User\Documents\Dev\ng2-admin\node_modules\*"`

**Possible cause:**
Changing the implicit default "sourceMapPathOverrides" setting by moving rule `"webpack:///./~/*"` to the first position resolves the issue:
```javascript
"sourceMapPathOverrides": {
    "webpack:///./~/*": "${workspaceRoot}/node_modules/*", // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
    "webpack:///./*":   "${webRoot}/*",                    // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js",
    "webpack:///*":     "*",                               // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    "meteor://💻app/*": "${webRoot}/*"                    // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```
instead of the default:
```javascript
"sourceMapPathOverrides": {
    "webpack:///./*":   "${webRoot}/*",                    // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js",
    "webpack:///./~/*": "${workspaceRoot}/node_modules/*", // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
    "webpack:///*":     "*",                               // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    "meteor://💻app/*": "${webRoot}/*"                    // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```

Initial launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000/*",
      "runtimeArgs": [
        "--disable-web-security",
        "--user-data-dir",
        "--remote-debugging-port=9222"
      ],
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}"
    },
    {
      "name": "Attach to Chrome, with sourcemaps",
      "type": "chrome",
      "request": "attach",
      "url": "http://localhost:3000/*",
      "port": 9222,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}"
    }
  ]
}
```

**Comment by roblourens** [comment]
The `~` rule actually isn't applied by default at all. It should be, though.

**Comment by Deilan** [comment]
@roblourens It can also be helpful to indicate the correct order in the readme instead of the current.

**Comment by nojvek** [comment]
Just to add to this, webpack will won't add `~` by default in latest version but `node_modules`as it should be. This was a pretty awful design from the start, I'm glad they fixed it.

**Comment by roblourens** [comment]
Thanks for pointing that out!
