### ISSUE TITLE
Consider adding react snippets 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-chrome-debug#404]
Refs: https://github.com/Microsoft/vscode/issues/24403

It is not trivial to setup chrome debug for react, consider adding a react snippet to make this experience easier for users.

For reference here's my configuraiton

```
{
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*"
            }   
        }
```

**Comment by roblourens** [comment]
I have this, which will cause the sourcemap config to work out of box, so you won't need to set sourceMapPathOverrides: https://github.com/Microsoft/vscode-chrome-debug/issues/315

And userDataDir won't be necessary in the near future.
