### ISSUE TITLE
multiple /this/ presented at top of call stack

### ISSUE THREAD

**Issue by ashmsuhsl** [Microsoft/vscode-chrome-debug#405]
Environment: Windows 10
VSCode: 1.12.0-insider
Target: Electron

Screen-shot:

![this_002](https://cloud.githubusercontent.com/assets/11518065/24919064/5a0798e2-1eda-11e7-82e6-5dba4636ddf5.png)

Scenario: debugging Electron renderer process; breakpoint set in button event handler; positioned at top of call stack

At breakpoint,  /this/ is displayed as:

React child node (Material-UI AppBar) in VARIABLES/Local 
React child node (Material-UI AppBar) in mouse-over popup
React component class instance (MyApp) in WATCH 
React component class instance (MyApp) in DEBUG CONSOLE

/this/ is in fact the MyApp instance, and the app's behaviour is as intended.

As you can see from the screenshot, the event handler is a lambda assigned to an instance member of MyApp. If the useage is changed to this:

`
public render()
{
  ...
  const handle = this._handle.bind(this);
  ...
  onLeftIconButtonTouchTap={handle} 
  ...
}
`

then /this/ is shown consistently as MyApp instance in debug windows, editor, and console.

**Comment by roblourens** [comment]
There have been some issues with showing the correct 'this' value, like https://github.com/Microsoft/vscode/issues/23143, and it's probably just a limitation of Chrome since that info comes directly from Chrome.

Does Chrome DevTools show the same value?

**Comment by ashmsuhsl** [comment]
@roblourens I see what you mean. Here is what I see in Chrome DevTools:

React child node (Material-UI AppBar) in Local
React component class instance (MyApp) in mouse-over popup
React component class instance (MyApp) in Watch
React component class instance (MyApp) in Console

So, the same behaviour in three of the four views. As long as one is aware of this, it isn't a problem. 

Thank you for your help.

**Comment by roblourens** [comment]
Not much I can do, besides evaluating 'this' on every step, as suggested in Microsoft/vscode#23143
