### ISSUE TITLE
Is it possible to debug with chrome mobile?

### ISSUE THREAD

**Issue by isometriq** [Microsoft/vscode-chrome-debug#408]
Not sure if I can use this for chrome mobile (on Android)

- VS Code Version: 1.11.1

Steps to reproduce:

1. "address" set to phone ip address
2. "url" set to vscode host ip address
3. "port" set to 9222 ?

**Comment by roblourens** [comment]
I'm not sure. Try it and let me know :)

**Comment by auchenberg** [comment]
You can use `adb` to setup a port forwarding connection manually, and configure VS Code to use the right port. A bit complicated: https://developer.chrome.com/devtools/docs/remote-debugging-legacy

**Comment by isometriq** [comment]
@roblourens Nope, didn't work like i described
@auchenberg Ok good to know, i agree a bit complicated but not so bad since I already have to use `adb.exe reconnect` to debug from Chrome. Thanks, I'll let you know how it goes when I use it.

**Comment by auchenberg** [comment]
Let me know how it works, we might add something in the future for mobile devices.
