### ISSUE TITLE
Question:  Working example of e2e protractor debugging launch.js app for angular cli project?

### ISSUE THREAD

**Issue by daBishMan** [Microsoft/vscode-chrome-debug#410]
- VS Code Version:
1.11.1
Steps to reproduce:

1.  Create a new project using angular cli 1.0.0 angular 4
2.  Try to debug e2e test ?

Not sure where to start, help please?

**Comment by roblourens** [comment]
Using Karma? http://blog.mlewandowski.com/Debugging-Karma-tests-with-VSCode.html

**Comment by daBishMan** [comment]
I am looking for debugging protractor tests, 

Thanks for the link on Karma tests much appreciated.

**Comment by dubcdr** [comment]
I found this. But I get some undesired errors being thrown at the end of every run

[Blog Post](https://blogs.msdn.microsoft.com/wushuai/2016/08/24/debug-protractor-script-in-visual-studio-code/)
