### ISSUE TITLE
Diagnostics for Sourcemaps?

### ISSUE THREAD

**Issue by brentarias** [Microsoft/vscode-chrome-debug#411]
- VS Code Version: 1.11.2
 node: 6.5.2
Debugger for Chrome: 3.0.1 (also had same problem with 2.7.3 before upgrading)

I'm trying to debug an AngularJS (v1.5) app.  The Chrome debug extension launches my app, but no matter what I've tried, I'm told "Breakpoint ignored because generated code not found (source map problem?)."

I don't have a way to discover what paths Chrome is using, whether to find my sourcemap file, or to find the files within the sourcemap.  I noticed in [isssue 272](https://github.com/Microsoft/vscode-chrome-debug/issues/272) that "sourcemap diagnostics" were consulted to help resolve the issue.  I don't know where those diagnostics came from.  Does Chrome or VSCode have a means to reveal what paths it is attempting or using in relation to the sourcemap?  When I launch a debug session, there are no error messages in the "debug console" panel.

For my particular situation, I'm using Browsersync to serve the app and I'm using the following launch.json profile:

        {
            "name": "Launch Dashboard",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
        },  

From within my gulpfile, my Browsersync configuration is as follows:

    browserSync.init(['./wwwroot/**/**.**'], {
        server: {
            baseDir: ".",
            index: "wwwroot/master/js/dash.test.html"
        },
        port: 4000,
        notify: false,
    });

An app path overview, including the location of the sourcemap, is as follows:

 * myApp/ (this corresponds to ${workspaceRoot})
   * node_modules/
   * wwwroot/
      * master/
         - dashboard.js          (contains most angular app components, bundled.  Loaded from index.)
         - dashboard.js.map        
        * components/ (folder contents omitted for brevity)
        * js/
          - dash.test.html       (Index file.  Loads dashboard.js and dash.test.js)
          - dash.test.js            (contains the main angular application)

My sourcemap file contains the following JSON:

    {"version":3,"sources":[
            "node_modules/browser-pack/_prelude.js",
            "wwwroot/master/components/app.templates.js",
            "wwwroot/master/components/components.module.js",
            "wwwroot/master/components/dashboard/dashboard.component.js",
            "wwwroot/master/components/dashboard/dashboard.module.js",
            "wwwroot/master/components/dashboard/filters/dash-filters.component.js",
            "wwwroot/master/components/hello/hello.component.js",
            "wwwroot/master/components/hello/hello.module.js",
            "wwwroot/master/components/kpi/active-lines/active-lines.component.js",
            "wwwroot/master/components/kpi/active-lines/active-lines.module.js",
            "wwwroot/master/components/kpi/no-usage/no-usage.component.js",
            "wwwroot/master/components/kpi/no-usage/no-usage.module.js",
            "wwwroot/master/components/kpi/submitted-tickets/submitted-tickets.component.js",
            "wwwroot/master/components/kpi/submitted-tickets/submitted-tickets.module.js",
            "wwwroot/master/components/kpi/upgrade-eligible/upgrade-eligible.component.js",
            "wwwroot/master/components/kpi/upgrade-eligible/upgrade-eligible.module.js"
        ],
        "names":[], "mappings":".... ... ... ...

**Comment by roblourens** [comment]
I think that since the sources entries in the sourcemap are relative paths, they will be resolved relative to the script's path. The diagnostics you're looking for is the `.scripts` command: https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command

**Comment by brentarias** [comment]
Bam!  Thank you, problem solved!  In my case I was seeing a redundant "wwwroot\master\wwwroot\master" as seen here:

    - wwwroot/master/components/app.templates.js (c:\repos\dashboard\src\max.web\wwwroot\master\wwwroot\master\components\app.templates.js)
    - wwwroot/master/components/components.module.js (c:\repos\dashboard\src\max.web\wwwroot\master\wwwroot\master\components\components.module.js)

So I modified my launch.json to contain this:

    "sourceMapPathOverrides": {
        "wwwroot/master/*": "${webRoot}/wwwroot/master/*"
    }

**Comment by roblourens** [comment]
Perfect, glad you were able to solve it.
