### ISSUE TITLE
Add "inspect in VS Code" context menu item in Chrome via extension

### ISSUE THREAD

**Issue by ButuzGOL** [microsoft/vscode-chrome-debug#412]
In webstorm you can click on plugin and do "inspect in Webstorm" and you starting debugging immediately so this looks quite good especially when you working with several env in one time

**Comment by auchenberg** [comment]
Hi @ButuzGOL

Can you provide some screenshots or links to how WebStorm is working? Having hard time grasping how it works.

**Comment by ButuzGOL** [comment]
Here is video

![webstorm-debug-demo](https://cloud.githubusercontent.com/assets/196564/25185950/6176c44c-2527-11e7-9275-c12ff0a851af.gif)

Also in webstorm we dont need run chrome with debug port

**Comment by auchenberg** [comment]
Ah interesting. That requires you to have a Chrome extension installed. At this point in time we have decided to avoid requiring users to install extensions, as we find the experience cumbersome.

**Comment by firelizzard18** [comment]
It would be awesome if the VSCode team were to provide an extension that could do this, if the developer wanted it.

**Comment by ButuzGOL** [comment]
I think now everything fine with context menu and select url for debug only thing is help a lot is this issue #438

**Comment by iShawnWang** [comment]
Cool idea, and I am also struggling with another issues : 

when I use vscode-chrome-debug plugin and set debug configuration like 👍 

```
{
    "type": "chrome",
    "request": "launch",
    "name": "Launch Chrome",
    "url": "http://localhost:8080",
    "webRoot": "${workspaceRoot}"
}
```

Every time, run debug will create a new chrome instance without plugin enabled, and console output 
`Download the React DevTools and ...`. 

So I have to run `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222` to open a Chrome instance and using VSCode attach to it.

Any elegant way to do this ?

**Comment by auchenberg** [comment]
@iShawnWang We are starting a new instance of Chrome with a new user profile (to be able to run in parallel with other open Chrome instances), so my recommendation would be to start debugging from VS Code, and then install your chrome extensions while it's running, etc.

Alternative you can start Chrome with remote debugging enabled like you do, and use an attach config instead.

Also, please open new issues instead of reusing old ones ;)

**Comment by iShawnWang** [comment]
Sorry for reuse this issue, and thank you ~

# :D

**Comment by minkir014** [comment]
See this extension does this feature.
https://marketplace.visualstudio.com/items?itemName=codemooseus.vscode-devtools-for-chrome

**Comment by connor4312** [comment]
The Chrome APIs the Webstorm extension uses to do this have gone away since Chrome 86 and it no longer works; it's not possible for us to build such as extension.
