### ISSUE TITLE
Problems debugging angular cli e2e tests.

### ISSUE THREAD

**Issue by smithag77** [Microsoft/vscode-chrome-debug#413]
- VS Code Version: 1.11.2
- Node Version: 6.10.2

I am struggling to debug my end to end tests in my application.  My launcher does launch the tests, but I get the "Breakpoint ignored because generated code not found (source map problem?)" message on all of my breakpoints.

Furthermore, it hits an exception immediately on the first step saying that it's trying to navigate to an invalid URL.  This step works correctly when I just run the tests via 'ng e2e' instead of using the launcher.  This might just be an issue with my own tests, but I would like to understand why my breakpoints are ignored.
![image](https://cloud.githubusercontent.com/assets/5438417/25197514/fa145f20-2509-11e7-857e-add71bdf1d9a.png)

Any assistance is most welcome, as I am pretty new to this and have a sneaking suspicion that I don't know what I'm doing :).

**launch.json: (the relevant launcher is named "LaunchProtractor")**

> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Launch Chrome against localhost, with sourcemaps",
>             "type": "chrome",
>             "request": "launch",
>             "url": "http://localhost:4200",
>             "sourceMaps": true,
>             "trace": true,
>             "webRoot": "${workspaceRoot}",
>             "userDataDir": "${workspaceRoot}/.vscode/chrome"
>         },
>         {
>             "name": "Attach to Chrome, with sourcemaps",
>             "type": "chrome",
>             "request": "attach",
>             "port": 9222,
>             "sourceMaps": true,
>             "trace": true,
>             "webRoot": "${workspaceRoot}"
>         },
>         {
>             "name": "Attach Karma Chrome",
>             "type": "chrome",
>             "request": "attach",
>             "address": "localhost",
>             "port": 9333,
>             "pathMapping": {
>                 "/": "${workspaceRoot}",
>                 "/base/": "${workspaceRoot}/"
>             }
>         },
>         {
>             "name": "LaunchProtractor",
>             "type": "node",
>             "request": "launch",
>             "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
>             "stopOnEntry": false,
>             "args": [
>                 "${workspaceRoot}/protractor.conf.js"
>             ],
>             "cwd": "${workspaceRoot}",
>             "preLaunchTask": "",
>             "runtimeExecutable": null,
>             "runtimeArgs": [
>                 "--nolazy"
>             ],
>             "env": {
>                 "NODE_ENV": "development"
>             },
>             "console": "internalConsole",
>             "sourceMaps": true
>         }
>     ]
> }

**protractor.conf.js:**

> require('ts-node/register');
> require('reflect-metadata');
> 
> var glob = require('glob');
> var seleniumPath = './node_modules/gulp-protractor/node_modules/protractor/selenium/';
> var seleniumJarPath = '';
> 
> glob(seleniumPath + '*.jar',
>   function (err, files) {
>     seleniumJarPath = files[0];
>   });
> 
> exports.config = {
>   seleniumServerJar: seleniumJarPath,
> 
>   capabilities: {
> 
>     //'browserName': 'firefox'
>     'browserName': 'chrome', 'chromeOptions': { 'args': ['incognito', 'no-sandbox', 'disable-web-security'] }
>   },
> 
>   useAllAngular2AppRoots: true,
> 
>   framework: 'custom',
>   frameworkPath: require.resolve('protractor-cucumber-framework'),
> 
>   specs: [
>     'e2e/**/*.feature'
>     // 'e2e/**/inventory-attachments.feature'
>     // 'e2e/**/inventory-details.feature'
>     // 'e2e/**/inventory-find.feature'
>     // 'e2e/**/inventory-lookup.feature',
>     // 'e2e/**/inventory-update.feature'
>     // 'e2e/**/login.feature'
>     // 'e2e/**/logout.feature'
>   ],
> 
>   cucumberOpts: {
>     require: [
>       'e2e/**/*.steps.ts',
>       'protractor-env.js'
>     ],
>     format: 'pretty',
>     keepAlive: false,
>     strict: true
>   },
> 
>   directConnect: true,
> 
>   onPrepare: function () {
>     browser.ignoreSynchronization = true;
>   }
> };

**Comment by daBishMan** [comment]
I would be interested of solution for out of the box plain angular cli 1.0.0 project and debugging e2e tests.

**Comment by daBishMan** [comment]
@smithag77 did yo solve this issue, I am also having the same problem, I can debug the app, and the karma tests fine, but not e2e?

**Comment by RobotnickIsrael** [comment]
Did anyone managed to do it?
I can debug my server and client (ng serve), but not testing (ng test \ e2e).
Did you find and good configurations for the last angular-cli?
(i'm not working directly with webpack, nor have any desire to do so)

**Comment by auchenberg** [comment]
We added a guide on how to debug `ng e2e` tests here, https://github.com/weinand/vscode-recipes/tree/master/Angular-CLI#debug-end-to-end-tests
