### ISSUE TITLE
Exceptions from Chrome's internal extension script pollutes stack traces 

### ISSUE THREAD

**Issue by Deilan** [microsoft/vscode-chrome-debug#414]
- OS Version: Windows 8 x64
- VS Code Version: 1.11.2
- Debugger for Chrome Version: 3.0.1

Was playing around with debugging of code from [akveo/ng2-smart-table](https://github.com/akveo/ng2-smart-table) repo when the following error occured:
```
TypeError: Cannot read property 'Binding' of undefined
    at extensions::runtime:7:46
Error: "Natives disabled"
    at (anonymous) (extensions::webstore:7:22)
```

Occured right after the moment when I continued execution after a breakpoint hit.

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "smartStep": true,
            "userDataDir": "${workspaceRoot}/.vscode/chrome"
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "smartStep": true
        }
    ]
}
```
![binding error](https://cloud.githubusercontent.com/assets/4777512/25369349/ec8a23e0-298b-11e7-9dec-2f3880b2efdd.png)
![untitled](https://cloud.githubusercontent.com/assets/4777512/25370141/5af3e88e-2991-11e7-8e0e-e31035252c84.png)

**Comment by roblourens** [comment]
Appears to be coming from the Chrome extension runtime, or just a Chrome extension.

**Comment by Deilan** [comment]
@roblourens Ok. FYI it's on the latest public Chrome version: 58.0.3029.81.

**Comment by justin-romano** [comment]
yep. im getting this.
![image](https://user-images.githubusercontent.com/1707226/26960837-666c56b8-4d2e-11e7-84f0-0849815a5e9d.png)

**Comment by roblourens** [comment]
Also looks like a file injected by chrome devtools. If you can repro it consistently, you can see if it happens in chrome devtools as well.

**Comment by bflopez** [comment]
Any update on this issue?

**Comment by auchenberg** [comment]
@bflopez This seem to be caused by an extension used in Chrome. Can you try to disable your Chrome extensions?

**Comment by PeterFeicht** [comment]
This is most likely not caused by an extension. I got this error with a Chrome install I use for developing, nothing else (so basically the most virgin install you're gonna get).

**Comment by Elyx0** [comment]
Same here, fresh user no extensions 
```
Error: "Natives disabled"
    at (anonymous) (extensions::app:7:22)
TypeError: Cannot read property 'Binding' of undefined
    at extensions::runtime:7:46
Error: "Natives disabled"
    at (anonymous) (extensions::webstore:7:22)
```

**Comment by auchenberg** [comment]
Looks like it's coming from https://chromium.googlesource.com/chromium/chromium/+/ee59ff6107cb390a75a2cd4775c7fb57218d9755/chrome/renderer/resources/extensions/event.js?autodive=0%2F%2F%2F

@justin-romano @Deilan @Elyx0 Do you have the uncaught exceptions option enabled in Code?

<img width="310" alt="screen shot 2017-08-15 at 2 55 35 pm" src="https://user-images.githubusercontent.com/173559/29338393-d9e98c80-81c9-11e7-8ff8-3c52d43b6482.png">

@roblourens Could we automatically exclude stack frames coming from `extension://`

**Comment by roblourens** [comment]
I do that for `chrome-extension:.*`, could add `extensions::.*`

**Comment by auchenberg** [comment]
@roblourens I think that would be a good start.

**Comment by volei** [comment]
same here (while debugging material2 md-table copied from plunkr into angular-cli latest, table structure doesn't show yet)
