### ISSUE TITLE
Breakpoint pointer jumps at the ending of a method after step into

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode-chrome-debug#417]
- VS Code Version: 1.11.2
- OS Version: Windows 8.1 x64
- Debugger for Chrome version: 3.0.1
- Chrome version: 58.0.3029.81
- Environment: Angular 4 CLI
- Language: TypeScript 2.2

Set a breakpoint at the beginning of a method, stept into it from an outer method, and just right after rhat the breakpoint pointer (yellow arrow) aligned at the ending of the method:

![untitled](https://cloud.githubusercontent.com/assets/4777512/25469930/1845ac14-2b28-11e7-9452-7b63430facc2.png)

After one more step over the pointer jumps to the beginning of the method:

![untitled1](https://cloud.githubusercontent.com/assets/4777512/25469929/1843e2e4-2b28-11e7-87c3-6663081832b8.png)

**Comment by roblourens** [comment]
Probably https://github.com/Microsoft/vscode-chrome-debug-core/issues/112. An annoying bug.
