### ISSUE TITLE
webRoot have no effect

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/vscode-chrome-debug#418]
- VS Code Version: 1.11.2

Steps to reproduce:

1. Create the following launch.json:
```
{
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:8080/",
    "webRoot": "${workspaceRoot}"
}
```
2. No matter what the `webRoot` is the Chrome always starts in user folder (`/home/user`). Because of this `"url": "http://localhost:8080/index.html"` can't be found.

OS is Linux Mint 18.1 Cinnamon 64

**Comment by roblourens** [comment]
You have to provide your own web server, webRoot is to tell vs code how it's configured. the extension won't start a server for you.

**Comment by nikitablack** [comment]
Of course I started it - in home directory. And my expectations was that `webRoot` will change the root to specified one.

**Comment by roblourens** [comment]
It won't change it. It just tells the extension what it is.
