### ISSUE TITLE
sourceMapPathOverrides with .js? files

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode-chrome-debug#419]
Version 1.12.0-insider
Commit 48ae6e3027be560d45dd1ebfbe090d6ff77af7f0
Datum 2017-04-26T06:13:08.212Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Steps to reproduce:

1. My Folder Structure:
![image](https://cloud.githubusercontent.com/assets/5635709/25497091/b7868374-2b83-11e7-8968-4e848e03576a.png)

2. examples from .scripts:
![image](https://cloud.githubusercontent.com/assets/5635709/25497638/91de88a4-2b85-11e7-8365-eac13bfad627.png)
webpack:///./pages/profile.js?**aabd4a0** (c:\Users\Alessandro\Dev\Client\termin365\_next\dist\pages\profile.js)

Getting the famous: generated Code not found

3. My launch.json:

![image](https://cloud.githubusercontent.com/assets/5635709/25497448/e6d76606-2b84-11e7-8803-430a4a64a073.png)

Is the ?Questionmark and the chars after it causing the mapping to fail?
If yes, how to do it correctly?

The code after the ? is from the nextjs build. It changes after each build. See 
https://zeit.co/blog/next2#scalable-hmr-(hot-module-replacement)
https://zeit.co/blog/next2#a-smaller-build

**Comment by roblourens** [comment]
Seems you have `_next` instead of `.next`?

**Comment by chmartinez** [comment]
@pungggi Were you able to solve the issue? How you do it? I'm getting the same issue as well...

**Comment by auchenberg** [comment]
@pungggi @chmartinez Your source files are located in the `.next` folder, but your `webRoot` points to `_next`.  Update the `webRoot` path and you should be good to go.
