### ISSUE TITLE
Opening chrome developer tools kills the debug session

### ISSUE THREAD

**Issue by josiahbgrace** [Microsoft/vscode-chrome-debug#422]
- VS Code Version: 1.12 - insiders

Steps to reproduce:

1. Start a debug session connecting to chrome.
2. Open up the dev tools (probably to check props from react :) )
3. Session is killed for vscode

I seem to remember this not happening previously, but it might be intended behavior. If it is intended behavior, this would be an awesome enhancement. Especially for network requests and React devtools.

**Comment by auchenberg** [comment]
This is sadly a limitation in Chrome. See https://github.com/Microsoft/vscode-chrome-debug/issues/83

**Comment by roblourens** [comment]
This should actually be working now. Which OS?

**Comment by roblourens** [comment]
Oh sorry, yes the debug session should be killed. Chrome itself shouldn't die though.

**Comment by cvharris** [comment]
@josiahbgrace to get around this issue, I set `userDataDir` to `false` so it uses my default Chrome profile, and then use the Launch configuration. This will spin up a 2nd tab that I can use the Debugger, while in an original tab I can have dev tools. Best of both worlds! 🌎  🌏
