### ISSUE TITLE
sourceMapPathOverrides - bundle.js.map - not mapping correctly

### ISSUE THREAD

**Issue by georgebatalinski** [Microsoft/vscode-chrome-debug#424]
- VS Code Version:
V 1.12.1
Steps to reproduce:

1. Use bundle.js in dist folder

**Karma** 
  serves the file
    http://localhost:9998/base/components\planner\planner.service.spec.ts?baffc4d22c3a292a952373187c889effb6ea83d7

**My local filesystem**
c:\workspace\web\components\planner\planner.service.spec.ts
c:\workspace\web\dist\assets\bundle.map.js - here is where all the map stuff is - to compiled code

**launch.config** 
```
{
            "type": "chrome",
            "request": "attach",
            "trace": true,
            "name": "Attach Karma Chrome",
            "address": "localhost",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:///./~/*.map":   "${webRoot}/dist/assets/bundle.js.map"
            } 
        }
```

**Error**
trying to find a source map in the same directory 
  - ENOENT: no such file or directory, open 'c:\workspace\web\components\planner\planner.service.spec.ts.map'

**Comment by roblourens** [comment]
You need to use `sourceMapPathOverrides` for paths in the sourcemap, not the .js.map file itself. See examples in the readme and use the `.scripts` command to debug.

**Comment by georgebatalinski** [comment]
Thank you for the help on the weekend :)

**.scripts** 
the mapping seems correct 
- webpack:///./components\planner\planner.service.spec.ts (c:\workspace\web\components\planner\planner.service.spec.ts)

any other suggestions?

**Comment by auchenberg** [comment]
@georgebatalinski 

What's the symptom? Breakpoints not being hit or?
What errors do you see in your debug console?
