### ISSUE TITLE
Chrome attach: Breakpoint triggers only when set *after* page reload

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode-chrome-debug#427]
- VS Code Version: 1.12.1 (maxOS)
- Debugger for Chrome Version: 3.1.1

Steps to reproduce:

1. Use the standard "Attach" launch configuration.
2. Run Chrome using the standard `--remote-debugging-port=9222` command line option
3. ??? (Verify source maps are valid with `.scripts`)
4. Set a breakpoint in the code that occurs after a user interaction (e.g. click handler).
5. Reload the page from within VS Code
6. Interact with the page and verify that the breakpoint **doesn't** trigger.
7. Reload the page from within VS Code
8. Set the breakpoint from step 4 again. (Disable, then re-enable.)
9. Interact with the page and verify that the breakpoint **does** trigger.

**Comment by roblourens** [comment]
Can I see a project or code snippet that demonstrates this?
