### ISSUE TITLE
I have to refresh chrome three times before I stop at the break point

### ISSUE THREAD

**Issue by Akram-Hassan** [Microsoft/vscode-chrome-debug#428]
In this demo I HAVE TO REFRESH CHROME THREE TIMES BEFORE I CAN STOP AT THE BREAK POINT

I created a folder with three files 

This is my launch.json

![image](https://cloud.githubusercontent.com/assets/5043572/25854295/cf7249a0-34cf-11e7-9c2c-150c9d3c9cf0.png)

this is index.html

![image](https://cloud.githubusercontent.com/assets/5043572/25854350/f8e45b0c-34cf-11e7-90e2-2d1ded910c1b.png)

and this is the javascript file

![image](https://cloud.githubusercontent.com/assets/5043572/25854360/019ee9ce-34d0-11e7-8e06-db1c45f7e89b.png)

The same happens when I move the folder to my localhost  IIS with this configuration

     {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/vscdemo/index.html",
            "webRoot": "${workspaceRoot}/wwwroot"
        }

What am I missing?

**Comment by auchenberg** [comment]
Tracking as https://github.com/Microsoft/vscode-chrome-debug/issues/445
