### ISSUE TITLE
Is that a normal char? => 'meteor://💻app/*': '${webRoot}/*'

### ISSUE THREAD

**Issue by Lenny32** [Microsoft/vscode-chrome-debug#431]
Hello,

I do not know if it is an issue but I just found this icon (emoji?) in the code of the file chromeDebugAdapter.ts. 

I do not know..
Thanks for your great work over this project.
Long live .Net Core

**Comment by auchenberg** [comment]
Yup, added to support Meteor's crazy default sourcemaps. See https://github.com/Microsoft/vscode-chrome-debug/issues/183
