### ISSUE TITLE
Restart doesn't save files.

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-chrome-debug#432]
- VS Code Version: 1.12.2

Only saves files on debug session start. Not on Restart.

The same is true for Breakpoints. If I remove a breakpoint in runtime and then restrat - the "new" session will break on the nonexistent point. if I save the file manually before restarting - it would work as expected

**Comment by roblourens** [comment]
I don't quite understand, can you break it down in steps?

**Comment by Spown** [comment]
![](https://drive.google.com/uc?id=0B-OJBofmehO3UGs0a0dLbFFNZnc)

**Comment by roblourens** [comment]
Thanks, got it. I think it would make sense to save files on restart, same as we do on launch. This would be on vscode.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode#26844

**Comment by Spown** [comment]
I don't think it is VSC's fault. Other debuggers I use (node2, Firefox-debug) do save on restart.

**Comment by Spown** [comment]
I may be mistaking, but I also think chrome-debug was saving on restart some time ago (I don't use it very often...)

**Comment by roblourens** [comment]
Oh yeah, there is actually a difference here, because chrome-debug overrrides it to refresh the page. But I don't think the extension can do anything about this at the moment. Will add comments in the vscode issue.
