### ISSUE TITLE
Not able to launch but attach (electron + angular)

### ISSUE THREAD

**Issue by vishalbhardwaj26** [Microsoft/vscode-chrome-debug#433]
VS code : 1.2.2
debugger for chrome: 3.0.1

Issue:
I am trying debugging my electron app (+Angular2) using extension "debugger for chrome", but not able to launch the application, it keeps on saying -
   >Discovering targets via http://127.0.0.1:9222/json
   >HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222

But If I start the application using cmd with run time debugging arguments, and then change my configuration to attach, it worked surprisingly.

Launch configuartion , I am using
    {
            "type": "chrome",
            "request": "launch",
            "name": "SwitchDesignerAttach",
            "runtimeExecutable": "C:/Projects/Git Repo/TDP/switchmanager/src/SwitchDesigner/node_modules/.bin/electron.cmd",
            "runtimeArgs": [
                "C:/Projects/Git Repo/TDP/switchmanager/src/SwitchDesigner/dist/main.js",
                "--enable-logging",
                "--remote-debugging-port=9222"
            ],
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/src/SwitchDesigner/",
            "diagnosticLogging": true,
            "preLaunchTask": null
        }

Logs while launching:
Verbose logs are written to:
C:\Users\vbhardwa\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.1\vscode-chrome-debug.txt
OS: win32 ia32
Adapter node: v7.4.0 ia32
vscode-chrome-debug-core: 3.15.3
debugger-for-chrome: 3.0.1
spawn('C:/Projects/Git Repo/TDP/switchmanager/src/SwitchDesigner/node_modules/.bin/electron.cmd', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","C:/Projects/Git Repo/TDP/switchmanager/src/SwitchDesigner/dist/main.js","--enable-logging","--remote-debugging-port=9222"])
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222

Please Advise?

**Comment by roblourens** [comment]
There's a section of the readme with tips on this exact error, but I'd guess that electron is not actually in debug mode. Try moving the `--remote-debugging-port` option to be the first one.

**Comment by vishalbhardwaj26** [comment]
Thanks @roblourens  for quick suggestion, though still not working
 > Discovering targets via http://127.0.0.1:9222/json
 > HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222

spawn('C:/Projects/Git Repo/TDP/switchmanager/src/SwitchDesigner/node_modules/.bin/electron.cmd', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--remote-debugging-port=9222","C:/Projects/Git Repo/TDP/switchmanager/src/SwitchDesigner/dist/"])

I am wondering why there are so many arguments while launching , is that something hindering with launch because while launching from cmd I am giving only two arguments (dist folder and remote-debugging-port), which is working.

**Comment by roblourens** [comment]
Can you access http://localhost:9222/json in a browser after launching? If not, then it's not actually in debug mode for some reason.

And actually you shouldn't even need to specify remote-debugging-port yourself since it's added by the extension automatically for a launch config. Those other args are for chrome, but shouldn't have any negative impact for electron.

**Comment by vishalbhardwaj26** [comment]
Thanks for explaining on arguments.
Actually when I start debugging from vscode only, it does not launch my application and there is no response on "http://localhost:9222/json".  

But (alternative) when I start my application from cmd using commands
 > C:\Projects\Git Repo\TDP\switchmanager\src\SwitchDesigner\node_modules\.bin>electron.cmd "C:\Projects\Git Repo\TDP\switchmanager\src\SwitchDesigner\dist" "--remote-debugging-port=9222"

and then again I start debugging from vscode, it automatically attach with my running instance of application. This is working but two step process and I am not getting why it is not getting started in my first way.

attaching screenshot of vscode debugging window:

![capture1](https://cloud.githubusercontent.com/assets/15126782/26189434/4e353844-3bc2-11e7-8e6e-818950e6baff.JPG)

**Comment by greg9504** [comment]
> Actually when I start debugging from vscode only, it does not launch my application and there is no response on "http://localhost:9222/json".


try down grading Debugger for Chrome to 2.7.3, see following link for details:
https://github.com/Microsoft/vscode-chrome-debug/issues/407

**Comment by FrogTheFrog** [comment]
As far as I know, you can not debug Electron's main app itself via "Debugger for Chrome", but you can debug renderer that Electron creates. That's why you need to first launch Electron's main app which then lauches renderer. Then you need to attach "Debugger for Chrome" like you did before. Below is an example of how to simplify this process via launch configuration ("Debug Electron" worked before, but now it needs some sort of timeout):

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Main",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}/dist",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "runtimeArgs": [
                "--remote-debugging-port=9222"
            ],
            "program": "${workspaceRoot}/dist/main.bundle.js",
            "protocol": "inspector",
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ]
        },
        {
            "name": "Debug Renderer",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}/dist/renderer"
        }
    ],
    "compounds": [
        {
            "name": "Debug Electron",
            "configurations": [
                "Debug Main",
                "Debug Renderer"
            ]
        }
    ]
}
```

**Comment by auchenberg** [comment]
This might becaused by using an older version of Electron that doesn't support the Inspector protocol which our Chrome debugger requires.

Please see https://github.com/weinand/vscode-recipes/issues/10 on how to configure Code to attach to the main and renderer process.
