### ISSUE TITLE
Extraneous console windows when launching 

### ISSUE THREAD

**Issue by greg9504** [Microsoft/vscode-chrome-debug#436]
- VS Code Version:
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:20:36.315Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- Debugger for Chrome Version 
2.7.3 Windows.

I'm wondering why I see several console windows open up when I start a debug session via launch.  It is an Electron based application.  Below is the launch configuration, screen shot and log.  

Launch config:
```
       {
            "name": "Debug Dev Renderer Process",
            "type": "chrome",
            "request": "launch",
            "userDataDir": "${workspaceRoot}/.chrome",            
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "runtimeArgs": [
              "${workspaceRoot}/dist",
              "--enable-logging",
              "--remote-debugging-port=9222"
            ],
            "sourceMaps": true,     
            "trace": "verbose",       
            "webRoot": "${workspaceRoot}"
                
        }

```

In the screen shot you see VS Code in the background, then 4 console windows, one is a Node window, then 3 windows with the path to the electron.exe, then the window of main application being debugged.

![image](https://cloud.githubusercontent.com/assets/1952281/26426052/048b2fae-40a5-11e7-9896-70d80ab72768.png)

Every once in a while the extra windows are not displayed and I'll see some debug output in the Node console window.  I also experience times when certain break points are not hit (in initialization code) but other times they are.  I have a colleague who uses the same repository and does not see this behaviour. 
 Any ideas what could cause this?  
Thanks.

[vscode-chrome-debug.zip](https://github.com/Microsoft/vscode-chrome-debug/files/1027278/vscode-chrome-debug.zip)

**Comment by roblourens** [comment]
If you are launching a windows script, then I think you need a cmd window to host it. I'm not sure what could cause it to appear or not appear, maybe some windows setting. I'm not sure how to work around it, sorry.
