### ISSUE TITLE
Error: Set breakpoints request timed out

### ISSUE THREAD

**Issue by feoh** [Microsoft/vscode-chrome-debug#439]
```javascript
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (/Users/cpatti/.vscode/extensions/msjsdiag.debugger-for-chrome-3.1.2/node_modules/vscode-chrome-debug-core/out/src/utils.js:54:24)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

- VS Code Version: Version 1.12.2 (1.12.2)

- Chrome Version: Version 58.0.3029.110 (64-bit)

- Chrome Debugger Version: 3.1.2

Steps to reproduce:

1. Launch VS Code, open this project (I usually do so using 'code .' - https://github.com/feoh/BeginningJavaScript/tree/master/05-loops
2. Open tests.js
3. Click the green Play triangle in the debugging pane.

**Comment by roblourens** [comment]
Is this still an issue? I can hit breakpoints in test.js with no issues.

**Comment by richardkazuomiller** [comment]
I'm having this issue. My project looks like this

```
cli/
  run.js
lib/
  thing.js
```

I run `cli/run.js` on node v8.1.0. `run.js` uses `thing.js` using `require('../thing.js')`. If I have debuggers inside only `thing.js`, this happens. However, if I add debuggers to `run.js`, those debuggers *and* the debuggers in `thing.js` work.

**Comment by richardkazuomiller** [comment]
It appears that if I wrap my code in a `setTimeout` all my breakpoints get added. I think it's because my code is synchronous.

```
const Thing = require('../lib/thing')
new Thing().run()
// breakpoints in thing.js don't work
```

vs

```
const Thing = require('../lib/thing')
setTimeout(() => {
  new Thing().run()
},1000)
// breakpoints in thing.js work!
```

**Comment by auchenberg** [comment]
@richardkazuomiller Does your `Thing().run()` logic run page load? We currently don't support break-on-load (https://github.com/Microsoft/vscode-chrome-debug/issues/445), but you should be able to set your breakpoint, and simply refresh in Chrome.

**Comment by auchenberg** [comment]
@richardkazuomiller Ah. Are you having problems with Node code? Please open an issue at https://github.com/Microsoft/vscode-node-debug2/issues

**Comment by richardkazuomiller** [comment]
Sorry! I thought this issue was for the VSCode Node debugger. Should have read more carefully.
