### ISSUE TITLE
[Suggestion] Add property active tab

### ISSUE THREAD

**Issue by ButuzGOL** [Microsoft/vscode-chrome-debug#440]
Have a suggestion add option start with active tab by default

**Comment by roblourens** [comment]
Not sure what you mean, can you explain more?

**Comment by ButuzGOL** [comment]
Usually when i start debug i have context menu "what tab to debug" but usually its active tab so i think may be add property so it will start for active tab without context menu

**Comment by roblourens** [comment]
I don't have any way to find out what the active tab is unfortunately.
