### ISSUE TITLE
[Bug] Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by moisesrodriguez** [Microsoft/vscode-chrome-debug#442]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.8.0|
|EditorConfig|EditorConfig|0.9.3|
|vscode-docker|PeterJausovec|0.0.15|
|code-settings-sync|Shan|2.8.1|
|npm-intellisense|christian-kohler|1.3.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|gitlens|eamodio|3.6.1|
|HTMLHint|mkaufman|0.3.3|
|atom-keybindings|ms-vscode|2.0.1|
|jscs|ms-vscode|0.1.9|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-spotify|shyykoserhiy|2.0.0|
|Material-theme|zhuangtongfa|2.8.5|;

---

Steps to Reproduce:

1. Start Debugger
2. Throws the error `Debug adapter process has terminated unexpectedly`

Haven't changed anything in my launch.json, it just stopped working after one update. Saw this issue https://github.com/Microsoft/vscode-chrome-debug/issues/377 but the guy who opened the issue mentions that after updating to 2.7.0 it solved the problem. I'm on version 3.1.2

Wanted to set `"diagnosticLogging": true` but did not know where to set that, so didn't attach any diagnostics log

![screen shot 2017-06-08 at 9 04 34 pm](https://user-images.githubusercontent.com/3869040/26958060-3642edda-4c8e-11e7-9891-bf9c750aa8a5.png)

**Comment by roblourens** [comment]
Did it stop working when you updated to VS Code 1.13?

Can you try running with `"trace": true` in your launch config, then upload the log file from the path it prints at the top of the debug console?

**Comment by moisesrodriguez** [comment]
@roblourens Negative it had already happened before updating VS Code to 1.13. It happened when I updated Debugger for Chrome. Just occurred to me to uninstall Debugger for Chrome and install it again and now it's working. Same launch.json as the one you see above in the screenshot. My best guess is that something got corrupted when updating the extension. A fresh install did the trick for me. Didn't get to try to setting `"trace": true"`

**Comment by roblourens** [comment]
Ok, glad that worked. 👍
