### ISSUE TITLE
unable to step into a script which includes `/base/` in src path even with `pathMapping` set

### ISSUE THREAD

**Issue by ilovett** [Microsoft/vscode-chrome-debug#444]
Attempting to step into a jasmine stub, I receive:
 Unable to open 'jasmine.js': File not found (/Users/ilovett/Projects/my-project/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js).

```
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "attach",
      "name": "Attach to ChromeDebugging",
      "address": "localhost",
      "port": 9333,
      "diagnosticLogging": true,
      "trace": true,
      "pathMapping": {
        "/": "${workspaceRoot}/",
        "/base/": "${workspaceRoot}/"
      }
    }
  ]
}

```

**Comment by roblourens** [comment]
Is that the right path?

**Comment by ilovett** [comment]
here's the important piece from `.scripts`

```
› http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?916005cc407925f4764668d61d04888d59258f5d (/Users/ilovett/Projects/my-project/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js)
› http://localhost:9876/base/node_modules/karma-jasmine/lib/adapter.js?7a813cc290d592e664331c573a1a796192cdd1ad (/Users/ilovett/Projects/my-project/base/node_modules/karma-jasmine/lib/adapter.js)
› http://localhost:9876/base/node_modules/karma-jasmine/lib/boot.js?945a38bf4e45ad2770eb94868231905a04a0bd3e (/Users/ilovett/Projects/my-project/base/node_modules/karma-jasmine/lib/boot.js)
› http://localhost:9876/base/src/test.ts?25fdfd23a230f622d85d4798bb65271df3e0e12d (/Users/ilovett/Projects/my-project/base/src/test.ts)
````

The code all functions properly, if I step over it for example, however if I attempt to step into it, the src path in vscode is trying to open `/base/` which I would assume should be removed or match the `pathMapping` which should remove it?

**Comment by roblourens** [comment]
Oh I understand, thanks. 
Can you try running with `"trace": true`, then upload the log file from the path it prints at the top of the debug console?

**Comment by ilovett** [comment]
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1081921/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
It's weird that the log doesn't show a scriptParsed event for that jasmine script, despite getting a console log message from there.

It looks like you didn't hit a breakpoint or step into that file during the logged run. Can you do that and send the log? Basically just repro the issue as you described.

**Comment by ilovett** [comment]
After that I see the file is 28 MB -- can I send it to your email to keep it private?

**Comment by roblourens** [comment]
Sure

**Comment by roblourens** [comment]
Fixed by https://github.com/Microsoft/vscode-chrome-debug-core/commit/d7c3ea3f804e47a68ccf2deedaba18f31108d925 - thanks for the help in tracking it down!
