### ISSUE TITLE
breakpoints not hit when set, instead with debugger; instruction

### ISSUE THREAD

**Issue by m4ss1m0g** [Microsoft/vscode-chrome-debug#446]
- VS Code Version: 1.13.1

Steps to reproduce:

1. Scaffolding new Vue app (vue-cli) with webpack
2. npm run dev (webpack hot module)
3. set breakpoint
4. execute code, nothing append
5. under the breakpoint in the code add `debugger;`
6. execute and the debugger; is hitted

Launch.json

```
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "sourceMaps": true,
            "trace": true,
            "webRoot": "${workspaceRoot}"
}
```

[Log](https://github.com/Microsoft/vscode-chrome-debug/files/1094200/Log.zip)

**Comment by arecvlohe** [comment]
I have the same issue with a React application. Only breaks when debugger statement is used.

**Comment by auchenberg** [comment]
We currently have an open issue with VueJS, due the way Vue generates it's sourcemaps. See https://github.com/Microsoft/vscode-chrome-debug/issues/430

**Comment by roblourens** [comment]
Let's continue the discussion in the other issue.
