### ISSUE TITLE
"trace": true, does not produce output FILE when "type": "node"

### ISSUE THREAD

**Issue by greg9504** [Microsoft/vscode-chrome-debug#449]
- VS Code Version:

> Version 1.13.1
> Commit 379d2efb5539b09112c793d3d9a413017d736f89
> Date 2017-06-14T18:21:47.485Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

- Debugger for Chrome Version:
3.1.6

While trying to figure out why my breakpoints were not being hit I set "trace": true for a "type": "node", I see extra logging in the debug console but no file is produced in %USERPROFILE%\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.6.  If I start a session with "type": "chrome" and  "trace": true I do get a file written.

Complete launch file attached.  I get the file for the Debug Renderer Process configuration but not the Debug Main Process configuration.  It's not a big problem, just seems inconsistent. 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Main Process",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}/",
            "trace": true,
            "sourceMaps": true,
            //"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            // Use the following for Windows
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "program": "${workspaceRoot}/dist/index.js",
            "protocol": "legacy"
        },
        {
            "name": "Debug Renderer Process",
            "type": "chrome",
            "request": "launch",
            "trace": true,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "runtimeArgs": [
                "${workspaceRoot}/dist",
                "--enable-logging",
                "--remote-debugging-port=9222"
            ],
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

**Comment by roblourens** [comment]
That's because you're debugging with node-debug, not this extension :)
