### ISSUE TITLE
Odd source map problem, can debug Renderer but not Main

### ISSUE THREAD

**Issue by greg9504** [Microsoft/vscode-chrome-debug#450]
- VS Code Version:

> Version 1.13.1
> Commit 379d2efb5539b09112c793d3d9a413017d736f89
> Date 2017-06-14T18:21:47.485Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

When I attempt to debug a main process of an Electron app that was built with webpack with the Debugger for Chrome extension it can't seem to find the source files, even though the trace log shows that the mapping was found.  I am unable to set breakpoints.  This is the error shown in the log:

```
20820: setBreakPointsRequest: {"path":"d:\\devtools\\js\\tutorials\\aeds_clean\\src\\electron\\index.ts","name":"index.ts"} [{"line":33}]
20820: _updateBreakpoints: result [{"verified":false,"message":"Breakpoint ignored because generated code not found (source map problem?)."}]

```
However earlier in the log I see this:
```
20820: _findSourceMapUrl: source map url found at end of generated file 'd:/devtools/js/tutorials/aeds_clean/dist/index.js'
...
20820: _registerSourceMap: webpack:///src/electron/index.ts -> d:/devtools/js/tutorials/aeds_clean/dist/index.js
```
which seems to suggest that the correct mapping has been found.

Executing the .scripts command results in:
```
.scripts
invalid expression: unexpected token .
```

This is my launch configuration, Debug Main Process:
```
      {
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Main Process",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}/dist",
            "trace": true,
            "sourceMaps": true,
            //"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            // Use the following for Windows
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "program": "${workspaceRoot}/dist/index.js",
            "protocol": "legacy"
        },
        {
            "name": "Debug Renderer Process",
            "type": "chrome",
            "request": "launch",
            "trace": true,
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "runtimeArgs": [
                "${workspaceRoot}/dist",
                "--enable-logging",
                "--remote-debugging-port=9222"
            ],
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

I swear this used to work.  However I tried downgrading the extension to 2.7.3 but ran into the same problem.   

What is a bit confusing is that I can debug the Renderer process no problem, breakpoints set in .ts files are hit.  I've attached the trace logs for both situations and the .script output for the renderer.

[sourcemapsproblem2.zip](https://github.com/Microsoft/vscode-chrome-debug/files/1112582/sourcemapsproblem2.zip)

**Comment by roblourens** [comment]
Your problem is with https://github.com/microsoft/vscode-node-debug, can you file the issue there?

**Comment by greg9504** [comment]
Oops,  sorry.  Yes I will thanks.
