### ISSUE TITLE
preLaunchTask does not get called on restart 

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#451]
preLaunchTask does not get called on restart whereas it does with node and other debuggers.
Steps to reproduce:
1. setup launch.json chrome debugger with a prelaunchtask
2. When normal launch happens the prelaunch task is executed as expected
3. Use Ctrl+Shift+F5 to restart. The browser is refreshed but the prelaunch task is not run.

Expected:
prelaunchtask:"taskname" should be completed prior to refreshing the browser.

**Comment by auchenberg** [comment]
Would you expect`prelaunchtask` to run on every page refresh? Also when invoked from Chrome itself?

**Comment by justin-romano** [comment]
if the context of what is a launch. For intents and purposes it is a restart of chrome as far as my build goes. i have changed code and need to do something before the browser reloads it. So yes.

**Comment by roblourens** [comment]
Will continue this in https://github.com/Microsoft/vscode/issues/28979
