### ISSUE TITLE
Specify custom port for web server

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-chrome-debug#452]
I don't want to use port 80, I want port 8001 just for that project (otherwise my autocomplete starts to get weird). How do I easily achieve this?

**Comment by auchenberg** [comment]
For launch you can use the `url` to set which url you want Chrome to launch.

Ex:
```json
        {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8001/",
            "webRoot": "${workspaceRoot}/src"
        },
```

**Comment by jpike88** [comment]
Yeah sorry I thought this would have a built in server... disregard
