### ISSUE TITLE
Package with built-in web server

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-chrome-debug#453]
Chrome version: Version 59.0.3071.115 (Official Build) (64-bit)
On macOS Sierra 10.12.5

Tried the default configurations, no luck. Looks like the web server doesn't even launch in the background... turning on 'trace' doesn't dump any log files either.

![screen shot 2017-07-07 at 12 42 22 pm](https://user-images.githubusercontent.com/9585787/27944553-d1bc3c1e-6311-11e7-8b33-fe8f6de63c0d.png)

**Comment by jpike88** [comment]
... wait... wouldn't it make sense to package this with a web server as well?!

**Comment by roblourens** [comment]
Users have tended to expect it, although I always assumed that they would have some other dev setup already.

**Comment by jpike88** [comment]
Yeah I had one already... but definitely had the expectation as you said. Probably worth putting in bold In the readme some sort of disclaimer!

**Comment by auchenberg** [comment]
VS Code doesn't provide a web-server. It's an editor, and our debugger is a debugger. If you don't load your files via `file://` you'll need to run your own web server. 

Tasks might be able to help you, https://code.visualstudio.com/docs/editor/tasks

**Comment by jpike88** [comment]
I am aware of all that as I've said, but there will be more people who come in like I did and expect what I expected. It's probably a good idea to mention that at the top of the readme to prevent any more confusion.

**Comment by roblourens** [comment]
Since this keeps coming up, I would actually consider packaging a webserver. I'll leave it open to consider it.

**Comment by auchenberg** [comment]
We shouldn't as it opens a slippery slope of the responsibility of the debugger. Should the web server support transpiling? What are the folder structure, etc? 

Launching of external components fits under "tasks", and should be handled outside of VS Code.

To @jpike88's point, then we should update the documentation to make it more clear that a local web-server is expected.

**Comment by auchenberg** [comment]
Added in https://github.com/Microsoft/vscode-chrome-debug/commit/e3823e8163c10859a3d850f27a7b51e10015e604
