### ISSUE TITLE
create-react-app no longer working out of box

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#454]
Running my demo app [Timey](https://github.com/auchenberg/timey), which is based on create-react-app doesn't no longer work with the default launch config. The debugger worked about a month ago. No changes has bee made to the app.

```
{
    "type": "chrome",
    "request": "launch",
    "name": "Chrome",
    "url": "http://localhost:3000",
    "webRoot": "${workspaceRoot}/client"
}
```

It seems like create-react-app is putting static assets under the magic `.` folder, while JavaScript files are under the correct path in the sourcemap:

```json
    - webpack:///src/clock/clock.js (src/clock/clock.js)
    - webpack:///./src/clock/clock.css?0738 (/Users/auchenberg/development/timey/client/src/clock/clock.css)
    - webpack:///./src/clock/clock.css (/Users/auchenberg/development/timey/client/src/clock/clock.css)
```

Notice the lack of webRoot in JavaScript paths. The default sourceMapPathOverrides seems to confuse the correctly generated paths in the map.

**Temp fix**
If I make a specific override for the `src` folder JavaScript files are mapped correctly.

```
"sourceMapPathOverrides": {
    "webpack:///./*": "${webRoot}/*",
    "webpack:///src/*": "${webRoot}/src/*"
},
```

**Correctly mapped paths**
```
  - webpack:///src/clock/clock.js (/Users/auchenberg/development/timey/client/src/clock/clock.js)
  - webpack:///./src/clock/clock.css?0738 (/Users/auchenberg/development/timey/client/src/clock/clock.css)
   - webpack:///./src/clock/clock.css (/Users/auchenberg/development/timey/client/src/clock/clock.css)
```

@roblourens Have we changed some default mapping logic recently?

**Comment by roblourens** [comment]
Is it getting a newer version of some dependency? This breaks the assumptions of the default sourcemap overrides - `  - webpack:///src/clock/clock.js (/Users/auchenberg/development/timey/client/src/clock/clock.js)`

because one of the default rules is `'webpack:///src/*': '${webRoot}/*'` (which maps to files not in a src folder) but in this case you want `'webpack:///*': '*'`. I thought I had added that for create-react-app, but I can't remember for sure.

**Comment by auchenberg** [comment]
No change in `create-react-app` version, only change is the version of VS Code and Chrome debugger.

Given that `src/clock/clock.js` is part of the sourcemap and `"webRoot": "${workspaceRoot}/client"` shouldn't the correct path be composed to `/Users/auchenberg/development/timey/client/` + `src/clock/clock.js` automaticlly as the `webpack://` prefix is stripped out? This seems like a potentiel regression to me.

**Comment by auchenberg** [comment]
Upgraded to newest version of `create-react-app` `1.0.10` and problem went away. 

Launch.json
```
    {
      "type": "chrome",
      "request": "launch",
      "name": "Chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/client"
    }
```
