### ISSUE TITLE
pickProcess UI is shown instead of the first target being chosen if url param is removed 

### ISSUE THREAD

**Issue by kwonoj** [Microsoft/vscode-chrome-debug#455]
I'm trying to setup compound configuration for latest electron and attach its renderer process once main process starts. I'm keep getting `ECONNREFUSED`, which seems by compound launch configuration immediately starts task and doesn't wait until main process boots up - is there way to tell `attach` task wait for some time, or either for wait for specific processes?

- VS Code Version:
latest

Steps to reproduce:

1. launch compound config `Hybrid`
```
"configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "args": [
        "${workspaceRoot}/main.js",
        "--remote-debugging-port=9333"
      ],
      "protocol": "inspector"
    },
    {
      "name": "Electron Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9333,
      "webRoot": "${workspaceRoot}"
    }
  ],
  "compounds": [
    {
      "name": "Hybrid",
      "configurations": [
        "Electron Main",
        "Electron Renderer"
      ]
    }
  ]
```

2. If manually trigger configurations subsequently (`Electron Main` first, then `Electron Renderer`) `attach` task can attach into process but compound task will fail with ECONNREFUSED

**Comment by auchenberg** [comment]
You can use the 'timeout' properly to increase the 'timeout' for the
renderer config?

**Comment by kwonoj** [comment]
I did try `timeout`, but connection attempt itself seems triggered immediately regardless of timeout (I get ECONNREFUSED immediately as soon as compound task starts). I was under assumption timeout would work as you've mentioned too. It maybe my misconfiguration still.

**Comment by auchenberg** [comment]
@kwonoj I just gave your config a try, and it seems that you are trying to connect to the Electron Main process using `"protocol": "inspector"`, which is the reason you get `ECONNREFUSED` right away, as Electron hasn't yet switched to the "inspector protocol".

Try to change to `"protocol": "legacy"` for the main process.

**Comment by kwonoj** [comment]
@auchenberg I intended set it to inspector for main proc, using latest electron which support those protocol. Once those task starts, node debug connects it via remote protocol. 

So is this means chrome debugger immediately try to connect main process of Electron and ignore `--remote-debug-port` configuration? node debug's `inspector` protocol assigns different port number automatically into main process, which is not expected chrome debugger (specifed 9333 in above config) to connect into.

**Comment by kwonoj** [comment]
and also, if that's case shouldn't non-compound task also not working?

**Comment by auchenberg** [comment]
I see. I just pulled https://github.com/electron/electron-quick-start and upgraded electron to `"~1.7.4"`, using the following configuration with 2x node debuggers makes the composite configuration work.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "args": ["${workspaceRoot}/main.js", "--remote-debugging-port=9333"],
      "protocol": "inspector"
    },
    {
      "name": "Electron Renderer",
      "type": "node",
      "request": "attach",
      "port": 9333,
      "protocol": "inspector",
      "webRoot": "${workspaceRoot}",
      "trace": "verbose"
    }
  ],
  "compounds": [
    {
      "name": "Hybrid",
      "configurations": ["Electron Main", "Electron Renderer"]
    }
  ]
}
```

Looks like we have an issue with the Chrome debugger.

**Comment by kwonoj** [comment]
Oh wow that was trick? Thanks, I'll give it a try on my end too. 🙇  (I'll close issue myself once after)

**Comment by kwonoj** [comment]
So giving it a try, specifying renderer to use node debug seems do the trick to attach process correctly but it loses debugability like breakpoint, etcs to renderer side code. Not sure what causes this though. If chrome debugger can attach process directly it'd be best way. 

Feel freely close issues at the moment, if you think chrome debugger side has issue to be looked into it'd be appreciate to track it.

**Comment by roblourens** [comment]
Hm, I'm not sure what would be different between node/chrome for this case. I'll try it out.

There are some differences between node and chrome that might cause it to not work for debugging the renderer process, so really I should figure out why it isn't working in your case.

**Comment by auchenberg** [comment]
@kwonoj I'm able to break fine in the render process in https://github.com/electron/electron-quick-start using the config from https://github.com/Microsoft/vscode-chrome-debug/issues/455#issuecomment-315473729

Is your render files located in sub-folder or similar? Maybe the `webRoot` needs to be updated. Try running the `.scripts` command in the debug console to see how files has been mapped. 

@roblourens The issue for the Chrome debugger seems to be the lack of a `url`, which causes the Debugger to fail to attach, as there's no valid target to attach too. The node debugger seem to attach to the first available target? Could Chrome be the same, if no URL is provided?

**Comment by roblourens** [comment]
It should do the same, 'url' is optional and only to disambiguate targets. I thought the problem involved it not waiting and respecting the timeout.

**Comment by auchenberg** [comment]
@roblourens When attaching manually to first "Electron Main" and then `Electron Renderer" with the following config, the "pickProcess" UI is shown instead of the first target being chosen. I suspect this could be the reason for why the Chrome debugger doesn't wait when used as a composite 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "args": ["${workspaceRoot}/main.js", "--remote-debugging-port=9333"],
      "protocol": "inspector"
    },
    {
      "name": "Electron Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9333,
      "webRoot": "${workspaceRoot}"
    }
  ],
  "compounds": [
    {
      "name": "Hybrid",
      "configurations": ["Electron Main", "Electron Renderer"]
    }
  ]
}
```

![screen shot 2017-07-16 at 7 27 08 pm](https://user-images.githubusercontent.com/173559/28253909-049e9a1c-6a5d-11e7-902e-92fbef19a1e1.png)

Demo: https://github.com/auchenberg/electron-quick-start-vscode

**Comment by roblourens** [comment]
You're seeing that popup I guess because you have the redux devtools installed - I don't get it. I debugged it and it is related to the timeout, which I apparently broke for 'attach'. Although the popup is still related because I think it broke when I implemented that.

**Comment by auchenberg** [comment]
Interesting. I don't have Redux/React DevTools installed, but I do have Adblock installed, which seem to installed a new DevTools tap. Looks like our "pickProcess" logic might be broken?

**Comment by roblourens** [comment]
I think this should be ok now - someone let me know if I need to reopen.
