### ISSUE TITLE
Webpack: Promise.reject while attempting hot module replacement in debug session

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode-chrome-debug#458]
- VS Code Version:
Version 1.15.0-insider (1.15.0-insider)
Mac OSX Sierra latest

Steps to reproduce:

1. npm install -g create-react-app
2. create-react-app my-app
3. cd my-app/
4. npm start in console
5. Change launch.json to "url": "http://localhost:3000"
6. Start debugging
7. Make a change. Wait for hot module replacement
8. Will except in a module named "bootstrap + arbitrary number"

```
Error: Aborted because ./src/App.js is not accepted
Update propagation: ./src/App.js -> ./src/index.js -> 0
    at hotApply (http://localhost:3000/static/js/bundle.js:430:30)
    at hotUpdateDownloaded (http://localhost:3000/static/js/bundle.js:283:13)
    at hotAddUpdateChunk (http://localhost:3000/static/js/bundle.js:263:13)
    at webpackHotUpdateCallback (http://localhost:3000/static/js/bundle.js:8:12)
    at http://localhost:3000/0.4f2a9fafafda0bf7f01e.hot-update.js:1:1

```
Doesn't happen with direct Chrome Debugging

**Comment by auchenberg** [comment]
This seems to be an error coming directly from WebPack and not Code.

What's the specific change are making, and what's your version of `create-react-app`?

**Comment by auchenberg** [comment]
Just tried to reproduce and I do indeed see an internal Webpack/HMR exception when the debugger is attached. Not seeing anything in Chrome Devtools.

@roblourens This is an interesting one.

**Comment by auchenberg** [comment]
@neilyoung As a temp solution you can disable stopping on uncaught exceptions in VS Code:

<img width="317" alt="screen shot 2017-07-16 at 4 37 05 pm" src="https://user-images.githubusercontent.com/173559/28252302-1bf2b40e-6a45-11e7-805c-87eb8ac6f3b6.png">

**Comment by auchenberg** [comment]
This is by design, as WebPack is throwing a uncaught exception. When VS Code or Chrome DevTools is configured to break on uncaught exceptions it's shown. The solution is as mentioned in https://github.com/Microsoft/vscode-chrome-debug/issues/458#issuecomment-315646279 to simply disable the feature.

**Chrome DevTools:**
<img width="1347" alt="screen shot 2017-07-16 at 4 42 19 pm" src="https://user-images.githubusercontent.com/173559/28252340-ec5279a4-6a45-11e7-87bc-1fe732b03352.png">

**Comment by auchenberg** [comment]
The underlaying issue in Webpack is being tracked here https://github.com/webpack/webpack/issues/5175

**Comment by neilyoung** [comment]
@auchenberg Thanks

**Comment by engmyahya** [comment]
try this ,may help  [https://github.com/webpack/webpack/issues/5175#issuecomment-352999475](url)
