### ISSUE TITLE
Sourcemaps can't be fetched via file:// protocol

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode-chrome-debug#460]
- VS Code Version: 1.14 windows

Steps to reproduce: I created this repo :https://github.com/Alphapage/sourcemapsexample

Hello,

When trying to debug my babel code with vscode, I wasn't able to get the sourcemap for debugger;.
I didn't know if it was babel, my code or vscode chrome debug, so I created a repo to compare and the problem comes from vscode.
I added some quick instructions to compare both.

It seems to that vscode-node-debug, vscode-node-debug2 aren't able to apply the sourcemaps too.
Is it a global vscode debug problem ?

Thank you in advance for your help.

**Comment by auchenberg** [comment]
Our debugger works supports sourcemaps, when they are generated correctly.

What are the specific problem you have? debugger-statements not breaking in the sourcemapped code?

**Comment by Alphapage** [comment]
You can check the repo I created to illustrate my problem.
`node express.js` will generate the code and sourcemaps, then starts the server on port 3000.
`localhost:3000` from chrome devtools will handle sourcemaps correctly, but vscode-chrome-debug fails to find the sourcemap and display the transpiled instead.

**Comment by Alphapage** [comment]
I tested with inline sourcemaps too and vscode-chrome-debug doesn't behave like chrome devtools: the mapped sourcecontent is not used.

**Comment by Alphapage** [comment]
I use nodejs v6.3 for info: is it the problem ?

**Comment by rs3d** [comment]
I have also this issue:
`//# sourceMappingURL=core.js.js.map` is referenced by `/dist/core.js`
Both files are in the same folder so chrome is resolving the map path relative to the js file. But vscode-chrome-debug can't find the sourcemaps. Maybe it isn't `"sourceRoot":"/app"` following correctly?

**Comment by rs3d** [comment]
After further inspection to make it work i need to `
      "sourceMapPathOverrides": {
        "/app/*": "${workspaceRoot}/app/*"
      }`

**Comment by auchenberg** [comment]
Fetching the sourcemap from ``file://`` seem to be the error

```
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"605","url":"file:////Users/auchenberg/development/sourcemapsexample/virtual.js","startLine":0,"startColumn":0,"endLine":30,"endColumn":2,"executionContextId":1,"hash":"ADBA59912D739E656D1F59724D090E5422190FE2","isLiveEdit":false,"sourceMapURL":"file:////Users/auchenberg/development/sourcemapsexample/virtual.js.map","hasSourceURL":true}}
SourceMaps.getMapForGeneratedPath: Finding SourceMap for file:////Users/auchenberg/development/sourcemapsexample/virtual.js by URI: file:////Users/auchenberg/development/sourcemapsexample/virtual.js.map
SourceMaps.loadSourceMapContents: Downloading sourcemap file from file:////Users/auchenberg/development/sourcemapsexample/virtual.js.map
To client: {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":573,"source":{"name":"virtual.js","path":"file:////Users/auchenberg/development/sourcemapsexample/virtual.js","sourceReference":1573,"origin":"read-only core module"}}}}
SourceMaps.loadSourceMapContents: Could not download sourcemap from file:////Users/auchenberg/development/sourcemapsexample/virtual.js.map
```

**Comment by auchenberg** [comment]
Also you don't seem you write the transpiled file to the filesystem, which causes our  Code to fail, as we work of the filesystem. If you persist the file and remove the hardcoded `file://` url prefixes, then things work as expected.

**Comment by Alphapage** [comment]
This is the behaviour: I don't want to pollute the file system! 
And the debugger can work with virtual links.
I hope my pull request https://github.com/Microsoft/vscode-chrome-debug-core/pull/221 could solve the problem, but it only works with node-debug2 for now.
