### ISSUE TITLE
Debugging doesn't seem to work Angular @ViewChild

### ISSUE THREAD

**Issue by Chippi** [Microsoft/vscode-chrome-debug#461]
- VS Code Version: 1.14.1

Steps to reproduce:

1. 
Bind ViewChild to a HTMLElement

```
// html
<div #test></div>

// ts
@ViewChild('test') testElement: ElementRef;
```

2. No values show up during debug

**Comment by auchenberg** [comment]
@Chippi Can you provide more information about your setup, build system and your `launch.json` ?

**Comment by Chippi** [comment]
@auchenberg 

Project information:
angular-cli - 1.1.2

Build system:
Windows 10

Launch.json
```
{
  "name": "Launch Chrome with ng serve",
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:4200/#",
   "webRoot": "${workspaceRoot}"
}
```

**Comment by auchenberg** [comment]
@Chippi Thanks. Can you elaborate on the steps you are doing to reproduce? Do you have a source file or similar? What line are you setting a breakpoint in, and what values are missing?

**Comment by Chippi** [comment]
@auchenberg The reason why it didn't work was because I tried to debug an element before the angular AfterViewInit lifecycle state. It works great now though. Sorry for wasting your time, please close this issue. 

Thank you, /chipp
