### ISSUE TITLE
Querystrings with no key-value in scripts paths causes debugger to fail.

### ISSUE THREAD

**Issue by prasannajit** [Microsoft/vscode-chrome-debug#462]
- VS Code Version: 1.14.1

I am using chrome debugger extension in Visual Studio code to debug my backbone application. The launch.json file is like this;

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "https://localhost:3000/authenticate/app/110020/"
            "webRoot": "D:/Apps/app",
            "sourceMaps": false,
            "trace": "verbose"
        }
    ]
}
When i am trying to put a breakpoint in the app.js file which is present in "D:/Apps/app" directory, the following error is displayed, "Breakpoint ignored because target path not found".

Executed .scripts command in the debug console; i can see the urls but no mapping to disk file.
› https://localhost:3000/authenticate/app/110020/src/js/app.js

**Comment by auchenberg** [comment]
@prasannajit Are you transpiling your code? You have disabled sourcemaps which is needed if you transpile your code with Babel or TypeScript.

Also try updating your `webRoot` to use a relative path such as `"webRoot": "${workspaceRoot}/app",`

**Comment by prasannajit** [comment]
@auchenberg I am combining multiple js files to single js file, but I am not minifying them. And the webroot path is the path of the combined js file. I am trying to debug the combined js file. Thats the reason I have disabled sourcemap.
I tried using a relative path as you have suggested ,
"webRoot": "${workspaceRoot}/app"
Still it does not work.
And the output of .scripts surprises me , as it did not give any information on the path of local file.

**Comment by auchenberg** [comment]
@prasannajit I'm still trying to understand the workflow. You run a script to combine your JS files into a bundle, which you save to the filesystem and then opens in Code. Once open you want to debug it in Chrome, by setting a breakpoint in the bundle?

`webRoot` should be a relative path, to your workspace directory, so if you set `"webRoot": "${workspaceRoot}/app"`, you should see the paths being transformed when running `.scripts`.

I see that you have enabled verbose logging, it would be super helpful if you could post a gist.github.com with the log output, so we can figure out what goes on.

**Comment by prasannajit** [comment]
@auchenberg Yes, you are right. I am trying to debug the bundle js file from code.
I am able to debug my code from chrome browser itself.
But when i launch a browser instance from vscode and attach to it, I am not able to debug it because it is giving the message as "Breakpoint ignored because target path not found".
Though, I am able to see the console output in code debug console, which proves that connection to chrome is happening properly.
--------------------------------
Output from debug console:
--------------------------------
From client: setBreakpoints({"source":{"path":"d:\\Apps\\app\build.js","name":"build.js"},"lines":[2455],"breakpoints":[{"line":2455}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
To client: {"seq":0,"type":"response","request_seq":26,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":2455,"message":"Breakpoint ignored because target path not found","id":1002}]}}

**Comment by auchenberg** [comment]
@prasannajit Got it. Looking at the log, it's your `webRoot` that's the problem as VS Code tells Chrome to set a breakpoint in `d:\Apps\app\build.js` but it should be `https://localhost:3000/build.js`

Again, try experiment with your `webRoot` path.

**Comment by prasannajit** [comment]
@auchenberg Sorry, I did not understand. What should be the webroot?
Why does not it map to local file?

**Comment by auchenberg** [comment]
@prasannajit Your `webRoot` should be relative to your project, and not be an absolute path, as you have currently.

I've created an example project that shows how to use `webRoot` with no sourcemaps. See https://github.com/auchenberg/vscode-simple-webroot-example

**Comment by prasannajit** [comment]
@auchenberg My project configuration is not that simple. The URL in the browser is pretty complex and the scripts are also served from dynamic paths. I can not paste the actual paths from production code. But will try to explain my scenario. I am somehow not able to get the pathMapping right.
As of now i am trying to debug just one file, to get started. The intention is to set debugging through vscode for entire project.
My login URL is something like https://localhost:3000/authenticate/xx/yy/1000/.
I have set this as launch URL in the launch json file.
After login I am redirected to a different URL, and then when I go through a particular flow(clicking series of buttons), i finally reach a page where the file I want to debug is loaded into browser(along with other js files which I am not debugging right now). The file "bundle.js" is presented in the relative directory,
${workspaceRoot}/js.
But the dynamic url that chrome uses to download the file is (The no 2000 in the url is changed dynamically),
"https://localhost:3000/dd/2000/app/js/pp?112/src/js/build.js"
I removed webroot config from launch json file and provided pathMapping as 
"pathMapping": {
                 "/dd/2000/app/js/pp?112/src/js/":"${workspaceRoot}/js"
             },
But I am still getting the error message as
"Breakpoint ignored because target path not found".
Somehow the path from local file is not getting translated to the correct URL.

**Comment by auchenberg** [comment]
The problem seem to be that the url `"https://localhost:3000/dd/2000/app/js/pp?112/src/js/build.js` you are using contains a querystring `?` with no key/value pair, which causes our path mapping logic to choke.

If you were serving the file from `/dd/2000/app/js/pp?112/src/js/build.js` a pathMapping like this would work:
```json
"pathMapping": {
    "/dd/2000/app/js/pp/src/js/": "${workspaceRoot}/app/"
}
```

Querystrings with no key-value pairs are [valid](https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value), but not commonly used. @roblourens

**Comment by prasannajit** [comment]
Will this issue be fixed?

**Comment by roblourens** [comment]
Let me know if I need to reopen this - I've fixed a bunch of things related to pathMapping in the past year.
