### ISSUE TITLE
[Feature] Inspect DOM/Elements

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode-chrome-debug#464]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|0.3.4
mssql|ms-|1.1.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
debugger-for-chrome|msj|3.1.6
vscode-docker|Pet|0.0.16
shell-launcher|Tyr|0.1.1

I would very much like to be able to inspect the DOM when using the Chrome extension. At this point, the only option is to open Chrome's inspector, which disconnects VSCode.

**Comment by auchenberg** [comment]
Closing, as DOM inspection is currently outside the scope of this script debugger extension for Code. This could be enable in new separate extension.

**Comment by Hobart2967** [comment]
+1 for this request!
For when is this extension planned?
