### ISSUE TITLE
Debugger requires restart (Shift+⌘F5) to pause on breakpoint

### ISSUE THREAD

**Issue by justinlevi** [Microsoft/vscode-chrome-debug#466]
- VS Code Version: Version 1.14.2 (1.14.2)

Following the article by @auchenberg here (https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f) 

I'm able to get vscode to pause at a breakpoint in my "Create React App" generated project, but only after clicking the green restart (Shift+⌘F5) button. 

I'm wondering if there is any way to fix this? Why isn't the debugger attached and the breakpoint triggered on the first load? More of an annoyance than anything but thought I'd ask. 

Steps to reproduce:

1. $ `yarn start` in a terminal window
2. F5 or Debug > Start Debugging from VS Code
3. A new instance of Chrome is launched with my app running
4. If I then click the restart icon from within VS Code, the breakpoints are triggered. 

Here's my `launch.json`: 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/src",
      "userDataDir": "${workspaceRoot}/.chrome",
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }
  ]
}
```

![screenflow](https://user-images.githubusercontent.com/1117989/28633882-3fde612c-7203-11e7-9b5e-e1cf81283148.gif)

**Comment by auchenberg** [comment]
Thanks for the detailed issue and animated gif! Our debugger doesn't currently support "break-on-load", which is needed to break on code that such as React Render code that get's executed when the page is loading. We simply don't have a way to tell Chrome "stop execution" while we connect from VS Code, which results in Chrome executing code before VS Code is connected.

You don't have the same experience with Chrome DevTools, as you usually open the tools after your page has loaded, and once the tools are open they will set the breakpoints on next page load. Just like VS Code sets the breakpoints after a page refresh.

If you set your breakpoint in an event-handler we should be able to break the first time you load your app. 

We have an open issue for this https://github.com/Microsoft/vscode-chrome-debug/issues/445

**Comment by justinlevi** [comment]
@auchenberg Thanks for the quick response. Totally makes sense.
