### ISSUE TITLE
Debugger.setAsyncCallStackDepth wasn't found

### ISSUE THREAD

**Issue by ChrisReddy** [Microsoft/vscode-chrome-debug#467]
- VS Code Version: 1.14.2
- Debugger for Chrome Version

Steps to reproduce:

1. Add configuration to launch.json
{
           "type": "chrome",
           "request": "launch",
           "name": "Launch Chrome",
           "url": "http://localhost:5000",
           "webRoot": "${workspaceRoot}"
       }

2. Run Launch Chrome from Debug drop-down
3.  Chrome Window opens but the following error occurs in Vscode and Chrome closes :
 Error processing "launch": 'Debugger.setAsyncCallStackDepth' wasn't found

**Comment by roblourens** [comment]
Is it possible that you're using an old version of Chrome?

**Comment by ChrisReddy** [comment]
I checked and I am using the latest 60.0.3112.78

**Comment by roblourens** [comment]
That's quite odd. I should fix it to not crash when debugging a runtime that doesn't have that method. But Chrome 60 shouldn't definitely have it.

Can I get you to add `"trace": true` to your launch config, and upload the log here?

**Comment by ChrisReddy** [comment]
Here ya go. Thanks for checking it out

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1185242/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
It doesn't explicitly log the Chrome version, but the log makes it look like an older version of Chrome. Is it possible that it's launching an older version of Chrome that you have installed? Is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` the right location?

**Comment by ChrisReddy** [comment]
Excellent catch. That is not the right location. I did have it installed to that location quite some time ago, and then added a new hard drive to my machine, and installed the latest version to the new F drive, so the path is really F:\Program Files (x86)\Google\Chrome\Application\chrome.exe. I added the runtimeExecutable argument to the launch.json and pointed it that location it''s working now. Thanks so much for looking at it.  Consider this closed.

**Comment by jalchr** [comment]
mmm, on Mac, I have chrome version 59, and I'm getting this same error. 
Any suggestions ?

**Comment by roblourens** [comment]
Could it be the same issue as above? Are you sure that it's launching Chrome in the correct location, and not an old version?

In any case, I'll get this fixed anyway because of https://github.com/Microsoft/vscode-chrome-debug-core/issues/226

**Comment by jalchr** [comment]
@roblourens Great. I hope we get a maintenance release soon.
