### ISSUE TITLE
Sourcemap problem running inside docker with angular >1.1.2

### ISSUE THREAD

**Issue by erlloyd** [Microsoft/vscode-chrome-debug#469]
- VS Code Version: 1.14.2

I noticed that I'm getting the dreaded `(source map problem?)` error with my breakpoints when I upgrade from `@angular/cli` v1.1.1 to v1.1.2. 

Looking at the @angular/cli codebase, the big thing that changed was the way they specify Webpack to build the source maps. Here you can see the change pretty clearly: 
![sourcemapchange](https://user-images.githubusercontent.com/2145299/28742196-2dd79a8c-73ef-11e7-9e42-53be9b7d475c.png)

The big thing that seems to be the problem is them specifying a `sourceRoot: 'webpack:///'`. If I `ng eject` and manually remove the `sourceRoot`, my breakpoints work.

Using the scripts command, I'm noticing weird mappings when `sourceRoot: 'webpack:///'` is enabled. For example
` - webpack:/src/app/components/app/app.component.ts (/Users/erlloyd/Code/BunkerWebClient/webpack:/src/app/components/app/app.component.ts)`

Notice the weird `webpack:` in both the left and right side of the mapping?

Here's how it looks from .scripts if I remove the `sourceRoot: 'webpack:///'`

` - ./src/app/components/app/app.component.ts (/Users/erlloyd/Code/BunkerWebClient/src/app/components/app/app.component.ts)`

Two other notes, I'm running this inside `docker` - not sure yet if that matters. Also, here's my custom `launch.json` I have (and needed) to get this working inside docker in v1.1.1:

```{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Bunker SPA against localhost",
            "url": "http://localhost:4200",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:////app/~/*": "${webRoot}/node_modules/*",
                "webpack:////app/*": "${webRoot}/*",
                "webpack:///./~/*": "${webRoot}/node_modules/*",
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///./*": "${webRoot}/*",
                "webpack:///*": "*"
            }
        },...```

**Comment by auchenberg** [comment]
@erlloyd Does this work if you are running outside of the docker containers? If it doesnt please try to upgrade to 1.1.3 of angular-cli, as it has a bunch of important webpack sourcemap fixes. https://github.com/angular/angular-cli/releases

If Docker is the problem please have a look at the `localRoot` and `remoteRoot` properties, as you might need to map the path difference between your server and local files. 

We have en example here, https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript

**Comment by erlloyd** [comment]
It does work outside of docker, and using 1.1.3 (and later) of angular cli doesn't help. But I was able to get the sourcemaps to load by adding a bunch more custom `sourceMapPathOverrides`. For now that's good enough for me. I can try the local and remote root variables later if you're interested.

**Comment by auchenberg** [comment]
@erlloyd This sounds like a mapping problem with local/remote root, so please try that when time allows it.

**Comment by asrath** [comment]
@erlloyd I have a similar problem, could you post the mappings that worked for you?

**Comment by Oliverwong369** [comment]
I have a very similar problem when I try to deploy some services to the docker swarm.
`TypeError: NetworkError when attempting to fetch resource.
Source URL：http://192.168.99.100:3000/main.bundle.js
Sourcemap URL：main.bundle.js.map`
