### ISSUE TITLE
Breakpoint ignored because generated code not found (source map problem?)

### ISSUE THREAD

**Issue by ToniIltanen** [Microsoft/vscode-chrome-debug#471]
Ok, long story short:

folder structure in project:

-src/app/a.js
-src/app/b.js
-src/app/components/c.js
-src/app/components/d.js
-src/app/containers/e.js
-src/app/containers/f.js
....etc

webpack source map pushes everything in the root, as:

-webpack:///a.js
-webpack:///b.js
-webpack:///c.js
-webpack:///d.js
-webpack:///e.js
-webpack:///f.js

my launch.json:

```json
{
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceRoot}/src/app",
            "sourceMaps": true,
            "trace": true

 }
```
Now, here comes the problem, the source map does not follow the actual file structure
every file is source mapped the following: webpack:///somefile.js - no matter what the actual folder structure is. it would work, if the source map would contain the original folder structure. but that seems impossible. 

and because e.js is not at the root, but in the src/containers folders, it will not work. It should find the actual source file from the given workspaceroots folders.

(from my current trace) => 
mapping webpack:///something.js => something.js via sourceMapPathOverrides entry - "webpack:///*": "*"

so, how can i give a wildcard to the configurations to search from multiple folders? As in:
 ```json
"sourceMapPathOverrides": {
         "webpack:///*": "${workspaceRoot}/src/app[wildcard here for directories]/[wildcard here for files]"
}
```
or, give multiple folders to the same key:
 ```json
"sourceMapPathOverrides": {
      "webpack:///*": "${workspaceRoot}/src/app/*",
      "webpack:///*": "${workspaceRoot}/src/app/components/*",
      "webpack:///*": "${workspaceRoot}/src/app/containers/*",
}
```

**Comment by roblourens** [comment]
Are you using Vue? I've seen this in that context and don't have a good answer yet. Or another framework? You can probably list out all the files one by one in sourceMapPathOverrides.

**Comment by auchenberg** [comment]
This seems to be a problem with your webpack setup, as the sourcemap is invalid.  We rely on valid paths in the sourcemap for our debugger.

If you provide some more details on the setup, then we might be able to help out.
