### ISSUE TITLE
"runtimeExecutable" of "launch.json" does not escape backslashes as expected

### ISSUE THREAD

**Issue by winglerw28** [Microsoft/vscode-chrome-debug#474]
**UPDATE:** This was me not thinking hard enough about what was happening rather than an actual issue.

## Issue

The value of  `runtimeExecutable` in `ILaunchRequestArgs` (e.g. creating a `launch.json` file for a workspace) does not sanitize the value provided.  This is especially problematic for Windows since `${workspaceRoot}` is a very common configuration alias that will cause this problem. 

Even more troubling, the non-sanitized input may result in a scenario where `spawn` sees a relative path that begins with a dot and simply writes the non-error output of `'.' is not recognized as an internal or external command, operable program or batch file`. In this scenario, the debugger can seemingly believe a process is still running and will not stop until manual intervention is taken.

[Here is a sample](https://gist.github.com/winglerw28/21f02bf2300bcd3e5a93758a9443683c) better describing the behavior.~~

## Reproduce

1. Create any application that requires a launch configuration with a `runtimeExecutable` (such as an Electron app), on a Windows machine
1. Use the `${workspaceRoot}` alias for the value of `runtimeExecutable`
1. Use the `${workspaceRoot}` alias for a value in `runtimeArgs`
1. Set "trace" to "verbose" and then attempt to launch your app in Code
1. In the output, note how the string passed to `spawn` from `runtimeExecutable` is a single-quoted, non-escaped string while the string passed 

## Proposed Solution

- Use the Node.js `path` utility in a similar manner that [the Node debugger](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts) does to ensure that the value provided is properly sanitized

## Environment Information

- Visual Studio Code 1.14.2
- Debugger for Chrome 3.1.7
- Node 6.10.1 (also tested on 7.4.0)

**Comment by winglerw28** [comment]
Aside: if anyone else is experiencing this problem while trying to debug the renderer process of their Electron app, a temporary workaround can be to use `"node"` as your `runtimeExecutable` since it very likely exists on your PATH, then add `"${workspaceRoot}/node_modules/electron/cli.js"` as the first value of `runtimeArgs`.

**Comment by roblourens** [comment]
Can you explain the actual problem a little more? You're just saying that the output looks wrong in the logs, but I think it's showing the correct thing, in that it's showing the literal backslash in the command executed, not the escaped form. Maybe it's confusing since other places in the log it shows the escaped form, due to using `JSON.stringify`.

I use the vscode launch config to debug with a `runtimeExecutable` using `${workspaceRoot}` all the time, and it works fine.

The node debugger doesn't do any extra sanitization of `runtimeExecutable` - it does check that it exists and look for platform-specific path extensions, but otherwise it uses it as-is. And it should be in the correct form as resolved in your launch config, or maybe I'm misunderstanding.

> Even more troubling, the non-sanitized input may result in a scenario where spawn sees a relative path that begins with a dot and simply writes the non-error output of `'.' is not recognized as an internal or external command, operable program or batch file`. In this scenario, the debugger can seemingly believe a process is still running and will not stop until manual intervention is taken.

This could be a real issue. Can you clarify what this scenario is?

**Comment by winglerw28** [comment]
> Can you explain the actual problem a little more? You're just saying that the output looks wrong in the logs, but I think it's showing the correct thing, in that it's showing the literal backslash in the command executed, not the escaped form. Maybe it's confusing since other places in the log it shows the escaped form, due to using JSON.stringify.

I added my actual `launch.json` and the [raw debug console output](https://gist.github.com/winglerw28/21f02bf2300bcd3e5a93758a9443683c#file-actual_debug_console_output-js) to the linked gist. Specifically, the line with the call to `spawn` is what led me to begin looking into this, but JSON.stringify makes perfect sense as to why it would appear that way, and manually entering the value results in the same output.

> I use the vscode launch config to debug with a runtimeExecutable using ${workspaceRoot} all the time, and it works fine.

I do this all the time as well, which is why I found this behavior baffling. I specifically was trying to use it with an Electron app, so this may be Electron-specific; if that is the case I will look into it more and report it to the proper place once I find the _actual_ underlying issue.

> The node debugger doesn't do any extra sanitization of runtimeExecutable - it does check that it exists and look for platform-specific path extensions, but otherwise it uses it as-is. And it should be in the correct form as resolved in your launch config, or maybe I'm misunderstanding.

Looking at the linked repository, I misread how things were being processed. The only difference I see is that the Node debugger, if passed a bad path string, would return `undefined` from `PathUtils.findExecutable` (and I assume that something similar happens here).

> This could be a real issue. Can you clarify what this scenario is?

I was too hasty in reporting this and now realize this is a separate issue tied to something other than the behavior of the Chrome debugger. I apologize for my brain apparently not working today - my goal wasn't to waste your time, I promise! 🤦‍♂️

**Comment by roblourens** [comment]
Yep what you are seeing is just the difference between writing the actual value of a string, and writing a JSON.stringified version:

![image](https://user-images.githubusercontent.com/323878/28887948-c8016e1c-7773-11e7-9fd9-6ee2f1e51c42.png)

No worries!
