### ISSUE TITLE
New feature: It'd be great if we supported the launch url to redirect arbitrary fast without issues

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-chrome-debug#475]
It'd be great if we supported the launch url to redirect arbitrary fast.
One possible way to solve this issue would be to use a temporary landing page while we are attaching to Chrome.

**Comment by roblourens** [comment]
We try to attach to `http://foo` but the page may redirect to `http://bar` before attach. Apparently this is common for ASP.net. It would also fix it if VS knows the real URL from the start and can use that instead.

**Comment by auchenberg** [comment]
What's the user scenario here @digeff?

**Comment by digeff** [comment]
Sometimes we open http://foo and http://foo redirects to http://foo/login instantly so the debugger fails to attach

**Comment by auchenberg** [comment]
Why would we fail to attach? Because the target `url` has changed? That should be solvable with a wildcard match.

**Comment by digeff** [comment]
You can use some identity services where your homepage redirects to www.myidentityservice.com/loginAndGoBackTo?page=localhost/
I don't see how we can make this work for all cases, without risking choosing the wrong Tab on Chrome.

**Comment by auchenberg** [comment]
Landed as a part of break-on-load breakpoints, which hopefully will be enabled by default

**Comment by roblourens** [comment]
Actually this is a different issue, this is when we launch to some url, then the page redirects, and we can't find it to attach to because the url is now different.
