### ISSUE TITLE
VS Code 1.15.0 jumps into wrong PHP line from Search in both 32 and 64bit Code editions

### ISSUE THREAD

**Issue by pegasus2013** [Microsoft/vscode-chrome-debug#476]
Visual Code is jumping into wrong line in result file from Search menu, since version 1.13, on Windows 10 64bit 1703 - with non extensions installed even after removing 32bit and installing 64bit version the problem still occurs every time.

- VS Code Version: 1.15.0 32bit and 64bit

Steps to reproduce:

1. Search for string in Search menu
2. Click on Search results in any file 
3. Code will jump into wrong line most of the time
4. After closing and opening that file in editor and cliking again will solve the problem for that file only
5. If you click on other results lines in files will reoccur the bug again

**Comment by roblourens** [comment]
Does this have anything to do with the chrome debug extension? Can you reopen it in the vscode repo with details, like whether it only happens on a certain file?

**Comment by pegasus2013** [comment]
No it does not have anything with any extension cause I have stated that not even single extension have been installed, how can you close this without checking...?
