### ISSUE TITLE
Breakpoints enabled but do not trigger.  Electron 1.7.5

### ISSUE THREAD

**Issue by greg9504** [Microsoft/vscode-chrome-debug#478]
- VS Code Version:

> Version 1.15.1
> Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
> Date 2017-08-16T18:05:38.342Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0
> Architecture ia32

I updated from 1.5.0 of Electron to 1.7.5 and I can no longer debug the renderer process of my Electron app, I can debug the main process...

The breakpoints display as enabled (no errors saying breakpoint can't be set) however they are not hit.  This did work.  
Source Maps appear to be correct.   The relevant sections of the logs (breakpoint set in project.service.ts):

> SourceMap: mapping webpack:///./src/app/shared/services/project.service.ts => d:\src\TAnalyzeElectron\src\app\shared\services\project.service.ts, via sourceMapPathOverrides entry - "webpack:///./*": "d:\src\TAnalyzeElectron/*"
> 
> setBreakpoints({"source":{"path":"d:\\src\\TAnalyzeElectron\\src\\app\\shared\\services\\project.service.ts","name":"project.service.ts"},"lines":[53,189,38],"breakpoints":[{"line":53},{"line":189},{"line":38}],"sourceModified":false})
> 
> SourceMaps.setBP: Mapped d:\src\TAnalyzeElectron\src\app\shared\services\project.service.ts to d:\src\TAnalyzeElectron\dist\main.bundle.js
> SourceMaps.setBP: Mapped d:\src\TAnalyzeElectron\src\app\shared\services\project.service.ts:53:1 to d:\src\TAnalyzeElectron\dist\main.bundle.js:608:9
> SourceMaps.setBP: Mapped d:\src\TAnalyzeElectron\src\app\shared\services\project.service.ts:189:1 to d:\src\TAnalyzeElectron\dist\main.bundle.js:723:13
> SourceMaps.setBP: Mapped d:\src\TAnalyzeElectron\src\app\shared\services\project.service.ts:38:1 to d:\src\TAnalyzeElectron\dist\main.bundle.js:597:9
> Paths.setBP: Resolved d:\src\TAnalyzeElectron\dist\main.bundle.js to file:///d:/src/TAnalyzeElectron/dist/main.bundle.js
> 

from .scripts

> - webpack:///./src/app/shared/services/project.service.ts (d:\src\TAnalyzeElectron\src\app\shared\services\project.service.ts)

I do see this message in the log:

> ← From target: {"error":{"code":-32601,"message":"'Runtime.run' wasn't found"},"id":6}

Here is my launch config:

>      {
>             "name": "Debug Dev Renderer Process",
>             "type": "chrome",
>             "request": "launch",
>             "userDataDir": "${workspaceRoot}/.chrome",
>             "windows": {
>                 "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
>             },
>             "runtimeArgs": [
>                 "${workspaceRoot}/dist",
>                 "--remote-debugging-port=9222"
>             ],
>             "port": 9222,
>             "sourceMaps": true,
>             "trace": "verbose",
>             "webRoot": "${workspaceRoot}"
>         }

Debugging with Chrome dev tools works fine.  
Attached full trace log and .scripts output.
[DebuggerForChromeNoBPHit.zip](https://github.com/Microsoft/vscode-chrome-debug/files/1230035/DebuggerForChromeNoBPHit.zip)

**Comment by roblourens** [comment]
Everything seems correct in the logs. The breakpoints are properly bound. Does the code run immediately on startup, in which case the bps might not bind fast enough? Are you definitely sure that it's running? Are the breakpoints hit if you reload electron?

**Comment by greg9504** [comment]
Arg.  Before posting above I did try reload to see if it was a timing issue, and the break points didn't hit.  I just tried again and the break points do not hit on launch but do if I reload.  Only thing I think I've done between now and when it wasn't working was to shut down all instances of Visual Studio code.  Sorry it appears to be working now.

**Comment by roblourens** [comment]
No worries, thanks for providing all the logs and details. Let me know if it keeps happening and we can debug some more.

**Comment by auchenberg** [comment]
Ref: https://github.com/Microsoft/vscode-chrome-debug/issues/445
