### ISSUE TITLE
With sourcemaps enabled, a set breakpoint will sometimes move to a previous line

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#48]
Sometimes happens with the first line in a typescript function. Workaround - setting a breakpoint on the next line or previous line will often work.

**Comment by roblourens** [comment]
Related to Microsoft/vscode-node-debug#7, but simply switching to LEAST_UPPER_BOUND breaks other edge cases

**Comment by edvinv** [comment]
Yes I can confirm that #84 is linked to this issue. I can see that mostly you are not able to set breakpoints on most wanted first line of function :). 

Quite annoying especially with single line functions and getters/setters.
