### ISSUE TITLE
(source map problem?)  Browsersync + Gulp (almost found it)

### ISSUE THREAD

**Issue by kyakubi** [Microsoft/vscode-chrome-debug#482]
I think I have a simple to solve issue...

I use gulp to do some tasks (babel,sourcemaps,watcher) and use browsersync to serve the files in memory.

 ```
   {
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "url": "http://localhost:3000/*",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/"
        }
```

I can't set any breakpoint because of the error but when I set a "debugger;" command in the code it works and opens the file...here is the funny thing (and probably the issue)

The path to the source file in vscode is this (i want to put breakpoints in this file) :
"[long windows path]\**webapp**\controller\worklistdetails\DetailsTab.controller.js"

Because of the debugger command it opens this file (the sourcemap probably)
"[long windows path]\controller\worklistdetails\DetailsTab.controller.js"

I changed "webRoot": "${workspaceRoot}/webapp/" but it still gives the same error...

I know I am missing something small but cant see exactly what it is

**Comment by roblourens** [comment]
There are some troubleshooting tips in the readme - try the `.scripts` command to get everything that vscode thinks it knows about your scripts.
