### ISSUE TITLE
Pause overlay no longer shown

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#486]
Previously the API to set the pause overlay was `Page.configureOverlay`. This changed recently to `Overlay.setPausedInDebuggerMessage` and I didn't notice.

It would have failed the build in CI if I'd called this in vscode-chrome-debug-core, because it regenerates the protocol .d.ts for every build, but this repo doesn't do that.

This is a pretty rare breaking change. I need to check whether the `Overlay` schema is supported, and use the new API if so, otherwise, keep the old API for Electron and slightly older Chrome versions.

https://chromium.googlesource.com/chromium/src/+/3b36efad6b17e10ae243a8668528aae310a312da%5E%21/#F22

https://chromedevtools.github.io/devtools-protocol/tot/Overlay/#method-setPausedInDebuggerMessage

FYI @auchenberg

**Comment by auchenberg** [comment]
Ah dang. The domain is marked as `experimental` so we can continue to expect changes. It has changed a few times, and I think this API structure seems better, so hopefully it will stabilize. 

Ping @paulirish
