### ISSUE TITLE
Suddenly chrome debugger extension stopped working

### ISSUE THREAD

**Issue by nvmkpk** [Microsoft/vscode-chrome-debug#488]
Started getting this error: `command 'extension.chrome-debug.startSession' not found`

**Comment by roblourens** [comment]
Hm that's odd. Can you try restarting vscode again? Or try to uninstall/reinstall the extension?

**Comment by nvmkpk** [comment]
Restarting vscode did not fix it but re-installing the extension fixed the issue.

**Comment by roblourens** [comment]
Ok, sounds like there might have been an issue with updating. Glad that fixed it.

**Comment by nvmkpk** [comment]
Was there an update pushed for this extension over the weekend? It was working fine the other side of weekend.

**Comment by roblourens** [comment]
Yes, last night
