### ISSUE TITLE
Cannot connect to the target: <!DOCTYPE html> for "Attach"

### ISSUE THREAD

**Issue by TLKG** [Microsoft/vscode-chrome-debug#489]
- VS Code Version = 1.15.1 
- Node = 8.2.1
- Chrome Debugger = 3.2.0

Application is a MEAN stack, inside Terminal started app successfully
`  node server.js`
open up a Chrome browser navigated to 

> http://localhost:3000/

  successfully, also Terminal shows all GET status code=200

Steps to reproduce:

1. when all above succeeded, back to VS Code
2. Debug, select the configuration "Attach", click on the green play button.
3. Right way, error came up across the top. **`Cannot connect to the target: <!DOCTYPE html>`**
4. Same problem regardless the following switch for Chrome.exe
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=3000

Here is my launch.json from .vcode folder:
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch",
            "protocol": "inspector",
            "program": "${workspaceRoot}\\server.js",
            "sourceMaps": true,
            "url": "http://localhost:3000"
        },
        {
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "port": 3000,
            "address": "localhost",
            "url": "http://localhost:3000",
            "disableNetworkCache": true,
            "trace": true,
            "diagnosticLogging": true,          // seems deprecated
            //"restart": true,
            //"protocol": "inspector"
            "webRoot": "${workspaceRoot}"
        }
    ]
}
![err1](https://user-images.githubusercontent.com/22269729/29787302-49f9a640-8be3-11e7-9dd4-594df903424e.JPG)

```

**Comment by roblourens** [comment]
It seems you're confusing the webserver port (`http://localhost:3000`) with the remote debug port for Chrome ("port" launch config prop and `--remote-debugging-port=3000`) - make sure you use different po

**Comment by TLKG** [comment]
Please elaborate what port to use in 

- launch.json

- Target property of Chrome exe.

**Comment by auchenberg** [comment]
@TLKG Your remote debugging port of Chrome can't be the same the same as your local website. Try to use a launch.json config like this

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Node",
            "protocol": "inspector",
            "program": "${workspaceRoot}\\server.js",
            "sourceMaps": true
        }
    ]
}
```

**Comment by TLKG** [comment]
@auchenberg 

1. I removed the switches from Chrome.exe.

2. Closed all Chrome instances.
3. Used the exact config you provided ("name": "Launch Chrome"), saved.
4. In Terminal, restart node server.js
5. Selected "Launch Chrome" from debug drop-down, click on green button.
6. Chrome was started successfully and my web page displayed briefly then wen to Google.com.
7. Back in VS Code, 
Error Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches: http://l...
8. no error showed in Terminal.

**Comment by auchenberg** [comment]
@TLKG We start a new instance of Chrome, telling it to navigate to the `url`. If something takes you away from `url`, it sounds like you have a setting or extension in Chrome that redirects a given page to google.com (or any other predefined page). Do you have any Chrome extensions installed?

**Comment by TLKG** [comment]
@roblourens If I don't try debugging from VS Code, but simply start a Chrome and localhost:3000, it works and stays there forever :)

**Comment by TLKG** [comment]
@auchenberg  If I don't try debugging from VS Code, but simply start a Chrome and localhost:3000, it works and stays there forever :)

**Comment by auchenberg** [comment]
Can I get you to set the `trace` property to  `"verbose"`, follow the last step in https://github.com/Microsoft/vscode-chrome-debug#general-things-to-try-if-youre-having-issues

**Comment by TLKG** [comment]
@auchenberg It works this time. It seems like some caching issues of the server, or I should say a lagging issue so config is not reflected shortly after. Must wait for a little while. Your assistance is highly appreciated it!!
Final workable config for "**Launch**":
"version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "trace": "verbose",
            "webRoot": "${workspaceRoot}"
        }
]}

Going to try "**attach**" next.
My understanding is this switch is needed for Chrome.exe, in Target property
 ` --remote-debugging-port=9222`
the port number is static.

**Comment by TLKG** [comment]
"Attach", 
from log:
```
Discovering targets via http://127.0.0.1:3000/json
HTTP GET failed with: 404 Not Found
Discovering targets via http://127.0.0.1:3000/json
HTTP GET failed with: 404 Not Found
To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /json</pre>\n</body>\n</html>).","body":{"error":{"id":2010,"format":"Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /json</pre>\n</body>\n</html>","_timeout":"10000"}}}}
 

```

> launch.json:

```
{
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "protocol": "inspector",
            "sourceMaps": true,
            "trace": "verbose",
            "port": 3000
        },
```
Steps:

1. Added switch to Chrome.exe becomes "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" **--remote-debugging-port=9222**
2. Start node server by node server.js
3. Start a new Chrome window, hit localhost:3000, ok. Ctrl-F5 to force a refresh, all status code = 200.
4. VS Code, select "Attach" option, click on green play button.
5. Observe "**GET /json 404 1.379 ms - 143**" repeating in Terminal, 10 seconds later yields "**Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after 10000 ms**". See above for log.

**Comment by roblourens** [comment]
You are using the 'node' type to attach to Chrome - make sure you're using "chrome". Also, you have "port" as your webserver port again :)

**Comment by TLKG** [comment]
@roblourens 
Changes to launch.json:

1. change "type" value to "chrome" from "node".
2. remove "port" pair.

In Terminal:

1. node server.js 
2. open a new Chrome window, localhost:3000, Ctrl-F5, successful.
3. VS Code, select "**Attach**" option, green play button, error came up right away w/o output in terminal:
`Cannot connect to the target: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">`

Meanwhile, **<PROBLEMS>** window show: Missing property  "`port`". Complete "Attach" options:
```
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach",
            "sourceMaps": true,
            "trace": "verbose"
        }
```

**Comment by TLKG** [comment]
Adding back "port" for "Attach", about a second later got this:
`Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222`

Chrome version: 

> Version 60.0.3112.113 (Official Build) (64-bit) lates and greates :)

**Comment by TLKG** [comment]
Same "**Attach**" with "port" but value change to **3000**, 

> Cannot connect to the target: <!DOCTYPE html>

**Comment by roblourens** [comment]
- Have "port" as 9222, or whatever you launch Chrome with
- _Kill all other instances of Chrome_
- Start Chrome with --remote-debugging-port=9222 flag
- If you get the ECONNREFUSED error, check whether you get a response for `http://localhost:9222` in a browser. If not, Chrome is not actually in debug mode (like there may be some Chrome.exe process sticking around in the background)

**Comment by TLKG** [comment]
@roblourens 
Before any test, here is the confusing part on PORT but I believe this interpretation:

1. the switch `--remote-debugging-port=9222` is required to start Chrome for testing, or make it simple, this switch and port are NEVER needed in launch.json UNLESS your app definitely accessing port 9222, should not be the case at all.
2. "port" pair is required for "ATTACH" debugging because your app can run at any port. So, its value must be whatever the port your app runs at. In my case is `"port":3000`  (should the number double-quoted? don't know).

Because of above, here is my config for "ATTACH" running node/express/AngularJS:
```
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach",
            "sourceMaps": true,
            "trace": "verbose",
            "port": 3000
        }
```
Steps:

1. Kill all Chrome.
2. Kill VSCode.
3. Start VSCode. <Terminal>, `node server.js`  started successfully
4. Start the first and only Chrome window, hit localhost:3000, Ctrl-F5, successful.
5. Choose "Attach", green button.
Yielding **"`Cannot connect to the target: <!DOCTYPE html`>"**

To confirm my Chrome is starting in debug-mode (so-called by me, meaning the aforementioned switch is effective), navigate to port 9222, verified good.
![9222](https://user-images.githubusercontent.com/22269729/29797245-cdfce76e-8c0a-11e7-8bc4-08c48b4974f0.JPG)

**Comment by roblourens** [comment]
No, "port" is never for your app. It's only so it knows which port Chrome is on for debugging. Otherwise, it has no idea which port Chrome is exposing. Try it with `"port": 9222`

**Comment by TLKG** [comment]
@roblourens 
Finally **attached**. Thank you! Complete config:
```
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach",
            "sourceMaps": true,
            "trace": "verbose",
            "port": 9222
        }
```
Are the followings right?

1. This port must match the port value in Chrome's Target property so VS Code knows where to sneak-in/attach in order to debug. 
2. No need to specify what port the app itself is running at.

Although attached, set a BP at the first line of server.js got 

> **"Breakpoint ignore because generated code not found(source map problem?)"**

**Comment by roblourens** [comment]
1, 2 - yes and yes.

You set the webroot in your launch config, do the same for your attach config.
