### ISSUE TITLE
Consider remove "attach" config from default launch configs

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#490]
We should consider remove "attach" config from default launch configs, as I believe it's causing more confusion than value, as it doesn't work for 80% of users, as they already have a Chrome instance running.

When we have a Chrome extension or a way to attach on demand we should consider adding it again.

@roblourens What do you think?

**Comment by roblourens** [comment]
Yeah I don't think it's that valuable.

**Comment by auchenberg** [comment]
👍
