### ISSUE TITLE
Chrome opens a fresh version with local caches wiped

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-chrome-debug#492]
Really annoying 'bug', my app uses IndexedDB in the browser for caching the user token. Hate having to login every time I initialise the Chrome window, looks like it fires up a seperate Chrome instance to the one already running on my Mac, so it's starting up this clean slate every time or something.

**Comment by roblourens** [comment]
By default it will start Chrome with a new `--user-data-dir` so it can run in debug mode alongside existing instances of Chrome. This also uses a new set of cookies and caches, etc. I would think that if you log into that new window once, it would persist. But maybe I'm wrong. You can set `"userDataDir": false` to disable this - just make sure you kill all existing instances of Chrome first, or it will not start in debug mode. You can also use an 'attach' config.
