### ISSUE TITLE
Breakpoint ignored because generated code not found - AngularJS w/ TypeScript, Gulp

### ISSUE THREAD

**Issue by slamflipstrom** [Microsoft/vscode-chrome-debug#493]
- VS Code Version: 1.14.2

Unfortunately I've been unable to get the Chrome Debugger to work with with the below setup in an AngularJS app utilizing TypeScript and Gulp. I've been working on this for the past couple days and can't seem to find a solution.

Thanks for all of your great work on this project 👍. Any assistance you could provide would be much appreciated!

**launch.json**
```
       {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "https://dev-samlinstro.crownpeak.com/AdventGeneral/v3",
            "webRoot": "${workspaceRoot}/app/",
            "trace": "verbose",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "app/*": "${webRoot}/app/*"
            }
        }
```
**Verbose output when setting a breakpoint**
```
To client: {"seq":0,"type":"response","request_seq":16,"command":"evaluate","success":true,"body":{"result":"","variablesReference":0}}
From client: setBreakpoints({"source":{"path":"c:\\inetpub\\wwwroot\\v3\\src\\components\\_shared\\asset-browser\\asset-browser.ts","name":"asset-browser.ts"},"lines":[234,224,242,258,284],"breakpoints":[{"line":234},{"line":224},{"line":242},{"line":258},{"line":284}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".ts"}}}
To client: {"seq":0,"type":"response","request_seq":17,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":234,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1006},{"verified":false,"line":224,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1007},{"verified":false,"line":242,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1008},{"verified":false,"line":258,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1009},{"verified":false,"line":284,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1010}]}}
```

**Output from running .scripts**
   See [this gist](https://gist.github.com/slamflipstrom/0986a67cbe8c70bd796a4a9ff8301b37)

**Comment by roblourens** [comment]
This is the actual path to the file (from the `setBreakpoints` log above):
`c:\\inetpub\\wwwroot\\v3\\src\\components\\_shared\\asset-browser\\asset-browser.ts`

And this is the important line from `.scripts`:

`    - \V3Src\components\_shared\asset-browser\asset-browser.ts (c:\inetpub\wwwroot\v3\app\V3Src\components\_shared\asset-browser\asset-browser.ts)`

There seem to be a couple issues:
- It looks like there is no `...wwwroot\v3\app`, this would be coming from `/app/` in your webRoot, I don't think that's necessary
- The sourcemap path starts with `V3Src` for some reason. You can either find where that's coming from and fix it, or use `sourceMapPathOverrides` to override it. Something like `"V3Src/*": "v3/src/*"` or `"V3Src/*": "${workspaceRoot}/src"`. Try it, run `.scripts` again to check the result, and iterate. 

(Maybe .scripts needs a way to filter the result, that's quite a lot to search through each time...)
