### ISSUE TITLE
AngularJS, Breakpoint cannot be reached because generated code not found

### ISSUE THREAD

**Issue by TLKG** [Microsoft/vscode-chrome-debug#494]
VS Code Version = 1.15.1
Node = 8.2.1
Chrome Debugger = 3.2.0

Steps to reproduce:

1. Downloaded this [sample](https://www.codeproject.com/Articles/1052703/MEAN-Stack-Beginner-Tutorial) app from codeproject.
2. In Terminal, ran `npm install `to **install all dependencies**
3. Modified `server.js` line 32 to followings to the latest method and connect to mlab.com:
```
app.use(session({
  secret: 'keyboard cat', saveUninitialized: true, resave: true
}));
```
  line 16 like following to connect to mlab.com using Mongo's client
`mongoose.connect('mongodb://user:psd@ds12345.mlab.com:12345/mean1', {useMongoClient:true});`
4. Add launch.json as:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```
5. In Terminal, `node server.js` starting app **successfully**.
6. Add "`--remote-debug-port=9222`" to Chrome.exe.
7. While no Chrome instance, start the first one, hitting `localhost:3000` **successfully**. No err output in Terminal.
8. Chose "Attach to Chrome", click green button, successfully attached.
9. Set a breakpoint at line 2 of Angular/Modules/mainApp.js. Chrome Ctrl-F5, back to VS Code, breakpoint becomes dimmed "**Breakpoint ignored because generated code not found**”.

**Comment by auchenberg** [comment]
You need to update your `webRoot` to reflect the path of the Angular app, which is `${workspaceRoot}/Angular`

I just cloned https://github.com/nomiali5/NodejsBasicAuthentication, and used the following launch.json config

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/Angular"
        }
    ]
}
```

Breakpoints are hit in the Angular code.

![screen shot 2017-08-30 at 10 27 56 pm](https://user-images.githubusercontent.com/173559/29893538-a5191600-8dd2-11e7-97a2-11f42539216f.png)

**Comment by TLKG** [comment]
@auchenberg 
After several attempts, it works!

1. If need to make it` "webRoot": "${workspaceRoot}/Angular"`, does it need to do anything for others like Express or Passport or else used in the project?
2. Can you pass me the document URL for `webRoot`?
Thank you!!
Awesome job!

**Comment by auchenberg** [comment]
Great to hear @TLKG 

1. Sounds like you want to debug your Node app too? Please see https://code.visualstudio.com/docs/nodejs/nodejs-debugging

2. `webRoot` is documented in our readme, https://github.com/Microsoft/vscode-chrome-debug#launch
