### ISSUE TITLE
Debugging of ServerLess functions doesn't work

### ISSUE THREAD

**Issue by rajivkanaujia** [Microsoft/vscode-chrome-debug#495]
Output of "diagnosticLogging": true, "verboseDiagnosticLogging": true is attached.
[495.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1272305/495.txt)

- VS Code Version: Version 1.15.1 (1.15.1)

Steps to reproduce:
I am using Mac - latest version, fully patched. Node.js is installed too.

1. Project Setup -
Select a working directory and use terminal to execute following commands 
```
$ npm install -g serverless
$ serverless create --template aws-nodejs --path my-service
$ cd my-service
$ serverless invoke local --function hello
```

you will get output like 

```
{
    "statusCode": 200,
    "body": "{\"message\":\"Go Serverless v1.0! Your function executed successfully!\",\"input\":\"\"}"
}
```

2. Create a default package.json
`$ npm init -f`

3. Add devDependencies for the project. 
Open my-service directory in VSCode and add following config

```
{
  "name": "my-service",
  "version": "1.0.0",
  "description": "Testing VSCode debugging",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless": "1.20.2"
  }
}
```

4. Go to terminal and execute following command
`$ npm install`

5. Go back to VSCode project and add a launch config

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/node_modules/.bin/sls",
            "args": [
                "invoke",
                "local",
                "-f",
                "hello",
                "--data",
                "{}"
            ]
        }
    ]
}
```

6. Run the "Launch Program" to find the debug console output as below

```
Debugging with inspector protocol because Node.js v8.4.0 was detected.
node --inspect=26030 --debug-brk node_modules/.bin/sls invoke local -f hello --data {} 
Debugger listening on ws://127.0.0.1:26030/bad49a43-f7cb-40d7-8100-0293e8395701
Debugger attached.
{
    "statusCode": 200,
    "body": "{\"message\":\"Go Serverless v1.0! Your function executed successfully!\",\"input\":{}}"
}
```

7. PROBLEM: Now try setting breakpoint handler.js
Observe that no matter where you put the breakpoint, it gets grayed out at debug run time. Hovering mouse over it giver information 

`"Breakpoint ignored because generated code not found(source map problem)". `

And it does not matter if you add outFiles or sourceMaps. 

Also see https://github.com/Microsoft/vscode-chrome-debug/issues/457

**Comment by roblourens** [comment]
I don't know a lot about serverless, is it possible that it's running the local program in a separate process or something?

**Comment by rajivkanaujia** [comment]
I don't think it is running the local program in separate process or something. I think it is not able to find the code and link it during the runtime process. 

For example, I used lambda-local to do something similar. 
launch config is something like below and it works.

       {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "/usr/local/bin/lambda-local",
            "cwd": "${workspaceRoot}",
            "args": [
                "-l",
                "${workspaceRoot}/hellolambda.js",
                "-e",
                "${workspaceRoot}/defaultevent.js"
            ]
        }

See https://www.codeproject.com/Articles/1163890/Debugging-AWS-Lambda-functions-locally-using-VS-Co 

Serverless does provide better lifecycle management of the AWS-API/Lambda etc., like deployment, testing, rollbacks and cleanups.

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it works there? Looking at the log, this actually looks like a problem I fixed earlier.  https://code.visualstudio.com/insiders

**Comment by rajivkanaujia** [comment]
Tried it and it works! Thanks!!!

**Comment by vrkr** [comment]
https://www.codeproject.com/Articles/1163890/Debugging-AWS-Lambda-functions-locally-using-VS-Co. I tried this approach. It worked as expected. But I am facing a problem with relative paths in my code. Is there any way in vs code I can config path.resolve(__dirname, 'src'). Otherwise I have to import ../../common/utility like this which I don't want to do. Can someone help me if any one knows a solution

**Comment by vrkr** [comment]
Hi, I solved the above issue, just pass NODE_PATH: './src' in env of launch.json.
