### ISSUE TITLE
Git behavior with debugging session

### ISSUE THREAD

**Issue by elghali** [Microsoft/vscode-chrome-debug#497]
- VS Code Version:
1.15.1
Steps to reproduce:

1. have a project controlled by git
2. run a debug session using "debugger for chrome"

Hello, 
my project is controlled by Git, and whenever I run a debug session, I get more than 500 files that need to be staged and committed in the source control tab and the number increases while debugging, so when I finish debugging I have to discard changes.

**Comment by roblourens** [comment]
Do you have `userDataDir` in your launch config set to somewhere in your project folder? That was old advice and is no longer needed, so you can just remove that setting.

Otherwise, can you tell me what the files are?

**Comment by elghali** [comment]
yes I did, and when I removed it, it worked, thank you man, good job btw
