### ISSUE TITLE
Can't get breakpoints to work with Typescript/Webpack

### ISSUE THREAD

**Issue by uglycoyote** [Microsoft/vscode-chrome-debug#498]
- VS Code Version:

Steps to reproduce:

1. Here's a zip of my test repo
[uglycoyote-typescriptreact-a64613f4b56e.zip](https://github.com/Microsoft/vscode-chrome-debug/files/1276304/uglycoyote-typescriptreact-a64613f4b56e.zip)

(this is a minimal repo representing the actual structure of my real app, but with minimal amount of code in it and still reproducing the chrome-vscode debugging problems)

2. npm install in the "client" directory

3. run "webpack --watch" from the "client" directory.    Client sources are built into a bundle that lands in "/server/public/js/client/TypescriptReactTest.entry.js"

4. run "python -m SimpleHTTPServer" from the /server/public directory

5. in vscode set the launch profile as follows

```

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:8000",
            "webRoot": "${workspaceRoot}/server/public",
            "sourceMaps" : true,
            "trace" : true,
            "verbose" : true,
            "sourceMapPathOverrides": {
                "webpack:///./~/*": "${webRoot}/node_modules/*",       // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
                "webpack:///./*":   "${workspaceRoot}/client/*"                   // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js",
            }
        }
    ]
}           
```

6.  Set breakpoints on code in the main tsx file, TypescriptReactTest.tsx

7. Press F5, Chrome shows up, navigates to the localhost:8000 address, but no breakpoints get hit

here's my trace output.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1276319/vscode-chrome-debug.txt)

here's the output from ```.scripts``` on the VSCode console.
```
.scripts
› VM36
› http://localhost:8000/js/client/TypescriptReactTest.entry.js (/Users/mike/development/web/TypeScriptExamples/TypescriptReact/server/public/js/client/TypescriptReactTest.entry.js)
    - webpack:///webpack/bootstrap 53c72bc4b68f0a130b1e (/Users/mike/development/web/TypeScriptExamples/TypescriptReact/server/public/js/client/webpack:/webpack/bootstrap 53c72bc4b68f0a130b1e)
    - webpack:///./src/TypescriptReactTest.tsx (/Users/mike/development/web/TypeScriptExamples/TypescriptReact/client/src/TypescriptReactTest.tsx)
    - webpack:///external "React" (/Users/mike/development/web/TypeScriptExamples/TypescriptReact/server/public/js/client/webpack:/external "React")
    - webpack:///external "ReactDOM" (/Users/mike/development/web/TypeScriptExamples/TypescriptReact/server/public/js/client/webpack:/external "ReactDOM")
```

as far as I can tell it is correct, most importantly the line

```webpack:///./src/TypescriptReactTest.tsx (/Users/mike/development/web/TypeScriptExamples/TypescriptReact/client/src/TypescriptReactTest.tsx)```

seems to be right;  i confirmed that if I copy the local path onto the command line that that file exists at that location.  I also confirmed by looking in the Chrome Dev tools that Chrome seems to be referring to that file as shown on the left side (```webpack:///.src/TypescriptReactTest.tsx```)

thanks for your help.

**Comment by roblourens** [comment]
Are the breakpoints in code that runs immediately, possibly before the debugger attaches? Are the breakpoints hit if you refresh the page?

**Comment by uglycoyote** [comment]
Since this is a very simple sample, basically the entire thing runs "immediately".  It's clear whether the debugger attaches before or after the script finishes running, but yes I did think of this and try refreshing in chrome.  Refreshing did not cause the breakpoints to start working.

**Comment by roblourens** [comment]
With the above setup, I do hit the breakpoint after refreshing:

![image](https://user-images.githubusercontent.com/323878/30086973-cca57266-9252-11e7-8783-f81cd25aac51.png)

Can you try again and if it doesn't work, attach a log that includes refreshing the page? Thanks.

**Comment by uglycoyote** [comment]
Yes I was able to get the breakpoint to work in my test codebase after hitting refresh in Chrome, just like you showed.

I then switched back to my other larger project (with similar structure, also adding breakpoint on the same initReact call in main.tsx) and tried debugging again, and was unable to get it to work for a while.   I then closed VSCode and restarted it, and things started working for me.  It's not clear what caused the hiccup, as I did not change and code, and settings, or any breakpoints between when it was not working and when it was started working again.

**Comment by uglycoyote** [comment]
It continued to work for me, I guess I'll close this issue.  If it ceases to function correctly and I figure out the pattern to when it does and doesn't work (and it is something other than just needing to refresh) then I'll reopen or open a more specific issue.   There seems to be some flakiness, but the issue is not useful to you if I cannot provide a specific condition to reproduce it.

**Comment by roblourens** [comment]
Thanks - if you leave `"trace" : true`, then if it stops working you can grab the log and upload it. That would be helpful. Thanks!
