### ISSUE TITLE
The debugger paused overlay should use the client's name

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-chrome-debug#499]
![image](https://user-images.githubusercontent.com/14098140/30122225-a80794b2-92e2-11e7-8783-b6edb0db2d0b.png)

It'd be great if we could change this string when the adapter is used by other clients.

**Comment by auchenberg** [comment]
@digeff Do you provide your own translations when shipping with VS Code?

**Comment by roblourens** [comment]
This was fixed right?
