### ISSUE TITLE
Move chrome launch code out of -core and switch to browser-launcher2 (bc chrome.exe isn't found in AppData)

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#50]
Apparently at one point the default install location for Chrome was `C:\Users\<username>\AppData\Local\Google\Chrome\Application\chrome.exe` and many people have it installed there. The extension should also look for it there if it isn't found in Program Files.

**Comment by compulim** [comment]
This is because Chrome is installed on a per-user basis, instead of system wide installation. When installing Chrome and the UAC prompt jumped out, click Cancel. The installer will ask you if you really want to install on a per-user basis.

This scenario should be supported.

**Comment by Sherry25** [comment]
There is post that is related to chrome.exe. You can read it to get information you need. http://pc-superman.com/remove-chrome-exe32-from-pc-with-practical-and-easy-methods/

**Comment by auchenberg** [comment]
Maybe we could switch to https://github.com/benderjs/browser-launcher2 or use https://github.com/vweevers/win-detect-browsers to detect Chrome.

**Comment by auchenberg** [comment]
@roblourens Hasn't this been completed?

**Comment by roblourens** [comment]
Yep!
