### ISSUE TITLE
Attaching creates a read-only copy of my js file at locallost

### ISSUE THREAD

**Issue by matt-erhart** [Microsoft/vscode-chrome-debug#500]
When I attach to process, I get a new copy of the file I'm working on at localhost...myfile, which I can step through but cannot edit. How can I step through and edit the same file? Launch is :

```
{
  "version": "0.1.0",
  "configurations": [
    {
      "name": "Attach",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "url": "http://localhost:8000/app/launchpad/?section_id=564",
      "webRoot": "C:/fullpath.../js/class_planner.js"
    }
  ]
}
```

**Comment by roblourens** [comment]
`webRoot` should be the path to the directory that the webserver is serving from, not a file.
