### ISSUE TITLE
Debugger fails immediately if target can't be reached regardless of timeout

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#501]
When using our Node + Chrome debugger to attach to both Electron processes, we use a composite configuration that firsts starts the Electron main process, followed by a Chrome debugger attaching to the launched Renderer process.

It takes 500ms-1000ms for the Main process to start, so when using a Composite configuration the Chrome config fails immediately if target can't be reached (no connection), which causes the composite experience to fall apart.

This happens regardless of the timeout setting, which I suspect only works when a connection has been established, but the right target hasn't been found. We should change this logic to retry connecting within the timeout period.

**Demo project:** 
https://github.com/auchenberg/electron-quick-start-vscode

**Steps:**
Try to use the "Electron: All" config and you'll get a `Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9223` warning, but if you start the two configurations manually it works.

This is blocking for us releasing our Electron recipe.

**Comment by auchenberg** [comment]
When using two instances of the `node` debugger things works as expected, so I would assume there's an implementation difference in how failed connections works.

**Comment by roblourens** [comment]
Someone reported this once and I couldn't repro. Will investigate.

**Comment by roblourens** [comment]
Oh dumb, it was due to the multiple target selection stuff in the extension host.

**Comment by auchenberg** [comment]
🔥

**Comment by roblourens** [comment]
I'll update the Chrome extension today with this fix.
