### ISSUE TITLE
How to lauch with specifig flag

### ISSUE THREAD

**Issue by LeMoussel** [Microsoft/vscode-chrome-debug#503]
To enable the experimental API in Chrome, You can do by this way: 
Specify the `--enable-experimental-extension-apis` flag each time you launch the browser. On Windows, you can do this by modifying the properties of the shortcut that you use to launch Google Chrome. For example: `path_to_chrome.exe --enable-experimental-extension-apis`

To use experimental API  in debug mode, How can I specify `--enable-experimental-extension-apis` flag?

**Comment by roblourens** [comment]
You can set that using `runtimeArgs: [...]`
