### ISSUE TITLE
Unable to debug typescript code

### ISSUE THREAD

**Issue by cac-software-factory** [Microsoft/vscode-chrome-debug#504]
- VS Code Version: 1.16.1

Steps to reproduce:

1.  Place a breakpoint on a line of ts code.
2.  Launch debugger using chrome, but breakpoint turns grey.  Hover says "Breakpoint ignored because gnerated code not found (source map problem?)"
3. I have run the `.scripts` command from the console.  After reviewing the results I see that none of the folders in my parent app folder are listed in the output from the `.scripts` command.
4. I am working on a project with a team of developers. Our folder structure is src>app>app1, src>app>app2, etc.
5. I see the sourcemapping for all of the other subfolders under app, but not mine. My subfolder is actually named 'analysis'.
6. Output of `.scripts` command is attached.

Thanks!

[scripts-command-output.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1307730/scripts-command-output.txt)

**Comment by auchenberg** [comment]
Looking at your `.scripts.` output it looks like your webpack sources are being mapped to `c:\projects\CUBWeb\node_modules\rxjs\operator\combineLatest.js` in ` webpack:\C:\projects\CUBWeb\node_modules\rxjs\operator\combineLatest.js (c:\projects\CUBWeb\node_modules\rxjs\operator\combineLatest.js)`. If this path isn't correct, please update your `webRoot` property in your `launch.json` config.

If you are missing files from your `analysis` path then these files aren't loaded in Chrome or included in your sourcemap generated by Webpack, which makes it impossible for VS Code to map back to your original source files.

Also it looks like you have multiple build systems in place as the some scripts are sourcemapped with `ng:///` namespace.

**Comment by cac-software-factory** [comment]
Thanks for your help and quick reply!  As it turns out, the problem was that I didn't have the proper imports in my app.module.ts, and so lacking a dependency chain, webpack wasn't pulling the typescript files.  Now the debugging and "stepping through the code" is working great!
