### ISSUE TITLE
No logs when attaching to chrome debugger for react native.

### ISSUE THREAD

**Issue by vettukal** [Microsoft/vscode-chrome-debug#505]
I can't see any console.log output when attaching the debugger to chrome for the react-native.

- VS Code Version: Version 1.16.1 (1.16.1)

Steps to reproduce:

1. Launch chrome with command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

2. in Launch.json the config is:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "diagnosticLogging": true,
            "port": 9222,
            "url": "http://localhost:8081/debugger-ui",
            "webRoot": "${workspaceRoot}"
        }
    ]
}

```
3. Attached the debugger.
4. output in debug console as follows:
```
Verbose logs are written to:
/var/folders/c5/7q9p3jtd1h99nwlmdsvwfpyshmyx6r/T/vscode-chrome-debug.txt
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.6
debugger-for-chrome: 3.2.1
Discovering targets via http://127.0.0.1:9222/json
Paths.scriptParsed: could not resolve http://localhost:8081/debugger-ui to a file under webRoot: /Users/16527/ios/dir2/myios-app. It may be external or served directly from the server's memory (and that's OK).
Target userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36
.scripts
› VM84
› http://localhost:8081/debugger-ui

```
Just wanted to ask, how can I see the logs in VSCode and also add breakpoints. 
P.S: I have tried react-native-debugger. Unfortunately that doesnot work for me. I guess this may be easier to setup.

**Comment by auchenberg** [comment]
Our Chrome debugger doesn't support React Native. We have a dedicated project, https://github.com/Microsoft/vscode-react-native, for this.

**Comment by auchenberg** [comment]
This issue was moved to Microsoft/vscode-react-native#537
