### ISSUE TITLE
Enhancement: Support --disable-web-security flag

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode-chrome-debug#506]
Hello,

It would be very beneficial to have the option for VSCode to launch Chrome with disabled web security. I need this flag on to test my local application before it goes to production, which causes me to temporarily ditch vscode-chrome-debug and use [this solution](https://stackoverflow.com/a/3177718/1404347). I wish it was an option on this vscode extension.

**Comment by roblourens** [comment]
You can set any flag you want with `"runtimeArgs": ["--disable-web-security"]`

**Comment by AskYous** [comment]
Thanks!

**Comment by Batur24** [comment]
Great! Thanks!
