### ISSUE TITLE
Demo image is not working

### ISSUE THREAD

**Issue by kmkanagaraj** [Microsoft/vscode-chrome-debug#508]
- VS Code Version:

Steps to reproduce:

1. Go to README.md
2. Click on 'Demo' link

Blank page appears with message 'Content length exceeded'

**Comment by auchenberg** [comment]
We don't have a "demo" link in our https://github.com/Microsoft/vscode-chrome-debug/blob/master/README.md

**Comment by kmkanagaraj** [comment]
Its here https://github.com/Microsoft/vscode-chrome-debug/blame/master/README.md#L22

**Comment by auchenberg** [comment]
Ah, that's our demo *image*, not a link. Thanks for the heads up!

**Comment by auchenberg** [comment]
Fixed in https://github.com/Microsoft/vscode-chrome-debug/commit/50fd20dbc6318babe9f61e3d22e74bd181f1860c
