### ISSUE TITLE
Exception breakpoint in Node 8.5.0

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-chrome-debug#510]
- VS Code Version:1.16.1

Steps to reproduce:

1. Use node 8.5.0
2. Trigger an UnhandledPromiseRejectionWarning with uncaught exception breakpoints turned on
3. This annoying async_hooks.js file is referenced in a breakpoint

![screen shot 2017-09-26 at 3 39 28 pm](https://user-images.githubusercontent.com/9585787/30850816-f3d6220c-a2d0-11e7-9ce3-f4175b9a4262.png)

**Comment by roblourens** [comment]
Yes, we are tracking this upstream at https://github.com/nodejs/node/issues/15464. It's a node bug.
