### ISSUE TITLE
Support sourcemaps with "sections" format

### ISSUE THREAD

**Issue by somewhatabstract** [Microsoft/vscode-chrome-debug#511]
We use sourcemaps that have the `sections` format. This plugin does not seem capable of consuming these, which means the sourcemaps don't load.

- VS Code Version: Version 1.16.1 (1.16.1)
- Debugger for Chrome Version: 3.3.0

Steps to reproduce:

1. Generate sourcemap with format like:
```
{
  "file": "myscript.js", 
  "sections": [
    {
      "map": {
        "file": "somemappedscript.js", 
        "mappings": "AAAA;AACA;AACA;AACA;AACA;AACA;AACA", 
        "names": [], 
        "sourceRoot": "/", 
        "sources": [
          "somemappedscript.js"
        ], 
        "version": 3
      }, 
      "offset": {
        "column": 0, 
        "line": 0
      }
    }, 
...
```

2. Try to debug in Chrome. The trace log shows that the map file is located and opened, but the sourcemap loader is assuming there is a single mapping in the file rather than multiple via the "sections" property.

Instead, it should recognise this format and map accordingly.

**Comment by roblourens** [comment]
Also https://github.com/Microsoft/vscode-chrome-debug-core/issues/217

What tool are you using that outputs sourcemap sections?

**Comment by somewhatabstract** [comment]
https://github.com/Khan/kake

Specifically, [this file](https://github.com/Khan/kake/blob/master/kake/sourcemap_util.py).

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/issues/217
