### ISSUE TITLE
Regression: runtimeExecutable no longer uses path

### ISSUE THREAD

**Issue by Ghostbird** [Microsoft/vscode-chrome-debug#512]
VSCode details:
Version 1.16.1
Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d
Date 2017-09-14T16:26:20.018Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Environment:
Debian 9

Steps to reproduce:
1. Create a Chrome launch configuration
2. Add the `runtimeExecutable` option that points to an executable on the path (e.g. `chromium`)
3. Launch this configuration
4. Receive error: `Attribute 'runtimeExecutable' does not exist ('chromium').`
5. Change `runtimeExecutable` to `/usr/bin/chromium` (or the correct equivalent for your environment)
6. Launch this configuration
7. Chromium launches

Previous behaviour (this was in VSCode 1.15 and earlier, but it was probably also with an earlier version of this extension):
1. Create a Chrome launch configuration
2. Add the `runtimeExecutable` option that points to an executable on the path (e.g. `chromium`)
3. Launch this configuration
4. Chromium launches

I think it is a bug with this extension because:

I change the launch configuration type from `chrome` to `node` with `runtimeExecutable` `chromium`. 
I launch that configuration, and Chromium launches immediately.

**Comment by roblourens** [comment]
Sorry, is this still an issue?
