### ISSUE TITLE
Allow configuration to launch custom resolution from 'Device Toolbar'

### ISSUE THREAD

**Issue by NiloCK** [Microsoft/vscode-chrome-debug#516]
I'm currently developing a web app for use in a school computer lab where the chromebooks have a 1366x768 resolution. It'd be nice if I could configure VSCode to launch chrome into this custom resolution.

Something like:

    "deviceHeight": 1366,
    "deviceWidth": 768

in launch.config would be ideal.

**Comment by auchenberg** [comment]
At this point in time I don't think we should expand the featureset to include emulation. Going forward with multiple connections this can be done from Chrome DevTools.
