### ISSUE TITLE
runtimeArgs option should omit regular Chrome arguments

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode-chrome-debug#518]
- VS Code Version: 1.16.1

When setting the `runtimeExecutable` to a custom program, I expected the `runtimeArgs` to be the exact list of arguments passed to that executable.  When the task was not launched I enabled the extension debugging and found that it *appends* these arguments to a fixed set of arguments:
* --remote-debugging-port=9222
* --no-first-run
* --no-default-browser-check

These should be omitted when the `runtimeExecutable` is specified because we may not be running Chrome.  In my case, I am running `cross-env` to set up environment variables before launching an electron app.

**Comment by roblourens** [comment]
Hm, I see the problem but this would break many Electron debugging configs. I think the typical usage of `runtimeExecutable` is to start with Electron, some script that starts a Chrome-like runtime, or the path to Chrome, e.g. I often use it for Canary.

Thoughts @auchenberg? A setting that disables the default runtime args?

**Comment by roblourens** [comment]
Does it break `cross-env` to specify args that it doesn't support?

**Comment by roblourens** [comment]
I see you're already on top of that one in https://github.com/Microsoft/vscode-chrome-debug/pull/520 :)

**Comment by jpap** [comment]
Thanks for your quick reply!

> Does it break cross-env to specify args that it doesn't support?

Unfortunately yes.

```
$ node_modules/.bin/cross-env echo hello world
hello world
$ node_modules/.bin/cross-env --no-first-run echo hello world
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn --no-first-run ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
$ 
```

> And, there is an issue to support setting environment variables. I would gladly support that if it avoids the issue entirely.

I submitted a [PR for that several hours ago](https://github.com/Microsoft/vscode-chrome-debug/pulls); appreciate your review.

While doing so doesn't appear to affect execution of Electron, I'd still prefer a way to drop those "default" arguments.  Would you be OK with having a second mutually exclusive option for runtime arguments, that if set, would drop the default arguments?

**Comment by jpap** [comment]
Ping @roblourens :-)

**Comment by roblourens** [comment]
Ping @auchenberg? I would like an option like `suppressTypicalRuntimeArgs` that would skip adding those the default runtime args.

**Comment by auchenberg** [comment]
Not huge fan of introducing options that disables the Chrome specific behavior, as the purpose of this adaptor is to a Chrome debug adaptor. To me this speaks for a "generic CDP adaptor" or an Electron specific one,/

That said we already got the `noDebug` argument in https://github.com/Microsoft/vscode-chrome-debug/blob/master/src/chromeDebugAdapter.ts#L64, and we could move the following line up, so chromeArgs are constructed when `noDebug` is false?

**Comment by roblourens** [comment]
Yeah I don't know. I'm not a big fan of using `noDebug` for this because I would still want those options set when running with noDebug.

**Comment by auchenberg** [comment]
@jpap `runtimeArgs` already get's set to `option 1`. The problem here is that `runtimeArgs` argument appends to the default today, and in your scenario you want to override.

We could add a `disableDefaulRuntimeArgs` option, but this is really a scenario that our debugger isn't designed for. This use-case should be contributed to https://github.com/octref/vscode-electron-debug/

**Comment by jpap** [comment]
> @jpap runtimeArgs already get's set to option 1. The problem here is that runtimeArgs argument appends to the default today, and in your scenario you want to override.

It's more subtle than that: the current "default" is actually []. (See the `package.json` definition.)

You might say that the three arguments discussed above aren't defaults at all, but "hidden prefix arguments".  That is, by setting `runtimeArgs` to anything, we can't actually override them.

The first option I gave promotes these three arguments to proper defaults that can be overridden by configuration.

> We could add a disableDefaultRuntimeArgs option, but this is really a scenario that our debugger isn't designed for. 

That can be a little misleading because there are no documented default runtime arguments. ;-)  (I found them when my executable wasn't running as expected and then by poking around in the code and looking at the adapter debug output.)

I totally understand how these three arguments came to be by virtue of this debug adapter being meant for Chrome, but there doesn't appear to be any other reason why this adapter can't be used with any executable that conforms to the Chrome DevTools Protocol.

> This use-case should be contributed to https://github.com/octref/vscode-electron-debug/

Even without these changes, Electron runs just fine so I'm not sure this cited repo needs any further contributions: what did you have in mind there?

**Comment by auchenberg** [comment]
@jpap The three arguments are default arguments that set by this Chrome specific debug adaptor, as they are an implementation detail and strictly needed to enable remote debugging for Chrome. Whether `runtimeArgs ` are defined in `package.json` as a empty array doesn't change this, but I understand why it can confusing. We are shielding developers from these arguments in the default `launch.json` as we aim to keep the configuration to a minimum.

The very problem here is that you are trying to use a Chrome specific adaptor to target another runtime, and if we don't want to change the existing behavior for `runtimeArgs` as it will break existing configurations used for Google Canary (and many unofficial Electron configurations). 

This debug adaptor isn't a genric CDP debugger, and the principle for our debug adaptors is that we have https://github.com/Microsoft/vscode-chrome-debug-core that serves as a generic debugging library for all Chrome DevTools protocol compatible targets, which is used by 8 **runtime specific debug adaptors**, which each implement runtime specific launch functionality (default arguments, runtime launch paths, etc)

My recommendation here is that you open an issue or simply work with [vscode-electron-debug](https://github.com/octref/vscode-electron-debug) to create a Electron specific or generic CDP debug extension that leverages [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core) that will work with your specific use-case.
