### ISSUE TITLE
Runtime executable is not terminated on debugger stop

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode-chrome-debug#521]
* VS Code Version: 1.16.1

Steps to reproduce:

1. Configure the extension to use a custom `runtimeExecutable` (e.g. Electron).
2. Start the debugger and verify that the runtime executable has started.
3. Stop the debugger. The runtime executable has not been terminated and continues to run.

I would have expected the runtime executable to be terminated by default when the debugger is stopped; though I'd be happy as a configurable opt-in.

**Comment by roblourens** [comment]
This works for me but there are platform and runtime differences that impact whether this works. Let me know if it's still an issue for you.
