### ISSUE TITLE
Source maps race on runtime executable start?

### ISSUE THREAD

**Issue by jpap** [Microsoft/vscode-chrome-debug#522]
- VS Code Version: 1.16.1

I can get breakpoints working with Electron (`launch` request via `runtimeExecutable` and `runtimeArgs`) and a webpack HMR server (via `preLaunchTask`), but **only** after the Electron app is launched and I "reload" it (View > Reload menu, or CMD-R on macOS).  In this case, the breakpoint in VSC is set before I start the debugger but only triggers after the reload.  The breakpoint is in the first (react) render pass of the app.

Is there a race condition between Electron starting and this VSC extension getting the source maps from the webpack HMR server?  If so, is there anything creative we can do about it...?

**Comment by auchenberg** [comment]
At this point in time we don't support break-on-load breakpoints. See https://github.com/Microsoft/vscode-chrome-debug/issues/445 for details.
