### ISSUE TITLE
Add the ability to control console log level in the Debug Console

### ISSUE THREAD

**Issue by Yohanna** [Microsoft/vscode-chrome-debug#523]
Currently the extension displays all output information in the console, it would be helpful to add an option to control what console level (log, error, warn..etc) to print, the same way Chrome's console does it:

![image](https://user-images.githubusercontent.com/6926228/31288008-4357f752-aa91-11e7-9a5d-a4e8ad396779.png)

**Comment by roblourens** [comment]
This is a feature request on vscode: https://github.com/Microsoft/vscode/issues/20838
