### ISSUE TITLE
using webpack -react, chrome debugger doesn't stop at any files

### ISSUE THREAD

**Issue by mhamri** [Microsoft/vscode-chrome-debug#525]
there is this strange behavior 

![image](https://user-images.githubusercontent.com/8991783/31384786-16b6535a-adf3-11e7-896f-468ebe0ea381.png)

the file in the debug panel is marked as ignored, but in the editor windows the break point is red, if the mapping was wrong then it was marked as gray. i checked my `.scripts` and mapping is correct. 

for example 

```
› webpack-internal:///174
    - webpack:///./src/index.js?9552 (c:\Users\pb\Documents\bitbucket\buesiness\pb-aweseome-frontend\src\index.js)
```

if i copy and run `c:\Users\pb\Documents\bitbucket\buesiness\pb-aweseome-frontend\src\index.js` in explorer i can open the file, so i assume the mapping is correct. 

my lunch json 

```JSON
{
         "name": "Launch localhost",
         "type": "chrome",
         "request": "launch",
         "url": "http://my.localhost:3000",
         "webRoot": "${workspaceRoot}",
         "sourceMaps": true,
         "trace": true
 }
```
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1371718/vscode-chrome-debug.txt)
[scripts-log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1371719/scripts-log.txt)
- VS Code Version:
1.17.0

**Comment by auchenberg** [comment]
Does this happen for all lines within the file? Try setting a breakpoint on `line 23` and see if it binds? Also try to refreshing the page in Chrome and see if it's hit.

**Comment by auchenberg** [comment]
Ah, please try changing your `devtool` setting to `eval-source-map` or `source-map` per https://webpack.js.org/configuration/devtool/.

This is probably because your generated sourcemaps doesn't contain enough information for our debugger.

**Comment by mhamri** [comment]
Thanks @Kenneth, it is working now

I changed it to `eval-source-map` and restart my npm and it is working fine
now

**Comment by auchenberg** [comment]
🎉
