### ISSUE TITLE
${webRoot} doesnt get resolved properly anymore

### ISSUE THREAD

**Issue by Morphexe** [Microsoft/vscode-chrome-debug#527]
I have been battling a issue, that I can't seem to figure out.

My launch setup : 

```  
{
      "type": "chrome",
      "request": "launch",
      "name": "DEV Chrome",
      "url": "http://localhost:1337",
      "webRoot": "${workspaceRoot}",
      "sourceMaps":  true,
      "trace": true
 },
```

A sample from the running the .scripts command gives me this which appears to be correct.

Its huge so I  just picking a couple, if need the complete, do tell, and I will gladly put it.

```
webpack:///./shared/components/App/ProfileRoute/Profile/Header/MatchVs/components/Avatar/index.js (${webRoot}\shared\components\App\ProfileRoute\Profile\Header\MatchVs\components\Avatar\index.js)
- webpack:///./shared/components/App/ProfileRoute/Profile/Header/MatchVs/components/Avatar/Team/index.js (${webRoot}\shared\components\App\ProfileRoute\Profile\Header\MatchVs\components\Avatar\Team\index.js)
- webpack:///./shared/components/App/ProfileRoute/Profile/Header/MatchVs/components/Bio/index.js (${webRoot}\shared\components\App\ProfileRoute\Profile\Header\MatchVs\components\Bio\index.js)
- webpack:///./shared/components/App/ProfileRoute/Profile/Header/Competition/index.js (${webRoot}\shared\components\App\ProfileRoute\Profile\Header\Competition\index.js)

```

Chrome launches, I can see the console logs on VScode, I can also see the correct source files from chrome console, but breakpoints are not being hit and are showing the (invalid source map).

Any ideas what might be causing this and how to fix?

**Comment by roblourens** [comment]
Is it actually writing out `${webRoot}` verbatim like that? If so it would seem that I'm not resolving that pattern in sourceMapPathOverrides correctly anymore...

**Comment by Morphexe** [comment]
Yes, that is copied directly from the .scripts command, I thought it was odd too at first, but I didn't had the time to actually look deeper.

**Comment by roblourens** [comment]
I can't repro this, if it still happens can you set `"trace": true` and upload the log?

**Comment by Morphexe** [comment]
This is not the same machine I was into originaly, but I am still unable to get the source maps to work.
[log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1404976/log.txt)
This one does not seem to have the webroot issue, but this is new machine with fresh install of both vscode and the extention.

Current Log :
[log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1404979/log.txt)
 

I can probably get you the log for the older machine later this week if that helps you out identifying what's going on with the ${webRoot}

**Comment by roblourens** [comment]
That log just shows attaching to a Chrome session that has a single script loaded, with no sourcemap, so it seems like you might have grabbed it early. I don't see script with those webpack sourcemap paths.
