### ISSUE TITLE
How to config http headers?

### ISSUE THREAD

**Issue by jesse1983** [Microsoft/vscode-chrome-debug#529]
Version 1.17.2 (1.17.2)

Hello guys!

Is possible to config http headers. Something like:

```json

{
    "type": "chrome",
    "request": "launch",
    "name": "Launch Chrome",
    "url": "http://localhost:8080",
    "webRoot": "${workspaceRoot}",
    "headers": {
      "Authorization": "access-key"
    }
}

```

**Comment by roblourens** [comment]
The extension doesn't send any web requests, it just points Chrome to a URL, so I'm not sure how to do auth automatically. I'm open to suggestions.
