### ISSUE TITLE
"chrome wasn't closed properly"

### ISSUE THREAD

**Issue by Franziskus1988** [Microsoft/vscode-chrome-debug#53]
Chrome often complains that it wasn't closed properly after debugging was stopped manually. 

Additionally when chrome is already running when starting debug session following error message appears: [webkit-debug-adapter] Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222.

Maybe one could start an own chrome instance like karma does.

**Comment by roblourens** [comment]
Thanks for pointing these out! I fixed the first issue in 0.1.11. The second issue unfortunately there's no easy way around besides closing Chrome before starting, or using attach mode, but I added the option `userDataDir`. You can set to a temp directory, then Chrome will start under a new user profile and will be correctly in remote debugging mode.
