### ISSUE TITLE
Using Chrome Canary Issue

### ISSUE THREAD

**Issue by bajras** [Microsoft/vscode-chrome-debug#531]
I was able to open the Chrome Canary from the JSON setting but I get the following error right away. 

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).`

Here my Setting:

![screen shot 2017-10-26 at 3 00 56 pm](https://user-images.githubusercontent.com/3359989/32074262-70a08d64-ba5e-11e7-9c75-6da4cfac9e13.png)

**Comment by auchenberg** [comment]
@bajras Do you happen to have other instances of Chrome Canary running?

**Comment by bajras** [comment]
VsCode opens a new tab in the Canary when I try it. If there are other tab opened alreadu it doesn't work and get that error but if I close Canary as a whole and open the debugger it works fine and then if I open a new tab that works fine too.

**Comment by auchenberg** [comment]
@bajras Can I get you to `trace: "verbose"` in your launch.json and paste/attach the full log in here? Looks like Chrome canary might be started with some wrong parameters.

**Comment by auchenberg** [comment]
Ah, this happens because we don't set a special Chrome profile when a `runtimeExecutable` are specified. Most likely as this is to enable Electron debugging.

To overcome this you can set the `userDataDir` property to a unique path and chrome will store the user profile settings there.

https://github.com/jpap/vscode-chrome-debug/blob/bc51a348481ae56d61308f807975d7706dd5ab03/src/chromeDebugAdapter.ts#L77

**Comment by bajras** [comment]
`HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
Discovering targets via http://127.0.0.1:9222/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).","body":{"error":{"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222","_timeout":"10000"}}}}
From client: disconnect({"restart":false})
Terminated: Got disconnect request
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"event","event":"terminated"}
Killing Chrome process
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}`

**Comment by auchenberg** [comment]
@bajras Use a config as the following if you already run Chrome Canary in parallel

```
    {
      "type": "chrome",
      "request": "launch",
      "name": "Chrome Canary",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/client",
      "runtimeExecutable": "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
      "userDataDir": "${workspaceRoot}/.vscode/chrome"
    }
```

**Comment by bajras** [comment]
@auchenberg that worked like it used to in stable chrome. Thanks. 

I had a question, does it have to open in a new Chrome on its own all the time than just opening the debug in an already opened window as a new tab?
<img width="103" alt="screen shot 2017-10-30 at 5 48 42 pm" src="https://user-images.githubusercontent.com/3359989/32199501-ce5aa07c-bd9a-11e7-9947-c1eb587dc60b.png">

**Comment by auchenberg** [comment]
@bajras Yes, unless you have started Chrome with remote debugging enabled, we have to start a new instance of Chrome with remote debugging and a new user profile, as we can't enable it on demand from the outside.

**Comment by bajras** [comment]
@auchenberg got it. Thanks for the help. Cheers.

**Comment by doque** [comment]
I'm using the [config mentioned above](https://github.com/Microsoft/vscode-chrome-debug/issues/531#issuecomment-340517087), but it fails for me with this error:

```
To client: {
    "body": {
        "error": {
            "format": "Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).",
            "id": 2010,
            "variables": {
                "_error": "Got a response from the target app, but no target pages found",
                "_timeout": "10000"
            }
        }
    },
    "command": "launch",
    "message": "Cannot connect to runtime process, timeout after 10000 ms - (reason: Got a response from the target app, but no target pages found).",
    "request_seq": 2,
    "seq": 0,
    "success": false,
    "type": "response"
}
```

(Full log here)[https://gist.github.com/doque/ea9c67b09611fa624d99a5b0bdad50e6].

The Canary window opens shortly (until the error with 10000ms timeout occurs), but debugging is not possible.

**Comment by bajras** [comment]
@doque Does it open a new instance of chrome for you or does it open in the same opened chrome canary?

**Comment by doque** [comment]
Yes, it's a new instance, with no user settings. The data dir is created inside `.vscode/chrome` as well.

**Comment by bajras** [comment]
@auchenberg should be able to help you :) he's the best.

**Comment by roblourens** [comment]
Most likely there is something else using that port
