### ISSUE TITLE
Stepping buttons in chrome do not appear after pausing or after hitting a breakpoint

### ISSUE THREAD

**Issue by 435vic** [Microsoft/vscode-chrome-debug#534]
This issue is not really that important, but it has been bugging me.
When my .js file hits a breakpoint or is paused, in the site there are no buttons for stepping over or restarting. 

My VS Code is version 1.17.2.

# How to reproduce
1. Debug any project in any mode (launching, attaching)
2. Pause or hit a breakpoint
3. If you reload in VS Code Debug menu, you will see the chrome buttons for a short time.

**Comment by roblourens** [comment]
I'm not sure what you mean. Are you asking about these buttons in Chrome

![image](https://user-images.githubusercontent.com/323878/32155344-0dd6e960-bcf4-11e7-8c34-b3ba4a70887d.png)

or these buttons in vscode

![image](https://user-images.githubusercontent.com/323878/32155351-18223118-bcf4-11e7-81df-12ad5caed369.png)

**Comment by 435vic** [comment]
Oh, sorry. I am reffering to the first ones, th ones that are injected into the chrome webpage.

**Comment by roblourens** [comment]
And they aren't appearing at all?

**Comment by 435vic** [comment]
Precisely. And what's most bizarre is that if I hit the restart button in VS Code, the buttons appear for less than half a second before dissappearing again.

**Comment by roblourens** [comment]
Can you try running with `"trace": true`, then upload the log file from the path it prints at the top of the debug console?

**Comment by 435vic** [comment]
When I save `trace: true` in launch.json, nothing appears in the debug console.

**Comment by roblourens** [comment]
Are you sure? You should see

![image](https://user-images.githubusercontent.com/323878/32200415-c3a3f6c6-bd8e-11e7-9b0c-20148140fa63.png)

**Comment by 435vic** [comment]
Yes. Not when it connects, or when it closes.

**Comment by 435vic** [comment]
Sorry, I put that statement in the attaching config, not the one I was using. So, here are the logs:
https://pastebin.com/CeQJHSQ1
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1429112/vscode-chrome-debug.txt)

Both are the same, if you were wondering.

**Comment by roblourens** [comment]
Thanks. The log doesn't show the app being paused. Can you repro the whole scenario for the log? Hit a breakpoint, see that the buttons are not visible, press restart where you see them briefly.

**Comment by 435vic** [comment]
Here is the new log, and a video of what I did. The logs were generated from what I did in the video.
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1429153/vscode-chrome-debug.txt)
[here is the video](https://youtu.be/izVGvqVQ_PU)

**Comment by roblourens** [comment]
Thanks for the video and log. The log shows the extension doing exactly the right thing, but I see that Chrome is not showing the overlay as it should. This looks like a Chrome bug.

Is that a canvas element on that page? I wonder if it's related to that? Can you test any other pages, or can you share the project for me to try?

**Comment by roblourens** [comment]
And if you debug it in chrome devtools, do you see the overlay?

**Comment by 435vic** [comment]
You were right! The `canvas` element was interfering with the overlay. I tried it on another page, but it worked as expected. one thing is that when I open devTools in chrome the connection closes, so I´m not able to inspect the page. So with this knowledge, is there a way to make it work wit a page that has a canvas?

**Comment by roblourens** [comment]
> one thing is that when I open devTools in chrome the connection closes, so I´m not able to inspect the page

Only one developer tool can be attached to the page, currently. But this will change in the future with chrome's multi-connection work.

>So with this knowledge, is there a way to make it work wit a page that has a canvas?

I have no idea, but you could file a bug at crbug.com
