### ISSUE TITLE
[Question] Using a `Launch Chrome` as `preLaunchTask`

### ISSUE THREAD

**Issue by stoffeastrom** [Microsoft/vscode-chrome-debug#535]
When doing multi target debugging it would be cool to be able to have a `launch` configuration as `preLaunchTask`. Then I don't have to manually start my `Launch Chrome` and then start another node launch that uses chrome debugging protocol to drive the launched headless chrome. It works really good using it manually without the "refresh" problem that others reported. This might already be possible but I haven't found it yet. Thanks for this awesome extension!!!

**Comment by roblourens** [comment]
This is the purpose of a "compound" launch config. See details here: https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations, try it out!
