### ISSUE TITLE
not support webpack HMR

### ISSUE THREAD

**Issue by lerit** [Microsoft/vscode-chrome-debug#536]
i want to know,if this plugin support HMR with out refresh full page.
- VS Code Version:
1.17.2
Steps to reproduce:
1.
i use webpack with hot-reload(use webpack-hot-middleware)
2.
i set breakpoint,and it work.
3.
i modify js code,save it ,webpack use HMR to reload this module:
[HMR] Checking for updates on the server...
process-update.js:41
[HMR] Updated modules:
process-update.js:114
[HMR]  - ./client/base/api/overhaul/procedure.js  **(this is the module i modified)**
[HMR] App is up to date.
4.
i want trigger the breakpoint by some operation,but it not work.
5.
i refresh the page,and it work again.

**Comment by auchenberg** [comment]
Webpack HMR should be working fine with our debugger, and is demonstrated in https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f/

Can you please provide more details on your specific setup, and preferably with a demo/example project for validation.
