### ISSUE TITLE
Debug session stops when opening the Developer Tools

### ISSUE THREAD

**Issue by maximedupre** [Microsoft/vscode-chrome-debug#54]
I am very grateful for this VSC plugin, it's really simplifying my debugging process. There is one thing, however, that is really bugging me. Whenever I open the Chrome Dev Tools, the debugging session stops and I have to constantly "reattach" to the browser. It isn't rare that I need to check the "Network" or "Elements" tab of the Dev Tools when I am coding. Is it a normal behaviour? Can it be fixed?

I am running OS X version 10.11.1.

Hopefully, this ticket isn't the same as #18.

Cheers!

**Comment by roblourens** [comment]
Yeah, so Chrome only allows one tool to be attached at a time. If you open Chrome Dev Tools, it kills the connection with the extension. There's no way around it, as far as I know :(

**Comment by maximedupre** [comment]
Ah, dammit! So be it then, I'll just stick to "reattaching" until a solution has been found. You can close this ticket. Thanks a lot!
