### ISSUE TITLE
Set breakpoints in actual src file with react/webpack/babel

### ISSUE THREAD

**Issue by xtapa** [Microsoft/vscode-chrome-debug#541]
- VS Code Version: 1.18.0

Steps to reproduce:

I've set up the launch.json and it actually works fine after a bit of browsinf for errors. The problem is, that I'm working with webpack and it is set to bundle my react-redux files ('C:\Projects\FacilityRegister\gui\src') via babel to another folder ('C:\Projects\FacilityRegister\out\prgFiles\html'). So trying to add the src folder as webRoot didn't work at all, so I've set webRoot to my output folder since these are the actual served files. But this ain't gonna help me as these files are automatically generated.
Is there any way to debug from my actual source files?

**Comment by roblourens** [comment]
Depends on what's in the sourcemap. Can you include the output of the `.sources` command?

**Comment by xtapa** [comment]
Sry, forgot to at that:

› https://wjhei01.d-velop.de/facilityregister/js/app.js (c:\Projects\FacilityRegister\out\prgFiles\html\js\app.js)
› https://wjhei01.d-velop.de/facilityregister/root?id=0&type=TYPE_SITE (c:\Projects\FacilityRegister\out\prgFiles\html\root)
› https://wjhei01.d-velop.de/facilityregister/vendor/dvelop-dapi/dapi.js (c:\Projects\FacilityRegister\out\prgFiles\html\vendor\dvelop-dapi\dapi.js)
› https://wjhei01.d-velop.de/facilityregister/vendor/dvelop-dux/dux.min.js (c:\Projects\FacilityRegister\out\prgFiles\html\vendor\dvelop-dux\dux.min.js)
› https://wjhei01.d-velop.de/shell/scripts/shell.js

**Comment by auchenberg** [comment]
We recommend using create-react-app, and here's a guide on how to get going: https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f
