### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by Johnny002** [Microsoft/vscode-chrome-debug#544]
- VS Code Version: 1.18.0 

Steps to reproduce:

1. Install Visual Studio Code on mac
2. Install chrome debugger
3. Install Chrome
4. Create new angular project using angular cli
5. Create debug configuration with below content:
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200/",
      "port": 4200,
      "sourceMaps": true,
      "trace": true,
      "webRoot": "${workspaceRoot}/src/index.html",
      "userDataDir": "${workspaceRoot}/out/chrome",
      "runtimeExecutable": "Applications/Softwares/Google Chrome.app"
    }
  ]
}
6. Error will print on debug console as:
Verbose logs are written to:
/var/folders/gq/k8r872117fq8swx9lff5528w0000gn/T/vscode-chrome-debug.txt
Error processing "launch": Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:390:9)
    at ChromeDebugAdapter.spawnChrome (/Users/vatish/.vscode/extensions/msjsdiag.debugger-for-chrome-3.5.0/out/bundle.js:386:48)
    at launch.then (/Users/vatish/.vscode/extensions/msjsdiag.debugger-for-chrome-3.5.0/out/bundle.js:246:37)
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1463679/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
This does not look right: `"runtimeExecutable": "Applications/Softwares/Google Chrome.app"`. Try removing that property entirely, the extension should be able to find Chrome automatically. If you have Chrome installed to an unusual location, make sure it's set correctly.

**Comment by roblourens** [comment]
And an example of a correct path to Chrome would be like `"/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary"`

**Comment by Johnny002** [comment]
Thanks it solved my issue. 👍
