### ISSUE TITLE
Gulp devstack - Breakpoint ignored because generated code not found (source map problem )

### ISSUE THREAD

**Issue by DavidSlavik** [Microsoft/vscode-chrome-debug#546]
Hello,

I would like to ask you for help with debugging...

- VS Code Version: 1.18.0

I'm using gulp devstack where in dev mode I have app.js file with all bundled js file without minification. Am I able to run debugging if I have this kind of devstack with browser sync reloading? I don't understand how it works inside...

In working directory i have all my js files in folder /src/app and when I start my project target file is on http://localhost:3344/js/app.js

Here is the link to our devstack where you can see folders structure etc. : https://github.com/actum/gulp-dev-stack

When I call '.script' I can see a lot of paths under the http://localhost:3344/js/app.js like a js libraries from node_modules or files from my project.

This is my launch.json:
{
    "version": "0.1.0",
    "configurations": [
        {
            "type": "chrome",
            "name": "Attach to Chrome",
            "request": "launch",
            "url": "http://localhost:3344",
            "webRoot": "${workspaceRoot}/src/app"
        }
    ]
}

Can you help me, please?

**Comment by roblourens** [comment]
> When I call '.script' I can see a lot of paths under the http://localhost:3344/js/app.js like a js libraries from node_modules or files from my project.

Are the paths right or wrong? This is the best way to see how the extension is resolving paths.

**Comment by DavidSlavik** [comment]
I think so, but I'm not sure how to set options if I'm bundling a lot of files into one. 

Debugger works fine in simple project without bundle or minification.

There is picture with all perspectives of files in my project.

1. Chrome dev tools
2. File structure in Visual studio code
3. Debug console with .scripts call
4. Visual Studio debug
5. launch.json
5. File system in Total commander

Thank you very much for your help!!!

I promise you public sample of my project when we will solve how to set debugging, like a sample with devstack based on gulp :-). I think, that it will be helpful for the others...

**Comment by roblourens** [comment]
I cloned the dev-stack repo to test my guess, but it isn't built with sourcemaps, and I can't figure out  what I need to enable them. But that's ok, I think what you need is to add an entry like this:

```
"sourceMapPathOverrides": {
    "*": "${workspaceRoot}/*"
}
```

Basically you can see that the sourcemap paths (`src/app/components`) are correct relative to the root, but the sourcemaps were probably copied into `dist/` during the build without having their paths updated. So it thinks all the sources are under `dist/`.

**Comment by DavidSlavik** [comment]
Thank you very much! I will try it when I will come to office. I will let you know.

If you want run our devstack with sourcemaps generating, run them with command:

`gulp --dev`

Sourcemaps will be generated into /dist/js/app.js.map

**Comment by DavidSlavik** [comment]
It works!!! Thanks a lot!!! You are nice and powerful :-).

I update our devstack with laung.json file and complete [documentation](https://github.com/actum/gulp-dev-stack#debugging-with-visual-studio-code-debugger-for-chrome).

You can add this use case into your wiki, because our devstack is public.

I think that it could be very helpful, if you will add to your documentation some informations about support with devstacks without webpack.
