### ISSUE TITLE
Node "attach" debugging - breakpoints ignored because generated code not found

### ISSUE THREAD

**Issue by aarestad** [Microsoft/vscode-chrome-debug#549]
Having trouble getting VS Code to see my code. Here is the relevant info:

- VS Code Version: 1.18.0

Launch.json contents:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "port": 9229,
      "protocol": "inspector",
      "sourceMaps": true,
      "outFiles": ["${workspaceFolder}/code/build/**/*.js"]
    }
  ]
}
```

Output of `.scripts`:

```
/Users/peter.aarestad/sundial/code/build/server/server.js
    - webpack:///webpack/bootstrap 1cfe6a47cd8c549d87e9 (/Users/peter.aarestad/sundial/code/build/server/webpack:/webpack/bootstrap 1cfe6a47cd8c549d87e9)
    - webpack:///./client/components/AppBar/index.jsx (${webRoot}/client/components/AppBar/index.jsx)
    - webpack:///./client/components/PasswordToolTip/index.jsx (${webRoot}/client/components/PasswordToolTip/index.jsx)
    - webpack:///./client/components/SimpleInput/index.jsx (${webRoot}/client/components/SimpleInput/index.jsx)
    - webpack:///./client/components/ToggleablePasswordInput/index.jsx (${webRoot}/client/components/ToggleablePasswordInput/index.jsx)
(etc)
 - webpack:///./server/cognito/CognitoApiFactory.js (${webRoot}/server/cognito/CognitoApiFactory.js)
    - webpack:///./server/cognito/authenticationApi.js (${webRoot}/server/cognito/authenticationApi.js)
    - webpack:///./server/cognito/models/Role.js (${webRoot}/server/cognito/models/Role.js)
    - webpack:///./server/cognito/models/User.js (${webRoot}/server/cognito/models/User.js)
    - webpack:///./server/components/html.js (${webRoot}/server/components/html.js)
(etc)
```

Let me know if you need more info. Thank you!

**Comment by auchenberg** [comment]
Note: ${webRoot} doesn't seem to get resolved properly

**Comment by roblourens** [comment]
Oh, I shouldn't do that when webRoot is not set. But in this case you need to set the webRoot property in your launch config. It needs to be the directory from which the server is serving files.

**Comment by auchenberg** [comment]
This is a node config. Do we support `webRoot` for node too?

**Comment by roblourens** [comment]
The launch config says "node" but the default sourceMapPathOverrides of node don't include webRoot, so did you actually run this with chrome?

**Comment by aarestad** [comment]
Nope - this is an attempt to debug a running Node process. It appears to connect, but Code keeps telling me that the breakpoints won't work because it can't find the source.

**Comment by roblourens** [comment]
Ok, well your `.scripts` output is confusing then. Can you set `"trace": true` in the launch config, repro it, and upload the log from the path it prints in the debug console?

**Comment by aarestad** [comment]
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1483153/vscode-node-debug2.txt)
Sure thing - log attached.

**Comment by aarestad** [comment]
Ah jeez. Did I file this bug in the wrong place? :< Sorry about that - go ahead and close if you want to and I'll refile in the right place.

**Comment by aarestad** [comment]
Reopening in the right place: https://github.com/Microsoft/vscode-node-debug/issues/164 Sorry to bug you guys. <3
