### ISSUE TITLE
[webkit-debug-adapter] Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by ffaubry** [Microsoft/vscode-chrome-debug#55]
I followed all the steps in the README.md for the Launch or Attach methods.
I have no other dev tools open.

I'm on a Mac 'El Capitan'.

**Comment by roblourens** [comment]
Was Chrome already open when you tried to run the launch config? When you get that message and Chrome is open, can you navigate to `http://localhost:9222` in a browser?

**Comment by pierznj** [comment]
I had this too. Tried everything. It worked after restarting the Mac.

**Comment by kowsheek** [comment]
:+1: I had this issue as well. Restarting Chrome fixed it.

**Comment by ffaubry** [comment]
As suggested, I restarted my Mac and now it's working.

**Comment by dsvaughan** [comment]
It was working fine for me and now I am getting the same error.  I have tried rebooting my PC with no success

**Comment by ffaubry** [comment]
@dsvaughan I found that it's trying to reuse my current chrome instance. I had to kill it then launch the debugger and all my tabs were lots etc. (not fun).
I discover that if you set this property "userDataDir" to a local dir like "./tmp" ("userDataDir": "./tmp") and it will launch a new instance of chrome and not conflict with the running instance.

**Comment by justin-romano** [comment]
if you had the chrome service (tray icon) still running for things like hangouts and chat then you need to close that completely. Right click the chrome tray icon and exit from there. All sweet after that.

**Comment by roblourens** [comment]
Good catch on Chrome running in the background. That will cause this issue. It can be disabled if you right click on the tray icon (on Windows at least).

**Comment by roblourens** [comment]
I'll add a note to the README

**Comment by g-guth** [comment]
same problem here on windows and no success after restarting the computer.

**Comment by roblourens** [comment]
@g-guth do you see chrome running in the background? Try killing it

**Comment by szymczakk** [comment]
@g-guth For me, reloading PC (Win 8.1) and starting chromewith --remote-debugging-port=9222 as a first instance of chrome in system, helped.

**Comment by bhushanvaidya3** [comment]
Killing the chrome process in taskbar and closing all instances helped me. 

Also started chrome with --remote-debugging-port=_PORT_NO

**Comment by kowsheek** [comment]
Just so you don't have to keep starting with the debugger port assigned set the Chrome launcher target to `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222`

**Comment by lizhong8532** [comment]
If OSX system that how set start params to chrome application?

**Comment by navarrorc** [comment]
I had to run the VS Code as an Administrator and it worked.

**Comment by Arelav** [comment]
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome  --remote-debugging-port=9222

**Comment by wangbourne** [comment]
I'm on Mac el caption, I got the same error msg.

When I tried :localhost:9222  in Chrome, i got following message: 

This site can’t be reached
localhost refused to connect.
Search Google for localhost 9222
ERR_CONNECTION_REFUSED

**Comment by Darksoulsong** [comment]
I can launch it by running vscode with admin privileges, but this is not an option to me.

**Comment by rafaelstz** [comment]
```
{
    "name": "Launch index.html",
    "type": "chrome",
    "request": "launch",
    "file": "${workspaceRoot}/index.html",
    "userDataDir": "${workspaceRoot}/out/chrome",
    "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
}
```
