### ISSUE TITLE
Debug GWT(Java) code

### ISSUE THREAD

**Issue by dominicE** [Microsoft/vscode-chrome-debug#550]
- VS Code Version: Version 1.18.1 (1.18.1)

In our company we are working with gwt. I have to use the SuperDevMode and DevTools to debug the web application. But DevTools debugging is really bad so I want to debug using VS Code.

I installed the Chrome Debug Plugin.

(I replaced our company name with xyz)
```
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Debug",
            "url": "http://master.login.xyz.com/xyz/ui-backend/",
            "webRoot": "/workspace/localsystem/http",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "http:/127.0.0.1:9876/sourcemaps/xyz_ui/*": "${workspaceRoot}/src/*"
            },
            "trace": true
        }
```

When I start the debugging, it opens Chrome and loads the web page.
After that I execute .scripts in debug console and it looks like that the sources are mapped correctly. Here is an example line of output:

`- http:/127.0.0.1:9876/sourcemaps/xyz_ui/eu/xyz/client/view/user/login/InitialLoginView.java (/workspace/ui-ui/src/eu/xyz/client/view/user/login/InitialLoginView.java)`

The path on local file system is correct but I can't set a breakpoint. Why?

Is it because of Java? Is GWT not supported by chrome debugging?

**Comment by roblourens** [comment]
So you're compiling Java to javascript? As long as the sourcemaps are correct, it should work. So this path is exactly correct: `/workspace/ui-ui/src/eu/xyz/client/view/user/login/InitialLoginView.java`? Are the breakpoints gray or red? If gray, what message do you see if you hover over it?

**Comment by dominicE** [comment]
Yes,
it's Java to Javascript. In-IDE-Debugging is "working" with IntelliJ and "Jetbrains IDE Support"-Plugin but it's very unstable.
I checked the path and it's correct. The problem is, I can't set any breakpoint. If I click next to the line number (left to it) nothing happens.

**Comment by roblourens** [comment]
> I checked the path and it's correct. The problem is, I can't set any breakpoint. If I click next to the line number (left to it) nothing happens.

You should see a breakpoint decoration even just when hovering in that area. Can you post a screenshot?

**Comment by dominicE** [comment]
I found the problem.
There is a setting called
debug.allowBreakpointsEverywhere which is set to false per default (for me).
Setting this option to true I can set breakpoints and it's working now.

Thank you for your help :)

**Comment by roblourens** [comment]
Ah, that makes sense. Glad you figured it out!
