### ISSUE TITLE
Docs - incorrect trace log location for Windows

### ISSUE THREAD

**Issue by gwicksted** [Microsoft/vscode-chrome-debug#551]
- VS Code Version: `1.18.1`

OS: `Windows 10 x64`
Docs are latest repo hash `52ddf52`

Header of `vscode-chrome-debug.txt`
```txt
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.18.4
10:38:51 AM, 11/17/2017
debugger-for-chrome: 3.5.0
```

NOTE: I have NodeJS 9.0.0 x64 installed which outputs `v9.0.0` when `node -v` is typed in `powershell`.

- Steps to reproduce:

1. Navigate to https://github.com/Microsoft/vscode-chrome-debug#general-things-to-try-if-youre-having-issues
2. See path listed as `~/.vscode/extensions/msjsdiag.debugger-for-chrome-<version>/vscode-chrome-debug.txt`

There is an existing file in the `/out/` subdirectory **but it is not from my PC** (it originated on a Mac):

`~/.vscode/extensions/msjsdiag.debugger-for-chrome-<version>/out/vscode-chrome-debug.txt`

- The **correct path** was logged in the `DEBUG CONSOLE` in `vscode` as:

`C:\Users\<my-user-name>\AppData\Local\Temp\vscode-chrome-debug.txt`

which is: `~/AppData/Local/Temp` or simply `%temp%` in Explorer.

**Comment by roblourens** [comment]
Good point, fixed
