### ISSUE TITLE
Can't stop going into chrome extensions when stepping over (F10)

### ISSUE THREAD

**Issue by David-Else** [Microsoft/vscode-chrome-debug#553]
- VS Code Version:1.18.1

I don't know if this is a bug or a misconfiguration by myself, this is my first attempt at setting up a debugger so please be forgiving :)

I am on Linux and can run everything OK using Chromium and Rollup with sourcemaps all working great. Here is the results of .scripts on the command line:
```

.scripts
› VM2988
› chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/js/contentscript.js
› chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/js/vapi-client.js
› chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/js/vapi.js
› chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/clobbercookie.js
› chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/clobberlocalstorage.js
› chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/fingerprinting.js

› extensions::binding
› extensions::event_bindings
› extensions::fileEntryBindingUtil
› extensions::json_schema
› extensions::lastError
› extensions::messaging
› extensions::messaging_utils
› extensions::runtime
› extensions::schemaUtils
› extensions::sendRequest
› extensions::uncaught_exception_handler
› extensions::utils
› http://127.0.0.1:5500/
› http://127.0.0.1:5500/dist/bundle.js (/home/david/sites/natural-expression-calculator-application/dist/bundle.js)
    - ../node_modules/flatpickr/dist/flatpickr.js (/home/david/sites/natural-expression-calculator-application/node_modules/flatpickr/dist/flatpickr.js)
    - ../src/data.js (/home/david/sites/natural-expression-calculator-application/src/data.js)
    - ../src/main.js (/home/david/sites/natural-expression-calculator-application/src/main.js)

```
I am aware of the` skipFiles` option, here is my config:
```

{
    "version": "0.1.0",
    "configurations": [{
        "name": "Attach to Chromium when live-server running",
        "type": "chrome",
        "request": "attach",
        "skipFiles": ["flatpickr.js", "node_modules"],
        "port": 9222,
        "url": "http://127.0.0.1:5500/",
        "webRoot": "${workspaceRoot}"
    }]
}
```
Whenever I am debugging I seem to end up inside a chrome extension! I never want them to open up under any circumstance, and don't see why they would be doing that by default?

How can I tell this extension to ONLY debug the files that want debugging, not the internal files of Chrome? I tried blocking `"extensions::"` but just ended up going into some bizzare node file.

Many thanks!

**Comment by roblourens** [comment]
Does the same thing happen when you debug with Chrome devtools? Are you breaking on exceptions in those files?

If you step all the way to the end of some code, then it makes sense that another F10 would pause in whatever happens to run next, which might be chrome extension code.

**Comment by David-Else** [comment]
Thanks for getting back to me. I have actually never used a debugger before, never mind in Chrome devtools. I am now officially graduating from console.log :)

> If you step all the way to the end of some code, then it makes sense that another F10 would pause in whatever happens to run next, which might be chrome extension code.

I actually don't know why that would be, but I would like to stop it if possible. You are right, this is probably what is happening, but I seem to end up in all sorts of strange disturbing places whenever I start to try the debugger... a lot of them seem internal node files.

Is it possible to stop this behaviour? Thanks.

**Comment by eightbit** [comment]
I have run into the same issue.  During debug VSC opens **extensions::utils** tab in the editor.
Debugging would take forever to run through the code in this fashion.
Is there a way to prevent the debugger from opening external libraries?
Thanks.

**Comment by David-Else** [comment]
Hi, this is still bugging me 6 months later. I see we now have a blacklist function that goes in launch.json (which works well):

`"skipFiles": ["node_modules/**/*.js", "vue*"]`

so what exactly should we add to stop stepping into `extensions::utils` as it is not a file? Cheers!
