### ISSUE TITLE
Breakpoint ignored because generated code not found with dvajs 

### ISSUE THREAD

**Issue by mglcarmona** [Microsoft/vscode-chrome-debug#554]
I'm using dvajs to build an application and i'm unable to make vscode debugger work

This is my launch.json setup

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:8000",
      "webRoot": "${workspaceRoot}/src",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }
  ]
}
```

My file tree 
![screenshot 2017-11-26 01 13 36](https://user-images.githubusercontent.com/8413939/33237644-333b71f4-d247-11e7-9bf5-2928a318aa4b.png)

And my sourcemaps generated by webpack-dev-server
![screenshot 2017-11-26 01 17 11](https://user-images.githubusercontent.com/8413939/33237656-90a4d722-d247-11e7-9de1-cb8eddf7e870.png)

**Comment by lxxoolxx** [comment]
#547  the same problem also happened to me , and this issue solve my problem

**Comment by roblourens** [comment]
The sourcemaps structure looks different than the real file structure, for example there is webpack://components, and src/components from the project root. But then webpack://src/models, which is src/models from the project root. So sourcemapPathOverrides will have to reflect this.

Try something like


```json
"sourceMapPathOverrides": {
        "webpack:///src/*": "${workspaceFolder}/src/*",
        "webpack:///*": "${workspaceFolder}/src/*"
}
```

and debug with the `.scripts` command if that doesn't work

**Comment by mglcarmona** [comment]
@roblourens Thanks a lot! it now works fine :D
