### ISSUE TITLE
viewing local variables with real names in minify code (with sourcemaps) done by rollupjs

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode-chrome-debug#555]
This might not be a bug, but is it an inherent limit of debugging with VSCODE, since I don't get this using the native chrome debug GUI.

- VS Code Version: 1.18.1

1. I created a minify bundle.js with rollupjs and minify plugin and include inline source maps.

See below screen shot. The break-point is at line #110, which is in the updateSprite(sprite) function,

I wanted to look the value of the passed in variable sprite. I have stepped the program to line #112, at this point the local variable loc should be defined.

But if you look at the left of the VSCODE debug window, in the pane called local variables, you see only
this, i and t as being the variables defined. They have the correct values for sprite and loc, but are named i and t,

This is because I am using rollupjs to take the source, and bundle it and then minifiy it (I like rollupjs better than webpack for this work).

The VSCODE debugger is smart enough to use the sourcemaps in bundle.js to show the correct line, but it does not do the local variables. Is this a inherent limit in VSCODE?

Because the Chrome native debugger (F12) does not do this, it shows the local variables with the real names in the LOCAL VARS pane.

![image](https://user-images.githubusercontent.com/2865368/33446876-6d8f9926-d5cf-11e7-9abc-93a3ffe57962.png)

**Comment by roblourens** [comment]
This isn't supported yet: https://github.com/Microsoft/vscode/issues/12066
