### ISSUE TITLE
Debugging in multi-folder workspace

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/vscode-chrome-debug#556]
My setup:
* a project ("Demo") has two folders: "Server" and "Client"
* inside Client I have app code and lib code in node_modules:
![image](https://user-images.githubusercontent.com/1203230/33481030-d271b7e6-d6a3-11e7-9a5e-1d79de52ce87.png)
* Let's use the file app.ts as an example - `D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.ts`
* The client project has build script which combine app and lib files and copy them to the server - inside `Server\wwwroot\client` folder (it's a dotnet core/ASP.NET Core  app):
![image](https://user-images.githubusercontent.com/1203230/33481125-2d71df2c-d6a4-11e7-9b50-b1b7214f748d.png)
* so there're the following files exist:
  * in Client (src): 
    * D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.ts 
    * D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.js
    * D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.js.map
  * in Server (runtime):
    * D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Server\wwwroot\client\app\app.ts 
    * D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Server\wwwroot\client\app\app.js.map 
    * D:\Work\R-n-D\XFW3_WebClient-tools\Demo\Server\wwwroot\client\app\app.js 
 
Inside Client folder I create a `launch.json` with attach configuration:
```
            "name": "Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:5000/",
            "webRoot": "${workspaceRoot}/../Server/wwwroot",
```
This - `"webRoot": "${workspaceRoot}/../Server/wwwroot"` should look strangely as of "..", but it seems that `${workspaceRoot}` targets to a folder where `launch.json` located not a real root.

I can set breakpoints in js files if I open them from Server/wwwroot. When a breakpoint hits a corresponding ts file is opened and debugged fine. Good enough but I want to debug files not in Server/wwwroot but in Client/src/ 
As I can understand I should change `webRoot` in the launch configuration:
```
 "webRoot": "${workspaceRoot}/src"
```
The problem is that under Client/src I only have app files (code that the application owns), but lib code is under node_modules. So when I step into lib code from my ts file (in Client/src) I lose source mapping (got into js file from "running documents" not a src file on disk).

So probably I can summarize that my problem is in that I have several roots for src files to which runtime scripts should map. Can I do anything with it or it's unsupported?

**Comment by roblourens** [comment]
You should be able to do that. Can you post the output of the `.scripts` command?

The files in the runtime are probably like `http://localhost/client/app.js`. You could use 

```
"pathMapping": {
  "/client/*": "${workspaceRoot}/src/*"
}
```

or something like that to map them to the .js files in your Client directory.

**Comment by evil-shrike** [comment]
I tried adding `pathMapping`:
```
            "webRoot": "${workspaceRoot}/src",
            "pathMapping": {
                "/client/app/*": "${workspaceRoot}/src/app/*",
                "/client/*": "${workspaceRoot}/node_modules/@croc/webclient/src"
            }
```
files from app/src are mapped correctly (see the output of `.scripts` below) but not from node_modules:
```
› http://localhost:5000/client/app/app.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.js)
    - app.ts (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.ts)
...
› http://localhost:5000/client/lib/binding.js
    - binding.ts (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\client\lib\binding.ts)
```
Actually behavior hasn't  changed, the result is the same as without `pathMapping`.


If I remove `webRoot` (as it's described as shorthand for pathMapping): 
```
            "url": "http://localhost:5000",
            //"webRoot": "${workspaceRoot}/src",
            "pathMapping": {
                "/": "${workspaceFolder}/src",
                "/client/app/*": "${workspaceRoot}/src/app/*",
                "/client/*": "${workspaceRoot}/node_modules/@croc/webclient/src"
            }
```
then:
```
› http://localhost:5000/client/app/app.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\client\app\app.js)
...
› http://localhost:5000/client/lib/binding.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\client\lib\binding.js)
```
Not correct for both app and lib scripts.

Also I said that with `"webRoot": "${workspaceRoot}/src"` it works for app scripts at least. But now it doesn't - I'm getting an error (and breakpoints aren't hit).
It seems that I didn't change anything in the project, I only updated Node from 7.x to 9.x.
```
Error processing "setBreakpoints": TypeError: Cannot read property 'mappedPath' of undefined
    at BaseSourceMapTransformer.setBreakpoints (C:\Users\Sergei Dorogin\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:63:23)
    at validateBreakpointsPath.then (C:\Users\Sergei Dorogin\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-3.5.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:827:40)
    at <anonymous>
```

**Comment by roblourens** [comment]
You can ignore the error, it's tracked in https://github.com/Microsoft/vscode-chrome-debug-core/issues/256

I think you need to reorder your pathMapping entries so the longest string is first, as is tries to resolve them in key order (I know that's unexpected, I have another issue to handle that differently). Otherwise it takes the first key that matches, in this case `"/": "${workspaceFolder}/src"`

**Comment by evil-shrike** [comment]
>You can ignore the error,
Ok, but breakpoints are not working also. Not in js nor in ts files.

Here's with reverse order:
```
            "pathMapping": {
                "/client/*": "${workspaceRoot}/node_modules/@croc/webclient/src",
                "/client/app/*": "${workspaceRoot}/src/app/*",
                "/": "${workspaceFolder}/src"
            }
```
`.scripts` output:
```
› http://localhost:5000/client/app/app.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\client\app\app.js)
...
› http://localhost:5000/client/lib/binding.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\client\lib\binding.js)
```
incorrect paths and no source maps

**Comment by roblourens** [comment]
I think I led you incorrectly, `pathMapping` doesn't use a `*`. Try just removing the trailing `*` on those two.

**Comment by evil-shrike** [comment]
Yeah, right, now both paths are correct:
```
› http://localhost:5000/client/app/app.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.js)
    - app.ts (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\src\app\app.ts)
...
› http://localhost:5000/client/lib/binding.js (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\node_modules\@croc\webclient\src\lib\binding.js)
    - binding.ts (d:\Work\R-n-D\XFW3_WebClient-tools\Demo\Client\node_modules\@croc\webclient\src\lib\binding.ts)
```
and breakpoints hit.

Thank you very much!

**Comment by roblourens** [comment]
Great! I should change pathMapping to work with `*`, same as sourceMapPathOverrides.
