### ISSUE TITLE
Function Breakpoint support?

### ISSUE THREAD

**Issue by kannanwisen** [Microsoft/vscode-chrome-debug#559]
Hi,

Is Function BreakPoint supports in Debugger for Chrome?

Thanks

Kannan.S

**Comment by roblourens** [comment]
No, I don't think we have a good way to implement this with the Chrome debug protocol.

**Comment by auchenberg** [comment]
Chrome supports this via the console, https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints#function

**Comment by auchenberg** [comment]
Closing as we don't have a way to support this over CDP.

**Comment by kannanwisen** [comment]
Thanks
