### ISSUE TITLE
Can connect to Chrome but breakpoints don't work

### ISSUE THREAD

**Issue by pierznj** [Microsoft/vscode-chrome-debug#56]
I get a bunch of messages in the debug console, indicating I've successfully connected to Chrome but breakpoints do not work at all. I can pause the application, but trying to inspect the current line just shows:
DevToolsAPI.dispatchMessage({"method":"Network.dataReceived","params":{"requestId":"2045.237","timestamp":2830.405761,"dataLength":13,"encodedDataLength":18}});

The debug console has lots of lines like this:
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"1276","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":186,"sourceMapURL":""}}

Sometimes (haven't worked out under what exact circumstances) if I have a breakpoint, the application appears to stop as if the breakpoint had been hit, but in VS Code the breakpoint is not highlighted, nor can I see watch variables, stack trace and so on.

**Comment by pierznj** [comment]
Never mind, I had my webroot set incorrectly.

**Comment by pierznj** [comment]
Actually scratch that. It worked briefly, but now I'm back to the same problem, that the scripts are getting mapped to empty urls, despite having webroot set correctly now.

**Comment by roblourens** [comment]
The scriptParsed lines with empty urls are normal, those probably come from Chrome eval'ing things. I just noticed something that I overlooked that may have caused this on OS X, but I'm not sure whether it's the same problem you're seeing. I published a fix. If updating doesn't fix this, could you post the whole log?

**Comment by pierznj** [comment]
Indeed that seems to have done it! Thank you.

**Comment by roblourens** [comment]
Great!
