### ISSUE TITLE
Launch from other extension 

### ISSUE THREAD

**Issue by ArthurMenezes** [Microsoft/vscode-chrome-debug#561]
Is it possible to launch chrome-debugger from another extension? If so, how do I do it?

**Comment by roblourens** [comment]
You could invoke the action to start debugging - `workbench.action.debug.start`. Is that what you mean?

**Comment by ArthurMenezes** [comment]
I am trying to do the following: when executing a command (defined in the extension I am developing), read the behavior of the activeTextEditor and fire the chrome-debugger. In chrome there will be an installed chrome-extension, which will receive this script and inject the page.

This extension of vscode will serve as a development environment for scripts.

Can you understand?

**Comment by roblourens** [comment]
Not sure I understand, but you should be able to do whatever you need with the debug extension APIs - https://code.visualstudio.com/docs/extensionAPI/vscode-api#_debug

`startDebugging` to trigger a debug session, or possibly a DebugConfigurationProvider.

**Comment by ArthurMenezes** [comment]
In that case the debug would have to be done in the browser, since I want to inject the script contained in the vscode editor in a webExtension (https://developer.mozilla.org/en-US/Add-ons/WebExtensions) or a chrome extension ( https://developer.chrome.com/extensions).
So you want to know if I can launch vscode-chrome-debug from my vscode extension

**Comment by roblourens** [comment]
`startDebugging` will let you start vscode-chrome-debug, but I'm not sure how that helps you inject a script. 

You can send requests to the debug adapter if you want - I think you could theoretically send an "evaluate" request from your extension to the adapter, that would inject the script onto the page.

**Comment by ArthurMenezes** [comment]
And, please, how do I make this request? Would you help me?

**Comment by roblourens** [comment]
I haven't tried this but it might work - you can get the debug session from `vscode.debug.activeDebugSession`. Then on the DebugSession object - https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namedebugsessionaspan-classcodeitem-id1380debugsessionspan call `.customRequest` with 'evaluate' with EvaluateArguments https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L884

**Comment by ArthurMenezes** [comment]
vscode.debug.activeDebugSession is undefined even after using the startDebugging function. Here is my code:

`function activate(context) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "botwriter" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', function () {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.showInformationMessage('asihdiusahcuishic!');
    });
    vscode.debug.onDidStartDebugSession(startDebuggingListner);

    let runPage = vscode.commands.registerCommand('extension.runPage', function() {
        
        let activeWindow = vscode.window.activeWindow;
        let activeTextEditor = vscode.window.activeTextEditor;
        //activeTextEditor.document.getText() //pega o conteudo do editor ativo(com foco)
        // let 
        console.log(activeWindow);
        console.log(activeTextEditor);
        // vscode.debug.
        let chromeDebugUri = vscode.workspace.workspaceFolders[0].uri;
        let debug = vscode.debug.startDebugging(
            vscode.workspace.getWorkspaceFolder(chromeDebugUri),
            "Launch Chrome TST"
            // "Attach with sourcemaps"
        );
        debug.then(function (result) {
            console.log(result);
            console.log(vscode);
            console.log(vscode.extensions.getExtension("msjsdiag.debugger-for-chrome"));
        }).catch(erro => {
            throw new Error(erro);
        });
    });

    context.subscriptions.push(disposable);
    context.subscriptions.push(runPage);
}`

And here's my launch.json of another project (which contains the script to be injected)

`{
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome TST",
            "userDataDir": false,
            "console": "internalConsole",
            "diagnosticLogging": true,
            "trace": "verbose",
            "sourceMaps" : true ,
            "url": "http://www.tst.jus.br/processos-do-tst"
            
        }`

**Comment by roblourens** [comment]
Where are you using activeDebugSession? I think you omitted startDebuggingListener.

**Comment by ArthurMenezes** [comment]
I'm using the vscode console, inside the startDebugging then. In the vscode documentation, it does not say anything about using listeners, so I did not find it necessary.

**Comment by roblourens** [comment]
Sorry, I don't understand. You said activeDebugSession is undefined, and I appreciate the code sample, but it doesn't reference activeDebugSession.

**Comment by ArthurMenezes** [comment]
Sorry if I was not clear, inside the then I activate a brake point, and in the console I see that vscode.debug.activeDebugSession is undefined

`debug.then(function (result) {
        console.log(result);   // break point here
        console.log(vscode);
        console.log(vscode.extensions.getExtension("msjsdiag.debugger-for-chrome"));
    }).catch(erro => {
        throw new Error(erro);
    });`

**Comment by roblourens** [comment]
I think you mean `console.log(vscode.debug.activeDebugSession)` instead of `getExtension`? Don't know why you're using `getExtension`.

**Comment by ArthurMenezes** [comment]
Got it. everything that is in console, is simply tests, to know the values of the properties at that moment, nothing important.
But it does not change the fact that vscode.debug.activeDebugSession is undefined. That I did not understand yet. I'll change the code to be clearer. Sorry for that failure.
`
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
const vscode = require('vscode');

function startDebuggingListner(event) {
    console.log("Estou no listner");
    console.log(event);
}

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
function activate(context) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "botwriter" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', function () {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.showInformationMessage('asihdiusahcuishic!');
    });
    vscode.debug.onDidStartDebugSession(startDebuggingListner);

    let runPage = vscode.commands.registerCommand('extension.runPage', function() {
        
        let activeWindow = vscode.window.activeWindow;
        let activeTextEditor = vscode.window.activeTextEditor;
        //activeTextEditor.document.getText() //pega o conteudo do editor ativo(com foco)
        // let 
        console.log(activeWindow);
        console.log(activeTextEditor);
        // vscode.debug.
        let chromeDebugUri = vscode.workspace.workspaceFolders[0].uri;
        let debug = vscode.debug.startDebugging(
            vscode.workspace.getWorkspaceFolder(chromeDebugUri),
            "Launch Chrome TST"
            // "Attach with sourcemaps"
        );
        debug.then(function (result) {
            console.log(result); //test
            console.log(vscode); //test
            console.log(vscode.debug.activeDebugSession); //undefined
        }).catch(erro => {
            throw new Error(erro);
        });
    });

    context.subscriptions.push(disposable);
    context.subscriptions.push(runPage);
}
exports.activate = activate;

// this method is called when your extension is deactivated
function deactivate() {
}
exports.deactivate = deactivate;`

**Comment by roblourens** [comment]
@isidorn is activeDebugSession expected to be undefined after the promise from `startDebugging` resolves? I tried this and it's undefined after onDidStartDebugSession too:

```
vscode.debug.onDidStartDebugSession(() => {
            console.log(vscode.debug.activeDebugSession);
});
```

**Comment by isidorn** [comment]
@roblourens this is a nice catch and I just fixed it via 430d61688a 
There are still some flaws with regards to the active session / thread and I plan to improve this via https://github.com/Microsoft/vscode/issues/18426

**Comment by ArthurMenezes** [comment]
So what should I do? Wait for a new official version of vscode, or can I download the project here and do the build?

**Comment by roblourens** [comment]
I'm guessing you can work around it by taking the debug session from the event -

`vscode.debug.onDidStartDebugSession(debugSession => ...`

**Comment by ArthurMenezes** [comment]
> I haven't tried this but it might work - you can get the debug session from vscode.debug.activeDebugSession. Then on the DebugSession object - https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namedebugsessionaspan-classcodeitem-id1380debugsessionspan call .customRequest with 'evaluate' with EvaluateArguments https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L884

> I'm guessing you can work around it by taking the debug session from the event -
> 
> `vscode.debug.onDidStartDebugSession(debugSession => ...`


The customRequest documentation is not very clear to me. What kind of command is the first paramenter? Where can I find examples of using this method?
