### ISSUE TITLE
Docs Confusion: Unclear whether file system launching is supported

### ISSUE THREAD

**Issue by mgummelt** [Microsoft/vscode-chrome-debug#564]
The docs say both that "Both modes requires you to be serving your web application from local web server", and that "You must specify either file or url to launch Chrome against a local file or a url", which seem to contradict each other.

**Comment by roblourens** [comment]
Yeah, a local webserver is recommended but not required. Suggested phrasing @auchenberg?

**Comment by danjeffrey** [comment]
Where can I find documentation on using this extension without a web server? Adding a web server brings unneeded complexity for my use case.

**Comment by roblourens** [comment]
Just use the 'file' prop instead of 'url'. There is an example under "Launch" in the readme

**Comment by danjeffrey** [comment]
Thanks! It works.

Note to self: RTFM or "RTFRM" in this case.
