### ISSUE TITLE
How does one map chrome-extension://<id>/* resources to local disk files?

### ISSUE THREAD

**Issue by akshaysinghal** [Microsoft/vscode-chrome-debug#566]
- VS Code Version: `v1.18.1`

My path mapping:
```javascript
"pathMapping": {
    "/gmail-client/dist/local/app/": "${workspaceRoot}/app/",
    "chrome-extension://<id>/assets/": "${workspaceRoot}/dist/local/extension/chrome/assets/"
}
```

The first mapping is working fine, the second one does not work. The script URLs for chrome-extension resources are of the form `chrome-extension://<id>/assets/src/scripts/gmail/getGlobals.js` as verified via `.scripts` output.

**Comment by roblourens** [comment]
Correct, it doesn't work yet.
