### ISSUE TITLE
Breakpoints don't resolve at all when "regex" breakOnLoad strategy misses

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-chrome-debug#569]
https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/breakOnLoadHelper.ts#L258

@rakatyal, Looks like when using "regex", we don't resolve the pending breakpoint when its script loads. Why is that? We have the info at that point to do it? If the regex isn't a match, then the bp is never resolved.

**Comment by roblourens** [comment]
Actually I think I remember discussing how the order of `scriptParsed` and `Debugger.paused` may not be consistent, and we had to pick one to handle it, or something. But the current solution assumes that `Debugger.paused` will handle it, which doesn't work when there is no matching script.

**Comment by rakatyal** [comment]
We skip that for only those files where we set a break on load breakpoint, for which resolvePending gets called inside Debugger.paused event (to avoid calling it twice). I don't understand what you mean by regex isn't a match? Is there a case where we will skip calling it?

**Comment by roblourens** [comment]
If I set a BP in `foo.ts`, but that file compiles to `bar.js` or something, so the breakOnLoad BP never gets hit, then we never resolve the BP even though we have the sourcemap info once bar.js loads.

**Comment by rakatyal** [comment]
Ahh I see. Thank you for catching this! I guess we would need to put an extra check which would make sure only those files are skipped whose soucemap file match the regex or find some other way to do this.

**Comment by connor4312** [comment]
Closing since we've revamped this logic in the new debugger. Let me know [over there](https://github.com/microsoft/vscode-js-debug) if you still have issues with it.
