### ISSUE TITLE
Breakpoint hit shows a file saying "Source is not available."

### ISSUE THREAD

**Issue by kowsheek** [Microsoft/vscode-chrome-debug#57]
When a breakpoint is triggered I get the breakpoint shown in a file saying "Source is not available." but when I step in, the file is loaded correctly.

My setup remains the same as #32. This is the [Diagnostic log](https://github.com/Microsoft/vscode-chrome-debug/files/50461/debugger-log-3.txt).

**Comment by roblourens** [comment]
Hm, it returns "/client/app/app.js" from stackTrace, which obviously doesn't exist. The angular.js file appears to be mapped correctly, though. That looks like just the end of the log and doesn't include the logs from when that file was processed. Would you mind posting the full log? Is this a config that worked before and stopped working?

**Comment by kowsheek** [comment]
Here's the full log till the point where the file with "Source is not available" shows up: 
[debugger-log-4.txt](https://github.com/Microsoft/vscode-chrome-debug/files/50524/debugger-log-4.txt)

**Comment by roblourens** [comment]
Honestly this is a weird one - that file is mapped correctly when you set the breakpoint, but not for the stack trace. Sorry to keep asking you for logs but the second one is still missing the part at the beginning that prints the config, and the scriptParsed event from Chrome for app.js. I think I know what it's going to say though. Let me think about this some more.

**Comment by kowsheek** [comment]
No worries, happy to help as much as I can. Sorry for not getting the copying right, the console output is difficult to copy from. Hope this shows what you're looking for: 
[debugger-log-5.txt](https://github.com/Microsoft/vscode-chrome-debug/files/52461/debugger-log-5.txt)

**Comment by roblourens** [comment]
I'm still not sure what's happening in your case, but I just pushed out an update that made a lot of changes to the code in this area. Could you update and try again?

**Comment by kowsheek** [comment]
I updated and seems to be working as expected again. Thanks!
