### ISSUE TITLE
Pause overlay flashes when breakOnLoadStrategy=regex, and sourcemaps are resolved slowly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-chrome-debug#570]
- Use the "regex" strategy with vscode
- Set a bp and launch
- When it hits the breakOnLoad bp, there's a lot going on. It takes more than 200ms to resolve the sourcemaps, set the real bp and continue, which is enough time for the chrome-debug overlay debounce to trigger and show the pause overlay.

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode-js-debug/issues/597
