### ISSUE TITLE
sourceMapPathOverrides not being applied

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/vscode-chrome-debug#571]
- VS Code Version: 1.19.0

Nothing I put in `sourceMapPathOverrides` seems to get applied when I run `.scripts`, even something like:

```
{
    "type": "chrome",
    "request": "launch",
    "name": "Client",
    "url": "http://localhost:8080/dashboard",
    "sourceMaps": true,
    "webRoot": "${workspaceFolder}",
    "sourceMapPathOverrides": {
        "*": "test/*",
    }
}
```

I tried to debug the extension, and while breakpoints in the top level of the extension files (like `ChromeDebugAdapter.js` get hit, nothing seems to be constructed if I place breakpoints in the constructors.

**Comment by Mosho1** [comment]
After investigating further, I found this line (`extension.ts:46`): 

```
if (config.request === 'attach') {
    /* ... */
}
```

**Comment by roblourens** [comment]
What are you seeing and expecting to see when you say that `sourceMapPathOverrides` aren't working? That test case works for me.

The code you reference is for picking a target when attaching in attach mode. It's irrelevant to launch mode, so I'm not sure what you mean by "everything works".

**Comment by Mosho1** [comment]
@roblourens I tried it again and it does work now. I'd like to think I wasn't crazy as I spent more than half an hour to find the problem, but I can't reproduce it. I'll reopen if I stumble across it again.
