### ISSUE TITLE
Debug breakpoints not hitting correctly in webpack project

### ISSUE THREAD

**Issue by meds** [Microsoft/vscode-chrome-debug#573]
- VS Code Version:

Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Details: Following [this example](https://webpack.github.io/docs/tutorials/getting-started/) to build a webpack project I was unable to get breakpoints to work in VSCode.

Steps to reproduce:

1. Download and unzip webpack project folder: [webpackproj.zip](https://github.com/Microsoft/vscode-chrome-debug/files/1589072/webpackproj.zip)

2. Run 'npm install' on extracted folder directory
3. Open extracted directory in VSCode
4. run command 'webpack --devtool source-map' followed by 'webpack-dev-server --progress --colors' in terminal or command prompt on folder
5. Place breakpoint on entry.js:3 (or anywhere else in javascript)
6. In VSCode with the folder open hit F5 to launch Chrome debugger

Observe: Breakpoints are not hit and sometimes are moved to a different spot than where you placed them despite being placed on executable js code

**Comment by roblourens** [comment]
From what I understand, `webpack-dev-server` uses the webpack config and compiles dyamically, not the previously built files. Set `devtool` in your webpack config and it should work. If not, ensure that the running version is actually built with sourcemaps.
