### ISSUE TITLE
Debugging with Chrome extension -- does not hit the break point

### ISSUE THREAD

**Issue by saurav-joshi** [microsoft/vscode-chrome-debug#574]
Visual Studio Code, Chrome extension, is giving inconsistent results in setting up break point. 

I have gone through the  [README section](https://github.com/Microsoft/vscode-chrome-debug#sourcemaps)  that discusses _Sourcemaps_ overrides that may be required for debugging Web applications running in Chrome. 

I am working on a React Application and have found that if I do not set *sourceMapPathOverrides* in launch.json file then the breakpoints are not hit. I went through some of the open issues where it was discussed that the default properties may require an override to map the source file in disk. 

I added  *sourceMapPathOverrides* option in my launch.json file and observed that order in which web pack mappings is added is affecting the outcome. 

for example  if "webpack:///*": "*"  is used as the first entry then the breakpoints are not hit but if I put it as the last entry then breakpoints are correctly enabled.  

_"sourceMapPathOverrides": {
                "webpack:///*": "*",
                "webpack:///./*": "${webRoot}/*",
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///./~/*": "${webRoot}/node_modules/*"  ----> does not work_

_"sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*",
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///./~/*": "${webRoot}/node_modules/*", 
                  "webpack:///*": "*",  ----> works_

The order of mapping should, ideally, not affect the outcome since  "webpack:///src/*": "${webRoot}/*" is more specific path than "webpack:///*": "*" and hence while resolving  "webpack:///src/*": "${webRoot}/*"  should be chosen over "webpack:///*": "*"

I have attached following files for reference.

1.  launch_sourceMapPathOverrides_not_working.json which uses  sourceMapPathOverrides and has "webpack:///*": "*" option at the top. 

2.. launch_sourceMapPathOverrides_working.json which uses  sourceMapPathOverrides and has "webpack:///*": "*" option at the bottom -- this version works .
3. Screenshots depicting that the breakpoints are hit when the order of mapping is changed. 

Other details are 
- VS Code Version: 1.18.1
- Chrome Version:  62. 

<img width="942" alt="sourcemappathoverrides_not_working" src="https://user-images.githubusercontent.com/10287641/34492272-d1609c90-f021-11e7-84b5-b50d12e0f157.png">
<img width="942" alt="sourcemappathoverrides_working" src="https://user-images.githubusercontent.com/10287641/34492273-d19449aa-f021-11e7-8690-6a29779c4b7d.png">

**Comment by roblourens** [comment]
The overrides are applied in order, which is unexpected, but it's not always obvious which one is "more specific" when wildcards are used. Applying longer paths first would be a big improvmenet though.

**Comment by saurav-joshi** [comment]
Thanks for the response. This is a bit counterintuitive since the generic/template codes always select the most specific path. 

I have a followup question. If the sourceMapPathOverrides option is not set, and the default mapping is chosen, then some of the scripts in the source folder are correctly mapped while some others are not mapped correctly. I am attaching  vscode-chrome-debug_without_overrides.txt  for reference. 

VS Code is a great editor and a productivity boost but at times the small anti idioms do take a good amount of time to resolve. 
Attached two files for reference 

1. VS Code verbose log file ,vscode-chrome-debug.txt 
2. screen shot of launch.config *without* sourceMapPathOverrides option 
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1598211/vscode-chrome-debug.txt)
<img width="942" alt="without_sourcemappathoverrides_not_working" src="https://user-images.githubusercontent.com/10287641/34493153-98d6a05a-f025-11e7-83c9-2eb52d523962.png">

**Comment by roblourens** [comment]
Agreed that it's counterintuitive, also because a JS object is not expected to have ordered keys.

That's expected, there are some overrides for common webpack patterns that are applied by default.

**Comment by SethHamilton** [comment]
@saurav-joshi  your `launch.json` settings made this all work for me on Chrome. Thank you. I've included a cut-and-past version of it below for anyone else having difficulty getting this cool module to work with React.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "trace": true
        }
    ]
}
```

**Comment by arunap2509** [comment]
@SethHamilton I copied the same configuration as you mentioned in my launch.json file for my vue based project, First thing is it's not entering the file if the file contains no life cycle hook and when specified it's not hitting the breakpoint, it's hitting somewhere else in the file
