### ISSUE TITLE
All breakpoints in .ts file not working in debug mode "Attach to Chrome"

### ISSUE THREAD

**Issue by SynneKDoG** [Microsoft/vscode-chrome-debug#578]
- VS Code Version: 1.19.1

Steps to reproduce:

1. Open Chrome with remote debugger 
2. Enter my url stated in launch.json
3. Run debug with request "Attach to Chrome"
4. Debug runs successfully
5. All breakpoints in my .ts file turn grey and are marked as "Ignored because generated code not found (source map problem)"
6. Try many solutions around the internet but nothing works

My launch.json along with folder structure and working file position:
![launch_json](https://user-images.githubusercontent.com/21306575/34651852-b4dfafda-f408-11e7-825d-b790a48ab238.PNG)

My tsconfig.json:
![tsconfig](https://user-images.githubusercontent.com/21306575/34651863-ff62641c-f408-11e7-9d34-c9fd4479c5e6.PNG)

My working file:
![working_file](https://user-images.githubusercontent.com/21306575/34651883-501837b0-f409-11e7-9a1c-d73dadefe8c7.PNG)

Thanks

**Comment by auchenberg** [comment]
Can you try to run the `.scripts` command as documented here, https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command, and see if your source mapped paths are right? I would suspect your `webRoot` path is wrong.

**Comment by SynneKDoG** [comment]
Thanks for replying,
i'm not sure how to correct my webRoot yet, I follow some instructions on the internet and point to where my .ts file is located

After running .scripts command:

.scripts
From client: evaluate({"expression":".scripts","context":"repl"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"› VM869\n› chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lastpass/content-script.bundle.js\n› chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js\n› chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/Grammarly.js\n› chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/Grammarly.styles.js\n› chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/editor-popup.js\n› chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js\n› chrome-extension://ngpampappnmepgilojfohadhhmbhlaek/content.js\n› extensions::binding\n› extensions::event_bindings\n› extensions::fileEntryBindingUtil\n› extensions::json_schema\n› extensions::lastError\n› extensions::messaging\n› extensions::messaging_utils\n› extensions::runtime\n› extensions::schemaUtils\n› extensions::sendRequest\n› extensions::uncaught_exception_handler\n› extensions::utils\n› http://localhost:3000/0.072dc4441bf947e6fcc7.chunk.js\n› http://localhost:3000/2.44bb7e77c42f6ce1c00b.chunk.js\n› http://localhost:3000/3.9153c5ad526ecc25ded6.chunk.js\n› http://localhost:3000/4.2881a2aa3191281598d9.chunk.js\n› http://localhost:3000/assets/bootstrap/bootstrap.min.js\n› http://localhost:3000/assets/js/custom.js\n› http://localhost:3000/assets/js/xlsx-populate.js\n› http://localhost:3000/assets/vendors/autosize/dist/autosize.min.js\n› http://localhost:3000/assets/vendors/bootstrap-daterangepicker/daterangepi[...]
› VM869
› chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lastpass/content-script.bundle.js
› chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js
› chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/Grammarly.js
› chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/Grammarly.styles.js
› chrome-extension://kbfnbcaeplbcioakkpcpgfkobkghlhen/src/js/editor-popup.js
› chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js
› chrome-extension://ngpampappnmepgilojfohadhhmbhlaek/content.js
› extensions::binding
› extensions::event_bindings
› extensions::fileEntryBindingUtil
› extensions::json_schema
› extensions::lastError
› extensions::messaging
› extensions::messaging_utils
› extensions::runtime
› extensions::schemaUtils
› extensions::sendRequest
› extensions::uncaught_exception_handler
› extensions::utils
› http://localhost:3000/0.072dc4441bf947e6fcc7.chunk.js
› http://localhost:3000/2.44bb7e77c42f6ce1c00b.chunk.js
› http://localhost:3000/3.9153c5ad526ecc25ded6.chunk.js
› http://localhost:3000/4.2881a2aa3191281598d9.chunk.js
› http://localhost:3000/assets/bootstrap/bootstrap.min.js
› http://localhost:3000/assets/js/custom.js
› http://localhost:3000/assets/js/xlsx-populate.js
› http://localhost:3000/assets/vendors/autosize/dist/autosize.min.js
› http://localhost:3000/assets/vendors/bootstrap-daterangepicker/daterangepicker.js
› http://localhost:3000/assets/vendors/fastclick/lib/fastclick.js
› http://localhost:3000/assets/vendors/iCheck/icheck.min.js
› http://localhost:3000/assets/vendors/jquery/dist/jquery.min.js
› http://localhost:3000/assets/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js
› http://localhost:3000/assets/vendors/moment/moment.js
› http://localhost:3000/assets/vendors/nprogress/nprogress.js
› http://localhost:3000/assets/vendors/pnotify/dist/pnotify.buttons.js
    - ..\src\pnotify.buttons.js (e:\Software\Microsoft VS Code\${workSpaceRoot}\src\app\courses\course-detail\course-detail-staff\assets\vendors\pnotify\src\pnotify.buttons.js)
› http://localhost:3000/assets/vendors/pnotify/dist/pnotify.desktop.js
    - ..\src\pnotify.desktop.js (e:\Software\Microsoft VS Code\${workSpaceRoot}\src\app\courses\course-detail\course-detail-staff\assets\vendors\pnotify\src\pnotify.desktop.js)
› http://localhost:3000/assets/vendors/pnotify/dist/pnotify.js
    - ..\src\pnotify.js (e:\Software\Microsoft VS Code\${workSpaceRoot}\src\app\courses\course-detail\course-detail-staff\assets\vendors\pnotify\src\pnotify.js)
› http://localhost:3000/assets/vendors/pnotify/dist/pnotify.nonblock.js
    - ..\src\pnotify.nonblock.js (e:\Software\Microsoft VS Code\${workSpaceRoot}\src\app\courses\course-detail\course-detail-staff\assets\vendors\pnotify\src\pnotify.nonblock.js)
› http://localhost:3000/inline.6509149307b47ca1f79e.bundle.js
› http://localhost:3000/main.a6c3b83666910a6e8707.bundle.js
› http://localhost:3000/polyfills.339bcea44af9babf3ded.bundle.js
› http://localhost:3000/vendor.8e724d0fe1224889515d.bundle.js
To client: {"seq":0,"type":"response","request_seq":17,"command":"evaluate","success":true,"body":{"result":"","variablesReference":0}}

**Comment by SynneKDoG** [comment]
The full log after opening debug is such huge
However, I notice there is only a field in red, is this the cause of my problem?


C:\Users\dtkho\AppData\Local\Temp\vscode-chrome-debug.txt
OS: win32 x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.21.0
9:48:40 AM, 1/8/2018
debugger-for-chrome: 4.0.0
.....................................


SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost:3000/assets/js/xlsx-populate.js, sourcemap: xlsx-populate.js.map
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\Users\dtkho\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:20:25)
    at sourceMapContentsP.then.contents (C:\Users\dtkho\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:53:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by auchenberg** [comment]
@roblourens Looks like `${workSpaceRoot}` doesn't get replaced properly. Got an idea?

**Comment by roblourens** [comment]
The correct capitalization is `workspaceRoot`.

**Comment by SynneKDoG** [comment]
Hi @roblourens ,
I correct the workspaceRoot, but the issue is still there

![same issue](https://user-images.githubusercontent.com/21306575/34660317-f2967dc0-f473-11e7-9ab9-161e8f93835f.PNG)

Thanks

**Comment by SynneKDoG** [comment]
I also try removing "${workSpaceRoot}........." with exact dir to my .ts file but no luck
It looks like this: 
"webRoot": "E: ............/src/app/courses/course-detail/course-detail-staff/course-detail-staff.component.ts"

**Comment by SynneKDoG** [comment]
Can you suggest the correct "webRoot " based on my folder structure?
I'm very grateful for that
Also, my tsconfig.json above is not default, I modified it with some help from the internet

**Comment by roblourens** [comment]
Use the `.scripts` command to tell where your scripts are being resolved to, and tweak the webRoot based on that. It should point to the folder where your webserver is serving from.

**Comment by SynneKDoG** [comment]
I used .scripts command and replied to @auchenberg above, would you mind taking a quick look at that and see if there is any trouble?
As I'm working on my "course-detail-staff.component.ts", I can't see where this script is located in .scripts command content.
And how should I correct my webRoot based on my .scripts command content?

**Comment by SynneKDoG** [comment]
Let me know if you need more info, I just really want my breakpoints to work
Thank you,

**Comment by roblourens** [comment]
Sure, but then you had the wrong `workspaceRoot` casing, if it still doesn't work after fixing that then there must be another problem.

You should check out the docs on what the command shows you - https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command - I usually tweak the launch config, check `.scripts`, tweak it again if it isn't right...
