### ISSUE TITLE
Debug process eats 100% of a CPU core and won't exit when Code exits

### ISSUE THREAD

**Issue by lolmaus** [Microsoft/vscode-chrome-debug#579]
- VSCode Version: Code 1.19.1 **[Unsupported]** (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z) Note that the [Unsupported] part refers to using the be5invis.vscode-custom-css addon which I use to embed a few lines of CSS.
- OS Version: Linux x64 4.10.0-42-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.25.0
vscode-custom-css|be5|2.6.1
npm-intellisense|chr|1.3.0
vsc-ember-frost|cie|0.0.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.3
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.1.8
vscode-ember|emb|0.1.1
auto-rename-tag|for|0.0.15
code-runner|for|0.8.7
terminal|for|0.0.10
docthis|joe|0.6.0
code-beautifier|mic|1.7.2
vscode-duplicate|mrm|1.2.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.0.0
EmberES6Snippets|pha|2.2.0
Ruby|reb|0.15.0
vscode-icons|rob|7.19.0
sass-indented|rob|1.4.6
---

Steps to Reproduce:

1. Start Code and see its child process eat 100% of a CPU core. The command is:

        /usr/share/code/code --nolazy --inspect=9333 /usr/share/code/resources/app/out/bootstrap --type=extensionHost

2. Exit Code, the child process keeps running.

Likely related to an extension because doesn't happen in `--disable-extensions` mode. But I struggle to figure out which one.

Reproduces without extensions: **No**
  
 Previously reported at https://github.com/Microsoft/vscode/issues/41287 .

**Comment by roblourens** [comment]
Why did you file this in vscode-chrome-debug? See these instructions to debug which extension is at fault - https://github.com/Microsoft/vscode/wiki/Performance-Issues#the-extension-host-process-consumes-a-lot-of-cpu

**Comment by lolmaus** [comment]
Because disabling this particular extension resolves the issue.

**Comment by lolmaus** [comment]
Your link says:

> If you cannot reproduce the issue when the extensions are disabled, then can you narrow down the extension by selectively disabling extensions? You can disable extensions in the Extensions Viewlet and restart/reload.

This is exactly what I did.

**Comment by roblourens** [comment]
Ok, your issue didn't say that. What are the repro steps to make this happen? Does it happen after debug sessions?

**Comment by lolmaus** [comment]
Sorry for that, my fault.

I do have a debug session configured, but I'm not using it. I even left laonch.json empty and it didn't help.

All I do is launch Code, then quit and see `--inspect=9333` spinning in background.

I can take a video if that helps.

**Comment by roblourens** [comment]
Hm, I have no idea what it could be doing.

If you delete the debug session, does it stop happening (after restarting Code)?

Can you get a CPU profile to help me understand what's happening? There are steps here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#the-extension-host-process-consumes-a-lot-of-cpu (via the `Developer: Show Running Extensions` command)

**Comment by lolmaus** [comment]
I wasn't able to reproduce the issue today. Either the reboot or deleting the empty `launch.json` helped, or it was totally random.

I'll build courage to try remote debugging again later, and I might be back. :D 

Thank you for your effort, you're making my life more satisfying.

**Comment by lolmaus** [comment]
The problem keeps happening without `vscode-chrome-debug` installed. I seem to have misidentified the extension to blame.

**Comment by lolmaus** [comment]
Gotcha: https://github.com/ecmel/vscode-html-css/issues/51#issuecomment-356247757

**Comment by roblourens** [comment]
No worries :)
