### ISSUE TITLE
Can't use cheap-module-eval-source-map

### ISSUE THREAD

**Issue by sanmaopep** [Microsoft/vscode-chrome-debug#580]
I use cheap-module-eval-source-map in webpack and the breakpoints always hint the wrong line.
After I change cheap-module-eval-source-map to eval-source-map or source-map, the breakpoints hint the right line.
I can't figure it out so I look for some help here.

**Comment by auchenberg** [comment]
You can't use `cheap-module-eval-source-map` as the generated sourcemap doesn't contain enough and correct information for our debugger to work. Our recommendation for webpack is either `eval-source-map` or `source-map`.
