### ISSUE TITLE
Documentation needs to be clearer about what webRoot actually is

### ISSUE THREAD

**Issue by 1attice** [Microsoft/vscode-chrome-debug#582]
The documentation talks of webRoot as 'the directory the files are served from'. This is unclear. Off the top of my head, this could mean:

 - it's the directory component of a URL containing app.js and app.js.map (the _web_ root)
 - it's the filesystem directory that brunch/webpack/whatever drops the slug into (the webroot)
 - it's the directory containing my source which is referred to by the sourcemap (the web _root_)
 - it's the directory containing my web application (the root of the web application)
 - give me five minutes, I can think of more.  ;) 

I'm working on a large Elixir/Phoenix app and VSC knows about the assets directory, but chrome debugger can't find my source maps, and I can't figure out which of the above interpretations of webroot is correct. I'm assuming I should set it to e.g. ../priv/static/, which then contains ./js/app.*map and ./css/*.map, but it could also be ../priv/static/js or.. gosh, even ./js/ or... like, guys, this is unclear  :)

Thanks for this code, but I could use some help parsing the README.md

**Comment by roblourens** [comment]
Thanks for the feedback, I am very open to suggestions for how to improve the documentation.

The webroot is the root directory of the webserver. So if some file is served from `http://localhost/app.js`, where is app.js? I'm not even sure which of your definitions applies :)

**Comment by liz-mars** [comment]
That's the problem for sure -- I'm not sure how it applies either :)  Here's our pipeline:

- source code lives in <application-root>/apps/app_web/assets/{js,css}. This is where the package.json is, and where VSC and I live.

- brunch minifies the source and drops the slugs at <application-root>/apps/app_web/priv/static/{js,css}. This is where I can find e.g. js/app.js and js/app.js.map. 

Which is my webRoot?

**Comment by liz-mars** [comment]
I've tried pretty much all the options I can think of and I'm still getting 'breakpoint ignored because generated code not found (sourcemap problem)'? as a tooltip when I hover over a breakpoint -- and the breakpoints are grey hollow circles

**Comment by liz-mars** [comment]
Any help appreciated <3

**Comment by liz-mars** [comment]
OK, here is the key question @roblourens  -- should app.js.map be in the folder indicated with webroot, or should it be the files *referred to* by app.js.map

**Comment by liz-mars** [comment]
After a 2h deep dive, I got it working. FWIW, webRoot could be described as 'the path to the part of your filesystem that lines up with the URLs produced by your web server or web app. It will contain the output of any pipeline you may be using (webpack, brunch, etc), including any source map files generated thereby.'

For example, Phoenix uses the ..../priv/static directory to hold the minified output of brunch.

**Comment by liz-mars** [comment]
For any other Phoenii out there, this configuration worked:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "attach",
      "name": "Attach Chrome against localhost",
      "port": 9222,
      "url": "http://localhost:4000/",
      "webRoot": "${workspaceFolder}/../priv/static/",
      "sourceMapPathOverrides": {
        "js/*": "${workspaceFolder}/js/*"
      }
    },
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:4000/",
      "webRoot": "${workspaceFolder}/../priv/static/",
      "sourceMapPathOverrides": {
        "js/*": "${workspaceFolder}/js/*"
      }
    }
  ]
}
```

**Comment by auchenberg** [comment]
@liz-mars Would be awesome if you wanted to contribute that as a recipe for https://github.com/Microsoft/vscode-recipes?

**Comment by SynneKDoG** [comment]
i'm still struggling with finding a correct webRoot to get my breakpoints in a .ts file working. Thank god, your suggestion came up, we really really need a clearer webRoot instruction and probably a specific example on a complicated folder structure <3

**Comment by gombosg** [comment]
You have to look at the source maps... for me the solution was:
```
"sourceMapPathOverrides": {
   "./src/*": "${workspaceFolder}/src/*"
}
```
Because paths in the source maps looked like `"./src/..../whatever.ts`.
And I set the webroot to the folder that the server actually serves from my disk.

@roblourens maybe you could emphasize this in the docs - to try to look at the generated source maps and figure out the proper overrides from there.

**Comment by reyou** [comment]
@auchenberg at your article in here https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f

I used exact same configuration for debugging my react app. It works automagically great, but also I did not get how webRoot understands there is a react app (or whatever it is) sits there and it launches it successfully and debugger works!

Normally `npm run start`  wraps `react-scripts start`. Does `webRoot` makes something similar?

What command it runs behind the scenes? There is no single line mentioned about `webRoot` command at docs https://code.visualstudio.com/docs/editor/debugging

**Comment by Roustalski** [comment]
Any thoughts on what the `webRoot` might be as part of an Electron-forge TS app? I've tried all of the permutations on `dist` and `src` folders, etc, but no luck so far.

**Comment by roblourens** [comment]
Since Electron usually just uses file:/// URIs, it may or may not be relevant.

If you're having trouble setting breakpoints, it may be another issue.

**Comment by doktordirk** [comment]
I used some of the information here to get my setup running:
```  
// where gulp and webpack place the compiled bundles and souremaps
// and where there was a symlink to from tomcat/webapp
"webRoot": "${workspaceFolder}/target/static-webapp/static-content/webpack", 

// default setting where i replaced webapp with workspaceFolder, 
// as they clearly have been very different
"sourceMapPathOverrides": {
    "webpack:///./~/*": "${workspaceFolder}/node_modules/*", 
    "webpack:///./*":   "${workspaceFolder}/*", 
    "webpack:///*":     "*",     
    "webpack:///src/*": "${workspaceFolder}/*", 
}
```

so as i see it:
webroot -> the files which are actually served
sourceMapPathOverrides -> the original source code
