### ISSUE TITLE
React: Breakpoint ignored because generated code not found

### ISSUE THREAD

**Issue by hos4m** [Microsoft/vscode-chrome-debug#583]
- VS Code Version: 1.19.2

I got this error after setting a breakpoint:
`Breakpoint ignored because generated code not found (source map problem?)`

launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src"
    }
  ]
}
```

**Comment by roblourens** [comment]
See the troubleshooting help here: https://github.com/Microsoft/vscode-chrome-debug#sourcemaps

What's the output of the `.scripts` command in the debug console?

**Comment by mrdrwest** [comment]
I got the same error, fought with it for hours. 
I'm using the following launch.json configuration:

  "version": "0.2.0",
  "configurations": [
  {
    "type": "chrome",
    "request": "launch",
    "name": "Chrome",
    "url": "http://localhost:9222",
    "webRoot": "${workspaceRoot}",
    "sourceMaps": true,
    "file": "${workspaceFolder}/index.html"
  }
  ]
}

My JavaScript file is called in a <script> tag from index.html, but it wasn't hitting the BP.

Then I decided to refresh Chrome (after several hours...SMH) a few times, and finally my BP was hit, allowing me to step thru the JavaScript code.

**Comment by MitchK** [comment]
React newbie here.

I was following this exact tutorial: https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/src"
        }
    ]
}
```

I understand that the problem has to relate to source maps as stated here: https://github.com/Microsoft/vscode-chrome-debug#sourcemaps

But I don't understand what I actually need to set in the overrides. My source code (```App.js```, etc.) is available under ```${workspaceRoot}/src```. I don't see any sourcemap files in my work tree.

In the VSCode debug console it says:
```
Error processing "setBreakpoints": TypeError: Cannot read property 'mappedPath' of undefined
    at BaseSourceMapTransformer.setBreakpoints (C:\Users\xxx\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:63:23)
    at validateBreakpointsPath.then (C:\Users\xxx\.vscode\extensions\msjsdiag.debugger-for-chrome-4.0.0\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:892:40)
    at <anonymous>
```

![sourcemap](https://user-images.githubusercontent.com/2472064/35201510-f90940a4-fed0-11e7-9765-f4a231a16c0f.PNG)

**Comment by auchenberg** [comment]
@roblourens Do you know what could case this error?

**Comment by roblourens** [comment]
@MitchK Please don't take over random issues, but the error is https://github.com/Microsoft/vscode-chrome-debug-core/issues/256

No response from the OP, closing

**Comment by hos4m** [comment]
@roblourens How can I re-open this issue?

**Comment by roblourens** [comment]
I can reopen it if you post the details I asked for, and it turns out to be a bug.

**Comment by hos4m** [comment]
Thank you but I already found the fix, this is my `launch.json`:
```
{
      "name": "Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceRoot}/src",
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      },
      "sourceMaps": true
}
```
