### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches: http://repo.intra.snap.com.br/. Available pages: [...

### ISSUE THREAD

**Issue by ArthurMenezes** [Microsoft/vscode-chrome-debug#584]
I have a problem similar to this, but with attach. my settings:

` 
{
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "url": "http://repo.intra.snap.com.br/",
            "userDataDir": false,
            "console": "internalConsole",
            "trace": "verbose",
            "sourceMaps" : true ,
        },
`

url is an internal url for network, the web server is also on the network.
I'm getting the following error: Can not connect to runtime process, timeout after 10000 ms - (reason: Can not find a target that matches: http://repo.intra.snap.com.br/. Available pages: [.. ..URLS]

**Comment by roblourens** [comment]
Is a tab with that URL open in Chrome? Is it listed in the list of "available pages"?

**Comment by ArthurMenezes** [comment]
> Is a tab with that URL open in Chrome?

No. The browser was initialized only for this test. I executed "killall chrome" and then "google-chrome-stable --remote-debugging-port=9222"

> Is it listed in the list of "available pages"?

Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches: http://repo.intra.snap.com.br/. Available pages: ["chrome://newtab/"]).

**Comment by roblourens** [comment]
You need to open the page you want to debug, so you can attach to it.

I recommend using a "launch" config. It's much simpler to set up.
