### ISSUE TITLE
Breakpoints Ignored

### ISSUE THREAD

**Issue by AFGM** [Microsoft/vscode-chrome-debug#587]
Hi everyone, before i opened this issue i saw many topics and many videos but i couldn't fix my problem.
I am trying to debug a simple express app in chrome but my breakpoints are ignored.

Above image we can see project files structure and the launch file config.
<img width="1168" alt="screen shot 2018-01-24 at 19 07 20" src="https://user-images.githubusercontent.com/23224577/35352084-b01cb7ce-013a-11e8-9af0-49937eb52235.png"> 

When I run Chrome i see breakpoints changing from red to grey(ignored).
<img width="709" alt="screen shot 2018-01-24 at 19 10 50" src="https://user-images.githubusercontent.com/23224577/35352150-f0c64d62-013a-11e8-81a6-0c5b401ba5ab.png">

Thanks in advance

**Comment by auchenberg** [comment]
Your code looks to be a server-side Node app. Please try to use the Node debugger https://code.visualstudio.com/docs/nodejs/nodejs-debugging, or follow this recipe https://github.com/Microsoft/vscode-recipes/tree/master/nodemon
