### ISSUE TITLE
Look up runtimeExecutable on PATH

### ISSUE THREAD

**Issue by eric-burel** [microsoft/vscode-chrome-debug#588]
Hi, I did not see any doc or issue about Chromium. How can we execute Chromium (the open source version of Google Chrome) instead of Chrome ?

Here is the relevant config:

```
        {
            "type": "chrome",
            "request": "launch",
            "name": "Meteor: Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}"
        },
```
I tried to change the `runtimeExecutable` to `chromium-browser` but it does not work, the attribute does seem to be valid when the type is `chrome`.

Edit: could be related to this [https://github.com/Microsoft/vscode-cordova/issues/273]()

**Comment by roblourens** [comment]
Setting runtimeExecutable is correct. If `chromium-browser` isn't on your path, you may have to set the absolute path to it.

**Comment by eric-burel** [comment]
Hm okay I'll try again to detail the error. `chromium-browser` is indeed set in the path so it should have worked.

**Comment by dmaisano** [comment]
Experiencing the same issue on Ubuntu 17.10, `chromium-browser` is set in my $PATH. Would love to get the debugger to work with chromium

**Comment by roblourens** [comment]
- If you open the integrated terminal in vscode, does running `chromium-browser` launch chromium?
- How did you launch vscode? Did you start it from a terminal?

**Comment by eric-burel** [comment]
Hi, vscode is launched through the Ubuntu launcher (so clicking the icon), and `chromium-browser` opens correctly from the vscode terminal.
Here is the error message : `Attribute 'runtimeExecutable' does not exist ('chromium-browser').`
And here is the config:
```
{
            "type": "chrome",
            "request": "launch",
            "name": "Meteor: Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}",
            "runtimeExecutable": "chromium-browser"
        },
```
So I don't understand why runtimeExecutable is not taken into account :/

**Comment by roblourens** [comment]
I just realized that chrome-debug expects an absolute path in `runtimeExecutable`. node-debug works with individual commands and has some code to find it on the PATH, but that needs to be copied to chrome-debug. I'll do that but for now, you can put in an absolute path to chromium-browser.

**Comment by preetender** [comment]
To solve this problem, simply create an alias for **chromium-browser**!

on linux: sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

**Comment by asinitson** [comment]
@preetender: That did the trick! Thanks!

Note that depending on distribution Chromium path might be different, for example for openSUSE (Chromium installed from distribution's default repository) symbolic link will be set like this:
`ln -s /usr/bin/chromium /usr/bin/google-chrome`

**Comment by DanKline** [comment]
On Debian 9 stretch for arm64 it is very similar to OpenSUSE.  I'm running the HeadMelted version of code "code-oss":

sudo ln -s /usr/bin/chromium /usr/bin/google-chrome.

Works like a champ ... Thanks folks.

**Comment by dontbyte** [comment]
Unfortunately the alias didn't work for me. I had to add the full path to chromium on Ubuntu 18.04.3 because of error "Attribute runtimeExecutable does not exist":

`"runtimeExecutable":` "/usr/bin/chromium-browser"

**Comment by asinitson** [comment]
@dontbyte: I use Ubuntu 18.04.3 at work and trick works well there. Are you sure you didn't do spelling mistake when creating symbolic link?

**Comment by dontbyte** [comment]
> @dontbyte: I use Ubuntu 18.04.3 at work and trick works well there. Are you sure you didn't do spelling mistake when creating symbolic link?
Yes, pretty sure there was no spelling mistake.

**Comment by roblourens** [comment]
By the way, I believe this should work correctly in the new experimental debug adapter: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by connor4312** [comment]
As Rob mentioned, we now have a new debugger with stronger discovery logic (powered by [this npm package](https://github.com/microsoft/vscode-js-debug-browsers)). The next [nightly version](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the new debugger also has the ability to allow you to set a custom default runtimeExecutable (https://github.com/microsoft/vscode-js-debug/issues/836) in case the built-in discovery is not sufficient for you -- but if this is the case please let us know since we may want to tweak our browser discovery logic.
