### ISSUE TITLE
incorect value for scope in arrow function that is implemented in ngOnInit

### ISSUE THREAD

**Issue by benshabatnoam** [Microsoft/vscode-chrome-debug#589]
- VS Code Version:
1.19.2
Steps to reproduce:
1. In an angular cli project create a new component.
2. implement onInit function.
3. in 'ngOnInit' function implement an arrow function.
4. on debug with vscode-chrome-dubug extention, 'this' is undefiend, but actualy it is not (you can see it's not on chrome dev tools).

Thanks

**Comment by roblourens** [comment]
I thought there was an existing issue for something like this but I can't find it.

- Are you using TS? Is there a `_this`?
- Can you evaluate `this` in the console?

**Comment by benshabatnoam** [comment]
I'm using TS 262. There is an _this.
In console 'this' is undefined

**Comment by roblourens** [comment]
Chrome devtools is able to show renamed variables from sourcemaps (_this -> this). I have an issue for this, https://github.com/Microsoft/vscode/issues/12066

But vscode is showing the correct name from the runtime.

**Comment by benshabatnoam** [comment]
Thanks
