### ISSUE TITLE
nextjs with typescript

### ISSUE THREAD

**Issue by renehauck** [Microsoft/vscode-chrome-debug#591]
I wanted to ask how I can use your tool with nextjs and typescript.
My configuration already works if I just wanted to debug .js files.
But with ts and tsx files, no breakpoint is hit.

`.scripts ` gives the following result:
```
...
  › http://localhost:3012/_next/1517246763703/page/index.js
...
        - webpack:///./gui/shared/searchBar/SearchBarComponent.js?18f2942 (${webRoot}/gui/shared/searchBar/SearchBarComponent.js)
...
```
The index.js-bundle

![screenshot_20180129_183822](https://user-images.githubusercontent.com/3898144/35525087-c84c9818-0523-11e8-81bb-575ea0c473d6.png)

and the tsx-File
![screenshot_20180129_183851](https://user-images.githubusercontent.com/3898144/35525127-e4a62060-0523-11e8-845d-2c35a5e962e0.png)

and my config:
```
    "configurations": [
        {
            "name": "Chrome Debug",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "url": "http://localhost:3012",
            "sourceMaps": true
        },
```

- VS Code Version: 1.19.3

Thanks for your work

**Comment by roblourens** [comment]
`        - webpack:///./gui/shared/searchBar/SearchBarComponent.js?18f2942 (${webRoot}/gui/shared/searchBar/SearchBarComponent.js)`

This line shows that it's trying to resolve the path in the sourcemap to a file on disk, but you haven't set the `webRoot` property. Try setting `"webRoot": "${workspaceFolder}"` or to the path where your webserver is serving files from, and run `.scripts` again to see if it's picking up the right path.

BUT that scripts entry also implies that the sourcemap doesn't include the `.ts` file, it may only map to some intermediate .js. If so, you'll have to adjust your build, and I don't have experience with nextjs unfortunately.

**Comment by renehauck** [comment]
> Try setting "webRoot": "${workspaceFolder}" or to the path where your webserver is serving files from, and run .scripts again to see if it's picking up the right path.

Already tried without success :cry: 

> BUT that scripts entry also implies that the sourcemap doesn't include the .ts file, it may only map to some intermediate .js. If so, you'll have to adjust your build, and I don't have experience with nextjs unfortunately.


I think that's the problem. 
Everyone is waiting for this PR: https://github.com/zeit/next.js/pull/2699
I think the ts-loader could solve the problem, right? :smiley:

**Comment by roblourens** [comment]
Yeah it sounds like we need that PR

**Comment by renehauck** [comment]
Ok, I  would close this issue and update, when we have that PR.

Thank you
