### ISSUE TITLE
Breakpoint ignored because generated code not found (source map problem ) -- can't resolve...

### ISSUE THREAD

**Issue by wind4gis** [Microsoft/vscode-chrome-debug#592]
- VS Code Version:
1.17.2, my debugger for chrome is  4.1.0
Steps to reproduce:

1. I use vscode, react, webpack( not using CRA!!! ),however when I debug, it shows Breakpoint ignored because generated code not found (source map problem ) 
2. I try .scripts and it shows nothing
3. I try trace:true , and look at the log, and can't understand what happend... it takes me a whole day to fix it...and can't still debug...is it the problem that i didn't use CRA to build my application?

**Comment by wind4gis** [comment]
it's my launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/src",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*"
            },
            "trace": true
        }
    ]
}

**Comment by wind4gis** [comment]
my project
![default](https://user-images.githubusercontent.com/3963291/35627858-2eea85a0-06d5-11e8-83f6-4a23a6077c81.png)

**Comment by wind4gis** [comment]
I start my project by webpack-dev-server.
and just debug...
is it wrong with using webpack-dev-server?

**Comment by wind4gis** [comment]
when I set a BP, and I set it on browser too, it will hint on both vscode and browser;
and I set a BP on bundle.js, it can hint too...
however, I set on original JS, it can't hint

**Comment by wind4gis** [comment]
uh.. I try .scripts again, and it shows, this is the log
[scripts.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1682148/scripts.txt)

**Comment by wind4gis** [comment]
oh... no...
I fix it!!!
I just add all to my launch.json

```
"sourceMapPathOverrides":` {
    "webpack:///./~/*": "${webRoot}/node_modules/*",       // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
    "webpack:///./*":   "${webRoot}/*",                    // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js",
    "webpack:///*":     "*",                               // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    "webpack:///src/*": "${webRoot}/*",                    // Example: "webpack:///src/App.js" -> "C:/project/src/App.js"
    "meteor://💻app/*": "${webRoot}/*"                    // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```
and fix it... it is so easy...

**Comment by roblourens** [comment]
Glad you got it to work, but do you have to add those to your launch.json? Those look like the defaults. They should be applied anyway if the sourceMapPathOverrides field is not set at all.
