### ISSUE TITLE
webpack URLs not showing up in .scripts

### ISSUE THREAD

**Issue by IAmPicard** [Microsoft/vscode-chrome-debug#593]
Hi,

I'm trying to debug an electron app using webpack-dev-server with hot reloading and inline source map. I can debug just fine in Chrome Dev Tools, but from VS Code I can't see any of the "webpack://" URLs if I run ",scripts".

- VS Code Version: 1.19.3

Steps to reproduce:

1. `webpack-dev-server --hot --host 0.0.0.0 --config=./webpack.dev.config.js`
2. From VS Code, attach with (launch.json):

```
{
   "type": "chrome",
   "request": "attach",
   "name": "Attach to Render Process",
   "port": 9222,
   "webRoot": "${workspaceRoot}/src",
   "sourceMaps": true,
   "trace": true
}
```

2. In the "Debug Console", run `.scripts`
3. Observe there's nothing about "webpack://" or sourcemaps.

This is [the project](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/blob/master/webpack.dev.config.js).

Log:
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1684033/vscode-chrome-debug.txt)

Screenshot (if it helps):
![screenshot](https://user-images.githubusercontent.com/31076775/35658621-10d1d8a2-06b7-11e8-9a8d-e06b2929d16e.png)

Let me know if I can provide more information.

Thank you!

**Comment by roblourens** [comment]
Thanks for all the details. It looks like you're attached to the devtools window, not the electron renderer window. Did it ask you to pick a tab when you attached?

**Comment by IAmPicard** [comment]
Yes, that was totally it. After closing the dev tools tab, the debugger attached and ".scripts" lists out all the webpack:// stuff.

Thank you so much for the quick reply!

FWIW, no, it didn't ask me to pick a tab (haven't seen anything in either VS Code or in Electron).

**Comment by roblourens** [comment]
Oh right, that's because Electron still only allows one debugging connection at a time. So you wouldn't be able to attach to the renderer window.
