### ISSUE TITLE
Open debugger in new tab instead of new window

### ISSUE THREAD

**Issue by hos4m** [Microsoft/vscode-chrome-debug#595]
- VS Code Version: 1.19.3

Steps to reproduce:

1. Set a breakpoint
2. Start the debugger

A new instance of Chrome is launched, is there a way to open a new tab in the current active window or it has to be in a new window?

Thanks.

**Comment by roblourens** [comment]
You can set `"userDataDir": false` to force it to use a running instance of Chrome, but if that instance wasn't started in debug mode (using the `--remote-debugging-port` flag), it won't be able to attach.
