### ISSUE TITLE
chrome debugger on mac support

### ISSUE THREAD

**Issue by jacobi85** [Microsoft/vscode-chrome-debug#596]
Any ideas on supporting chrome debugger on mac computers?

**Comment by roblourens** [comment]
It is supported, why do you think it isn't?

**Comment by jacobi85** [comment]
This is so weird. It's impossible to find the extention. I browse through extensions but it does not show up. When I try to download it from https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome I'm prompted to install it on windows. see picture.
![screenshot 2018-02-08 20 13 19](https://user-images.githubusercontent.com/1927274/35993159-b8a02632-0d0c-11e8-886b-e8efba132207.png)

**Comment by jacobi85** [comment]
Yes that's correct. It launches VMware fusion.

**Comment by jacobi85** [comment]
> If all else fails, you can install from the extension viewlet inside vscode.

oh I see. Well that does the trick

**Comment by auchenberg** [comment]
You can also open up VS Code on your Mac, and install the extension from within VS Code.
