### ISSUE TITLE
Chrome debugger with Webpack/HMR opens wrong file.

### ISSUE THREAD

**Issue by lillehummer** [Microsoft/vscode-chrome-debug#597]
Hi there,

I have a development setup with VS Code 1.20, Chrome Debugger extension and webserver that uses webpack-dev/hot-middleware for HMR and Webpack with vue-loader to serve a VueJS application.

Breakpoints I set in VS Code are hit but they open up the files added by Webpack HMR instead of the original file.

If I add a breakpoint in one of the source files it will be hit correctly but open the wrong file in VS Code. The file is named with the number that corresponds with the `http://webpack-internal/35` URL that is visible in the Sources panel in Chrome, it is the compiled version served by HMR matching the right component. Chrome has the same behaviour and opens the wrong file.

If I check `.scripts` in the debug console it shows:

```› webpack-internal:///35
    - webpack:///./resources/assets/js/components/Questionnaire.vue?2620 (/Users/x/Sites/x/resources/assets/js/components/Questionnaire.vue)
```

The last path is the correct path for the source file. I'm at a loss as to what's happening here and whether this is a configuration issue or a bug. Thanks a bunch for helping out!

---

Some configuration details:

`launch.json` looks like this:

```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "breakOnLoad": true
        }
    ]
}
```

`webpack.config.js` looks roughly like this:

```let config = {
  entry: {
    app: ['webpack-hot-middleware/client', './resources/assets/js/app.js']
  },
  output: {
    filename: 'js/[name].js',
    publicPath: 'http://localhost:3000/'
  },
  devtool: 'eval-source-map',
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new WebpackNotifierPlugin(),
    new CleanWebpackPlugin(['public/styles', 'public/js']),
    new webpack.DefinePlugin({
        'process.env': {
            NODE_ENV: '"development"'
        }
    })
  ]
}
```

`webpack:///./resources/assets/js/components/Questionnaire.vue?2620` where the breakpoint in Chrome leads to has this Webpack footer:

```//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-b4ea8908","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./resources/assets/js/components/Questionnaire.vue
// module id = 35
// module chunks = 0
```

The `35` file in VS Code that is opened has this footer:
```//# sourceURL=[module]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9yZXNvdXJjZXMvYXNzZXRzL2pzL2NvbXBvbmVudHMvUXVlc3Rpb25uYWlyZS52dWU/MjYyMCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsaUJBQWlCO0FBQ2pCO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBIiwiZmlsZSI6IjM1LmpzIiwic291cmNlc0NvbnRlbnQiOlsidmFyIHJlbmRlciA9IGZ1bmN0aW9uKCkge1xuICB2YXIgX3ZtID0gdGhpc1xuICB2YXIgX2ggPSBfdm0uJGNyZWF0ZUVsZW1lbnRcbiAgdmFyIF9jID0gX3ZtLl9zZWxmLl9jIHx8IF9oXG4gIHJldHVybiBfYyhcImRpdlwiLCBbX3ZtLl92KFwiXFxuICBDb21wb25lbnRcXG5cIildKVxufVxudmFyIHN0YXRpY1JlbmRlckZucyA9IFtdXG5yZW5kZXIuX3dpdGhTdHJpcHBlZCA9IHRydWVcbnZhciBlc0V4cG9ydHMgPSB7IHJlbmRlcjogcmVuZGVyLCBzdGF0aWNSZW5kZXJGbnM6IHN0YXRpY1JlbmRlckZucyB9XG5leHBvcnQgZGVmYXVsdCBlc0V4cG9ydHNcbmlmIChtb2R1bGUuaG90KSB7XG4gIG1vZHVsZS5ob3QuYWNjZXB0KClcbiAgaWYgKG1vZHVsZS5ob3QuZGF0YSkge1xuICAgIHJlcXVpcmUoXCJ2dWUtaG90LXJlbG9hZC1hcGlcIikgICAgICAucmVyZW5kZXIoXCJkYXRhLXYtYjRlYTg5MDhcIiwgZXNFeHBvcnRzKVxuICB9XG59XG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9ub2RlX21vZHVsZXMvdnVlLWxvYWRlci9saWIvdGVtcGxhdGUtY29tcGlsZXI/e1wiaWRcIjpcImRhdGEtdi1iNGVhODkwOFwiLFwiaGFzU2NvcGVkXCI6ZmFsc2UsXCJidWJsZVwiOntcInRyYW5zZm9ybXNcIjp7fX19IS4vbm9kZV9tb2R1bGVzL3Z1ZS1sb2FkZXIvbGliL3NlbGVjdG9yLmpzP3R5cGU9dGVtcGxhdGUmaW5kZXg9MCEuL3Jlc291cmNlcy9hc3NldHMvanMvY29tcG9uZW50cy9RdWVzdGlvbm5haXJlLnZ1ZVxuLy8gbW9kdWxlIGlkID0gMzVcbi8vIG1vZHVsZSBjaHVua3MgPSAwIl0sInNvdXJjZVJvb3QiOiIifQ==
//# sourceURL=webpack-internal:///35
```

The Sources panel in Chrome looks like this:

![screen shot 2018-02-11 at 13 31 34](https://user-images.githubusercontent.com/597072/36073379-ebfeb4f6-0f2f-11e8-995c-d73b0397a675.png)

**Comment by roblourens** [comment]
I think having both a sourceURL and a sourceMappingURL might be strange. Try just `devtool: 'source-map'`. Otherwise, can you run with `"trace": true` and attach the log file here?

**Comment by auchenberg** [comment]
This indeed is a sourcemapping problem, since neither Chrome DevTools or our debugger can pick up the references.  Using the `'source-map'` setting in webpack should generate the most detailed sourcemap, which hopefully works.

**Comment by lillehummer** [comment]
Hi @roblourens, @auchenberg, changing to `'source-map'` seems to solve my problem indeed. Can confirm it is now working on two separate projects, although I've had a few times where it would open up the compiled and bundled app.js file, I'll let you know if I still run into any problems.

If you are interested I can still provide you with the log files for the `'eval-source-map'` output, if I recall correctly this was the setting that was suggested to be used with Chrome Debugger in various online sources.

Thanks a bunch for helping out!

**Comment by auchenberg** [comment]
Attaching your logs would be great @lillehummer, but in general we know 'eval-source-map' doesn't contain enough information for our debugger, so it simply won't work in most cases.
