### ISSUE TITLE
Getting path mapping to work with a rails & sprockets 3 (without sourcemaps)

### ISSUE THREAD

**Issue by aharpervc** [microsoft/vscode-chrome-debug#598]
- VS Code Version: 1.20.0

Steps to reproduce:

1. set up a launch configuration to launch chrome, and confirm that it works & the debugger is connected to chrome, and source maps is off
2. run `.scripts` and confirm that path mapping doesn't match expectations

I would like to configure this extension to work for a Rails project using Sprockets 3. This version does not produces source maps (introduced with Sprockets 4). I believe that it may still be possible to set things up to work right using a clever path mapping.

When I set up `pathMapping` as

```json
"pathMapping":{
  "/": "${workspaceFolder}/app",
}
```

I get the following from `.scripts`:

```log
› http://localhost:3000/assets/session.self.js?body=1 (C:\users\aharper\workspace\my-rails-app\app\assets\session.self.js)
```

The actual file path on disk for this asset is `C:\users\aharper\workspace\my-rails-app\app\assets\javascripts\session.js` It is the same as what vscode-chrome-debug assumes it is, except without the `.self` part, which is inserted into the served asset url by Sprockets. So, pretty close right off the bat.

I then tried the following path mappings:

```json
"pathMapping":{
  "/assets/session.self.js": "${workspaceFolder}/app/assets/javascripts/session.js",
}
```

This does work, for this single file! Partial success!

However, my project has a lot of asset files, and it would be burdensome to create an explicit mapping for every single one. Is there a clever glob syntax I could use to remove `.self` in the file paths? Is there any way to make this work without hand crafting each asset listing in pathMapping?

**Comment by roblourens** [comment]
So every file is named like `x.self.js` => `x.js`, `y.self.js` => `y.js`, and so on? You can use a wildcard in the pathMapping, this might work:

```json
"pathMapping": {
  "/assets/*.self.js": "${workspaceFolder}/app/assets/*.js",
}
```

**Comment by aharpervc** [comment]
> So every file is named like x.self.js => x.js, y.self.js => y.js, and so on?

Correct.

> You can use a wildcard in the pathMapping, this might work:

This is what I was hoping would work. However, it does not work, ie, `.scripts` shows no mapped paths.

To clarify:

```json
"pathMapping":{
  "/assets/session.self.js": "${workspaceFolder}/app/assets/session.js",
}
```
results in:

```
› http://localhost:3000/assets/session.self.js?body=1 (C:\users\aharper\workspace\my-rails-app\app\assets\session.self.js)
```

Whereas

```json
"pathMapping": {
  "/assets/*.self.js": "${workspaceFolder}/app/assets/*.js",
}
```
results in no mappings. The asset urls are listed but without corresponding file paths.

(Btw, in the process of sanitizing this example case, I edited the asset path incorrectly. In all cases, the on disk path is `/app/assets/javascripts/whatever.js`. But it's the file name rather than the folder path which is the trouble. In real life, I have the path set correctly.)

**Comment by roblourens** [comment]
This case works fine for me. Can you run with `"trace": true` and upload the log here?

**Comment by aharpervc** [comment]
> Can you run with "trace": true and upload the log here?

Done, and included my launch.json as well in case anything stands out: https://gist.github.com/aharpervc/b2027c3cd403900b0e652dd10820b6d5

I did need to sanitize it a bit, since this is a real app. One thing I believe it a red herring is using both `\` and `/` for path separators... I tested pathMapping with both and the effect was the same (ie, still doesn't work). Also, when mapping session.js individually as described above, I had been using `/`, and it worked for that one file.

**Comment by roblourens** [comment]
Ok, I see the issue. PathMapping simply doesn't actually support wildcards, and my test wasn't valid because it was able to fall back on webRoot. I don't have any other workaround to suggest.

I'll take this as a feature request for wildcards in pathMapping. A PR would be cool ;)

**Comment by aharpervc** [comment]
> A PR would be nice ;)

I am not at all familiar with extension development. Is there a guide somewhere for setting up a dev environment for this project?

**Comment by roblourens** [comment]
There's a guide here https://github.com/Microsoft/vscode-chrome-debug/blob/master/CONTRIBUTING.md

and the relevant function is here https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeUtils.ts#L12

**Comment by aharpervc** [comment]
@roblourens I have opened a preliminary PR here: https://github.com/Microsoft/vscode-chrome-debug-core/pull/286

**Comment by SE2Dev** [comment]
I just encountered the need for this feature the other day, as it could be incredibly useful for debugging SharePoint projects.

I noticed that the sourceMap code only supports a single wildcard character, but I was wondering if it would also be useful to map more complex paths that require multiple wildcards as well. As a result, I considered driving functionality using regular expressions, in which case the pathMappings would look like this:
```json
"pathMapping": {
  "regexp:\/assets\/(.*).self.js": "${workspaceFolder}/app/assets/($1).js",
}
```
but the keys tend to look somewhat verbose when using this format. Perhaps simply detecting the asterisk character, and supporting positional replacements would be enough? Ex.
```json
"pathMapping": {
  "/assets/*.self.js": "${workspaceFolder}/app/assets/${1}.js",
}
```

@roblourens Would this functionality be practical or do you still think it should mirror the sourceMap functionality that currently exists. I haven't looked *too* much into the source map code yet, but I definitely think that this feature is useful in certain situations.

Also, does anyone know chrome possesses the functionality to map (local overrides)[https://developers.google.com/web/updates/2018/01/devtools#overrides] to specific files in the VSCode workspace rather than opening the entire Chrome override directory as a workspace in VSCode. (I suppose technically this feature could be mimicked by using a multi-folder workspace, but for ASP.NET generated sites, this could get rather messy.

**Comment by roblourens** [comment]
I'd really like to avoid making this any more complicated. Is there any way to unblock your debug scenario without supporting multiple wildcards?

**Comment by SE2Dev** [comment]
Yeah, definitely. I'll look into the source maps code a bit more and once I have a solid sense of how everything is set up I'll look into porting the code to the pathMapping feature.

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
