### ISSUE TITLE
the site can't be reached

### ISSUE THREAD

**Issue by AyushKenhi** [Microsoft/vscode-chrome-debug#605]
- VS Code Version: 1.20.1

> The extension operates in two modes - it can launch an instance of Chrome navigated to your app, or it can attach to a running instance of Chrome. Both modes requires you to be serving your web application from local web server, which is started from either a VS Code task or from your command-line. Using the url parameter you simply tell VS Code which URL to either open or launch in Chrome.

I wasn't able to understand the above in readme about local web server. This is my auto-generated launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
it launches new instance of chrome with url `localhost:8080` . 
I get this 
![image](https://user-images.githubusercontent.com/18135995/36804877-dc094d26-1ce1-11e8-8d05-1cef95a7a0b9.png)

**Comment by auchenberg** [comment]
@AyushKenhi You need to run your own local website thats available on the `url` you define in your `launch.json`, so in this case your web server needs to run on `http://localhost:8080`

**Comment by AyushKenhi** [comment]
@auchenberg and how exactly can I do that 
> so in this case your web server needs to run on http://localhost:8080

**Comment by auchenberg** [comment]
You have multiple options. This article on MDN would be a good start: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
