### ISSUE TITLE
Breakpoint ignored because generated code not found - React, Webpack

### ISSUE THREAD

**Issue by phamquocduy** [Microsoft/vscode-chrome-debug#607]
- VS Code Version: 1.20.1

I've been unable to get the Chrome Debugger to work with with the below setup in an React app. I've been working on this for the past couple days and can't seem to find a solution.

Any assistance you could provide would be much appreciated!

**launch.json**
```javascript
{
      "name": "Launch Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:1234/",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}/public",
      "trace": true,
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/webpack:/src/"
      }
 }
```

**Project structure**
https://imgur.com/a/ZSva9

**Output .scripts**
[scripts_output.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1770626/scripts_output.txt)

**Comment by roblourens** [comment]
Why are you setting this? `"webpack:///src/*": "${webRoot}/webpack:/src/"`? Where does that come from? The right side should resolve to the correct path for the script. You may not even need sourceMapPathOverrides.

**Comment by phamquocduy** [comment]
Hi roblourens, thank you for response. Maybe I did not truly understand what should have to be done there... Webpack bundles the codes from src folder into public folder as you can see in my project structure, I set it up according to .script output. Can you give me some advice how to set up debugging there ?

**Comment by roblourens** [comment]
First try without sourceMapPathOverrides. If it doesn't work, use `.scripts` to guide adding them. See the description of how it works in the docs: https://github.com/Microsoft/vscode-chrome-debug#sourcemaps

**Comment by phamquocduy** [comment]
I did some research and found this similar issue

https://github.com/Microsoft/vscode-chrome-debug/issues/357

Final package.json that works for me

`{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:1234",
      "webRoot": "${workspaceRoot}/public/",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///*": "${workspaceRoot}/src/*"
      }
    }
  ]
}
`

Btw thank you for your help 👍
