### ISSUE TITLE
how to build angular 1 !!!!!!!!!

### ISSUE THREAD

**Issue by Moonies** [Microsoft/vscode-chrome-debug#608]
now !!
ERR_CONNECTION_REFUSED
my configuration
"configurations": [
        {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080/index.html",
            "webRoot": "${workspaceRoot}/D:/SP/WEBAPP/new-bcs/"
        },
        {
            "name": "Launch index.html (disable sourcemaps)",
            "type": "chrome",
            "request": "launch",
            "sourceMaps": false,
            "file": "${workspaceFolder}/index.html"
        },
    ]

web root ?? file ?? 
my extensions
angular essentials
debugger for chrome
view in browser

**Comment by roblourens** [comment]
Please explain your question some more.

**Comment by Moonies** [comment]
i need to debug angular 1 with google chrome
and installed extension debugger for chrome la not working

**Comment by auchenberg** [comment]
We have several Angular recipes in https://github.com/Microsoft/vscode-recipes, and there's several articles found online to. Look at your sourcemap/bundle setup and make the nessesary adjustments to your `webRoot` property.
