### ISSUE TITLE
Chrome crashes when I stop debugging

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-chrome-debug#61]
Chrome crashes when I stop the the vscode debugging session.
The next time i start debugging chrome asks to send a crash report.
Chrome also crashes if I try to inspect an element.
Not sure if this is related to vscode debugger or if this is a chrome remote debugging issue.

My system: Win10 x64, Chrome 47.0.2526.73 x64

**Comment by roblourens** [comment]
When you click the stop debugging button, the extension shuts down Chrome, which is by design. Chrome just thinks it's crashing. Earlier I made a change to make it shut down gracefully but it only works sometimes, and I'm not sure why. If you have any idea, I'm open to PRs :)

**Comment by skolmer** [comment]
"Note: Currently, the Chrome debugging protocol supports only one client per page. So you can use the DevTools to inspect a page, or use a third-party client, but not both at the same time."
https://developer.chrome.com/devtools/docs/integrating#debugging-protocol-clients

If I understand this right, every time I hit F12 to inspect and element the remote debugging session will be closed and vscode-chrome-debugger will close chrome. That explains why chrome seems to crash when I try to inspect an element while connected to vscode debugger.

I would prefer to keep the chrome instance open even if I detach the debugger to be able to switch between devtools and remote debugging. I could use the attach launch configuration to attach to the chrome instance later again.

**Comment by roblourens** [comment]
In this case the extension doesn't explicitly kill Chrome. The chrome process is a child of the extension process, so when Code kills the extension process, Chrome gets killed too. I tried a couple things to fix it by detaching the Chrome process but couldn't get it to work - I think there's something weird with Windows here. Feel free to open an issue and I'll take another look when I get a chance. In *theory* it's fixable.

**Comment by skolmer** [comment]
maybe this can help to find a fix: https://nodejs.org/api/child_process.html#child_process_options_detached
it states: "When using the detached option to start a long-running process, the process will not stay running in the background after the parent exits unless it is provided with a stdio configuration that is not connected to the parent."

**Comment by roblourens** [comment]
That's what I was trying :). I'll take another look when I get a chance.
