### ISSUE TITLE
mapping to {url}:80 fails

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode-chrome-debug#611]
VSC 1.21, OS Win10x64

with ``"url": "http://127.0.1.7:80/",`` in launch.json:
![](https://lh3.googleusercontent.com/-3a8ewuLw0rw/WqH9YpJHLJI/AAAAAAAAAoU/dAl-I-enD1QnmZw65-B9o1rMYj3Ck7cUwCHMYCw/s0/Code_2018-03-09_04-20-01.png)

Also why does the debugger show the error via standard win alert (with the standard nerve-wrecking sound) instead via the [VSC one, that was advertised recently](https://code.visualstudio.com/updates/v1_21#_new-notifications-ui)?

Thank you.

**Comment by roblourens** [comment]
Looks like the page was redirected to 127.0.1.7 without the port? That should be exactly what's in the browser.

The native dialog is shown because it's a hard error that's a direct result of a user action, so we think the notification ui could be too easy to miss.

**Comment by Spown** [comment]
>Looks like the page was redirected to 127.0.1.7 without the port? That should be exactly what's in the browser.

Yes. Normally nobody would do that (adding ``:80``), but in this case the launch.json was generated with my custom yeoman generator. I input the port in the prompt (80 is the default) and it gets inserted everywhere, including launch. I've modified the generator so it makes an exception for this case:
``<%- port===80?'':(':'+port) -%>``
So you can either just ignore&close this "issue" or do something similar for your extension to ensure it never happens.

**Comment by roblourens** [comment]
Ok. I'm not going to special case it for now.
