### ISSUE TITLE
Breakpoint get hit only if it is defined after the debugging starts on VsCode

### ISSUE THREAD

**Issue by msaragnoli** [Microsoft/vscode-chrome-debug#618]
- VS Code Version: 1.21.1
- Log file (set `"trace": true` in launch config): [vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1817425/vscode-chrome-debug.txt)

Steps to reproduce:

1. Set some breakpoints on you javascript file - BEFORE start Debugging
2. Start Debugging on VsCode
3. The breakpoints aren't hit.
4. Refresh the Browser by hitting 'F5' or even 'Crtl + F5'
5. Breakpoints are not hit yet.
6. Keeping the debugging running, set a NEW breakpoint on the same .js file
7. Refresh the Browser.
8. The new breakpoint get hit

I think this is not a big issue, but it kind of bothers me a little.

I guess my launch.config is set correctly, once the breakpoint gets hit if it sets after the debugging starts.

**Comment by roblourens** [comment]
This is probably https://github.com/Microsoft/vscode/issues/45657#issuecomment-373556464, please update the Chrome Debug extension and try again

**Comment by msaragnoli** [comment]
Perfect, the Debugger for Chrome new version 4.2.1, fixed the issue.

Thank you!
