### ISSUE TITLE
Confusing source map docs

### ISSUE THREAD

**Issue by clozach** [Microsoft/vscode-chrome-debug#626]
- VS Code Version: n/a
- Log file (set `"trace": true` in launch config): n/a

Steps to reproduce:

The source map [docs](https://github.com/Microsoft/vscode-chrome-debug#sourcemaps) currently give the following mapping examples:

```javascript
"sourceMapPathOverrides": {
    "webpack:///./~/*": "${webRoot}/node_modules/*",       // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
    "webpack:///./*":   "${webRoot}/*",                    // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js",
    "webpack:///*":     "*",                               // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    "webpack:///src/*": "${webRoot}/*",                    // Example: "webpack:///src/App.js" -> "C:/project/src/App.js"
    "meteor://💻app/*": "${webRoot}/*"                    // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```

To understand what's confusing here, it helps to look at just the comments, so let's replace the actual code with '➿':

```javascript
"sourceMapPathOverrides": {
    ➿ // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
    ➿ // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js",
    ➿ // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    ➿ // Example: "webpack:///src/App.js" -> "C:/project/src/App.js"
    ➿ // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```

Note the capitalization inconsistency between `…index.js" -> /Users…` and `…app.js -> "/users…`, or between `…App.js" -> "C:…` and `…main.ts" -> "c:…`. Then there's the sudden switch from what looks like a *nix/macOS paths to Windows paths.

If these were presented as wholly independent examples, it might not be an issue, but they're all sandwiched together inside the "sourceMapPathOverrides" block, making it seem like this entire code sample could be dropped into a project to get similar outputs, which is surely not the case.

Basically, it seems like the definition of `webRoot` is getting implicitly changed between examples. It even seems to change between the last two examples, leaving me to wonder if that's something to do with the switch from `webpack` to `meteor`, or whether that's yet a third example environment.

Perhaps something like this would be clearer…

```javascript
// webRoot = "/Users/me/project/"
"sourceMapPathOverrides": {
    "webpack:///./~/*": "${webRoot}/node_modules/*",       // Example: "webpack:///./~/querystring/index.js" -> "/Users/me/project/node_modules/querystring/index.js"
    "webpack:///./*":   "${webRoot}/*",                    // Example: "webpack:///./src/app.js" -> "/Users/me/project/src/app.js",
}
```

…with a separate block for the `C:` drive examples, or two separate blocks if the `meteor` line is really its own thing?

**Comment by roblourens** [comment]
The example that I put in the docs is actually the set of overrides that are included in the extension to be applied by default. I included all of these to show how the patterns can be applied in different types of projects, not to show how anyone would configure it for a single project.

I think you're right that I should spell that out a little more, and keep variables like webRoot the same across examples.
