### ISSUE TITLE
Breakpoint ignored because generated code not found (source map problem?)

### ISSUE THREAD

**Issue by mrguzzi** [Microsoft/vscode-chrome-debug#628]
Hello,
the debugger was working  few 2 days ago and now no more without any evident change.
that's my launch.json configuration:
{
"name": "Attach to Chrome",
"type": "chrome",
"request": "attach",
"port": 9222,
"webRoot": "${workspaceRoot}"
}
Tried all the above but nothing change. Only if i set webRoot "${workspaceRoot}/rm-datadir-app/src"
it stops at breakpoint but in the wrong points

Tried also with sourceMapPathOverrides but without success.

Here is my .scripts response:
https://gist.github.com/mrguzzi/417489863ae5d5205e52baa15c1af4e9

Here is log:
https://gist.github.com/mrguzzi/5f0e2213f6145600b4d8da931c07ac74

- VS Code Version: 
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- Log file (set `"trace": true` in launch config):

Thanks

**Comment by roblourens** [comment]
As a side note, you may want to update vscode, 1.19 is getting a bit old.

What sourceMapPathOverrides did you try? You will need to fix the ng:///

**Comment by mrguzzi** [comment]
Hello @roblourens 
i succeeded with the following configuration:
 {
            "name": "Attach to Chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}/rm-datadir-app",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
              "webpack:///rm-datadir-app/src/*": "${webRoot}/rm-datadir-app/src/*"
            }            
        }

**Comment by roblourens** [comment]
I'm not sure where `rm-datadir-app` came from since I don't see that in your .scripts list, but I'm glad you got it to work!

**Comment by mrguzzi** [comment]
anyway it's behaving strange. Sometimes doesn't stop at the breakpoints
