### ISSUE TITLE
Webpack Examples

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/vscode-chrome-debug#63]
Hi I can't get this working on webpack using the middleware. Is it possible to add some example projects to see what the setup should be?

**Comment by skolmer** [comment]
I have created a sample project based on react-hot-boilerplate

**Comment by andrew-w-ross** [comment]
@skolmer I gave this project a try, I got it to break but only if I had a debugger statement. I think this might legitimately be a bug then.

**Comment by skolmer** [comment]
@andrew-w-ross I'm able to set breakpoints and step into the original source files. but it can take some time until the scripts are loaded in chrome and you can start debugging. 
you can set `"diagnosticLogging": true` in launch.json to see when the scripts are loaded

**Comment by andrew-w-ross** [comment]
@skolmer I'm assuming this is the most relevant bit of the log :
This appears when the page loads, I've removed all the other files for the sake of brevity.
```
  ›SourceMaps.scriptParsed: http://localhost:3000/bundle.js was just loaded and has mapped sources: [//Users/ross/Projects/react-hot-boilerplate-vscode/src/App.js"]
```

And then when I try and add the breakpoint:

```
  ›From client: setBreakpoints({"source":{"path":"/Users/ross/Projects/react-hot-boilerplate-vscode/src/App.js"},"lines":[8,7]})
  ›SourceMaps.setBP: /Users/ross/Projects/react-hot-boilerplate-vscode/src/App.js can't be resolved to a loaded script.
```

I'm going to take a wild guess but perhaps that extra slash at the front causes the mismatch? I'm on mac osx btw.

**Comment by roblourens** [comment]
That extra slash would be an issue... at one point I had a mac-only issue like that, I'll try this on a mac tomorrow.

**Comment by skolmer** [comment]
@andrew-w-ross please try to replace "file:///" by "file://" in webpack.config. It seems that windows requires three slashes while mac os only accepts two

**Comment by roblourens** [comment]
That might do it - file urls on Windows look like 'file:///C:/path' but on OSX, like 'file:///path/', inconsistent because on OSX the path by itself already starts with /

**Comment by skolmer** [comment]
@andrew-w-ross please try the latest version of the sample. I updated the webpack.config to address this issue.

**Comment by andrew-w-ross** [comment]
@skolmer That change you did correctly changes the file path so that it looks the same
```
  ›SourceMaps.scriptParsed: http://localhost:3000/bundle.js was just loaded and has mapped sources: ["/Users/ross/Projects/react-hot-boilerplate-vscode/src/App.js”]
```

And it seems to set the breakpoint correctly this time
```
  ›SourceMaps.setBP: Mapped http://localhost:3000/bundle.js:5:11 to /Users/ross/Projects/react-hot-boilerplate-vscode/file:/webpack/bootstrap%20de646338ebd06efb29be:4

  ›To client: {"seq":0,"type":"response","request_seq":9,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":true,"line":5}]}}
```

But it doesn't break when it gets to the method. I can verify it's connected and firing because I can see the little 'Hello World' log out to the debug console.

**Comment by skolmer** [comment]
@andrew-w-ross Does it break if you reload the page after you have set a breakpoint? I still have some issues with hot reloading. It only breaks if I don't change the code. If I make changes to the original source files I have to reload the page in chrome to get the debugging in vscode working again.

**Comment by andrew-w-ross** [comment]
@skolmer I gave that a try. It's still ignoring the breakpoints but it does break if I throw an exception and oddly enough inside the `hotDownloadUpdateChunk` function webpack uses even though it doesn't throw an exception. To be thorough I did try different devtool options to no avail.

Thanks for the help, I really appreciate it.

**Comment by skolmer** [comment]
I just took another look at your console output `›SourceMaps.setBP: Mapped http://localhost:3000/bundle.js:5:11 to /Users/ross/Projects/react-hot-boilerplate-vscode/file:/webpack/bootstrap%20de646338ebd06efb29be:4`

The to-path doesn't seem right, it should point at the original source file. If you run the code on your windows machine you should see the expected behavior.
Is this output based on a different configuration? Did you changed the dev tool in webpack config or anything else?
@roblourens do you have an idea what is going on here?

**Comment by roblourens** [comment]
The extension with file: in the middle is definitely wrong. I'll clone that repo and try it out.

**Comment by andrew-w-ross** [comment]
@skolmer  Everything but the App.js `clickHandler` function was the same. After I messed around with webpack.config to see if changing the sourcemaps could help.

**Comment by Gabriel0402** [comment]
I'm also using the angular2-webpack-starter. The only thing I need to change to make it work is the webpack.config:
```
output: {
    path: root('__build__'),
    filename: '[name].js',
    // filename: '[name].[hash].js',
    sourceMapFilename: '[name].js.map',
    chunkFilename: '[id].chunk.js',
    // publicPath: 'http://mycdn.com/'
    devtoolModuleFilenameTemplate: function(info){
      return "file:///"+info.absoluteResourcePath;
    }
  },
```
And the launch.json is:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "__build__"
		}
	]
}
```
Hope it helps!

**Comment by roblourens** [comment]
I tried to run this project on a Mac, but the server never started. It said it was listening on `localhost:3000` but I couldn't connect. Now I'm trying on Windows and I can connect to the server, but I get `Uncaught Error: Cannot find module "./src/index.js"`. Any idea what I'm missing?

**Comment by roblourens** [comment]
@andrew-w-ross It might be easier if you can just post the full log

**Comment by Gabriel0402** [comment]
@roblourens which node and npm version are you using? I pull the latest and it worked on Mac.

**Comment by skolmer** [comment]
@roblourens not sure why the dev server fails on your system. did you get any warnings or errors while running npm install? 
the console output of the running server should look like this:

> running command> node server.js
Listening at localhost:3000
webpack: wait until bundle finished: /index.html
Hash: d7e3fcf2e499bde96154
Version: webpack 1.12.9
Time: 17601ms
     Asset       Size  Chunks             Chunk Names
 bundle.js    2.42 MB       0  [emitted]  main
index.html  178 bytes          [emitted]  
chunk    {0} bundle.js (main) 873 kB [rendered]
    [0] multi main 52 bytes {0} [built]
   ...
  [247] ./~/react-hot-loader/isReactElementish.js 288 bytes {0} [built]
webpack: bundle is now VALID.


After the webpack bundling has finished (this could take some seconds) you should be able to connect to http://localhost:3000

**Comment by roblourens** [comment]
Node 4.2.1, and npm 2.14.7. I only see the first two lines of that log, like it's stuck on 'listening at localhost:3000'. I'll see if I can try on a different mac tomorrow, or debug it.

**Comment by roblourens** [comment]
Sorry for the slow response - I deleted my clone of that repo and tried again, and it ran fine this time.

I saw the same issue on OS X and found a bug that looks like it's probably responsible for this not working. I pushed the update, so let me know how it goes!

**Comment by skolmer** [comment]
@roblourens  I will test this as soon as I'm back in the office. Have a nice holiday and thanks!

**Comment by haarismian** [comment]
Was this resolved?
