### ISSUE TITLE
Breakpoint ignored because generated code not found (source map problem)

### ISSUE THREAD

**Issue by tsando** [Microsoft/vscode-chrome-debug#636]
Hi,

My breakpoint seems to be ignored and I'm not sure why. I am using VS Code Version 1.21.1.

This is the folder structure of my app. As you can see, it is inside the directory `app`.

![screen shot 2018-04-02 at 13 18 29](https://user-images.githubusercontent.com/13929456/38196000-6bef7f46-3678-11e8-9316-c6d48cb160e3.png)

My config file is this:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/app",
            "trace": true
        }       
    ]
}
```

When I try to put a breakpoint on `index.js` (line 5) this is ignored on the Chrome instance:

![screen shot 2018-04-02 at 13 21 33](https://user-images.githubusercontent.com/13929456/38196084-e80c5ae0-3678-11e8-92f3-e2c6ce70ce01.png)

When i type `.scripts` in the debug console, nothing comes out:

![screen shot 2018-04-02 at 13 22 55](https://user-images.githubusercontent.com/13929456/38196088-f90dd83c-3678-11e8-9a30-d85b0ec644d0.png)

I also attach the file `vscode-chrome-debug.txt`.

Would really appreciate your help to understand the problem. Thanks.

[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1868047/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
index.js looks like a node script. You are attached to Chrome. Do you want to debug node or chrome?
