### ISSUE TITLE
Breakpoint is not hit when offline.

### ISSUE THREAD

**Issue by threeFatCat** [Microsoft/vscode-chrome-debug#638]
- VS Code Version: 1.21.1 Windows x64
- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/1872115/vscode-chrome-debug.txt)

Steps to reproduce:

1. Create a basic reactjs app following the instruction [here](https://github.com/facebook/create-react-app). 
2. Add json configuration. I tried three samples json configuration:

    - https://code.visualstudio.com/docs/nodejs/reactjs-tutorial
    `{
                "type": "chrome",
                "request": "launch",
                "name": "Launch Chrome against localhost",
                "url": "http://localhost:3000",
                "webRoot": "${workspaceFolder}"
    }`

    - https://stackoverflow.com/questions/42714449/vscode-debugging-with-create-react-app
    -https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#debugging-in-the-editor
    `{
    "version": "0.2.0",
    "configurations": [{
        "name": "Chrome",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceRoot}/src",
        "userDataDir": "${workspaceRoot}/.vscode/chrome",
        "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
        }
    }]
    }`

    - **Similar to above but with slightly modified `sourceMapPathOverrides` which is the configuration attached in the log**:
    `"sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
    }`
3. Add to configuration:
`            "skipFiles": [
                "bundle.js"
            ],`
4. Add breakpoint anywhere. Sample: Breakpoint in index.js in this line:
`ReactDOM.render(<App />, document.getElementById('root'));`
5. Run code using `npm start`.
7. Testing:
        a. Press F5 to run debugger while there is network connection, you'll notice that the breakpoints are hit, no matter which configuration you used from above.
        b. Press F5 to run debugger while there is **NO** network connection, you'll notice that the breakpoints are not hit and display in the left panel :
 `Breakpoint ignored because generated code not found (source map problem?).`

I tried using vscode insiders but still the same thing occur. This is my very first time to post on github so please bear with me. Thank you

**Comment by roblourens** [comment]
Being offline is preventing it from resolving 'localhost'. I've seen similar issues with node. Assuming that url is correct, I can work around it by replacing 'localhost' with '127.0.0.1'.

```
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:3000/static/js/bundle.js.map
HTTP GET failed: Error: getaddrinfo ENOENT localhost:3000
```

**Comment by threeFatCat** [comment]
You're right, replacing localhost to 127.0.0.1 in the configuration works. At first I was confused how to reproduce the issue then finally bump that it is cause by working offline. Thank you.
