### ISSUE TITLE
CORS Support for VS code Chrome Debugger: Renders useless.

### ISSUE THREAD

**Issue by CLAV88** [Microsoft/vscode-chrome-debug#639]
- VS Code Version:
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Launch against a local file is not supported when querying api's because of CORS issue
![image](https://user-images.githubusercontent.com/23463357/38330886-c029df5e-381f-11e8-87d9-d29f357d6e38.png)

**Comment by roblourens** [comment]
You'll see the same thing whether you use the debug extension, or just open your file directly in Chrome, right?

**Comment by CLAV88** [comment]
Yes,

What to do?

**Comment by roblourens** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
