### ISSUE TITLE
Bug : Launch.json with command 

### ISSUE THREAD

**Issue by jmarandet** [Microsoft/vscode-chrome-debug#647]
Hi,

I am building a custom VSCode extension and I would like to handle my Chrome-debug settings, within the "url" field.

I thought that I could expose a command that just return a string, and then use the ${command:commandID} tips that figures on this page : https://code.visualstudio.com/docs/editor/variables-reference 

But I can't get it work...
When I start to debug my extension, I can see that the "vscode-chrome-debug" plugin really launch my custom command, as I can trace it. And my function is really simple so it really resolves to a string.
But nothing happens...

For example, here is a kind of launch.json setting that I would like to use : 

```
 {
     "configurations": [
         {
             "name": "myExtension settings",
             "type": "chrome",
             "request": "launch",
             "url": "${command:myExtension.url_command}"
         }
     ]
 }

```
and here is a really dummy custom command function that could be exposed by my extension : 
```
export function url_command():string {
   return 'https://www.google.fr';
}
```

**Comment by roblourens** [comment]
@isidorn?

**Comment by isidorn** [comment]
This should work fine
@jmarandet can you share your extension repository so I simply clone it and try to reproduce this. Thanks

**Comment by jmarandet** [comment]
Here you are @isidorn 

https://github.com/jmarandet/test_chrome

**Comment by jmarandet** [comment]
ok..., your exemple is showing a configurationSnippets strategy
I am a newby in VSCode extension authoring, and I still need to learn the ways to handle that stuff...
I will read more about that method and give it a try.

At a first glance I just thought to make my plugin pushing a launch.json config, with 
`
const launchConfig = vscode.workspace.getConfiguration('launch');
const configurations = launchConfig['configurations'];
configurations.push({ ... });
launchConfig.update('configurations', configurations, false);
`
And within the push, writting the same kind of command that I have summarized within the dummy 'test_chrome' extension.

**Comment by jmarandet** [comment]
I a updated my 'test_chrome' repository to show-up the strategy I was thinkin off.

**Comment by isidorn** [comment]
@jmarandet your package.json is not contributing variables. Please try doing that as the node debug is doing that in the example I provided a pointer to.
More about variables with a great example can be found here https://code.visualstudio.com/docs/extensions/example-debuggers

**Comment by jmarandet** [comment]
@isidorn : sorry for the bother, but I would like to clarify a little misunderstanging (on my side)

I thought that I could write a new extension that only contributes a custom variable for the vscode-chrome-debug extension.
But when I read the documentation you refers, it seems that I have to contribute my own debugger (with all the stuff like type, program, runtime, etc...), is that it ? 
Is that the direction you are advising me ?

Is it possible for me to only contribute a variable that would be resolved by the vscode-chrome-debug debugger ?

I found the VSCode documentation not clear about it. The first link of documentation ( https://code.visualstudio.com/docs/editor/variables-reference ) seems to say that it should be okay.
And the strange thing is that in the little code I gave to you, we can see the console message to be kicked off. So my custom function is called. 
Somewhere... and somehow...

**Comment by jmarandet** [comment]
ok... shame on me I got it.

I have updated my dummy repo.

**Comment by jmarandet** [comment]
@isidorn ; sorry twice, but it really seams that this method is buggy (cf. https://github.com/Microsoft/vscode/issues/45957#issuecomment-387104959 ) as it spawns several "Debug adapter process has terminated unexpectedly".

I also read https://github.com/Microsoft/vscode/issues/41182 but I didn't understood how to insert a breakpoint within the rawDebugSession.ts file...
