### ISSUE TITLE
Chrome crashes (sad face) and VS code can't connect in Windows 10

### ISSUE THREAD

**Issue by viktorlarsson** [Microsoft/vscode-chrome-debug#648]
- VS Code Version: Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Windows 10

- Log file (set `"trace": true` in launch config): 
Log file here: https://gist.github.com/viktorlarsson/66814402eb717b13d625ba646e3823ce
Steps to reproduce:

1. Add the following launch.json

```  
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "vuejs: chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src",
            "breakOnLoad": true,
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*"
            }
        },
}
```
2. Start the launch from VSCode

The following happends:
Chrome crashes with a sad face

![sad face](https://user-images.githubusercontent.com/722315/38934448-10f99076-431c-11e8-8cc1-88ea228a3da9.png)

And VSCode states the following

![launch error](https://user-images.githubusercontent.com/722315/38934371-e45c0382-431b-11e8-8918-7725bc6bd2b5.png)

Any ideas why this might occur?

**Comment by roblourens** [comment]
Can you try setting `port` to some number to force it to use a different userDataDir?

Also, try closing all running instances of Chrome, then starting with `"userDataDir": false`?

**Comment by viktorlarsson** [comment]
I've actually managed to get it running, but using a runtimeFlag on chrome which you probably shouldn't use. It displays a warning, but if someone else also receives this error it might help them. 

```  
        {
            "type": "chrome",
            "request": "launch",
            "name": "dev: chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}",
            "breakOnLoad": true,
            "sourceMapPathOverrides": {
                "webpack-inline:///src/*": "${webRoot}/src*/",
            },
            "runtimeArgs": ["--no-sandbox"],
            "sourceMaps": true
        },
```

![image](https://user-images.githubusercontent.com/722315/38984417-e94b0cfc-43c6-11e8-98a2-8e6207953120.png)

**Comment by viktorlarsson** [comment]
@roblourens Yes!

**Comment by roblourens** [comment]
I recommend not doing that. If you have to, you can try adding the unofficial option `"shouldLaunchChromeUnelevated": true` to your launch config.
