### ISSUE TITLE
Restart kills browser rather than just refreshes it

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#65]
This is a performance issue. Would be nice to have the option in the launch config

**Comment by roblourens** [comment]
Do you mean the restart icon at the top of Code? The extension doesn't have control of that unfortunately. It's like clicking stop then start.

**Comment by justin-romano** [comment]
Ah yes. Do you have a means with the extension API to add buttons with keybindings?

**Comment by roblourens** [comment]
An extension can register a command with a keybinding, but debug adapters are not normal extensions. They run in their own process and don't have access to the normal extension APIs. So a debug adapter can't easily add a keybinding to refresh the page. Maybe Code will address that in the future.

**Comment by roblourens** [comment]
Closing since I don't have a good solution for now.
