### ISSUE TITLE
disableNetworkCache is not working

### ISSUE THREAD

**Issue by areinoza** [Microsoft/vscode-chrome-debug#650]
disableNetworkCache is not working

- VS Code Version: 1.22.2

Steps to reproduce:

1. Setup "disableNetworkCache": true in launch.json
2. Launch app
3. Open Chrome DevTools
4. Open Settings in DevTools
5. Review disable cache (while debugging only) option.

**Comment by roblourens** [comment]
Maybe the devtools UI state is not synced correctly, but the extension is sending the right message to disable the network cache.

`→ To target: "{\"id\":14,\"method\":\"Network.setCacheDisabled\",\"params\":{\"cacheDisabled\":true}}"`

So let me know if you see incorrect behavior that seems like it hasn't disabled the cache.
