### ISSUE TITLE
interruption points are being ignored

### ISSUE THREAD

**Issue by newmesiss** [microsoft/vscode-chrome-debug#651]
hello, since a few days I have a problem, I can not debug in all my files, this happened after updating several libraries, now most of my interruption points are ignored, besides the points that these will always be in a copy file read only, this did not happen before.

- VS Code Version: 1.22.2

```config: 
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "chrome",
        "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
        "port": 9222,
        "webRoot": "${workspaceRoot}",
        "sourceMaps": true,
        "trace": true
        
      }
    ]
  }```

**Comment by roblourens** [comment]
> this happened after updating several libraries

Which libraries? What is your project like? Can you share your project?

**Comment by newmesiss** [comment]
dejo aqui mi package.json  
old: ![oldp](https://user-images.githubusercontent.com/5264883/39503191-e80febc2-4d9a-11e8-964c-424d05f3e502.png)
 new: 
![newp](https://user-images.githubusercontent.com/5264883/39503212-002ad1e0-4d9b-11e8-82fd-4686fdca4e75.png)

project structure: 
![screenshot at may 01 23-55-34](https://user-images.githubusercontent.com/5264883/39503237-2c4ce7ae-4d9b-11e8-9970-28eff0ca6d74.png)

**Comment by roblourens** [comment]
If you run the `.scripts` command does it show your scripts as being resolved correctly?

Can you share the project?

**Comment by newmesiss** [comment]
file .scripts
https://www.pastefs.com/pid/54083
I have no option to share private project

**Comment by newmesiss** [comment]
I attach new configurations that it establishes, even so it does not stop solving my problem
.scripts https://www.pastefs.com/pid/54204
launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}/src"
        }
     
    ]
}

**Comment by roblourens** [comment]
Can you try again in the latest chrome-debug version, 4.4.1?

**Comment by newmesiss** [comment]
@roblourens  the problem is still with Chrome-Debug, 4.4.1. I've also noticed that when I add breakpoints in some places they do not add up and jump to other points

**Comment by newmesiss** [comment]
@roblourens I just created another project and the problem continues in the new project

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/). Particularly, the bug template in that repo has instructions that will let you collect a detailed log file that should help us resolve your issue.
