### ISSUE TITLE
bug - Attach debug option doesn't work, throws an error

### ISSUE THREAD

**Issue by slishnevsky** [Microsoft/vscode-chrome-debug#654]
Followed instructions to the letter.

Extension installed

launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Attach to Chrome",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
Chrome is started with documented remote debugging parameter:

**"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222**

Web server is started using "serve -p 8080", the page is loaded at: http://localhost:8080/

When I click on Debug green arrow icon (with "Attach to Chrome" option) VSCode throws an error:

**Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: ECONNREFUSED 127.0.0.1:9222)**

There are many posts regarding this bug, but no solution.

**Comment by roblourens** [comment]
You probably have a running instance of Chrome already. Close it first or see the notes on using `--user-data-dir` in the readme (I just tweaked the readme notes about this kind of issue)
