### ISSUE TITLE
update to 4.4.0 failed

### ISSUE THREAD

**Issue by simahao** [Microsoft/vscode-chrome-debug#655]
when updated to 4.4.0, update progress show installing status all the time.I uninstalled the plugin,deleted related directory and reinstalled,install progress still show "installing" and could not finish normally.

**Comment by roblourens** [comment]
I accidentally included a large file that I shouldn't have. I just published 4.4.1 that fixes it - please try it out.

**Comment by Doppp** [comment]
@roblourens The install is still taking forever.

**Comment by roblourens** [comment]
It's basically as small as it can be now. Smaller than many other extensions.

**Comment by asampal** [comment]
I'm still seeing the endless install with 4.4.1.

**Comment by eamodio** [comment]
I am seeing the same thing on both my Windows 10 machines. This is what I see in the `Log (Shared)` channel:
```
[2018-05-04 23:33:16.834] [sharedprocess] [info] Installing extension: debugger-for-chrome
[2018-05-04 23:33:17.126] [sharedprocess] [info] Downloaded extension: debugger-for-chrome
[2018-05-04 23:33:41.032] [sharedprocess] [info] Starting to clean up unused language packs.
```

I've tried completely wiping the extension folder (with vscode closed) and I get the same behavior no matter what I try. I also see the same behavior in both stable and insiders versions of vscode too.

**Comment by roblourens** [comment]
I see the same on Windows. Will keep investigating...

**Comment by roblourens** [comment]
Ok, there was a file in the package that got renamed to `(*&)))&^.js` somehow. Not sure where that came from but it was causing the unzip to fail on windows. Please try again with 4.4.3.

**Comment by simahao** [comment]
it works,3ks.
