### ISSUE TITLE
4.4.1 does not install

### ISSUE THREAD

**Issue by DRempfer** [Microsoft/vscode-chrome-debug#657]
Subject says it all. Install from within vscode hangs, trying to install from the command line gives error message:

WARNING: Promise with no error callback:287
{ exception: null,
  error:
   { Error: ENOENT: no such file or directory, open 'C:\Users\username\.vscode\extensions\.msjsdiag.debugger-for-chrome-4.4.1\node_modules\vscode-chrome-debug-core\out\src\(*&)))&^.js'
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',

and so on...

**Comment by dotnetengineers** [comment]
Having same issue with VS insiders - nightly build

**Comment by mon6912640** [comment]
I encountered the same problem.

I had reverted to v4.3.0 by offline installation package.

**Comment by solar-vibez** [comment]
@mon6912640 how can I downgrade? Encountered the same issue with vscode 1.23.0...

**Comment by timurmelnikov** [comment]
I confirm the problem

**Comment by Refs** [comment]
@mon6912640  thank you solve my problems;  additional to tie `" extensions.autoUpdate": false` in the user settings to disable vscode extension auto update action

**Comment by cloving** [comment]
This problem does not exist in the linux version of vscode

**Comment by DannyDobrev** [comment]
I have the same problem on Windows, it's stuck on installing.

**Comment by PimmoZz** [comment]
@roblourens Any updates? 4.4.1 won't install on windows.

**Comment by kalints** [comment]
+1 for this, some info from my end:

### Visual Studio Code Version:

```
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

### Trace of the error:

```
$ code --install-extension msjsdiag.debugger-for-chrome
Found 'msjsdiag.debugger-for-chrome' in the marketplace.
Installing...
WARNING: Promise with no error callback:254
{ exception: null,
  error:
   { Error: ENOENT: no such file or directory, open 'C:\Users\kalin\.vscode\extensions\.msjsdiag.debugger-for-chrome-4.4.1\node_modules\vscode-chrome-debug-core\out\src\(*&)))&^.js'
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Users\\kalin\\.vscode\\extensions\\.msjsdiag.debugger-for-chrome-4.4.1\\node_modules\\vscode-chrome-debug-core\\out\\src\\(*&)))&^.js' },
  promise:
   { _oncancel: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: v],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value:
      { Error: ENOENT: no such file or directory, open 'C:\Users\kalin\.vscode\extensions\.msjsdiag.debugger-for-chrome-4.4.1\node_modules\vscode-chrome-debug-core\out\src\(*&)))&^.js'
        errno: -4058,
        code: 'ENOENT',
        syscall: 'open',
        path: 'C:\\Users\\kalin\\.vscode\\extensions\\.msjsdiag.debugger-for-chrome-4.4.1\\node_modules\\vscode-chrome-debug-core\\out\\src\\(*&)))&^.js' },
     _isException: false,
     _errorId: 254,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 254,
  parent: undefined }
C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:58
define(e[9],t([1,0,2]),function(e,t,n){"use strict";function r(e){i(e)||t.errorHandler.onUnexpectedError(e)}function i(e){return e instanceof Error&&e.name===u&&e.message===u}Object.defineProperty(t,"__esModule",{value:!0});var o={};n.TPromise.addEventListener("error",function(e){var t=e.detail,n=t.id;t.parent?t.handler&&o&&delete o[n]:(o[n]=t,1===Object.keys(o).length&&setTimeout(function(){var e=o;o={},Object.keys(e).forEach(function(t){var n=e[t];n.exception?r(n.exception):n.error&&r(n.error),console.log("WARNING: Promise with no error callback:"+n.id),console.log(n),n.exception&&console.log(n.exception.stack)})},0))});var s=function(){function e(){this.listeners=[],this.unexpectedErrorHandler=function(e){setTimeout(function(){if(e.stack)throw new Error(e.message+"\n\n"+e.stack);throw e},0)}}return e.prototype.addListener=function(e){var t=this;return this.listeners.push(e),function(){t._removeListener(e)}},e.prototype.emit=funct

Error: ENOENT: no such file or directory, open 'C:\Users\kalin\.vscode\extensions\.msjsdiag.debugger-for-chrome-4.4.1\node_modules\vscode-chrome-debug-core\out\src\(*&)))&^.js'

Error: ENOENT: no such file or directory, open 'C:\Users\kalin\.vscode\extensions\.msjsdiag.debugger-for-chrome-4.4.1\node_modules\vscode-chrome-debug-core\out\src\(*&)))&^.js'
    at Timeout._onTimeout (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:58:758)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) 
```

**Comment by JAugustusSmith** [comment]
Same issue on 2 machines

**Comment by snailuncle** [comment]
@mon6912640 
感谢大佬,已经成功安装, 就是一直提示更新到4.4.1,

**Comment by ozone702** [comment]
This was first posted here: https://stackoverflow.com/questions/50184838/cannot-install-debugger-for-chrome-into-visual-studio-code

The temporary solution is:

- close VS Code
- in file explorer go to %UserProfile%\.vscode\extensions
- remove .msjsdiag.debugger-for-chrome-4.4.1 directory
- start VS Code
- disable auto updating extensions from EXTENSIONS menu in VS Code
- download prior version from here: https://msjsdiag.gallery.vsassets.io/_apis/public/gallery/publisher/msjsdiag/extension/debugger-for-chrome/4.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
- rename the file to have a .vsix extension
- choose "install from VSIX" from EXTENSIONS menu in VS Code

**Comment by Seefer1** [comment]
So there's no way to install 4.4.1 or update from 4.3.0 to 4.4.1 at the moment?

**Comment by ozone702** [comment]
@Seefer1 Currently I do not believe so.  A bot has assigned this to a MS developer to look into.

**Comment by mkotormus** [comment]
I tried downgrading vscode (uninstall/reinstall) to 1.21.1 and installing dev tools 4.4.1 worked (doing the same on higher version of vscode gets stuck even when doing first install of dev tools 4.4.1. So it maybe due to some recent change in vscode as well.

**Comment by dotnetengineers** [comment]
Just tried new version release 4.2.2 - Same issue - Not Fixed - Ughhh

Having same issue with VS insiders - nightly build Version 1.24.0-insider

Update: Workaround - restore version 4.3.0 from Backup to C:\Users\.vscode-insiders\extensions

**Comment by roblourens** [comment]
Sorry about this - please try 4.4.3, it should be fixed.

**Comment by dotnetengineers** [comment]
Just installed new version release 4.2.3 - Installed flawlessly - Will test functionality later ;>) - Thanks @roblourens  

VS insiders - nightly build Version 1.24.0-insider

**Comment by ozone702** [comment]
I just installed 4.4.3 and it installed fine.  Thank you Rob for the quick turn around!

**Comment by timurmelnikov** [comment]
Новая версия - работает. Спасибо!
