### ISSUE TITLE
Breakpoint does not get hit

### ISSUE THREAD

**Issue by patrickhaug** [Microsoft/vscode-chrome-debug#660]
- VS Code Version: 2.9.0

I have a server rendered react app through php v8 and in dev mode it get's the client file via webpack-dev-server. when i want to hit a breakpoint when client took over, it says breakpoint ignored. 
when running .scripts i see all sourcemap entries from the client file. 

`{
  "type": "chrome",
  "request": "launch",
  "name": "Launch Chrome",
  "url": "https://xxxxx.xx.localhost",
  "webRoot": "${workspaceFolder}/src/",
  "sourceMaps": true,
  "smartStep": true,
  "skipFiles": [
    "node_modules/**"
  ]
}`

what could I do?

**Comment by roblourens** [comment]
See the troubleshooting section of the readme: https://github.com/Microsoft/vscode-chrome-debug/blob/master/README.md#troubleshooting

Especially the section with the `.scripts` command to see whether your sourcemaps are resolved correctly.
