### ISSUE TITLE
"Unverified breakpoints", behavior is different from a few days ago.

### ISSUE THREAD

**Issue by ogrotten** [microsoft/vscode-chrome-debug#663]
I'm working on a node project with pug templating. Backend debugging works fine.

When I installed Debugger for Chrome module, it worked well. It would spawn a new, separate chrome instance specifically for this project. 

Today however this functionality has stopped. It doesn't spawn a new chrome instance and breakpoints cannot be set. I'm 96% sure that I did not change the configuration to cause this. 

Is there a preferred launch.json config to produce the original behavior?

**Comment by roblourens** [comment]
> It doesn't spawn a new chrome instance 

Can you explain the problem some more? Nothing changed around how Chrome is spawned.

One thing to narrow it down would be to set `"port": 9250` or some other number besides the default.

You could run with `"trace": true` and attach the log here if that helps.

**Comment by ogrotten** [comment]
I'm sorry, I don't have much more in the way of details. I set it up, it was working, and I pretty much just stopped paying attention to it. After several days away, it's different. It used to spawn a new chrome instance, with no extensions (adblock and the like) and the breakpoints problem. 

Is it not supposed to spawn a new chrome instance? That's not ideal, but it certainly makes sense, and achieves the goal without requiring extra steps by the user.

Is there a way to do a "clean" uninstall? Are there ancillary files that could be removed when uninstalled? Perhaps that with a reinstall may fix it?

**Comment by roblourens** [comment]
I still don't understand what the problem is. It used to spawn chrome. Now it does... what?

I gave you a couple troubleshooting pointers, please try those.

**Comment by roblourens** [comment]
> it uses an existing instance and opens a new tab.

Got it - it still does this by setting a user-data-dir based on the port. Either you are setting `runtimeExecutable` in your launch config which disables this, or the previous instance is using that user-data-dir, or you've disabled this like by setting `"userDataDir": false`.

If it's the second, setting a different port number (in your launch config) would cause it to use a new user-data-dir.

You can post your launch config here if you're not sure.

**Comment by roblourens** [comment]
That's a node "attach" config, it's not a chrome launch config. Can you post your chrome config?

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
