### ISSUE TITLE
Fix for broken breakpoints when running react in Ubuntu Bash under windows

### ISSUE THREAD

**Issue by SethHamilton** [Microsoft/vscode-chrome-debug#664]
If you are using Bash under windows to run Node, you will not hit your breakpoints in VS Code using the chrome debugger. The issue is that the windows side of things will be given a linux path. 

If you translate the path from a linux path to a windows path your breakpoints will be hit (i.e. `/mnt/e` to `e:\`). To do this simply add a `sourceMapOverrides` entry at the top of the list (in your `launch.json` file):

```
            "sourceMapPathOverrides": {
                "/mnt/e/*": "e:/*"
            },            
```

I know it's not a bug, but googling around for a fix I found others with this exact issue. This is what I came up with and it worked (very satisfying seeing those little gray circles turn red in the code listing).

**Comment by roblourens** [comment]
Yes, this is the fix I would recommend, if the build produces sourcemaps that have the full path like that. It won't work for other setups.

Thanks for the tip!

**Comment by SethHamilton** [comment]
@roblourens it works nicely with variables like `${workspaceRoot}`, not sure how it would work with fully relative paths (however, all my `requires` are relative, and this works).
