### ISSUE TITLE
Enabling smart step doesn't skip over webpack generated code

### ISSUE THREAD

**Issue by RonanQuigley** [Microsoft/vscode-chrome-debug#667]
- VS Code Version: 1.23.1
- Log file (set `"trace": true` in launch config): 
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2004487/vscode-chrome-debug.txt)

When running this module with a webpack setup via attach to chrome, I'm unable to get the debugger to skip uninteresting code even with smartStep enabled. Not only that, after stepping through the webpack internals, the deugger then just stops running:

![bug](https://user-images.githubusercontent.com/33596237/40052158-1688c13c-5835-11e8-8c47-18cc2defeb93.gif)

This is my debug config:

``` 
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "trace": true,
            "smartStep": true,
            "webRoot": "${workspaceFolder}",
            "skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js",
                "<node_internals>/**/*.js",
            ],
        },
```

If I strip it out to just the following the issue is still there:

```
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "trace": true,
            "smartStep": true,
```

Initially I thought that it was my hot reloading setup with webpack-hot-middleware that was causing it, as I did notice it was stepping into a ton of hot module replacement code. But even after removing that plugin from my webpack config it's still doing it. The gif posted above is without that module.

From looking at the log, interestingly it says "Terminated: Got disconnect request" towards the end; why I have no idea.

Here is the webpack config for my front-end if it helps. I've also tried various devtool options for source mapping, both inline and non-inline but it's still the same result

``` 
// merged with the front end dev below
const frontEndCommon = {
    name: 'client',
    target: target,
    output: {
        path: dist,

        // this is a multi-page app; let webpack
        // set the filename through our entry config
        // filename: 'client.js',

        // workaround for a bug with webpack :
        // https://github.com/webpack/webpack/issues/6642
        globalObject: 'this'
    },
    plugins: [new webpack.NamedModulesPlugin()],
    module: {
        rules: [
            {
                exclude: /node_modules|packages/,
                test: /\.js$/,
                use: 'babel-loader'
            },
            {
                sideEffects: false 
            }
        ]
    }
};

// this is a webpack.dev.babel.js file that is used for vscode chrome debugger
const dev = {
    mode: 'development',
    entry: {
        index: ['whatwg-fetch', './src/client/pages/index/'],
        results: ['whatwg-fetch', './src/client/pages/results/']
    },
    devtool: 'source-map',
    plugins: [
        new webpack.EnvironmentPlugin({
            NODE_ENV: process.env.NODE_ENV
        })
    ]
};

```

**Comment by roblourens** [comment]
I think I know what the problem is, can you try adding 

```
"webpack:///webpack/bootstrap",
"webpack\\bootstrap"
```

to your skipFiles entry? (Not sure which one will match.)

**Comment by RonanQuigley** [comment]
Just to add, smartStep does say that it is skipping over the file. Though of course that's not actually the case.

![image](https://user-images.githubusercontent.com/33596237/40107532-67766f0c-58f0-11e8-9be4-121bcb7398c6.png)

**Comment by RonanQuigley** [comment]
@roblourens, just to bump this; have you had a chance to take a look at my response?

**Comment by roblourens** [comment]
Yes I'm able to repro this or something like it - I just need to find time to debug it.

**Comment by RonanQuigley** [comment]
Great thanks. if you need a repo of the issue let me know. If it helps, I think that I have managed to work around some of the issue by utilising the following in my webpack config output option : 

```
devtoolModuleFilenameTemplate(info) {
    return `file:///${info.absoluteResourcePath.replace(
        /\\/g,
        '/'
    )}`;
}
```

**Comment by roblourens** [comment]
I have a fix which seems to cover this, I'll try to get it out in the next week.

**Comment by RonanQuigley** [comment]
Hey, tried out your fix. Seems to have worked, but I have also noticed that if I use say cheap-module-eval-source-map for example I get the following error:

```
Error processing "scopes": TypeError: Line must be greater than or equal to 1, got 0
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (C:\Users\Ronan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\node_modules\source-map\lib\source-map-consumer.js:584:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (C:\Users\Ronan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\node_modules\source-map\lib\source-map-consumer.js:653:22)
    at SourceMap.authoredPositionFor (C:\Users\Ronan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:133:34)
    at SourceMaps.mapToAuthored (C:\Users\Ronan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMaps.js:43:18)
    at BaseSourceMapTransformer.mapScopeLocations (C:\Users\Ronan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:247:44)
    at scopesResponse.scopes.forEach.scope (C:\Users\Ronan\.vscode\extensions\msjsdiag.debugger-for-chrome-4.6.0\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:240:57)
    at Array.forEach (native)
    at BaseSourceMapTransformer.scopesResponse (C:\Users\Ronan\.vscode\extensions\msjsdiag.d[...]
```

However, you can still step around the code okay, though at times the breakpoints jump to the incorrect line. I'm aware that the source-map option is best, but should this at least not be throwing this error?

**Comment by roblourens** [comment]
Could you try setting `"trace": true` in your launch config, and running again?

**Comment by RonanQuigley** [comment]
Actually, the debugging with cheap-module-eval-source-map is completely unusable now, so not sure what's what 😄 

[vscode-chrome-debug.zip](https://github.com/Microsoft/vscode-chrome-debug/files/2089645/vscode-chrome-debug.zip)

**Comment by roblourens** [comment]
Hm, I was thinking, the only way this is possible is if Chrome sent nonsense locations, and sure enough

```json
{
	"type": "closure",
	"object": {
		"type": "object",
		"className": "Object",
		"description": "Object",
		"objectId": "{\"injectedScriptId\":130,\"id\":2}"
	},
	"name": "./src/client/pages/results/index.js",
	"startLocation": {
		"scriptId": "126075",
		"lineNumber": -1,
		"columnNumber": -1
	},
	"endLocation": {
		"scriptId": "126075",
		"lineNumber": -1,
		"columnNumber": -1
	}
}
```

I'm not sure what to do about scopes at invalid locations. I'll open a new issue for it.

The problem with the webpack sourcemap settings is that they tend to vary between different projects or webpack configurations or versions. I just tried cheap-module-eval-source-map in a random webpack project I have and it worked fine. Other people report that nothing works but source-map. So I can't predict what will work for everyone and what won't.

**Comment by RonanQuigley** [comment]
Ah right, that make sense. Even an explanation of that would that elaborates on that issue would be great in the readme though. I for one ended up fiddling around for an hour with the various source map options. If only browsers were more consistent in how they responded to them. 😞 

Out of interest, would it be possible for you to post the config that you used for cheap-module-eval-source-map? Would be great to see why it is not working in my setup (though it was working before).

**Comment by roblourens** [comment]
Sure, it's this project: https://github.com/roblourens/vscode-settings-editor/blob/ejectedWebpack/config/webpack.config.dev.js#L32
