### ISSUE TITLE
Documentation suggestion re: sourcemaps, webpack, babel, react

### ISSUE THREAD

**Issue by DTrejo** [Microsoft/vscode-chrome-debug#669]
## Using Webpack with Babel and want VSCode to step over the original source of your react code?

Try this in your development webpack config:

``` json
devtool:  'eval-source-map',
```

You should be able to set breakpoints, even in jsx, and hit them. VSCode should not tell you "unverified breakpoint."

Cheers and thanks for the extension!!!

**Comment by roblourens** [comment]
I recommend `'source-map'` but thanks for the tip!

**Comment by DTrejo** [comment]
sounds good - i just wasnt sure i saw this recommendation in the docs which is why i made the issue - if it's already there and i missed it, whoops! thanks again!

**Comment by DTrejo** [comment]
Just checked, looks like you don't have this in the main readme that shows in the vscode store page. want a PR to add that (`source-map`)? I bet this is a cause for a lot of the issues you get on here about source map problems

**Comment by roblourens** [comment]
Added a note to the README, thanks

**Comment by DTrejo** [comment]
thank you Rob!
