### ISSUE TITLE
Why is debugging web workers not supported?

### ISSUE THREAD

**Issue by nickytonline** [Microsoft/vscode-chrome-debug#675]
- VS Code Version:Version 1.24.0-insider (1.24.0-insider)
- Log file (set `"trace": true` in launch config): N/A

First off, great project. Thanks so much for this.

So, I'm just curious why web worker debugging is not supported. I can debug them in Chrome directly but not with the VS Code extension.

**Comment by roblourens** [comment]
Just that it would be a lot of work to support and there has been little demand for it. Covered by this issue though: https://github.com/Microsoft/vscode-chrome-debug-core/issues/251

**Comment by nickytonline** [comment]
Cool. Thanks for the info @roblourens.
