### ISSUE TITLE
ReferenceError for local variables in debug console

### ISSUE THREAD

**Issue by nopor** [Microsoft/vscode-chrome-debug#678]
<img width="666" alt="vs-code-chrome-debugger" src="https://user-images.githubusercontent.com/9073633/40908112-146306a4-67e6-11e8-9e2e-6c2fb446bbe8.png">

The site I'm trying to debug in Code is hosted on a local AEM server. The breakpoints get hit and I don't have any issues with the source maps or other global variables in the debug console.
The config should be accessible, if I'm not mistaken. The $ from jQuery, however, is accessible.

Is this the intended behaviour?

- VS Code Version: 1.23.1

**Comment by roblourens** [comment]
Is `config` the actual name of this variable at runtime? Or could it have been renamed by a minifier/transpiler?

**Comment by nopor** [comment]
Okay, never mind.
The chrome debugger console showed what happened.

The problem was, or is, that the breakpoint was not in the correct line (for chrome). The variables haven't been renamed, nor minified or transpiled.
Will try to figure out why chrome isn't in the correct line.

Thank you for your help.
