### ISSUE TITLE
Source files do not map correctly when using MS MVC views

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#68]
Cannot set breakpoints when using MVC views even when the mapped view 
See launch.json
```javascript
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "The Test",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost/test/web/Products",
      "runtimeExecutable": "C:\\Users\\user\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe",
      "runtimeArgs": ["--remote-debugging-port=9222"],
      "webRoot": "C:/src/user/apps/test/Views",
      "sourceMaps": false      
		}
	]
}
```
debugger; command works and you can even edit and save in vscode after it is caught but breakpoints dont work.
request url is
```
Request URL:http://localhost/test/web/Views/products/productsController.js
```
mapped location is
```
C:/src/user/apps/test/Views/products/productsController.js
```

[vscode-chrome-debug.log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/59864/vscode-chrome-debug.log.txt)

**Comment by roblourens** [comment]
I don't see a scriptParsed event from Chrome for productsController.js. Did one come later? Or are you sure it's attached to the right tab in this run?

**Comment by roblourens** [comment]
I don't have enough info as is - feel free to reopen though.

**Comment by justin-romano** [comment]
I couldnt copy all the text. How do i copy the log?

**Comment by justin-romano** [comment]
[console.log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/68260/console.log.txt)

I think i have it all now. How do i reopen this?

**Comment by roblourens** [comment]
Thanks, I'll reopen it. I don't see an obvious issue in this log though - 2 breakpoints were set successfully in productsController.js.

First, Code tries to set the breakpoints, but it's waiting for the scripts to be loaded. Once they are loaded, it sets the breakpoints in Chrome. Then the last lines in the log are Chrome responding that the breakpoints were set correctly.

**Comment by justin-romano** [comment]
Hmm. because it just does not stop.
I figured it was because of ASP redirecting the paths. I thought code it would be missing some interpolation to get to the correct spot mapping the correct place.
If you have visual studio (legacy) installed maybe you can setup a a ASP MVC app to test it. most likely you could repro this with the template MVC project.

**Comment by roblourens** [comment]
I can debug the MVC template project with no issues. I don't think there's anything different about this scenario because of ASP. Are you sure that the line with the breakpoint is being hit? All I know from the log is that Chrome says the breakpoints were set.

**Comment by justin-romano** [comment]
Acually. I downloaded the latest version of code and it now works. Just not
the initial dom load debug connect sequence. So you press run but the break
points don't hit. Press f5 in the browser and they do. Like some timing
issue. Hope the helps

**Comment by roblourens** [comment]
Progress :), can you share the log now, from the beginning to when it pauses after a refresh?

**Comment by roblourens** [comment]
Hey @justin-romano, closing for now but let me know if you can give me the full log.
