### ISSUE TITLE
Synchronize blackbox settings between VS Code and Chrome

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#683]
Chrome DevTools supports blackboxing, it would be great if VS Code could synchronize the settings.

Request from: https://mobile.twitter.com/odahcam_/status/1005124939547136000

API: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBlackboxPatterns

**Comment by roblourens** [comment]
Not sure what you mean by 'synchronize' exactly, I can't overwrite or retrieve the patterns that are set in the chrome devtools UI

**Comment by auchenberg** [comment]
I think what's meant here is to retrieve the patterns already set in Chrome DevTools, but indeed the API doesn't seem to exist for this.
