### ISSUE TITLE
Debugger pause at start 

### ISSUE THREAD

**Issue by Cyrus-d** [Microsoft/vscode-chrome-debug#686]
When setting a breakpoint before starting the debugger, debugger pauses at the beginning of the file called vm82 ‘installGlobalHook(window)’. 

VS Code Version: 1.24.1
Log file: 
[https://gist.github.com/Cyrus-d/4a3dedf369424628d0eb56ca23e0f5ca](https://gist.github.com/Cyrus-d/4a3dedf369424628d0eb56ca23e0f5ca)

Steps to reproduce:
1. Install ‘create-react-app‘
2. Create launch.json file with following content:

```
"version": "0.2.0",
"configurations": [
    {
        "type": "chrome",
        "request": "launch",
        "name": "Launch Chrome against localhost",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceFolder}",
        "trace": true
    }
]

```
3. Set a breakpoint in ‘render’ function of App.js file
4. start the app from terminal 'npm start'
5. start the debugger

the debugger will pause at the file location mentioned earlier.

thanks

**Comment by roblourens** [comment]
This is from 'break on load'. The first pause event has

`"reason":"ambiguous","data":{"reasons":[{"reason":"EventListener","auxData":{"eventName":"instrumentation:scriptFirstStatement"}},{"reason":"EventListener","auxData":{"eventName":"instrumentation:scriptFirstStatement"}}]}`

I don't know why that would happen but I'll work around it. FYI @digeff @rakatyal.
