### ISSUE TITLE
Need guidance, have something working but quite suboptimal

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vscode-chrome-debug#69]
First off, thanks for this extension - I've been waiting for in-browser debugging for 6 months or so!

That said, the configuration is rather difficult to get right, though it was the same for debugging in Chrome at the time (not very well documented).

I have a TypeScript "app"/SPA, here's what works: my repo (simplified) looks like this
```
/ts/<hierarchy_of_folders_and_ts_files>
/less/<less_files>
/html/<html_file>
./<various_files>
/testbed/<built_files>
```

The idea is that while developing, Visual Studio Code ignores the contents of `/testbed` and looks only at the contents of `/ts/**`, `tsconfig.json` is configured properly and generally everything works great.

There is a `gulpfile.js` (at the root) which orchestrates building all these files into final output which resides in `testbed/**` and this is what is served (many people seem to call this folder `out`).

When I build sourcemaps, the only way to make things work _in Chrome_ (so ignoring for the time being this extension) was to copy all TypeScript sources into the `testbed` and set `sourceRoot` (in gulp sourcemaps plugin) to `./ts/`. In the final map file the TS sources are having paths like `ts/<correct__relative_path>`. Then I can debug normally in Chrome, set breakpoints etc. Everything works like charm. Apparently, the TS paths (as set in map file) correspond to web server paths, so the files need to served by the HTTP server.

As mere existence of this plugin shows :smile: , it's better to have debugger integrated with the editor so I started tinkering with settings trying to get debugging to work in VS Code too.

The only way I've managed to make it work (while keeping existing setup) was with the following setup (complete `launch.json` reproduced):

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "sourceMaps": true,
            "port": 9222,
            "webRoot": "<absolute_path_to_testbed_folder>,
            "diagnosticLogging": true
        }
    ]
}
```

This works fine **but** I need to open the files copied to the `testbed/ts` (these are the ones served by the HTTP server, I have a small node server locally running serving the files) in order to set breakpoints, which is not what VS Code is normally using (again, I'm actually ignoring this folder because the source I edit is not there, I only copy sources there to satisfy the needs of tooling).

The breakpoints are hit, I can see call stack, inspect variables - it's great.

Except... I see a lot of squigglies in VS Code because the whole setup is made with `/ts/**` in mind, not `testbed/ts/**` (in other words, I'm fighting my own setup).

Theoretically, I should be able to "work around" this by having actual source files served by the HTTP server, but they are "up" from the `testbed` folder so don't share the same (local filesystem) root (yeah, making a symbolic link/junction between the two `ts` folders will work, but it's silly-ish).

I tried setting `sourceRoot` (for gulp sourcemaps plugin) to absolute local path (including backslashes since on Windows), this does not seem to work. If it should, what should be put in the `webRoot` in `launch.json`? Though I don't like using absolute paths because people on other machines (especially non-Windows) won't have the same setup.

I guess this is a long-winded intro to the question: what is the preferred way to handle this setup? Is there a way for debugging to work which does **not** involve having to actually serve TS files by the Web server (because this aspect seems to complicate things the most)?

I'm looking for some guidance on how to do this, from some other issues in this repo I can guesstimate this to be relatively frequent setup, but I cannot figure out from the discussions in these other issues what was the solution.

Thanks in advance for any suggestion or pointer.

**Comment by roblourens** [comment]
If I understand correctly, you have a setup for Chrome that involves copying the TS files from the actual source location to somewhere served by the webserver, so CDT can find them. I don't know of any way around that - the sourcemap file gives an absolute or relative path to the source file, and Chrome will resolve this to a URL and download it.

You're right that setting `sourceRoot` to an absolute path should work for the extension. It may work for Chrome if the path is right for that machine, but I'm not sure. Setting the entries in `files` to absolute paths (that start with file:///) is probably a slightly better tested scenario because of webpack, if you can get gulp to do that. `webRoot` should always be the path to the webserver's root, but it wouldn't actually be used for sourcemaps if it has an absolute path for the source file.

If you can't move your sources to be under webRoot, maybe you could configure your webserver to serve a different path for "/ts" requests? That's about as hacky as using a symlink though. Sorry I don't have a better answer! I assume most people using sourcemaps in CDT either output absolute paths, or serve up their sources.

**Comment by ddotlic** [comment]
Yeah, you got it all right.

You've just confirmed my assumption that the best course of action (not counting absolute paths for `sourceRoot` which for some reason doesn't even work for me) would be to simply (web) serve the sources such that they're accessible without copying them around in the filesystem (which again I do only to satisfy tooling so it's not a hard requirement). Since I'm serving files myself with a tiny node based HTTP server, this should be doable (I haven't authored the server personally but no matter).

Thanks for your input and thanks for this plugin, IMHO it's literally the most important plugin a Web developer needs when using Code, seeing how most other needs are already nicely filled by the Code without plugins.

Cheers!
