### ISSUE TITLE
Debugger pauses without a breakpoint

### ISSUE THREAD

**Issue by tzachshabtay** [Microsoft/vscode-chrome-debug#690]
- VS Code Version: 1.24.1
- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2133461/vscode-chrome-debug.txt)

Steps to reproduce:

I don't know how to reproduce this. I just upgraded the extension in the hope of resolving the "installGlobalHook" bug (https://github.com/Microsoft/vscode-chrome-debug/issues/686), and it really doesn't pause in that line anymore, but now it started to pause on a new function I wrote in my typescript file (the function is called "onMenuButtonClicked", you can see it in the log file). I.e I just wrote that new function, compiled and ran without setting any breakpoint there and it now pauses the debugger every time I click on the menu button (I tried restarting vs code but it doesn't help).

**Comment by roblourens** [comment]
The log shows that you have a breakpoint there in grid_toolbar.tsx, are you sure you don't have a breakpoint set?

**Comment by tzachshabtay** [comment]
Yes, I'm sure, it's completely new code and doesn't have a breakpoint set there (I haven't even clicked on "Inspect" on chrome to open the dev tools). Just to make sure, I've now opened the dev tools to verify that there's no breakpoint there (but it still pauses).

**Comment by roblourens** [comment]
Hm, and the log says the breakpoint is in vscode, not devtools or anywhere else.

grid_toolbar.tsx, line 186. Can you check the breakpoints view of the debug viewlet just to make sure? In case it's not showing up on the editor margin for some reason. Or maybe add and remove a bp on that line.

![image](https://user-images.githubusercontent.com/323878/41864843-1e5261f2-7860-11e8-8460-b82ad1fa5c84.png)

**Comment by tzachshabtay** [comment]
Huh, that's odd. Yeah, there's a breakpoint in the breakpoint viewlet but I don't see it in the actual file editor:

![breakpint](https://user-images.githubusercontent.com/1819001/41865458-218a0c7e-787b-11e8-88aa-fd9fe83c5a01.jpg)

So I guess it's a bug in vscode?
I also see that when I place a breakpoint in the area in the file where the new lines were written it sets the breakpoint on the lines after that area (i.e if I place a breakpoint in line 184 it will place the breakpoint in line 190).

I removed the breakpoint and it doesn't pause now (and I can't reproduce that now).

On a side note, this is the first time a breakpoint on vscode actually pauses the client, I'm used to just setting breakpoints on dev tools because it didn't work, so I'm pleasantly surprised it works now, was there a recent fix?

**Comment by roblourens** [comment]
It looks like the breakpoint is in a copy of the file from your debugger, which would happen if there's some issue with your project's sourcemaps that prevent the sources from being resolved correctly to files on disk. That would be why

> this is the first time a breakpoint on vscode actually pauses the client

You can use the `.scripts` command to see how sources are being resolved or if you can share the project I can try to straighten it out.

**Comment by tzachshabtay** [comment]
Ah, got it, thanks, fixed the sourcemap path, so I'll close this now.
