### ISSUE TITLE
Reducing the friction of using attach

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode-chrome-debug#691]
I prefer attaching over launching because, this way:

- I can benefit from the extensions (e.g. React dev tools) and state (e.g. cookies) of my default Chrome user profile.
- I can immediately inspect a tab I have in my open browser, without having to launch a new instance of Chrome, navigate to the same page, and recreate any page state. (Like how you can immediately open Chrome dev tools.)

However, attaching is currently not as convenient as I would like it to be. This is because, by default, Chrome doesn't launch with remote debugging enabled.

How can we reduce the friction of using attach? Some ideas:

- Use a replacement application shortcut for opening Chrome *with remote debugging enabled*. Users would use this instead of the default shortcut. The debugger docs would mention how to set this up.
- Find a way to permanently enable remote debugging, e.g. via some global configuration for Chrome. Perhaps we could file an issue for this with Chrome in the appropriate place?

Perhaps there are other solutions I'm not aware of? I've read the docs and searched the issues, to no avail. Surely I'm not the only person who wants this?

**Comment by roblourens** [comment]
You can use your user profile with "launch" if you want by setting `"userDataDir": false`. It won't work unless you close all open instances of Chrome first which is why we use a fresh one by default.

Your first suggestion would still have the downside of requiring users to open a new browser, recreate the page state etc, right? The second is unsafe, it's probably not a good idea to use Chrome in debug mode all of the time.

We also have the idea of debugging the page via a Chrome extension, instead of with the app debugging switch. I can't find the original issue @auchenberg but we have https://github.com/Microsoft/vscode-chrome-debug/issues/412

**Comment by OliverJAsh** [comment]
> Your first suggestion would still have the downside of requiring users to open a new browser, recreate the page state etc, right?

My thinking was that this shortcut would replace the main application shortcut, so each time the user wanted to open Chrome (for browsing, not specifically for debugging), they would use the shortcut that enables remote debugging.

> The second is unsafe, it's probably not a good idea to use Chrome in debug mode all of the time.

Good point. But from a user's perspective, I can open Chrome dev tools without any ceremony, and I would like to do the same with other debugging tools.

> We also have the idea of debugging the page via a Chrome extension, instead of with the app debugging switch.

How would an extension get around the requirement that remote debugging must be enabled? 🤔

**Comment by roblourens** [comment]
I haven't looked at it for a long time, but from what I remember, debugging is exposed through the chrome extension APIs too. So an extension could run its own  websocket server and pipe the debug commands into Chrome through those APIs.

**Comment by auchenberg** [comment]
@OliverJAsh Please see this original proposal, https://github.com/Microsoft/vscode-chrome-debug/issues/92, and https://github.com/Microsoft/vscode-chrome-debug/issues/388

In general I agree that it would be wonderful to have a mechanism to enable remote debugging for running Chrome instances, but this isn't possible unless we get an API from the Chrome team.

We have proposed a similar mechanism that Node is using but this was rejected: https://bugs.chromium.org/p/chromium/issues/detail?id=649823

**Comment by OliverJAsh** [comment]
Thanks for getting back to me! The Chrome extension sounds like the best way forward with the tools available to us today. Was it decided that this was out of scope for this project? Could this be developed by the community, or does it require work inside of vscode-chrome-debug?

**Comment by auchenberg** [comment]
@OliverJAsh This would require work in `vscode-chrome-debug` and in a new chrome extension. The best way forward could be a contribution that implements https://github.com/RemoteDebug/remotedebug-chrome-devmode
