### ISSUE TITLE
Unverified breakpoint, Breakpoints set but not yet bound (Windows, Typescript)

### ISSUE THREAD

**Issue by ingbabic** [Microsoft/vscode-chrome-debug#692]
VS Code Version:
Version 1.24.1
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS: Windows
Language: Typescript

Steps to reproduce:

1. Set breakpoint
2. Start debugging
3. Break point is not hit (red circle becomes empty, on hover you get a message as in title)

**Comment by roblourens** [comment]
Please see the readme for debugging tips
