### ISSUE TITLE
Improve documentation about webpack devtool option.

### ISSUE THREAD

**Issue by tchaffee** [Microsoft/vscode-chrome-debug#693]
- VS Code Version: N/A
- Log file (set `"trace": true` in launch config):
N/A

Steps to reproduce:

None - documentation improvement.

I spent way too much time trying to change my `launch.json` file to use the `"devtool": "source-map"` option based on the following docs:

> If you're using Webpack, we recommend using the `"devtool": "source-map"` option as the others produce lower-fidelity sourcemaps and you may have issues setting breakpoints.

Perhaps it should have been obvious to change it in my webpack config, but I'm new to webpack. I suggest the following improvement to the docs:

> If you're using Webpack, we recommend using the `"devtool": "source-map"` option (in your `webpack.config.js` file) as the others produce lower-fidelity sourcemaps and you may have issues setting breakpoints. You can also use `"devtool": "eval-source-map"`. See the [full list of devtool options for webpack](https://webpack.js.org/configuration/devtool/) for more information.

**Comment by tchaffee** [comment]
Happy to submit a PR for this.

**Comment by roblourens** [comment]
I would take a PR, without the part about `eval-source-map`. It probably works in most cases but sourcemaps for eval code is still more likely to have issues than just with `source-map`.

**Comment by tchaffee** [comment]
Done. https://github.com/Microsoft/vscode-chrome-debug/pull/694

**Comment by roblourens** [comment]
Thanks
