### ISSUE TITLE
Feature request: Chrome coverage tool integration

### ISSUE THREAD

**Issue by walrus95** [Microsoft/vscode-chrome-debug#695]
I’d like an integration between the “coverage” tool in the Chrome developer tools and Visual Studio Code. I’m developing an Angular application, and I would like to see highlighted in Visual Studio Code the lines of code which have been executed by the running instance of Chrome. I would also like to see highlighted the files in the sidebar which contain lines that have been executed in Visual Studio Code, similar to how files are highlighted when using the Git integration.

Thank you.

https://github.com/Microsoft/vscode/issues/53351

**Comment by roblourens** [comment]
That would be cool. I think this is part of the Profiler domain in the devtools protocol: https://chromedevtools.github.io/devtools-protocol/tot/Profiler

**Comment by auchenberg** [comment]
This would be a great candidate for a separate extension, that could either leverage this Chrome debugger for the connection, or use https://github.com/GoogleChrome/puppeteer to run in a headless browser.

Prior work on Type Profiling has been done https://gist.github.com/kdzwinel/5b27649ec5829121e628b79c276a1e52

@TheLarkInn
