### ISSUE TITLE
Unable to debug angular application based on angular cli 1.7.4 using angular chrome extension

### ISSUE THREAD

**Issue by AkashKarve241191** [Microsoft/vscode-chrome-debug#697]
I am not able to debug my angular 5 app with angular cli 1.7.4 and always gives error breakpoint set but not yet bound.
Following is my  launch.json file configuration
{
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:50155",
            "webRoot": "${workspaceFolder}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                // "webpack:///./*": "${webRoot}/*",
                // "webpack:///src/*": "${webRoot}/*",
                // "webpack:///*": "*",
                // "webpack:///./~/*": "${webRoot}/node_modules/*",
                // "meteor://💻app/*": "${webRoot}/*",
                "ng:///./*": "${webRoot}/*",
            }
thanks in advance.

**Comment by roblourens** [comment]
Are you sure you need that `sourceMapPathOverrides` setting? have you tried without it?

**Comment by AkashKarve241191** [comment]
Yes i tried without it also but no success.
Debugging is possible when i create application from scratch and has
standard folder structure.
My application has different folder structure so in my case its not working.
Is there any configuration we need to change for mapping folder structure?
Thanks in advance.

**Comment by roblourens** [comment]
See the notes about `.scripts` and `sourceMapPathOverrides` in the readme to help figure out whether your sourcemaps don't have the correct paths.
