### ISSUE TITLE
"Unverified breakpoint, Breakpoints set but not yet bound" VS 1.24.1 simple app

### ISSUE THREAD

**Issue by TimGab** [Microsoft/vscode-chrome-debug#698]
- VS Code Version: 1.24.1
- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2177097/vscode-chrome-debug.txt)

Steps to reproduce:

1. Create app.js
```
`var express = require('express');

var app = express();

app.get('/', function(req, res) {
    res.redirect('/login');
});
  
app.get('/login', function(req, res) {
    console.log(req.cookies);
    console.log("hi");

    res.cookie('acookie', 'this is a cookie');
  
    res.send('\
    <head>\
        <title>test</title>\
    </head>\
    <body>\
        <a href="/auth">Login</a>\
    </body>\
    ');
});

app.get('/auth', function(req, res) {
    console.log("damn");
    res.send('\
    <head>\
        <title>test</title>\
    </head>\
    <body>\
        <a href="/auth">RECURSION</a>\
    </body>\
    ');
});

app.listen(8081);
console.log('listening on 8081');`
```
2. Configure launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:8081",
            "webRoot": "${workspaceFolder}",
            "trace": true
        }

    ]
}
```
3. Set some breakpoints (I set them for app.get login and app.get auth)
4. Run app.js by using F5 in VS Code
5. The first breakpoint (at /login) should have already triggered. But they both become grey circles displaying "Unverified breakpoint, Breakpoints set but not yet bound"
![image](https://user-images.githubusercontent.com/40239252/42463626-9972d5e4-839e-11e8-97b6-04f05e329b0e.png)

.scripts is not helping ;/
![image](https://user-images.githubusercontent.com/40239252/42463297-9ee8eb72-839d-11e8-8d06-657ad08d4e0e.png)

Help would be much appreciated!

**Comment by roblourens** [comment]
`.scripts` is helping because it shows that your scripts are not loaded :)

Are you trying to debug the server or the client? It looks like your breakpoints are set in server code. This extension is for debugging code running in Chrome. You may want a "node" debug config.

**Comment by TimGab** [comment]
Yes this is the server code. Thanks for the quick help!
I used a node debugger and that worked. That's all I need.

While I am currently  not using this, I am interested in it:
Is there any kind of guide on how to use your plugin for the following case? I am creating html files in my node server and serving them to the clients. How would I now use your plugin to debug user activities on these pages? Simply adding the config in launch.json did not work.

**Comment by roblourens** [comment]
The readme should cover everything you need.
