### ISSUE TITLE
Third Party Extensions are not working

### ISSUE THREAD

**Issue by Jonatthu** [Microsoft/vscode-chrome-debug#705]
Trying to make work Redux DevTools

With this config

```
{
"name": "ng serve",
"type": "chrome",
"request": "launch",
"url": "http://localhost:4200/#",
"webRoot": "${workspaceFolder}",
},
```

It show the extension icon but is not working, on normal chrome works fine.
Same for other extensions as Augury.

**Comment by roblourens** [comment]
We don't support chrome devtools extensions.
