### ISSUE TITLE
ERR_CONNECTION_REFUSED for debug in url

### ISSUE THREAD

**Issue by tajenli** [Microsoft/vscode-chrome-debug#708]
- VS Code Version:

> Version: 1.25.1
> Commit: 1dfc5e557209371715f655691b1235b6b26a06be
> Date: 2018-07-11T15:43:53.668Z
> Electron: 1.7.12
> Chrome: 58.0.3029.110
> Node.js: 7.9.0
> V8: 5.8.283.38
> Architecture: x64

- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2229306/vscode-chrome-debug.txt)

- launch.json
```
        {
            "name": "Debug in Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000/",
            "webRoot": "${workspaceFolder}/test/VSCode",
            "trace": true,
        },
        {
            "name": "Launch index.html",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceFolder}/test/VSCode/index.html"
        },
```

Steps to reproduce:
1. Run debug "Debug in Chrome"
2. Got error message:

> This site can’t be reached
> localhost refused to connect.
> ERR_CONNECTION_REFUSED

- More about the error:
    - Debug "Launch index.html" (file://...) works fine.
    - I also install PHP Server extension, which is also running on localhost:3000, works fine.

**Comment by roblourens** [comment]
Is there a server on port 3000? You have to run your own server.

**Comment by tajenli** [comment]
Do you mean adding "Listen 3000" in httpd.conf for Apache?

If I do so. Every time I run "Debug in Chrome" will go to the root of my Apache, not the webRoot I set up in launch.json. I can manually type in the path, then all debug work. But this is quite annoying.

I thought the webRoot and the port are supposed to be bound at runtime?

**Comment by tajenli** [comment]
Oh~ not sure about "set up your own server"?
Can you provide a link I can follow?

**Comment by roblourens** [comment]
It sounds like you have Apache already. However you would normally start a local server on port 3000, just do that.

**Comment by tajenli** [comment]
I usually just add Listen 3000 in httpd.conf. But that's not 100% working as I mentioned above.

**Comment by roblourens** [comment]
I don't understand what you're asking. You can use whatever port you want. But you have to start Apache or some other server yourself.

**Comment by tajenli** [comment]
Yes, that's my question. I have all settings and server running in place. Then I got this error...

**Comment by tajenli** [comment]
Ya, my server is up and running all the time. I am using localhost for development every day. 

It's the issue between this extension and my server. They just can not connect with each other.

If I have Listen 3000 in httpd.conf. Then yes, the localhost:3000 will run. but it doesn't work with Debugger with Chrome. I thought the port 3000 supposed to be free if I am running the debugging?

I have the other extension called "PHP Server". It uses port 3000 too, and it works without any issue. I stop it then run Debugger for Chrome. It still not working. So I really don't know what's going on with the issue.

**Comment by roblourens** [comment]
This extension doesn't connect with your server, it just opens Chrome to the url. There is nothing special that happens. So if your local server can normally load in Chrome, then this should work. Are you sure your server is running when you start the debugger?

**Comment by tajenli** [comment]
Yes, my local server is running all the time. I was doing PHP XDebug as well. But just this extension doesn't work. Any suggestion I can try to fix the issue?

**Comment by roblourens** [comment]
The extension only opens Chrome, I can't tell you why Chrome won't load your webpage.

**Comment by tajenli** [comment]
I see. Thank you for your time anyway.
