### ISSUE TITLE
Debug popup or dialog with Electron

### ISSUE THREAD

**Issue by pp611** [Microsoft/vscode-chrome-debug#709]
- VS Code Version: 1.25.1

I tried to debug the Gary Simon Electron tutorial code on youtube. I can set breakpoint on the main process and the renderer with `index.js`, but could not break with `add.js` referenced by `add.html` of the popup window.

The popup window was produced by

``` javascript
notifyBtn.addEventListener('click', function(event) {
    const modalPath = path.join('file://', __dirname, 'src/add.html')
    let win = new BrowserWindow({width: 400, height: 200,  frame: false, transparent: true, alwaysOnTop: true})
    win.on('close', function() { win = null})
    win.loadURL(modalPath)
    win.show()
})
```

The method in `add.js` was called for sure,  but the console log message in that method was not on VSCode's DEBUG CONSOLE. So I guess the popup window was running in a separate process which was not attached. Is this understanding right?

How should popup or dialog be debugged in general? Would `dialog.showOpenDialog()` open dialog in the same process thus attached and debuggable?

The content of `launch.json` file:

``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron: Main",
      "protocol": "inspector",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "runtimeArgs": [
        "--remote-debugging-port=9223",
        "."
      ],
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
      }
    },
    {
      "name": "Electron: Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "webRoot": "${workspaceFolder}",
      "timeout": 30000
    },
  ],
  "compounds": [
    {
    "name": "Electron: All",
    "configurations": [
      "Electron: Main",
      "Electron: Renderer"
    ]
  }]
}
```

**Comment by roblourens** [comment]
You are right that it's running in a separate process that you need to attach to.

Try this - make a copy of your Attach config with a new name (since you can only run one instance of a config) and after the second window is opened, run that new config. It should find the new window and attach to it.

If that doesn't work for some reason you might try to help it narrow down which window to find with `"urlFilter": "*add.html*"`.

**Comment by pp611** [comment]
Get it work. Thanks much for the quick reply, roblourens.

With `urlFilter": "*add.html*"`, the process is attached and breakpoints works as expected. Without `urlFilter": "*add.html*"`, VSCode would pop up which window to attached to, which would make adding the new config unnecessary if launch the `Electron: Renderer` config after the popup is shown.
