### ISSUE TITLE
Is it possible to open chrome debug in new tab of vscode itself?

### ISSUE THREAD

**Issue by VladislavAnkudinov** [Microsoft/vscode-chrome-debug#710]
I have issue similar to https://github.com/Microsoft/vscode-chrome-debug/issues/595 but slightly different.
Is it possible to open chrome debug in new tab of vscode itself, not browser? It will be very useful and reduce context switching greatly! For example one could split vscode window and have sources at the left side and chrome at the right. Its possible to do so resizing windows but its hustle, and If you need to check out some tutorials at usual browser its actually become a nightmare. Just having chrome debug at vscode tab will save a lot of time and bring a lot of joy!

**Comment by roblourens** [comment]
That would be cool but it's not likely to happen unfortunately.
