### ISSUE TITLE
Request: possibility to view network tab of native chrome debugger

### ISSUE THREAD

**Issue by bc3** [Microsoft/vscode-chrome-debug#714]
First of all this is a very cool plugin, makes debugging better and faster, i only miss one thing compared to debugging with the inline chrome devtools, and that is the network tab, are there plans to integrate this also into VS Code ? Or is it already possbile or do i need another extension ? I did'nt find it in the readme

I know there are tools like fiddler etc to do this, but i would really like the network tab from the inline debugger

THX

**Comment by roblourens** [comment]
No, there's no plan to do that. But you can debug in vscode and still open chrome devtools at the same time to use their network tools :)

**Comment by bc3** [comment]
Are you sure, when i try this, I get this exception in VS code when attaching the debugger

![vscodechromedebug](https://user-images.githubusercontent.com/2547576/43581060-ddbf8384-9657-11e8-945d-c7d5c5921d8f.PNG)

**Comment by roblourens** [comment]
It might only work if vscode is attached first. Otherwise make sure Chrome is up to update.
