### ISSUE TITLE
Different "this" reference between devtools (chrome) and debugger for chrome

### ISSUE THREAD

**Issue by leorolland** [Microsoft/vscode-chrome-debug#716]
Hi, this is my first time opening an issue so maybe I'm not doing the things right..

- VS Code Version: 1.25.1
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Attach a Subscription to an observable (rxjs, angular) 
2. Debug the variable "**this**" in both chrome and vscode
3. See different object types : 

- Chrome sees the object that called the observable. (Here my component
![devtools](https://user-images.githubusercontent.com/7632179/43570244-2152028e-963a-11e8-8503-0ad9b922cd41.PNG)

- VScode sees the object the instance of the subscription (SafeSubscriber) 
![vscode](https://user-images.githubusercontent.com/7632179/43570243-2132bb72-963a-11e8-8708-816f59935783.PNG)

this my code : 

```
this._alertesApiService.findAlert(this.editIdAlerte).subscribe(data => {
          // Got data from response.
          let dtoAlert = data.json();
          const alertData = ApiAlerteData.to(dtoAlert, this.editIdAlerte);
          // alertData.mapToObject(this.editIdAlerte);

          this.modelId = this.editIdAlerte;

          // Update fleets/vehicles.
          // this.onReceiveFleets(data[1], {fleets: alertData.fleets, vehicles: alertData.vehicles});
          // Initialize fleets propositions.
          this.loadFleets({fleets: [alertData.fleet], vehicles: alertData.vehicles})

          { // Finish form fill.
            console.log(this)
            this.form.patchValue(alertData);
            this.form.updateValueAndValidity();

            // Show the trigger inputs.
            this.onSetType(this.data.type);

            this.loading = false;
          }
        });
```

**Comment by roblourens** [comment]
vscode evaluates the name when you hover it, so vscode's `this` is whatever it is at that line at runtime, but that isn't necessarily `this` in your source. Most likely that code is being transpiled and `this` has been renamed. Chrome devtools is able to find that information in the sourcemap. vscode doesn't do that yet. https://github.com/Microsoft/vscode/issues/12066
