### ISSUE TITLE
Breakpoints added on VS Code do not fire

### ISSUE THREAD

**Issue by PhotoPaul** [Microsoft/vscode-chrome-debug#72]
Breakpoints added on VS Code, fail to be added on Chrome and as a result they do not fire.

The log simply says:
`    ›From client: setBreakpoints({"source":{"path":"c:\\Users\\******\\Documents\\www\\******\\library-new\\main.js"},"lines":[26]})`
`    ›SourceMaps.setBP: c:\Users\******\Documents\www\******\library-new\main.js can't be resolved to a loaded script.`

It appears to be a Windows-only issue.

**Comment by roblourens** [comment]
Does it work without sourcemaps enabled? Did the same config work before? Can you share the full log or any other info? Otherwise all I can say is, works for me :)

**Comment by PhotoPaul** [comment]
**Here is my launch.json file:**
`{`
`    "version": "0.1.0",`
`    "configurations": [`
`        {`
`            "name": "Launch on Chrome",`
`            "type": "chrome",`
`            "request": "launch",`
`            "url": "http://localhost/******/library-new/",`
`            "webRoot": "C:\\users\\******\\www\\******\\library-new\\",`
`            "sourceMaps": true,`
`            "diagnosticLogging": true`
`        }`
`    ]`
`}`

**And here is the log:**
`›OS: win32 ia32`
`›Node version: v4.1.1`
`›Adapter version: 0.2.0`
`›initialize({"adapterID":"chrome","linesStartAt1":true,"pathFormat":"path"})`
`›launch({"name":"Launch on Chrome","type":"chrome","request":"launch","url":"http://localhost/******/library-new/","webRoot":"C:/users/******/www/******/library-new/","sourceMaps":false,"diagnosticLogging":true,"outDir":null,"address":"localhost","program":null,"stopOnEntry":false,"args":null,"cwd":"c:\\Users\\******\\Documents\\www\\******\\library-new","runtimeExecutable":null,"runtimeArgs":null})`
`›spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost/******/library-new/"])`
`›Attempting to attach on port 9222`
`›To target: {"id":1,"method":"Debugger.enable"}`
`›To target: {"id":2,"method":"Console.enable"}`
`›From target: {"id":2,"result":{}}`
`›To client: {"seq":0,"type":"event","event":"initialized"}`
`›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}`
`›From client: setBreakpoints({"source":{"path":"c:\\Users\\******\\Documents\\www\\******\\library-new\\main.js"},"lines":[26,3]})`
`›Paths.setBP: No target url cached for client path: c:\Users\******\Documents\www\******\library-new\main.js, waiting for target script to be loaded.`
`›From client: setExceptionBreakpoints({"filters":["all"]})`
`›To target: {"id":3,"method":"Debugger.setPauseOnExceptions","params":{"state":"all"}}`
`›From target: {"id":3,"result":{}}`
`›To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}`

**Please note that the only difference on the log depending on wheather sourceMaps is true or false, is this line:**
`›Paths.setBP: No target url cached for client path: c:\Users\******\Documents\www\******\library-new\main.js, waiting for target script to be loaded.`
which becomes:
`›SourceMaps.setBP: c:\Users\******\Documents\www\******\library-new\main.js can't be resolved to a loaded script.`

**Comment by roblourens** [comment]
Is that the whole log? There are no 'scriptParsed' events from Chrome, so that would imply that the scripts are not being loaded.

**Comment by PhotoPaul** [comment]
Sorry I didn't include the whole log. Here are the lines in question (I didn't include everything that had to do with Chrome extensions):

`›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"96","url":"http://localhost/******/library-new/main.js?v=3830","startLine":0,"startColumn":0,"endLine":596,"endColumn":7405,"sourceMapURL":""}}`
`›Paths.scriptParsed: could not resolve http://localhost/******/library-new/main.js?v=3830 to a file in the workspace. webRoot: C:\users\******\www\******\library-new\`
`›From target: {"id":1,"result":{}}`

**Comment by roblourens** [comment]
Could you try setting `"webRoot": "C:\users\******\www"`? webRoot should be the path that files are served from, and judging from the script url, it should be that directory.

**Comment by PhotoPaul** [comment]
I changed webRoot into this:
`"webRoot": "C:\\users\\******\\www\\"`

But I'm still getting the following warning:
`›Paths.scriptParsed: could not resolve http://localhost/******/library-new/main.js?v=23023 to a file in the workspace. webRoot: C:\users\******\www\`

My project is under:
`C:\users\******\www\******\library-new\`

This file exists:
`C:\users\******\www\******\library-new\main.js`

The same file is perfectly accessible here:
`http://localhost/******/library-new/main.js?v=23023`

Still no luck.

**Comment by PhotoPaul** [comment]
I created a new empty project on a simpler path (1 level deep). The .scriptParsed method now seems to work:
`›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"91","url":"http://localhost/test/test.js?v=28302","startLine":0,"startColumn":0,"endLine":7,"endColumn":1,"sourceMapURL":""}}`
`›Paths.scriptParsed: resolved http://localhost/test/test.js?v=28302 to c:\users\***\Documents\www\test\test.js. webRoot: C:\users\***\Documents\www\`

However I'm not done yet since the breakpoints still don't fire **unless** I invoke the lines from VS Code's debugger console.

If for example, if I have a function like this:
`function addInt(a,b){`
`return a + b;`
`}`

and my page has a button like this:
`<input type="button" value="Add" onclick="addInt(4,6)">`

If I go to VS Code's debugger console and I type: `addInt(4,6)` the breakpoint **fires**. But if I click on my button on Chrome, the breakpoint **doesn't** fire.

ps. The breakpoint also **doesn't** fire if I type `addInt(4,6)` on Chrome's developer tools console, but I can live with that.

**Comment by roblourens** [comment]
> If I go to VS Code's debugger console and I type:  addInt(4,6)  the breakpoint fires. But if I click on my button on Chrome, the breakpoint doesn't fire.

Is it possible that you're attached to the wrong tab? There is no difference from this extension's perspective between those 2 scenarios - either Chrome pauses, or it doesn't.

> ps. The breakpoint also doesn't fire if I type  addInt(4,6)  on Chrome's developer tools console, but I can live with that.

Then something weird is definitely going on. If Chrome doesn't hit a breakpoint, this extension isn't going to hit that breakpoint.

**Comment by roblourens** [comment]
Hey @PhotoPaul, sorry but I have no clue what's going on. Let me know if you have more info.
