### ISSUE TITLE
Replace files in Website loded from a server 

### ISSUE THREAD

**Issue by elberfeld** [Microsoft/vscode-chrome-debug#721]
Is it possible to replace a file, for example a javascript file, for a website which is loading from a website whith a local file ? 
By simply using the debugger the source file which is loded inside chrome is still the server version. 
Even if the .scripts command shows the file is correctly mapped with a local file.

# Example:
The website is https://example.org and using the Script https://example.org/somescript.js 
I want to load this page in the debugger, but the file https://example.org/somescript.js should be replace by a version in my workspace folder.

# Use case:
The Application cannot be started on the local machine, it can be only run on specific servers.
The developer has no possibility to replace the file on the Server directly due to access limitations.  

This is simiar to the autoresponder Function of the tool fiddler but i would like to avoid using fiddler as an additional tool and stremline the workflow for the affected developers.

**Comment by roblourens** [comment]
The debugger can't do this. It only attaches to a browser which loads files by its own rules. The debugger can't control which files are loaded. Fiddler is probably the right tool to use for this.
