### ISSUE TITLE
No longer able to launch chrome via F5

### ISSUE THREAD

**Issue by vwzhang** [Microsoft/vscode-chrome-debug#722]
I have been using this extension happily for a long time until last week that my office upgraded Office 2007 to 365. I am no long able to launch chrome against local server. The error message is popped after 10 sec say: ECONNREFUSED port: 9222. I reinstalled the latest Code, this Extension. and checked no other application listen at 9222 and local firewall is off. I am pretty sure the problem just as the error message said but cannot figure out the reason. Please help.

**Comment by roblourens** [comment]
There are some notes on that error in the readme, please check them for troubleshooting tips.
