### ISSUE TITLE
Issues with breakpoints in minified code

### ISSUE THREAD

**Issue by qiulang** [Microsoft/vscode-chrome-debug#723]
- VS Code Version: 1.26.1 (1.26.1)
- vscode-chrome-debug : 4.9.0

The debugger just can't stop at the line I set.
It used to work so I had thought was it because I upgraded to the latest webpack 4.17 ? Then I found out it was not because when I set breakpoint directly in chrome it works.

My babel setting (6.26.3) and webpack setting is quite simple:

```
.babelrc
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 3 Chrome versions","last 2 Firefox versions"]
      }
    }]
  ]
}
```

```
webpack.config.js
module.exports = {
    entry: './src/ui/index.js',
    output:{
        path: path.resolve(__dirname, './dist'),
        filename: 'bundle.js'
    },
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader"  //"babel-loader": "^7.1.5",
          }
        },
... the other usual stuff
```

**Comment by qiulang** [comment]
They bind to the wrong lines near my breakpoints, but it is not clear which lines they bind to.   
I pasted some pictures here to make my point more clear. So here I set 2 breakpoints to debug my eventListener callback

<img width="1401" alt="window_and_index_js_ _jssipwrap" src="https://user-images.githubusercontent.com/516243/44951985-c99ac380-aea5-11e8-8335-9f4a7d1e9c59.png">

When I run it seems that the debugger stop at the second breakpoint` if (type == 'register') { `
But actually it did not! Because when I click step over it run to a totally unrelated line.

<img width="1425" alt="window_and_index_js_ _jssipwrap_and_document" src="https://user-images.githubusercontent.com/516243/44951971-6f016780-aea5-11e8-8e89-1297bc9ab019.png">

This is another function, not that  eventListener callback I set my breakpoints.

<img width="1338" alt="window_and_index_js_ _jssipwrap" src="https://user-images.githubusercontent.com/516243/44952016-d966d780-aea6-11e8-8ae3-83c953b031ea.png">

Compared to how I run it in Chrome, it works fine.

<img width="1424" alt="window_and_document_and_index_js_ _jssipwrap" src="https://user-images.githubusercontent.com/516243/44952046-7b86bf80-aea7-11e8-900c-2be0d680697f.png">

**Comment by qiulang** [comment]
I can't but I will try to make a project I can

**Comment by qiulang** [comment]
Hi, I made a simple project to illustrate the issue.   
https://github.com/qiulang/es6-tutorial (Check the readme for further info).

So I set breakpoints at line 6, 9, 30

<img width="1387" alt="default" src="https://user-images.githubusercontent.com/516243/44968951-506e9f80-af7d-11e8-9dd4-89864d63f1dc.png">

But when launch the debugger it changed to other lines, the value I watched (principal) is wrong and I just can't stop at the line 30!

<img width="1380" alt="default" src="https://user-images.githubusercontent.com/516243/44968993-9b88b280-af7d-11e8-94e5-dc7b6228db3e.png">

When running in Chrome it works. The value of principal is correct too.

<img width="1440" alt="default" src="https://user-images.githubusercontent.com/516243/44969018-c83cca00-af7d-11e8-8104-8127fe265c11.png">

**Comment by roblourens** [comment]
Hm, the way the code is minified and processed by Chrome, for some reason we can't set a breakpoint on `document`. It has to be on the `getElementById` part. I'm not sure what Chrome does to get this case right. Will have to investigate more.

**Comment by roblourens** [comment]
The issue is basically that we our algorithm to pick the breakpoint spot doesn't look at the original line of the code, it just prefers a breakpoint location on the same minified line at an earlier column. Since the minified file is all a single line, and `document` is not a valid bp location, we end up picking the wrong bp location. We need to be smart enough to pick a bp location on the same original source line.

There are some issues with debugging minified code, I recommend not minifying code during development. It can make debugging confusing.

**Comment by qiulang** [comment]
But I did not use any minify plugin at all. To my limited knowledge I will need to use babel-preset-minify or babel-minify-webpack-plugin to minify my codes, which I didn't. Isn't that the case ?

**Comment by roblourens** [comment]
Sorry, I don't know, but if you look at the output it's minified.

**Comment by roblourens** [comment]
How do you build the app? `npm run debug` doesn't work for me, app.bundle.js 404s. So I did `npm run bundle` which I guess is a production build.

**Comment by qiulang** [comment]
Weird! `npm run debug` works for me
But you can also do  `npm run bundle` (but change to` "webpack --mode development"` to make sure it is not minified) then `npm start` (I just tried it again and it works for me)

**Comment by qiulang** [comment]
Hi I just found that if I use `"webpack --mode development"`  the debugger can stop at correct lines! So you were right in my sample project it was b/c of minified codes.

But I check my "real" project I make sure they are not minified and the debugger stop at the wrong lines

**Comment by qiulang** [comment]
Wait it is probably not b/c of **minified** codes but b/c of `webpack-dev-server` ! Let me further check.

**Comment by roblourens** [comment]
I'm not sure what the other issue is then, sorry.

**Comment by qiulang** [comment]
Hi I further check my project and have interesting finding, when I ` webpack --mode development` the generated code is not "entirely" minified, just each function body is minified. When I ` webpack --mode production` the entire file is minified.  I don't how webapck does that because I didn't set any thing for that

I updated my project so you have a look.  https://github.com/qiulang/es6-tutorial/tree/master/debug-vscode

**Comment by qiulang** [comment]
This is my webpack.config.js so which setting you were talking about. I don't think I set devtool option, but webpack always drives me crazy so I am not 100% sure :$

```
const HtmlWebPackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const webpack = require('webpack'); 
const path = require("path");

module.exports = {
    entry: './src/ui/index.js',
    output:{
        path: path.resolve(__dirname, './dist-wp'),
        filename: 'bundle.js'
    },
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader"
          }
        },
        {
          test: /\.html$/,
          use: [
            {
              loader: "html-loader",
              options: { minimize: true }
            }
          ]
        },
        {
          test: /\.(s*)css$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {}
            },
            'css-loader','sass-loader'
          ]
        },
        {
          test: /\.(gif|png|jpe?g|svg)$/i,
          use: [
            "file-loader"
          ]
        }
      ]
    },
    plugins: [
      new webpack.ProgressPlugin(),
      new HtmlWebPackPlugin({
        template: "resources/index.html",
        filename: "index.html"
      }),
      new MiniCssExtractPlugin({
        filename: "[name].css",
        // chunkFilename: "[id].css"
        publicPath:path.resolve(__dirname, './dist-wp'),
      })
    ],
    devServer: {
      contentBase: path.join(__dirname, './dist-wp'),
      port: 9000
    }
  };
```

**Comment by roblourens** [comment]
Maybe devServer sets it up like that, try setting `devtool: sourcemap`

**Comment by qiulang** [comment]
Hey I added `devtool: 'source-map'` to my webpack.config.js (so not to devServer setting) and the debugger works! 
It can stop at the breakpoints! I check the bundle file and the function body is NOT minified now.

So it is b/c of `devtool: 'source-map'` !

Thank you very much!

**Comment by roblourens** [comment]
It is mentioned in the readme
