### ISSUE TITLE
ReferenceError: showSavedCopyButton is not defined

### ISSUE THREAD

**Issue by Sing-T** [Microsoft/vscode-chrome-debug#726]
- VS Code Version: 1.27.0
- Chrome Version: Version 69.0.3497.81 (Official Build) (64-bit)
- OS Version: Windows 7 Professional

Steps:
1. Open vs code.
2. `vue create my-project`.
3. Choose 'Launch Chrome' configuration and Execute program.

Actual Result:
- New chrome window opens but throws exception.

```
Exception has occurred: ReferenceError
ReferenceError: downloadButton is not defined
    at HTMLButtonElement.eval (eval at E (chrome-error://chromewebdata/:14:208), <anonymous>:3:21)
    at w (chrome-error://chromewebdata/:4903:845)
    at L.e (chrome-error://chromewebdata/:4907:197)
    at window.jstProcess (chrome-error://chromewebdata/:4911:800)
    at chrome-error://chromewebdata/:4913:56
```
In VM44.js line 3.

Expected result:
- Chrome is successfully launched and html file opened.

I see an issue related with mine #682 . But I don't know if it has been solved.
I try to debug the project in webstorm, but it still don't work. So I think it may be the problem with the chrome. I hope u can help me.

**Comment by roblourens** [comment]
Probably the same cause as the other issue. Check that chrome is loading your page and your server is actually running.

**Comment by Sing-T** [comment]
I tried, but still don't working.

![1](https://user-images.githubusercontent.com/9331639/45136260-d127d880-b1d5-11e8-922b-728318be9e86.png)
![2](https://user-images.githubusercontent.com/9331639/45136267-d71db980-b1d5-11e8-9f8f-98d5f9419da6.png)

**Comment by Sing-T** [comment]
I've already uninstalled Chrome and then reinstalled it.

**Comment by roblourens** [comment]
You need to start a server for your app on that url. If you look at Chrome, you will see that it's not loading your webpage.

**Comment by Sing-T** [comment]
I run `npm run dev`, then I click the debug button.
The problem disappear but i get this.
![3](https://user-images.githubusercontent.com/9331639/45137784-aab96b80-b1dc-11e8-8c8c-7c9fb41e4dd3.png)

**Comment by Sing-T** [comment]
It doesn't have an impact on debugging, maybe I'll leave it there.
Thanks for your time.
