### ISSUE TITLE
Can't hit breakpoint on first line of javascript file in Chrome 69

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-chrome-debug#729]
Steps:
1. Set breakpoints on line 1 and 2 of a javascript file
2. Launch a web-page in VS Code chrome debug adapter that should hit those 2 breakpoints when the page loads

Actual:
Only the breakpoint on line 2 is hit

Expected:
The breakpoint on line 1 is hit

This work as expected in Chrome 68.

This is happening due to this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=882909

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
