### ISSUE TITLE
Unable to debug javascript in web page using Debugger for Chrome and VSCode Browser Sync

### ISSUE THREAD

**Issue by lupee431** [Microsoft/vscode-chrome-debug#732]
**Setup:**
(1)  Launch browser sync in side panel of vscode
(2) Get the port # being used for communication (this was 3010)
(3) Update launch.json  with the following:
{
            "name": "Chrome : Launch Chrome 3010, sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3010",
            "webRoot": "${workspaceRoot}/www/index.html",
            "sourceMaps": true,
            "runtimeArgs": [
            "--remote-debugging-port=9222"
            ]
        }
(4) set break point in javascript (I know the script is loaded...outputs to console.log)
(5) Choose launch config for Debugger and run

**Symptoms:**
(1) chrome is launched with about:blank
(2) vscode hangs for ~10 secs
(3)  The following is displayed:
"Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find valid target that matches: about: blank

Thanx,
Lew

**Comment by roblourens** [comment]
It looks like you switched from a "launch" config to an "attach" config, but another thing is that for a "launch" config you don't need to add that `--remote-debugging-port` flag yourself, Chrome will be launched with that flag automatically.

>  I could not get the debugger to attach when opening browser sync on a side panel

I don't understand, what do you mean by "side panel"?

**Comment by lupee431** [comment]
One of the browser sync options is to load your within vscode in a split screen view. It will display the port used in a popup. I tie the port and update my attach config then run the config. Didn't work. Syncing and debugging in separate chrome instance works great!
