### ISSUE TITLE
Add support for conditional breakpoints

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-chrome-debug#74]
Please add support for conditional breakpoints.
https://github.com/Microsoft/vscode/issues/1671

**Comment by minggo** [comment]
Yep, it is very useful.

**Comment by justin-romano** [comment]
![image](https://cloud.githubusercontent.com/assets/1707226/13732474/8dee455c-e9e8-11e5-8c78-937bc49a0594.png)
I suppose thats why im seeing this

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#10
