### ISSUE TITLE
Unable to open specified url (it opens blank page, instead)

### ISSUE THREAD

**Issue by JLammeer** [Microsoft/vscode-chrome-debug#743]
- VS Code Version: 1.28.2
- Log file (set `"trace": true` in launch config): [log-file.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2493718/log-file.txt)

Steps to reproduce:

1. Open VSCODE;
2. Click the green button for debugging.

Further informations:

1. It was working perfectly, untill yeasterday (10/17/2018);
2. [launch-file.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2493719/launch-file.txt);
3. [Error message](https://user-images.githubusercontent.com/35262827/47185742-b1bbb980-d304-11e8-83c0-e7896aac7d1f.png).

**Comment by JLammeer** [comment]
Problem, solved!

Solution: as you suggested, I changed the port.

Quick questions:

1. Is there any recommendation of port number to use (I'm using a random one)?
2. Why do I need to use a port, if it was never required in order to the extension to work?
3. Howcan I check Chrome processes hanging around from an old debug session (and stop it, maybe)?

**Comment by roblourens** [comment]
Great! 🎉 

In normal operation you shouldn't have to worry about that. The reason this fixed it is that the port number is included in the path that we generate for Chrome's user profile. If some Chrome process is stuck using the old user data dir, you may not be able to launch Chrome properly.

You can check whether that's the case by closing all instances of Chrome and looking for other chrome processes in task manager.
