### ISSUE TITLE
Feature request: support for human readable debugging for Immutable.js types

### ISSUE THREAD

**Issue by livemixlove** [microsoft/vscode-chrome-debug#744]
Investigating this. Looks like this is where the formatting action currently happens:
https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L2710

https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L2672

Here is immutablejs formatting code for chrome devtools:
https://github.com/andrewdavey/immutable-devtools/blob/master/src/createFormatters.js

This might be a feature for a separate extension, but since immutable is so popular, maybe add to this extension?

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/102181
