### ISSUE TITLE
this show wrongly in vscode

### ISSUE THREAD

**Issue by sandogeek** [Microsoft/vscode-chrome-debug#745]
- VS Code Version: 1.27.2
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. stop at same stopPorint,but this in vscode is diffent from the one in broswer as shown below:
![snipaste_2018-10-23_21-04-18](https://user-images.githubusercontent.com/16507453/47362590-4ceacf80-d707-11e8-8219-5a64c81ad958.png)

**Comment by sandogeek** [comment]
yes,that's what i mean.

**Comment by roblourens** [comment]
In that case you can watch the feature request here #12066
