### ISSUE TITLE
SourceMap issues when debugging Chrome WebExtension

### ISSUE THREAD

**Issue by ClementVidal** [microsoft/vscode-chrome-debug#746]
I'm trying to setup an **attach** config to debug a [Chrome WebExtension](https://developer.chrome.com/extensions) we are building.

Debugger correctly attach to chrome, but _**sourcemap**_ isn't at all present.

As observed in the *source* panel of the Chrome devtool every file used by my WebExtension are served from a weird, chrome extension specific url:

**chrome-extension://{some-long-strange-hash}/path/to/my/file.js**

So at first, i thought:
Easy, let's just write the correct **sourceMapPathOverrides** in **launch.json** and it should be ok !

But this was not that easy:

1. I wasn't able to write it, because if this some-long-strange-hash that change over time.
2. It seems that file loaded from **chome-extension** are skipped: https://github.com/Microsoft/vscode-chrome-debug/blob/be6219fcaa855829786c84778b0be89489c1a091/src/chromeDebugAdapter.ts#L207

So:

- Is there any well known receipe to correctly setup _vscode-chrome-debug_ when working with WebExtension ?
- Is this actually possible ?

Thanks !

**Comment by roblourens** [comment]
I don't officially support debugging extensions, but I can make changes to make it possible.

If giving you a way to disable that chrome-extension skipping line would help, I can do that. You could clone this repo and remove it to see if that fixes it for you.

**Comment by ClementVidal** [comment]
Disabling chrome-extension skipping line would solve half of the problem.

The other half being:
How do i correctly write the sourceMapPathOverrides knowing that there is a part of the url that change over time ( the some-long-strange-hash segment in the exemple )

Does the sourceMapPathOverrides support something like regex capture group ?

**Comment by roblourens** [comment]
That's right, only one * is supported, so you would probably need one pattern per file.

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code which supports non-capturing groups in the form `?:*`, for example

```
"chrome-extension://?:*/*": "${workspaceFolder}/*
```
