### ISSUE TITLE
Question: How to launch chrome debug in unsafe mode?

### ISSUE THREAD

**Issue by vksbansal** [Microsoft/vscode-chrome-debug#747]
First of all you have built an amazing tool which has saved my hours (if not months) of frustrating debugging. Many thanks and bless you.

Here, I am not reporting a bug instead its query :)

I am developing a React app and I have to launch chrome in unsafe mode for development phase.

To do that I run the following lines in terminal
```open -a Google\ Chrome --args --disable-web-security --user-data-dir=""```

Is it possible to run the ```vscode-chrome-debug``` in the unsafe mode too?

Your Admirer,
Vikas Bansal

**Comment by roblourens** [comment]
You can use the `runtimeArgs` property in your launch config to pass whichever args you want. For example, `"runtimeArgs": ["--disable-web-security"]`. Let me know if that helps!
