### ISSUE TITLE
How to set "sourceMapPathOverrides" with file extention?

### ISSUE THREAD

**Issue by YipingRuan** [microsoft/vscode-chrome-debug#750]
- VS Code Version: 1.28.2

In the document, it says 

> "The left hand side of the mapping is a pattern that can contain a wildcard, and will be tested against the sourceRoot + sources entry in the source map." 

If I have source files with special ending like "xyz.ts", may I use pattern like

`"webpack:///MyCode/*.xyz.ts`

to map to a special location?

**Comment by roblourens** [comment]
That should work
