### ISSUE TITLE
Simplify generated launch.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-chrome-debug#751]
Refs: https://github.com/Microsoft/vscode/issues/62851

Forking off from that discussion since this is chrome specific.

@roblourens I would remove the `webRoot`. The user just has to discover other field by using inteli-sense and I do not know is webRoot that special for chrome?
Apart from that I would not do anything for chrome for now. configuring sourceMapPathOverrides and pathMapping seems unrelated to this issue. Though we should probably think on how to tackle that independetly.
Also there is no way for you to find this out during the resolveConfiguration call?

**Comment by roblourens** [comment]
cc @auchenberg 

I don't know, I'm just not sure it helps that much, at the possible cost of confusing someone who needs to change that property. We made that decision a while ago, nothing else has changed since then.

**Comment by isidorn** [comment]
Ok. I leave this up to you and @auchenberg to decide what is best for chrome and if it could profit from some simpilfication / usage of quick input. 
Also let me know if there is anything on the vscode side which we should add that could potentially make the debug setup for chrome much easier.

I will focue more on engaging with extension authors outisde of our team.

**Comment by auchenberg** [comment]
I don't see a way for us to remove the `webRoot` property, as we need it to resolve paths for the source maps. 

By default it's set to workspaceFolder, which should be self explanatory.
