### ISSUE TITLE
Attach to Chrome not working while not in the exact url in browser

### ISSUE THREAD

**Issue by benshabatnoam** [Microsoft/vscode-chrome-debug#752]
When trying to attach the debugger to a working chrome (after lunching chrome with parameter: --remote-debugging-port=9222), the debugger won't attach unless the browser url is the exact same as configured in lunch.json file.

I expect that in any of my app routes the Attach to Chrome will success.
Lets say that the configuration url is http:/localhost:4200, then all of the this site child routes should work.

- VS Code Version: 1.29.0
- vscode-chrome-debug Version: 4.11.1

**Comment by roblourens** [comment]
See the parameter `urlFilter` which can take a wildcard

**Comment by benshabatnoam** [comment]
Used `urlFilter` with * wildcard at the end of the url and now I can attach debug to chrome.
10x a lot
