### ISSUE TITLE
About targetTypes

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/vscode-chrome-debug#758]
I have a electron renderer process, which has target type "webview".

I change the option `targetTargets ` to:
```
"targetTypes": [
    "webview"
],
```
But it still hint me that no matched debugger found.

So I traced into this repos, and I found in file `src/extension.ts`(master branch):
```
// line 53
targets = await discovery.getAllTargets(....... 
``` 
the `defaultTargetFilter` is passed to this function, it contains only `page` target type.

I change this argument to `getTargetFilter(config.targetTypes)` then it works.

Should I create a PR or there is a better solution?

**Comment by roblourens** [comment]
A PR would be great!

**Comment by roblourens** [comment]
Although I'm not sure why that would cause a problem, if that code doesn't find a matching target, it should continue normally to the code that does use the correct target type.

**Comment by connor4312** [comment]
Closed with the PR (and already supported in js-debug)
