### ISSUE TITLE
Kill child VS Code Task when you close Chrome

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/vscode-chrome-debug#759]
We have a `task.json` which launches our web app as a background task. This is launched as the `preLaunchTask` of the chrome debugger. However, when we stop the debug session, there's no way to indicate to VS Code that we want to kill the background task, so it stays running in the background.

Is this expected behaviour, or is there a way to force the background task to close as some event when the debugger is closed?

**Comment by roblourens** [comment]
I don't know of any way around it, @isidorn?

**Comment by isidorn** [comment]
Please use the `postDebugTask` in your `launch.json`. The `postDebugTask` should kill your background task.

**Comment by isaacabraham** [comment]
@isidorn how do I know which is the background task to kill? is there some way that we can thread this through the launch / task json files?

**Comment by isaacabraham** [comment]
@isidorn Also - appreciate that there are lots of issues across VS Code to wade through, but it would also really be nice if you could at least wait until I reply before closing the issue.

**Comment by isidorn** [comment]
We can always reopen.
As for which background task to kill that is up to your implemenation and how you contribute your task, more details here https://code.visualstudio.com/docs/editor/tasks and @dbaeumer can also help here better than me

**Comment by isaacabraham** [comment]
Great, that would be appreciated - I've read through the tasks docs but am still unclear how this would work.

**Comment by dbaeumer** [comment]
@isidorn actually if the task is started by debug then debug needs to kill it. Task doesn't know when a debug session ends. But IMO this should be configurable in the launch.json

**Comment by isidorn** [comment]
@dbaeumer the user just needs to specify a postDebugTask. That task will be called when the debug session ends. The postDebugTask should terminate the task and the user question is more about setting up a task that could do it properly

**Comment by dbaeumer** [comment]
Does `postDebugTask` support commands. Asking us to implement a task to terminate another tasks sounds very strange.

**Comment by isidorn** [comment]
`postDebugTask` is symetrical to `preLaunchTask`. So you can specify in it any task you want.
I do not think you need to implement anything, the user just needs guidance how to set this up as far as I undestand

**Comment by isaacabraham** [comment]
@isidorn I know of `postDebugTask` - the question is how that task can "get a handle" to the existing background task that was launched during the debug session in order to terminate it.

**Comment by dbaeumer** [comment]
@isidorn how do you imagine this should work if `postDebugTask` takes only tasks. What task should the user specify here. A shell task that tries to execute `kill ?`.

**Comment by isidorn** [comment]
@dbaeumer yes I imagined something like that. But I am not sure if it is possible, thus I pinged you.

**Comment by isidorn** [comment]
@isaacabraham than please file a feature request against vscode since we do not have this functionality at the moment
@dbaeumer thanks
