### ISSUE TITLE
VM49 Reference Error

### ISSUE THREAD

**Issue by PandaBoi57** [Microsoft/vscode-chrome-debug#763]
- VS Code Version: 1.29
- Log file (set `"trace": true` in launch config): Nothing changed when setting `"trace": true`

Steps to reproduce:

1. Run html?

Whenever i run the extension i get told localhost refused to connect, then vscode opens VM49 on line 3 and shows this error:

```
Exception has occurred: ReferenceError
ReferenceError: suggestionsSummaryListHeader is not defined
    at HTMLParagraphElement.eval (eval at E (chrome-error://chromewebdata/:14:208), <anonymous>:3:21)
    at w (chrome-error://chromewebdata/:5201:845)
    at L.b (chrome-error://chromewebdata/:5207:231)
    at L.e (chrome-error://chromewebdata/:5206:393)
    at window.jstProcess (chrome-error://chromewebdata/:5209:800)
    at chrome-error://chromewebdata/:5211:56
```

**Comment by roblourens** [comment]
This is an error from chrome itself. Same as https://github.com/Microsoft/vscode-chrome-debug/issues/682.

Is your webserver running? Is chrome able to load your site?

**Comment by PandaBoi57** [comment]
Chrome cannot connect to localhost:8080 because access is denied.

**Comment by roblourens** [comment]
Ok, then it sounds like you have some issue on your end with accessing your webserver.
