### ISSUE TITLE
Debugging Angular SPA with browserify: Breakpoints won't be hit...

### ISSUE THREAD

**Issue by cyphersx** [Microsoft/vscode-chrome-debug#77]
Hi,
i am using browserify with grunt to develop an Angular SPA. My problem is, that the breakpoints won't be hit, when i set sourceMaps to true. Browserify writes it's output into the dist-folder and the sourcemaps uri is attached at the end of the output file there. When i start debugging, chrome pops up and my app's login appears. When i've logged in, the breakpoints should hit, but they won't. I am assuming, that the extension (maybe) cannot find the sourcemaps the right way or something like that. Please help me, i like that extension a lot! See my filestructure, breakpoints and launch.config below:

![bildschirmfoto 2016-01-08 um 11 50 52](https://cloud.githubusercontent.com/assets/7375654/12196356/32efd63e-b5fe-11e5-935c-b0b2f0ddcfac.png)

Best regard!
Carsten.

**Comment by roblourens** [comment]
Hey, sorry for the slow response. Try setting the `diagnosticLogging` option in your launch.json config. You will see some hints about how the extension is trying to resolve the sourcemap. And if you can't figure it out, post the full log here.
