### ISSUE TITLE
When destructuring variables using rename syntax - variable's value is not accessible

### ISSUE THREAD

**Issue by drdmitry** [Microsoft/vscode-chrome-debug#775]
- VS Code Version:
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Datum: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architektur: x64
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Debugging Angular 6 app (TypeScript)
2. Use variables destructuring and renaming:
`const { publisherId: id, publisherName: name } = site as any;`
3. Expect values in `id` and `name`
4. In Chrome it is correct
![image](https://user-images.githubusercontent.com/4129726/49942344-56154300-fee5-11e8-9272-44dd033ee641.png)
5. In Visual Studio Code - `name` has name `name_2`, and when I hover on variable `name` - it's value is empty
![image](https://user-images.githubusercontent.com/4129726/49942599-0b47fb00-fee6-11e8-8f58-058f80d3a0a2.png)

Expected that "name" in VS Code Debugger will be not empty.

**Comment by roblourens** [comment]
Sometimes TS renames variables in down compilation cases and we have this issue to use names from the sourcemap https://github.com/Microsoft/vscode/issues/12066 but I don't know why it's renamed in this case, and can't repro it. What version of TS are you using, and what is the 'target' in your tsconfig?

**Comment by drdmitry** [comment]
@roblourens, thanks for getting back so quick.
TS version is 3.1.4 and `"target": "es5"`.

**Comment by roblourens** [comment]
Ok, that's basically what I'm trying. All I can say is that it's probably covered by https://github.com/Microsoft/vscode/issues/12066.

Building to es6 would help too.
