### ISSUE TITLE
[mobx.array] Attempt to read an array index (979) that is out of bounds (4)...

### ISSUE THREAD

**Issue by homoluden** [microsoft/vscode-chrome-debug#776]
Steps to reproduce:

1. Create simple project with ReactJS and MobX as a state management.
2. Create a MobX Store class with an observable array field.
```javascript
export default class SomeStoreModel extends computed(Actions) {    
    @observable someOptions = [{}, {}];

   constructor(model, showImageWidget, isUploaderEnabled) {
        super();
        
        this.someOptions = [{},{},{}]
    }
}
```

3. Create a function somewhere to instantiate this model.
4. Add a Breakpoint inside .ctor and try to peek at a value of 'someOptions' in Debug mode inside VS Code.

Actual Result: spam in Debug Console (see issue title and screenshot below)
![vs code debugger bug](https://user-images.githubusercontent.com/651025/50010495-12990280-ffd3-11e8-8fc5-98d1cf1dd2f5.jpg)

Expected Result: 
Filter out messages by tag "[mobx.array]" if possible.

PS: it looks like Chrome Dev Tools shows these dummy console records only if I hover over 'someOptions' in VS Code window, but when I'm doing the same in F12 window of the browser these warnings don't appear.

PS2: Sorry for blurring... NDA... blabla + had no time to create separate solution. Hope you'll got an idea of the issue. Let me know if repro code is really needed.

**Comment by homoluden** [comment]
Did you use @observable decorator? I believe mobx creates a proxy for array with length of 1000 items. Also mobx creates an indexed getter to throw a warning in case if some code tries to make cross bound access. If I peek this proxy wrapper in Chrome, browser also exposes all fake  items, but it don't spam into console.

Will try to implement repro code.

**Comment by connor4312** [comment]
This doesn't seem to reproduce on recent mobx versions -- seems like the underlying implementation has changed

![](https://memes.peet.io/img/20-11-40522539-aace-4013-a24c-382a98d7e777.png)

We have a [new debugger](https://github.com/microsoft/vscode-js-debug/) -- if you continue to run into problems, please open an issue there. Thanks!
