### ISSUE TITLE
Chrome debugger continues automatically

### ISSUE THREAD

**Issue by be-codified** [Microsoft/vscode-chrome-debug#778]
Hi,

I have installed the extension, created launch file with the following settings:

    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}"
    }

I have then set up a breakpoint, pressed F5, choose Chrome, Chrome then opens but I see "paused" notification, which disappears, shows again (this happens multi times) and it stops outside of debug mode.

Am I doing something wrong?

Thank you in advance.

**Comment by roblourens** [comment]
That's weird. Does it work better if you set `"breakOnLoad": false`?

**Comment by be-codified** [comment]
@roblourens thank you for your reply.

I have tried, things don't get any better. Can we dig deeper? Maybe it is something with my built system, I am using gulp and webpack.

**Comment by roblourens** [comment]
Can you set `"trace": true`, try it again, and upload the log from the path in the debug console?
