### ISSUE TITLE
Documentation for Linux missing

### ISSUE THREAD

**Issue by wbartussek** [Microsoft/vscode-chrome-debug#78]
Why is there no reference to using the debugger for Chrome on Linux boxes? VS Code runs perfectly on my Ubuntu box. Would be nice to have some guideline with examples how to install it there.
Cheers!

**Comment by roblourens** [comment]
In the readme, there is a line for launching Chrome in remote debug mode on Linux. Besides that, there are no Linux-specific instructions. You should be able to install it from `ctrl+shift+p` -> `install extension` -> `Debugger for Chrome`, same as other platforms.

**Comment by wbartussek** [comment]
Hi Rob,

 

thank you for your quick response! I think it would be helpful to give some hint that Chrome isn’t Chrome on Ubuntu but chromium-browser and how to find where it is installed. I had to gather all that from stackoverflow and other resources. Information on this is sparse. As a consequence I had a hard time setting up a working launch.json. So, an ‘official’ example of such a file for this environment would help beginners and save a lot of time.

 

Regards,

Wolfram

 

Von: Rob Lourens [mailto:notifications@github.com] 
Gesendet: Freitag, 8. Januar 2016 18:01
An: Microsoft/vscode-chrome-debug
Cc: Wolfram Bartussek
Betreff: Re: [vscode-chrome-debug] Documentation for Linux missing (#78)

 

In the readme, there is a line for launching Chrome in remote debug mode on Linux. Besides that, there are no Linux-specific instructions. You should be able to install it from ctrl+shift+p -> install extension -> Debugger for Chrome, same as other platforms.
