### ISSUE TITLE
Timeout when setting breakpoints

### ISSUE THREAD

**Issue by Malex** [microsoft/vscode-chrome-debug#781]
I get the following when I try to set any breakpoint anywhere in my code
```
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Users\$USER\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.1\node_modules\vscode-chrome-debug-core\out\src\utils.js:71:24)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

This does happen when I run
yarn start:dev 
which does the following:
ng serve --aot --configuration=dev --proxy-config proxy.conf.json
whereas, if I run yarn dev breakpoints work just fine
yarn dev does the following
ng serve --aot --configuration=dev

Proxy file doesnt do a lot (just "target": "http://localhost:8080", "secure": false)
launch.json is a simple     
```
"configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
        }
    ]
```

If you need any additional information, I'll try to provide as much as I can

**Comment by Malex** [comment]
Here's the only trace log that appears when setting to to true/verbose
`From client: setBreakpoints({"source":{"name":"hello.component.ts","path":"C:\\PATH\\to\\Component\\hello.component.ts"},"lines":[52],"breakpoints":[{"line":52}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"Versions.DebugAdapterCore":"6.7.34","Versions.DebugAdapter":"4.11.1","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@15234034d19b85dcd9a03b164ae89d04145d8368","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","Versions.Target.V8":"7.1.302.31","Versions.Target.Project":"Chrome","Versions.Target.Version":"71.0.3578.98","fileExt":".ts"}}}
SourceMaps.setBP: Mapped C:\\PATH\\to\\Component\\hello.component.ts to http://localhost:4200/main.0f33ac99db9ef95a2ccd.js
SourceMaps.setBP: Mapped C:\\PATH\\to\\Component\\hello.component.ts:52:1 to http://localhost:4200/main.0f33ac99db9ef95a2ccd.js:1:2008507
Paths.setBP: http://localhost:4200/main.0f33ac99db9ef95a2ccd.js is already a URL
→ To target: "{\"id\":36,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"20\",\"lineNumber\":0,\"columnNumber\":0},\"end\":{\"scriptId\":\"20\",\"lineNumber\":1,\"columnNumber\":0},\"restrictToFunction\":false}}"`

**Comment by roblourens** [comment]
That looks like just a portion of the log, can you post the whole file?

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
