### ISSUE TITLE
VS Code does not open nor highlight the source code where breakpoint is set  to

### ISSUE THREAD

**Issue by bgiavotto** [microsoft/vscode-chrome-debug#782]
Steps to reproduce:

1. the issue show up using create-react-app. so to reproduce, install reactjs 
2. create a sample project using create-react-app
3. in command prompt cd onto the application
4.  in command prompt type code .
5. start the application with yarn start  ( or equivalent  npm )
6 . when is does run, close the browser 
7. place a breakpoint on the first line on the render method
7.  go to VS Code, start a debug session on vscode
8. when the browser open up, click refresh, 
9. notice that the breakpoint will be reached and hit, vs code catch the break, however, fail to open the source code where the breakpoint were placed and also fail to highlight the current execution location.
Please note: 
a) If, when the program is suspended on the breakpoint one switch to chrome browser and open dev tools / source code, the exact current execution point is highlighed on the chrome dev tool.
b) Edge/Firefox debugger plugins are working as expected.

the exact same project works OK, on a different machine without problems, 
same versions on both machines of:
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Debugger for chrome : 4.11.1

Expected behavior:
when a break point is reached, VS Code should open the source code in a window (if not already opened), then highlight the current execution point.

**Comment by roblourens** [comment]
In the call stack, are the frames grayed out with "skipped via smartStep" or something like that?

**Comment by bgiavotto** [comment]
I have done a screen shot. the screen shot show vscode in "breakpoint reached" mode.
As you can see, the call stack is on the left. the breakpoint is reached and it does correctly stop at the breakpoint line. However i expect to see a sign and a bullet showing the current execution point.

If i switch to Chrome dev tools here the current execution point is showed.


![ss](https://user-images.githubusercontent.com/24678659/52698501-e0286900-2f73-11e9-82fc-2c37bcbb2360.png)
![image](https://user-images.githubusercontent.com/24678659/52698742-75c3f880-2f74-11e9-8f85-e56b2210f808.png)

**Comment by bgiavotto** [comment]
A side note: in the screen shot you see the source code window opened without the execution point sign only because the source code tab was previously opened. this is a side effect, the problem is that when the breakpoint is reached, VS Code, try to open the source code tab and fail, So if the source code was previously displayed you see the situation in the screen shot. Otherwise, without a source code tab alredy on screen no tab will be opened, It does appear as VS Code is failing to correctly find the source code file on filesystem.

**Comment by roblourens** [comment]
It should open the file correctly if you click the top stack frame though right?

Could you set `"trace": true` in your launch config, run this again, and upload the log here? It writes the log path to the debug console.

**Comment by ilovett** [comment]
I started experiencing my lines not being highlighted on step overs or debugger break points, I did see the `skipped by 'smartStep'` which @roblourens mentioned:

![image](https://user-images.githubusercontent.com/1776100/53840665-8e11ac80-3f4f-11e9-8c4c-d230d7a975d4.png)

But not always.

I am using the PickProcess method with babel-node compile:

```
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Debug Pick Process",
      "processId": "${command:PickProcess}",
      "restart": true,
      "protocol": "inspector",
    }
```

`package.json`:
```
  "scripts": {
    "start": "nodemon --exec babel-node src/server.js",
    "start:debug": "nodemon --inspect --exec babel-node src/server.js",
  }
```

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
