### ISSUE TITLE
My Chrome Debugger doesn't work in VSC 1.31.1

### ISSUE THREAD

**Issue by Bundas** [Microsoft/vscode-chrome-debug#783]
Issue Type: <b>Bug</b>

**Expected:** When the app hits a breakpoint - VS code's editor reflects it (allows me to explore variables and so on).

**Actual:** When the app hits a breakpoint, there is correct callstack, debugger knows that app hit the breakpoint but editor doesn't allow me to explore variables etc. Also variables "section" in debugger tab shows nothing. It's empty.

**How to reproduce:** Install chrome debugger plugin, set a breakpoint, make the app hit the breakpoint

Extension version: 4.11.1
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Can you show a screenshot so it's clear what you are seeing? @isidorn

**Comment by roblourens** [comment]
You are probably seeing https://github.com/Microsoft/vscode/issues/68464, I am updating the Chrome extension now to give you a way to fix this.

**Comment by roblourens** [comment]
Now you should be able to set `"smartStep": false` to work around this. Real fix coming with https://github.com/Microsoft/vscode/issues/68127
