### ISSUE TITLE
cannot connect to runtime process timeout after 10000 ms - (reason cannot connect to the target: connect econnrefused 127.0.0.1:9222

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [Microsoft/vscode-chrome-debug#784]
Hi,
I am trying to debug my SPFx web part in Visual studio code. So I ran "gulp serve -nobrowser" in npm and hit F5 in VS Code.
But my debugger is not hitting the break point. It is throwing below error.

![image](https://user-images.githubusercontent.com/42473451/52793904-af752c00-3066-11e9-8d75-d22c3ffb7e98.png)

This is my code in launch.json:
```
{
  /**
   * Install Chrome Debugger Extension for Visual Studio Code to debug your components with the
   * Chrome browser: https://aka.ms/spfx-debugger-extensions
   */
  "version": "0.2.0",
  "configurations": [{
      "name": "Local workbench",
      "type": "chrome",
      "request": "launch",
      "url": "https://localhost:4321/temp/workbench.html",
      "webRoot": "${workspaceRoot}",
      "userDataDir": "${workspaceRoot}/out/chrome",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../../src/*": "${webRoot}/src/*"
      },
      "runtimeArgs": [
        "--remote-debugging-port=9222"
      ]
    },
    {
      "name": "Hosted workbench",
      "type": "chrome",
      "request": "launch",
      "url": "https://enter-your-SharePoint-site/_layouts/workbench.aspx",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../src/*": "${webRoot}/src/*",
        "webpack:///../../../../../src/*": "${webRoot}/src/*"
      },
      "runtimeArgs": [
        "--remote-debugging-port=9222",
        "-incognito"
      ]
    }      
  ]
}

```

Please help
Steps to reproduce:

1. I closed all instances of chrome and  tried multiple times but still it didn't work.

**Comment by roblourens** [comment]
Why did you include `"--remote-debugging-port=9222"`? You don't need that. It's probably causing this issue because the debug adapter will pick a different port.

**Comment by AnjaniChallamcherla** [comment]
@roblourens I didn't include anything. All those were created by Visual Studio Code while creating a new SPFx web part.

**Comment by roblourens** [comment]
So the launch configs came from an extension or something? Try removing `"--remote-debugging-port=9222"` I think that should fix it.

**Comment by AnjaniChallamcherla** [comment]
The launch config came from an spfx webpart, which I created by following steps in https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part. I didn't make any changes.

**Comment by roblourens** [comment]
When you run it, does Chrome launch succesfully?

**Comment by AnjaniChallamcherla** [comment]
When I run the code without debugging it is launching chrome successfully.
But when I run the code with debugging I am getting time out error as below image
https://user-images.githubusercontent.com/42473451/52793904-af752c00-3066-11e9-8d75-d22c3ffb7e98.png

**Comment by roblourens** [comment]
But when you get the timeout error, does it still launch chrome?

**Comment by AnjaniChallamcherla** [comment]
No, nothing happens after that.

**Comment by roblourens** [comment]
I wonder if you have Chrome installed in an unusual place? Are there any errors in the debug console?

Can you set `"trace": true`, run it again, and upload the log from the path in the debug console?

**Comment by epignot** [comment]
Hi,
I had the same problem on MacOS until I noticed the address used by Chrome for exposing debugging api :
```bash
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

DevTools listening on ws://[::1]:9222/devtools/browser/5678127d-1c0c-4405-a504-d9aa62edc405
```
I saw in trace Chrome Debugging Extension was trying to reach '127.0.0.1'
So, I resolved it by specifying the debugging adress in launch.json : 
```json
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "address": "[::1]",
            "url": "http://localhost:3000",
```
In fact, Chrome was responding on '[::1]' and 'localhost' but not on '127.0.0.1',

Hope this helps

**Comment by roblourens** [comment]
That's interesting! But shouldn't that address still respond to `http://localhost:9222`? Do you know why it's using the ipv6 form?

**Comment by LuminescentMoon** [comment]
I'm having the same problem. Here's the log: https://www.hastebin.com/nasusarecu.log

**Comment by LuminescentMoon** [comment]
I've noticed that VSCode adds flag `--inspect-brk=6483` when launching the process, but according to the [Node documentation for --inspect-brk](https://nodejs.org/en/docs/guides/debugging-getting-started/), the argument format is `[host:port]` when VSCode only provides a number. Could this be the issue?

**Comment by LuminescentMoon** [comment]
Never mind that. Manually specifying the port the process listens to **AND** the port VSCode connects to solves the problem. Reading the logs again, I've noticed that Electron 5.0.0-beta.5 completely ignores the port to listen to specified by `--inspect-brk`.

**Comment by roblourens** [comment]
Host and port are both optional. 

> Reading the logs again, I've noticed that Electron 5.0.0-beta.5 completely ignores the port to listen to specified by --inspect-brk.

That's really interesting. Thanks for pointing that out, I'll have to investigate

**Comment by LuminescentMoon** [comment]
@roblourens it's a known issue. https://github.com/electron/electron/issues/17348
