### ISSUE TITLE
Script not loaded in iframes so breakpoints not hit

### ISSUE THREAD

**Issue by akrantz** [microsoft/vscode-chrome-debug#786]
Debugging Office Add-ins running in Chrome will work, meaning breakpoints will be hit, when using the Chrome browser dev tools. However, when using VSCode Debugger for Chrome, the breakpoints will not be hit. It appears that the extension does not handle scriptParsed messages for source inside of an iframe.

- VS Code Version: 1.31.1
- Log file (set `"trace": true` in launch config):

Steps to reproduce:
(Need git and Node installed.)
1. git clone https://github.com/OfficeDev/Excel-Custom-Functions.git
2. cd Excel-Custom-Functions
3. npm install
4. Open certs\ca.crt and install certificate in Current User, place in Trusted Root Certification Authorities.
![image](https://user-images.githubusercontent.com/741153/53810855-ba580980-3f0c-11e9-95be-fc444d041192.png)
![image](https://user-images.githubusercontent.com/741153/53810894-d5c31480-3f0c-11e9-8551-d9f2e905a83d.png)
4. code .
5. Terminal, Run Task, "Watch"
6. Terminal, Run Task, "Dev Server"
7. Close Chrome if running, then open to https://localhost:3000/taskpane.html. Verify that SSL certificate is trusted for localhost.
8. Open Chrome browser to http://www.office.com, and sign in.
9. Click Excel, then New blank workbook.
![image](https://user-images.githubusercontent.com/741153/53810400-b24b9a00-3f0b-11e9-8f56-400c94300414.png)
![image](https://user-images.githubusercontent.com/741153/53810424-c2637980-3f0b-11e9-9e57-c00123b16178.png)
10. Click Insert, Add-ins.
![image](https://user-images.githubusercontent.com/741153/53810499-f343ae80-3f0b-11e9-92d6-23a078d22791.png)
![image](https://user-images.githubusercontent.com/741153/53810519-02c2f780-3f0c-11e9-828e-69fd337f3af8.png)
11. Click arrow next to Manage My Add-ins, and choose Upload My Add-in.
![image](https://user-images.githubusercontent.com/741153/53810579-2423e380-3f0c-11e9-9a13-46ffbd296bfa.png)
12. Click Browse, open "manifest.xml" file in Excel-Custom-Functions folder, and click Upload.
13. Click on Home, Show TaskPane.
![image](https://user-images.githubusercontent.com/741153/53811075-56821080-3f0d-11e9-93d0-eadab4205d38.png)
![image](https://user-images.githubusercontent.com/741153/53811086-600b7880-3f0d-11e9-990e-cf7288e880d6.png)
14. Click Run button. The selected cell will turn yellow.
15. Right-click task pane in empty area near Run button.
16. In dev tools, click on Sources.
17. Ctrl+P and open "taskpane.ts" (This is webpack:///./src/taskpane/taskpane.ts)
18. Set a breakpoint in run() on "await Excel.run()" line. 
19. Click the Run button in the task pane. The breakpoint will be hit.  (This shows the breakpoint working in Chrome dev tools.
20. Close Chrome dev tools. 
21. Click the Share button for the Excel document, and copy the link.
![image](https://user-images.githubusercontent.com/741153/53811304-eaec7300-3f0d-11e9-853d-1a91ee18747c.png)
 
![image](https://user-images.githubusercontent.com/741153/53811334-02c3f700-3f0e-11e9-8046-4621fafa3631.png)
![image](https://user-images.githubusercontent.com/741153/53811374-153e3080-3f0e-11e9-9035-0d78da132346.png)
22. Close the Chrome tab containing the Excel document.
23. Go to VS Code.
24. Open src/functions/functions.ts.
25. Set a breakpoint in run() method on "await Excel.run()" line.
26. Switch to Debug view.
27. Choose "Office Online (Chrome)" launch target.
28. Press F5 or green arrow to start debugging.
29. When prompted, paste the link into the edit box and press Enter.
![image](https://user-images.githubusercontent.com/741153/53811471-56cedb80-3f0e-11e9-8ba8-0bdd333961dd.png)
30. Chrome will launch and open the Excel document.
31. The Home menu tab should be selected. Click the Show TaskPane button.
32. Click the Run button in the taskpane.
RESULT: it does not hit the breakpoint in VS Code.
EXPECTED: it should hit the breakpoint.

**Comment by akrantz** [comment]
log file:
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2931307/vscode-chrome-debug.txt)

**Comment by akrantz** [comment]
In Chrome dev tools Source, there is a `{"baseFrameName":...` source which is for the iframe. There is no scriptParsed event that appears for VSCode-chrome-debug log file.
![image](https://user-images.githubusercontent.com/741153/53812017-68fd4980-3f0f-11e9-8e99-bac45a9f5373.png)

**Comment by akrantz** [comment]
Apologies for the long repro steps, but I couldn't construct a simple repro using an iframe. It would help to have one.

**Comment by roblourens** [comment]
Thanks for the info, you are correct that debugging in iframes is not currently supported.

**Comment by MatisseHack** [comment]
Just ran into this issue as well when trying to debug a different type of extension (Azure DevOps). Although I was able to debug it eventually by using Firefox instead, it would be great if iframes were supported with Chrome!

**Comment by pl4nty** [comment]
Battled for several hours until I found this thread. Will have to use Firefox as [SO](https://stackoverflow.com/questions/37007971/vscode-debugging-an-iframe-inside-a-web-application-with-vscode-chrome-debug) and Matisse mentioned.

**Comment by rmouser** [comment]
> Just ran into this issue as well when trying to debug a different type of extension (Azure DevOps). Although I was able to debug it eventually by using Firefox instead, it would be great if iframes were supported with Chrome!

Same here, working with the new Azure DevOps extension API and could use better debug tools.

**Comment by connor4312** [comment]
We now support iframes with the new debugger that was released at the end of June.
