### ISSUE TITLE
Please Show Angular Config Example

### ISSUE THREAD

**Issue by largeDachshund** [microsoft/vscode-chrome-debug#787]
I'd love to use this code editor for debugging.  I'm developing an Angular CLI app

**launch.json**
![image](https://user-images.githubusercontent.com/7054672/54080357-a3b20980-42a2-11e9-9e22-a231d646f9fa.png)

result:
a blank Chrome window pops up, but disappears and this shows:
![image](https://user-images.githubusercontent.com/7054672/54080347-811ff080-42a2-11e9-95ef-9f12a2a7992e.png)

- VS Code Version:
![image](https://user-images.githubusercontent.com/7054672/54080366-dbb94c80-42a2-11e9-881c-19b02d01eb16.png)

Steps to reproduce:

1.Create an Angular CLI app
2.Create a launch.json file according to the VS Code example
3. Start debugger with Launch configuration

**Comment by roblourens** [comment]
Did a new tab open in Chrome when you started the launch config?
