### ISSUE TITLE
Breakpoint being set on wrong line during SourceMaps.setBP mapping

### ISSUE THREAD

**Issue by EricG-Personal** [microsoft/vscode-chrome-debug#788]
- VS Code Version: Version 1.32.1 (1.32.1)
- Debugger For Chrome Version: 4.11.3
- Log file (set `"trace": true` in launch config):

[log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2958396/log.txt)

Steps to reproduce:

0. git clone https://github.com/ericg-vue-questions/quasar_debug.git
1. yarn install
2. quasar dev
3. set a breakpoint on line 21 in Index.vue ( console.log('in returnArray') )
4. Press play

It will not stop on the breakpoint.

Looking at the trace, the problem seems to be that when it tries to setBP on line 21, it never gets mapped to the correct line in the original file.

**Comment by Enteleform** [comment]
This might be resolved by the [new debugger](https://github.com/microsoft/vscode-chrome-debug/issues/1010#issuecomment-632219525).

**Comment by EricG-Personal** [comment]
> This might be resolved by the [new debugger](https://github.com/microsoft/vscode-chrome-debug/issues/1010#issuecomment-632219525).

Unfortunately, I haven't been able to confirm that. It could be due to the instability of the new debugger. It would be nice to know if the intent was for this bug to fixed with the new debugger.

**Comment by roblourens** [comment]
The new debugger is on its way to becoming the default, and if there is a bug on our end, it will be fixed in the new debugger and not in the old one. What issues are you having with it?

**Comment by EricG-Personal** [comment]
@roblourens It is probably too much to say "everything". I cannot currently locate any kind of easy quick start guide, etc. to help me figure out how the new debugger differs from the old one in terms of setup and configuration. Most of the documentation I find is using the old debugger and I am assuming it doesn't apply any longer.

Let's say I want to do something simple:

1. quasar create quasar_new_debugger
2. to ./pages/Index.vue, add:

```
  mounted: function () {
    console.log("I'm here")
  }
```

inside of ```export default```

3. quasar dev

"I'm here" should appear in the console. Now, I want to set a breakpoint on the console.log statement and have it stop there.

What do I do now?

I need launch.json file. What should it look like?

I understand that answering these kinds of questions are likely beyond the scope here, but I am willing to spend the time trying to figure this out if you wanted to use me to help improve documentation in this area for people who just want to see things work.

The informational page for the Javascript Debugger extension is written for those who can answer these questions.

**Comment by EricG-Personal** [comment]
@roblourens If you would like to pursue this further and there is a better forum in which to do so, please let me know.

**Comment by roblourens** [comment]
I see that you already have a launch config in your test repo, ideally you should not have to change that to work with the new debugger.

**Comment by roblourens** [comment]
The new one is enabled by default in the vscode Insiders build - https://code.visualstudio.com/insiders, you either install that and try running it there, or enable `debug.javascript.usePreview` to use it in stable vscode

**Comment by EricG-Personal** [comment]
I am using VS Code 1.46.1. I have debugger for chrome v4.12.8 installed. Javascript Debugger v1.46.1 is already installed.

debug.javascript.usePreview is true.

I do as described in the bug above and set the breakpoint. 

It does not stop.

Is it supposed to stop?

**Comment by roblourens** [comment]
cc @connor4312

**Comment by connor4312** [comment]
Using the new debugger and your launch config + deps from the repo, I'm able to hit a breakpoint there

![](https://memes.peet.io/img/20-07-b5770e40-25ab-4e80-8ddf-dc0f44da0c4e.png)

the output also appears in the terminal

![](https://memes.peet.io/img/20-07-67de8f08-2787-4a11-8326-b36bf2d32105.png)

Am I doing something differently than you are?

Enabling `trace: true` and sharing the resulting log file with us (its location will be printed in the Debug Console) will help us dive in further to any issues.

Thanks for the report!

**Comment by EricG-Personal** [comment]
@connor4312 

I have to assume that I am doing something different because it does not work for me. I have attached the log file.

In addition, you can find a screen recording here: http://ericgorr.net/recording.mov

(note, the recording won't be there for long and I wasn't sure if it would be ok to attach it to this report...if you wanted to grab it and attach it, feel free.)

Please let me know what more I can do. I would like to see this working reliably.

Note, the first time I pressed play, I received a timeout error (vscode-debugadapter-3.json). I am not sure if the Javascript Debugger was involved or not. 

The second time I pressed play, the code ran, but the breakpoint was not hit.

I have not mentioned yet that I am using macOS X 10.15.5. This may be an OS specific issue.

[Archive.zip](https://github.com/microsoft/vscode-chrome-debug/files/4861720/Archive.zip)

**Comment by EricG-Personal** [comment]
@connor4312

I have to assume that I am doing something different because it does not work for me. I have attached the log file.

Please let me know what more I can do. I would like to see this working reliably.
[vscode-debugadapter-7.json.zip](https://github.com/microsoft/vscode-chrome-debug/files/4861770/vscode-debugadapter-7.json.zip)


I have not mentioned yet that I am using macOS X 10.15.5. This may be an OS specific issue.

**Comment by connor4312** [comment]
Ah, I see you're on a slightly older version that came before I put in [a fix for handling vue apps](https://github.com/microsoft/vscode-js-debug/commit/2f3c93a08df0ceb09eda86251d0309d34bfb26ef). You have three options:

 - Wait for the upcoming stable release on Wednesday that will contain a new version of js-debug
 - Use our [Insiders build](https://code.visualstudio.com/insiders/) that already contains the new version
 - Or use the [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) of js-debug

Once you are able to try with the new version, let me know if you hit any problems!

**Comment by EricG-Personal** [comment]
Unfortunately, it does not appear to be working for me.

```
Version: 1.47.0-insider
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:41:12.081Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Debugger for Chrome v4.12.9
Javascript Debugger (Nightly) v2020.7.117

It appears I need to use the nightly version of JS Debugger.

When I press "Play", a dialog appears which says "Unable to attach to browser".

I have attached the log file.

Perhaps the nightly version is broken and the version you were using is working.

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4864225/vscode-debugadapter-0.json.gz)

**Comment by EricG-Personal** [comment]
@connor4312 

I tried something different and think I may now be using the JS Debugger that came with the Insiders version. Is that v1.47.1?

When I pressed play the first time, I got the following message:

```
Error processing launch: Error: Could not attach to main target
	at Object.t.timeoutPromise (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33023)
	at f.prepareLaunch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2619737)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async f.launch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2620312)
	at async t.Binder.captureLaunch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25642)
	at async t.Binder._launch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25213)
	at async Promise.all (index 6)
	at async t.Binder._boot (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:24473)
	at async t.default._onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2459238)
```

This should be the log file [vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4864569/vscode-debugadapter-1.json.gz)

I pressed play a second time and got the "Unable to attach to browser" message. Log File: [vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4864575/vscode-debugadapter-2.json.gz)

I still cannot get the code to run or stop at a breakpoint.

**Comment by connor4312** [comment]
> I pressed play a second time and got the "Unable to attach to browser" message

This happens if the browse is already running -- unfortunately then launching a new instance of the browser will 'no-op' and direct to the existing instance. Usually we clean up after ourselves, but if a launch fails then the browser can remain open. Fixed this in f864657

From your log, it _looks_ like Chrome is being sluggish, or the launchservice lookup we do takes a long time to find your Chrome binary. Some suggestions:

- To rule out launchservices, you could set the `runtimeExecutable` to the Chrome binary manually. On my MacBook the path is `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`
- Rebooting the machine might clear whatever is causing an issue

**Comment by EricG-Personal** [comment]
@connor4312 

I updated my launch.json to:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src",
            "breakOnLoad": true,
            "sourceMapPathOverrides": {
                "webpack:///./src/*": "${webRoot}/../src/*",
                "webpack:///src/*": "${webRoot}/../src/*",
            },
            "trace": "verbose",
            "timeout": "30",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        }
    ]
}
```

I can confirm that it is using the *runtimeExecutable* setting because if I set it to a bad path, I get an error message that it cannot find the executable. The timeout setting had no effect on how quickly the "Unable to attach to browser" message appeared.

I did try restarting my machine, but that did not help.

I also tried using a much faster machine and got the same behavior.

I do not think the issue is finding or launching Chrome. Chrome does appear and a new window does open with a tab called "about:blank" ... which I think is expected just before the site actually loads. Unfortunately, the site never loads and I get the attach error.

Let me know what else you would like me to try. I continue to be motivated to get this working.

**Comment by connor4312** [comment]
I think this should be fixed with https://github.com/microsoft/vscode-js-debug/issues/570
