### ISSUE TITLE
Allow editing of values in watch window

### ISSUE THREAD

**Issue by sandipchitale** [Microsoft/vscode-chrome-debug#789]
- VS Code Version: 1.32.1

Steps to reproduce:

1. Load an expression in watch window.
2. Try to edit values of properties of the resulting object.
3. The value cannot be edited. I am able to edit values in Variables view. I think Chrome's devtools supports it.

![image](https://user-images.githubusercontent.com/3310939/54316826-db6cca00-459e-11e9-8198-6f69cbf11604.png)

**Comment by roblourens** [comment]
This would have to be supported by vscode and the debug adapter protocol. I think it's not likely to happen but you could file a request on the vscode repo.
