### ISSUE TITLE
Breakpoints not reloaded using HMR

### ISSUE THREAD

**Issue by jmesa-sistel** [microsoft/vscode-chrome-debug#791]
- VS Code Version: 1.32.3

Steps to reproduce:

1. Start a HMR project
2. Add a breakpoint in code, at now it works
3. Modify code, then HMR reload the page
4. Breakpoints are not working

Workaround add a new breakpoint & remove it

**Comment by thunderkid** [comment]
I'm getting breakpoints just graying out whenever I launch the debugger, using 1.32.3. Happens prior to any HMR reloads. Had this a year or so back - they seemed very unstable so I just bothering with them. They seemed to be working fine a couple of weeks ago, but now unusable again.

**Comment by warappa** [comment]
Hit this bug also with **Vue 2.6.11** and **VS Code 1.46.1** and **vscode-chrome-debug 4.12.8**.
It's like the breakpoint still is on the old version and not on the new version of the file.

Running `Reapply All Breakpoints` is also a workaround that works.

As it is tedious to always try to find this button I created a keyboard-mapping, so this is my way forward in the mean-time.

**Comment by connor4312** [comment]
Thanks for the issue, apologies for the late response!

We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/) if you continue to run into problems.
