### ISSUE TITLE
Angular 6 : vscode chrome debug not working in angular proxy mode.

### ISSUE THREAD

**Issue by prakashsam** [microsoft/vscode-chrome-debug#794]
Angular 6 : vscode chrome debug working in normal mode and  not working in angular proxy mode.

**Comment by roblourens** [comment]
Please give more details like a project where I can reproduce the issue.

**Comment by prakashsam** [comment]
In Angular 6  we configure the proxy in proxy.conf.json file.

{
    "/app/snl/**": {
        "target": "http://localhost:6000/",
        "secure": false,
        "logLevel": "debug",
        "changeOrigin": "true",
        "pathRewrite": {
            "^/app/snl": "/"
        }
    }
In normal mode  running in http://localhost:4200/ - vscode debug workig fine.
In proxy mode running in  http://localhost:6000/app/snl/#/ and config this url in launch.json but not working.

**Comment by theresiasnow** [comment]
changed http to https in proxy.conf -> started working :-)

**Comment by theresiasnow** [comment]
and then stopped. using http://127.0.0.1:<port> works..

**Comment by connor4312** [comment]
Thanks for the issue, apologies for the late response!

We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/) if you continue to run into problems.
