### ISSUE TITLE
Launch debugger programatically?

### ISSUE THREAD

**Issue by Raagh** [Microsoft/vscode-chrome-debug#795]
Hi, I am currently building a vscode extension for running angular tests.  I will try to build a feature to support not only running tests but debugging them in vscode. for that I need to launch the debugger for chrome programatically from my vscode extension. is there a way to do this?

**Comment by roblourens** [comment]
Yes, you can use the `startDebugging` extension API to launch a debug config, either by name in launch.json or by providing the whole config in code: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L8833
