### ISSUE TITLE
sourceMapPathOverrides does nothing

### ISSUE THREAD

**Issue by JacobDB** [Microsoft/vscode-chrome-debug#802]
- VS Code Version: 1.33.0
- Log file: [vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/3060586/vscode-chrome-debug.txt)

I'm trying to get debugging JavaScript working, but I can't seem to get VS Code to recognize my source files that are referenced in files compiled with Webpack. I've tried numerous configurations on `sourceMapPathOverrides`, none of which seem to work. `.scripts` doesn't show any valid mappings, and breakpoints are never hit. I've even tried doing 1-to-1 file mapping, taking the exact paths from `.scripts` and pointing them to the exact uncompiled paths, but that doesn't do anything either.

This is the most recently configuration I've been trying to get working. What am I doing wrong?

```JavaScript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "JavaScript – Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://framework.localhost/",
            "webRoot": "${workspaceFolder}/dev",
            "sourceMapPathOverrides": {
                "webpack:///./node_modules/*": "${workspaceFolder}/node_modules/*",
                "webpack:///./src/*": "${workspaceFolder}/src/*",
            },
            "trace": true
        },
    ]
}
```

I'm testing this on my custom WordPress framework &ndash; https://github.com/JacobDB/new-site.

**Comment by JacobDB** [comment]
`webRoot` does work correctly, as `.scripts` shows a correct mapping for those files, and changing it or removing it removes the mapping. I'm sure I'm doing something wrong...

**Comment by roblourens** [comment]
It looks like your scripts do not actually have sourcemaps, and that property only overwrites details from the sourcemap. So you probably need to fix your build to produce sourcemaps.

**Comment by JacobDB** [comment]
I'll take another look in the morning, and post one of my compiled files, but I'm pretty sure they have sitemaps. I can see the list of `webpack:///` things when I run `.scripts`, and I can browse the uncompiled code with Chrome's Dev tools.

**Comment by JacobDB** [comment]
Alright, [here's one of my compiled files](https://gist.github.com/JacobDB/9afad6ce3ac079e49186bbb4269c0a0e). As you can see, there's 35 instances of `webpack:///` in the code,

And [here's what I see in the Chrome dev tools "Sources" panel](https://user-images.githubusercontent.com/1123997/55883226-8f944d00-5b6b-11e9-8ffc-a8da481399c5.png).

**Comment by JacobDB** [comment]
Interesting, setting `"devtool": "source-maps"` does fix the problem, although that requires me to change how some stuff is generated... shouldn't it work with the inline `webpack:///` stuff?

**Comment by JacobDB** [comment]
With some modifications, I'm able to make using `.map.js` files work with my needs, so that's a good enough fix for me. I did read about using `.map.js` files in the README, but the stuff referencing `webpack:///` mappings confused me, and made me think that they weren't necessary. Making that a bit more clear would be great, I'm sure there are others like me who are new to this and just very confused.

Thanks for your patience and your help!
