### ISSUE TITLE
Cannot read property 'logout' of undefined

### ISSUE THREAD

**Issue by shakibamor** [Microsoft/vscode-chrome-debug#803]
I am using chrome debugger for VS Code for my Angular project. I had no issue working with debugger before from today it started giving me these below error:

![image](https://user-images.githubusercontent.com/8889578/55832197-fc173980-5ae2-11e9-8f18-ddae1b51f678.png)

- VS Code Version: 1.33.0
- Log file (set `"trace": true` in launch config): Attached

Steps to reproduce:

in my login component I have:
import { AuthenticationService } from 'src/app/_services';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor(
    private authenticationService: AuthenticationService,

    }

  ngOnInit() {

    // reset login status
     this.authenticationService.logout();

}

I am not sure why suthenticationService is undefined. It is compiling perfectly fine when I use Angular CLI ng serve.

I did not find any hint in log file and I am not sure what is the difference between compilations in ng serve and chrome debugger that I get this error just in debug mode.

This is my lauch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
            "trace": true
        }
    ]
}
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/3060822/vscode-chrome-debug.txt)

Thanks,

**Comment by roblourens** [comment]
This is an error from your app code. I don't know Angular well enough to debug it for you, sorry.
