### ISSUE TITLE
Wrong variable in debugger for 'this' scope

### ISSUE THREAD

**Issue by dehart** [microsoft/vscode-chrome-debug#804]
- VS Code Version: 1.33.0

Steps to reproduce:

1. Create a class `Test` with private function and a constructor like this:
```typescript
Class Test {
  constructor(element: HTMLFormElement) {
    element.addEventListener('change', this.onChange);
  }
  private onChange = (e: Event) => {
    console.warn(this);
  }
}
```
3. Set breakpoint on console.warn(this) line
4. Trigger the change event by changing a field in the passed HMTL form

Issue:
The Local `this` variable shown in the debugger will be the HTMLFormElement passed in the constructor. While this is actually an instance of the class itself.

In Chrome the debugger work correct. The "debug console" will also log the correct value.
![Screen Shot 2019-04-10 at 09 20 29](https://user-images.githubusercontent.com/3679323/55859246-f6b50000-5b71-11e9-9f8d-431bd6f8339a.png)
![Screen Shot 2019-04-10 at 09 22 21](https://user-images.githubusercontent.com/3679323/55859350-311e9d00-5b72-11e9-959d-c3beacae6e7c.png)

**Comment by Lazarencjusz** [comment]
I noticed same behavior @roblourens @dehart,  see my comment [here](https://github.com/microsoft/vscode-chrome-debug/issues/933#issuecomment-534406672). would it be taken under consideration as a bug?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-chrome-debug/issues/918
