### ISSUE TITLE
How to access & define key/value pairs for application's local storage

### ISSUE THREAD

**Issue by rbadapanda** [Microsoft/vscode-chrome-debug#806]
My application reads some key/value from localstorage during start.

Is there a way I can provide that with this extension?
or, 
can you please expose the developer tools instance of the browser that is embedded in VScode?

Anyway, thanks for the great tool!

**Comment by roblourens** [comment]
You are free to open the developer tools on the instance of Chrome that launches, or use the debug console to edit localStorage like `localStorage.set('foo', 'bar')`
