### ISSUE TITLE
Enhancement: Edge support

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/vscode-chrome-debug#812]
I was able to use this extension to debug in edge by just adding  `"runtimeExecutable": "C:/Program Files (x86)/Microsoft/Edge Dev/Application/msedge.exe"`. I was thinking if it is possible to extend this extension and just support `"type": "edge"` instead of specifying the runtimeExecutable? 

Although I haven't tested it extensively but basic debugging just works out of the box. Since the new edge is built upon chromium I guess this extension will run pretty good.

**Comment by roblourens** [comment]
This extension is just focused on Chrome but there is an extension for Edge: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge

**Comment by lafe** [comment]
@roblourens I think you closed this too soon without reading the description itself. This issue is related to the new Edge (aka Edgium) which is just another Chromium browser. I suspect that the extension for Edge is not compatible with the new Edge version.

**Comment by roblourens** [comment]
It is compatible with the new Edge, I worked with them to make that possible 😁 

https://twitter.com/MSEdgeDev/status/1116393650110386176
