### ISSUE TITLE
relative sourcemapurl in node_module not working

### ISSUE THREAD

**Issue by ajelcocks** [microsoft/vscode-chrome-debug#820]
I have two projects built using webpack and distributed to a local npm with the following structure

```
node_modules
    @abc/firstProject
        dist
            first.js
            first.js.map
        src
            first.js
```

dist/first.js contains `//# sourceMappingURL=first.js.map`
    which points to `{"version":3,"sources":["../src/first.js"]`

```
node_modules
    @abc/secondProject
        dist
            second.js
            second.js.map
        src
            second.js
```

dist/second.js contains `//# sourceMappingURL=second.js.map`
    which points to `{"version":3,"sources":["../src/second.js"]`

A third project has code which imports each as:
```
    import * as First from "@abc/firstProject/dist/first";
    import * as Second from "@abc/secondProject/dist/second";
```

Even though the mappings are relative ["../src/..."] the debugger does not resolve the maps unless I add sourceMapPathOverrides to the launch file.

Thats great, except they are both referenced as 
    webpack:///../src/*

Obviously it would be best if the relative addressing were used without the need for sourceMapPathOverrides but, given that does not seem to be the case...

can sourceMapPathOverrides accept an array?

Of course, this would brealk for like-named files in the different projects.
The only alternative I see is that each project uses a unique folder name rather than src, i.e. src/proj1 and src/proj2

One could argue that, since each project should have unit tests and have been tested in isolation, that there should be no need to step into them when debugging project 3 - but there are times when I need to.

Without the sourceMapPathOverrides the .scripts command shows:

```
webpack-internal:///./node_modules/@abc/firstProject/dist/first.js (c:\Users\[...absolute address...]\dist\first.js)
    - webpack:///../src/first.js?a2fd (..\src\first.js)
```

I am able to see the files and set breaks in Chrome Dev Tools, just not in VS Code.

What are my options? Has anyone else encountered this?

**Comment by roblourens** [comment]
Yes this is something that isn't currently really possible for us to handle. We will have to look at each `webpack://` fake source paths within the context of each node_modules project, instead of just interpeting them all in the same global context.

**Comment by connor4312** [comment]
This appears fixed in webpack 5. Creating a similar setup, webpack builds a recursive sourcemap where `webpack://./foo/first/dist/index.js` and `webpack://./foo/second/dist/index.js` references their own `index.js.map`s, in which we preserve context and are able to resolve correctly with the [new debugger](https://github.com/microsoft/vscode-js-debug/).
