### ISSUE TITLE
Simple Chrome Extension development: Unverified Breakpoint, "Breakpoint set but not yet bound"

### ISSUE THREAD

**Issue by LGFN** [microsoft/vscode-chrome-debug#835]
- Log file: [vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3153986/vscode-chrome-debug.txt)
- Extension source code: [Tally Counter.zip](https://github.com/microsoft/vscode-chrome-debug/files/3153989/Tally.Counter.zip)
- VS Code Version (text of About box): 
```
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
Please see attached source code for a very simple test Chrome extension (click on the popup to raise the number one at a time). Running it as it is doesn't hit any breakpoints for reason "Breakpoint set but not yet bound". Is there anything I need to change here to make sure breakpoints are hit? I couldn't figure out how to define `sourceMapPathOverrides` it should work, I read through the README, but I couldn't figure out how to make it work in this particular project.

Any help would be appreciated.

**Comment by roblourens** [comment]
Debugging chrome extensions isn't supported, and from what I understand, there are some issues preventing it from being configured to work. There are a few issues in this repo about it.

**Comment by LGFN** [comment]
Perhaps write that in the README and/or throw an error with the reason? I have been trying to figure this out for days until I decided to post it here.
