### ISSUE TITLE
Ability to break on specific exceptions

### ISSUE THREAD

**Issue by pjc2007** [microsoft/vscode-chrome-debug#838]
It would be great to be able to break on a specific exception type whenever it is raised, exactly like you can in C# in Visual Studio.

My specific case is debugging using the Cordova debugger for an Ionic/TypeScript project.  I believe it is mostly based of the Chrome debugger hence the feature request here.

**Comment by oparisy** [comment]
I would definitely have use for such a feature while debuging TypeScript.

My understanding is that this is indeed specific to each debugger integration extension, as per https://github.com/microsoft/vscode/issues/47149.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/104453 -- coming soon(tm)
