### ISSUE TITLE
Breakpoints are moved to invalide position

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode-chrome-debug#84]
I have TS project with source mapping enabled. I have noticed that some breakpoints are moved to incorrect location when set in source code.

Some observations:
- some breakpoints are set correctly but some are moved to invalide position even in the same source file
- I don't see any errors in diagnostic logging
- If I set breakpoint in js file, debugger is stops at the correct location in ts file, but setting breakpoint at the same position in ts will move it to invalide location
- I'm always able to step correctly through ts file

**Comment by iradul** [comment]
Related or dup with #48

**Comment by roblourens** [comment]
This looks the same as #48 which I haven't figured out yet. Thanks for the report.
