### ISSUE TITLE
Chrome Instance Quits When Stopping Debug

### ISSUE THREAD

**Issue by dill0wn** [microsoft/vscode-chrome-debug#841]
My launch.json looks like the following: 

```
{
  "type": "chrome",
  "request": "launch",
  "name": "Launch Chrome",
  "url": "http://localhost:8080",
  "webRoot": "${workspaceFolder}",
  "preLaunchTask": "typescript-compile"
}
```

Whenever I first launch a new debugging session, a new instance of chrome launches. If an instance already exists, then launching adds a new tab to the existing chrome instance window.

This is what I want.

My co-worker, with the exact same launch.json, and the exact same settings.json gets a slightly different result. Every time they stop a debug session, it quits the debug chrome instance.

How do you enable this feature to keep the chrome instance open?

Steps to reproduce:

1. Use the launch.json provided above
2. Launch debug
3. Stop debug
4. Voila - the debug chrome window either closes or does not close.

Thanks!

**Comment by roblourens** [comment]
It is actually supposed to kill the Chrome instance when using a "launch"-type config. If it doesn't, that is technically a bug although there have been issues with this in the past especially on Windows.

If you want a reliable way to have it not kill the window then you can use an "attach"-type config to attach to an already running instance, see the readme for some more details on that.

**Comment by dill0wn** [comment]
Thank you i will try attaching.
