### ISSUE TITLE
Launch configuration in user/workspace/folder settings.json

### ISSUE THREAD

**Issue by jaromero** [microsoft/vscode-chrome-debug#842]
The Firefox debug adapter extension can use [user, workspace or folder settings](https://github.com/hbenl/vscode-firefox-debug#overriding-configuration-properties-in-your-settings) for its own options.

This helps me e.g. in the case where some of my coworkers (who all use Linux) have their Chrome executable in a different place, whether it's due to distro/packaging differences, or because they're using Chromium instead, or because they want a different profile dir, etc. and we're able to keep those settings outside of our `.vscode/launch.json` file which we keep in VCS.

For example, `.vscode/launch.json` in our repository might have this content:

~~~json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "firefox",
      "request": "launch",
      "name": "Launch Firefox",
      "url": "http://localhost:3001",
      "reAttach": true,
      "webRoot": "${workspaceFolder}/src",
      "pathMappings": [
        {
          "url": "webpack:///src/",
          "path": "${webRoot}"
        },
        {
          "url": "webpack-internal://./src/",
          "path": "${webRoot}"
        }
      ]
    }
  ]
}
~~~

And in my personal `settings.json`:

~~~json
{
  // ... etc.
  "firefox.executable": "/home/ar/.local/lib/firefox/firefox", // Firefox Nightly
  "firefox.profile": "debug",
  "firefox.args": [
    "--no-remote",
    "--start-debugger-server"
  ]
}
~~~

Someone else may have:

~~~json
{
  // ...
  "firefox.executable": "/home/user/src/firefox/firefox", // Local build of Firefox source
  "firefox.profile": "frontend-debug",
  "firefox.args": [
    "--start-debugger-server",
    "--devtools"
  ],
  "firefox.keepProfileChanges": true
}
~~~

etc.

Is there a way to achieve something similar with this extension (Debugger for Chrome)?

**Comment by roblourens** [comment]
I don't have anything exactly the same but here is what we recommend in general for keeping private launch configs: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-launch-configurations

In short,

- Create a workspace with your folder if you don't have one already (e.g. run "Duplicate Workspace in New Window")
- Edit the launch configuration to the workspace config file (run "Open workspace configuration file")
- Add a launch configuration to it under "launch"

Then you can keep your private launch config here without checking it in
