### ISSUE TITLE
Start chrome with the --remote-debugging-pipe argument

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode-chrome-debug#844]
Spawning a chrome process with the `--remote-debugging-port=<port>` is discouraged, starting it with the `--remote-debugging-pipe` is preferred since it allows secure communication with the browser and works around the port conflict scenarios.

Pipes `3` and `4` are used to write and read respectively. See how Puppeteer [launches](https://github.com/GoogleChrome/puppeteer/blob/2b68c104aaf309488fe710a0dd7127369373d5fb/lib/Launcher.js#L174) chrome with the [pipe](https://github.com/GoogleChrome/puppeteer/blob/master/lib/PipeTransport.js) transport.

Note that pipe exposes the `browser` endpoint and connections to the pages need to be established using the [`Target`](https://vanilla.aslushnikov.com/?Target) domain. Please use `flatten` communication style when attaching to the pages.

**Comment by connor4312** [comment]
This is now done with js-debug
