### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by radar66** [microsoft/vscode-chrome-debug#847]
- Issue Type: `Performance`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.11.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\HP\msjsdiag.debugger-for-chrome-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by roblourens** [comment]
You didn't attach the profile file
