### ISSUE TITLE
webRoot ignored with static assets

### ISSUE THREAD

**Issue by adelphes** [microsoft/vscode-chrome-debug#849]
- VS Code Version:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-15-generic

There appears to a lot of issues about breakpoints not being enabled, sourceMap/webRoot config, etc, so I may be missing something, but I'd like to understand what's happening here.

I'm attempting to debug a plain `app.js` script loaded from a static folder - no transpiling and no sourceMaps.
I launch a webserver pointing to the folder and the page loads correctly in Chrome. I then try to attach the Chrome Debugger using the following config:

```
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "url": "http://localhost:3101/my-app/test",
            "webRoot": "${workspaceFolder}/public",
            "trace": "verbose"
        }
```
(`workspaceFolder` = `/home/dave/dev/project/static-spa`)

It should be noted that the app is a SPA - all URLs redirect to the same `index.html` and `app.js` located in the `${workspaceFolder}/public` folder.
Trying to set breakpoints with this config fails - with the trace log showing this:
```
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in VM31
SourceMap: creating for VM31
SourceMap: sourceRoot: undefined
SourceMap: sources: ["app.js"]
SourceMap: pathMapping: {"/":"/home/dave/dev/project/static-spa/public"}
SourceMap: no sourceRoot specified, using webRoot + script path dirname: 
SourceMaps.scriptParsed: VM31 was just loaded and has mapped sources: ["/home/dave/app.js"]
```

If I execute `.scripts` in the console, I can see the same incorrect mapping to my home folder:
```
› VM31
    - app.js (/home/dave/app.js)
› VM39
› VM40
....
```

My question is why is it using my home folder and not `webRoot` for the base folder?
This is particularly confusing, given the log line: **`SourceMap: no sourceRoot specified, using webRoot + script path dirname: `**

If I set a `sourceMapOverrides` entry with `app.js` pointing to `webRoot`, it works...
```
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "sourceMapPathOverrides": {
                "app.js": "${webRoot}/app.js"
            },
            "url": "http://localhost:3101/my-app/test",
            "webRoot": "${workspaceFolder}/public",
            "trace": "verbose"
        }

SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in VM31
SourceMap: creating for VM31
SourceMap: sourceRoot: undefined
SourceMap: sources: ["app.js"]
SourceMap: pathMapping: {"/":"/home/dave/dev/project/static-spa/public/public"}
SourceMap: no sourceRoot specified, using webRoot + script path dirname: 
SourceMap: mapping app.js => /home/dave/dev/project/static-spa/public/app.js, via sourceMapPathOverrides entry - "app.js": "/home/dave/dev/project/static-spa/public/app.js"
SourceMaps.scriptParsed: VM31 was just loaded and has mapped sources: ["/home/dave/dev/project/static-spa/public/app.js"]
```
Naturally, it would be nice if just setting `webRoot` would actually cause the script to be mapped to the correct folder instead of needing to also set `sourceMapPathOverrides` to point to the same folder, but perhaps I'm misunderstanding what `webRoot` is actually used for.

**Comment by roblourens** [comment]
app.js is from a dynamic (eval'd) script which doesn't have a path, so webRoot doesn't apply. Fixing this with sourceMapPathOverrides is the right fix for now. Looking at the webRoot for dynamic scripts would probably be the right thing to do.

**Comment by connor4312** [comment]
We've since moved a new debugger in VS Code, and from what you've said I don't _think_ this bad code path would be taken there. If you're still having this issue in recent VS Code releases, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
