### ISSUE TITLE
Can't adjust zoom of preview without adjusting font size

### ISSUE THREAD

**Issue by ibdf** [microsoft/vscode-chrome-debug#851]
- VS Code Version: Version 1.34.0 (1.34.0)
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Open browser preview
2. press Command plus "-" or "+" on a mac

This command typically let's you control the browser zoom. In VS Code this command also controls the Font Size. So I can't control one without controlling the other. It also seems like the browser preview is matching the font size, which is an issue because I use a large font size, and don't necessarily need a zoomed in preview.

**Comment by auchenberg** [comment]
This sound like an issue for https://github.com/auchenberg/vscode-browser-preview/

**Comment by ibdf** [comment]
You are correct. I had both git repos opened and I posted under the wrong one. Sorry about that.
