### ISSUE TITLE
 I can only start part of the workbench.

### ISSUE THREAD

**Issue by Dr-Harris** [microsoft/vscode-chrome-debug#856]
- VS Code Version: 1.35.0
Steps to reproduce:

1. Install  `debug for chrome` and Select `Launch VS Code` ,then `f5`
2.I only got incomplete workbench.

![image](https://user-images.githubusercontent.com/22830171/59177551-0612f280-8b8f-11e9-9461-7fc8097965d8.png)

The purple vscode instance is not fully started

**Comment by Dr-Harris** [comment]
I want to debug vscode source code through vscode,Is this not the right question to ask here?

**Comment by roblourens** [comment]
Are there errors in the debug console?

Does it start up correctly if you run `scripts/code.bat`?

Most likely vscode is not built correctly. Make sure that you have followed all the steps in https://github.com/microsoft/vscode/wiki/How-to-Contribute without errors

**Comment by Dr-Harris** [comment]
There isn't any errors in the debug console,and it can start up correctly when I run `scripts/code.bat`.
This problem only occurs when I debug with vscode, and it happens occasionally.

**Comment by roblourens** [comment]
Can you start with logging enabled (`"trace": true` in the launch config) and share the log?

**Comment by Dr-Harris** [comment]
Is this the file?
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3279164/vscode-chrome-debug.txt)
![image](https://user-images.githubusercontent.com/22830171/59317209-7edf8f00-8cf4-11e9-859f-7b7ce8e6d517.png)

**Comment by Dr-Harris** [comment]
Is this the file?
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3279167/vscode-chrome-debug.txt)
![image](https://user-images.githubusercontent.com/22830171/59317300-d7af2780-8cf4-11e9-8366-d58ed7697be9.png)

**Comment by roblourens** [comment]
Sorry, I have no idea what the problem is. The log looks like it started successfully. You can try launching it yourself with the `--remote-debugging-port=9222` flag, then run the "Attach to VS Code" config instead.

**Comment by Dr-Harris** [comment]
Okay, thank you all the same.
