### ISSUE TITLE
Python call stack is not viewable or accessible when launching debugWithChrome

### ISSUE THREAD

**Issue by brianjsw** [microsoft/vscode-chrome-debug#857]
Very possible user error here, and I'm not sure where the problem resides.  The problem could be in either the Chrome Debugging or Python Extension.

I am unable to view my python call stack when my python program is paused on a breakpoint.  This problem happens only when I launch using a serverReadyAction of debugWithChrome (aka: activating Chrome Debugging Tools for VS Code), and in fact, if I stop the Chrome debugger, the Python call stack suddenly becomes accessible again.  

I don't see a way to switch contexts (between Chrome and Python) short of what one would normally do (click on the entry in the tree view).  A screen shot is provided below which demonstrates the empty Python call stack.

![2019-06-10_16-09-30](https://user-images.githubusercontent.com/245758/59228104-999ef000-8b9c-11e9-85de-f17f5dd40d31.png)

After I kill the Chrome Debugger, the call stack starts to display.  See below:

![2019-06-10_16-28-25](https://user-images.githubusercontent.com/245758/59228222-ebe01100-8b9c-11e9-8d12-27bb25338741.png)

- VS Code Version:1.35.0
- Log file (uncertain how to turn on trace flag (I am using a different flavor of launch config, see below)

{
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "internalConsole",
            "args": [
                "runserver",
                "devpos-local:8123",
                "--noreload",
                "--nothreading"
            ],
            "django": true,
            "serverReadyAction": {
                "pattern": "Quit the server with CONTROL-C.",
                "uriFormat": "http://devpos-local:8123",
                **"action": "debugWithChrome",**
            },
            "envFile": "${workspaceFolder}/.environments/local"
        }

Steps to reproduce:

1. Set a breakpoint in Python code
2. Run a Python program with an associated serverReadyAction that invokes the 'debugWithChrome' action.
3. Notice that when the Python breakpoint is hit, the call stack is not accessible or viewable.
4. Stopping the Chrome Debug session causes the Python call stack to start working again.

**Comment by roblourens** [comment]
@weinand do you know what's happening here? Is this a `serverReadyAction` issue?

**Comment by connor4312** [comment]
I made a change with js-debug so that the browser debug session is not a child of whatever parent, so this case should not happen (and this year there has been much refinement of nested call sessions as we've used in it js), thus closing. Let us know if you run into more issues.
