### ISSUE TITLE
Remote VS Code Extension - Container - Unverified Breakpoint

### ISSUE THREAD

**Issue by razilevin** [microsoft/vscode-chrome-debug#861]
- VS Code Version: 1.36.0-insider
- Log file (set `"trace": true` in launch config): https://gist.github.com/razilevin/d414e9cde09054e0c5953da644b76efc

Trying to use the Remote VS  Code Extension to create a Angular application and trying to use the Google chrome Debugger Extension in UI installed environment. I try to set breakpoints in the TS files only to notice that when I start the debugging session the breakpoints enter the unverified state. I did notice that there were some like issues raised earlier that have been closed so this can still be a regression or there is something I am not doing correctly. I really do not understand how the sourceMapPathOverrides property works so that can be my source of confusion. Note that setting the breakpoints in Google chrome correctly sets the breakpoint in Visual Studio Code. 

Attached to the gist above:
1. Output of .scripts debug command
2. Output of trace of logging session
3. launch.json used to start debugging session

Steps to reproduce:

1. Open project via Remote-Containers: ReOpen  Folder In Container
2. Try to set breakpoint in any source file.
3. Begin Debug Session - Breakpoints are not verified

**Comment by roblourens** [comment]
Thanks for trying this out, debugging with Chrome in a remote window is new. I think I see the issue.

**Comment by roblourens** [comment]
Please try again with version 4.11.5.

**Comment by razilevin** [comment]
Still does not work. Upgraded to 4.11.5. What am I missing? Really simple to reproduce I can send you my .devcontainer contents so you can replicate in your testing environment. Pasted contents of Extension info so you can be sure I updated the extension.

Name: Debugger for Chrome
Id: msjsdiag.debugger-for-chrome
Description: Debug your JavaScript code in the Chrome browser, or any other target that supports the Chrome Debugger protocol.
Version: 4.11.5
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome

**Comment by roblourens** [comment]
Yep, thanks for updating. Can you share the log again with this new version?

**Comment by razilevin** [comment]
Gist Chrome Debugger Log:  https://gist.github.com/razilevin/56faa07a2bd95207b8dc4e05a84ed49a

**Comment by RyanEwen** [comment]
I think I have the same or similar issue using remote+ssh

What's interesting is that I can put `debugger` into my source code and it will open a 2nd copy of the file when hit, rather than the actual source file. 

I'm not using source maps or anything fancy. Apache server, serving static files.

Log https://gist.github.com/RyanEwen/f98d01e731364494768cd99bb5668043

**Comment by RyanEwen** [comment]
Through some trial and error based on info in the log I was able to get this working in my case. 

My workspace is `/var/www/html/rewen` and I had been using the default `webRoot`, but I found in the log that it was doubling up part of the path (`rewen/rewen`). I grabbed the URI from the log before `rewen` and used it as my `webRoot` which appears to work.

```
            "url": "http://localhost:8000/rewen/test.html",
            "webRoot": "/__vscode-remote-uri__/var/www/html/",
```

Not sure if this helps you fix the issue or if it helps the OP work around the issue.. it seems like it may have been a different problem in my case due to my site being nested within a subdir?

**Comment by roblourens** [comment]
@RyanEwen Possibly you actually just need `"webRoot": "${workspaceRoot}/var/www/html/`

@razilevin Thanks, there's another issue, this doesn't work when my default webpack mapping patterns are applied. Try copying them into your launch config:

```json
"sourceMapPathOverrides": {
  "webpack:///./~/*": "${workspaceRoot}/node_modules/*",
  "webpack:///./*": "${workspaceRoot}/*",
  "webpack:///*": "*",
  "webpack:///src/*": "${workspaceRoot}/*",
```

Even with that, you may also see this issue: https://github.com/microsoft/vscode-remote-release/issues/840#issuecomment-506098934

**Comment by RyanEwen** [comment]
`"webRoot": "${workspaceRoot}/var/www/html/` seems to be a no go but thanks for the suggestion.

**Comment by roblourens** [comment]
Actually @razilevin what is your value for `webRoot`? Is it just an absolute path? It will need to be defined with `${workspaceFolder}`. I can't decide whether that's something I can work around or not.

The log only shows the value of webRoot after variables have been resolved so I can't see your raw launch config.

**Comment by razilevin** [comment]
Ok I tried to play with the **webRoot** attribute. I really don't understand how it works to so I brute forced the values. Please note that the absolute value of the project in the docker container is 

> /workspaces/angular-remote/dnd/src

My webRoot setting is 

> ${workspaceFolder}

It appears in the log that the paths are correct minus the magic prefix of __vscode-remote-uri__ 

> [00:24:10.104 UTC] From client: setBreakpoints({"source":{"name":"main.ts","path":"vscode-remote://dev-container%2B2f686f6d652f726c2f70726f6a656374732f616e67756c61722d72656d6f7465/workspaces/angular-remote/dnd/src/main.ts"},"lines":[7],"bre     akpoints":[{"line":7}],"sourceModified":false})
  69 [00:24:10.105 UTC] remoteMapper: mapping remote uri vscode-remote://dev-container%2B2f686f6d652f726c2f70726f6a656374732f616e67756c61722d72656d6f7465/workspaces/angular-remote/dnd/src/main.ts to internal path: /__vscode-remote-uri__/workspaces/angular-remote/dnd/src/main.ts
  70 [00:24:10.105 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"Versions.DebugAdapterCore":"6.7.50","Versions.DebugAdapter":"4.11.5","Versions.Target.CRDPVersio     n":"1.3","Versions.Target.Revision":"@cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0","Versions.Target.UserAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36","Versions.Target.V8":"7.     5.288.23","Versions.Target.Project":"Chrome","Versions.Target.Version":"75.0.3770.100","fileExt":".ts"}}}
  71 [00:24:10.106 UTC] SourceMaps.setBP: /__vscode-remote-uri__/workspaces/angular-remote/dnd/src/main.ts can't be resolved to a loaded script. It may just not be loaded yet.

**Comment by roblourens** [comment]
Oh ok, currently we are not doing the right thing for workspaceFolder, just workspaceRoot. You can try replacing that to see if it works. I am fixing that. https://github.com/microsoft/vscode-remote-release/issues/840#issuecomment-506098934

**Comment by roblourens** [comment]
Note to self, in short the actual issue remaining is

> This will work for relative paths in sourcemaps like `webpack:///./*` but not absolute ones like `webpack:///*`. I need to change the way remote paths are handled to account for this.

**Comment by pierreyves-lebrun** [comment]
Is there an ETA for any fix on that issue?

I tried many different settings but eventually the only way I could get breakpoints to work in a VSCode container is to set them in the Chrome console.

It would be absolutely awesome if VSCode could fully support them in the case of remote containers.

**Comment by NilsNiBe** [comment]
As @pierreyves-lebrun already said, it's possible to hit a debug breakpoint by setting it in the browser.

Though only the copy of the file is opened in VSCode. I noticed the file path is displayed as a windows path "workspaces\devcontainer\src\App.tsx" and readonly. The oringal file inside the linux container still shows unverified breakpoints und won't be opened for debugging.

**Comment by CristoAMH** [comment]
@NilsNiBe Did you find a solution? I am fighting the same problem.

**Comment by NilsNiBe** [comment]
@CristoAMH Unfortunately not. But I haven't tryed since.

**Comment by sebastianspross** [comment]
I am still experiencing the same. Setting the breakpoint in chrome is working but not in vscode. Is there progress or anything I can do as a workaround?

**Comment by connor4312** [comment]
Thanks for the issue!

We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/) if you continue to run into issues.
