### ISSUE TITLE
[Question] Is there a way to run the chrome debugger for react, whilst proxying network requests to a different port?

### ISSUE THREAD

**Issue by Darruma** [microsoft/vscode-chrome-debug#863]
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}",
        }
    ]
}
```

I am using the default launch.json and I was wondering If i could proxy the network requests from the application to a different port , like localhost:6000.

**Comment by roblourens** [comment]
I'm not really sure what you are referring to. Network requests from your app? The extension doesn't provide any capability for that, you will have to figure out how to set it up yourself.

**Comment by Darruma** [comment]
@roblourens The network requests would come from some server running on a different port. You can put a proxy in the package.json file and it will proxy network requests, but it doesn't seem to work with the chrome debugger

**Comment by roblourens** [comment]
If you can explain some more or provide a working example repo then I can investigate, but this extension doesn't really do anything differently with the inside of your app, and this just sounds like an issue with your app.
