### ISSUE TITLE
Problem with Laravel and breakpoint

### ISSUE THREAD

**Issue by lucabecchetti** [microsoft/vscode-chrome-debug#865]
- VS Code Version: Last version

I have debug configured like this:

`{
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "https://mydomain.test",
            "webRoot": "${workspaceFolder}",
            "breakOnLoad": true,
            "sourceMaps": true
            /*"sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*"
            }*/
        }`

My installation is laravel, all vue files are in folder /resources/js/components, than laravel mix compile all and place in public/js/app.js, the problem is that if i place a breakpoint inside a .vue files, debuuger open compiled app.js whats wrong?

**Comment by roblourens** [comment]
What is the output of `.scripts` in the debug console? You may need some adjustment to your sourceMapPathOverrides.

**Comment by lucabecchetti** [comment]
.scripts output:

› VM18
› VM19
› VM20
› VM21
› VM34
› VM35
› https://hosts.mysite.test/become_host
› https://hosts.mysite.test/js/app.js
› https://js.stripe.com/v3
› https://use.typekit.net/hoy3lrg.js


my structure is:

/resources/js/compontents:  contail all .vue files

when i run npm run dev all files are compiled into

/public/js/app.js
