### ISSUE TITLE
Breakpoint moved when start debugging

### ISSUE THREAD

**Issue by lucabecchetti** [microsoft/vscode-chrome-debug#866]
Hi guys, I'm trying to debug a laravel + vue application, but when i attach debugger i have this problem on ".vue" files:

![errore](https://user-images.githubusercontent.com/16253548/60335030-27504d00-999d-11e9-966f-4e542ef0603f.gif)

This is my configuration:

launch.json:

{
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "https://hosts.site.test",
            "breakOnLoad": true,
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}",
            "sourceMapPathOverrides": {
                "webpack:///./resources/js/components/*.vue": "${webRoot}/resources/js/components/*.vue",
                "webpack:///./resources/js/components/*.js": "${webRoot}/resources/js/components/*.js",
                "webpack:///./resources/js/*.js": "${webRoot}/resources/js/*.js",
                "webpack:///./node_modules/*": "${webRoot}/node_modules/*"
            }
        },
        
.scripts output:

› VM18
› VM19
› VM20
› VM21
› VM34
› VM35
› https://hosts.mysite.test/become_host
› https://hosts.mysite.test/js/app.js
› https://js.stripe.com/v3
› https://use.typekit.net/hoy3lrg.js

my files structure is:

/resources/js/compontents: contail all .vue and .js files

when i run npm run dev all files are compiled into

/public/js/app.js

Any help? Thanks!

**Comment by lucabecchetti** [comment]
up

**Comment by roblourens** [comment]
Most likely a sourcemap issue. Does it work in chrome devtools? Check the `devtool` setting in your webpack config.

**Comment by lucabecchetti** [comment]
Ok, with this configuration it works:

"webRoot": "${workspaceFolder}/public",
            "sourceMapPathOverrides": {
                "webpack:///resources/js/components/*.vue": "${workspaceFolder}/js/omponents/*.vue",
                "webpack:///./resources/js/components/*.js": "${workspaceFolder}/js/components/*.js",
                "webpack:///./node_modules/*": "${workspaceFolder}/node_modules/*"
            }

i'm able to break on .js files, .vue file with javascript, .ts files, but we can't break on a .vue files containing typescript, any ideas?

**Comment by roblourens** [comment]
Typo? `omponents`
