### ISSUE TITLE
Mac dock icon does not deleted when debug stop.

### ISSUE THREAD

**Issue by engnakagawa** [microsoft/vscode-chrome-debug#872]
- VS Code Version: 1.35.1(1.35.1)
- Debugger for Chrome: 4.11.6
- macOS Mojave

Steps to reproduce:

1. Create Launch Chrome configuration.
2. Debug Start.
3. New Chrome Window is opened. (added dock icon)
4. Close New Chrome window(cmd + q) or Debug Stop
5. New Chrome Window is closed, but dock icon does not deleted.

I expect dock icon is deleted when [close new chrome window] or [debug stop].

**Comment by roblourens** [comment]
> but dock icon does not deleted

Not sure what you mean? MacOS does now have a section for "recently used" apps and Chrome will stay there even when it is closed, if that's what you mean.

**Comment by engnakagawa** [comment]
@roblourens 

Hello :)

Please look this.

<img width="1165" alt="スクリーンショット 2019-07-04 19 32 23" src="https://user-images.githubusercontent.com/32351802/60660364-97297080-9e92-11e9-9373-6c5b58289025.png">

Leftmost chrome icon is I added manualy, and Everyday use.(please do not worry)
But, Other chrome icons is added by Debugger for Chrome, and These are Endlessly increasing( Every time debug start/stop).
And, added chrome icon can not launch chrome app.

Is this really desirable?

**Comment by roblourens** [comment]
This is an issue with macOS, the extension does not control what happens with dock icons. Sorry, I don't know what the issue is.
