### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nil4587** [microsoft/vscode-chrome-debug#877]
- Issue Type: `Performance`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.11.6`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.36.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/nileshprajapati/msjsdiag.debugger-for-chrome-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by roblourens** [comment]
Please attach the file like the message asks for, otherwise I can't do anything
