### ISSUE TITLE
[Question] Disable loading of files in devtools "Sources" tab

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode-chrome-debug#879]
latest of everything:
vscode 1.36.0
extension 4.11.6

The extension works and I can debug an angular app.

But on load, when the devtools are open, the browser switches to the "Sources" tab, and then loads lots of files. This takes time and slows down everything. Files like "polyfill.js", "promisify.js", "msg.js", "prefs.js", "page.js", and lots more.

This happens
- when I refresh the page
- the debugging session starts
- I save in vscode, and that triggers a reload

Is this normal? Is there a way to stop it? I don't need those files opened, as I do the debugging in vscode rather than the browser. And it slows my work.

**Comment by roblourens** [comment]
No, there is no way for us to control what happens in chrome devtools unfortunately

**Comment by lonix1** [comment]
OK thanks.

Is that normal behavior though?

**Comment by roblourens** [comment]
I think that chrome devtools will persist your open files and last open tab from the last session.
