### ISSUE TITLE
\ in paths in sourcemaps aren't handled properly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug#88]
Sourcemaps on Windows can be built with \, but the source-map library requires /. Apparently gulp-sourcemaps can still produce / because it's been working in my test app.

**Comment by felixfbecker** [comment]
Didn't we come to the conclusion that a source map URL is always a file URL? In that case backslashes are not valid

**Comment by roblourens** [comment]
Fixed in v0.2.3
