### ISSUE TITLE
debug.chrome.runtimeExecutables is an unknown configuration setting

### ISSUE THREAD

**Issue by ChildishGiant** [microsoft/vscode-chrome-debug#880]
- VS Code Version: 1.36.0
- Extension Version: 4.11.6

![image](https://user-images.githubusercontent.com/13716824/60762087-cfc27900-a04f-11e9-89d6-daa090a7bb8c.png)

I imagine this has just been moved to another name but I can't find it.

**Comment by roblourens** [comment]
That is not a setting. Maybe you are trying to set `runtimeExecutable` in your launch config? Otherwise I am not sure what you are trying to do

**Comment by ChildishGiant** [comment]
Oh, I got it from [this comment](https://github.com/microsoft/vscode-chrome-debug/issues/532#issuecomment-360965152). Is the only way to set it in the launch config? I'd prefer to have it set in my settings as I'll be using the same executable for every project.

**Comment by roblourens** [comment]
That is just a suggestion from a user. I disagree, I think it would be too confusing to have to look in multiple locations to see your launch config values.

**Comment by ChildishGiant** [comment]
Ah sorry about that
