### ISSUE TITLE
How to use debugWithChrome serverReadyAction with Remote - WSL extension?

### ISSUE THREAD

**Issue by justinneff** [microsoft/vscode-chrome-debug#892]
- VS Code Version: 1.36.1
- Extension Version: 4.11.6
- OS: Window 10
- WSL: Ubuntu 16.04.6 LTS

I am migrating from using the deprecated `useWSL` option in `launch.json` to using the Remote - WSL extension. We are using the `debugWithChrome` with the `serverReadyAction` to launch chrome once the app is finished starting up. For reference this is what my launch configuration looks like:

```
{
      "type": "node",
      "request": "launch",
      "name": "Manager",
      "cwd": "${workspaceFolder}/web/manager",
      "env": {
        "MANAGER_DEBUG_PORT": "9300",
        "MANAGER_HTTP_PORT": "3000"
      },
      "runtimeExecutable": "yarn",
      "runtimeArgs": ["dev"],
      "port": 9300,
      "console": "internalConsole",
      "sourceMapPathOverrides": {
        "webpack:///${workspaceFolder}/node_modules/@my-project/*": "${workspaceFolder}/packages/*",
        "webpack:///./*": "${workspaceFolder}/web/manager/*",
        "webpack:///*": "*"
      },
      "serverReadyAction": {
        "action": "debugWithChrome",
        "pattern": "ready on http://localhost:([0-9]+)",
        "uriFormat": "http://localhost:%s/tours",
        "webRoot": "${workspaceFolder}/web/manager"
      }
    }
```

When running in the Remote - WSL environment, the `debugWithChrome` action fails launch with the following error message: 

`The action 'debugWithChrome' requires the 'Debugger for Chrome' extensions.`

The Debugger for Chrome extension does not give the option to Install on WSL. Is this configuration supported?

**Comment by roblourens** [comment]
It shouldn't be needed to be installed in WSL, it should work with the debugger as a "UI" extension. @weinand

**Comment by weinand** [comment]
My existence-check for the Debugger for Chrome uses the `getExtensions` API which does not return extensions running "on the other side" (UI extensions). This is a known limitation of our API.

As a workaround I've excluded WSL from this check.

**Comment by weinand** [comment]
@justinneff if possible, please verify the workaround in the next Insiders.

**Comment by justinneff** [comment]
I have verified on today's Insiders build and the workaround does the trick for me. Thanks, @weinand for you help on this.

**Comment by weinand** [comment]
@justinneff you're welcome
