### ISSUE TITLE
Remote sessions apply invalid source map override on WSL with "ui" extension

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/vscode-chrome-debug#899]
- Issue Type: `Bug`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.11.6`
- OS Version: `Windows_NT x64 10.0.18945`
- VSCode version: `1.36.1`

So, here's the `launch.json`. I'm using: https://github.com/clshortfuse/materialdesignweb/blob/175f3e7c4d04c9ebf52f84473183c6262e064181/.vscode/launch.json

The second configuration works perfectly fine on WSLv1 when using the extension in "workspace" mode. On WSL, it will call the chrome executable over `/mnt/c/`. The mapping are "local" and relative to the WSL environment. (Namely: `/home/carlos/projects/materialdesignweb/`).

I've since upgraded to WSLv2, which does not support WSL => Windows when using `localhost`. That means `ws://localhost:9222` isn't resolved, and thus, means I must use the extension in "ui" mode.

This would be the first configuration in the `launch.json` file. The problem is that files are mapped as `\__vscode-remote-uri__\home\carlos\projects\materialdesignweb\` which doesn't actually open my workspace files. I've also noticed that they would actually open the source code of the file that's included in the sourcemap, not the actual file in the workspace. That's because I normally use `nosources-source-map`, which is just has a reference to the source file. When using that, VSCode says it can't find the file. When I use `source-map`, then "finds" the file, but as I said before, I imagine that it's pulling it from the sourcemap.

So, right now I have a working configuration with "workspace" mode with no issues but can't work on WSLv2, and the "ui" based one which I would like to get working so I can use WSLv2. UI mode isn't working for me either on WSLv1.

I added a `console.log()` in `/docs-src/prerender.js` and ran three trace files:

`uimode-nosources-source-map.txt`:
* VSCode maps output to minified filename `\__vscode-remote-uri__\home\carlos\projects\materialdesignweb\docs-src\prerender.min.js` that can't be opened

`uimode-source-map.txt`:
* VSCode maps output to correct filename and path, but in `\__vscode-remote-uri__\home\carlos\projects\materialdesignweb\docs-src\prerender.js`, which isn't the workspace file (I assume from source-map).

`workspacemode-nosources-source-map.txt`:
* VSCode maps to workspace folder correctly to `/home/carlos/projects/materialdesignweb/docs-src/prerender.js`

`workspacemode-source-map.txt`:
* VSCode maps to workspace folder correctly to `/home/carlos/projects/materialdesignweb/docs-src/prerender.js`

I also noticed that ui-mode is using `\` instead of `/`. That may be the problem, but I'm not entirely sure. If it is, it could be related to this commit https://github.com/microsoft/vscode-chrome-debug-core/commit/2bfcdc020699fee737ddc5e1d445af105ffedcd2 by @roblourens 

Perhaps it has to be `/__vscode-remote-uri__/*` because it's an internal URL understood by VSCode and not an actual path. Therefore, `path.posix` should be used instead here. 

I would have tried it myself, but I honestly don't know how to modify the source code of the extension from within VSCode. If you need me to pull up some more traces, or need more info, I'll be glad to help.

-----

[uimode-nosources-source-map.txt](https://github.com/microsoft/vscode-chrome-debug/files/3439672/uimode-nosources-source-map.txt)
[uimode-source-map.txt](https://github.com/microsoft/vscode-chrome-debug/files/3439673/uimode-source-map.txt)
[workspacemode-nosources-source-map.txt](https://github.com/microsoft/vscode-chrome-debug/files/3439674/workspacemode-nosources-source-map.txt)
[workspacemode-source-map.txt](https://github.com/microsoft/vscode-chrome-debug/files/3439675/workspacemode-source-map.txt)

**Comment by clshortfuse** [comment]
@roblourens Thanks, but it's still not completely fixed. It does now properly convert `/__vscode-remote-uri__` to `vscode-remote://wsl%2Bdefault/`.

But it doesn't map minified files because `baseSourceMapTransformer.fixSourceLocation` will only remap to local files because its dependency on `fs.stat`. Since the file isn't local and thus not reachable, the debugger leaves the file reference as is, which links to non-existent files (constructed by webpack).

I added some more debug lines to walk through the code and here's the relevant part:

````
onConsoleAPICalled: {"type":"log","args":[{"type":"string","value":"hello"}],"executionContextId":2,"timestamp":1568653288683.0771,"stackTrace":{"callFrames":[{"functionName":"./prerender.js","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":447,"columnNumber":8},{"functionName":"__webpack_require__","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":19,"columnNumber":29},{"functionName":"3","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":459,"columnNumber":17},{"functionName":"__webpack_require__","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":19,"columnNumber":29},{"functionName":"","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":83,"columnNumber":17},{"functionName":"","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":86,"columnNumber":9}]}}
logObjects - mapCallFrame: {"functionName":"./prerender.js","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":447,"columnNumber":8}
mapCallFrame - frame: {"functionName":"./prerender.js","scriptId":"14","url":"http://localhost:8080/prerender.min.js","lineNumber":447,"columnNumber":8}
mapCallFrame - debuggerCF: {"location":{"lineNumber":447,"columnNumber":8,"scriptId":"14"},"url":"http://localhost:8080/prerender.min.js","functionName":"./prerender.js"}
mapCallFrame - stackFrame: {"id":1000,"name":"./prerender.js","source":{"name":"prerender.min.js","path":"http://localhost:8080/prerender.min.js","sourceReference":1001},"line":447,"column":8}
mapCallFrame - stackFrame (pathTransformer.fixSource): {"id":1000,"name":"./prerender.js","source":{"name":"prerender.min.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js"},"line":447,"column":8}
SourceMap: creating for /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js
SourceMap: sourceRoot: 
SourceMap: sources: ["webpack:///webpack/bootstrap","webpack:///../core/document/index.js","webpack:///./_menuoptions.js","webpack:///./_storage.js","webpack:///./prerender.js"]
SourceMap: pathMapping: {"/":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src"}
SourceMap: getComputedSourceRoot  -> /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js
SourceMap: no sourceRoot specified, using script dirname: /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src
SourceMap: mapping webpack:///webpack/bootstrap => /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/webpack/bootstrap, via sourceMapPathOverrides entry - "webpack:///*": "/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/*"
SourceMap: mapping webpack:///../core/document/index.js => /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/core/document/index.js, via sourceMapPathOverrides entry - "webpack:///*": "/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/*"
SourceMap: mapping webpack:///./_menuoptions.js => /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/_menuoptions.js, via sourceMapPathOverrides entry - "webpack:///*": "/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/*"
SourceMap: mapping webpack:///./_storage.js => /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/_storage.js, via sourceMapPathOverrides entry - "webpack:///*": "/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/*"
SourceMap: mapping webpack:///./prerender.js => /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js, via sourceMapPathOverrides entry - "webpack:///*": "/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/*"
SourceMaps.scriptParsed: /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js was just loaded and has mapped sources: ["/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/webpack/bootstrap","/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/core/document/index.js","/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/_menuoptions.js","/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/_storage.js","/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js"]
SourceMaps.scriptParsed: prerender.min.js.map
fixSourceLocation - mapped: {"source":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js","line":16,"column":8,"name":"log"}
fixSourceLocation: Script IS mapped, but does NOT exist on disk: /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js
mapCallFrame - stackFrame (sourceMapTransformer.fixSourceLocation): {"id":1000,"name":"./prerender.js","source":{"name":"prerender.min.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js"},"line":447,"column":8}
mapCallFrame - stackFrame (lineColTransformer.convertDebuggerLocationToClient): {"id":1000,"name":"./prerender.js","source":{"name":"prerender.min.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js"},"line":448,"column":9}
logObjects: - newStackFrame {"id":1000,"name":"./prerender.js","source":{"name":"prerender.min.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js"},"line":448,"column":9}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"hello\n","source":{"name":"prerender.min.js","path":"vscode-remote://wsl%2Bdefault/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js"},"line":448,"column":9}}
````

The line of interest is `fixSourceLocation: Script IS mapped, but does NOT exist on disk: /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js` which I added at https://github.com/microsoft/vscode-chrome-debug-core/blob/179e8fcb97ea0ce548c8cf903875627c2d010952/src/transformers/baseSourceMapTransformer.ts#L251

Right now, I have modified that to be:

````
} else if (mapped) {
  sourceLocation.source.path = mapped.source;
  sourceLocation.source.sourceReference = undefined;
  sourceLocation.source.name = path.basename(mapped.source);
  sourceLocation.line = mapped.line;
  sourceLocation.column = mapped.column;
  sourceLocation.isSourceMapped = true;
}
````

and things are working as expected, including breakpoints.

My new log out, in case your wondering is:

````
fixSourceLocation: Script IS mapped, but does NOT exist on disk: /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.min.js
fixSourceLocation: Forcing mapping to : /__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js
mapCallFrame - stackFrame (sourceMapTransformer.fixSourceLocation): {"id":1000,"name":"./prerender.js","source":{"name":"prerender.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js"},"line":16,"column":8,"isSourceMapped":true}
mapCallFrame - stackFrame (lineColTransformer.convertDebuggerLocationToClient): {"id":1000,"name":"./prerender.js","source":{"name":"prerender.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js"},"line":17,"column":9,"isSourceMapped":true}
logObjects: - newStackFrame {"id":1000,"name":"./prerender.js","source":{"name":"prerender.js","path":"/__vscode-remote-uri__/home/carlos/projects/materialdesignweb/docs-src/prerender.js"},"line":17,"column":9,"isSourceMapped":true}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"hello\n","source":{"name":"prerender.js","path":"vscode-remote://wsl%2Bdefault/home/carlos/projects/materialdesignweb/docs-src/prerender.js"},"line":17,"column":9}}
````

I'm sure you can work out the best way to implement a remote URL check. It's interesting because the code checks if the mapped location exists, but doesn't check if the original source exists (which it doesn't). Perhaps another adjustment can be that if neither exists, to prefer the mapping, instead of always defaulting to the original source location.

Regardless, it seems like I can finally use WSLv2 now! :)

**Comment by roblourens** [comment]
Hm, it does need to be extended to also use our remote filesystem provider

**Comment by danny-p93** [comment]
I think, i have the same issue:
On my setup i'm using VScode with Chrome Debugger and WSL-Remote (WSLv1) and have created a react app but i was not able to debug on my sourcefiles as expected (Chrome Debugger as UI extension). 
I tried the same steps with a virtual Linux and everything worked without problems and i was able to set breakpoints in VScode so my Chrome Debugger stopped at that Point.

I tried different steps to solve the issue because i like the idea with WSL and in the end the hint in the beginning from @clshortfuse helped me a lot and i got my debugging work within the extension-in-workspace setup.

But i want to add some things, i figured out while i tried to solve it on my own (i just didn't found the explanation from above).
For me it looks like the `/__vscode-remote-uri__/` at the beginnig of workspaceFolder/workspaceRoot is a problem. As i removed that manually from the generated paths, Vscode was able to find the right source files on my (wsl-)system to validate the breakpoints. But it was strange, that it openend the same file in a new Vscode tab. In this case i had the extension installed on ui side (as default).
Another thing i recognized when scrolling thru the trace log of Chrome debugger: after Vscode broke succesfully at my breakpoint, somewhere in the log it says "read-only inlined Content from source map", so i think that could be the problem, that somehow windows-Vscode locks the file and therefor it opens a new file, which shows the correct breakpoint.

**Comment by clshortfuse** [comment]
@roblourens Can we get this slated with a milestone? Can't really debug with WSL every time Visual Studio updates. I have to come back and apply these fixes which gets tedious.

**Comment by roblourens** [comment]
So the mapping correct if you just get rid of the 'existsSync'? Like it sounds like if I disable the existsSync check for this scenario, everything would work?

**Comment by clshortfuse** [comment]
Well, if you do that you'd be changing the priority. I have the code defaulting to the mapped source only after checking for inlined and source location. Makes sense for VSCode to use a confirmed existing source instead of just accepting a mapped source it can't verify.

So it should be `if (mapped &&(utils.existsSync(mapped.source) || (!inlinedSource && !utils.existsSync(sourceLocation.source.path))))` at the first check.

**Comment by clshortfuse** [comment]
FYI, I wrote this based on my experience on WSL, but using SSH remote produces a similar issue. Rewriting `baseSourceMapTransformer` to use the mapped source as is as a last resort works well. 

I added a breakpoint to `src/prerender.js` and I get an error popup of.

> Unable to open 'prerender.min.js': Unable to read file 'vscode-remote://ssh-remote+devbox1/home/carlos/projects/materialdesignweb/docs/prerender.min.js' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+devbox1/home/carlos/projects/materialdesignweb/docs/prerender.min.js').

Once I modify `%USERPROFILE%\.vscode\extensions\msjsdiag.debugger-for-chrome-4.12.6\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js` and restart VSCode, it debugs properly.

In case you want to check it yourself, you can `git clone git@github.com:clshortfuse/materialdesignweb.git` in a remote SSH session (forward port 8080) and add any breakstop in `src/prerender.js`.
