### ISSUE TITLE
Unable to debug angular (in vscode) after upgrading to version 8 (cross posted)

### ISSUE THREAD

**Issue by IgnacioHR** [microsoft/vscode-chrome-debug#900]
There is a full report posted here

[https://github.com/angular/angular/issues/31890](https://github.com/angular/angular/issues/31890)

including steps to reproduce. I suspect there is an issue with the Regular Expressions not recognised as such or something like that

- VS Code Version: 1.36.1

- Selected lines in the log:

`SourceMap: sources: ["/./src/app/app.component.html","/(webpack)/hot sync nonrecursive ^\\.\\/log$","/./src/$_lazy_route_resource lazy namespace object","/./src/app/app.component.scss","/./src/app/app.component.ts","/./src/app/app.module.ts","/./src/environments/environment.ts","/./src/main.ts"]
SourceMap: pathMapping: {"/":"/Users/ihr/test-angular-project"}
SourceMap: no sourceRoot specified, using webRoot + script path dirname: /Users/ihr/test-angular-project
SourceMaps.scriptParsed: http://localhost:4200/main.js was just loaded and has mapped sources: ["/./src/app/app.component.html","/(webpack)/hot sync nonrecursive ^\\.\\/log$","/./src/$_lazy_route_resource lazy namespace object","/./src/app/app.component.scss","/./src/app/app.component.ts","/./src/app/app.module.ts","/./src/environments/environment.ts","/./src/main.ts"]
OnScriptParsed.resolvePendingBPs: The following pending breakpoints won't be resolved: undefined pendingBreakpointsByUrl = [["/Users/ihr/test-angular-project/src/main.ts",{"args":{"source":{"name":"main.ts","path":"/Users/ihr/test-angular-project/src/main.ts"},"lines":[7],"breakpoints":[{"line":7}],"sourceModified":false},"ids":[1000],"requestSeq":4,"setWithPath":""}]] source = /./src/main.ts
BreakOnLoadHelper: Finished waiting for breakpoints to get resolved.
`

- Complete debug log:
[trace_verbose.txt](https://github.com/microsoft/vscode-chrome-debug/files/3441859/trace_verbose.txt)

Steps to reproduce:

See the explanation at the provided link ahead

**Comment by roblourens** [comment]
This is https://github.com/angular/angular-cli/issues/15116. Until 8.1.3 is released, you will need to set

```
"sourceMapPathOverrides": {
        "webpack:/*": "${webRoot}/*",
        "/./*": "${webRoot}/*",
        "/src/*": "${webRoot}/*",
        "/*": "*",
        "/./~/*": "${webRoot}/node_modules/*"
}
```
