### ISSUE TITLE
runtimeArgs don't seem to be taken into account when using "userDataDir": false

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-chrome-debug#902]
- VS Code Version: 1.36.1 (1.36.1)

Is this by-design or a known issue?
Im trying to use `"runtimeArgs": ["--disable-web-security"]` which work great when i have "userDataDir": true, but not when its false.

**Comment by roblourens** [comment]
If you have a chrome window already running, and you are opening another window on that profile, then those args will not apply.

**Comment by jasonwilliams** [comment]
@roblourens no this is a fresh session with all of my windows previously closed
