### ISSUE TITLE
Debug console logs black text on dark themes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-chrome-debug#904]
Launch VS Code debug target with Abyss theme:

![image](https://user-images.githubusercontent.com/2193314/60629787-06786500-9dac-11e9-9e30-a90a01fef018.png)

FYI terminal apps work around this sort of problem by inverting the color instead of printing white and black.

@lramos15 spotted this earlier today

**Comment by roblourens** [comment]
Fixed
