### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AngelCavalier** [microsoft/vscode-chrome-debug#905]
- Issue Type: `Performance`
- Extension Name: `debugger-for-chrome-nightly`
- Extension Version: `2019.8.900`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\DELL\msjsdiag.debugger-for-chrome-nightly-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by roblourens** [comment]
Please attach the profile file. Also just out of curiousity, why are you using the nightly version of this extension? Are you doing that on purpose?

**Comment by BeingArasalan** [comment]
besically i dont know how to attach (C:\Users\DELL\msjsdiag.debugger-for-chrome-nightly-unresponsive.cpuprofile.txt) this file if you will tell that will help me.

**Comment by BeingArasalan** [comment]
> Please attach the profile file. Also just out of curiousity, why are you using the nightly version of this extension? Are you doing that on purpose?

besically i dont know how to attach (C:\Users\DELL\msjsdiag.debugger-for-chrome-nightly-unresponsive.cpuprofile.txt) this file if you will tell that will help me.
