### ISSUE TITLE
Some breakpoints not bound in Remote - Containers

### ISSUE THREAD

**Issue by Trakhan** [microsoft/vscode-chrome-debug#907]
- VS Code Version: 1.36.1

- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug-container.txt](https://github.com/microsoft/vscode-chrome-debug/files/3478002/vscode-chrome-debug-container.txt)
[vscode-chrome-debug-win.txt](https://github.com/microsoft/vscode-chrome-debug/files/3478003/vscode-chrome-debug-win.txt)

Steps to reproduce:
1. Run vscode on windows (win 10, but version is probably insignificant)
2. Configure angular app with nrwl/nx schematics (https://github.com/nrwl/nx)
3. Create an app and a library
4. Create service in a library and use it in the app
5. Setup launch.json:
		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch esbir-ver-portal in Chrome",
			"url": "http://localhost:4301",
			"webRoot": "${workspaceFolder}/apps/app_name",
		},
6. When run without Remote-Containers all breakpoints bind and hit just fine (either the main app or the library). If run in Remote-Containers only breakpoints in the main app are bound and hit. Breakpoints set in the library are not bound. If a breakpoint is set in the library directly in chrome devtools, VSCode opens the file with the service - only with path containing backslashes instead of forward ones.

Probable cause: Nrwl/nx uses full paths for all libraries and relative for the main app. The paths are setup correctly, only vscode-chrome-debug (or maybe vscode containers extension?) send full path with backslashes instead of regular ones. It is most likelly caused by windows-linux mismatch between container (running dev server) and windows (running chrome).

Also testable in sample project: 
[test.zip](https://github.com/microsoft/vscode-chrome-debug/files/3477995/test.zip)

**Comment by lucasapereira** [comment]
I am having a similar problem, but I am using a node react development server instead. The breakpoints only works when I am running locally.

**Comment by cropse** [comment]
Same issue here, any solution?

**Comment by roblourens** [comment]
I see the problem. This will work for relative paths in sourcemaps like `webpack:///./*` but not absolute ones like `webpack:///*`. I need to change the way remote paths are handled to account for this.

**Comment by roblourens** [comment]
I guess I already have https://github.com/microsoft/vscode-chrome-debug/issues/861 for that issue.
