### ISSUE TITLE
Cannot launch Chrome Debug configuration in Vscode

### ISSUE THREAD

**Issue by TitaneBoy** [microsoft/vscode-chrome-debug#910]
- VS Code Version: 1.37.0
Chrome : 76.0.3809.100
Node.js : 10.16.0
OS : Windows 10 Profesionnal (64 bits)

- VS Code extension: 4.11.7
![image](https://user-images.githubusercontent.com/15614466/62797265-487e8000-baa9-11e9-9852-15628e8733de.png)

- Log file 
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3487393/vscode-chrome-debug.txt)

Hello there.. I'm trying to debugging my angular application by launching chrome against localhost but I'm having this error: 

![image](https://user-images.githubusercontent.com/15614466/62796725-e40ef100-baa7-11e9-84cc-aaa4f448396b.png)

Before launching configuration, I'm serving the angular app with this command:
`ng server --configuration=defbug`

You can see the result of serving here:
![image](https://user-images.githubusercontent.com/15614466/62796846-33552180-baa8-11e9-8c27-af5ecfaac138.png)

Opening manually a chrome web page with the url: `http://localhost:4200/home` works great.

Steps to reproduce:

1. Serving web app with: `ng serve --configuration=defbug`
2. In vscode, select the debug configuration name to launch. In my case: "Launch Chrome again localhost"

![image](https://user-images.githubusercontent.com/15614466/62797229-284ec100-baa9-11e9-85fa-fd4939df2a0a.png)

Here's the configuration I use:

```
{
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "trace": true
    }
```

Thank you for your help

**Comment by Calidus** [comment]
I have seen similar messages about not being able to find a valid target when chrome didn't get properly shut down from the last debugging sessions and is still running in the background. Have you checked your task manager to see if chrome is still running?

**Comment by TitaneBoy** [comment]
@Calidus That's interesting because I didn't think about killing chrome processes. Once done, it looks to work great now. Thank you for the tips. But for your information, since I migrated to Windows 10 (Was on Windows 7 before), it is the first time I am trying to debug my Angular App on Windows 10. Before, on Windows 7, I didn't have any issues from a long time. The computer had a fresh new installation of Windows 10.  So I don't know why this issue happened. I hope that by rebooting next time my computer, I will not have this issue again...

Thank you again for your help :-)
