### ISSUE TITLE
Chrome debug hangs with large Angular Application

### ISSUE THREAD

**Issue by Calidus** [microsoft/vscode-chrome-debug#911]
I have a respectable sized Angular application(~5mb main.js, ~3.5mb vendor.js ), that is causing chrome to hang when launched using vs-code using chrome debug. The application doesn't load into the browser and there is nothing in the debug console  I have kill the process because the window becomes unresponsive and using the stop button in vs-code does not close the window.

- I have tried run different commits ranging from 1 week to 6 months old and I am getting the same results.
- I have reinstalled chrome, vs-code, chrome-debug extension, and restarted my pc
- I have tried using VS Code Insiders
- I have asked a coworker git clone, npm install, rebuild and debug the application and the results were the same
- I can create a new angular application using ng new and chrome debugging works fine
- I can access my application by running ng serve and then opening a chrome tab manually
- I can debug my application using the fire fox debugging extension
- Launch chrome from the command line: `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --no-first-run --no-default-browser-check --user-data-dir=C:\Users\userName\AppData\Local\Temp\vscode-chrome-debug-userdatadir_9222 http://localhost:4200` then run attach just fine.

```
 {
      "type": "chrome",
      "request": "attach",
      "name": "Attach to Chrome",
      "port": 9222,
      "webRoot": "${workspaceFolder}"
    },
```

I am in a enterprise environment, are there common security settings that could be interfering? 

I have tried a couple different launch configs but I am getting the same results:

Original config

```
{
  "name": "ng serve",
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:4200/#",
  "webRoot": "${workspaceFolder}"
},
```

Config from vs-code recipes:  https://github.com/microsoft/vscode-recipes/tree/master/Angular-CLI

```
{
  "name": "ng serve",
  "type": "chrome",
  "request": "launch",
  "preLaunchTask": "npm: start",
  "url": "http://localhost:4200/#",
  "webRoot": "${workspaceFolder}",
  "sourceMapPathOverrides": {
    "webpack:/*": "${webRoot}/*",
    "/./*": "${webRoot}/*",
    "/src/*": "${webRoot}/*",
    "/*": "*",
    "/./~/*": "${webRoot}/node_modules/*"
  }
},

```

- Chrome/76.0.3809.100
- Extension: 4.11.7
- VS Code Version: 1.37.0
- Windows 10

- Log file (set `"trace": true` in launch config): https://gist.github.com/Calidus/cc8888d950728d7e2dda27735b5f33a2

**Comment by Calidus** [comment]
One more piece of information: If create a prelaunch task for chrome from using task.json, I run into the same issue. This leads me to believe something in my environment doesn't like the way chrome is launched or the way process are being created from VS Code.

```
    {
      "label": "launch chrome from cmd",
      "type":"shell",
      "command": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
      "args": ["--remote-debugging-port=9222", "--no-first-run", "--no-default-browser-check", "--user-data-dir=C:\\Users\\userName\\AppData\\Local\\Temp\\vscode-chrome-debug-userdatadir_9222", "http://localhost:4200"]
    }
```

```
    {
      "type": "chrome",
      "request": "attach",
      "preLaunchTask": "launch chrome from cmd",
      "name": "Attach to Chrome",
      "port": 9222,
      "webRoot": "${workspaceFolder}"
    },
```

**Comment by Calidus** [comment]
I am able to get around the issue by setting `runtimeExecutable` to a installation of Brave. I can leave this issue open until I figure what chrome or windows setting is causing the issue or I can close it now.

**Comment by roblourens** [comment]
>  I have kill the process because the window becomes unresponsive

Are you killing Chrome or vscode?

If you run the same command from that task just in a normal command prompt, does it work ok?

There are quite a few scripts in your app but it is not the largest app I have seen so I am not sure what the problem is.

**Comment by Calidus** [comment]
I am killing Chrome.

Yes, if I use the command line to launch chrome with the args I am able to attach to chrome and get debugging working inside of vscode.

**Comment by roblourens** [comment]
> Yes, if I use the command line to launch chrome with the args I am able to attach to chrome and get debugging working inside of vscode.

That's interesting because that's really exactly what the extension does, but I'm glad you have a workaround...

> edit: I think my issue has something to do with Chrome being managed by my organization.

Hm, why do you say that?

**Comment by Calidus** [comment]
> That's interesting because that's really exactly what the extension does, but I'm glad you have a workaround...

I have noticed that chrome launched via the extension doesn't have a parent process in windows according to process explore. While chrome I launch from the command line myself does.

> Hm, why do you say that?

Other Chromium based browsers(Brave, Opera) work fine with the extension but those are not managed/controlled by my organization. I haven't tried the Edge Beta yet.

**Comment by roblourens** [comment]
Ok. I'm not sure there's much I can do here. I don't know what the problem would be but it sounds like you have a few options for workarounds (use a different browser, use an attach config with Chrome).
