### ISSUE TITLE
Play framework cant map source file

### ISSUE THREAD

**Issue by garciaErick** [microsoft/vscode-chrome-debug#912]
I am using play framework and I am trying to get the "sourceMapOverrides" to work, can I get some help? 
Attached is the screenshot of what I want to map
![image](https://user-images.githubusercontent.com/31434516/62983627-ea250a80-bde4-11e9-9c89-3789618e571a.png)

**Comment by roblourens** [comment]
Not really clear what's going on. Can you share what info you have and what you have tried? Also run the command `.scripts` in the Debug Console while debugging.
