### ISSUE TITLE
SelfHosting: Debugge stuck on non-existent breakpoints after reload

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-chrome-debug#916]
1. VSCode repository, run the "Debug VS Code main and Renderer"
2. Hit any breakpoint in the first window. For example put it [here](https://github.com/Microsoft/vscode/blob/eb5c8a0208301cba37bf9498d5b2f4df4c8a94e9/src/vs/workbench/contrib/files/common/explorerService.ts#L152)  and execute "Reval Active File in Sidebar" command
3. Press continue
4. Reload the debugee (second window) -> the debugee seems to think that multiple breakpoints get hit and is stuck in this state. Pressing the Chrome continue button has no effect

I can reproduce this reliably so let me know if you need more details.

![Screenshot 2019-08-21 at 16 49 54](https://user-images.githubusercontent.com/1926584/63442655-c5a7de80-c433-11e9-9c64-142036b0160c.png)

**Comment by roblourens** [comment]
Me too, it's a weird electron issue, I haven't been able to figure it out :(

It is not actually paused, it just won't clear the decoration.

**Comment by isidorn** [comment]
@roblourens should we check with @deepak1556 maybe you have ideas? Or know someone in Electron?

**Comment by deepak1556** [comment]
This is an upstream issue for chromium devtools that looks fixed with electron 6 (our current exploration builds), tested with exploration builds and also bare electron. Attaching video demo, I could try to track down the fix in upstream if needed at later point.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/964386/63557722-b8a3f180-c4fe-11e9-9abf-346958f09698.gif)

**Comment by roblourens** [comment]
Awesome, thanks for checking Electron 6, I should have tried that.

**Comment by isidorn** [comment]
@deepak1556  Fantastic!
I am fine with waiting for electron 6 update for this to be fixed. Thanks a lot!

**Comment by connor4312** [comment]
Please let me know if you continue to hit this with js-debug/the new electron builds
