### ISSUE TITLE
SelfHosting: Restart Frame requires a step to go to a proper location

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-chrome-debug#917]
1. VSCode, launch "Debug VS Code Main and Renderer"
2. Hit a breakpoint, do some stepping. Call Stack -> Restart Frame
3. No effect 🐛 
4. Do a step over -> you are taken to the correct restarted location

I would expect that a step over is not required, but that the restrt frame action would take the execution point to the appropriate location like in Chrome Dev Tools.

![restartFrame](https://user-images.githubusercontent.com/1926584/63443593-59c67580-c435-11e9-8085-c223f7cebaf9.gif)

**Comment by connor4312** [comment]
Fixed this a while ago in js-debug
