### ISSUE TITLE
Ease consumption of debug adapter in other tools by publishing it on npmjs

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode-chrome-debug#929]
This is related to #927 .
Other IDEs that have support for the Debug Adapter Protocol can take advantage of the Chrome Debug Adapter implemented in this project. However, consuming this Debug Adapter currently requires some hacky steps (fetching extension, extracting subset, npm pack/install...).
It would really be easier if the debugAdapter (the `server` module) would be published on npmjs as a standalone artifact.

**Comment by connor4312** [comment]
This debugger [has been superceded](https://github.com/microsoft/vscode-js-debug) and will not receive m/any more updates.
