### ISSUE TITLE
vscode-chrome-debug causes error in launch.json : Matches multiple schemas when only one must validate

### ISSUE THREAD

**Issue by svankirk** [microsoft/vscode-chrome-debug#932]
This is occurs in older code and while using Visual Studio Code for Insiders v1.39 2019-09-17

When I  install Chrome Debug in VSCode and open up my launch.json,  I get a warning for each entry's opening bracket"{" (except for the `"type": "chrome"` entry).  The warning is:

"Matches multiple schemas when only one must validate"

So far, I haven't noticed any side effects other than the error message.  I'll update if I do.

Steps to reproduce:

1. I have a launch.json in my project:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Server WordLobby.ts",
            "type": "node",
            "runtimeArgs": [/*"-r esm"*/],
            "args": [/*"-r esm"*/],
            "protocol": "inspector",
            "request": "launch",
            "program": "${workspaceFolder}/server/index.ts",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "cwd": "${workspaceFolder}",
            "sourceMaps": true,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "${workspaceFolder}",
            "console": "externalTerminal",
        },
        {
            "name": "Client wordLogin.html",
            "type": "chrome",
            "request": "launch",
            "url": "http://127.0.0.1:5500/client/wordLogin.html",
            "webRoot": "${workspaceFolder}/dist/client",
            "runtimeExecutable": "C:/Users/I7/AppData/Local/Google/Chrome SxS/Application/chrome.exe",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
        },
        {
            "name": "streamTest.ts",
            "type": "node",
            //"runtimeArgs": ["-r", "esm"],
            //"args": [/*"-r esm"*/],
            "protocol": "inspector",
            "request": "launch",
            "program": "${workspaceFolder}/server/streamTest.ts",
            "outFiles": [
                 "${workspaceFolder}/dist/server/streamTest.js"
            ],
            "cwd": "${workspaceFolder}",
            "sourceMaps": true,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "${workspaceFolder}",
            //"console": "externalTerminal",
        },

    ],
}
```
2.  Install Chrome Debug and the errors appear.

**Comment by svankirk** [comment]
Okay, I've been playing with my setup, installing and uninstalling other extensions and I  noticed that now I don't see the issue.  Argh!   the insiders release is back to where it was for extensions with only the Chrome Debugger installed and it's not giving me the error.  I have not touched either the settings or the file.  Can anyone duplicate this error?

**Comment by roblourens** [comment]
I can't reproduce it

**Comment by capataz** [comment]
I saw this issue when installing Chrome Debug for the first time.  Restarting VSCode (without uninstalling the extension) made the warning go away.

**Comment by isidorn** [comment]
Thanks for reporting this. However this is a vscode issue.
Can you please create an issue on the vscode side with repro steps and ping me on it? (I could not reproduce this by uninstalling / reinstalling chrome)

**Comment by nevir** [comment]
Just ran into this as well. Steps taken:

1. Install VS Code Chrome Debugger extension (had one config in launch.json)
2. Add a second launch.json config

At that point, the schema validation error popped up and persisted until I did a "Developer: Reload Window"
