### ISSUE TITLE
[help] Breakpoints set in VScode not works, in chrome - do

### ISSUE THREAD

**Issue by Lazarencjusz** [microsoft/vscode-chrome-debug#933]
Please help me with config in `launch.json`. I am struggling with that fore few hours already. The brerakpoints set in VS Code are marked grey with "set but not yet bound". However, when I set such in Chrome console, VS Code opens me the corresponding file in right line. I have no idea how I should set configs. I use webpack to build my app, and external local server. Please see:

![image](https://user-images.githubusercontent.com/6573466/65222258-f58fe380-dabe-11e9-845f-03718a278f0a.png)

Config:
```json
    {
      "sourceMapPathOverrides": {
        "webpack:///./~/*": "${webRoot}/node_modules/*",
        "webpack:///./*": "${webRoot}/*",
        "webpack:///*": "*",
        "webpack:///src/*": "${webRoot}/*"
      },
      "name": "Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "https://local-adres:1444/smf/smf",
      "webRoot": "${workspaceFolder}/src",
      "sourceMaps": true
    },
```

Oppened file from Chrome breakpoint:
![image](https://user-images.githubusercontent.com/6573466/65221269-fcb5f200-dabc-11e9-9600-85cc3cf0a7ac.png)

So webpack build app to `c:/.../my-project/dist`, and my sources are in `c:/.../my-project/src`

- VS Code Version: 1.36.1

Could you help me and show what I am doing wrong?

**Comment by roblourens** [comment]
The path looks wrong, it has a `webpack:` in the middle of it. There is probably a weird path in your sourcemaps somewhere.

**Comment by Lazarencjusz** [comment]
> The path looks wrong, it has a `webpack:` in the middle of it. There is probably a weird path in your sourcemaps somewhere.

OK, but this should be what path. It should be absolute path to my local files, to sources of page, or some mapper between files what Chrome use to my local files? 

So during writing this comment, I figured it out: I have mapped source files of the app to my workspace filder with local files and it works! 
![image](https://user-images.githubusercontent.com/6573466/65438932-9ddada80-de26-11e9-8a91-371d41bb1b10.png)

**Comment by roblourens** [comment]
Glad you figured it out!

**Comment by Lazarencjusz** [comment]
@roblourens one more thing, I have a problem with `this` context, please see example from my code:
![image](https://user-images.githubusercontent.com/6573466/65485867-475fb180-dea3-11e9-9f3a-ea5314bbd420.png)

Inside class method, written as arrow function, the `this` context is not a class, but the area where it was called (this case, inside `ReactLookupComboMultiple` component. When I go to `render` method, everything is correct:
![image](https://user-images.githubusercontent.com/6573466/65485838-33b44b00-dea3-11e9-80b6-d102aebff883.png)

Inside Chrome dev console, it works correct, I mean `handleSelectionChange` contains correct context of `this`.

Is it expected/normal behavior? Can it be changed somehow?

**Comment by roblourens** [comment]
I marked that other issue as a bug.
