### ISSUE TITLE
Cannot connect to runtime process

### ISSUE THREAD

**Issue by DanToker** [microsoft/vscode-chrome-debug#937]
Haven't been using VS code in the last 3 weeks.
Since I got back there seems to be an error and I can't run my debugger (won't open a chrome window).

I've tried adding –remote-debugging-port=9222 to chrome target,
like I've seen in some places. 
also tried to close all chrome processes, and a complete computer reboot. 

Nothing seems to eliminate this issue.

Working on Win7 64 bit with the latest VS code and debugger for chrome extension

![tmpImage](https://user-images.githubusercontent.com/38724822/67001067-a058e900-f0e1-11e9-8b2c-a6cce4252bfe.png)

Configuration:
   {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "userDataDir": false,
            "webRoot": "${workspaceFolder}/src"
        }

**Comment by roblourens** [comment]
Why did you set userDataDir to false? Please see the debugging tips in the readme
