### ISSUE TITLE
Chrome Instance crashing on file input click

### ISSUE THREAD

**Issue by dumartinetj** [microsoft/vscode-chrome-debug#938]
Hi,

When using the Chrome Debugger for my Nuxt.js project Chrome crashes (closes) whenever I click on a file input (before opening file explorer). I tried with my other chrome session (not launched within VS Code Debugger) its working just fine. Also tried to disable every other plugin.

- VS Code Version: 1.39.2
- OS : Ubuntu 19.04
- Log file : [vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3744374/vscode-chrome-debug.txt)
- Launch config : [launch.txt](https://github.com/microsoft/vscode-chrome-debug/files/3744382/launch.txt)

Thanks

**Comment by roblourens** [comment]
Sorry can you explain what you mean by "file input"

**Comment by dumartinetj** [comment]
Thanks for your answer, sorry if I'm not clear.

Whenever I click on a <input type="file"/> in a form, instead of opening my file explorer, chrome just closes.

**Comment by roblourens** [comment]
Is it a `<input type="file" />`?

**Comment by dumartinetj** [comment]
Yes sorry it was deleted from my comment

**Comment by roblourens** [comment]
I can't reproduce it. Are you sure it doesn't happen when using chrome devtools on the browser?
