### ISSUE TITLE
chrome async await can't set breakpoint

### ISSUE THREAD

**Issue by jiangbo0216** [microsoft/vscode-chrome-debug#939]
- VS Code Version:
- Log file (set `"trace": true` in launch config):
basiclly: I follow this article https://medium.com/js-dojo/debugging-nuxt-js-with-vs-code-60a1a9e75cf6

```json
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "client: chrome",
      "url": "http://lcoalhost:3001",
      "webRoot": "${workspaceFolder}",
      "sourceMapPathOverrides": {
        "webpack:///*": "${webRoot}/*" 
      },
      "smartStep": true,
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**",
      ],
      "trace": true,
      "showAsyncStacks":true,
      "sourceMaps":true
    },
```

Steps to reproduce:
![igif](https://user-images.githubusercontent.com/18640629/67158019-8f200e80-f365-11e9-97dd-495f8521af23.gif)
![2gif](https://user-images.githubusercontent.com/18640629/67158047-e625e380-f365-11e9-8219-6608045be253.gif)
step over can't stop in line `const tmp = await wait(1000)`

can't set breakpoint in await line, 
any solution? or is anyone met this

**Comment by roblourens** [comment]
Does it work if you debug with chrome devtools?
