### ISSUE TITLE
Why does the debugger always replaces the console panel ?

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode-chrome-debug#94]
When debugging, I like to leave opened the debug console on one side, and on the other side, the current file being inspected (where the current breakpoint is).

The problem is that each time I choose to "step into" a function, if the function is in another file than the current one, the console panel is replaced by the file.

Is it possible to make the debugger re-use current panel when stepping into functions instead of replacing the console panel ?

**Comment by warpdesign** [comment]
Actually it seems the debugger recycles current *active* panel. So if I use the console, it means I have to first activate another panel, then process in the debugging.

If this is a problem with Code itself, I'll make a feature request on vscode's repository instead.

**Comment by roblourens** [comment]
Yeah, I don't have control over that.
