### ISSUE TITLE
Degugger randomly hits phantom breakpoints in library/framework JS files that were never set

### ISSUE THREAD

**Issue by CodeLiftSleep** [microsoft/vscode-chrome-debug#941]
Not sure why but it happens consistently where after a while random breakpoints in the actual library/framework js files will start getting hit that were never set and the only way to get them to stop is by stopping the debugger and restarting it.  Even on reload these items still will get hit for some reason.

- VS Code Version: 1.39.2
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Run the debugger for any length of time with some breakpoints set
2. Debugger will then for no reason it seems start hitting stuff like zone.evergreen.js or core.js breakpoints that have never been set.

**Comment by roblourens** [comment]
Is it breaking on exceptions or debugger statements? Or files related to the files where breakpoints were set (and sourcemaps not resolved correctly)?

Please include the log or a project where I can reproduce this.
