### ISSUE TITLE
How to debug JavaScript code executed by V8

### ISSUE THREAD

**Issue by ahmadov** [microsoft/vscode-chrome-debug#942]
I'm using a standalone `V8 (Version 7.4.288)` and `V8 Inspector` to execute and debug the JavaScript code. The V8 Inspector API is very powerful and it fully supports Chrome Debugger Protocol.
`ChromeDevTools (CDT)` uses WebSocket connection for the communication. Thus, I've implemented a WebSocket server to provide communication between the V8 Inspector and CDT.

So, I can finally debug the JavaScript code by entering the following link in the Chrome: 

```
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=<address>:<port>
```
Is there any way to use VSCode instead of CDT for debugging? How can I connect to the V8 Inspector from VSCode?

- VS Code Version: 1.39.2

**Comment by roblourens** [comment]
Well this isn't officially supported but you might get it working with the node debug extension. Try creating a node "attach" type config, with "port" set to the port you're using. If that doesn't work, you can set `"trace": true` in your launch config to get a full log.

**Comment by ahmadov** [comment]
Hi @roblourens,
I got it working with the vscode built-in `node` debug extension. But I still want to open this issue in the next few days. First I'd like to try a few things first and if it's okay then I'll close the issue.

Another question:
What does `'or other targets that support the Chrome DevTools Protocol.'` mean? This is the description of this extension. My first impression was that I'd able to debug the V8 Inspector from the vscode with this plugin because the V8 Inspector supports and handles all `Chrome DevTool Protocol` messages.

**Comment by ahmadov** [comment]
Hi, @roblourens,

The VSCode built-in node extension almost works perfectly with a standalone V8 Inspector.

However, I have a few questions. The most important one is about the relative path.

The breakpoint and other features work when I set the absolute path of my JS code as a ScriptOrigin in the V8 inspector. But when I set the ScriptOirigin as a relative path, the breakpoint feature does not work. Instead, VSCode opens a new window and the title says `read-only core modules` and in the loaded scripts section the source is shown like `<node-internals>/src/app.js`.

It'd be very great if I can set the relative path as a ScriptOrigin, how can I achieve that?
I have already tried to set the ScriptOrigin like `file:///src/app.js` and it that case in the loaded scripts it's shown like `/src/app.js` instead of `src/app.js`. Is it expected?

I want to close this issue because there is nothing else to do with the chrome extension.
But I don't know where should I ask the above question. Is the [vscode-node-debug2](/microsoft/vscode-node-debug2) is correct place to continue?

**Comment by roblourens** [comment]
I don't know anything about ScriptOrigin or this setup, so you will have to debug it yourself, sorry. 

> I have already tried to set the ScriptOrigin like file:///src/app.js and it that case in the loaded scripts it's shown like /src/app.js instead of src/app.js. Is it expected?

I don't know, is that what you expect? :D

VS Code tries to tie the reported path of the script to a file in your workspace. So ideally you would set the path to the real path to that file if you want breakpoints to work.

**Comment by ahmadov** [comment]
> > I have already tried to set the ScriptOrigin like file:///src/app.js and it that case in the loaded scripts it's shown like /src/app.js instead of src/app.js. Is it expected?
> 
> I don't know, is that what you expect? :D

No, I don't expect that :) I was expecting to see the path of JS file (in VS Code loaded scripts section) as a relative path instead of an absolute path.

Anyway, I also make it work with Chrome debug extension. The debugger works perfectly by using Chrome debug extension.
