### ISSUE TITLE
Debug session using extention opens chrome windows instead of GUI

### ISSUE THREAD

**Issue by visjble** [microsoft/vscode-chrome-debug#943]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by visjble** [comment]
-Install Debugger for chrome ext.
-Launch debugger
VSC opens a chrome window to the localhost:8080, unreachable.

Expected to load debug session on vsc gui

**Comment by roblourens** [comment]
You might try the Live Server extension
