### ISSUE TITLE
Using "Set Value" in Variables panel when stopped at breakpoint has no effect

### ISSUE THREAD

**Issue by qgates** [microsoft/vscode-chrome-debug#946]
Debugging a Vue project, when I set a breakpoint on a Vue method and try changing local variables using "Set Value" nothing happens.

VS Code version: Code 1.40.1 (8795a98, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

Steps to reproduce:

1. Set a breakpoint on a Vue component method
2. When vscode breaks out, attempt to mutate local variables in the Variables panel with right click->Set Value. Eg. this.some_variable (where `this` is a VueComponent)

Changes made with Set Value have no effect.

However, in the debug console, issuing this.some_variable = 123 works, and the value updates in the Variables panel.

**Comment by roblourens** [comment]
You may not see the change until you step again. Are you sure it's not taking effect? Does this work in the chrome devtools?

**Comment by qgates** [comment]
Hi Rob.

1. Change does not take effect after subsequent steps (using step over)
2. Works in chrome devtools
3. As mentioned previously, while stopped at a breakpoint, setting a local variable using the debug console `this.somevariable = 123` works and the updated value immediately reflects in the variables panel.

The only thing to add which may or may not be relevant is that the project I'm editing resides on a local server which is mapped to the development machine (Win10) as X: via windows/samba networking.

**Comment by roblourens** [comment]
Can you share the project or can you try running with `"trace": true`, then upload the log file from the path it prints at the top of the debug console?

**Comment by qgates** [comment]
Ok, so since updating to 1.40.2 the problem has slightly changed. When I try to set variables, instead of nothing happening (as before) I get a red `referenceerror: value is not defined` tooltip, then the corresponding 'Variables' row disappears. So in the below screenshot, I set a breakpoint at console.log(lbe). Once the debugger breaks, I'm trying to set 'data' in lbe[0]. You can see this successfully done in the debug console, but if I try to do it by right-clicking and 'Set Value' I get the error tooltip, then the 'data' variable disappears altogether.

Examining the debug trace (line 298), it does appear as though variables panel 'data' is being mapped to lbe[0].data with the correct data type (string), so something seems to have gone awry.

Vscode debug trace:
[vscode-chrome-debug.zip](https://github.com/microsoft/vscode-chrome-debug/files/3898235/vscode-chrome-debug.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/4213509/69747965-394a3d80-113f-11ea-9575-0966f8088c13.png)

**Comment by roblourens** [comment]
Thanks. I realized that this is probably https://github.com/microsoft/vscode-node-debug2/issues/250 and will have a fix out soon.
