### ISSUE TITLE
script paths in console output aren't links

### ISSUE THREAD

**Issue by tobiasfeil** [microsoft/vscode-chrome-debug#947]
When a script causes an error and its path is output in red in the console, telling you where the error occured, you can't just click on that path and it takes you there (and, even more preferably, puts your cursor in the respective line) like you can in the Chrome debugger.

- VS Code Version: 1.40.1
- Log file (set `"trace": true` in launch config): confidential

Steps to reproduce:

1. write a script that causes an error
2. click on the file name of the error-causing script, nothing happens

**Comment by roblourens** [comment]
Please give an example. This works for me.

**Comment by tobiasfeil** [comment]
Oh I just found out it works with ctrl + click. Thank you!
