### ISSUE TITLE
Wrong local variables shown

### ISSUE THREAD

**Issue by junalmeida** [microsoft/vscode-chrome-debug#948]
- VS Code Version: 1.40.1

Steps to reproduce:

1. Set a breakpoint on VSCode
2. Check variables panel with wrong locals:
![vscode-breakpoint](https://user-images.githubusercontent.com/991675/69552365-f2ecb700-0f63-11ea-94e5-454ad249c4d2.png)
3. Remove the VSCode breakpoint and set on Chrome DevTools
4. Check variables are correct: 
![chrome-breakpoint](https://user-images.githubusercontent.com/991675/69552360-eff1c680-0f63-11ea-9e16-fba3cf96c8dc.png)

I have no idea if this might be a misconfiguration on my side, so I appreciate any help. Seems that sourcemaps are ok since google chrome can use it.

My project is compiled with webpack and ts-loader. Source files are typescript. 

Thanks in advance.

**Comment by roblourens** [comment]
VS Code doesn't look at renamed variables from sourcemaps yet. There is a feature request for this in the vscode repo. So you are seeing the renamed variables from TS in the variables pane.

**Comment by junalmeida** [comment]
@roblourens Thank you for the clarification, indeed those variables were renamed.
