### ISSUE TITLE
Breakpoints not bound

### ISSUE THREAD

**Issue by evanwellens** [microsoft/vscode-chrome-debug#949]
0

I am trying to set breakpoints in my angular cli workspace project in VS code.

I have no problem breaking in chrome debugger, or the parent project. Just not the library.

When I use a launch like "configurations": [ { "type": "chrome", "request": "launch", "name": "Launch Chrome against localhost", "url": "http://localhost:4200", "webRoot": "${workspaceFolder}/projects/MainProject", "sourceMaps": true } I can debug only code in the MainProject when serving with ng serve MainProject.

MainProject uses a library project ( not via npm but export ) my-lib. Directory structure is like below

10/16/2019 05:22 PM my-lib 10/24/2019 11:51 AM MainProject

If i change the launch "webRoot": "${workspaceFolder}/projects/my-lib",

I still get no breakpoints in vs code.

References to my-lib in the MainProject as as follows. import { xyz } from '../../../../../ccui-lib/src/public_api'

where public.api.ts will have exports like export * from './lib/components/xyz/xyz.component';

Not even sure what I'm trying is possible , seems like it should work and that I am missing something ... Any help would be awesome!!!

I keep getting Breakpoint set but not yet bound ( which appears in the vscode-chrome-debug.txt )

- VS Code Version:
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

- Log file (set `"trace": true` in launch config):
Not sure where the logs end up when launching to include here

Steps to reproduce:

1. Laucnh VS debugging session
2. Set breakpoint  (

**Comment by roblourens** [comment]
Please use the `.scripts` command to get details, or include a log, or share the project with me.

**Comment by evanwellens** [comment]
Here are the logs... Tx
[-1575313100291.log](https://github.com/microsoft/vscode-chrome-debug/files/3912879/-1575313100291.log)

**Comment by roblourens** [comment]
I am looking for a debug log, see steps in the readme https://github.com/microsoft/vscode-chrome-debug#general-things-to-try-if-youre-having-issues
