### ISSUE TITLE
Able to use devtools features other than source debugging (with debugger disconnecting)

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#95]
Or even implement a dome and net inspectors in vscode.

**Comment by felixfbecker** [comment]
This is much needed. Can't really debug a web page without DOM explorer and Network tab.

**Comment by helvanic** [comment]
You can open a second tab though, the devltools will work on it. Not perfect but still...

**Comment by justin-romano** [comment]
I know. This is what i have been doing, using duplicate tabs. 
Be great to be able to do this. Even if the devtools source/debug tab is disabled or something similar

**Comment by sibbl** [comment]
Also, this is not possible if you only need the mobile emulation feature for the tab which you want to debug with VS code.

**Comment by auchenberg** [comment]
The connection limit is a limitation of Chrome's server implementation. See https://bugs.chromium.org/p/chromium/issues/detail?id=129539. 

Closing.
