### ISSUE TITLE
Does webRoot differ between the Chrome and Firefox extensions for remote workspaces?

### ISSUE THREAD

**Issue by sfsccn** [microsoft/vscode-chrome-debug#958]
It appears that, at least in some situations, for the [Firefox extension](https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug)  `webRoot` is the directory served by `url`, but for the Chrome extension `webRoot` is a parent of that directory. 

I’m using VSC on Windows for a project on a remote Linux machine (Remote SSH). Suppose the root directory for my remote webserver at http://mySite is `/webServerRoot` and the directory served for http://mySite/myProject is `/webServerRoot/myProject`. My VSC worksapce has root `/webServerRoot/myProject`, so that in `launch.json`, `${workspaceFolder}` evaluates to `/webServerRoot/myProject`.  It seems that in `launch.json` if `url=”http://mySite/myProject”` I must set:

1. **Firefox extension**: `webRoot: “${workspaceFolder}”`
2. **Chrome extension**: `webRoot: “/webServerRoot”` (example - CentOS: /var/www/html)

Does that sound correct?

While configuring the Firefox extension was straightforward the Chrome extension took a bit more time. The final step was changing `webRoot` from `${workspaceFolder}` to `/webServerRoot`. 

Notes

1. The description of `webroot` given in the Debugger for Chrome [docs page](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) is "the directory that files are served from".
2. The `launch.json` example [here](https://github.com/roblourens/angular2-tour-of-heroes/blob/master/.vscode/launch.json), which is one of the examples from the Debugger for Chrome [docs page](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome), uses the variable `${workspaceRoot}`, which apparently was deprecated in favor of `${workspaceFolder}` as described [here](https://code.visualstudio.com/docs/editor/variables-reference).
3. There’s another example [here](https://github.com/auchenberg/timey/blob/master/.vscode/launch.json), which used `${workspaceFolder}` with no `url` option, but that configuration did not work for me. I was able to get a configuration to work that had no `url` option, but I needed `webRoot` to be `/webServerRoot`. Perhaps that’s the ideal configuration?
4. I was not able to get things working with forwarded ports as described on the Debugger for Chrome [docs page](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome).
5.  Even when I get it to work, I’m not sure I’m using the Chrome extension correctly. I open one Chrome window via cmd with the `-remote-debugging-port=9222` option set and go to http://mySite/myProject, then open another Chrome window at http://localhost:9222, and then VSC mirrors the debugger shown in the localhost window. Is that how it’s supposed to work?

- **VS Code Version**: 1.40.2
- **OS Running VS Code**: Windows 1903
- **Remote Machine**: Scientific Linux 7.1 3.10.0-957.21.3.el7.x86_64 (CentOS-based)
- **Debugger for Chrome**: 4.12.2
- **Chrome**: 78.0.3904.108

**Comment by roblourens** [comment]
Thanks for the detailed issue, tbh I have no idea how the Firefox debugger handles webRoot, so I can't make any comparison with the Chrome extension.

2. I updated the angular project's launch.json but those examples are not well maintained, sorry, I should revisit that.
4. Can you explain more about what issue you had forwarding a remote port?

> and then VSC mirrors the debugger shown in the localhost window. Is that how it’s supposed to work?

I guess so? Easier to use a "launch" type configuration. If you also open the chrome devtools, then you would see the same pausing happening.

**Comment by sfsccn** [comment]
So it sounds like there's no extension-independent convention on `webRoot`, thanks.

I was able to get a launch configuration to work, thanks again. That does seem much easier. However, it's a little weird probably because I'm doing it wrong. I launch with the following configuration. Here `/var/www/html` is my apache root directory and my (remote) project is essentially at `/var/www/html/myproject`:

`{
	"name": "Launch Chrome",
	"type": "chrome",
	"request": "launch",
	"url": "http://myproject",
	"webRoot": "/var/www/html"
},`

Chrome opens, but breakpoints set in VSC aren't bound. However, if I set a breakpoint in Chrome devtools and refresh, it seems a special version of that script opens as read-only in VSC. There I can set breakpoints and everything works great. I can even stop debugging and that special version stays open and breakpoints will work if I start debugging again.

Here's a view of the script opened by the Chrome debugger (top - note there's no path shown) and the same script opened in my VSC workspace (bottom):

![image](https://user-images.githubusercontent.com/7990148/70393375-b03ccd00-19ae-11ea-9705-e9ee9f66a886.png)

Breakpoints set in the top script work, and are shown in the debugger with a "\http:\" prefix like this:

![image](https://user-images.githubusercontent.com/7990148/70393402-eda15a80-19ae-11ea-9c01-e8322b8dceb9.png)

Breakpoints set in the bottom script do not work, and show as open circles.

Should the configuration be changed (sourcemapping?) so I can work directly with the files in my workspace and not have to do the extra devtools/special file step? For example, I tried changing `webRoot` to `${workSpace}` but that causes errors like in the following screenshot (where the workspace directory is `/var/www/html/study-js`). It sounds like it's putting my workspace directory in the web server root and so the workspace directory gets repeated in the path. Setting `webRoot=/var/www/html` seems to fix it.

![image](https://user-images.githubusercontent.com/7990148/70393513-6523b980-19b0-11ea-98c0-3fc98546e65d.png)

Regarding port forwarding, I really don't know how to configure it. My web server's running on port 80. I can't forward that in VSC because it's < 1024. I don't know how to set that in the .ssh/config file, I did try some things I found by web search but nothing seemed to work.

**Comment by sfsccn** [comment]
I was able to get it working without the additional "devtools" step described in my previous post. I just changed the `webRoot` option to the following `pathMapping` option. 

`{
        "name": "Launch Chrome",
	"type": "chrome",
	"request": "launch",
	"url": "http://myserver/myproject/",
	"pathMapping": { "/myproject/": "${workspaceFolder}/" }
}`

Now breakpoints set in VSC work and engage when debugging starts - no need to reload, open devtools, etc.

Perhaps the property of the of the `pathMapping` option (`"/myproject/"` above) must correspond to the `url`. That would explain why replacing the `pathMapping` option with `"webRoot": "/var/www/html/"` doesn't work. 

Anyway, I should be all set, thanks.

**Comment by roblourens** [comment]
That looks like the correct pathMapping for your project, glad you figured it out! It can't be expressed just with webRoot because you need to "remove" the `myproject` segment which doesn't seem to be a folder inside your `workspaceFolder`.

To forward the port, you can use the `LocalForward` directive in your ssh config file, https://www.ssh.com/ssh/config/
