### ISSUE TITLE
Start new chrome instance but use default user

### ISSUE THREAD

**Issue by Sairony** [microsoft/vscode-chrome-debug#959]
I need to use a chrome extension for debugging purposes ( WebGL ). Default configuration runs as a temp user, as a consequence the extension isn't enabled. According to the documentation I can instead set `userDataDir` to false. Since chrome is already running with the default user for my web browsing needs it tries to attach to that instance, which of course fails since it's not started with remote debugging. Instead I want to launch a new chrome instance with remote debugging enabled using the default user, is this possible some way?

**Comment by roblourens** [comment]
No, unless you kill the existing chrome instances. I suggest installing the chrome extension for the other user.
