### ISSUE TITLE
Issue since updating to VS0.10.8  - [webkit-debug-adapter] spawn UNKNOWN

### ISSUE THREAD

**Issue by garfbradaz** [Microsoft/vscode-chrome-debug#96]
Hey Guys,

Since updating to the newer version of visual code (0.10.8), I'm unable to launch Chrome. I have updated to 0.2.2 of the Chrome Debugger. My launch.json is here (I'm using the first config):

```json
{
	"version": "0.2.2",
	"configurations": [
		{
			"name": "Launch clarizenform",
			"type": "chrome",
			"request": "launch",
			"file": "clarizenform.html",
            "diagnosticLogging": true
		},
		{
			"name": "Launch test_rig",
			"type": "chrome",
			"request": "launch",
			"file": "testrig.html"
		},
		{
			"name": "Launch localhost with sourcemaps",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost/mypage.html",
			"sourceMaps": true,
			"webRoot": "wwwroot"
		},
		{
			"name": "Attach",
			"type": "chrome",
			"request": "attach",
			"port": 9222
		}
	]
}
```

The output from the diagnostics is here:

 

>  ›OS: win32 ia32 
>   ›Node version: v4.1.1
>   ›Adapter version: 0.2.2
>   ›initialize({"adapterID":"chrome","linesStartAt1":true,"pathFormat":"path"})
>   ›spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","file:///c:\\Git\\MyGitHub\\clarizen.js\\clarizenform.html"])
>   ›Error: spawn UNKNOWN
>     at exports._errnoException (util.js:837:11)
>     at ChildProcess.spawn (internal/child_process.js:298:11)
>     at Object.exports.spawn (child_process.js:351:9)
>     at WebKitDebugAdapter.launch (C:\Users\mydir.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\webkit\webKitDebugAdapter.js:73:44)
>     at C:\Users\mrdir\.vscode\extensions\msjsdiag.debugger-for-chrome-0.2.2\out\adapter\adapterProxy.js:19:76
>     at process._tickCallback (node.js:369:9)

**Comment by roblourens** [comment]
I am seeing something similar but not the same - Chrome launches, but it crashes. Like the page is dark gray and the tab has a :( icon. I'm looking at it. You should be able to work around it by using an 'attach' instead of a 'launch'.

**Comment by garfbradaz** [comment]
@roblourens diamond - I will give that a try.

**Comment by roblourens** [comment]
Actually it's working just fine now. I'm not sure what was going on there. I hate to say this but if this is happening consistently, you could try restarting Code, killing all chrome processes, or restarting your computer.

**Comment by roblourens** [comment]
Also I'll test on another computer later.

**Comment by garfbradaz** [comment]
@roblourens The attach works. Did a full shutdown of the machine and restarted, "launch" still doesnt work. I will try the same config on my home Windows 10 machine tonight.

**Comment by roblourens** [comment]
Does this still repro? I haven't heard any other reports.

**Comment by garfbradaz** [comment]
Hey Rob - Im on it like a car bonnet tonight :dash:

**Comment by garfbradaz** [comment]
This works on my work Windows 10 PC not on my work machine. I will do some more digging.

**Comment by roblourens** [comment]
Haven't seen or heard anything else about this - cleaning up.
