### ISSUE TITLE
Breakpoint set but not yet bound

### ISSUE THREAD

**Issue by scrayWC** [microsoft/vscode-chrome-debug#961]
Hello there. I am have installed the Debugger for Chrome and am attempting to use it but for some reason I can seem to set bounding breakpoints within my app when have the Debugger for Chrome turned on.  I also can't F5 to bring up the Debugger when I want to use it. I am using VS Code version 1.40.2 on a Mac Book and when I press F5 or shift + F5 while in VS Code the debugger doesn't come up. 
My app is using 2 servers. TomCat for the Java code running in the backend and a node script to start the webpack build that injects the front end React code into to the Java project.

Here is an image of my launch.json file. 
<img width="1074" alt="Screen Shot 2019-12-05 at 11 28 01 AM" src="https://user-images.githubusercontent.com/30298592/70254039-6a83c880-1752-11ea-8338-70dbfb287ea3.png">

**Comment by roblourens** [comment]
webRoot is probably wrong, it should probably point to the directory that your server is serving files from. See the README in this repo for troubleshooting tips.

**Comment by scrayWC** [comment]
@roblourens I am trying to use the debugger in a React app that uses Webpack. I read from a StackOverFlow answer to try using the entry point file that is listed in the Webpack config file. That is where pollyfills.js is coming from.

**Comment by ratsey** [comment]
I recently started getting the same problem, both at work and home projects. I had to change the webRoot, as @roblourens  says: edit it to an explicit path - seems that `${workspaceFolder}` has recently either stopped working or is pointing now to the wrong folder.

```
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:4200",
      // "webRoot": "${workspaceFolder}"
      "webRoot": "C:\\Users\\jens\\Projects\\Repos\\preorder\\preorder"
}
```

**Comment by scrayWC** [comment]
@ratsey I tried the explicit path but breakpoints still show the same error. 

<img width="1065" alt="Screen Shot 2019-12-10 at 8 22 25 AM" src="https://user-images.githubusercontent.com/30298592/70533040-392a4480-1b26-11ea-8102-95b1f480dfa8.png">

**Comment by roblourens** [comment]
@ratsey I'm pretty sure that there's nothing wrong with workspaceFolder, please check that your hardcoded path is exactly the same as the folder you have open.

**Comment by scrayWC** [comment]
@roblourens yes, the path that I have in the webRoot is to the folder that I have open in VS Code. Could there be something going on with the way my project is set up? We aren't using the hot load that automatically comes with the react-create-app because we are using Showcase for our components and my previous lead had to remove that functionality to get Showcase to work properly in the project.

**Comment by ratsey** [comment]
@roblourens You're absolutely right. I think it's the double 'preorder' folder that was confusing things. Setting to this works just fine:

`"webRoot": "${workspaceFolder}/preorder"`

**Comment by thunderkid** [comment]
I've just started getting the message in the title of this issue - breakpoints get grayed out with message 'breakpoint set but not yet bound'. Using VS1.41.1. Setting `webroot` explicitly does not help.

**Comment by samusstrike** [comment]
I'm not using the chrome-debug, but I am using VSCode debugging. I just ran into this issue and discovered that my require path had an uppercase letter which was is lowercase in the filename.
e.g. require("./jsFile") vs require("jsfile") will behave differently.
Is this intended behavior?

**Comment by UiCandy** [comment]
Also facing this issue on `Version: 1.42.1` had been using the same config successfully over the past year so don't think it's the config unless something has changed drastically.

**Comment by roblourens** [comment]
First off, we are working on a new and improved debug adapter, and I'd really appreciate everyone trying it out to see if your scenario is improved - https://code.visualstudio.com/updates/v1_42#_new-javascript-debugger

Secondly, I'll use this issue for the OP and other people can file new issues (there are a lot of different things that can go wrong to produce an issue like this and I'd rather keep them separate)

If the new debug adapter doesn't fix it, then please set `"trace": true`, try again, and share the log from the path in the debug console and I can try to investigate more.

**Comment by simonnishi** [comment]
yeah this version broke something
no change to launch.json and now I can't debug anymore :(

**Comment by satyamnaga** [comment]
am also facing the issue to debug please resolve ASAP

**Comment by adrian-gremlin** [comment]
i can't debug anymore after auto-update to Version: 1.43.1

Two debugger instances seem to auto-attach, neither work i can't hit breakpoints get the "set but not bound" on hover. Pls fix asap and dont send out updates that break things pls.

Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0

**Comment by kcoop** [comment]
Sounds like this is now an issue for multiple people - can we reopen it?

After setting trace=true, when I attempt to set a breakpoint, I see the following message in the verbose log:

`
[23:28:49.414 UTC] SourceMaps.setBP: {MYROOT}/ui/dist/frontend/details_panel.js can't be resolved to a loaded script. It may just not be loaded yet.
`

I can definitely set a breakpoint from within Chrome devtools against this. FWIW, this path is indeed where the source is, but not where the webroot and typescript map file is:

`
[23:28:23.598 UTC] From client: launch({"type":"chrome","request":"launch","name":"NUM 2: Launch Chrome against localhost","url":"http://localhost:10000/index.html","trace":true,"webRoot":"{MYROOT}/out/debug/ui","__sessionId":"ec8e7d5b-747e-4747-a2b8-15c0f323ae3d"})
`

**Comment by roblourens** [comment]
Could someone open a new issue and include the log? You can also use the `.scripts` command to see the resolved locations of scripts.

**Comment by kcoop** [comment]
Will try to get to this later today. Haven't used the .scripts command, how do I do that?

**Comment by kcoop** [comment]
Ack, now I can set breakpoints! :-P  Maybe I just needed to run the .script command. :-)

**Comment by saikatHi6** [comment]
Hi, I am new to VsCode. I am facing the same issue. Not able to debug. It displayed "Breakpoint set but not yet bound". Can anyone advise who had face the same issue and resolved? Thank you in advance.
