### ISSUE TITLE
When launched with noDebug, dispatch "exited" event after Chrome is closed by user

### ISSUE THREAD

**Issue by joshtynjala** [microsoft/vscode-chrome-debug#963]
When vscode-chrome-debug is launched with `noDebug`, and the user exits Chrome, there's no message sent to the IDE that anything has happened. Ideally, some kind of event would allow the IDE to update its state (disable a stop button, kill the debug adapter process, etc.)

When debugging, the [terminated](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated) event is dispatched if Chrome is closed by the user. However, according to the specification, that's to indicate that "debugging of the debuggee has terminated". Since we're using `noDebug`, it makes sense that terminated is not dispatched. However, maybe dispatching the [exited](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Exited) event would be appropriate when launched with `noDebug`?

https://microsoft.github.io/debug-adapter-protocol/specification#Events_Exited

**Comment by roblourens** [comment]
Are you using the extension with a non-vscode editor? Or are you seeing this cause an issue in vscode?

**Comment by joshtynjala** [comment]
I am integrating the extension into a non-VSCode editor. However, I just gave it a try in VSCode, and it seems to show the same undesirable behavior.

If I use _Start Without Debugging_ in VSCode, and then I close the Chrome window, VSCode does not seem to notice that anything happened. For instance, the stop button in VSCode's debug toolbar remains active, as if it were still running. However, if I use _Start Debugging_, and then I close the Chrome window, VSCode responds by immediately removing the debug toolbar. That's the behavior that I'd like to see in both cases, for consistency.

**Comment by roblourens** [comment]
I can repro it, however it seems to work correctly with this extension, which is the future debug adapter: https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

So I don't plan to fix it unless someone sends a PR.

**Comment by joshtynjala** [comment]
Fair enough! I'll switch to the future debug adapter once it is stable.
