### ISSUE TITLE
Unable to launch or attach with error - Cannot connect to runtime process, timeout after 10000 ms

### ISSUE THREAD

**Issue by MarkBonner** [microsoft/vscode-chrome-debug#966]
Hi.

I'm currently unable to connect with the error - Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: socket hang up).

Unfortunately there is no information in the VS Code Debug Console.

{
        "type": "chrome",
        "request": "attach",
        "name": "Attach to Chrome",
        "port": 5001,
        "url": "https://localhost:5001/",
        "webRoot": "${workspaceFolder}"
    },
    {
        "type": "chrome",
        "request": "launch",
        "name": "Launch Chrome against localhost",
        "port": 5001,
        "url": "https://localhost:5001",
        "runtimeArgs": ["--inspect=5001"],
        "webRoot": "${workspaceFolder}"
    },

Kind regards

Mark

**Comment by roblourens** [comment]
"port" is the debug port. This should be different from the port your webserver is using.
