### ISSUE TITLE
Debugging with multiple arrays in a row

### ISSUE THREAD

**Issue by hardik-singhal** [microsoft/vscode-chrome-debug#967]
During debugging the AngularJs code in vscode whenever we have multiple arrays with different indexes and we want to work on the last array in the code we can not see its value by debugging as the debugger only allows us to first array with index it finds in the code. It would be more easier to work with debugging in vscode if this feature will be released.
please refer to [issue 87705](https://github.com/microsoft/vscode/issues/87705)
please find attachment. 
Thanks!
![test](https://user-images.githubusercontent.com/22071153/71617329-a3dc1680-2be0-11ea-9e26-513e4a84a1bc.png)

**Comment by roblourens** [comment]
Sorry, I really don't understand the issue. Please explain the problem in more detail.
