### ISSUE TITLE
Chrome freezes setup userDataDir to my current user

### ISSUE THREAD

**Issue by 50l3r** [microsoft/vscode-chrome-debug#968]
I want to open new tab using my current user and extensions. But when i specify userDataDir to false or my current folder it took to long to unfreeze the tab. 

If i reload the page it rebuild all files (see video) other time and i need to wait too much time

- VS Code Version: 1.41.1
- It's a Vue CLI 3 project

Steps to reproduce:

1. Start debugging
2. Open Developer Tools

```
{
    "version": "0.2.0",
    "configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "VueJS: Chrome",
			"url": "http://localhost:8080",
			"userDataDir": "C:\\Users\\50l3r\\AppData\\Local\\Google\\Chrome\\User Data",
			"webRoot": "${workspaceFolder}/src",
			"breakOnLoad": true,
			"sourceMapPathOverrides": {
				"webpack:///src/*": "${webRoot}/*"
			}
		}
    ]
}
```

[![Image from Gyazo](https://i.gyazo.com/ba2b583cdf9756240ef2857ec3e891f5.gif)](https://gyazo.com/ba2b583cdf9756240ef2857ec3e891f5)

**Comment by roblourens** [comment]
Sorry I don't quite understand what I'm seeing in the screen capture. Why is it pausing on every file?

**Comment by 50l3r** [comment]
> Sorry I don't quite understand what I'm seeing in the screen capture. Why is it pausing on every file?

I don't know but when i open devtools it ocurrs this. It opens me too much files in Sources tab. It takes a long time until it ends. Then the browser tab unfreeze but if i reload the page it ocurrs one more time

**Comment by roblourens** [comment]
Does it happen if you set `"breakOnLoad": false`?

**Comment by 50l3r** [comment]
It doesn't freeze but don't stop in breakpoints.

**Comment by roblourens** [comment]
Could you try this with our new debugger implementation by installing vscode Insiders (https://code.visualstudio.com/insiders) and setting `debug.javascript.usePreview`?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/597
