### ISSUE TITLE
Support Firefox Remote debugging

### ISSUE THREAD

**Issue by charlesmilette** [Microsoft/vscode-chrome-debug#97]
Can this addon also support debugging Javascript with the Firefox browser?

I found some documentation about remote debugging in Firefox [here](https://wiki.mozilla.org/Remote_Debugging_Protocol)

**Comment by roblourens** [comment]
No, but it wouldn't be impossible.

**Comment by auchenberg** [comment]
Hi Charles,

For now we aren't focusing on adding support for other browsers than Chrome, as we still are iterating on the optimal debugging experience for Chrome. Sourcemaps and the attach-to-browser process needs to be better, and simpler to use.

If you were to debug Firefox, what mind of features do you imagine? Same as the current ones in Chrome?

/k

**Comment by charlesmilette** [comment]
I'd like to be able to run a web server, that VS Code would  call Firefox to open, for example "localhost:8080". The javascript/web page would then be loaded and executed, and Visual Studio Code would redirect me to where the error happened and the details, a bit like when debugging C# code with VS.

Not needed, but appreciated:
 - Break points
 - Variables inspector
 - Making changes while running for them to be loaded on next browser refresh

**Comment by auchenberg** [comment]
Thank you vey much @charlesmilette! Hereby noted.

**Comment by auchenberg** [comment]
@charlesmilette A 3rd party has build a dedicated firefox extension, https://github.com/hbenl/vscode-firefox-debug

Closing because of this.
