### ISSUE TITLE
"Reload Required" is always shown, even after reload

### ISSUE THREAD

**Issue by windless0530** [microsoft/vscode-chrome-debug#971]
- VS Code Version: 1.39.2 (Mac)
- Log file (set `"trace": true` in launch config):
- Extension Version: 4.12.5

My current workspace is a C++ project so this extension is not applicable, gray and disabled. There had been nothing wrong for long time. But these days, maybe after some upgrade, the RELOAD REQUIRED button is always shown, no matter how many times I click it to reload Code, or even restart Code.

P.S. Another extionsion vscode-eslint has the same [issue](https://github.com/microsoft/vscode-eslint/issues/878).

![image](https://user-images.githubusercontent.com/4645959/72673117-c7d49e80-3aa0-11ea-9b39-bdee48646454.png)

**Comment by roblourens** [comment]
Can you try uninstalling the extension, closing all VS Code instances, and reinstalling it?
