### ISSUE TITLE
Problem configuring debug of Adobe CEP extension (chromium)

### ISSUE THREAD

**Issue by StefanRiedmann** [microsoft/vscode-chrome-debug#974]
Hello! 
An Adobe CEP extension with debug enabled permits the chrome debug tools to connect. I want to do this from VSCode. 

This is my current configuration:
`
{
"configurations": [
        {
            "name": "Attach to container extension 8080",
            "type": "chrome",
            "request": "attach",
            "port": 8080,
            "url": "localhost:8080",
            "webRoot": "file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.ciclosoftware.container/dist"
        },`

I'll attach a screenshot of the chrome inspector (which is working) and the error I get from VSCode (in the message box I find no way to read the whole path). 

![screenshot_chromedebugger_ext](https://user-images.githubusercontent.com/20997981/72901229-25b6ef80-3d08-11ea-928e-d69aa23ce8d9.jpg)

![screenshot_vscodedebugger](https://user-images.githubusercontent.com/20997981/72901253-31a2b180-3d08-11ea-8431-7f4876ebf7a5.jpg)

**Comment by roblourens** [comment]
Just fix the url or get rid of it and it should work.

**Comment by StefanRiedmann** [comment]
Getting rid of it doesnt help. "Fix the url" is exactly the problem why I wrote in the first place. Impossible to know the extact path from the error window (the text is cut). And I tried all possible combinations of the paths from the chrome screenshot that I've sent.

**Comment by StefanRiedmann** [comment]
Ok thanks. Like this it's working... 

`{
            "name": "EXT Container 8080",
            "type": "chrome",
            "request": "attach",
            "port": 8080,
            "sourceMaps": true
        }`
