### ISSUE TITLE
Random breakpoints getting set for no reason in things like main.js, core.js, zone-evergreen.js in Angular 8 and the only way to make these stop is stop and restart

### ISSUE THREAD

**Issue by CodeLiftSleep** [microsoft/vscode-chrome-debug#976]
This get highly annoying after a while where a random breakpoint gets created in some angular core js file and it will then get hit every time on reload and in some cases require 50-100 "continue" button presses before it goes away.  I have no idea why this occurs as I am not going into any of these Angular 8 js files and setting breakpoints, I just know that if you are in a debug session long enough this will start happening for an unknown reason and the only way to get it to stop is by closing out and restarting the debugger.

Please get this to stop, this is to the point I am going to consider not using this anymore as this happens constantly and it takes forever to get through these unspecified breakpoints in most cases.

**Comment by roblourens** [comment]
Why does it say it is pausing? Do you have the checkboxes to pause on exceptions selected?
