### ISSUE TITLE
Breakpoint  only work in (localhost:3000, 127.0.0.1:3000), Proxy domain not work.

### ISSUE THREAD

**Issue by snoopy83101** [microsoft/vscode-chrome-debug#977]
- VS Code Version:
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Proxy a domain ry.geeknt.com to 127.0.0.1:3000 
2. chrome open ry.geeknt.com  Then all breakpoints not working

![image](https://user-images.githubusercontent.com/24613784/73445377-8348dd00-4395-11ea-9c02-d0cfe922028e.png)

**Comment by snoopy83101** [comment]
My system needs to use the secondary domain to make some judgments.
ry.geeknt.com (for company 1)
ry2.geeknt.com (for company 2)
....
The system calls different configurations.
But the breakpoint only works under localhost and 127.0.0.1

**Comment by roblourens** [comment]
Does that change the paths of the scripts or only the domain? Can you share a log? 
Add `"trace": true` to your launch config, then upload the log file from the path it prints at the top of the debug console.

**Comment by snoopy83101** [comment]
I change my hosts   ry.geeknt.com  =>  127.0.0.1:7001 by 

![image](https://user-images.githubusercontent.com/24613784/73475013-87432200-43ca-11ea-8fc6-48a9a9aa6fec.png)

![image](https://user-images.githubusercontent.com/24613784/73475059-9a55f200-43ca-11ea-9558-daf07352c449.png)

Verbose logs are written to:
/var/folders/mb/mj7wtvbs1yvgc98v6kp7jgdh0000gn/T/vscode-chrome-debug.txt
Classic mode for store/ is deprecated and will be removed in Nuxt 3.
sys:344
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
sys:344
[HMR] connected
sys:344
A parser-blocking, cross site (i.e. different eTLD+1) script, https://api.map.baidu.com/getscript?v=3.0&ak=s0EtLRajWbsHd3FQu2eaPPaC431EaVXS&services=&t=20200109192240, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
api?v=3.0&ak=s0EtLRajWbsHd3FQu2eaPPaC431EaVXS:1
A parser-blocking, cross site (i.e. different eTLD+1) script, https://api.map.baidu.com/getscript?v=3.0&ak=s0EtLRajWbsHd3FQu2eaPPaC431EaVXS&services=&t=20200109192240, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
api?v=3.0&ak=s0EtLRajWbsHd3FQu2eaPPaC431EaVXS:1
A cookie associated with a cross-site resource at http://hm.baidu.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032. [http://ry.geeknt.com/sys/]
A cookie associated with a cross-site resource at http://baidu.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032. [http://ry.geeknt.com/sys/]

**Comment by snoopy83101** [comment]
![image](https://user-images.githubusercontent.com/24613784/73475261-f7ea3e80-43ca-11ea-8599-8f036bf405ab.png)

**Comment by snoopy83101** [comment]
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/4137491/vscode-chrome-debug.txt)
@roblourens  sorry , this is my log(when attach  'ry.geeknt.com/sys'  to Chrome)

**Comment by roblourens** [comment]
Where are the sourcemaps located? Seems they couldn't be downloaded:

```
[03:46:45.766 UTC] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://ry.geeknt.com/sys/_nuxt/runtime.js.map
[03:46:45.779 UTC] HTTP GET failed with: 404 OK
[03:46:45.779 UTC] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://ry.geeknt.com/sys/_nuxt/commons.app.js.map
[03:46:45.780 UTC] HTTP GET failed with: 404 OK
[03:46:45.780 UTC] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://ry.geeknt.com/sys/_nuxt/pages/index.js.map
[03:46:45.781 UTC] HTTP GET failed with: 404 OK
[03:46:45.781 UTC] SourceMaps.loadSourceMapContents: Could not download sourcemap from http://ry.geeknt.com/sys/_nuxt/app.js.map
```

**Comment by snoopy83101** [comment]
![image](https://user-images.githubusercontent.com/24613784/73587517-cd49d400-44f7-11ea-9279-2230aa0af611.png)
![image](https://user-images.githubusercontent.com/24613784/73587529-ee122980-44f7-11ea-9e66-7154d24a0bc2.png)
Thank you for your answer.
I feel a little clearer.
These are all openable in my development environment.

If you remove the agent (that is, the production environment), it will not open.
I think it was because I didn't go through the proxy while downloading, which led to the production environment.

If it is for this reason
Is there any way to get him to configure a proxy?

**Comment by roblourens** [comment]
Not yet - got this issue for it https://github.com/microsoft/vscode-chrome-debug-core/issues/262
