### ISSUE TITLE
Cannot change breakpoint on continue (new breakpoint is ignored)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-chrome-debug#978]
- VS Code Version: Version: 1.41.1
- Log file https://gist.github.com/jasonwilliams/388a1bec7702f568fb9ce4cb19b9e526

Steps to reproduce:

1. Navigate to https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example and clone
2. npm install
3. set a breakpoint in the first function
3. npm run-script dev
4. continue then set a different breakpoint

The log for the video you see in the gif is above.
![capture_breakpoint1](https://user-images.githubusercontent.com/936006/73550970-72ec3d00-443d-11ea-8c8a-9b275e9c99dd.gif)

**Comment by roblourens** [comment]
Could you copy that error stack? It moves a little too quickly and is too small for me to see it.

**Comment by roblourens** [comment]
We have a new version of the debug extension which solves a lot of issues, could you check whether it works with this? https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by jasonwilliams** [comment]
@roblourens i can confirm with the new extension installed and 
```
  "debug.chrome.useV3": true,
  "debug.node.useV3": true
```
added to my settings it does indeed work as expected.

**Comment by roblourens** [comment]
Awesome. Thanks!

**Comment by jasonwilliams** [comment]
@roblourens whats will be the future of this repo if the new nightly plugin is needed?

**Comment by roblourens** [comment]
The new extenstion's repo is microsoft/vscode-js-debug

**Comment by jasonwilliams** [comment]
@roblourens sure, but don’t I still need this extension installed for chrome debugging to work? Do I need both installed right now?

**Comment by roblourens** [comment]
No, just one or the other.

**Comment by jasonwilliams** [comment]
> No, just one or the other.

This doesn't seem right, I've deleted the `vscode-chrome-debug` plugin and now i can't use the chrome launch profile.
"The debug type is not recognized"

**Comment by roblourens** [comment]
Yeah. Or you can keep this extension installed and use "chrome" with the useV3 setting

**Comment by jasonwilliams** [comment]
@roblourens i removed the chrome extension and used "pwa-chrome" instead which caused the breakpoints to no longer work, should i report this as a bug? 

(I've since reverted back to keeping the chrome extension installed with V3 setting)

**Comment by roblourens** [comment]
Those two cases should be pretty much the same, so yeah you can file a bug for it with more details.

**Comment by jasonwilliams** [comment]
"pwa-chrome" now works, im guessing something updated in the nightly.
Does that mean this repo is in maintenance mode now and not being worked on?
