### ISSUE TITLE
Unable to launch chrome in debug mode: connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by ankurihg** [microsoft/vscode-chrome-debug#979]
Error: connect ECONNREFUSED 127.0.0.1:9222

- Version: 1.41.1 (user setup)
- Chrome version :  79.0.3945.130
- Node version: 10.18.0

Steps to reproduce:

1.
[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/4154091/vscode-chrome-debug.txt)

2. chrome is not launching neither on "launch" or "attach" mode.

**Comment by roblourens** [comment]
There is a section in the README about this error, does that help?

**Comment by ankurihg** [comment]
No. I have tried each everything there. i have tried both options, launch and attach. 
I have also tried checking is something else is not running on that port by executing http://localhost:9222/json.

**Comment by roblourens** [comment]
Does a Chrome window actually launch at least?

Can you try enabling our new debugger implementation by setting `debug.javascript.usePreview`?

**Comment by ankurihg** [comment]
Chrome was not at all launching. From insider it worked for me.
I have a question. i am seeing an error in the launch.json "Matches multiple schemas when only one must validate."
Also i didn't understood your 2nd statement "setting debug.javascript.usePreview". Where are how to use this?

<img width="754" alt="schemas" src="https://user-images.githubusercontent.com/57941537/73915515-8be36b00-48e1-11ea-9b11-9f5ad1a7d91d.PNG">

**Comment by ankurihg** [comment]
This is working fine now. I faced a timeout issue, the browser was not launching in 10 seconds so i increased the timeout and things are working fine for now.

Thanks.

**Comment by roblourens** [comment]
I'm glad it's working now. If you still want to try out that setting, I meant that you can set it in vscode's settings, https://code.visualstudio.com/docs/getstarted/settings
