### ISSUE TITLE
Extension host terminated unexpectedly. 

### ISSUE THREAD

**Issue by Brolly0204** [microsoft/vscode-chrome-debug#980]
- VS Code Version: 
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
- Log file (set `"trace": true` in launch config):
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Chrome",
      "url": "http://localhost:8000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

Steps to reproduce:
1.Turn off and run debugger again or debug
![debugger](https://user-images.githubusercontent.com/16096724/74599052-fb621300-50b6-11ea-9cc1-6c26ffd45c6f.jpg)

**Comment by roblourens** [comment]
It looks like the vscode-javac extension might be crashing the EH, could you try disabling that extension and check whether this still happens?
