### ISSUE TITLE
Using vscode-chrome-debug as workspace extension

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-chrome-debug#982]
It should be great if you could document the following use case (as others can benefit from it).

- VS Code Version: 1.42.1
- Debugger for Chrome Version: 4.12.6
- OS Version: Ubuntu 19.10

Scenario:

* Running VSCode with [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) extensions installed.
* Using Docker [container](https://code.visualstudio.com/docs/remote/containers) development.
* Have a Docker container with chrome installed.
* No chrome installed on host machine.
* Want to use container's chrome for debugging.

Steps to reproduce:

1. Use a **Dockerfile** based on image with chrome installed (in my case, I use a custom one based on Ubuntu 18.04 and cutomized for my development needs)
```Dockerfile
FROM rubensa/ubuntu-tini-dev-chrome

# Keep container running (for use in VSCode)
CMD [ "tail", "-f", "/dev/null" ]
```
2. In **devcontainer.json** add extension and force it to be "**workspace**" (instead of "**ui**")
```json
{
  ...
  "extensions": [
    // Chrome debugger
    "msjsdiag.debugger-for-chrome"
  ],
  "settings": {
    "remote.extensionKind": {
      // Force chrome debugger extension installation on container
      "msjsdiag.debugger-for-chrome": [
        "workspace"
      ]
    }
  },
  ...
}
```
**NOTE**:  In order to work, the extension must be installed locally (but **disabled Locally** and **enabled in the Dev Container**)
3. Setup Docker run arguments in **devcontainer.json**
```json
{
  ...
  "runArgs": [
    // X11 Unix-domain socket
    "--mount",
    "type=bind,source=/tmp/.X11-unix,target=/tmp/.X11-unix",
    "--env=DISPLAY=unix${localEnv:DISPLAY}",
    // Allow shared memory to avoid RAM access failures and rendering glitches due to X extesnion MIT-SHM
    "--ipc=host",
    // The kernel requires SYS_ADMIN for Chrome sand-box
    "--cap-add",
    "SYS_ADMIN",
    // $(id -u):$(id -g)
    "-u",
    "1000:1000"
  ],
  ...
}
```
4. For my particular Dockerfile set to not override Docker command by VSCode in **devcontainer.json**
```json
{
  ...
  "overrideCommand": false
  ...
}
```

Now, when you open your project in **Remote - Containers**, you can debug your code inside the container.

![Screenshot from 2020-02-18 22-52-55](https://user-images.githubusercontent.com/1469340/74781382-ad5d3300-52a1-11ea-86e8-ca08ac6be28e.png)

**Comment by roblourens** [comment]
Thanks for the suggestion, but I mainly expect people to use the extension as a UI extension with the server port forwarded over the remote, and don't really want to confuse people with setting up X11 forwarding.

Also, when the new JS debugging extension supports remote debugging, it will run as a workspace extension but control Chrome remotely via another UI extension. https://github.com/microsoft/vscode-js-debug/issues/337 And if you want to use X11 forwarding with that, that would require some other workaround on our part to enable it. So I don't want to document this anywhere yet.
