### ISSUE TITLE
At launching Chrome task, Error: Configured debug type 'pwa-chrome' is not supported

### ISSUE THREAD

**Issue by magneticcore** [microsoft/vscode-chrome-debug#983]
- VS Code Version: 1.42.1
- Debugger for Chrome version: 4.12.6
- Chrome version: 80.0.3989.114
- No log file, even if "trace": true is set in launch.json

Error:
Impossible to launch the task for Chrome to debug an Angular application.  

Steps to reproduce:

1. In Run and Debug panel, launch the default task "Launch Chrome against localhost".
2. A dialog with an error message appears: "Configured debug type 'pwa-chrome' is not supported" with 2 buttons "Open launch.json" or "Cancel".
3. Doesn't matter the clicked button, the launching task is stopped.

This is my launch.json:
`{
    "version": "0.2.0",
    "configurations": [  
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "trace": true,
            "webRoot": "${workspaceFolder}/path/src"
        },
        {
            "name": "Launch Edge against localhost",
            "type": "edge",
            "request": "launch",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}/path/src",
            "sourceMapPathOverrides": {
                "webpack:/./*": "${webRoot}/*",
                "webpack:/src/*": "${webRoot}/src/*",
                "webpack:/*": "*",
                "webpack:/./~/*": "${webRoot}/node_modules/*"
            },
        },
    ]
}`

**Comment by roblourens** [comment]
Did you set `debug.javascript.usePreview` or one of the `useV3` settings? If so you need to install this extension or unset that setting https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by connor4312** [comment]
The new debugger is now built-in, so this should no longer be an issue
