### ISSUE TITLE
Debugging does not start

### ISSUE THREAD

**Issue by NumanIjaz** [microsoft/vscode-chrome-debug#984]
Hi,
I have a custom python configured as interpreter in vscode, when I start debugging nothing happens but an error appears on the Dev tools console (Help -> Toggle Developer Tools). The error states:

```
_ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:728)
    at file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:159
    at async t.RawDebugSession.shutdown (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2890:248)_
```

- VS Code Version: 1.42.1 (user setup)
- Python extension for VS code version: 2020.2.63990

The debugging worked fine a week ago but now the error won't disapper. I also tried to install previous versions of VS Code and Python extension but it doesn't work.

What can be the possible reason? And how to fix?

**Comment by roblourens** [comment]
It looks like this should be filed on the Python extension?

**Comment by NumanIjaz** [comment]
I have seen this issue appears for other extensions as well such as Unity extension for VS code. Which kind of convinced me that the issue could be in VS code.

I tried installing a previous version of python extension (which worked earlier) but I get the same error. My colleague is also facing the same issue.

**Comment by roblourens** [comment]
FYI @isidorn look familiar?

**Comment by isidorn** [comment]
Nope. Sorry.

**Comment by roblourens** [comment]
Could you try this in the Insiders build? I see the same error in this issue that was closed this month https://github.com/microsoft/vscode/issues/87767

https://code.visualstudio.com/insiders

**Comment by novaXire** [comment]
Same issue here, i tried with the insiders build but same error.
I can't debug any python script. Python works fine in command line.
It worked fine yesterday, and suddendly it stopped to work during the afternoon
@NumanIjaz did you fix your visual code?

**Comment by NumanIjaz** [comment]
@novaXire The issue is with the Python extension for VS Code. I switched to Python extension 2019.9.34911 and it works now. Probably something broke in the later versions.

**Comment by novaXire** [comment]
it was better the "Python Debug Console" was now open, but nothing was happening :( 
I had to uninstall python, delete the python folder and reinstall it (repair or install a new version did nothing)

**Comment by con-cso** [comment]
I also face this issue. After downgrading to 2019.9.34911, it works like a charm.

Even though newer versions of vscode-python used to work with older versions of vscode until about January or February, this seems like it belongs to vscode-python?

**Comment by roblourens** [comment]
If downgrading works, please file this on the python extension's repo, thanks.
