### ISSUE TITLE
How do I launch this from vscode on a specific port?

### ISSUE THREAD

**Issue by boldwade** [microsoft/vscode-chrome-debug#986]
When I launch from vscode it only goes to port 5500. I don't see any way for me to change the port. I tried adding a launch.json file with a specific port but that didn't do anything.

**Comment by roblourens** [comment]
What is the "it" in this scenario? If you mean your server, you will have to change that yourself.

**Comment by boldwade** [comment]
Sorry... nvm... I finally see the option to change the port within vscode.
