### ISSUE TITLE
Automatically close tab when debug is finished

### ISSUE THREAD

**Issue by r44083** [microsoft/vscode-chrome-debug#987]
Hi, Is there a way to force a chrome tab to close at the end of the debug session?

**Comment by roblourens** [comment]
If you have a "launch" type config, then the browser should close if you click "stop" in the debugger. Do you not see that happening?

**Comment by r44083** [comment]
Browser doesn't close when I stop debugging:
![open-chrome](https://user-images.githubusercontent.com/13915612/75919559-745abc00-5e66-11ea-86a2-4268f23a567e.gif)

Maybe something wrong in my debug config?

**Comment by roblourens** [comment]
Possibly because the developer tools are open, and since there is still a debug client, it doesn't shut down
