### ISSUE TITLE
Property skipFiles is not allowed

### ISSUE THREAD

**Issue by Pra3t0r5** [microsoft/vscode-chrome-debug#989]
I was wanting to skip any kind of node_modules black-boxing during my already tedious debugging sessions of a really big project. Upon a short research i found out that i can ignore everything node_modules with this inserted in vscode/launch.json:
```
"skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ]
``` 
However, i'm getting a warning that makes me suppose this functionality is not implemented in  browser-preview. (The very same lines inside any other launcher config like "ng serve" do work)

- VS Code Version: 1.42.1

Steps to reproduce:

1. Add lines as suggested in this stackoverflow post https://stackoverflow.com/questions/47556495/how-do-i-skip-external-code-when-debugging-in-vs-code
2. You get the warning described in the pic
![Screenshot from 2020-03-09 10-31-41](https://user-images.githubusercontent.com/38087682/76217618-871c1a80-61f1-11ea-80cb-28e6e963b056.png)

**Comment by roblourens** [comment]
Sorry, you'll have to file this on the browser-preview extension
