### ISSUE TITLE
2 different versions of chrome.

### ISSUE THREAD

**Issue by artoodeeto** [microsoft/vscode-chrome-debug#990]
- VS Code Version:  1.43.0
- Log file (set `"trace": true` in launch config):

Hello, I have a problem running chrome debugger. So I have 2 different versions of chrome. 

development version: `Version 82.0.4068.4 (Official Build) dev (64-bit)` 

old version: `Version 58.0.3029.96 (64-bit)`

I set my development version to default but when I tried running chrome debugger as `launch` it will use the old version not the default version. So I tried running chrome as `attach` then Im getting an error : `HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9229` is it because its looking for the old version chrome? Do you have support where you can change which chrome version to use?

Steps to reproduce:

1. Download 2 different version of chrome
2. Set the first download version as default
3. then set the 2nd version as default
4. run chrome debugger as `launch` or `attached` it will use the 1 downloaded version.

**Comment by roblourens** [comment]
All you should have to do for a 'launch' config is set `runtimeExecutable` in your launch config to be the path to chrome. Does that work?

**Comment by artoodeeto** [comment]
ahhh. thats what im looking for. thank you. I was thinking of a key `chrome` something something. thank you. Ill close this.
