### ISSUE TITLE
Unbound Breakpoint using Launch Chrome

### ISSUE THREAD

**Issue by CodeLiftSleep** [microsoft/vscode-chrome-debug#991]
- VS Code Version:1.43.0
- Log file (set `"trace": true` in launch config):

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [  

        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "localhost:4200",
            "webRoot": "${workspaceFolder}",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                "*": "${webRoot}/*"
            },
            "trace": true    
        }
    ]
}
```

Steps to reproduce:

This same configuration was just working yesterday, I update VS Code to 1.43.0 and no it no longer works?  This extension is so maddening at times as it just randomly stops working for no apparent reason and then also seemingly starts working again for no apparent reason.

I am setting breakpoints in the code and they remain unbound after launching this. Please help resolve.

**Comment by FishOrBear** [comment]
Now this breakpoint will fly around.

**Comment by roblourens** [comment]
Can you share the project or the log file? By setting `"trace": true` in the launch config and sharing the log from the path printed to the debug console. Sorry for the trouble and the slow response.
