### ISSUE TITLE
Do not quit Chrome when stopping debugging with "request": "launch"

### ISSUE THREAD

**Issue by vegerot** [microsoft/vscode-chrome-debug#996]
- VS Code Version:
- Log file (set `"trace": true` in launch config):
```
{
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://localhost",
      "breakOnLoad": false,
      "webRoot": "${workspaceFolder}/",
      "userDataDir": "${workspaceFolder}/.vscode/vscode-chrome-debug-userdatadir",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///./*": "${webRoot}/*",
        "webpack:///src/*": "${webRoot}/*",
        "webpack:///*": "*",
        "webpack:///./~/*": "${webRoot}/node_modules/*",
        "meteor://💻app/*": "${webRoot}/*"
      },
    }
```

Right now, when I stop a debug session Chrome quits.  I can understand why that may be convenient for certain use cases.  In my use case though, I would like Chrome to remain open.
Steps to reproduce:

1. Start debug session
2. Stop debug session

**Comment by roblourens** [comment]
I don't plan to change this right now, however you could get around it by using an "attach" session and launching Chrome yourself.

**Comment by vegerot** [comment]
@roblourens the reason I use "launch" instead of "attach" is because I want it to use a custom session that I wrote

**Comment by vegerot** [comment]
And I'd like it to open Chrome for me, not just close it.
