### ISSUE TITLE
Chrome does not start on local machine when debugging a remote project as described in the README

### ISSUE THREAD

**Issue by finite-light** [microsoft/vscode-chrome-debug#997]
- VS Code Version: 1.43.2
- Log file (set `"trace": true` in launch config): 
I just followed the document [Usage with remote VS Code extensions][], and cannot found a log file

Steps to reproduce:

1. Create a project in remote machine (in my case, it's a ubuntu18.04-x64 virtual machine without graphical interface in vmware)
   - create a html file `index.html` with some javascript codes in a script tag, such as
      ```html
      <!DOCTYPE html>
      <html>
        <head>
          <title>vscode-chrome-debug Remote Test</title>
        </head>
        <body>
          <script>
            console.log('hello, world!')
          </script>
        </body>
      </html>
       ```

2. Open the project using vscode installed in local machine (in my case, it's a windows-x64 os with build version 18363)

3. Serve the project as static files using `Live Server` plugin of vscode, or using shell command `serve . -l 5500` (by the way, you can get the `serve` script with `npm install -g serve`)

4. Forward port `5500` to the local machine as described in [step 3 of Usage with remote VS Code extensions][Usage with remote VS Code extensions]

5. Create a chrome launch configuration in `vscode/launch.json`, such as
    ```json
    {
      "version": "0.2.0",
      "configurations": [
        {
          "type": "chrome",
          "port": 9232,
          "address": "127.0.0.1",
          "request": "launch",
          "name": "debug in chrome (launch)",
          "url": "http://localhost:5500",
          "webRoot": "${workspaceFolder}",
          "trace": true
        }
      ]
    }
    ```

6. Start the `debug in chrome (launch)` config as described in [step 4 of Usage with remote VS Code extensions][Usage with remote VS Code extensions]

But the chrome doesn't launch as the described in [step 5 Usage with remote VS Code extensions][Usage with remote VS Code extensions] I just got a error message box (as shown below), and I don't know where to get the log file

![vscode-chrome-debug-error](https://user-images.githubusercontent.com/62316053/77516335-29f0bc00-6eb5-11ea-8a10-f15a3f02cfb1.png)

[Usage with remote VS Code extensions]: https://github.com/microsoft/vscode-chrome-debug#usage-with-remote-vs-code-extensions

**Comment by roblourens** [comment]
Is Chrome installed?

**Comment by finite-light** [comment]
Chrome is installed in local machine (the windows os), but is not installed on the virtual machine.

**Comment by roblourens** [comment]
Is it installed to an unusual location? Basically we just can't find it in the usual install locations.

**Comment by finite-light** [comment]
Probably not. I get ChromeSetup.exe from https://www.google.com/chrome/browser/desktop/index.html, and run this startup program to install it.
The final install location is `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

**Comment by roblourens** [comment]
Can you set `runtimeExecutable` to that path, and if it still doesn't work, set `"trace": true`, try again, and share the log from the path that's printed to the top of the debug console.

**Comment by finite-light** [comment]
That still doesn't work for me, and the debug console was not launched, so I still couldn't find the path to the log:
![image](https://user-images.githubusercontent.com/62316053/78234508-d2cc9600-7509-11ea-98b2-1ef9bd0d3b11.png)

**Comment by roblourens** [comment]
Hm, no clue. Maybe it has something to do with having a non-english windows language, I'll try that. Could you also see if it works with our new debug adapter implementation, which fixes a lot of issues? Details:
https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by finite-light** [comment]
I made some attempts, but it still doesn't seem to work.

* I installed this new javascript debugger, and followed the plugin instructions to add the following settings in my `settings.json`:

  ```json
  {
    "debug.javascript.usePreview": true,
    "debug.node.useV3": true,
    "debug.chrome.useV3": true,
  }
  ```

* I tried the previous launch settings, but just got the same error as before and couldn't find the log.

* Then I tried the following settings:
  ```json
  {
    "type": "pwa-chrome",
    "port": 9222,
    "request": "launch",
    "name": "debug in chrome (launch)",
    "url": "http://localhost:5033",
    "webRoot": "${workspaceFolder}",
    "trace": true,
    "runtimeExecutable": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
  }
  ```

  - But got an error of `command 'js-debug-companion.launchAndAttach' not found`
    ![image](https://user-images.githubusercontent.com/62316053/78314271-06500480-758c-11ea-957e-3a4c99566cae.png)

  - <details>
    <summary>
      And this is the debug log
    </summary>
    <code>
      {"timestamp":1585876772337,"tag":"runtime.welcome","level":1,"message":"js-debug-nightly v2020.3.3117 started","metadata":{"os":"linux x64","nodeVersion":"v12.4.0","adapterVersion":"2020.3.3117"}}
      {"tag":"dap.receive","timestamp":1585876772277,"metadata":{"connectionId":7,"message":{"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"pwa-chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}},"level":0}
      {"tag":"dap.send","timestamp":1585876772277,"metadata":{"connectionId":7,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":false,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"caught","label":"Caught Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":false}],"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartFrame":true,"supportsGotoTargetsRequest":false,"supportsStepInTargetsRequest":false,"supportsCompletionsRequest":true,"supportsModulesRequest":false,"additionalModuleColumns":[],"supportedChecksumAlgorithms":[],"supportsRestartRequest":true,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":false,"supportsSetExpression":false,"supportsTerminateRequest":false,"completionTriggerCharacters":[".","[","\"","'"],"supportsBreakpointLocationsRequest":true}}},"level":0}
      {"tag":"dap.send","timestamp":1585876772279,"metadata":{"connectionId":7,"message":{"seq":2,"type":"event","event":"initialized","body":{}}},"level":0}
      {"tag":"dap.receive","timestamp":1585876772330,"metadata":{"connectionId":7,"message":{"command":"launch","arguments":{"type":"pwa-chrome","name":"debug in chrome (launch)","request":"launch","trace":{"console":false,"level":"verbose","stdio":true,"logFile":"/home/virtual/.vscode-server/data/logs/20200403T084419/exthost2/ms-vscode.js-debug-nightly/vscode-debugadapter-7.json","tags":[]},"address":"localhost","outputCapture":"console","port":9222,"timeout":10000,"showAsyncStacks":true,"skipFiles":[],"smartStep":true,"sourceMaps":true,"pauseForSourceMap":true,"resolveSourceMapLocations":null,"rootPath":"/home/virtual/temp/html-demo","outFiles":["/home/virtual/temp/html-demo/**/*.js","!**/node_modules/**"],"sourceMapPathOverrides":{"webpack://?:*/*":"${webRoot}/*","webpack:///./~/*":"${webRoot}/node_modules/*","meteor://💻app/*":"${webRoot}/*"},"__workspaceFolder":"/home/virtual/temp/html-demo","disableNetworkCache":true,"pathMapping":{},"url":"http://localhost:5033","urlFilter":"","webRoot":"/home/virtual/temp/html-demo","server":null,"cwd":null,"file":null,"env":{},"includeDefaultArgs":true,"runtimeArgs":null,"runtimeExecutable":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","userDataDir":true,"__workspaceCachePath":"/home/virtual/.vscode-server/data/User/workspaceStorage/503f528d03a9dbf1b78fd3a264756985/ms-vscode.js-debug-nightly","__sessionId":"b37346e6-1370-4ca4-9df3-92c638149fba"},"type":"request","seq":2}},"level":0}
      {"tag":"dap.send","timestamp":1585876772330,"metadata":{"connectionId":7,"message":{"seq":3,"type":"event","event":"output","body":{"category":"console","output":"Note: Using the \"preview\" debug extension\n"}}},"level":0}
      {"tag":"dap.send","timestamp":1585876772331,"metadata":{"connectionId":7,"message":{"seq":4,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-chrome","request":"launch","os":"linux x64","nodeVersion":"v12.4.0","adapterVersion":"0.9.0","parameters":"{\"type\":\"pwa-chrome\",\"name\":\"<string>\",\"request\":\"launch\",\"trace\":{\"console\":false,\"level\":\"<string>\",\"stdio\":true,\"logFile\":\"<string>\",\"tags\":[]},\"address\":\"localhost\",\"outputCapture\":\"console\",\"port\":9222,\"timeout\":10000,\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"pauseForSourceMap\":true,\"resolveSourceMapLocations\":null,\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack://?:*/*\":\"<string>\",\"webpack:///./~/*\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"__workspaceFolder\":\"<string>\",\"disableNetworkCache\":true,\"pathMapping\":{},\"url\":\"<string>\",\"urlFilter\":\"\",\"webRoot\":\"<string>\",\"server\":null,\"cwd\":null,\"file\":null,\"env\":{},\"includeDefaultArgs\":true,\"runtimeArgs\":null,\"runtimeExecutable\":\"<string>\",\"userDataDir\":true,\"__workspaceCachePath\":\"<string>\",\"__sessionId\":\"<string>\"}"}}}},"level":0}
      {"tag":"dap.send","timestamp":1585876772332,"metadata":{"connectionId":7,"message":{"seq":5,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\n/home/virtual/.vscode-server/data/logs/20200403T084419/exthost2/ms-vscode.js-debug-nightly/vscode-debugadapter-7.json\n"}}},"level":0}
      {"tag":"dap.send","timestamp":1585876772338,"metadata":{"connectionId":7,"message":{"seq":6,"type":"event","event":"launchBrowserInCompanion","body":{"type":"chrome","serverPort":40281,"browserArgs":["--disable-background-networking","--disable-background-timer-throttling","--disable-backgrounding-occluded-windows","--disable-breakpad","--disable-client-side-phishing-detection","--disable-default-apps","--disable-dev-shm-usage","--disable-renderer-backgrounding","--disable-sync","--metrics-recording-only","--no-first-run","about:blank"],"launchId":7,"params":{"type":"pwa-chrome","name":"debug in chrome (launch)","request":"launch","trace":{"console":false,"level":"verbose","stdio":true,"logFile":"/home/virtual/.vscode-server/data/logs/20200403T084419/exthost2/ms-vscode.js-debug-nightly/vscode-debugadapter-7.json","tags":[]},"address":"localhost","outputCapture":"console","port":9222,"timeout":10000,"showAsyncStacks":true,"skipFiles":[],"smartStep":true,"sourceMaps":true,"pauseForSourceMap":true,"resolveSourceMapLocations":null,"rootPath":"/home/virtual/temp/html-demo","outFiles":["/home/virtual/temp/html-demo/**/*.js","!**/node_modules/**"],"sourceMapPathOverrides":{"webpack://?:*/*":"/home/virtual/temp/html-demo/*","webpack:///./~/*":"/home/virtual/temp/html-demo/node_modules/*","meteor://💻app/*":"/home/virtual/temp/html-demo/*"},"__workspaceFolder":"/home/virtual/temp/html-demo","disableNetworkCache":true,"pathMapping":{},"url":"http://localhost:5033","urlFilter":"","webRoot":"/home/virtual/temp/html-demo","server":null,"cwd":null,"file":null,"env":{},"includeDefaultArgs":true,"runtimeArgs":null,"runtimeExecutable":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe","userDataDir":true,"__workspaceCachePath":"/home/virtual/.vscode-server/data/User/workspaceStorage/503f528d03a9dbf1b78fd3a264756985/ms-vscode.js-debug-nightly","__sessionId":"b37346e6-1370-4ca4-9df3-92c638149fba"}}}},"level":0}
      {"tag":"dap.receive","timestamp":1585876772339,"metadata":{"connectionId":7,"message":{"command":"setBreakpoints","arguments":{"source":{"name":"index.html","path":"/home/virtual/temp/html-demo/index.html"},"lines":[8],"breakpoints":[{"line":8}],"sourceModified":false},"type":"request","seq":3}},"level":0}
      {"tag":"dap.send","timestamp":1585876772339,"metadata":{"connectionId":7,"message":{"seq":7,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":18,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
      {"tag":"dap.receive","timestamp":1585876772391,"metadata":{"connectionId":7,"message":{"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":4}},"level":0}
      {"tag":"dap.send","timestamp":1585876772391,"metadata":{"connectionId":7,"message":{"seq":8,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true,"body":{}}},"level":0}
      {"tag":"dap.receive","timestamp":1585876772405,"metadata":{"connectionId":7,"message":{"command":"configurationDone","type":"request","seq":5}},"level":0}
      {"tag":"dap.send","timestamp":1585876772405,"metadata":{"connectionId":7,"message":{"seq":9,"type":"response","request_seq":5,"command":"configurationDone","success":true,"body":{}}},"level":0}
      {"tag":"dap.receive","timestamp":1585876772424,"metadata":{"connectionId":7,"message":{"command":"threads","type":"request","seq":6}},"level":0}
      {"tag":"dap.send","timestamp":1585876772424,"metadata":{"connectionId":7,"message":{"seq":10,"type":"response","request_seq":6,"command":"threads","success":true,"body":{"threads":[]}}},"level":0}
      {"tag":"dap.send","timestamp":1585876777280,"metadata":{"connectionId":7,"message":{"seq":11,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"performance":[{"operation":"initialize","totalTime":0.3,"max":0.3,"avg":0.3,"stddev":null,"count":1,"failed":0,"errors":[]},{"operation":"setBreakpoints","totalTime":0.5,"max":0.5,"avg":0.5,"stddev":null,"count":1,"failed":0,"errors":[]},{"operation":"setExceptionBreakpoints","totalTime":0.9,"max":0.9,"avg":0.9,"stddev":null,"count":1,"failed":0,"errors":[]},{"operation":"configurationDone","totalTime":0.4,"max":0.4,"avg":0.4,"stddev":null,"count":1,"failed":0,"errors":[]},{"operation":"threads","totalTime":0.3,"max":0.3,"avg":0.3,"stddev":null,"count":1,"failed":0,"errors":[]}]}}}},"level":0}
      {"tag":"runtime.launch","timestamp":1585876782334,"message":"Launch returned error","metadata":{"error":"Unable to launch browser: \"Timed out waiting for browser connection\": timeout after 10000ms","name":"n"},"level":2}
      {"tag":"dap.send","timestamp":1585876782335,"metadata":{"connectionId":7,"message":{"seq":12,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Unable to launch browser: \"Timed out waiting for browser connection\": timeout after 10000ms","body":{"error":{"id":9223,"format":"Unable to launch browser: \"Timed out waiting for browser connection\": timeout after 10000ms","showUser":true}}}},"level":0}
      {"tag":"dap.receive","timestamp":1585876782448,"metadata":{"connectionId":7,"message":{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":7}},"level":0}
      {"tag":"dap.send","timestamp":1585876782448,"metadata":{"connectionId":7,"message":{"seq":13,"type":"response","request_seq":7,"command":"disconnect","success":true,"body":{}}},"level":0}
      {"tag":"dap.send","timestamp":1585876787337,"metadata":{"connectionId":7,"message":{"seq":14,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"performance":[{"operation":"launch","totalTime":10005.7,"max":10005.7,"avg":10005.7,"stddev":null,"count":1,"failed":0,"errors":[]},{"operation":"disconnect","totalTime":0.7,"max":0.7,"avg":0.7,"stddev":null,"count":1,"failed":0,"errors":[]}]}}}},"level":0}
    </code>
    </details>

**Comment by roblourens** [comment]
Oh yes, to do this you will also need to install the https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-companion extension. @connor4312 is that step called out in documentation somewhere? 

Also just to be sure, before you set the usePreview settings, do you have the "Debugger for Chrome" extension installed on the remote or the local machine? Should be installed locally.

**Comment by finite-light** [comment]
Well, I installed `debugger-for-chrome` in remote before, this should be why it doesn't work. 

I add the following settings in `.vscode/settings.json`, now it works well!
  ```json
  {
    "remote.extensionKind": {
      "msjsdiag.debugger-for-chrome": "ui"
    }
  }
  ```

Thanks for your kind help!

**Comment by roblourens** [comment]
That should be the default and you shouldn't need the setting, but I'm glad it's working now!

**Comment by finite-light** [comment]
Yes, I used `"msjsdiag.debugger-for-chrome": "workspace"` in the global settings a long time ago, because the plugin prompted me to install in the remote, and I didn’t hold back the temptation...
