### ISSUE TITLE
breakpoint fly 

### ISSUE THREAD

**Issue by FishOrBear** [microsoft/vscode-chrome-debug#998]
[vscode-chrome-debug.zip](https://github.com/microsoft/vscode-chrome-debug/files/4453584/vscode-chrome-debug.zip)

- VS Code Version:1.44 1.43
- Win10

I don't have this problem when installing 4.11.7, but if you install 4.12. * This problem will occur.
I use TypeScript 3.8.3 + Webpack4

![chrome-debug-bug](https://user-images.githubusercontent.com/19372111/78849480-32193180-7a47-11ea-9b08-f1f71c0e957d.gif)

**Comment by roblourens** [comment]
Could you try this with our new debugger implementation?  It fixes lots of bugs in this area. https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by FishOrBear** [comment]
`use v3' caused the page to load very slowly.

![bug](https://user-images.githubusercontent.com/19372111/79045671-df09cf00-7c3e-11ea-84f1-f0329253e012.gif)

**Comment by connor4312** [comment]
The slow-loading issue in the new debugger (which is now the default) should be fixed. If you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).
