### ISSUE TITLE
SourceMap doesn't work for some modules

### ISSUE THREAD

**Issue by GuillaumeDesforges** [microsoft/vscode-chrome-debug#999]
- VS Code Version: Insider 1.45 (as of 12/04/2020)
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Clone my project https://github.com/GuillaumeDesforges/pixijs-typescript-starter
2. `npm install`
3. Open folder with VS Code, set a breakpoint on line 5 of index.ts : https://github.com/GuillaumeDesforges/pixijs-typescript-starter/blob/master/src/index.ts#L5
4. I'm using Remote Development so I had to map remote port 3000 to localhost 3000
5. Launch the "Complete development" launch config in VS Code
6. The breakpoint will normally pause
7. Use the "Go inside" step

I get the error

```
Unable to open 'resource-loader.esm.js': Unable to read file 'vscode-remote://ssh-remote+poseideep/home/arsleust/pixijs-typescript-starter/dist/node_modules/node_modules/resource-loader/dist/resource-loader.esm.js' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+poseideep/home/arsleust/pixijs-typescript-starter/dist/node_modules/node_modules/resource-loader/dist/resource-loader.esm.js').
```

I tried a lot of sourceMapPathOverrides, nothing worked...

**Comment by roblourens** [comment]
I can repro but I see that you have found our new debugger implementation that you are using for the server. This works for me if I also use the new debugger for the client side. You can do this by changing the "type" in the launch config to "pwa-chrome". You will also have to install this extension to do this in remote: "JavaScript Debugger Companion Extension"

**Comment by GuillaumeDesforges** [comment]
`type: "pwa-chrome"` fixed it, many thanks.
